### ISSUE TITLE
install ANts

### ISSUE THREAD

**Issue by stu5** [ANTsX/ANTs#1000]
What are the steps or procedures for installing ANTS for Ubuntu or Windows? Can you post a pdf or link about the installation?
![image](https://user-images.githubusercontent.com/53066495/81627142-1b903c80-9430-11ea-9d0e-d1b94af7f351.png)
this process can ok？

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

There's not much Windows support. I'd use Docker if you can.
