### ISSUE TITLE
Mouse brain T2 segmentation

### ISSUE THREAD

**Issue by paulrowley** [ANTsX/ANTs#1001]
I’m doing some mouse brain MRI segmentation. Specifically, I hope to segment and compute hemispheric parenchymal volumes (minus ventricles) in mouse brains based on 3D T2 acquisitions at 4.7 T. I have reconstructed them to be 0.23 mm isotropic. Importantly, half of the samples are from mice that are lesioned via hypoxic-ischemic injury, so I do not think it is feasible to use prior probability masks for segmentation due to gross differences in morphology after injury.

I have tried several algorithms for segmentation, one of which is ANTS Atropos N4. The segmentation results suggest that it has difficulty differentiating between cortical grey matter and ventricles due to similarities in intensity, at least with the parameters I have used so far:

antsAtroposN4.sh -d 3 -a sample_T2.nii.gz -x sample_mask.nii.gz -c 4 -o sample_T2

Does anyone have any suggestions on how to overcome this or alternative approaches?

Thanks in advance for your thoughts.
<img width="546" alt="segmentation_ex" src="https://user-images.githubusercontent.com/52928356/81736171-c702b680-945b-11ea-950a-8e774c8e1288.png">
<img width="546" alt="T2_mouse_example" src="https://user-images.githubusercontent.com/52928356/81736182-cb2ed400-945b-11ea-8030-f3c569bc0220.png">

**Comment by ntustison** [comment]
Yeah, ``antsAtroposN4.sh`` was not designed for small animal segmentation and the lack of contrast is going to make intensity-based segmentation difficult.  You might want to use a registration-based approach where you use something like the Waxholm atlas at Duke to warp labels to your subjects of interest.  In fact, you might want to consult some of the papers from that group who have done quite a bit of adaptation of ANTs to mouse brains.

**Comment by gdevenyi** [comment]
The mouse imaging center has a bunch of atlases and tools as well: https://github.com/Mouse-Imaging-Centre

**Comment by paulrowley** [comment]
Thank you for the response. I did as you recommended.

I roughly aligned my T2 with the segmentation from Waxholm (via affineScalarVolume) and then resampled my data to the resolution of the atlas (256X512X256 0.04 isotropic) (attached).

Then I used the following command to warp the atlas T2 to my data using the following command:

fixed_img_1=${subj_dir}/${subjID}_reo_WHS_1.nii.gz
moving_img_1=${atlas}/canon_T2star_half_rez.nii
segmentation=WHS_atlas_v0.5.1/Data/half_rez/WHS_0.5_Labels.nii

ANTS 3 -m PR[$fixed_img_1,$moving_img_1,1,4]  -o ${subjID}_template_ANTS_PR.nii -i 10x20x5  -r Gauss[3,0] -t SyN[0.25] --affine-metric-type CC --number-of-affine-iterations 1000x1000x1000
antsApplyTransforms -d 3 -r $fixed_img_1 -o [${subjID}_composed_transform.nii.gz,1] -t ${subjID}_template_ANTS_PRWarp.nii -t ${subjID}_template_ANTS_PRAffine.txt
antsApplyTransforms -d 3 -r $fixed_img_1 -i $segmentation -o ${subjID}_segmentation.nii.gz -t ${subjID}_composed_transform.nii.gz -n NearestNeighbor

Other than more closely aligning the T2 and unwarped segmentation prior to running ANTS, do you have any suggestions on how to improve the warped segmentation (attached) at the end?

Thanks in advance.

Paul
[cid:D16F341D-BCBC-4F08-9E77-852A4A59E287]
[cid:0D658AC7-9C66-47A4-84EA-3176B3496FEA]


On May 12, 2020, at 14:39, Nick Tustison <notifications@github.com<mailto:notifications@github.com>> wrote:



Yeah, antsAtroposN4.sh was not designed for small animal segmentation and the lack of contrast is going to make intensity-based segmentation difficult. You might want to use a registration-based approach where you use something like the Waxholm atlas at Duke to warp labels to your subjects of interest. In fact, you might want to consult some of the papers from that group who have done quite a bit of adaptation of ANTs to mouse brains.

**Comment by ntustison** [comment]
I don't see any attachment.  And please start with the simpler script ``antsRegistrationSyNQuick.sh`` and let's start from those results.

**Comment by paulrowley** [comment]
Thanks for letting me know and for your help. I have attached the missing screenshots here. I'll try using that simpler script.

<img width="2160" alt="Screen Shot 2020-05-13 at 12 21 50" src="https://user-images.githubusercontent.com/52928356/81975425-9dc56000-95ec-11ea-8340-90814db3f364.png">
<img width="1625" alt="Screen Shot 2020-05-13 at 08 14 10" src="https://user-images.githubusercontent.com/52928356/81975435-a322aa80-95ec-11ea-8b74-71bb3e2ebb3e.png">

**Comment by ntustison** [comment]
Yeah, those are garbage results.  We should definitely be able to do better.  Please start with the scripts and come back once you get those results.

**Comment by paulrowley** [comment]
Sounds good - thank you for the feedback / reassurance.

On May 14, 2020, at 14:14, Nick Tustison <notifications@github.com<mailto:notifications@github.com>> wrote:



Yeah, those are garbage results. We should definitely be able to do better. Please start with the scripts and come back once you get those results.

**Comment by paulrowley** [comment]
Hi Nick,
As suggested, I used the following code:

moving_img_1=$Atlas/canon_T2star_half_rez.nii
fixed_img_1=$subj_dir/${subjID}_highres.nii.gz
antsRegistrationSyN.sh -d 3 -f $fixed_img_1 -m $moving_img_1 -o WHS_

I have attached screenshots of each input image as well as the warped atlas overlaying the fixed image. It looks better to me. What do you think? What would you suggest for next steps for transforming the labels nifti file to segment ROIs?


Thanks.

Paul
<img width="1307" alt="Screen Shot 2020-05-15 at 07 37 41" src="https://user-images.githubusercontent.com/52928356/82051369-589e3e00-967f-11ea-857a-9157ad9486cd.png">
<img width="751" alt="Screen Shot 2020-05-15 at 07 36 56" src="https://user-images.githubusercontent.com/52928356/82051340-4cb27c00-967f-11ea-978a-f19d0689fa78.png">
<img width="1407" alt="Screen Shot 2020-05-15 at 07 37 32" src="https://user-images.githubusercontent.com/52928356/82051361-55a34d80-967f-11ea-9a43-1d7e08864a97.png">

**Comment by ntustison** [comment]
You can use the transforms to warp the labels to your mouse brain.  

```
$ antsApplyTransforms -d 3 -v 1 -i ${labels} -r ${fixed_img_1} -o ${labelsWarped} -n GenericLabel -t WHS1Warp.nii.gz -t WHS0GenericAffine.mat
```

**Comment by paulrowley** [comment]
Thank you - I warped the labels to the mouse brain with nearest neighbor interpolation and got the attached results.

$ antsApplyTransforms -d 3 -v 1 -i ${labels} -r ${fixed_img_1} -o ${labelsWarped} -n NearestNeighbor -t WHS_1Warp.nii.gz -t WHS_0GenericAffine.mat

A big improvement. Are there any tweaks in transformation parameters or additional processing you'd suggest to optimize the results?

<img width="1478" alt="Screen Shot 2020-05-15 at 10 20 32" src="https://user-images.githubusercontent.com/52928356/82067524-775bff00-9696-11ea-8f4a-8b6303f6431b.png">

**Comment by ntustison** [comment]
You could try antsRegistrationSyN.sh but that will take longer.  You’re the one that ultimately is to decide if the results are “good enough.”  So why don’t you run a few more subjects through and see if there are any systematic improvements you’d like to see.  Once you have those specifics, we’ll be in a better position to offer advice.
