### ISSUE TITLE
ANTs build fails with missing `ANTS_VERSION_*` when built from commit archive, but not from checkout.

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#1002]
**When did the error occur?**
[x] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: Gentoo Linux
 - OS version: rolling release
 - Type of system: Desktop
 
**ANTs version**

**Build configuration and logs**
 
This is the full [build.log](https://github.com/ANTsX/ANTs/files/4632031/build.log).

**Additional context**
Diff for the missing variables looks identical in the commit archive and checkout version:

```
silenthost /var/tmp/portage/sci-biology/ants-2.3.1_p20191013 # ag ANTS_VERSION work/ANTs-f78b2d4a382d3090230641b5ade5da28962dad04/
work/ANTs-f78b2d4a382d3090230641b5ade5da28962dad04/Examples/ANTsVersion.cxx
43:    return ANTS_VERSION_MAJOR;
47:    return ANTS_VERSION_MINOR;
51:    return ANTS_VERSION_PATCH;
59:    static const std::string v( ANTS_VERSION );

work/ANTs-f78b2d4a382d3090230641b5ade5da28962dad04/Examples/CMakeLists.txt
31:    SOVERSION ${ANTS_VERSION_MAJOR}  VERSION ${${PROJECT_NAME}_VERSION})
55:    SOVERSION ${ANTS_VERSION_MAJOR}  VERSION ${${PROJECT_NAME}_VERSION})

work/ANTs-f78b2d4a382d3090230641b5ade5da28962dad04/ANTsVersionConfig.h.in
19:#define ANTS_VERSION_MAJOR @ANTS_VERSION_MAJOR@
20:#define ANTS_VERSION_MINOR @ANTS_VERSION_MINOR@
21:#define ANTS_VERSION_PATCH @ANTS_VERSION_PATCH@
22:#define ANTS_VERSION_TWEAK @ANTS_VERSION_TWEAK@
23:#define ANTS_VERSION "@ANTS_VERSION@"
silenthost /var/tmp/portage/sci-biology/ants-2.3.1_p20191013 # ag ANTS_VERSION ~/sci_ants-2.3.1_p20191013/work/ants-2.3.1_p20191013
/root/sci_ants-2.3.1_p20191013/work/ants-2.3.1_p20191013/Examples/ANTsVersion.cxx
43:    return ANTS_VERSION_MAJOR;
47:    return ANTS_VERSION_MINOR;
51:    return ANTS_VERSION_PATCH;
59:    static const std::string v( ANTS_VERSION );

/root/sci_ants-2.3.1_p20191013/work/ants-2.3.1_p20191013/Examples/CMakeLists.txt
31:    SOVERSION ${ANTS_VERSION_MAJOR}  VERSION ${${PROJECT_NAME}_VERSION})
55:    SOVERSION ${ANTS_VERSION_MAJOR}  VERSION ${${PROJECT_NAME}_VERSION})

/root/sci_ants-2.3.1_p20191013/work/ants-2.3.1_p20191013/ANTsVersionConfig.h.in
19:#define ANTS_VERSION_MAJOR @ANTS_VERSION_MAJOR@
20:#define ANTS_VERSION_MINOR @ANTS_VERSION_MINOR@
21:#define ANTS_VERSION_PATCH @ANTS_VERSION_PATCH@
22:#define ANTS_VERSION_TWEAK @ANTS_VERSION_TWEAK@
23:#define ANTS_VERSION "@ANTS_VERSION@"
```

**Comment by cookpa** [comment]
Does this hold true for the latest code? The hash in your logs appears to be from last year.

**Comment by TheChymera** [comment]
@cookpa this is one of the versions we currently maintain, so I was looking to update its source code distribution specifically. Tarballs are easier for us to reposit than entire git trees.

In any case, to answer your question, the current HEAD fails with what appears to be a completely different build error, possibly better addressed in a separate issue: [build.log](https://github.com/ANTsX/ANTs/files/4632976/build.log)

Do you have any inkling why the version error I encounter may be happening specifically with the tarball? Where would it be getting the version from?

**Comment by cookpa** [comment]
I think it's because CMake is using git to get the version information, and that is failing when the source is not a git repository. 

It now sets the version numbers to 0.0.0.0, and there's an optional CMake variable ANTS_SNAPSHOT_VERSION where the user can input the hash or release tag of their tarball at config time. This allows the executables to have version information when compiled from a tarball. 

Here's the PR where this change was made, if you want to try to patch your version. 

https://github.com/ANTsX/ANTs/pull/911/files

**Comment by TheChymera** [comment]
@cookpa thank you :)
