### ISSUE TITLE
Using 4D nifti file in antsApplyTransforms

### ISSUE THREAD

**Issue by renilmathew** [ANTsX/ANTs#1004]
Hey,
Trying to use 4D file as antsApplyTransform input file. Which is to be done across subjects and trails. Successfully estimated the transformation using antsRegistrationSyNQuick on mean EPI image of individual subjects. For the further analysis, I want to use the estimated files on all the nifti files of each subject.
Inside the 'for' loop 

antsApplyTransforms -d 3 -e 3 -i 4D_nifti.nii -o output.nii -r $referencepath/template.nii -n linear -t $warpPath/out1Warp.nii.gz -t $warpPath/out0GenericAffine.mat

If not the 4D file, is it possible use a wildcard (*) as input to select all the 3D nifti files together.

Error shown: 52 segmentation fault (core dumped) antsapplytransforms

Thanks,
R

ANTs Version: 2.3.3.dev161-ge0d77
On windows, Ubuntu bash 16.04.

**Comment by cookpa** [comment]
Thanks can you please run with —verbose?

Sent from my iPhone

On May 25, 2020, at 12:20 PM, Rey_Matt <notifications@github.com> wrote:

﻿

Hey,
Trying to use 4D file as antsApplyTransform input file. Which is to be done across subjects and trails. Successfully estimated the transformation using antsRegistrationSyNQuick on mean EPI image of individual subjects. For the further analysis, I want to use the estimated files on all the nifti files of each subject.
Inside the 'for' loop

antsApplyTransforms -d 3 -e 3 -i 4D_nifti.nii -o output.nii -r $referencepath/template.nii -n linear -t $warpPath/out1Warp.nii.gz -t $warpPath/out0GenericAffine.mat

If not the 4D file, is it possible use a wildcard (*) as input to select all the 3D nifti files together.

Error shown: 52 segmentation fault (core dumped) antsapplytransforms

Thanks,
R

ANTs Version: 2.3.3.dev161-ge0d77
On windows, Ubuntu bash 16.04.

**Comment by renilmathew** [comment]
Used the debug. Now the error is "/s1066/EPI1/uf1066-0012-00220-000220-01.nii: cannot execute binary file: Exec format error"

**Comment by renilmathew** [comment]
![Capture](https://user-images.githubusercontent.com/37015938/82894756-60999000-9f53-11ea-91ca-0e7928073f41.PNG)

**Comment by cookpa** [comment]
Can you run the same call (the first the line as it is printed above), and add `--verbose`? And then post the complete terminal output.

**Comment by renilmathew** [comment]
![apply](https://user-images.githubusercontent.com/37015938/82919734-b6336400-9f76-11ea-8659-354e98834f57.PNG)
The above error was shown after applying transformation to 219 of 220.

**Comment by cookpa** [comment]
You are still running your own wrapper script, we need to isolate the antsApplyTransforms call. In the first screen cap you had debug on so that it printed the exact antsApplyTransforms call. Please run that directly in the shell, with all the variables expanded, and verbose on, then paste the command as run plus all the output here. Text is better than screen shots. If it's really a lot, you can paste into a text file and drop it here.
