### ISSUE TITLE
Paediatric Template Creation

### ISSUE THREAD

**Issue by sankalp492** [ANTsX/ANTs#1005]
Dear All,

I have a cohort of 55 pediatric subjects(age 7-14 years) and i want to calculate cortical thickness and gyrification index via ANTs. Can anyone suggest me how to create a pediatric template using ANTs which can be further used for brain extraction and calculation of cortical thickness and gyrification.
Thank you

**Comment by ntustison** [comment]
Have you looked at [these examples](https://github.com/ntustison/TemplateBuildingExample)?
