### ISSUE TITLE
LabelGeometryMeasures : Eccentricity

### ISSUE THREAD

**Issue by ArthurJ1** [ANTsX/ANTs#1006]
Hi everyone.
I would like to make shape measurements on masks segmented manually. I found that the `LabelGeometryMeasures` command was very useful for obtaining interesting metrics such as the `Elongation` and `Eccentricity` of the labeled areas.
I wanted to check how these two metrics were calculated. It seems to me that the `Elongation` is equal to the `AxesLength_y / AxesLength_x` ratio, however I cannot understand how does the `Eccentricity` is calculated.
Could someone enlighten me please?

**Comment by cookpa** [comment]
These measures are all derived from the ITK [LabelGeometryImageFilter](https://itk.org/Doxygen/html/classitk_1_1LabelGeometryImageFilter.html)

https://www.insight-journal.org/browse/publication/301

**Comment by dorianps** [comment]
I have been wanting to know this as well, and that ITK page is not very
informative to find the pdf. Here is the direct link I found:
http://insight-journal.org/midas/bitstream/view/9290

**Comment by dorianps** [comment]
Just in case, another explanation of many shape features with visual
examples:
http://www.cyto.purdue.edu/cdroms/micro2/content/education/wirth10.pdf

**Comment by ArthurJ1** [comment]
Thanks a lot for your answers.
 @dorianps I had also found the "Shape Analysis
& Measurement"  ppt from M. A. Wirth yet I found that the definitions of the elongation and eccentricity metrics were different from those proposed by ITK.

**Comment by cookpa** [comment]
It's nice to have theoretical background but the filter is the definitive source for the ANTs program. If the Insight Journal paper doesn't provide the answers, I would recommend asking on the ITK Discourse site.
