### ISSUE TITLE
resource requirements for buildtemplateparallel.sh

### ISSUE THREAD

**Issue by noah10** [ANTsX/ANTs#1007]
We recently ran the following buildtemplateparallel command:

`/usr/lib/ants/buildtemplateparallel.sh -m 30x90x20 -r 1 -g 0.25 -i 4 -t GR -s CC -d 3 -o btp1_ -c 2 -n 1 -j 96 -z /flywheel/v0/input/template/btp_test_template.nii.gz subj-*-*_MPRAGE_reoriented_upsampled.nii.gz`

...and found that it needed a little less than 3TB of disk space and took about 30 hours to run when given 10 scans. We want to run this same command on 245 scans. What are some reasonable estimates for the amount of disk space we would need to configure and the amount of time we might expect it to run? We're using v2.1.0 of ANTs.

**Comment by cookpa** [comment]
What is the image size? (output of PrintHeader <image> 2)

**Comment by noah10** [comment]
351x447x511

**Comment by cookpa** [comment]
OK. That's a big grid and will definitely use a lot of disk space. You need to keep copies of the bias-corrected input data, the working template, and two warp fields for every subject's pairwise registration. The warp fields are the largest files as they are 3D vectors.

buildtemplateparallel.sh uses ANTS for registration, which stores everything as double. It also backs up the output for each iteration. You can turn off output backup by using `antsMultivariateTemplateConstruction.sh`, or you can comment it out in your script.

Other than that, disk space can become inflated if processes are failing. If there are any core files in your output folder, it can increase the size dramatically.

For the run time, there's various ways to speed things up by running fewer iterations at full resolution, changing the metric to MI, or multi-threading. You could start by multi-threading, which won't help you with your full set of subjects but can help test on your subset more efficiently.

You can use multiple threads by setting the ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS variable. With `-c 2 -j 96`, the pexec script will try to run up to 96 parallel jobs. If you have 96 cores, you can set something like `export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=8` to run your 10 subjects with `-c 2 -j 10`.

**Comment by noah10** [comment]
Thanks - we'll try out these suggestions. Am I right in thinking that if we made no changes at all we could expect both disk and compute time to grow linearly with the number of scans?

**Comment by cookpa** [comment]
Compute time will depend on how many jobs you can run in parallel. With 96 cores, you should be able to run more subjects in about the same time, but once you pass 96 it will have to run a second round of registrations, which will double the time.

Disk space should grow linearly with the number of subjects.
