### ISSUE TITLE
SyNMN - Multivariate Analysis

### ISSUE THREAD

**Issue by sahjiro** [ANTsX/ANTs#1008]
Hi,
I red the "Multivariate Analysis of Structural and Diffusion Imaging in Traumatic Brain Injuty, Avants et al" paper (https://pubmed.ncbi.nlm.nih.gov/18995188/). This paper is very interesting for my internship because I would like to do something similar. I was searching in the documentation of ANTs if there is an option for using SyNMN while doing registration but I can't find anything. Has someone an idea where I can find this option (if it actually exists)?
Thank you in advance!!

**Comment by stnava** [comment]
as you see from the paper - the method is quite old.   its implementation has not survived in the current incarnation of ants.  however, you could approximate it with some of the multivariate registration features illustrated here:  https://github.com/stnava/structuralFunctionalJointRegistration
  and in other ants documentation.

**Comment by sahjiro** [comment]
Okay, thank you very much for your reply! I will have a deep look at this joint structural and functional registration.
Concerning the other ants documentation, are you thinking about functions in particular that could be helpful?

**Comment by sahjiro** [comment]
Hi,

I had a deep look at what you sent me last time and it is very interesting, thank you!!
I am trying to adapt your script to my data (T1, FA, QSM). My goal is to combine these 3 modalities to improve targeting for DBS.
To do so, I have a few more questions concerning the metrics part, if you don't mind.

- I added two terms in my metrics list : one considering the FA and the other one considering QSM. In your example, you use Mattes metric but I was wondering if you have any idea what metrics could be more appropriate in my case? 

- Moreover, in the documentation, I red that : "_Each multivariate metric needs 5 entries: name of metric, fixed, moving, weight, samplingParam_". I believed that the sum of the weights should be one. But seeing your example I wondered if this thought was correct given the fact that you use 2 metrics with a weight equal to one in both case. 

- My last question concerns again the arguments for multivariate extras : I am not sure to understand what represent the samplingParam: would it be possible to have a better understanding of this parameter? Is it the parameter that permits to describe the metric (region radius for CC, nb of bins for MI)?

Thank you very much in advance for your answer!

**Comment by stnava** [comment]
* maybe CC
* the sum can be whatever you want but keep the weights positive 
* yes

**Comment by sahjiro** [comment]
Okay, thank you very much for your reply!

**Comment by sahjiro** [comment]
Hi,
In your script, you are using the multivariate_extras argument in antsRegistration. I have already tried to use it to see what was the effects on the registration of my volumes. 
To have a better understanding I was wondering if you'd written a paper about it. In deed, I would like to understand how this option is integrated in the function.
If such a paper exists, could it be possible to have the link or the references?
Thank you in advance!

**Comment by stnava** [comment]
here is one paper:

https://pubmed.ncbi.nlm.nih.gov/18995188/

and this presents an additional obvious application:

https://onlinelibrary.wiley.com/doi/abs/10.1002/hipo.20619?casa_token=33leIbjkCfQAAAAA:cYriuBHjz3RDrIBHvuRTWL6WvMyh26EH9gDT2YJNN_CqNGFeD-HTr8PoYgFfYFJjgi0sjILhzWGEDAPD

generally speaking, the idea is:

* one metric may be good at matching feature X 

* another metric may be good at matching feature Y 

* combining both metrics can help both X and Y

the idea is not specific to ANTs

https://en.wikipedia.org/wiki/Multi-objective_optimization
