### ISSUE TITLE
Weird interruption using antsRegistrationSyN.sh

### ISSUE THREAD

**Issue by younghoo** [ANTsX/ANTs#1011]
Dear experts,

I made a simple registration between individual T1 image and the MNI standard template and this is my commands ( ANTs version 2.2.0, Compiled: Nov 17 2017 10:41:53):

bash ${ANTSPATH}/antsRegistrationSyN.sh -d 3 -n 1 -f MNI.nii.gz -m T1.nii.gz -o T12MNI -x MNImask.nii.gz

I worked in an SEG environment and submit the above commands for each subject.

My problem is that: in some subjects, there are some interruptions without giving any information. 

The only error message is: "/data/software/ANTsX-2.2/bin/antsRegistrationSyN.sh: line 581: 178857 Killed                  $COMMAND"

More specifically, this interruption seems always in the fourth level of iteration.

This problem is not specific to the dataset and I suspect that it might be caused by memory limit but it gives no such information. I think it may be not caused by ANTs but I hope the experts could give some clues to identify the cause of this problem. Thanks!

**Comment by ntustison** [comment]
Yep, sounds like a memory issue.

**Comment by cookpa** [comment]
Agreed, it sounds like the process is exceeding a memory limitation at full resolution. 

The system might simply kill the process that exceeds the limit, in which case ANTs (or any program) never gets to know that it ran out of available memory, and cannot print any error message to that effect.

Your cluster admins should be able to help you request more memory for your jobs.
