### ISSUE TITLE
Estimating Surface Area

### ISSUE THREAD

**Issue by nm329** [ANTsX/ANTs#1013]
Hello, 

I've been trying to work out the best way to calculate surface area estimates using ANTs. 

Currently, I've generated grey matter volume and cortical thickness maps using ANTs, so I was wondering whether diving the grey matter volume maps by the cortical thickness maps, for each of my subjects, would be an appropriate method of obtaining surface area estimations of the cortex. 

Thank you for your time and help!

**Comment by ntustison** [comment]
``LabelGeometryMeasures`` will give you the surface area for segmentations.

**Comment by nm329** [comment]
Thanks for your quick reply! So is the method I initially suggested not appropriate? I was hoping to get a voxel-wise map of surface area.

Regarding LabelGeometryMeasures, I would like to get surface area estimates from multiple cortical regions. To do this, can I binarize my cortical grey matter maps and then multiply them by a parcellated atlas (e.g. the AAL template), and then run LabelGeometryMeasures on those images. Or do I need to run antsJointLabelFusion to get an accurate surface area estimate?

Thanks a lot!

**Comment by ntustison** [comment]
>> Currently, I've generated grey matter volume and cortical thickness maps using ANTs...

By grey matter volume maps, I assume you mean the gray matter segmentation probability map.   I suppose you could divide it by thickness but I don't see how that gives you a voxelwise surface area.

>> Regarding LabelGeometryMeasures, I would like to get surface area estimates from multiple cortical regions. To do this, can I binarize my cortical grey matter maps and then multiply them by a parcellated atlas (e.g. the AAL template), and then run LabelGeometryMeasures on those images. Or do I need to run antsJointLabelFusion to get an accurate surface area estimate?

Either although the latter would probably be more accurate.

**Comment by nm329** [comment]
**By grey matter volume maps, I assume you mean the gray matter segmentation probability map. I suppose you could divide it by thickness but I don't see how that gives you a voxelwise surface area**

My line of thought was that if each voxel has a value of both grey matter volume and of cortical thickness, then dividing the grey matter volume map by the cortical thickness map would provide some sort of estimate of surface area. 

Though it seems like I've misunderstood what those voxel values actually mean.


Thank you both for your help, I really appreciate it!

**Comment by nm329** [comment]
Just to clarify, that idea of dividing the volume maps by the cortical thickness maps wouldn't produce any meaningful/accurate estimate of surface area?

Also, I've been trying to use antsJointLabelFusion to produce surface area measurements of cortical regions. The regions I'd like to estimate are from the AAL template, which has been registered into MNI space. 

Am I correct in thinking that my -g options would be the MNI template image, and the -l options would be the individual parcellations of the AAL template? So the command would be:

antsJointLabelFusion.sh -d 3 -x or -o Subject1_JFL -t Subject_1_skullstripped_brain.nii.gz -g MNI152_T1_2mm_brain.nii.gz -l Parcel_1.nii.gz -g MNI152_T1_2mm_brain.nii.gz -l Parcel_2.nii.gz -g MNI152_T1_2mm_brain.nii.gz -l Parcel_3.nii.gz -g MNI152_T1_2mm_brain.nii.gz -l Parcel_4.nii.gz etc.... 


Thanks!

**Comment by ntustison** [comment]
>> Just to clarify, that idea of dividing the volume maps by the cortical thickness maps wouldn't produce any meaningful/accurate estimate of surface area?

Yes.

> Am I correct in thinking that my -g options would be the MNI template image, and the -l options would be the individual parcellations of the AAL template?

No, this is a *multi*-atlas-based approach so you would need to have more than one AAL-labeled image.  Each ``-g`` indicates the grayscale image and each ``-l`` corresponds to the labeled image as shown in the example:

```
antsJointLabelFusion.sh -d 3 -t target.nii.gz -o malf \
              -p malfPosteriors%04d.nii.gz \
              -g atlas1.nii.gz -l labels1.nii.gz \
              -g atlas2.nii.gz -l labels2.nii.gz \
              -g atlas3.nii.gz -l labels3.nii.gz
```

**Comment by cookpa** [comment]
The recommended way to resample labels from a single atlas is by using the `-n GenericLabel` option in `antsApplyTransforms`.

**Comment by nm329** [comment]
Right, so instead I would be warping the AAL template into subject space like so:

antsApplyTransforms -d 3 -i AAL_Parcellation.nii.gz -o AAL_in_subject_space.nii.gz -r Subject1_ExtractedBrain0N4.nii.gz -t Subject1_TemplateToSubject0Warp.nii.gz -t Subject1_TemplateToSubject1GenericAffine.mat -n GenericLabel -v 1

And then put the AAL_in_subject_space.nii.gz output file into LabelGeometryMeasures to get the surface area metrics for each parcel?

As the cortex would be parcellated into multiple different regions, e.g. middle frontal gyrus, superior frontal gyrus etc.. would LabelGeometryMeasures be calculating only the outer surface of each parcel (so the pial surface), or would it calculate the surface area of the entire parcel (which would include the surface area of the inner parts of the parcel)?

Thanks!

**Comment by ntustison** [comment]
It calculates the surface area of each labeled region.  You'll see once you run it.

**Comment by nm329** [comment]
Is there a way to get it to only calculate the outer surface of a region?

Thanks!

**Comment by ntustison** [comment]
Unfortunately, no.  The [underlying algorithm](https://www.insight-journal.org/browse/publication/852/1) simply estimates the surface area of a labeled region.  It has no notion of what constitutes an "outer" surface.

**Comment by nm329** [comment]
Ah ok got it. Thanks so much for your help with this!
