### ISSUE TITLE
antsRegistration gives negative convergenceValue and stops

### ISSUE THREAD

**Issue by dyollb** [ANTsX/ANTs#1014]
**Describe the problem**

I am trying to register two rat datasets. Due to relatively large deterioration of the MR images of the second rat, I am trying to align the most important tissues by aligning the segmentation of the brain, spinal cord, and several other landmarks. I am using first using a similarity transform followed by SyN. For the first rat I do not have images of the entire rat (only head to heart).

I am using a MeanSquares metric, but comparing the labels/images directly. Instead I generated the signed distance function to segmented structures. To avoid far-away structures having too much influence I set sdf[sdf>0] = log( sdf[sdf>0] + 1.0 ).

I am seeing two kinds of problems:

a) the convergenceValue is negative (at iteration 10), optimization stops.
if I set the convergenceThreshold to -1000, iteration continues and the convergenceValue flips between negative/positive values. The metric does not seem to decrease.

What could be causing this issue? How can I solve it? I have tried reducing the gradientstep, or using BSplineSyN instead of SyN with little clear indication what helps.

b) when the above problem does not occur, I manage to register structures in the center of the image extent nicely. However, near the image boundaries of the image I cannot get the spinal cord to match. I tried to add padding (fixed and moving) but do not see any improvement from this.

**To Reproduce**

 * The exact command line as it was run:

antsRegistration.exe -d 3 -v 1 -z 0 -o [F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\multimetric_v6_tmp5_] -a 1 -m MeanSquares[F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\bad_rat_lgsdf_starter.nii.gz,F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\good_rat_lgsdf_starter.nii.gz,1.000000,8,Regular,0.5] -t Similarity[0.05] -c [80x80,1e-06,10] -s 2x1vox -f 12x8 -x [None,None] -m MeanSquares[F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\bad_rat_lgsdf_starter.nii.gz,F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\good_rat_lgsdf_starter.nii.gz,0.100000,8,Regular,0.5] -m MeanSquares[F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\bad_rat_lgsdf_sphere_crop.nii.gz,F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\good_rat_lgsdf_sphere_crop.nii.gz,1.000000,8,None,1] -t BSplineSyN[0.05,5,0] -c [120x80x40,1e-06,10] -s 0x0x0vox -f 16x8x4 -x [None,None]

 * The full verbose output:
 
All_Command_lines_OK
Using double precision for computations.
  Reading mask(s).
    Registration stage 0
 file None does not exist . 
      No fixed mask
 file None does not exist . 
      No moving mask
    Registration stage 1
 file None does not exist . 
      No fixed mask
 file None does not exist . 
      No moving mask
  number of levels = 2
  number of levels = 3
  fixed image: F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\bad_rat_lgsdf_starter.nii.gz
  moving image: F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\good_rat_lgsdf_starter.nii.gz
  fixed image: F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\bad_rat_lgsdf_starter.nii.gz
  moving image: F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\good_rat_lgsdf_starter.nii.gz
  fixed image: F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\bad_rat_lgsdf_sphere_crop.nii.gz
  moving image: F:\Data\oSPARC\RatVagus\FirstRat2SecondRat\prealigned\good_rat_lgsdf_sphere_crop.nii.gz
Dimension = 3
Number of stages = 2
Use Histogram Matching false
Winsorize image intensities false
Lower quantile = 0
Upper quantile = 1
Stage 1 State
   Image metric = MeanSquares
     Fixed image = Image (00000213ABF4E460)
  RTTI typeinfo:   class itk::Image<double,3>
  Reference Count: 2
  Modified Time: 1194
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 977
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [550, 550, 800]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [550, 550, 800]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [550, 550, 800]
  Spacing: [0.08, 0.08, 0.08]
  Origin: [-44.9792, 19.0782, -75.2396]
  Direction: 
0.939693 0.0298131 -0.340718
-4.10218e-06 0.996195 0.0871564
0.34202 -0.0818989 0.936117

  IndexToPointMatrix: 
0.0751754 0.00238505 -0.0272575
-3.28174e-07 0.0796956 0.00697251
0.0273616 -0.00655191 0.0748894

  PointToIndexMatrix: 
11.7462 -5.12642e-05 4.27525
0.372664 12.4524 -1.02374
-4.25898 1.08946 11.7015

  Inverse Direction: 
0.939693 -4.10113e-06 0.34202
0.0298131 0.996195 -0.0818989
-0.340718 0.0871564 0.936117

  PixelContainer: 
    ImportImageContainer (00000213ABCC9C70)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,double>
      Reference Count: 1
      Modified Time: 974
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 00000213AC1BB040
      Container manages memory: true
      Size: 242000000
      Capacity: 242000000

     Moving image = Image (00000213ABF5C6A0)
  RTTI typeinfo:   class itk::Image<double,3>
  Reference Count: 2
  Modified Time: 1195
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 1192
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [574, 1000, 552]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [574, 1000, 552]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [574, 1000, 552]
  Spacing: [0.0801688, 0.08, 0.079646]
  Origin: [-23.8149, 34.3873, -0.975077]
  Direction: 
-0.24165 0.337953 -0.909612
0.936972 -0.162527 -0.309303
-0.252366 -0.927024 -0.277378

  IndexToPointMatrix: 
-0.0193728 0.0270362 -0.0724469
0.0751159 -0.0130021 -0.0246348
-0.0202319 -0.0741619 -0.022092

  PointToIndexMatrix: 
-3.01427 11.6875 -3.14793
4.22441 -2.03158 -11.5878
-11.4207 -3.88347 -3.48263

  Inverse Direction: 
-0.24165 0.936972 -0.252366
0.337953 -0.162527 -0.927024
-0.909612 -0.309303 -0.277378

  PixelContainer: 
    ImportImageContainer (00000213ABCC95F0)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,double>
      Reference Count: 1
      Modified Time: 1189
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 000002141F818040
      Container manages memory: true
      Size: 316848000
      Capacity: 316848000

     Weighting = 1
     Sampling strategy = regular
     Number of bins = 32
     Radius = 4
     Sampling percentage  = 0.5
   Transform = Similarity
     Gradient step = 0.05
     Update field sigma (voxel space) = 0
     Total field sigma (voxel space) = 0
     Update field time sigma = 0
     Total field time sigma  = 0
     Number of time indices = 0
     Number of time point samples = 0
Stage 2 State
   Image metric = MeanSquares
     Fixed image = Image (00000213AB87CFC0)
  RTTI typeinfo:   class itk::Image<double,3>
  Reference Count: 2
  Modified Time: 1626
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 1409
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [550, 550, 800]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [550, 550, 800]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [550, 550, 800]
  Spacing: [0.08, 0.08, 0.08]
  Origin: [-44.9792, 19.0782, -75.2396]
  Direction: 
0.939693 0.0298131 -0.340718
-4.10218e-06 0.996195 0.0871564
0.34202 -0.0818989 0.936117

  IndexToPointMatrix: 
0.0751754 0.00238505 -0.0272575
-3.28174e-07 0.0796956 0.00697251
0.0273616 -0.00655191 0.0748894

  PointToIndexMatrix: 
11.7462 -5.12642e-05 4.27525
0.372664 12.4524 -1.02374
-4.25898 1.08946 11.7015

  Inverse Direction: 
0.939693 -4.10113e-06 0.34202
0.0298131 0.996195 -0.0818989
-0.340718 0.0871564 0.936117

  PixelContainer: 
    ImportImageContainer (00000213ABCC8A70)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,double>
      Reference Count: 1
      Modified Time: 1406
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 00000214B6987040
      Container manages memory: true
      Size: 242000000
      Capacity: 242000000

     Moving image = Image (00000213AB8770C0)
  RTTI typeinfo:   class itk::Image<double,3>
  Reference Count: 2
  Modified Time: 1627
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 1624
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [574, 1000, 552]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [574, 1000, 552]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [574, 1000, 552]
  Spacing: [0.0801688, 0.08, 0.079646]
  Origin: [-23.8149, 34.3873, -0.975077]
  Direction: 
-0.24165 0.337953 -0.909612
0.936972 -0.162527 -0.309303
-0.252366 -0.927024 -0.277378

  IndexToPointMatrix: 
-0.0193728 0.0270362 -0.0724469
0.0751159 -0.0130021 -0.0246348
-0.0202319 -0.0741619 -0.022092

  PointToIndexMatrix: 
-3.01427 11.6875 -3.14793
4.22441 -2.03158 -11.5878
-11.4207 -3.88347 -3.48263

  Inverse Direction: 
-0.24165 0.936972 -0.252366
0.337953 -0.162527 -0.927024
-0.909612 -0.309303 -0.277378

  PixelContainer: 
    ImportImageContainer (00000213ABCC8FF0)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,double>
      Reference Count: 1
      Modified Time: 1621
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0000021529FE4040
      Container manages memory: true
      Size: 316848000
      Capacity: 316848000

     Weighting = 0.1
     Sampling strategy = regular
     Number of bins = 32
     Radius = 4
     Sampling percentage  = 0.5
   Transform = BSplineSyN
     Gradient step = 0.05
     Update field sigma (voxel space) = 0
     Total field sigma (voxel space) = 0
     Update field time sigma = 0
     Total field time sigma  = 0
     Number of time indices = 0
     Number of time point samples = 0
Registration using 2 total stages.

Stage 0
  iterations = 80x80
  convergence threshold = 1e-06
  convergence window size = 10
  number of levels = 2
  using the MeanSquares metric (weight = 1)
  Shrink factors (level 1 out of 2): [12, 12, 12]
  Shrink factors (level 2 out of 2): [8, 8, 8]
  smoothing sigmas per level: [2, 1]
  regular sampling (percentage = 0.5)

*** Running Similarity3DTransform registration ***

DIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
 2DIAGNOSTIC,     1, 1.640058415923e-03, 1.797693134862e+308, 6.0833e+00, 6.0833e+00, 
 2DIAGNOSTIC,     2, 1.623406230093e-03, 1.797693134862e+308, 6.1144e+00, 3.1101e-02, 
 2DIAGNOSTIC,     3, 1.597109972609e-03, 1.797693134862e+308, 6.1454e+00, 3.1038e-02, 
 2DIAGNOSTIC,     4, 1.559314261507e-03, 1.797693134862e+308, 6.1766e+00, 3.1212e-02, 
 2DIAGNOSTIC,     5, 1.503349884690e-03, 1.797693134862e+308, 6.2107e+00, 3.4058e-02, 
 2DIAGNOSTIC,     6, 1.406195585141e-03, 1.797693134862e+308, 6.2456e+00, 3.4954e-02, 
 2DIAGNOSTIC,     7, 1.222179836275e-03, 1.797693134862e+308, 6.2802e+00, 3.4505e-02, 
 2DIAGNOSTIC,     8, 1.123241396829e-03, 1.797693134862e+308, 6.3140e+00, 3.3838e-02, 
 2DIAGNOSTIC,     9, 1.113609325289e-03, 1.797693134862e+308, 6.3437e+00, 2.9756e-02, 
 2DIAGNOSTIC,    10, 1.112594716534e-03, 3.023492186209e-02, 6.3824e+00, 3.8661e-02, 
 2DIAGNOSTIC,    11, 1.111756613719e-03, 2.755566015387e-02, 6.4122e+00, 2.9768e-02, 
 2DIAGNOSTIC,    12, 1.109930495236e-03, 2.301010148265e-02, 6.4425e+00, 3.0325e-02, 
 2DIAGNOSTIC,    13, 1.102694105520e-03, 1.748392608298e-02, 6.4962e+00, 5.3730e-02, 
 2DIAGNOSTIC,    14, 1.101245434003e-03, 1.165350457091e-02, 6.5306e+00, 3.4401e-02, 
 2DIAGNOSTIC,    15, 1.100953818544e-03, 6.247251690487e-03, 6.5673e+00, 3.6673e-02, 
 2DIAGNOSTIC,    16, 1.100307010219e-03, 2.143530927102e-03, 6.5972e+00, 2.9860e-02, 
 2DIAGNOSTIC,    17, 1.098930777560e-03, 6.581775460328e-04, 6.6315e+00, 3.4372e-02, 
 2DIAGNOSTIC,    18, 1.098000038012e-03, 4.989028978260e-04, 6.6823e+00, 5.0734e-02, 
 2DIAGNOSTIC,    19, 1.097718666904e-03, 4.253948360006e-04, 6.7128e+00, 3.0578e-02, 
 2DIAGNOSTIC,    20, 1.096140467950e-03, 3.495090992479e-04, 6.7479e+00, 3.5043e-02, 
 2DIAGNOSTIC,    21, 1.095857850144e-03, 2.595478262136e-04, 6.7782e+00, 3.0297e-02, 
 2DIAGNOSTIC,    22, 1.095457712302e-03, 1.736274521907e-04, 6.8082e+00, 3.0055e-02, 
 2DIAGNOSTIC,    23, 1.094126844281e-03, 1.639511020027e-04, 6.8385e+00, 3.0221e-02, 
 2DIAGNOSTIC,    24, 1.085389949337e-03, 2.381132281710e-04, 6.8829e+00, 4.4459e-02, 
 2DIAGNOSTIC,    25, 1.081169798287e-03, 3.243915977831e-04, 6.9174e+00, 3.4493e-02, 
 2DIAGNOSTIC,    26, 1.080660087254e-03, 3.841800322851e-04, 6.9533e+00, 3.5919e-02, 
 2DIAGNOSTIC,    27, 1.080579207759e-03, 4.177631469164e-04, 6.9837e+00, 3.0343e-02, 
 2DIAGNOSTIC,    28, 1.079081123992e-03, 4.303571836386e-04, 7.0181e+00, 3.4396e-02, 
 2DIAGNOSTIC,    29, 1.078415053546e-03, 4.071118028400e-04, 7.0536e+00, 3.5519e-02, 
 2DIAGNOSTIC,    30, 1.077212118914e-03, 3.679709812358e-04, 7.0850e+00, 3.1425e-02, 
 2DIAGNOSTIC,    31, 1.073811194954e-03, 3.254587626453e-04, 7.1212e+00, 3.6173e-02, 
 2DIAGNOSTIC,    32, 1.068506399372e-03, 2.975515480830e-04, 7.1526e+00, 3.1396e-02, 
 2DIAGNOSTIC,    33, 1.065587781403e-03, 2.715220445153e-04, 7.1984e+00, 4.5769e-02, 
 2DIAGNOSTIC,    34, 1.058894937427e-03, 3.298145972757e-04, 7.2382e+00, 3.9809e-02, 
 2DIAGNOSTIC,    35, 1.052849818724e-03, 4.239975525442e-04, 7.2777e+00, 3.9537e-02, 
 2DIAGNOSTIC,    36, 1.050545803848e-03, 4.912881917049e-04, 7.3170e+00, 3.9286e-02, 
 2DIAGNOSTIC,    37, 1.049751505437e-03, 5.140286125070e-04, 7.3519e+00, 3.4917e-02, 
 2DIAGNOSTIC,    38, 1.049593396624e-03, 4.975573382672e-04, 7.3868e+00, 3.4867e-02, 
 2DIAGNOSTIC,    39, 1.049523390350e-03, 4.387879581160e-04, 7.4168e+00, 2.9998e-02, 
 2DIAGNOSTIC,    40, 1.049482253572e-03, 3.476255277746e-04, 7.4522e+00, 3.5383e-02, 
 2DIAGNOSTIC,    41, 1.049437863720e-03, 2.474267664176e-04, 7.4828e+00, 3.0625e-02, 
 2DIAGNOSTIC,    42, 1.049404021064e-03, 1.595822729452e-04, 7.5174e+00, 3.4595e-02, 
 2DIAGNOSTIC,    43, 1.049388819814e-03, 7.646904279357e-05, 7.5538e+00, 3.6420e-02, 
 2DIAGNOSTIC,    44, 1.049388079123e-03, 2.631223007195e-05, 7.5888e+00, 3.4999e-02, 
 2DIAGNOSTIC,    45, 1.049452226732e-03, 8.266416093413e-06, 7.6190e+00, 3.0220e-02, 
 2DIAGNOSTIC,    46, 1.049425472433e-03, 2.571029932626e-06, 7.6494e+00, 3.0391e-02, 
 2DIAGNOSTIC,    47, 1.049335250846e-03, 1.445657082915e-06, 7.6838e+00, 3.4394e-02, 
 2DIAGNOSTIC,    48, 1.049293816314e-03, 1.178035036777e-06, 7.7196e+00, 3.5849e-02, 
DIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
 2DIAGNOSTIC,     1, 1.049397317620e-03, 1.797693134862e+308, 1.4354e+01, 6.6346e+00, 
 2DIAGNOSTIC,     2, 1.048961839898e-03, 1.797693134862e+308, 1.4467e+01, 1.1253e-01, 
 2DIAGNOSTIC,     3, 1.048931815008e-03, 1.797693134862e+308, 1.4583e+01, 1.1664e-01, 
 2DIAGNOSTIC,     4, 1.048914592521e-03, 1.797693134862e+308, 1.4704e+01, 1.2020e-01, 
 2DIAGNOSTIC,     5, 1.048911760598e-03, 1.797693134862e+308, 1.4827e+01, 1.2350e-01, 
 2DIAGNOSTIC,     6, 1.048915369385e-03, 1.797693134862e+308, 1.4937e+01, 1.1026e-01, 
 2DIAGNOSTIC,     7, 1.048917575334e-03, 1.797693134862e+308, 1.5078e+01, 1.4097e-01, 
 2DIAGNOSTIC,     8, 1.048920434151e-03, 1.797693134862e+308, 1.5188e+01, 1.0944e-01, 
 2DIAGNOSTIC,     9, 1.048925750158e-03, 1.797693134862e+308, 1.5283e+01, 9.5496e-02, 
 2DIAGNOSTIC,    10, 1.048930707974e-03, 1.047839618401e-05, 1.5379e+01, 9.5917e-02, 
  Elapsed time (stage 0): 1.9363e+01

Stage 1
  iterations = 120x80x40
  convergence threshold = 1.0000e-06
  convergence window size = 10
  number of levels = 3
  using the MeanSquares metric (weight = 1.0000e-01)
  using the MeanSquares metric (weight = 1.0000e+00)
  Shrink factors (level 1 out of 3): [16, 16, 16]
  Shrink factors (level 2 out of 3): [8, 8, 8]
  Shrink factors (level 3 out of 3): [4, 4, 4]
  smoothing sigmas per level: [0, 0, 0]
  regular sampling (percentage = 5.0000e-01)

*** Running B-spline SyN registration (updateMeshSizeAtBaseLevel = [9, 9, 13], totalMeshSizeAtBaseLevel = [0, 0, 0]) ***

XDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
WDIAGNOSTIC,     1, 6.480512917023e-02, 1.797693134862e+308, 7.8878e-01, 7.8878e-01, 
WDIAGNOSTIC,     2, 6.480489936796e-02, 1.797693134862e+308, 1.5530e+00, 7.6424e-01, 
WDIAGNOSTIC,     3, 6.480466819169e-02, 1.797693134862e+308, 2.3209e+00, 7.6790e-01, 
WDIAGNOSTIC,     4, 6.480445075498e-02, 1.797693134862e+308, 3.0712e+00, 7.5034e-01, 
WDIAGNOSTIC,     5, 6.480424367505e-02, 1.797693134862e+308, 3.8166e+00, 7.4535e-01, 
WDIAGNOSTIC,     6, 6.480403697884e-02, 1.797693134862e+308, 4.5742e+00, 7.5757e-01, 
WDIAGNOSTIC,     7, 6.480384551681e-02, 1.797693134862e+308, 5.3148e+00, 7.4064e-01, 
WDIAGNOSTIC,     8, 6.480366144765e-02, 1.797693134862e+308, 6.0762e+00, 7.6135e-01, 
WDIAGNOSTIC,     9, 6.480348737113e-02, 1.797693134862e+308, 6.8253e+00, 7.4917e-01, 
WDIAGNOSTIC,    10, 6.480333664519e-02, -1.404968050192e-06, 7.5656e+00, 7.4027e-01, 
XDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
WDIAGNOSTIC,     1, 7.206753014222e-02, 1.797693134862e+308, 2.0595e+01, 1.3029e+01, 
WDIAGNOSTIC,     2, 7.206722036399e-02, 1.797693134862e+308, 3.3536e+01, 1.2941e+01, 
WDIAGNOSTIC,     3, 7.207484741759e-02, 1.797693134862e+308, 4.6476e+01, 1.2940e+01, 
WDIAGNOSTIC,     4, 7.207722525504e-02, 1.797693134862e+308, 5.9379e+01, 1.2903e+01, 
WDIAGNOSTIC,     5, 7.208043934742e-02, 1.797693134862e+308, 7.2261e+01, 1.2882e+01, 
WDIAGNOSTIC,     6, 7.208022604208e-02, 1.797693134862e+308, 8.5129e+01, 1.2868e+01, 
WDIAGNOSTIC,     7, 7.207991168178e-02, 1.797693134862e+308, 9.8050e+01, 1.2921e+01, 
WDIAGNOSTIC,     8, 7.208233921600e-02, 1.797693134862e+308, 1.1092e+02, 1.2871e+01, 
WDIAGNOSTIC,     9, 7.208269885546e-02, 1.797693134862e+308, 1.2385e+02, 1.2927e+01, 
WDIAGNOSTIC,    10, 7.208635652246e-02, -1.849089202724e-05, 1.3672e+02, 1.2875e+01, 
XDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
WDIAGNOSTIC,     1, 8.131428270887e-02, 1.797693134862e+308, 5.0699e+02, 3.7027e+02, 
WDIAGNOSTIC,     2, 8.131639083859e-02, 1.797693134862e+308, 8.7684e+02, 3.6985e+02, 
WDIAGNOSTIC,     3, 8.131967716668e-02, 1.797693134862e+308, 1.2499e+03, 3.7303e+02, 
WDIAGNOSTIC,     4, 8.131975701865e-02, 1.797693134862e+308, 1.6206e+03, 3.7076e+02, 
... (stops at iteration 10)
  Elapsed time (stage 1): ...
Total elapsed time: ...

 * Example input data:
Currently the data is relatively large. I can try to reduce it and see if I reproduce the problem. But maybe you have insight into the problem without it already...

**System information (please complete the following information)**
Many issues are specific to a particular system. Please include all information
about your computing environment.

 - OS: Windows
 - OS version: 10
 - Type of system: Desktop

 
**ANTs version information**
ANTs Version: 2.3.3.dev164-g8c61a
Compiled: May  1 2020 15:19:29

**Additional information**
Add any other information that might help solve the problem.

**Comment by gdevenyi** [comment]
Sounds like this? https://github.com/ANTsX/ANTs/commit/3d416475b296321dfe5e6cf905e05f197f4afb52

**Comment by cookpa** [comment]
@gdevenyi the version the OP has doesn't have that bug.

There's a lot going on here. Without seeing the data, here's some general thoughts.

I think the first step is to get a good initialization (-r or antsAI), then a rigid solution, then proceed to Similarity / Affine, and then SyN. 

If the initial overlap is not good, then the gradient descent in the registration has nothing to work with. For normal images it's usually sufficient that the physical spaces roughly overlap. But when working on a distributed set of segmentation labels, the initial alignment might need to be a lot closer.

I very rarely use Similarity, always Affine, so I don't know how well Similarity converges with difficult problems. But getting the rigid result to a reasonable state first is important.

Mean squares is not a very generalizable metric, consider MI. For MSQ you really need to be sure that the diference in the intensities goes to zero as we approach the correct solution.

You might try interactive registration with ITK-SNAP. You can export the initial transform and use it with antsRegistration.

**Comment by gdevenyi** [comment]
@cookpa oops you're right, that's a negative convergence value. Yeah, this sounds like initialization issues. If ants heads off on the wrong path in affine registration space, my failures look like this.

**Comment by dyollb** [comment]
The initial similarity transform is quite reasonable. I guess rigid would be enough though, since both rats are the same size/age. the brain and upper part of the spinal cord are nicely aligned. The problem is that one rat has much more curvature in the spine (a linear transform cannot capture this).

The negative convergence values always occur during the SyN (or BSplineSyN) stage.
The SyN is basically doing nothing in the 10 iterations until it stopes with a negative convergence value.

I will try MI. The mean square difference of the signed distance would go to zero at the object boundaries (for perfect overlap) and it should also decrease as corresponding objects get closer. 

Is there any way I can specify corresponding points as an additional metric in ants? I think it is available in elastiX. I don't mean using icp, but the Euclidean distance between user-defined corresponding points.

**Comment by dyollb** [comment]
> @cookpa oops you're right, that's a negative convergence value. Yeah, this sounds like initialization issues. If ants heads off on the wrong path in affine registration space, my failures look like this.

The similarity transform aligns the brain and upper spinal cord quite well. the fixed lower spinal cord is bent, whereas the moving lower spinal cord is straight and maps outside the fixed image space. I guess this means this region does not contribute to the msqr metric/optimization.
In this case the [Euclidean distance between corresponding points](https://github.com/SuperElastix/elastix/tree/develop/Components/Metrics/CorrespondingPointsEuclideanDistanceMetric) metric would probably be useful. But maybe by placing only few corresponding points (e.g. 1), I can trick the ICP metric in ANTs to bend the lower spinal cord.

I still don't understand why the convergence values are/should be negative. Is this just (lack of) robustness of the convergence estimator?

**Comment by ntustison** [comment]
>> I still don't understand why the convergence values are/should be negative. Is this just (lack of) robustness of the convergence estimator?

[Convergence is not sophisticated](https://itk.org/Doxygen/html/classitk_1_1Function_1_1ConvergenceMonitoringFunction.html).  The iteration window is used to fit a line to the similarity values and the resulting slope is compared against the specified threshold.  If you're iterating between positive and negative values, that means you've hit a local minimum and you're just oscillating in that region.

**Comment by cookpa** [comment]
I've used the PSE metric a few times, usually in combination with MI or CC. You can vary the metric weights between the two.
