### ISSUE TITLE
Create Quality Control images

### ISSUE THREAD

**Issue by egarza** [ANTsX/ANTs#1015]
Greetings,

I would like to know if it's possible to export PNG or JPEG snapshots of a volume in different views, similar to create_verify_image from minctoolkit, in order to create Quality Control pictures in a script. 

Thank you in advance,

Eduardo

**Comment by gdevenyi** [comment]
CreateTiledMosaic

**Comment by gdevenyi** [comment]
https://github.com/CoBrALab/antsRegistration-MAGeT/blob/master/bin/mb_qc.sh

**Comment by egarza** [comment]
Thanks

**Comment by gdevenyi** [comment]
For those he come here looking for a solution, I wrote a more comprehensive one recently:
https://github.com/CoBrALab/minc-toolkit-extras/blob/master/ants_label_qc_image.sh
