### ISSUE TITLE
ANTs version inconsistency

### ISSUE THREAD

**Issue by jhuguetn** [ANTsX/ANTs#1016]
I wanted to install the latest release version, so I cloned ANTs repo at tag '2.3.4' as follows,

```
git clone https://github.com/ANTsX/ANTs.git
cd ANTs/
git checkout tags/2.3.4
```

Everything seemed fine:
```
jhuguet@dev:~/downloads/ANTs> git rev-parse HEAD
29bdfbdf20774b150a303663b2e53e428d397984
jhuguet@dev:~/downloads/ANTs> git status
HEAD detached at 2.3.4
nothing to commit, working directory clean
```

And followed successfully the building procedure stated in the documentation to create binaries and libs. However, when testing my binaries at the end of the road I get the following version number/hash:

```
jhuguet@dev:~/downloads/ANTs> which antsRegistration
/opt/packages/ants/2.3.4/bin/antsRegistration
jhuguet@dev:~/downloads/ANTs> antsRegistration --version
ANTs Version: 2.3.3.dev168-g29bdf
Compiled: Jun  3 2020 22:47:28
```

**Comment by cookpa** [comment]
Thanks for letting us know. I think this was my fault because I did not prefix the tag with "v". I changed it now, so hopefully that will fix the problem.

**Comment by cookpa** [comment]
Update: it does not. I think this is to do with Github making a "lightweight" tag for the release, which CMake does not appear to like. Going to try to fix

**Comment by cookpa** [comment]
OK that appears to do it. The tag has to be an annotated tag. Thanks for finding this @jhuguetn

**Comment by jhuguetn** [comment]
You went faster than I did, I was going to tell you that the tag label change (adding the "v") was not fixing the problem.   
However, making the version tag an "annotated" Git tag instead of a "lightweight" one fixes the issue. I've tested it and can confirm that it works fine now. 

Thanks @cookpa for addressing this issue.
