### ISSUE TITLE
Halfway space registration in ANTs

### ISSUE THREAD

**Issue by eco9** [ANTsX/ANTs#1018]
Hi! I am trying to create an halfway space registration between a T1w and a T2w scan in order to obtain a symmetric registration between the two images. I came across your explanation of the unbiased_pairwise_registration.sh (https://github.com/ANTsX/ANTs/issues/414), but I am not sure if this could be the best solution or if there are other functions that you would recommend for the purpose. 
Many thanks in advance!

**Comment by gdevenyi** [comment]
You could try antsMultivariateTemplateConstruction2.sh between the two images, although with different contrasts it may not work well...

**Comment by cookpa** [comment]
It's been a while since this was updated, but you might be interested in 

https://github.com/ANTsX/ANTs/blob/master/Scripts/unbiased_pairwise_registration.sh

**Comment by cookpa** [comment]
I don't know if there's anything more advanced than `unbiased_pairwise_registration.sh`, which is what I came here to suggest. 

I'm curious about the use case though. What's the application of the symmetric warp?

**Comment by novellisa** [comment]
Dear ANTs experts,

I would like to use your `unbiased_pairwise_registration.sh` in ANTs ver. 2.2.0.dev104-gb43df.

My goal is to linearly register two identical diffusion-weighted MRI volumes from the same subject acquired in different series from the same MRI session. In other words, this is a within-subject registration for images with identical contrast from the same MRI session. For this reason, I prefer just using a rigid+affine half-way registration, without the SyN step, which I think I don't need in my case.

By reading `unbiased_pairwise_registration.sh` it seems to me that the `${prefix}_A_norm_aff.nii.gz` and `${prefix}_B_norm_aff.nii.gz` are respectively my A and B images affine-transformed to the midpoint space (more specifically to A moved to the midpoint space). Do you confirm this? Can I take `*_norm_aff.nii.gz` files as my linearly registered images in the midpoint space?

Thank you so much in advance for any help.
Best.

**Comment by ntustison** [comment]
Yeah, that should be correct.  Did you test it out and see if the results make sense?

**Comment by novellisa** [comment]
Thank you so much for your reply, yes, the results seem to make sense indeed. Best.
