### ISSUE TITLE
Making a deformation symmetric

### ISSUE THREAD

**Issue by dyollb** [ANTsX/ANTs#1020]
**Describe the problem**
I have a displacement field from a hyperelastic deformation, which results in local inversion and self-intersections. I am wondering if I could use SyN or another diffeomorphic registration method to create an invertible deformation field which is as close as possible to the input deformation.

I guess the metric could minimize the mean squares error between the SyN transformation (in the source image) and the input displacements. My deformation field is on a tetrahedral mesh, but I could interpolate it onto an image grid.

Any ideas would be welcome. Thanks

**Comment by ntustison** [comment]
A couple ideas:

* Try ``SmoothDisplacementField``.
* @stnava put something together---probably one of his ``ANTsIntegrate...`` but I've never used it.  
* Another diff. approach I wrote is [here](https://github.com/ntustison/Utilities/blob/master/src/EstimateDiffeomorphism.cxx) but it's not in ANTs.

**Comment by dyollb** [comment]
@ntustison thanks. i will try these suggestions
