### ISSUE TITLE
Registration with QSM image

### ISSUE THREAD

**Issue by sahjiro** [ANTsX/ANTs#1021]
Hi,

For my project, I would like to register two QSM images (from two patients) together and save the deformation field to apply it to other modalities images (such as T1, FA) to better target specific brain areas.

My problem is that when I do the registration between the two volumes, it doesn't work. 
Here is my command line with antspy (I have left the default settings):
_reg = ants.registration(fixed=QSM_01, moving=QSM_02, type_of_transform='SyN')_
 After that, I wanted to check the results, so I did:
_ants.image_write(reg['warpedmovout'], path)_
 Then I opened it with MRView and the image was the exact same as the QSM_01. 
I tried Affine transform but it didn't changed anything. On the other hand, if I threshold the QSM with ants.threshold_image to focus on the specific areas I'm interesting in and then I register the two thresholded volume, the registration works (even though the results aren't that good).

I also have to point out that the registration between two T1 or FA works fine. 

Has someone an idea why it doesn't work and how I could fix this? Could it be because of the properties of the QSM?

Thank you in advance!

**Comment by stnava** [comment]
This issue should be opened at ANTsPy.  In general, if you don't share details ( see the issue templates ) then it's tough to help.
