### ISSUE TITLE
I get some negative values of the Jacobian of the deformation field

### ISSUE THREAD

**Issue by white-hy** [ANTsX/ANTs#1022]
Hi, Dear Author.
I used `antsRegistrationSyN.sh` based on diffeomorphisms to obtain the deformation field. When I calculate the Jacobian determinant of the deformation field, I get some negative values.

1. These negative values mean that folding has occurred, right?
2. Why can't a diffeomorphisms-based algorithm completely avoid folding?

**Comment by ntustison** [comment]
Achieving strictly positive Jacobian values is a theoretical ideal that is limited by such things as the chosen gradient step and image resolution for which all algorithms are susceptible.

**Comment by stnava** [comment]
it is also common for people to calculate the Jacobian incorrectly.   or to use the log-jacobian.   if you use one of the recommended methods, you are not likely to get this issue.

**Comment by gdevenyi** [comment]
Without your call to CreateJacobianDeterminantImage, we cannot determine if you have computed the Jacobian in such a way that negatives are expected.

**Comment by white-hy** [comment]
@ntustison @ntustison @gdevenyi Thank you very very much.

I tried this command.
`CreateJacobianDeterminantImage 3 case1_Syn_1Warp.nii.gz inv_jac.nii.gz 0 0`
Then I got about `50` folding in` 224*144*160(5160960)` positions. Although the folding position was very very few, but it still existed. Is it normal that these very small amounts of folding exist?
Thanks again.

**Comment by white-hy** [comment]
Would you like to answer my question?  The question puzzled me for a long time.
Thank you very much!

**Comment by ntustison** [comment]
My answer above applies to your question

> Achieving strictly positive Jacobian values is a theoretical ideal that is limited by such things as the chosen gradient step and image resolution for which all algorithms are susceptible.

**Comment by white-hy** [comment]
@ntustison 
Thank you very much. I'm going to try more parameters to eliminate the negative Jacques ratio as much as possible
