### ISSUE TITLE
Error message about ResampleImage

### ISSUE THREAD

**Issue by CarolineBao** [ANTsX/ANTs#1024]
I've been getting the following error when running ResampleImage. The file _ambmc_15micron.nii can be found here: https://drive.google.com/file/d/1WP0SoTXcUHCYq-rs8-xesXu9nZnreI47/view?usp=sharing
Deos anyone know where issue is?

**Command**
ResampleImage 3 _ambmc_15micron.nii __ambmc_40micron.nii 0.04x0.04x0.04 size=1 spacing=0 4

**Error Message**
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
../ambmc.sh: line 17: 32152 Aborted                 ResampleImage 3 _ambmc_15micron.nii __ambmc_40micron.nii 0.04x0.04x0.04 size=1 spacing=0 4

ANTs version: 2.3.1.dev37-gf78b2
OS: Gentoo Linux

**Comment by cookpa** [comment]
`ResampleImage` expects an integer array specifying the new voxel dimensions, eg 128x128x64. 

The things in brackets are placeholders, you should enter the numeric code for the option you want. So something like 

`ResampleImage 3 _ambmc_15micron.nii __ambmc_40micron.nii 0.04x0.04x0.04 0 0 4`

to resample the image to 0.04 mm spacing.

**Comment by CarolineBao** [comment]
Thank you! I was able to fix it following your suggestions.
