### ISSUE TITLE
CMake Error at CMakeLists.txt:66

### ISSUE THREAD

**Issue by ekuama** [ANTsX/ANTs#1025]
**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)

**Build environment**
 - OS: [Ubuntu on Windows 10 Pro using WSL 1]
 - OS version: [18.04]
 - Type of system: [Desktop]
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/4784971/CMakeCache.txt)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/4784972/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/4784973/CMakeOutput.log)

Following the instructions from
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Windows-10 and
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

after these lines 
mkdir build install
cd build
ccmake ../ANTs

I get the error
CMake Error at CMakeLists.txt:66 (project):
   No CMAKE_CXX_COMPILER could be found.

   Tell CMake where to find the compiler by setting either the environment
   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
   to the compiler, or to the compiler name if it is in the PATH.

**Comment by stnava** [comment]
The error says you need to install a compiler.

https://linuxconfig.org/how-to-install-gcc-the-c-compiler-on-ubuntu-18-04-bionic-beaver-linux

brian
