### ISSUE TITLE
Windows PATH issue- 'N4BiasFieldCorrection' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by kylerioux** [ANTsX/ANTs#1026]
**Build environment**
Windows 10
 
**ANTs version**
ANTs-2.3.4 (downloaded zip from site- pre built on 2020-06-15)

**Additional context**
I believe my issue has something to do with the PATH/ANTSPATH as I get the following error:
'N4BiasFieldCorrection' is not recognized as an internal or external command,
operable program or batch file.

The path I gave to both PATH and ANTSPATH was to the main directory for what I extracted(img below). 
ie. PATH and ANTSPATH are currently:  C:\Users\myName\Dependencies\ANTs-2.3.4\ANTs-2.3.4\

Should my paths lead somewhere else, or do I have to build ANTS myself? The instructions I have seen for building it myself are for OSX/Linux.
![image](https://user-images.githubusercontent.com/35410495/84908669-beb52100-b082-11ea-99da-a53f637ab6cc.png)

**Comment by cookpa** [comment]
Yes, the path you are showing point to the source. Windows users either build using the Windows Subsystem for Linux, or using Docker. 

Under WSL, you can build using the Linux instructions.

**Comment by kylerioux** [comment]
So I can't just use this pre-built version and point to it?

**Comment by cookpa** [comment]
If you can find binaries for your OS, you can install them. ANTs is open source so anyone is free to build and distribute it under the terms of its license. We've relied on community volunteers for most of our Windows support to date.

In the long term we do want to improve the release system to distribute binaries and containers for different platforms. But for the foreseeable future most users will need to build from source or use one of the community-supported distributions.

**Comment by kylerioux** [comment]
Thank you for the timely responses. It means a lot as I am clearly new to dealing with this type of software haha. Do you think my best bet is to try and use the WSL method you mentioned, or is there somewhere I can find Windows 10 built versions (community supported ones you mentioned)?

**Comment by dorianps** [comment]
Kyle, both Phil and I have created some Docker images that can get you
running very quickly. Check my GitHub account dorianps, it has also Windows
scripts which you just double click.

If you are going for WSL, don't use the old wsl. Wait until you get the May
Windows update 2004, then switch to using wsl2. It is much faster and
everyone is loving working on wsl2 now.

**Comment by dorianps** [comment]
The docker image has all the dependencies needed to run ANTs. You just run
the container and start using ANTs right away. If you need other software
besides ANTs on that container, you need to install them yourself. I.e.,
you can start an interactive shell session on that container, install what
you need, and "commit" the container to make it become a docker image with
your other software in it.

**Comment by kylerioux** [comment]
I can't write a docker COMMIT command in that terminal, or even a sudo command- is that because only ANTs is installed in that image? How do I get all the packages I need in and commit them if I can't even write sudo or other basic commands?

**Comment by dorianps** [comment]
You would need to log in as root in the container, something like docker
run -u 0. The container is built on purpose to work with non-root user to
avoid security flaws.

**Comment by kylerioux** [comment]
to become the root user I attempted the command: su -, but it wants a root user password.  Is that something you would have set? I tried empty password, 'password', and 'root'. I am not able to use the command you mentioned as the docker command is not found.

**Comment by dorianps** [comment]
You can't su from within the container. You need to start the container
itself as root user. Or reconnect with -u 0. There is no password to su.

**Comment by kylerioux** [comment]
Hello Again! I switched to linux to make things easier and build ANTs successfully (all indicators mentioned are there), however I am having trouble with the "Post installation: set environment variables PATH and ANTSPATH" step. I installed it in /home/myname instead of /opt, is that a problem? I can not find the /ANTs/bin folder which I need to add to my PATH

**Comment by cookpa** [comment]
You can install wherever, you should see a bin/ and a lib/ directory under the install prefix.

You have to do the `make install` step before they will appear.
