### ISSUE TITLE
quality control measures

### ISSUE THREAD

**Issue by BIG-S2** [ANTsX/ANTs#1027]
Hello, I want to know are there quality control measures for ants cortical thickness pipeline? I found there is a "Pearson correlation" together with GM, WM, sum of thickness, etc. in the final generated .csv file. Can we threshold that value by using Pearson correlation > threshold? usually how shall we set the threshold? is there any other qc measures? Thank you a lot!

**Comment by ntustison** [comment]
> Can we threshold that value by using Pearson correlation > threshold?

I don't know what this would accomplish.  However, it is not done in practice.

> is there any other qc measures?

Output includes png mosaics that one can quickly inspect.

**Comment by cookpa** [comment]
I wouldn't set a hard threshold on any of the summary measures, but you can use them to look for outliers in a data set.

Segmentation failures are often local, so using an atlas in your template space to get regional thickness lets you look in more detail than the whole-brain average.
