### ISSUE TITLE
Unclear what functionality depends on VTK

### ISSUE THREAD

**Issue by liamtimms** [ANTsX/ANTs#1028]
Hi all, 

I see that VTK is "optional" according to the build instructions (https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS). However, I haven't been able to locate any information in the documentation (which I recognize is a WIP) explaining what exactly is lost by opting not to use VTK in the build process. Have I missed something obvious here? It looks like `ccmake` defaults to `USE_VTK=OFF`  on my system, is that configuration generally recommended?

edit: I should mention I am currently attempting to build the latest release (v2.3.4) rather than using the master branch. 

Thanks.

**Comment by ntustison** [comment]
See [here](https://github.com/ANTsX/ANTs/blob/master/Examples/CMakeLists.txt#L234-L245).  If you don't need those apps, the added VTK dependency isn't worth building.

**Comment by liamtimms** [comment]
@ntustison great thanks, that's exactly the sort of list I was looking for.
