### ISSUE TITLE
Problems enabling BUILD_STYLE_UTILS on ubuntu 19.10 with Cmake 3.13.4

### ISSUE THREAD

**Issue by holderg** [ANTsX/ANTs#1029]
The problem occurs trying to enable BUILD_STYLE_UTILS in cmake.
Trying to generate the make files gives:
 CMake Error at SuperBuild/External_Cppcheck.cmake:56 (ExternalProject_Add):
(base) root@detre-slurm-controller:/share/apps/src/ants/build# 

     /share/apps/src/ants/ANTs-2.3.4/SuperBuild/External_Cppcheck.cmake:67

   when parsing string

     CXX=$CMAKE_CXX_COMPILER{}

   Syntax $CMAKE_CXX_COMPILER{{} is not supported.  Only ${}, $ENV{}, and
   $CACHE{} are allowed.
 Call Stack (most recent call first):
   CMake/SlicerMacroCheckExternalProjectDependency.cmake:69 (include)
   SuperBuild.cmake:224 (SlicerMacroCheckExternalProjectDependency)
   CMakeLists.txt:67 (include)

If you are using system ITK or VTK, please verify you have the correct
versions (see the Wiki link above). If you can, please also attempt a
Superbuild and let us know if that compiles successfully.

**When did the error occur?**
[x ] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: [Ubunu]
 - OS version: [19.10]
 - Type of system: [labtop]
 
   If you are building inside a virtual machine, container, NO, 
   Windows Subsystem for Linux, or other non-native environment, please 
   let us know and include details of both the virtual Linux and the 
   host OS. 
 
**ANTs version**
Specify the release tag or commit hash of the code you are building
from. If you downloaded a snapshot as a ZIP file, please provide the
date of the download.
2.3.4

**Build configuration and logs**
Please attach the following files (relative to your build directory)

  - build.log (the terminal output from make)
  - CMakeCache.txt
  - CMakeFiles/CMakeError.log
  - CMakeFiles/CMakeOutput.log

**Additional context**

**Comment by holderg** [comment]
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/4808457/CMakeCache.txt)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/4808458/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/4808459/CMakeOutput.log)

**Comment by gdevenyi** [comment]
This is a long dead setting that produces nothing useful as far as I know.

**Comment by cookpa** [comment]
ITK uses KWStyle and not cppcheck, so maybe that option is indeed useless. Still, this looks like a typo to me:

```
 CXX=$CMAKE_CXX_COMPILER{}
```

should be 

```
 CXX=${CMAKE_CXX_COMPILER}
```

right? Quick fix, will do later

**Comment by cookpa** [comment]
I can't build style utils because it wants to use `cvs` for KWStyle. I guess this needs more work, but I'll fix the typo.
