### ISSUE TITLE
Velocity field as output in antsRegistration

### ISSUE THREAD

**Issue by andreaurru** [ANTsX/ANTs#1032]
Hello, I was wondering if there is a flag or a specific call in antsRegistration to save, alongside the deformation field, the velocity field when using the TimeVarying transforms. Thank you,

**Comment by ntustison** [comment]
No, there isn't.

**Comment by stnava** [comment]
it used to be written out as Velocity.* -- perhaps no more?

brian

**Comment by ntustison** [comment]
That's [right](https://github.com/ANTsX/ANTs/blob/master/Examples/antsRegistrationTemplateHeader.h#L1420-L1450).  Thanks @stnava

**Comment by andreaurru** [comment]
Thank you for your help. So it is supposed to write it automatically or should I add a specific flag?

**Comment by ntustison** [comment]
I believe it should be automatic.
