### ISSUE TITLE
ANTs Registration

### ISSUE THREAD

**Issue by dain5832** [ANTsX/ANTs#1033]
If you are having problems running ANTs on a particular data set, please use the
"Bugs or other run time problems" template.

If you are having problems compiling or installing ANTs, please use the "build
problems" template.

**Before opening an issue**

Please check the ANTs wiki:

https://github.com/ANTsX/ANTs/wiki

The Github wiki search only covers page titles, but you can do a full
text search by entering into Google:

```
<your search terms> site:https://github.com/ANTsX/ANTs/wiki
```

Please check previous issues on Github at

https://github.com/ANTsX/ANTs/issues

```
is:issue <your search terms>
```

If you find relevant issues but still have questions, please go ahead and create a new issue and include links to the other issues.

If you need to open an issue, you can remove this text before typing your
question. 

Hi I got Brain MR images in nifti format.
(T1CE in axial plane, T2 in sagittal plane)
And I converted the orientation of T1CE images from axial to sagittal by transposing numpy array.
However, when I tried to co-register T2 images to T1CE images,
T2 image is registered to axial T1CE image so images are being distorted.

Any idea why it is happening?
And can you tell me if there's any other way to convert image orientation??

**Comment by stnava** [comment]
You should not mess with the data in that way.   Just register the original images.   

Medical images have meaningful (anatomically defined) physical spaces.  If you want to change those spaces, you have to spend some time understanding what they mean.

**Comment by dain5832** [comment]
I see.
Can you help me to figure out how to convert image orientation?? or any useful sources??

**Comment by stnava** [comment]
you should not "convert" the image orientation.  if you think you need to -
use itk-snap.

brian

**Comment by dain5832** [comment]
Thanks, I'll check it.
