### ISSUE TITLE
Why applying a rigid transform on a tensor do not preserve fiber orientation (after reading/using all the wiki pages information) ?

### ISSUE THREAD

**Issue by valeryozenne** [ANTsX/ANTs#1036]
**To Reproduce**

All the data and the command/script to reproduce the problem is available at the link:
https://filesender.renater.fr/?s=download&token=82a8dc88-e25e-488e-8253-57b7d0757b9d

 * The exact command line is included (command)
 * The full verbose output is included (log.txt). 
 * Example input data is included.
 * The size of the data is small.

**System information)**
 - OS: Ubuntu
 - OS version: 18.04
 - Type of system: [Laptop] 
  
**ANTs version information**
- ANTs Version: 2.3.4.dev172-gc801b
Compiled: Jun 29 2020 13:29:57
- Compiled from source 

**Describe the problem**

I’m looking for some help, I know this topics has been widely covered (sorry) but I didn’t find the solution to my problem. I also would like to first thanks you for updating the wiki. The news pages are really helpful. 

My main objective is to average tensor from different samples. As a simple first test, I start by applying a rigid transform on a tensor (for DTI processing) but the output do not preserve the fiber orientation on my dataset. I'm using a large rotation. I have been trying to do this operation for a while (> 1 year) now but unfortunately I'm not able to make it work. From my understanding, the potential errors are:

- wrong data format (probable) but the data are correctly store in memory as recommanded in [antsDTOrientationTests] and component ordering and intent_code should be ok.
- wrong use of ANTs (likely probable)
- wrong conversation of data to another software for visualization (unlikely probable as triple check)
- other issues

Results:
- Input tensors are correct; deformed image is OK
- Deformed image is aligned but the tensor scalars is OK
- Deformed tensor scalars are correct but the reorientation is WRONG

I added the ground truth fiber orientation and the output of ANTs that significantly differs. I would be really grateful if you could have a look at my dataset. 

Thanks a lot in advance.
Valéry

**Additionnal info**

The script is quite long as it includes lots of verification & figures but the attempt is only to apply a rigid transformation on a tensor.
I'm using MRtrix to visualize the fiber orientation. The script include also some verification on the conversation process. 4D (mrtrix data) -> 5D (ANTs) -> 4D (mrtrix data).
In my sample, fiber orientation (V1) is really simple, it should mostly follow the tangent of the isosurface.

**Comment by cookpa** [comment]
Thanks for the example, it looks like you've ruled out many potential problems. 

For ANTs, the tensor on disk needs to be stored in the voxel coordinate system, such that they can be transformed into ITK physical space by applying the direction cosine matrix. I'm afraid I don't know an easy way to check if this is the case. One thing you can do is to probe individual voxels, eg

```
ImageMath 3 inputFA.nii.gz TensorFA Data/tensor_5_5D.nii.gz
ImageMath 3 pd_x.nii.gz TensorToVectorComponent Data/tensor_5_5D.nii.gz 0
ImageMath 3 pd_y.nii.gz TensorToVectorComponent Data/tensor_5_5D.nii.gz 1
ImageMath 3 pd_z.nii.gz TensorToVectorComponent Data/tensor_5_5D.nii.gz 2
itksnap -g inputFA.nii.gz -o pd_x.nii.gz pd_y.nii.gz pd_z.nii.gz
```

These commands will pull the (x,y,z) components of the principal directions in voxel coordinates, as they are stored on disk. Reorientation will only work correctly if these directions can be correctly oriented into physical space using the direction cosine matrix of the input image (you can get this matrix with `PrintHeader`).

**Comment by valeryozenne** [comment]
Thanks for the indications.

I apply the command. The individual voxel looks correctly oriented in the voxel coordinates (using ITKsnap), for instance, x=45,y=45,z=50 , the x,y,z value seems correct (z high = fiber go up/down), but I cannot confirm the negative or positive value. And the global value of the vector x,y,z is fine. 

Nevertheless, I don't know how to guarantee with 100% accuracy that the : "Reorientation is correctly oriented into physical space using the direction cosine matrix of the input image" 

I fully understand that it is hard to debug,  is my script seems correct ? I never see an example with a rigid transform ? I'm assuming that a specific case of an affine transform. 

Could you give me additional information on the related topics ? 

* If I understand well the (x,y,z) components  (pd_x, pd_y, pd_z) of the principal directions in voxel coordinates extract from the tensor_5_5D.nii.gz  should  (or should not) be same that the value return by the following command of MRtrix  "tensor2metric Data/tensor_5_4D.nii.gz -vector Data/v1_5_initial.nii.gz -num 1 --force"  . The values differ significantly but the I don't undersand why ? The orientation is well displayed in MRtrix (mrview Data/v1_5_initial.nii.gz). And it looks that the value pd_x , pd_y, pd_z describe the exact same pattern.

* No sure if it is relevant, if I load the file "Data/v1_5_initial.nii.gz " and  "pd_z.nii.gz" in itksnap, there are located at the same position, if I load them in 3DSlicer that's not the case , but the fa/mean_bzero/tensor_5D are correctly located in both softwares  before and after deformation, do you have any idea why ?

* Do you have any brut force method to script that could allow me to have the correct orientation? I can review the result. I'm struggling for a while, any method that could work will be really appreciated.

Thanks a lot in advance,
Valéry


** Additionnal info **

Direction Cos Mtx. : 
1  0 0
0 -1 0
0  0 1

**Comment by cookpa** [comment]
Unfortunately, any time you bring in other software to help, you are viewing the result of that software's conventions, which might look correct but still be wrong for ANTs.

To really solve this, you have to go back to the original data and the bvecs file, and know what coordinate system those use. You can try flipping the sign of the bvecs, eg multiplying the x component of each vector by -1 will flip left-right in the tensor orientation. With some trial and error you may be able to find a solution that works for the ANTs registration and reorientation, but be sure to test carefully with different rotations.

The correct solution for ITK might make the tensor orientation appear wrong in other software. You might have to undo whatever coordinate flip you apply in order to export the data back to mrtrix or some other software.

**Comment by valeryozenne** [comment]
Ok, I will try. Do you have any recommandation on the software ?  I have seen that you are using Camino in your example. In practice, do you have for each dataset/studies to solve the software's conventions or just using camino and ANTs, it is just working ? 

I have a script that export that dwi in nifti and the bvalue either in fsl or mrtrix format. I should be able to adapt to use camino.

**Comment by valeryozenne** [comment]
I also have some easier questions to ask: 
* Is it possible to apply transformation on vectors (I have seen an option -e 1 in antsApplyTransforms)   ? 
* Does antsApplyTransforms only move the vector in space without changing the direction like the tensor ? And then we need to reorient them using another function ? 
* Using for instance ,  pd_x.nii.gz pd_y.nii.gz pd_z.nii.gz  , which command should I use to create the vector (in 5D [X,Y, Z,1,3] like the tensor if it is the same convention as time is usually the fourth ) ? 

Thanks in advance for your help.

**Comment by cookpa** [comment]
You can transform vectors but unfortunately there's no ReorientVectorImage. I've been meaning to add one but have not done so because most of my project pipelines reorient tensors.

For making vector images, I think either 4D or 5D images will work as long as you specify `-e 1`, but you'd have to check. In my test repo, I was making 4D because some software insists on that and won't read 5D, although that's what the NIFTI standard says you should do.

I have one idea that might simplify testing. Instead of registering the DT "5" to "6" (and I don't think 6 is included in your upload), how about we make a known rotation and apply that? In ITK-SNAP, you can load a scalar image and then rotate it manually. eg

```
itksnap -g Data/fa_5.nii.gz -o Data/fa_5.nii.gz 
```

If you go to Tools->Registration and select the manual tab, you can apply a precise rotation to the image, then save the transform as an ITK transform that can be used by `antsApplyTransforms`. Then we can see if the reorientation of the tensors is being applied correctly. 

I've been thinking about this problem and reviewing the code a bit. I'm wondering if the image spacing is an issue, as all of my tests have been on human in-vivo data. When I get time (might be a few days), I'll test this out by changing the image header to have 2mm voxels and seeing if that alters the results. I'm just mentioning this idea in case you might want to test it yourself first.

**Comment by valeryozenne** [comment]
Hi,

I have some good and bad news. I follow your indications and made a lot of tests. I use itksnap to test with some basic transform like 90°. Now I'm seeing strange behavior of ANTs. I'm not sure but I start thinking this might be related to ANTs (I bet now on 1% chance). I haven't yet tested with lower resolution data, I have some at 600um and I can try next week. 

You find below a new link with all the code/and script in case you can have a look. I also made a short presentation (only 4 slides) summarizing the examples :

https://filesender.renater.fr/?s=download&token=051b7fa8-0ffc-47aa-8ba4-428bcc6a689f

**Results**

- 90° along X results in good orientation  
- 90° along Y results in wrong orientation for 10 % of the voxels in different location of the images, the other 90% are fine
- 90° along Z results in wrong orientation for 10 % of the voxels in different location of the images, the other 90% are fine
- rigid transform (X,Y,Z, rotation + translation) results in wrong orientation for 50-75 % of the voxels in different location of the images

**To reproduce**

All the data/script are available here (I put everything in different folder), I also add the position "6" in the folder 
There is redundancy in the data but it is for avoiding any mistake, I used separate folder.

https://filesender.renater.fr/?s=download&token=bf64d7ad-b437-4521-96dc-9b97b7225fbc


**Goal**

My goal is to average tensors from different samples after applying rigid + affine + warp on them. Once I solved the rigid issue , I will move to an affine transform them warp. The goal is to extract average metric (fa, adc, fiver orientation), and also do tractography. I have control and specific datasets to compare. This is why I'm asking all these questions. ANTs seems the best software for doing this. Template construction is not an issue even if some data break the "intensity conservation rules".

**Some additional information**

I have three "gold standards" to characterize the output of ANTs:

- my knowledge of cardiac structure: basically, there is a cylindrical symmetry, fiber "turns" in the ventricle and "fall" in some specifc area (at the center and on the border).
- some "rules": for instance, the fibers cannot leave the structure : ANTs output results (in some location) with the fiber orthogonal to the isosurface of the sample at the border location which is unlikely probable.
- an algorithm doing vector reorientation from mrtrix (I'm not saying the mrtrix is true by essence) but the result perfectly match my understanding of the cardiac micro structure. Nevertheless, as pointed by the developer, the function interpolate the vector in space so it means that vector might not be perfectly orthogonal. Nevertheless, it is working really well as shown in the figure and can be considered as true in first approximation.

Thanks in advance for your help,
Valéry

**Comment by valeryozenne** [comment]
Hello, did you had a chance to look at the data ?

**Comment by cookpa** [comment]
I tried varying the spacing but it didn't seem to have an effect. 

I can't understand why the reorientation would be correct for some voxels but not others. Can you notice any patterns about these wrong voxels?

Does the resampling look "correct" before reorientation? The resampled tensors from antsApplyTransforms should retain their original orientation - they will just move location.

**Comment by valeryozenne** [comment]
Thanks for your input. I have made some progress but it still doesn't work. 

**Results and comments regarding previous posts**

My 90° test were not a good idea.

- I can confirm that the resampling look "correct" before reorientation. 
- I found two reasons why the reorientation would be correct for some voxels but not others (it is not yet fully clear): 

  * First, my last claims were wrong, doing a 90 ° along y and z , all voxels are wrong but the vector reorientation is correct is one plane and wrong in the two other planes. 
  * Secondly, it was difficult to see because in some case due to the 90 ° rotation, some computation (I guess, cos and sin in the apply transform) result in 0 and 1 value that help depending of the initial vector orientation. If I pick a 45°, every plane is wrong.  
  ( I  made two tables below summarizing ) 

- Basically as you mentionned before it seems to be a sign issue in the direction or storage ( what you called " the tensor on disk needs to be stored in the voxel coordinate system, such that they can be transformed into ITK physical space by applying the direction cosine matrix"). 

| Plane/Rotation  | 90 X | 90 Y | 90 Z |
| ------------- | ------------- | ------------- | ------------- |
| XY  | OK  | WRONG  | OK  |
| XZ  | OK  | OK  | WRONG  |
| YZ  | OK  | WRONG  | WRONG  |

| Plane/Rotation  | 45 X | 45 Y | 45 Z |
| ------------- | ------------- | ------------- | ------------- |
| XY  | OK  | WRONG  | WRONG  |
| XZ  | OK  | WRONG  | WRONG  |
| YZ  | OK  | WRONG  | WRONG  |

**New approach using Camino**

So I switch my processing to Camino and I saw that the "Direction Cos Mtx. :" were different along the y direction.
Using this new convention I can apply the following z transformation  but still, now rotation along x and y results in wrong orientation:

| Plane/Rotation  | 45 X | 45 Y | 45 Z |
| ------------- | ------------- | ------------- | ------------- |
| XY  | WRONG  | WRONG  | OK  |
| XZ  | WRONG  | WRONG  | OK  |
| YZ  | WRONG  | WRONG  | OK  |  


**Questions**
 
I'm a bit lost now, I will continue my investigation:

1) Do you know if some dwi denoising is doable in camino , I didn't find any command ?
2) I have a question related to antsApplyTransforms , using the data from Camino here is the command

apply linear transform using -e 2
logCmd antsApplyTransforms -d 3 -e 2 -i ${TENSOR_5D_NII} -o ${TENSOR_5D_NII_DEFORMED} -t ${TRANSFORM_ITK}  -r ${REFERENCE}

If you have computed a single affine transform only, you can reorient the tensor at this stage:
logCmd ReorientTensorImage 3 ${TENSOR_5D_NII_DEFORMED} ${TENSOR_5D_NII_REORIENTED} ${TRANSFORM_ITK}

I usely defined REFERENCE as the new image space, for instance if set  REFERENCE=${INITIAL_LOCATION} , the reorientation is correct but if I set  REFERENCE=${NEW_LOCATION} ( b0_moved for instance) the reorientation is wrong. In this case, the antsApplyTransforms doesn't do the job ( in this case: the resampling is not  "correct" before reorientation). What is your recommandation? For my understanding , it should because the new FoV of the deformed tensor should be set from the new location.

Thanks in advance,
Valéry

**Comment by cookpa** [comment]
I appreciate your thoroughness, sorry I've not had time to follow up in more detail. I can answer the questions about the reference space. Because the tensors are stored in the voxel coordinate system of the image, the reference image will affect the final output. The workflow is

1. Tensors in moving voxel space
2. Tensors rotated into physical space using moving header, then back into voxel space of the reference image using the reference header.
3. Tensors resampled into the reference image space

So if you call `antsApplyTransforms` with a different image for `-r` , the output tensors can be different.

**Comment by valeryozenne** [comment]
Hi,

**Update**

I made some progress. I found a solution to my problem. I described quickly the solution if someone needs it. 

**Solution**
It was only one line of code (but 24 days of labor). I need to store the data in RAS format and then ANTS is happy. For mrtrix point of view. It means set the strides as 1,2,3,4 using mrconvert (mrconvert -strides 1,2,3,4 $IN $OUT). I made a lots of tests to be sure, and I can confirm that it is well working.

**New related issue**
Before closing the issue, I have a new related issue (an easy one) when using a compositeTransform in antsApplyTransforms on Tensor (not to ReorienteTensor). I can create a new issue if you prefer? 

**Description**

I have 3 transformations: 
- a rigid transform created in itksnap
- a affine transform from the template creation
- a warp transform from the template creation 


I try to make a composite transform adding rigid + affin + warp and (move+ reoriente my tensor) . It fails. If I do a two steps process (rigid + (move+ reoriente) then a composite of affine+ warp + (move+ reoriente)) it looks fine. Could you tell me what is wrong in my command ? I share the data/code/figures if you can have a look. When I say it fails, the location of tensor and mean value is correct but the resampling look "incorrect" before reorientation.

Thanks in advance.

**Pipeline**

-----------------------------------------
WAY 1 FAILED
- make a composite transform off the rigid + affine + warp
- apply the composite transform on the tensor 
- reoriented the tensor with the composite 
---------------------------------------
WAY 2 SEEMS OK
- apply the rigid transform on the tensor 
- reoriented the tensor

- make a composite transform off the affine + warp
- apply the composite transform on the tensor 
- reoriented the tensor with the composite 
---------------------------------------

**To reproduce**

https://filesender.renater.fr/?s=download&token=21ddc356-f12c-4101-9b4f-4d22ca2b54e5

The code compute :
- a one step process (rigid + affine + warp). files are named  _wiki.nii.gz   
- a two step process (rigid) then (affine + warp)
  
**Additionnal Information**

The problem exist also without the wrap using either :

=============================================================================
The composite transform comprises the following transforms (in order): 
  1. 0_Prepare/transform-itk_2_to_initial_reference.txt (type = MatrixOffsetTransformBase)
  2. /home/valeryo/mount/valery.ozenne//Dev/ants-modules/U1045/template_SyN_masked_0.20g//T_mean_bzero_2_to_ref_via_ants_masked10GenericAffine.txt (type = AffineTransform)
=============================================================================

or either

=============================================================================
The composite transform comprises the following transforms (in order): 
  1. Transform/transform-itk_1_to_initial_reference.txt (type = MatrixOffsetTransformBase)
  2. Transform/T_mean_bzero_1_to_ref_via_ants_masked00GenericAffine.mat (type = AffineTransform)
  3. Transform/T_mean_bzero_1_to_ref_via_ants_masked01Warp.nii.gz (type = DisplacementFieldTransform)
=============================================================================

Can I create a composite transform using a MatrixOffsetTransformBase and a AffineTransform ?

**Comment by cookpa** [comment]
You should be able to compose multiple transforms using `antsApplyTransforms`. If this isn't working, could you make a simpler example? Containing the moving image, reference image, transforms, and calls to `antsApplyTransforms` needed to reproduce the problem.
