### ISSUE TITLE
QC Mosaic can use too broad of a mask due to resampling of thickness map

### ISSUE THREAD

**Issue by ins0mniac2** [ANTsX/ANTs#1038]
Reporting an issue with creation of thickness map QC mosaics. The resampling of the thickness map to 1x1x1 in line 1370 of ACT script (logCmd $resample2) uses ResampleImageBySpacing with default linear interpolation. Some of the data where no original dimension is 1mm will produce a CorticalThicknessMask.nii.gz image that covers almost the entire brain -- as a result, none of the underlying brain is visible in the final mosaic.

The most faithful mask is obtained by using nn-interp, and directly resampling into the 1x1x1 space already created previously in BrainSegmentation0N4Resampled.nii.gz.

**Comment by ntustison** [comment]
Can you provide an image where this issue occurs along with some images to demonstrate what you're referring to?  I'm struggling to understand the problem.

**Comment by ins0mniac2** [comment]
Hey Nick, attached is a thickness map, the resampled thickness map, and the thickness map image that demostrate what happens.
[125573CorticalThicknessMask.nii.gz](https://github.com/ANTsX/ANTs/files/4887170/125573CorticalThicknessMask.nii.gz)
[125573CorticalThicknessHotResampled.nii.gz](https://github.com/ANTsX/ANTs/files/4887171/125573CorticalThicknessHotResampled.nii.gz)
[125573CorticalThickness.nii.gz](https://github.com/ANTsX/ANTs/files/4887172/125573CorticalThickness.nii.gz)

**Comment by ntustison** [comment]
Sorry, but I'm still not understanding what the problem is.  I see that the mask is way off but I don't understand why that would mask would be produced in the first place.

**Comment by ntustison** [comment]
Perhaps you can post the png.

**Comment by ins0mniac2** [comment]
Here you go. I shared those 3 niftis so you could reproduce the 2 steps (below) that produced the erroneous mask.

ResampleImageBySpacing 3 125573CorticalThickness.nii.gz 125573CorticalThicknessHotResampled.nii.gz 1 1 1
ThresholdImage 3 125573CorticalThicknessHotResampled.nii.gz 125573CorticalThicknessMask.nii.gz 0 0 0 1

![125573CorticalThicknessTiledMosaic](https://user-images.githubusercontent.com/1168408/86849959-75069780-c07e-11ea-943a-5e21515a6cbd.png)

**Comment by ntustison** [comment]
I see.  Thanks.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/pull/1039/files
