### ISSUE TITLE
Unable to Install without Administrative Permissions

### ISSUE THREAD

**Issue by davisn11** [ANTsX/ANTs#1042]
**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[X] Installation (make install)

**Build environment**
 - OS: MAC OS
 - OS version: 10.15.5
 - Type of system: Laptop
 
**ANTs version**
Version 2.3.4

**Build configuration and logs**
Please attach the following files (relative to your build directory)
[build.log](https://github.com/ANTsX/ANTs/files/4898599/build.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/4898601/CMakeCache.txt)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/4898605/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/4898607/CMakeOutput.log)

**Additional context**
I have been trying to install ANTs using the instructions on the wiki. I don't have admin privileges and when I go to the troubleshooting section and try the 2 work arounds there I still end up getting errors saying "CMake Error at Examples/cmake_install.cmake:36 (file):
  file cannot create directory: /new/install/dir/lib.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)". This was the farthest I had gotten through the installation process. I am very green when it comes to coding so I apologize for my naivety. Thank you for your help!

**Comment by cookpa** [comment]
You can change the install prefix:

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#the-build-completed-but-i-forgot-to-set-the-install-prefix-and-cant-write-to-the-default

**Comment by davisn11** [comment]
> You can change the install prefix:
> 
> https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#the-build-completed-but-i-forgot-to-set-the-install-prefix-and-cant-write-to-the-default

Thank you for your quick reply. I tried following these directions, but each time would get the error that I needed administrative privileges. Is there a specific prefix that wouldn't require privileges?

**Comment by cookpa** [comment]
On Mac, something under /Users/[your user name]

**Comment by davisn11** [comment]
Will this matter where I install it? Does it need to be in the same directory as cmake or anything?
