### ISSUE TITLE
Effect of ANTS SyN Registration to MNI on MD values

### ISSUE THREAD

**Issue by CallowBrainProject** [ANTsX/ANTs#1043]
Hello,

I have recently warped my diffusion images to MNI space using the following process.

b0->T1
T1->MNI

Apply these registrations to MD, FA, and Gray matter segmentation maps to get in MNI space.

I am getting some large MD values (1-2.6 or so), when trying to extract diffusivity values from cortical gray matter. I have tried to account for Partial volume errors and the b-gradient used was 900mm/s^2. However, I was wondering if the non-linear registrations might also alter the MD values to the point where they might no longer be expected to fall into the same range?

Any thoughts you can provide on the matter would be greatly appreciated.

**Comment by cookpa** [comment]
The large diffusivity values usually result from interpolation errors. Try applying the transforms with `-n NearestNeighbor`.

**Comment by CallowBrainProject** [comment]
Thanks!
