### ISSUE TITLE
Code of conduct for ANTs?

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTs#1044]
Hey all,

I discussed with @stnava about the possibility of adopting a code of conduct for ANTsX projects.  One possible choice is the open-source [contributor covenant](https://www.contributor-covenant.org/).  Does anybody have any thoughts with respect to this?

Thanks,
Nick

**Comment by cookpa** [comment]
I think it's a good idea. Is this what ITK uses? I think it would be good to have a basic summary for the Wiki as well as the longer form.

**Comment by ntustison** [comment]
[This is ITK's](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CODE_OF_CONDUCT.md).  I looked at it yesterday and, while I agree with it, I figure other people have thought longer and more in-depth than I have about these issues and have made those thoughts available for direct adoption.  That's how I found the contributor covenant.

**Comment by cookpa** [comment]
Closing now that the code of conduct is adopted (see badge on main page).
