### ISSUE TITLE
Long run time for antsRegistration

### ISSUE THREAD

**Issue by CarolineBao** [ANTsX/ANTs#1049]
**Describe the problem**

I'm currently running the following command on these images (dsurqec_15micron_masked.nii, ambmc_15micron.nii):
https://github.com/IBT-FMI/mouse-brain-atlases_generator/blob/a5f1bd27ba52d006e3c9df90fe3a8193c6651761/ambmc2dsurqec.sh#L31-L63

The call has been running for almost 2 weeks, which is much longer than expected.

I saw that the iteration number (second column in the collapsed section "Current output" below) had reached over 20000, which I didn't expect to see since none of the convergence calls have maximum levels of iteration large enough to allow for that. Is there another part of the output that I should be referencing to see the iteration number?

Additionally, I'm currently running the code in tmux and see a limited number of lines of output. Are there any options in the antsRegistration call that would allow for logging the results of calling antsRegistration?

<details>
  <summary>Current output</summary>
  2DIAGNOSTIC, 22229, -3.302809298038e-01, 1.431010088204e-09, 7.9666e+05, 3.5720e+01,                                  
 2DIAGNOSTIC, 22230, -3.302809298038e-01, 1.430945806291e-09, 7.9670e+05, 3.5778e+01,                                  
 2DIAGNOSTIC, 22231, -3.302809298038e-01, 1.430881413356e-09, 7.9674e+05, 3.5849e+01,                                  
 2DIAGNOSTIC, 22232, -3.302809298038e-01, 1.430817020420e-09, 7.9677e+05, 3.5769e+01,                                  
 2DIAGNOSTIC, 22233, -3.302809298038e-01, 1.430752627485e-09, 7.9681e+05, 3.5822e+01,                                  
 2DIAGNOSTIC, 22234, -3.302809298038e-01, 1.430688345572e-09, 7.9684e+05, 3.5753e+01,                                  
 2DIAGNOSTIC, 22235, -3.302809298038e-01, 1.430623952636e-09, 7.9688e+05, 3.5797e+01,                                  
 2DIAGNOSTIC, 22236, -3.302809298038e-01, 1.430559670723e-09, 7.9691e+05, 3.5675e+01,                                  
 2DIAGNOSTIC, 22237, -3.302809298038e-01, 1.430495277788e-09, 7.9695e+05, 3.5812e+01,                                  
 2DIAGNOSTIC, 22238, -3.302809298038e-01, 1.430430995875e-09, 7.9699e+05, 3.5796e+01,                                  
 2DIAGNOSTIC, 22239, -3.302809298038e-01, 1.430366713961e-09, 7.9702e+05, 3.5810e+01,                                  
 2DIAGNOSTIC, 22240, -3.302809298038e-01, 1.430302321026e-09, 7.9706e+05, 3.5645e+01,                                  
 2DIAGNOSTIC, 22241, -3.302809298038e-01, 1.430238039113e-09, 7.9709e+05, 3.5821e+01,                                  
 2DIAGNOSTIC, 22242, -3.302809298038e-01, 1.430173757200e-09, 7.9713e+05, 3.5817e+01,                                  
 2DIAGNOSTIC, 22243, -3.302809298038e-01, 1.430109475287e-09, 7.9716e+05, 3.5794e+01,                                  
 2DIAGNOSTIC, 22244, -3.302809298038e-01, 1.430045193374e-09, 7.9720e+05, 3.5888e+01,                                  
 2DIAGNOSTIC, 22245, -3.302809298038e-01, 1.429980911460e-09, 7.9724e+05, 3.5970e+01,                                  
 2DIAGNOSTIC, 22246, -3.302809298038e-01, 1.429916629547e-09, 7.9727e+05, 3.5777e+01,                                  
 2DIAGNOSTIC, 22247, -3.302809298038e-01, 1.429852347634e-09, 7.9731e+05, 3.5821e+01,                                  
 2DIAGNOSTIC, 22248, -3.302809298038e-01, 1.429788065721e-09, 7.9734e+05, 3.5825e+01,                                  
 2DIAGNOSTIC, 22249, -3.302809298038e-01, 1.429723783808e-09, 7.9738e+05, 3.5858e+01,                                  
 2DIAGNOSTIC, 22250, -3.302809298038e-01, 1.429659501895e-09, 7.9742e+05, 3.5962e+01,                                  
 2DIAGNOSTIC, 22251, -3.302809298038e-01, 1.429595219982e-09, 7.9745e+05, 3.5803e+01,                                  
 2DIAGNOSTIC, 22252, -3.302809298038e-01, 1.429531049091e-09, 7.9749e+05, 3.5843e+01,
</details>
                       
@TheChymera

**Comment by cookpa** [comment]
What version of ANTs are you using? It sounds like you have the bug that was fixed here 

https://github.com/ANTsX/ANTs/commit/bfddb4b139c225dd2f6fce2038cc6e3eaa0b4143

**Comment by CarolineBao** [comment]
I'm using 2.3.1.dev37-gf78b2. Would I need to update ANTs to fix this? I saw that the bug was first mentioned for version 2.3.2.

Also, are there any options in the antsRegistration call that would allow for logging the results of calling antsRegistration?

Thank you!

**Comment by cookpa** [comment]
'--verbose' to log output.

Can you update ANTs and see if the problem persists?

**Comment by cookpa** [comment]
To test for the bug, run with verbose and --convergence [ 5x10x20, 0 ]. If you have the bug, it will instead run 10x20xZ iterations, where Z is a random number that will differ for each execution.
