### ISSUE TITLE
Rotating bvec after registering to T1

### ISSUE THREAD

**Issue by sambal145** [ANTsX/ANTs#1050]
Dear ANTs experts,
 
I corrected for EPI distortions by registering the average b0 volume to the T1 image, by using antsRegistrationSyN.sh followed by antsApplyTransforms. I then proceeded with the estimation of the diffusion parameters within the FSL environment (bedpostx).
However, I now realize that I did not rotate the bvec file accordingly, and I was wondering what’s the way to proceed in this case.
 
I tried to search on the forum and I stumbled upon antsMotionCorrDiffusionDirection. I am not sure though whether this applies also to my case and I am sorry if the question has been asked already. **How do I apply the transformation to my bvec file?** 
 
Thanks in advance for the help!

**Comment by cookpa** [comment]
@jeffduda do we have any support for this workflow? In other words, can `antsMotionCorrDiffusionDirection` take a list of transforms from `antsRegistration`, or does it require `antsMotionCorr`?

**Comment by jeffduda** [comment]
I believe it will only take the output of antsMotionCorr. If you have a
list of transform files, it should be pretty easy to generate a compatible
file using ANTsR
-Jeff

**Comment by cookpa** [comment]
Thanks @jeffduda . It would be nice to have a function somewhere that could do a bvec rotation with a generic transform.

@sambal145 what we're talking about here is correcting for a global rotation, such as you would get with `antsMotionCorr`. If you are doing a deformable registration then the rotation will not be global - in effect, you will have a set of bvecs that vary across the image. This isn't widely supported in reconstruction software.

You would probably be better off warping your T1w image to the DWI space, and doing the tractography in the diffusion native space. You can take the results back to T1w space later if needed.

**Comment by sambal145** [comment]
Thanks @cookpa and @jeffduda for your answers. I have been searching online quite a bit in the last week, and I found the following script taking the ANTs rigid transform as input to rotate the bvecs: https://gist.github.com/mpaquette/5d59ad195778f9d984c5def42f53de6e. 

I however have a couple of questions, also based on your comments.
Do you think it is ok to apply the rotation using this script, even if not a global rotation as you mentioned? 

- If **NO**, suppose it would not be possible to re-run the registration the other way around (from T1 to DWI instead of DWI to T1), would it be at that point better not to rotate the bvecs at all? How can I extract information about the amount of movement between b0 and T1 to estimate how much not rotating the bvecs would alter fiber tracking results?

- If **YES**, my antsRegistrationSyn call included a rigid + affine + deformable registration (-t s option). Would I need to concatenate these transforms to rotate the bvecs? Or would the _0GenericAffine.mat do the trick? 

Thanks again!

**Comment by cookpa** [comment]
In my opinion, the more you can do in native space the better, because you avoid potential problems or introducing artifacts by resampling the data. 

If you apply a deformable registration, you will no longer have a constant bvec set for all voxels in the image. This is a problem for most reconstruction algorithms.

FSL and ANTs do have some different conventions. One notable one is that bvecs in FSL must always be in radiological orientation, regardless of the data. 

https://github.com/ANTsX/ANTs/wiki/Importing-diffusion-tensor-data-from-other-software
