### ISSUE TITLE
AntsRegistration

### ISSUE THREAD

**Issue by mindmap2** [ANTsX/ANTs#1052]
Dear ants community,
I want to register 1490 2D images one by one to 1 2D image.Is there a command that I can follow( like a loop) to save time or should I repeat my registration 1490 times?

Thanks,

**Comment by ntustison** [comment]
There's no internal looping in an ``antsRegistration`` call or any of the scripts so any looping you're going to need to perform externally.  A simple bash script could work as would using ANTsR or ANTsPy.

**Comment by dorianps** [comment]
A for loop in bash might work well, too. If you have many CPU cores you can
try to set high numbers of itk global threads, or you can just send them as
separate jobs in a computing cluster. In antsr, the loop is easy but
sending multiple jobs in parallel is annoyingly complicated.

Dorian

**Comment by mindmap2** [comment]
Thanks for your help Nick and Dorian.What do you mean by performing loop externally and then transfer it to ants?Is there any specific command to do that kind of registration in ANTsR?

Thanks,

**Comment by gdevenyi** [comment]
You may find this introductory material on the shell useful https://swcarpentry.github.io/shell-novice/
