### ISSUE TITLE
-fpermissive issues when compiling ants-2.3.4

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#1053]
**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)
[x] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: [Gentoo Linux]
 - OS version: [Rolling release]
 - Type of system: [Desktop]

 
**ANTs version**
ants-2.3.4

**Build configuration and logs**

[build.log](https://github.com/ANTsX/ANTs/files/4970849/build.log)

**Additional context**

**Comment by gdevenyi** [comment]
Hi, you have not provided your configuration details, I'm guessing that gentoo is providing "custom" build options?

**Comment by cookpa** [comment]
Looks like a problem populating the version information.

Can we see the rest of the build config files?

Was this built from a downloaded tarball (not a git clone)?

Does buildDir/ANTS-build/ANTsVersionConfig.h exist? What does it look like?

**Comment by TheChymera** [comment]
@gdevenyi  @cookpa apologies, this was in fact misfetched via git. The build still fails, but with a wholly different error: https://github.com/ANTsX/ANTs/issues/1054
