### ISSUE TITLE
Build fails with `FileModeEnum`-related error

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#1054]
**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)
[x] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: [Gentoo Linux]
 - OS version: [Rolling release]
 - Type of system: [Desktop]

 
**ANTs version**
ants-2.3.4 (from versioned github tarball)

**Build configuration and logs**

[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/4974885/CMakeOutput.log)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/4974886/CMakeError.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/4974887/CMakeCache.txt)
[build.log](https://github.com/ANTsX/ANTs/files/4974888/build.log)

**Comment by cookpa** [comment]
Does a Superbuild work? It's possible your system ITK is out of date. There have been a lot of changes to the enums in ITK.

**Comment by TheChymera** [comment]
@cookpa can I tell from the pasted logs whether the superbuild works? I use ITK `5.0.1`.

**Comment by cookpa** [comment]
SuperBuild means you let ANTs download it's own ITK. ANTs is fairly tightly coupled with ITK development and is not usually backwards compatible. I think the source of your particular error is that you have an ITK from before the recent enum refactoring, which ANTs has been modified to expect.

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#using-system-itk-or-vtk

**Comment by TheChymera** [comment]
@cookpa I'm trying to compile ITK 5.1.0, that's even newer than the tag, so maybe it will work? :)

**Comment by TheChymera** [comment]
@cookpa any idea why I get these files ending in `.0.0.0.0`? https://ppb.chymera.eu/721264.log

**Comment by TheChymera** [comment]
This particular issue was fixed with the ITK update, thank you.
