### ISSUE TITLE
[Question] Crop away 0s from 3D image  

### ISSUE THREAD

**Issue by thomshaw92** [ANTsX/ANTs#1057]
Hi experts,
I have a T1w image (size: 192x192x192, 1mm), and a binary mask with the same spacing. 

Does ANTs have a function that could crop the binary mask so the size of the mask image is roughly the size of the masked region (i.e., get rid of all the 0s in the mask). I need to do this to save compute at a later step.

What I already tried/issues: mask changes positions between cases so I can't use a standard co-ordinate/slice number to ExtractRegion. 

Thanks for your help!

**Comment by dorianps** [comment]
Not sure if ANTs has this, but in ANTsR there is a `cropImage` function which seems to do exactly that.
https://github.com/ANTsX/ANTsRCore/blob/master/R/cropImage.R

**Comment by thomshaw92** [comment]
@dorianps try as I might, I couldn't get ANTsR installed on WSL :(  and I don't have a linux box with root access :/ 
I'll give the Docker version a go, I just saw it!

**Comment by dorianps** [comment]
The docker container should work on Windows. I have put also some .bat scripts to make it a one click process. See dorianps/docker.

**Comment by gdevenyi** [comment]
ExtractRegionFromImageByMask

**Comment by thomshaw92** [comment]
Thanks @gdevenyi :D
