### ISSUE TITLE
antsApplyTransforms generated nothing and no bug is reported

### ISSUE THREAD

**Issue by YamengGu** [ANTsX/ANTs#1060]
**Describe the problem**
When I use the antsApplyTransforms to register the fMRI data to the anatomical template using the information generated by registering the structural image to the anatomical template, there is no output and no bug is reported. I do not know what happened.

**To Reproduce**
This is the command line I used:
antsApplyTransforms -d 4 -i ${dir}/sub-KKY921-func-sub-KKY921_task-rest_run-1_bold_reg.nii.gz -r ${dir3}/Template_C57Bl6_n30_brain.nii -o ${dir}/bold_reg2tmp.nii.gz -n Linear -t ${dir}/T2_reg_C57_v21Warp.nii.gz -t ${dir}/T2_reg_C57_v20GenericAffine.mat

The data can be found here:
https://drive.google.com/drive/folders/1M4X7RUZfIMldlfYlkvPPnq_HkQ7Da_nc?usp=sharing

**System information (please complete the following information)**
Linux redhat

**ANTs version information**
 - ANTs code version: 2.3.4
 - ANTs installation type: Compiled from source

**Additional information**
Add any other information that might help solve the problem.

**Comment by gdevenyi** [comment]
Add "--verbose" for it to actually print your error in the command.

This is a bug that the errors don't get printed without --verbose

**Comment by YamengGu** [comment]
> Add "--verbose" for it to actually print your error in the command.
> 
> This is a bug that the errors don't get printed without --verbose

Thanks for your reply. I added the --verbose and changed the -d 3. And I do see the output nii file. But when I open the output file and it's all zero.

**Comment by cookpa** [comment]
Also, you need `-d 3 and -e 4` for time series data.

This is using the T1w to template warp, so it will only be correct if the fMRI data is already aligned with the T1w image.

**Comment by YamengGu** [comment]
> Also, you need `-d 3 and -e 4` for time series data.
> 
> This is using the T1w to template warp, so it will only be correct if the fMRI data is already aligned with the T1w image.

I added the -d 3 and -e 4 and it still gave me all zeros in the output nii file. Actually, this commands is to register BOLD time series to template warp. And the BOLD time series is already aligned with the T1w image. Thanks.

**Comment by cookpa** [comment]
OK. Can you please add the T1w image to the Google drive?

**Comment by YamengGu** [comment]
> OK. Can you please add the T1w image to the Google drive?

Sure. I added the image to the Google drive. Also, I used this command to register T1 to the template: antsRegistrationSyNQuick.sh -d 3 -f ${dir3}/Template_C57Bl6_n30_brain.nii -m ${dir}/T2w_bet.nii.gz -o ${dir}/T2_reg_C57_v2.

**Comment by cookpa** [comment]
Apologies, I told you the wrong thing. Try `-e 3`.

**Comment by YamengGu** [comment]
> Apologies, I told you the wrong thing. Try `-e 3`.

After I changed to -e 3 and it started running and I can see that Applying transforms to time point 36 (out of 400). Then the command got killed. This is really weird.

**Comment by cookpa** [comment]
That could be memory. Add `--float 1` and see if it gets further.

**Comment by YamengGu** [comment]
> That could be memory. Add `--float 1` and see if it gets further.

It works. Thanks.
