### ISSUE TITLE
Can I do N4 without segmentation

### ISSUE THREAD

**Issue by wy1996** [ANTsX/ANTs#1065]
I wanted to do the bias filed correction for a TOF image, so I used _antsAtroposN4.sh_. I used the whole image volume with no mask or prori. Since I will do the segementation after using SPM, please tell me that if I can only do the N4 bias correction without segmentation?
Thank you very much！

**System information (please complete the following information)**

 - OS: Win10 + VMware Workstation Pro + Ubuntu
 - OS version: Ubuntu 18.04.4 LTS
 - Type of system: Linux

**ANTs version information**
 - ANTs code version: ANTs Version: 2.3.3.dev168-g29bdf
 - ANTs installation type: Compiled from source

**Comment by cookpa** [comment]
You can certainly call `N4BiasFieldCorrection` directly, the mask is optional.
