### ISSUE TITLE
[Question] N4BiasFieldCorrection 3D vs 4D

### ISSUE THREAD

**Issue by tashrifbillah** [ANTsX/ANTs#1067]
Hi all,

I have a 4D diffusion-weighted image and I am trying to understand the correct way of doing N4BiasFieldCorrection. If I say `-d 4`, would that correct each 3D volume separately and then merge? Or is there a mechanism in place to figure out bias field over 4D and correct?

**Comment by ntustison** [comment]
Specifying ``-d 4`` would estimate the smoothly-varying, 4-D bias field over the entire longitudinal image set.  Although that functionality is there, it has not been explored in any depth whatsoever and so we wouldn't be able to provided direction on recommended usage.  For example, one would have to specify the knot spacing in time which would require one to make a good choice for temporal voxel spacing and we haven't ever looked at that.  My recommendation would be split it up into separate 3-D volumes and apply bias correction to each volume separately or do some sort of averaging to minimize the computation time.

**Comment by tashrifbillah** [comment]
I did the latter, thanks @ntustison.

**Comment by ntustison** [comment]
No.  Something like: 

```
for i in `ls b*.nii`; 
  do 
    ImageMath 3 ${i\.nii\corrected\.nii} / $i b0_bias.nii
  done
```

**Comment by tashrifbillah** [comment]
So is the correction a division?

**Comment by cookpa** [comment]
That's right. The bias field is multiplicative, so dividing the original data by the bias field gives the corrected image.

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/Dimensionality-or-ImageDimension-option-in-ANTs
