### ISSUE TITLE
opposite effect of updateFieldVarianceInVoxelSpace

### ISSUE THREAD

**Issue by jordandekraker** [ANTsX/ANTs#1068]
I am trying to run highly fluid SyN registration between two labelmaps. Note that this is being run as a multi-contrast registration, where each contrast is a different binarized label. I'm investigating the effect of `updateFieldVarianceInVoxelSpace`, and the wiki page suggests that higher values should lead to a more regularized final result. Instead, I seem to be getting the opposite effect, where higher values lead to a more fluid deformation (see image below). This remained true across different floating images (columns of the image below), and using the metric MeanSquares radius=3 or radius=9 (not shown here, but results were roughly the same). 

One example of the call looks like this:

```
antsRegistration -d 3 --interpolation Linear -r TemplateShapeTest/INDD103764-R/updatefield03/tmp//labelmap-midProcess_UPennAtlasReg-Aff/ants_0GenericAffine.mat --convergence [50x100x200,1e-7,10] --shrink-factors 2x1x1 --smoothing-sigmas 2x1x0.25vox --metric MeanSquares[TemplateShapeTest/INDD103764-R/updatefield03/tmp//labelmap-midProcess_UPennAtlasReg-SynGM/template_label-1.nii.gz,TemplateShapeTest/INDD103764-R/updatefield03/tmp//labelmap-midProcess_UPennAtlasReg-SynGM/target_label-1.nii.gz,3,3] --metric MeanSquares[TemplateShapeTest/INDD103764-R/updatefield03/tmp//labelmap-midProcess_UPennAtlasReg-SynGM/template_label-2.nii.gz,TemplateShapeTest/INDD103764-R/updatefield03/tmp//labelmap-midProcess_UPennAtlasReg-SynGM/target_label-2.nii.gz,1,3] --transform SyN[0.25,3,0] --output [TemplateShapeTest/INDD103764-R/updatefield03/tmp//labelmap-midProcess_UPennAtlasReg-SynGM/ants_] -v
```
, where `-transform SyN[0.25,X,0]` could take on different values for X as the `updateFieldVarianceInVoxelSpace` .

Here are some examples of the resulting deformation of the floating images (originals at the top) to the reference (top left) across different `updateFieldVarianceInVoxelSpace` values (rows):

![image](https://user-images.githubusercontent.com/25106300/90668701-78b14080-e21e-11ea-8e03-27600126717a.png)

I was thinking that perhaps this might be because of the pyramid&smoothing levels I chose? However I did want to preserve as many high frequency details as possible, and the yellow label is very thin (1-2 voxels thick). Was wondering if anyone has an intuition of what might be going on here, or if increasing `updateFieldVarianceInVoxelSpace` does indeed increase the overall fluidity in general?

```
antsRegistration --version
ANTs Version: 2.1.0-gGIT-N
Compiled: May 24 2017 07:49:00
```

Thanks!

**Comment by ntustison** [comment]
* The wiki is correct.  It's hard to say what might be occurring with your data.  However, if all you're looking for is a more regularized SyN solution, I would switch to the BSplineSyN transform.  Try ``BSplineSyN[3,26,0]`` to start.  
* The radius is a non-existent parameter for the MSQ metric.  
* If you can, please update your ANTs version.  That version is rather outdated.

**Comment by stnava** [comment]
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/324222/90697265-fd668380-e24b-11ea-827d-c2afc82cc4a9.png">


```
library( ANTsR )
i1 = ri( 1 )
i2 = ri( 2 )
fsss = c( 1, 3, 7, 12, 18, 25 )
layout(matrix(1:length(fsss),nrow=1))
for ( fss in fsss ) {
  reg=antsRegistration( i1, i2, 'SyNOnly', totalSigma=0, flowSigma=fss, regIterations=c(50,0,0), synMetric='MeanSquares',  verbose=TRUE )
 plot( createWarpedGrid( i1, transform=reg$fwdtransforms, fixedReferenceImage=i1) )
}
```


however, scale effects are complicated by the fact that you are integrating across scales and across time;  the update field only controls the scale of the gradient not of the integrated solution over the whole optimization process.  that is controlled by the total field variance.

**Comment by stnava** [comment]
one other note - the "time" component will make the apparent deformation increase over time as well - so you would want to manage that too if you were trying to do a controlled experiment.
