### ISSUE TITLE
different results using different versions of MeasureImageSimilarity

### ISSUE THREAD

**Issue by namiranian** [ANTsX/ANTs#1070]
Hi,
I want to check the similarity between two nii images, using MeasureImageSimilarity. I compare the results of two versions of ANTs codes, and their results are different (as summarized in the following tables). In the recent version, when the fixed and moving images exchange, the results change, while the same value is reported, using the old version.
what is the reason for these differences? and which one is valid?

**Old Version:**
ANTs Version: 2.1.0.post437-g6f2ac
Compiled: Nov 25 2015 04:31:24
command:
${ANTSPATH}/MeasureImageSimilarity $dim 2 $fixedImage $mov
${ANTSPATH}/MeasureImageSimilarity $dim 1 $fixedImage $mov
(dim=3)
Result:
   
    fixed    moving  |      MI    |   CC
    Im1       Im2    | -0.556639  |  0.992826
    Im2      Im1     | -0.556639  |   0.992826
    Im1      Im1     |  -0.669661 |    1
    Im2      Im2     |  -0.791062 |   1

**Recent Version:**
ANTs Version: 2.3.4.dev187-gb37e8
Compiled: Aug 12 2020 08:00:22
command:
 ${ANTSPATH}/MeasureImageSimilarity -d $dim -m MI[ $fixedImage, $mov , 1,  32 ]
${ANTSPATH}/MeasureImageSimilarity -d $dim -m CC[ $fixedImage, $mov, 1,4 ]
Result:

    fixed    moving  |       MI    |   CC
    Im1       Im2    | -0.362532   |  -0.932187
    Im2      Im1     | -0.361234   |   -0.932187
    Im1      Im1     |  -0.479957  |    -1
    Im2      Im2     |  -0.574473  |    -1

**Images:**
[images.zip](https://github.com/ANTsX/ANTs/files/5130250/images.zip)

**Comment by ntustison** [comment]
Thanks.  And the additional information helps.  

The code for the two implementations are completely different.  @stnava wrote the first version based on some of the original ANTS code.  The new version is based on the refactored ANTs code which is now included in ITK.   There were so many code changes that I wouldn't now where to start in listing all the possible reasons for the actual differences in numerical values.  The new version should map identically with the ``antsRegistration`` tool, while the first version is certainly valid given the underlying code differences and hidden parameter selection, the second version is also valid but has greater consistency with the current toolkit.
