### ISSUE TITLE
ants joint label fusion

### ISSUE THREAD

**Issue by anagrammarian** [ANTsX/ANTs#1071]
Hi,

For a thalamic segmentation project, we have been using ANTS for registration and jointfusion fro PICSL_MALF for the label fusion. However we are running into issues installing PICSL-MALF on Mac and newer Ubuntu releases so I was playing with using the ANTS Joint fusion option (antsJointFusion). When I tried it with the exact same data, it worked but I had 2 issues.
Using 3x3x3 option for -s failed. Says 3x3x3 file not found. -s 3 worked (same for 2x2x2 etc).  I thought they were equivalent per the help command.
The second issue is it takes a really long time several minutes whereas jointfusion (PICSL MALF) took seconds. Any ideas? The final outputs look virtually identical give or take a few pixels.

This is an old install of ANTS 2.1.0 installed in June of 2016. I know there was a bug in the older version of ANTs in JF but this should be after the fixes. At any rate, it worked fine albeit super slowly.

Thanks
manoj saranathan

**Comment by ntustison** [comment]
Even though there are bugs in old releases, we really don't debug old ANTs versions for various reasons.  Please install ANTs as a fresh checkout from the GitHub repository and let us know which issues persist.

**Comment by anagrammarian** [comment]
I just installed the latest version and tried it. The good news is the first issue (-s argument) is solved. The long time to do fusion still remains. Again several 10s of minutes (as opposed to jointfusion).

**Comment by ntustison** [comment]
That is good news.  So the ``antsJointFusion`` implementation is based on ``jointfusion`` so my initial guess is that it is a parameter selection issue.  Can you post the two calls?

**Comment by anagrammarian** [comment]
Executing: jointfusion 3 1 -g temp/668_02282013_CD/WMnMPRAGE_bias_corr.nii.gz temp/884_06272013_TS/WMnMPRAGE_bias_corr.nii.gz temp/ctrl_921_07122013_MP/WMnMPRAGE_bias_corr.nii.gz temp/915_07112013_LC/WMnMPRAGE_bias_corr.nii.gz temp/845_05312013_VZ/WMnMPRAGE_bias_corr.nii.gz temp/943_07242013_PA/WMnMPRAGE_bias_corr.nii.gz temp/ctrl_911_07082013_TTO/WMnMPRAGE_bias_corr.nii.gz temp/869_06142013_BL/WMnMPRAGE_bias_corr.nii.gz temp/823_05202013_AJ/WMnMPRAGE_bias_corr.nii.gz temp/ctrl_902_07052013_SI/WMnMPRAGE_bias_corr.nii.gz temp/824_05212013_JS/WMnMPRAGE_bias_corr.nii.gz temp/ctrl_920_07122013_SW/WMnMPRAGE_bias_corr.nii.gz temp/ctrl_925_07152013_LS/WMnMPRAGE_bias_corr.nii.gz temp/ctrl_918_07112013_TQ/WMnMPRAGE_bias_corr.nii.gz temp/964_08092013_TG/WMnMPRAGE_bias_corr.nii.gz temp/819_05172013_DS/WMnMPRAGE_bias_corr.nii.gz temp/901_07052013_AS/WMnMPRAGE_bias_corr.nii.gz temp/ANON724_03272013/WMnMPRAGE_bias_corr.nii.gz temp/ANON606_20130110/WMnMPRAGE_bias_corr.nii.gz temp/ANON624_20130117/WMnMPRAGE_bias_corr.nii.gz -tg temp/crop_LIFUP020_MPRAGE_WMn.nii.gz -l temp/668_02282013_CD/13-Hb.nii.gz temp/884_06272013_TS/13-Hb.nii.gz temp/ctrl_921_07122013_MP/13-Hb.nii.gz temp/915_07112013_LC/13-Hb.nii.gz temp/845_05312013_VZ/13-Hb.nii.gz temp/943_07242013_PA/13-Hb.nii.gz temp/ctrl_911_07082013_TTO/13-Hb.nii.gz temp/869_06142013_BL/13-Hb.nii.gz temp/823_05202013_AJ/13-Hb.nii.gz temp/ctrl_902_07052013_SI/13-Hb.nii.gz temp/824_05212013_JS/13-Hb.nii.gz temp/ctrl_920_07122013_SW/13-Hb.nii.gz temp/ctrl_925_07152013_LS/13-Hb.nii.gz temp/ctrl_918_07112013_TQ/13-Hb.nii.gz temp/964_08092013_TG/13-Hb.nii.gz temp/819_05172013_DS/13-Hb.nii.gz temp/901_07052013_AS/13-Hb.nii.gz temp/ANON724_03272013/13-Hb.nii.gz temp/ANON606_20130110/13-Hb.nii.gz temp/ANON624_20130117/13-Hb.nii.gz -m Joint[0.1,0.5] -rp 1x1x1 -rs 5x5x5 temp/13-Hb.nii.gz

antsJointFusion -d 3 -g temp/ms9/WMnMPRAGE_bias_corr.nii.gz temp/ms8/WMnMPRAGE_bias_corr.nii.gz temp/ms7/WMnMPRAGE_bias_corr.nii.gz temp/ms6/WMnMPRAGE_bias_corr.nii.gz temp/ms5/WMnMPRAGE_bias_corr.nii.gz temp/ms4/WMnMPRAGE_bias_corr.nii.gz temp/ms3/WMnMPRAGE_bias_corr.nii.gz temp/ms2/WMnMPRAGE_bias_corr.nii.gz temp/ms1/WMnMPRAGE_bias_corr.nii.gz temp/ms11/WMnMPRAGE_bias_corr.nii.gz temp/ms10/WMnMPRAGE_bias_corr.nii.gz temp/ctrl8/WMnMPRAGE_bias_corr.nii.gz temp/ctrl9/WMnMPRAGE_bias_corr.nii.gz temp/ctrl4/WMnMPRAGE_bias_corr.nii.gz temp/ctrl5/WMnMPRAGE_bias_corr.nii.gz temp/ctrl6/WMnMPRAGE_bias_corr.nii.gz temp/ctrl7/WMnMPRAGE_bias_corr.nii.gz temp/ctrl1/WMnMPRAGE_bias_corr.nii.gz temp/ctrl2/WMnMPRAGE_bias_corr.nii.gz temp/ctrl3/WMnMPRAGE_bias_corr.nii.gz -t temp/crop_LIFUP020_MPRAGE_WMn.nii.gz -l temp/ms9/13-Hb.nii.gz temp/ms8/13-Hb.nii.gz temp/ms7/13-Hb.nii.gz temp/ms6/13-Hb.nii.gz temp/ms5/13-Hb.nii.gz temp/ms4/13-Hb.nii.gz temp/ms3/13-Hb.nii.gz temp/ms2/13-Hb.nii.gz temp/ms1/13-Hb.nii.gz temp/ms11/13-Hb.nii.gz temp/ms10/13-Hb.nii.gz temp/ctrl8/13-Hb.nii.gz temp/ctrl9/13-Hb.nii.gz temp/ctrl4/13-Hb.nii.gz temp/ctrl5/13-Hb.nii.gz temp/ctrl6/13-Hb.nii.gz temp/ctrl7/13-Hb.nii.gz temp/ctrl1/13-Hb.nii.gz temp/ctrl2/13-Hb.nii.gz temp/ctrl3/13-Hb.nii.gz -a 0.1 -b 0.5 -p 1x1x1 -s 5x5x5  -o temp/13-Hb.nii.gz

The directory names are slightly different as they have been renamed so ctrl5 ctrl2 etc are called different but the arguments for the parameters seem identical.

**Comment by anagrammarian** [comment]
It finished after almost 1.5 hrs. jointfusion takes about 5 min. The outputs are almost identical. We are having issues installing jointfusion on Macs due to some ITK library issues so I would love to use the ants version. Otherwise they have to install Ubuntu VMs and then run it which is a pain. Any insights would be very helpful.

**Comment by cookpa** [comment]
Could it be a difference in how background voxels are handled? I've not used jointfusion in a long time but I don't remember it being so much faster on dense brain labels. But if only the thalamus is labeled, it might work much better if it doesn't do the fusion in voxels where all the atlases have no label.

**Comment by anagrammarian** [comment]
I am already using cropped images (bilateral thalamus plus some) so it should be pretty fast. My q is if ants is using the Wang implementation of jointfusion, why is it taking so much more time for what I think are the same parameters (radius etc). I am sure there is an explanation but I cannot seem to see it after staring it for a day ;)

**Comment by cookpa** [comment]
OK. I looked at the code and I think a major difference is that the default metric for antsJointFusion is pearson correlation, and for jointfusion it's SSD. Maybe `-m MSQ` will speed up your ANTs call.

**Comment by anagrammarian** [comment]
Brilliant. I will give that a shot. Thanks cookpa

**Comment by ntustison** [comment]
I would suspect this [check](https://github.com/ANTsX/ANTs/blob/b37e8b56e4e518b0f2947f80d0e3701a5ddfe120/ImageSegmentation/itkWeightedVotingFusionImageFilter.hxx#L459) I turned off is the culprit.  Try specifying a mask consisting of the union of the nonzero segmentation label voxels of the input images.

**Comment by anagrammarian** [comment]
The -m MSQ didn;t make much of a difference. I tried with a small set of 2 labels to check. Again I can mask but its already cropped to the thalami and won't make much of a difference plus why is calling jointfusion so much faster? Still seems like some parameter is off?

**Comment by anagrammarian** [comment]
Ah I see what you mean. It automatically masks inside. I will try the masking.

**Comment by anagrammarian** [comment]
I did both -m MSQ and a mask. Seems much faster. Let me run jointfusion and then compare the results. Thanks a lot. Why did you comment those lines?

**Comment by anagrammarian** [comment]
Scratch that. -m MSQ gave me some weird results. So just did the masking. Sped it up quite a bit. I can now probably get rid of jointfusion requirement so my segmentation will now work on MACS. Thanks a lot Nick and cookpa.

**Comment by ntustison** [comment]
I don't have the ``jointfusion`` code in front of me but I believe it originally used correlation as the default metric, just like ``antsJointFusion``.  There were a few things we added to the latter including refactoring for thread safety, multi-threading, and joint intensity fusion (JIF).  The latter is the reason why I commented out Paul's heuristic because it no longer fit with the possibility of JIF and could be explicitly set by the user anyway via masking.

**Comment by anagrammarian** [comment]
I had one last q. Is JIF better than the original JF of Wang/Yushkevich? Has it been published? Is it automatically used in the antsJointFusion command?

**Comment by ntustison** [comment]
JIF is an extension to JLF, not a competitor.  It is a patch-based image intermodality synthesis/transformation algorithm which uses JLF technology.  We never wrote a publication because of the performance of deep learning approaches.

**Comment by anagrammarian** [comment]
Thanks again.
