### ISSUE TITLE
Restrict deformation problem on time series

### ISSUE THREAD

**Issue by Vanwalleghem** [ANTsX/ANTs#1072]
Hi,

we've been using ANTs with a lot of success on our larval zebrafish, thanks for this tool!

I have been trying to use it to register 2D images across time, while restricting the deformations to just x and y.
So far what worked was to transform my 3D movie into a sequence of 2D images and applying
```
antsRegistration -d 2 --float 1 -o [OutImg, OutImg.nii] -n WelchWindowedSinc -w [0.005,0.995] -u 1 -r [FixImg,MovImg, 1] -t rigid[0.1] -m MI[FixImg,MovImg,1,32, Regular,0.25] -c [1000x500x200x50,1e-7,5] -f 8x4x2x1 -s 2x1x1x0vox 
-t Affine[0.1] -m MI[FixImg,MovImg,1,32, Regular,0.25] -c [1000x500x200x50,1e-7,5] -f 8x4x2x1 -s 2x1x1x0vox 
-t SyN[0.05,6,0.5] -m CC[FixImg,MovImg,1,2] -c [100x500x200x50,1e-7,5] -f 8x4x2x1 -s 2x2x1x0vox -v 0
```

I then tried to use ImageMath to replicate the first image of the time series and use it as a template while restricting deformations across time

```
antsRegistration -d 3 --float 1 -o [OutImg, OutImg.nii] -n WelchWindowedSinc -w [0.005,0.995] -u 1 -r [FixImg,MovImg, 1] -t rigid[0.1] -m MI[FixImg,MovImg,1,32, Regular,0.25] -c [1000x500x200x50,1e-7,5] -f 8x4x2x1 -s 2x1x1x0vox -g 1x1x0x1x1x0 
-t Affine[0.1] -m MI[FixImg,MovImg,1,32, Regular,0.25] -c [1000x500x200x50,1e-7,5] -f 8x4x2x1 -s 2x1x1x0vox -g 1x1x1x1x1x1x0x0x0x1x1x0 
-t SyN[0.05,6,0.5] -m CC[FixImg,MovImg,1,2] -c [100x500x200x50,1e-7,5] -f 8x4x2x1 -s 2x2x1x0vox -g 1x1x0  -v 0
```

However, that didn't work to restrict the deformation across time. Is there anything I missed or an error in my calls?
Would I need to run each registration step individually?

**Comment by ntustison** [comment]
I'm not sure what the registration situation actually is.  Can you elaborate a bit more?  Is it that you have a single time series of ``N`` 2-D images and you want all the 2-D images registered across time?

**Comment by Vanwalleghem** [comment]
Yes I have N 2-D images and I want the 2-D images registered to the first image of the sequence to correct for movement artefacts.

When I create the 3-D template, I actually replicate the first 2-D image N times to create the volume template. Then I am trying to restrict the deformation to the x and y axis and ignore the time axis.

I hope that's clearer?

**Comment by ntustison** [comment]
Have you looked at antsMotionCorr?

**Comment by Vanwalleghem** [comment]
No I was not aware of it, that looks to be exactly what I need! Thanks.
I should be able to call it with more or less the same arguments than above, right?
It's still odd that it wouldn't work with the restrict-deformation, but I'll give this a go and let you know if it works
