### ISSUE TITLE
Velocity Field Saving (Log of deformations) when using TVF or Exponential. 

### ISSUE THREAD

**Issue by jjbouza** [ANTsX/ANTs#1074]
**Describe the problem**
Lie Group methods (e.g. stationary or time-varying LDDMM) parameterize the deformations using a velocity vector field. It seems these are not saved by default in ANTS, and the documentation for how to have them saved is lacking.

**To Reproduce**
This is not a data-specific issue as far as I can tell. Just for completeness, I came across this while registering the common "C" and "half C" example, saved as NIFTI files. Here is the command I ran:

```
dim=2
m=data/c.nii.gz
f=data/chalf.nii.gz
its=[1x1x1x1x0,0,5]   
smth=8x6x4x2x1vox
down=8x6x4x2x1
~/local_libs/install/bin/antsRegistration -d $dim  \
                   -m CC[ $f,$m, 0.5, 0 ] \
                   -m meansquares[ $f,$m, 1, 0 ] \
                   -t tvf[ 2.0, 8, 1,0.0, 0.05,0 ] \
                   -c $its  \
                   -s $smth  \
                   -f $down \
                   -u 1 \
                   -o output \
                   -v
```
Note: the 1 iteration at each level is to get an output that isn't too long, I obviously tested with normal iterations as well. 

Output:

```
All_Command_lines_OK
Using double precision for computations.
  number of levels = 5
  fixed image: data/chalf.nii.gz
  moving image: data/c.nii.gz
  fixed image: data/chalf.nii.gz
  moving image: data/c.nii.gz
Dimension = 2
Number of stages = 1
Use Histogram Matching true
Winsorize image intensities false
Lower quantile = 0
Upper quantile = 1
Stage 1 State
   Image metric = CC
     Fixed image = Image (0x56089f675df0)
  RTTI typeinfo:   itk::Image<double, 2u>
  Reference Count: 2
  Modified Time: 721
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 503
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  BufferedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  RequestedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  Spacing: [1, 1]
  Origin: [0, 0]
  Direction:
1 0
0 -1

  IndexToPointMatrix:
1 0
0 -1

  PointToIndexMatrix:
1 0
0 -1

  Inverse Direction:
1 0
0 -1

  PixelContainer:
    ImportImageContainer (0x56089f677f00)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
      Reference Count: 1
      Modified Time: 500
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 0x7f76a9391010
      Container manages memory: true
      Size: 22500
      Capacity: 22500

     Moving image = Image (0x56089f67d440)
  RTTI typeinfo:   itk::Image<double, 2u>
  Reference Count: 2
  Modified Time: 722
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 719
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  BufferedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  RequestedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [150, 150]
  Spacing: [1, 1]
  Origin: [0, 0]
  Direction:
1 0
0 -1

  IndexToPointMatrix:
1 0
0 -1

  PointToIndexMatrix:
1 0
0 -1

  Inverse Direction:
1 0
0 -1

  PixelContainer:
    ImportImageContainer (0x56089f67f9d0)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
      Reference Count: 1
      Modified Time: 716
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 0x7f76a9365010
      Container manages memory: true
      Size: 22500
      Capacity: 22500

     Weighting = 0.5
     Sampling strategy = none
     Number of bins = 32
     Radius = 0
     Sampling percentage  = 1
   Transform = TimeVaryingVelocityField
     Gradient step = 2
     Update field sigma (voxel space) = 1
     Total field sigma (voxel space) = 0.05
     Update field time sigma = 0
     Total field time sigma  = 0
     Number of time indices = 8
     Number of time point samples = 8
Registration using 1 total stages.

Stage 0
  iterations = 1x1x1x1x0
  convergence threshold = 0
  convergence window size = 5
  number of levels = 5
  using the CC metric (radius = 0, weight = 0.5)
  preprocessing:  histogram matching the images
  using the MeanSquares metric (weight = 1)
  preprocessing:  histogram matching the images
  Shrink factors (level 1 out of 5): [8, 8]
  Shrink factors (level 2 out of 5): [6, 6]
  Shrink factors (level 3 out of 5): [4, 4]
  Shrink factors (level 4 out of 5): [2, 2]
  Shrink factors (level 5 out of 5): [1, 1]
  smoothing sigmas per level: [8, 6, 4, 2, 1]
  Using default NONE metricSamplingStrategy

*** Running time-varying velocity field registration (varianceForUpdateField = 1, varianceForTotalField = 0.05, varianceForUpdateFieldTime = 0, varianceForTotalFieldTime = 0) ***

XDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
WDIAGNOSTIC,     1, -1.000000000000e+00, 1.797693134862e+308, 5.8735e-02, 5.8735e-02,
XDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
WDIAGNOSTIC,     1, -1.000000000000e+00, 1.797693134862e+308, 1.3104e-01, 7.2310e-02,
XDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
WDIAGNOSTIC,     1, -1.000000000000e+00, 1.797693134862e+308, 2.3550e-01, 1.0445e-01,
XDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
WDIAGNOSTIC,     1, -1.000000000000e+00, 1.797693134862e+308, 4.1262e-01, 1.7712e-01,
  Elapsed time (stage 0): 4.7286e-01


Total elapsed time: 4.7422e-01
```

**System information (please complete the following information)**
Running WSL 2 on Windows 10. Container is Ubuntu 18.04. 

**ANTs version information**

ANTs Version: 2.3.4.dev187-gb37e8
Compiled: Aug 29 2020 16:18:52

I compiled the source myself. 

**Additional information**
The command above just saves `output/0InverseWarp.nii.gz` and  `output/0Warp.nii.gz`. I think these are the forward and inverse deformation fields. **My group is interested in obtaining the underlying velocity vector fields.** 

There have been several previous threads on this topic , for example [here](https://github.com/ANTsX/ANTs/issues/1032), but the given explanation is lacking. It seems that the velocity fields should be saved by default when using the correct method (e.g. tvf here), but that is not the case using this script. 

It would be nice to get this sorted out. I am aware of two groups (included ours at UF) that are interested in using the velocity fields for other downstream tasks, but both have come across this problem.

**Comment by ntustison** [comment]
Just checked and there's definitely an issue.  I'm surprised I didn't notice this before.  I see what the problem is and I can fix it but, for now, try setting "-z 0" and verify that you are getting the "outputVelocityField.nii.gz" output file.

**Comment by jjbouza** [comment]
Thanks for the quick reply @ntustison

I’ll try this and get back to you.

**Comment by ntustison** [comment]
Okay, let me add a bit more information.  

* [Section of code](https://github.com/ANTsX/ANTs/blob/master/Examples/antsRegistrationTemplateHeader.h#L1394-L1415) where the velocity field is written (if it exists).  A check is performed [here](https://github.com/ANTsX/ANTs/blob/master/Examples/antsRegistrationTemplateHeader.h#L1367) to see if it is a velocity field transform type.
* However, before this section of code is where the [transform collapsing occurs](https://github.com/ANTsX/ANTs/blob/master/Examples/antsRegistrationTemplateHeader.h#L1276-L1313).  The problem is that only the displacement fields are composed so the "transform type" simply gets set to "SyN" if an inverse transform exists and "GeneralDisplacementFIeld" if not.   The result is that the velocity field transform type check doesn't survive.

Anyway, I wanted to detail this issue before deciding what to do.  Right now I'm inclined to simply require the user to set ``-z 0`` if they want the velocity fields, which is an exceptional case anyway, but specify it in the documentation.

**Comment by jjbouza** [comment]
I see. So if my registration pipeline has n velocity field transformation types would setting -z 0 save n velocity fields?

**Comment by jjbouza** [comment]
It seems this works for our purposes, so I will close the issue for now. Feel free to reopen it if you would like to for your own tracking of the issue.

**Comment by ntustison** [comment]
Yes, that is correct.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/commit/71778bfb3c0b23ca49c1d4f59feb48f1e49e0812
