### ISSUE TITLE
Using ANTSIntegrateVelocityField (converting .nii to .mhd)

### ISSUE THREAD

**Issue by gfcortes** [ANTsX/ANTs#1075]
I used the following shell script to output the underlying velocity field for a typical image registration.
```dim=2
m=data/c.nii.gz
f=data/chalf.nii.gz
its=[1x1x1x1x0,0,5]   
smth=8x6x4x2x1vox
down=8x6x4x2x1
/opt/ANTs/bin/antsRegistration -d $dim  \
                   -m CC[ $f,$m, 0.5, 0 ] \
                   -m meansquares[ $f,$m, 1, 0 ] \
                   -t tvf[ 2.0, 8, 1,0.0, 0.05,0 ] \
                   -c $its  \
                   -s $smth  \
                   -f $down \
                   -u 1 \
                   -o output \
                   -z 0
```
I would then like to use `ANTSIntegrateVelocityField` by passing in the previously outputted `output0VelocityField.nii.gz` file. I see that this function takes in the velocity field with a `.mhd` file extension instead of the `.nii` extension. I tried doing this with two different methods. First, I manually changed the extension in the filename. Second, I used the following python script.
```
import SimpleITK as sitk 

img = sitk.ReadImage("output0VelocityField.nii.gz")
sitk.WriteImage(img, "output0VelocityField.mhd")
```
Neither of these methods worked, both producing the following error message.
```
start 
 dim 2
 time-0 0 dt 0.1 time-1 0.5
Exception caught during reference file reading 

itk::ImageFileReaderException (0x7fdfea305ad0)
Location: "unknown" 
File: /Users/gcortes/Desktop/build/staging/include/ITK-5.1/itkImageFileReader.hxx
Line: 133
Description:  Could not create IO object for reading file output0VelocityField.mhd
  Tried to create one of the following:
    BMPImageIO
    BioRadImageIO
    Bruker2dseqImageIO
    GDCMImageIO
    GE4ImageIO
    GE5ImageIO
    GiplImageIO
    HDF5ImageIO
    JPEGImageIO
    JPEG2000ImageIO
    LSMImageIO
    MGHImageIO
    MINCImageIO
    MRCImageIO
    MetaImageIO
    NiftiImageIO
    NrrdImageIO
    PNGImageIO
    StimulateImageIO
    TIFFImageIO
    VTKImageIO
  You probably failed to set a file suffix, or
    set the suffix to an unsupported type.


 file output0VelocityField.mhd
 No TV Field 
```
It appears that the issue is with the `reference_image` parameter, which I assumed was simply the moving image from the initial registration. Furthermore, I'm unsure of whether I'm correctly converting my `output0VelocityField.nii.gz` to the desired `output0VelocityField.mhd` file. How do I correctly use this function?

**Comment by ntustison** [comment]
1) Don't mix ants and simple itk readers/writers.  The internal organization of the image is different.  You can convert simply using the ants.read/write functions.  

2) I'm pretty sure you can input .nii.gz files.

**Comment by jjbouza** [comment]
@gfcortes @ntustison This command works:

```ANTSIntegrateVelocityField moving.nii.gz output0VelocityField.nii.gz output0deformation.nii.gz 0 0.5 0.1```

for integrating a velocity field from 0 -> 0.5 in this example. You can also try integrating from 0 -> 1.0 and confirm the (integrated) deformation field output0deformation.nii.gz matches the original output0Warp.nii.gz from ANTS (it does).

**Comment by gfcortes** [comment]
It looks like this only returns the velocity field at time t = 0. How would you recommend extracting the velocity field (not the deformation) at an arbitrary time t? @ntustison

**Comment by ntustison** [comment]
The usage indicates the user can choose the two time points over which integration occurs, i.e., 

```
ANTSIntegrateVelocityField reference_image  VelocityIn.mhd DeformationOut.nii.gz  time0 time1 dT
```

**Comment by gfcortes** [comment]
Right, but ```DeformationOut.nii.gz``` is the diffeomorphism obtained from integrating (for example) from t = 0 to t = 0.5. If I wanted to obtain the underlying velocity field, would I just need to differentiate afterwards? @ntustison

**Comment by ntustison** [comment]
No, that wouldn't work.  You'd probably have to figure out how many time points would be needed for your specified time interval and run the registration accordingly.
