### ISSUE TITLE
Registration of aal atlas 3 (MNI space) in native DWI space

### ISSUE THREAD

**Issue by diogenesbispo** [ANTsX/ANTs#1077]
Dear,

How do I register an aal 3 atlas (MNI space) in the native space of the DWI image?

I already have a "antsRegistration" from the subject's T1 image to the subject's DWI image:

antsRegistration --dimensionality 3 --float 0\
        --output [output,outputWarped.nii.gz,outputInverseWarped.nii.gz]\
        --interpolation Linear --use-histogram-matching 0\
        --winsorize-image-intensities [0.005,0.995]\
        --initial-moving-transform [$b0,$t1,1]\
        --transform Rigid['0.2']\
        --metric MI[$b0,$t1,1,32,Regular,0.25]\
        --convergence [500x250x125x50,1e-6,10] --shrink-factors 8x4x2x1\
        --smoothing-sigmas 3x2x1x0\
        --transform Affine['0.2']\
        --metric MI[$b0,$t1,1,32,Regular,0.25]\
        --convergence [500x250x125x50,1e-6,10] --shrink-factors 8x4x2x1\
        --smoothing-sigmas 3x2x1x0\
        --transform SyN[0.1,3,0]\
        --metric MI[$b0,$t1,1,32]\
        --metric CC[$fa,$t1,1,4]\
        --convergence [50x25x10,1e-6,10] --shrink-factors 4x2x1\
        --smoothing-sigmas 3x2x1

Thanks.

**Comment by ntustison** [comment]
If you can do the first image pair, what difficulty are you having with applying the same, or similar, command to the second pair?

**Comment by diogenesbispo** [comment]
The first registration (antsRegistration) was carried out in the TractoFlow pipeline (https://tractoflow-documentation.readthedocs.io/en/latest/). So I would like to use it to register the atlas aal in the same native DWI space.
The sequence would be:
1) Register T1 native space in the DWI native space - T1-> DWI (already done in TractoFlow).
2) Register T1 native space in T1 in standard space (MNI) - T1-> T1MNI
3) Reverse transformation of the register (2) - T1MNI-> T1
4) Concatenated transformation of the registries (1) and (2) - T1MNI-> T1-> DWI
5) Apply concatenated transformation to the aal atlas (-interp nearestneighbour)
That's right?

**Comment by cookpa** [comment]
antsApplyTransforms -d 3 -r $b0 -n GenericLabel -t output1Warp.nii.gz -t output0GenericAffine.mat -t [ t1ToMNI0GenericAffine.mat, 1 ] -t t1ToMNI1InverseWarp.nii.gz -i labelsMNI.nii.gz -o labelsDWI.nii.gz 

Assuming here that you used MNI as the fixed image and $t1 as the moving image in step (2).

**Comment by diogenesbispo** [comment]
I was successful in processing antsRegistration and antsApplyTransforms. However, I had two doubts and would like to clarify:
1) I used the following command to register the subject's T1 sequence to the MNI space:

antsRegistration --dimensionality 3 --float 0 --output [t1ToMNI,t1ToMNIWarped.nii.gz,t1ToMNIInverseWarped.nii.gz] --interpolation NearestNeighbor  --winsorize-image-intensities [0.005,0.995] --use-histogram-matching 1 --initial-moving-transform [mni.nii.gz,t1.nii.gz,1] --transform Rigid['0.1'] --metric MI[mni.nii.gz,t1.nii.gz,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0 --transform Affine['0.1'] --metric MI[mni.nii.gz,t1.nii.gz,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0 --transform SyN[0.1,3,0] --metric CC[mni.nii.gz,t1.nii.gz,1,4] --convergence [100x70x50x20,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0

The file t1ToMNIWarped.nii.gz showed an image with slight distortion of the cortex. Is there anything I could adjust?

2) Atlas aal 3 was created in the MNI space (colin27 single-subject). When superimposing the MNI and aal3 atlas images, small areas with no overlap are observed. These discrete distortions are transferred to the transformations.

What could I do to resolve this?

Thanks.

**Comment by cookpa** [comment]
Registration can be regularized by changing `SyN[0.1,3,0]` to `SyN[0.1,3,0.5]`.

Label sets sometimes don't overlap as desired for various reasons. The ImageMath command PropagateLabelsThroughMask will fill in missing labels in a mask region.
