### ISSUE TITLE
Visualizing the .nii.gz velocity field after antsRegistration

### ISSUE THREAD

**Issue by gfcortes** [ANTsX/ANTs#1088]
After running a typical antsRegistration with ```-z 0``` argument, it outputs an ```output0VelocityField.nii.gz``` file. Opening the velocity field in ITK-SNAP gives the following outputs for each vector component:
<p float = "left">
<img width="365" alt="Screen Shot 2020-09-27 at 10 23 15 PM" src="https://user-images.githubusercontent.com/52980859/94384301-3f6acb00-0110-11eb-97b1-4d49431ba34e.png">
<img width="362" alt="Screen Shot 2020-09-27 at 10 23 41 PM" src="https://user-images.githubusercontent.com/52980859/94384306-442f7f00-0110-11eb-8c19-3688035037e3.png">
</p>

This is not an intuitive visualization for me and I would much rather have a concrete visualization such as a velocity field or mesh grid. How would one go about doing this for an .nii.gz formatted velocity field?

_antsRegistration call for reference:_
```
dim=2
m=data/c.nii.gz
f=data/chalf.nii.gz
its=[1x1x1x1x0,0,5]   
smth=8x6x4x2x1vox
down=8x6x4x2x1
/opt/ANTs/bin/antsRegistration -d $dim  \
                   -m CC[ $f,$m, 0.5, 0 ] \
                   -m meansquares[ $f,$m, 1, 0 ] \
                   -t tvf[ 2.0, 8, 1,0.0, 0.05,0 ] \
                   -c $its  \
                   -s $smth  \
                   -f $down \
                   -u 1 \
                   -o output \
                   -z 0
```

**Comment by cookpa** [comment]
In ITK-SNAP, open the layer inspector and change multi component view from "single component". There should be an option for deformation grid

**Comment by gfcortes** [comment]
This is all I'm seeing.
<img width="637" alt="Screen Shot 2020-09-27 at 11 18 00 PM" src="https://user-images.githubusercontent.com/52980859/94387304-c2dbea80-0117-11eb-9287-d03bfacb5756.png">

**Comment by cookpa** [comment]
Oh. Sorry. Then I'm not sure if ITK-SNAP supports 2D grid display. It works for 3D warp fields.

One option would be to make a 3D image with k=1 and the z-component set to 0. 

Otherwise I'd have to suggest asking on the ITK-SNAP users list

**Comment by cookpa** [comment]
I don't know why I didn't think of this previously, but `CreateWarpedGridImage` will make a grid image for a 2D warp field.
