### ISSUE TITLE
SyN registration of EPI to 3D T2 FLAIR or how to properly brain extract

### ISSUE THREAD

**Issue by NitramNimod** [ANTsX/ANTs#1089]
Hello!

As the head line states, my issue is related to registering common EPI images (here: unweighted b=0 diffusion sequence images; Siemens MDDW) to a 3D T2-weighted FLAIR sequence.
My first problem I'm not able to solve is a proper brain extraction of the EPI image. The T2 FLAIR is close to perfect, when using antsBrainExtraction.sh, means a very close "shave" to the gray matter boundaries and nice removal of surrounding CSF. The EPI, on the other hand,  has lots of residues of CSF and other noise surrounding the brain.
As the intensities histograms for the different tissues between these sequence types differ very much, I presume a good brain extraction for a successful registration is imperative.
The other, perhaps minor question: which metrics would be optimal for this kind of data/registration? Perhaps this is a special problem and needs special treatment? Sounds desperate, yes…
Any hints or tricks I could apply to improve the results would be highly welcome! If you need any testing data, I can provide it.

Thanks in advance and best regards,
Martin

**Comment by ntustison** [comment]
Before suggesting anything, can you post a sample EPI?

**Comment by NitramNimod** [comment]
I uploaded two volumes, the "raw" one and the already bias and noise corrected one.
(BTW, don't know if it's new to you: noise correction here only works with the Gaussian model, not the Rician noise model. The latter eats "holes" into the volume…)
[nodif_N4_denoise_N4.nii.gz](https://github.com/ANTsX/ANTs/files/5299735/nodif_N4_denoise_N4.nii.gz)
[nodif.nii.gz](https://github.com/ANTsX/ANTs/files/5299736/nodif.nii.gz)

**Comment by ntustison** [comment]
Relatively speaking, we haven't done a whole lot of non-T1-weighted application of ``antsBrainExtraction.sh``.  However, we have done some work over at ``ANTsPyNet/ANTsRNet`` which you might want to check out.  Attached is the result from the following code:
```
>>> import ants
>>> import antspynet
>>> epi = ants.image_read("nodif.nii")
>>> probability_mask = antspynet.brain_extraction(epi, modality="t2", verbose=True)
>>> ants.image_write(ants.threshold_image(probability_mask, 0.5, 1, 1, 0), "nodif_mask.nii.gz")
```
[nodif_mask.nii.gz](https://github.com/ANTsX/ANTs/files/5300040/nodif_mask.nii.gz)

**Comment by NitramNimod** [comment]
Hi,

thanks for the effort, but this mask is not much better than all the other results I had so far. And here parts of the frontal lobe are missing in the mask.
The reason I'm doing this at all is, that I have MS lesion maps that are derived from the FLAIR image and I want the DWI data (or derived diffusion index images) to be spatially normalized, incorporating those lesion maps. The distortions of the DWI and FLAIR are significantly and non-linearly different, so I need a proper registration between those images.

Is there any non-miraculous solution for this problem?

Best,
Martin

**Comment by ntustison** [comment]
If none of those work and you don't have a same-subject reference image that you can use, then you can try the more computationally expensive joint label fusion approach.

**Comment by stnava** [comment]
you may not need brain extraction for within subject distortion correction

brian

**Comment by cookpa** [comment]
Can you share a T2 image for the same session?

**Comment by NitramNimod** [comment]
Sorry for the delay! I wanted to share a face obscured full head image, but at the moment I have no working tool for it. So here is the brain extracted version with the respective mask image, as produced by antsBrainExtraction.
[3D_FLAIR_N4_denoise_N4_brain_mask.nii.gz](https://github.com/ANTsX/ANTs/files/5311752/3D_FLAIR_N4_denoise_N4_brain_mask.nii.gz)
[3D_FLAIR_N4_denoise_N4_brain.nii.gz](https://github.com/ANTsX/ANTs/files/5311753/3D_FLAIR_N4_denoise_N4_brain.nii.gz)

**Comment by NitramNimod** [comment]
Not really nice, but if you need skull and neck, here is a face edited version (without bias and noise correction).
[3D_FLAIR_1mm_defaced.nii.gz](https://github.com/ANTsX/ANTs/files/5311853/3D_FLAIR_1mm_defaced.nii.gz)

**Comment by cookpa** [comment]
Thanks, I ran this script using the brain-extracted T2

https://github.com/ftdc-picsl/dtProcessing/blob/master/preproc/distCorrDiffToStructural.pl

Here's the output

[diffToStructural_DWIBrainMask.nii.gz](https://github.com/ANTsX/ANTs/files/5319701/diffToStructural_DWIBrainMask.nii.gz)

**Comment by NitramNimod** [comment]
Hey, thank you very much!
If I understand correctly, you are registering the non-brain-extracted B0 to the brain-extracted T2-FLAIR? And then use the inverse for transforming the T2 brain mask to the B0? And the only secret is BSplineSyN?
Shouldn't one always use either brain-extracted or non-extracted images, but not a mixed image pair? Is their an explanation why this works at all?

Thanks for the efforts, I really appreciate it! :)

**Comment by cookpa** [comment]
Yes, it mostly works on my data because the registration is intra-subject and intra-session, so a rigid initialization gets us close to the solution. I also use the T2w brain mask as a metric mask, to try to further prevent a mismatch. 

In general, I would not recommend trying to register brain-extracted to non-extracted images.

**Comment by NitramNimod** [comment]
I had the time to test your example code and changed the procedure a bit. Even if not recommended, I'm registering the low-res B0 to the T2 FLAIR (the coarse mask for the B0 produced by FSL BET is loose enough to contain most of the T2), but in the end it is not really satisfactory. As I can't get rid of the CSF in the B0 image, a proper registration at the outer border of the brain is not possible for me here. At least this could be enough to transform the lesion maps of the T2 to the B0.
Thanks for your help!

```bash
ImageMath 3 xfms/${fixedName}_LAPLACIAN.nii.gz Laplacian ${fixed}.nii.gz 1.5 1
ImageMath 3 xfms/${movingName}_LAPLACIAN.nii.gz Laplacian ${moving}.nii.gz 1.5 1

cmd="antsRegistration"
	cmd="${cmd} --output ["
	cmd="${cmd} ${outputPath}/${outputPrefix}_,"
	cmd="${cmd} ${outputPath}/${outputPrefix}_Warped.nii.gz,"
	cmd="${cmd} ${outputPath}/${outputPrefix}_InverseWarped.nii.gz"
	cmd="${cmd} ]"
	cmd="${cmd} --dimensionality 3"
	cmd="${cmd} --float 1"
	cmd="${cmd} --verbose 1"
	cmd="${cmd} --collapse-output-transforms 1"
	cmd="${cmd} --use-histogram-matching 0"
	cmd="${cmd} --transform Rigid[0.1]"
	cmd="${cmd} --metric Mattes[ ${fixed}.nii.gz, ${moving}.nii.gz, 1, 16, Regular, 0.25 ]"
	cmd="${cmd} --convergence [ 30x30x0, 1e-7,10 ]"
	cmd="${cmd} --shrink-factors 3x2x1"
	cmd="${cmd} --smoothing-sigmas 2x1x0vox"
	cmd="${cmd} --masks ${fixed}_mask.nii.gz"
	cmd="${cmd} --transform BSplineSyN[ 0.2, 40, 0, 3 ]"
	cmd="${cmd} --metric CC[ ${fixed}.nii.gz, ${moving}.nii.gz, 0.5, 4 ]"
	cmd="${cmd} --metric CC[ xfms/${fixedName}_LAPLACIAN.nii.gz, xfms/${movingName}_LAPLACIAN.nii.gz, 0.5, 4]"
	cmd="${cmd} --convergence [ 30x30x0,1e-7,10 ]"
	cmd="${cmd} --shrink-factors 2x2x1"
	cmd="${cmd} --smoothing-sigmas 1x0x0vox"
${cmd}
```

**Comment by NitramNimod** [comment]
After lots of testing and trying multiple templates (even FLAIR templates, hard to come by, but always mediocre quality, btw) I remembered Brian's comment. Indeed, brain extraction is not needed. Even the close to invisible skull/head of the B0 image is sufficient for a satisfying registration between B0 and FLAIR. So, intra-subject: don't do brain extraction.
