### ISSUE TITLE
antsRegistration runtime memory requirement estimation

### ISSUE THREAD

**Issue by jamesjcook** [ANTsX/ANTs#1091]
**Describe the problem**

I'm working on a cluster and trying to properly request memory for my antsRegistration job.
My working expectation for memory assumes everything is 64-bit, with 3x images + 4x warps, with every warp counted as 3x images. 

For my current work, the images are 813x1317x611, which makes my guess <75GiB =  (8x(3 + 4x3) x (813x1317x611)) / 2^30
My cluster nodes have 256GiB of memory, and these jobs failed due to insufficient memory.

(I've gone as far as running 1-2 iterations at each level and its both more than my estimate, and less than the eventual requirement.)

I moved this job to a super Windows 2016 server with 1.5TB of memory, and was able to run to completion. 
My attempt to to capture the memory info failed due to the performance monitor log I set up corrupting during runtime.

Random samples of memory usage by looking at taskmanager showed 200,000-300,000 MB of memory usage

**To Reproduce**
My simplified command line, 
antsRegistration -v 1 -d 3 -m CC[ FIXED.nhdr,MOVING.nii.gz,1,4,None ]  -o MOVING_TO_FIXED_   -c [ 100x100x100x60,1e-8,20 ] -f 8x4x2x1 -t SyN[0.5,3,0.5] -s 4x2x1x0vox  -r MOVING_to_FIXED_affine.mat  -u;
and log
[antsRegistration.log](https://github.com/ANTsX/ANTs/files/5307830/antsRegistration.log)

**System information**
Red Hat Enterprise Linux Server release 7.7 (Maipo)

HPC cluster using bright management software with the
SLURM job scheduler

**ANTs version information**
Two versions of ants tested, one stale, 
antsRegistration --version
ANTs Version: 2.2.0.dev64-g7e85d
Compiled: Nov 28 2017 10:58:06

One relatively fresh
antsRegistration --version
ANTs Version: 2.3.4.dev170-g11953
Compiled: Aug 12 2020 16:41:45

**Additional information**
I've tried to get a handle on memory usage by running tests on our cluster at different maximum shrink factors, with differing counts of iterations, but I'm not able to connect the result concretely to my expectations.
Using max shrink, 2,4,8 all ran to completion, 1 was killed at the specified memory usage.
Blanks are tests I didnt bother to run.

Max res Scale | Iter 			test | Iter 			test | Iter 			test | Iter 			test | Iter 			test
-- | -- | -- | -- | -- | --
Iteration Count  | 1 | 5 | 10 | 20 | 40
1 | 252956. | 251613. |   |   | 250351.
2 | 79279. | 81993. | 81462. |   |  
4 | 52354. | 52583. | 54098. | 54145. | 53863.
8 | 50619. | 50535. | 50679. | 50679. | 50699.

**Comment by cookpa** [comment]
Thanks for the thorough report. It can be really hard to accurately estimate how much memory a process is really using. Your numbers suggest that the number of iterations doesn't influence the memory consumption, which makes sense to me.

But it looks like the reported memory is not really scaling with the resolution. Just to confirm, for the reduced max res, are you setting "-f 8x4" etc? Because if you do "-f 8x4x2x1 -c 1x1x0x0" it will still need to compose a full-resolution warp field.

**Comment by gdevenyi** [comment]
Hi, I published some benchmarking work, its a bit old now, but I think the general ideas are helpful:
https://github.com/gdevenyi/antsRegistration-benchmarking

**Comment by jamesjcook** [comment]
@cookpa the max scale was where I ended the -f option, eg, 4 means either -f 8x4, or -f 4. To clean reporting here, I filtered it to only the latter.   My expectation on the mem usage with a top shrink > 1 was (the memory cost of the chosen shrink level) + (the memory cost of input volumes).  Time permitting I plan to go back and do the downsample outside the ants command to get a better look at the results.

@gdevenyi I saw your benchmark results before I launched into this, and I unfortunately wasn't able to understand it well enough. I recognized the expected curve of mem requirements as voxels got smaller, but I couldnt see how to relate voxels in mm to my voxel count. Between that and hope that ANTs has changed over the last 4 years I launched a batch of tests while I had a minute.

**Comment by cookpa** [comment]
That sounds correct. I'm trying to think of where all the memory is going.

We have the fixed and moving images. There's also a point set for metric sampling in the virtual space. With dense sampling that's effectively another vector image, as it's one 3D point per voxel in the image. Then there's the fixed and moving image intensities at those sample points.

Warp fields will cost more than 3x(image size) because the vectors are not primitive types, they are not just three scalar images of type double or float. The pixel for a displacement field is a vector object, so each vector is going to be larger than the three spatial coordinates it represents, and we also need pointers to the vector at each voxel.

**Comment by gdevenyi** [comment]
> @gdevenyi I saw your benchmark results before I launched into this, and I unfortunately wasn't able to understand it well enough. I recognized the expected curve of mem requirements as voxels got smaller, but I couldnt see how to relate voxels in mm to my voxel count. Between that and hope that ANTs has changed over the last 4 years I launched a batch of tests while I had a minute.

Good point, I've reconceptualized how I think about some of this since writing that, I should probably do a new set of runs on a more modern build/system and re-generate my results.

**Comment by jamesjcook** [comment]
> The pixel for a displacement field is a vector object,

Can you elaborate on this enough to estimate?   I'm trying to read carefully, but i'm not terribly familiar with ITK and its data types.  I presume pointers are ints, so it sounds like I'd need to add one more "volume" for those.   A simple implementation of the vectors would be 3x voxels right?  So, that guess should be correct, but I need to add the overhead for the class(which could easily overshadow the 3xVox),

Do you know which vector class I should look at?(my best guess is itk::VectorImage)

**Comment by ntustison** [comment]
No, as shown on the [doxygen page](https://itk.org/Doxygen/html/classitk_1_1VectorImage.html)

```
Conceptually, a VectorImage< TPixel, 3 > is the same as a Image< VariableLengthVector< TPixel >, 3 >.
```

Instead, our 3-D displacement fields are 

```
Image< Vector< TPixel, 3 >, 3 >.
```

**Comment by jamesjcook** [comment]
Does that mean 9x values per voxel co-ordinate? +(vector overhead X nvoxels) + image class overhead?

**Comment by cookpa** [comment]
From the Doxygen, it looks like the memory allocation should be 3*(sizeof(pixel type)) as you first estimated. The vector objects are created at run time when a pixel value is queried, they are not stored.
