### ISSUE TITLE
antsMotionCorrStats output

### ISSUE THREAD

**Issue by dlupinsky** [ANTsX/ANTs#1094]
the output file  MOCOparams.csv indicates 12 parameters, how does one know what information these represent? 

MetricPre,MetricPost,MOCOparam0,MOCOparam1,MOCOparam2,MOCOparam3,MOCOparam4,MOCOparam5,MOCOparam6,MOCOparam7,MOCOparam8,MOCOparam9,MOCOparam10,MOCOparam11

0,-1.14092350413256,0.994067323642393,-0.00103253552404307,-0.0013238457349336,4.43118069233336e-05,0.992399935145715,0.000297309510208729,0.000470010652374613,0.00251714848763369,0.999093036598948,-0.065400772106337,-0.136386228911491,0.0584662385136057

**Comment by gdevenyi** [comment]
Assuming you did an affine:

> This class provides several methods for setting the matrix and vector defining the transform. To support the registration framework, the transform parameters can also be set as an Array<double> of size (NDimension + 1) * NDimension using method SetParameters(). The first (NDimension x NDimension) parameters defines the matrix in row-major order (where the column index varies the fastest). The last NDimension parameters defines the translation in each dimensions.

https://itk.org/Doxygen/html/classitk_1_1AffineTransform.html
