### ISSUE TITLE
Avoid using proprietary .mat files

### ISSUE THREAD

**Issue by tbenst** [ANTsX/ANTs#1099]
Thanks for this great package!!

**Is your feature request related to a problem? Please describe.**
I am not a matlab user, and the current `qmSTutqns7_warp0GenericAffine.mat` file that gets created can be opened by Python's `scipy.io.loadmat`but not Julia's `Mat.jl`. I'm guessing this is because the .mat file is v4 or earlier..? Old proprietary formats become increasingly hard to open as time goes on, and it would be great to use open formats for this wonderful open-source package.

**Describe the solution you'd like**
Switch to any other open format, like hdf5, csv, feather, etc. Or if we must use .mat, switch to v7 which is based on HDF5 and can be reaad from many languages.

**Describe alternatives you've considered**
Buying the $2150 MATLAB license :rofl:

**Comment by gdevenyi** [comment]
There's are not Matlab files, they are ITK binary transform files.

**Comment by tbenst** [comment]
Hm, I'm pretty sure it's explicitly written to be compatible with the .mat spec for v4 or earlier, and I think ITK internally refers to these files as `MatlabTransformIO` unless I'm mistaken. In any case, if I understand correctly from the ANTs manual the code currently uses [`itk::TransformFileWriter`](https://itk.org/Doxygen/html/namespaceitk.html#ac934724a2f28e702e215ad36f6f3bf08), which I believe is now deprecated.

Documentation is a bit tough to sort through. SimpleITK more cleanly lists the available options for the new fileIO api: https://simpleitk.readthedocs.io/en/master/IO.html.

This is a great package, thanks so much!

**Comment by gdevenyi** [comment]
ConvertTransformFile can be used to convert to the text-based tfm format if you want to use a reader that doesn't support the itk binary form.

**Comment by tbenst** [comment]
Good to know, thanks! Now that I’ve used ANTs a bit more it’s not really a big deal since the transform file is mainly used internally by the program, but I could imagine scenarios where I might want to read it in, and I’m glad there are workarounds.
