### ISSUE TITLE
Salvage 'antsMultivariateTemplateConstruction2' that timed out?

### ISSUE THREAD

**Issue by erincamille** [ANTsX/ANTs#1101]
Hi there,

I am running 'antsMultivariateTemplateConstruction2.sh' on some CT images. My issue is that I am using a system of shared resources, and my registration takes a long time (>1 week). The system is using SLURM, but I am not able to run the script in parallel there due to issues that I won't get into here.

I am wondering what the best way is to salvage the work my script has done over several days if it ends up timing out. For exmaple, should I use the 'template0' as the -z parameter? Can I use the 'repaired' images as inputs? 

Thanks in advance.

**Comment by gdevenyi** [comment]
Yes, make sure you don't have -r, disable N4, and use the in progress template for -z

**Comment by erincamille** [comment]
Thank you, I'll try that.
