### ISSUE TITLE
How to transform labels into a study template 

### ISSUE THREAD

**Issue by Marina-Blmz** [ANTsX/ANTs#1105]
Hello experts,

I want to transform an image with labels into my study template space. So I have 3 images: atlas, labels on this atlas, and my template space image.
First thing that came to my mind was to do the following:

   1. rigid body registation of the atlas to the template with flirt

  2.  antsRegistrationSyN.sh -d 3 -f Template.nii.gz -m Atlas.nii.gz -o AtlastoTemplate_ -j 1 -p f

  3.  antsApplyTransforms -d 3 -i labels.nii.gz -o labels_on_template.nii.gz -t AtlastoTemplate_1InverseWarp.nii.gz -t AtlastoTemplate_0GenericAffine.mat -n GenericLabel --verbose -r Template.nii.gz

It didn’t work though, as the resulting labels_on_template.nii.gz is quite deformed.

Any suggestions on what I could have done better to make it work would be greatly appreciated!

Cheers,
Marina

**Comment by ntustison** [comment]
Try replacing step 3 with

```
antsApplyTransforms -d 3 -i labels.nii.gz -o labels_on_template.nii.gz -t AtlastoTemplate_1Warp.nii.gz -t AtlastoTemplate_0GenericAffine.mat -n GenericLabel --verbose -r Template.nii.gz
```

**Comment by Marina-Blmz** [comment]
Hey Nick! thanks a lot for your reply - it helped to fix the issue!
