### ISSUE TITLE
Properly restricting SyN to one direction after Rigid alignment

### ISSUE THREAD

**Issue by dangom** [ANTsX/ANTs#1106]
I acquired a distorted EPI image and a (not nearly as distorted) GRE image.
I would like to register the EPI (moving) to the GRE (target), first by applying a rigid-body transform and then a non-linear transform to account for distortions. To simplify the problem, I want to constrain the SyN transform to only operate on the phase encoding direction.

My question is: If I first apply a rigid body transform, how can I properly constrain the SyN algorithm if the PE direction is no longer parallel to the image axis?

One possible solution that I found, but I'd be happy to hear your opinions:

1. First register the GRE (moving) to the EPI (target) using a rigid body registration. Call the output GRE_space-EPI
2. Register the EPI (moving) to GRE_space-EPI (target) using only the SyN. Call the output EPI-undistorted.
3. Concatenate transforms, first applying the EPI-undistorted then the inverse GRE_space-EPI to obtain EPI-undistorted_space-GRE.

Does this make sense or would there be a better approach?

**Comment by ntustison** [comment]
Why can't you do all your ``transformation-restricting`` registrations (``-g``) in the reference space where the PE is parallel to an image axis and then move it out of that space once the registrations are complete?

**Comment by dangom** [comment]
Thx that sounds much simpler I will try that and report back.
