### ISSUE TITLE
how to install and build antsSurf

### ISSUE THREAD

**Issue by Fionayjx** [ANTsX/ANTs#1107]
I have no problem running the registration, my issue comes when I try to run the visualizationexample provided on the github. It says that the antsSurf is not found. I wonder how to install and build the antsSurf. I used the Superbuild to build the ANTs. Tanks!

**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: [ Mac OS]
 - OS version: [e.g. 10.13.6]
 - Type of system: [Desktop]
 
 
**ANTs version**
I downloaded on 10/22/2020

**Build configuration and logs**
Please attach the following files (relative to your build directory)

  - build.log (the terminal output from make)
[build.log](https://github.com/ANTsX/ANTs/files/5435606/build.log)

  - CMakeCache.txt
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/5435607/CMakeCache.txt)

  - CMakeFiles/CMakeError.log
[CMakeError.log](https://github.com/ANTsX/ANTs/files/5435611/CMakeError.log)

  - CMakeFiles/CMakeOutput.log
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/5435614/CMakeOutput.log)

**Additional context**

**Comment by gdevenyi** [comment]
``-DUSE_VTK=ON``

**Comment by Fionayjx** [comment]
> `-DUSE_VTK=ON`

Hi, thanks for your reply. Could you elaborate more? I am sorry I am not familiar with these. Thanks!!

**Comment by ntustison** [comment]
You would need to [compile ANTs directly from source](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS).  One of the CMake options, which is off by default, is installing VTK.  You would need to turn that on and then you should also be able to compile those visualization programs you're asking about.

**Comment by Fionayjx** [comment]
> You would need to [compile ANTs directly from source](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS). One of the CMake options, which is off by default, is installing VTK. You would need to turn that on and then you should also be able to compile those visualization programs you're asking about.

Thanks for your detail explanation. But I still do not know how to turn it on? I used the Superbuild to build the ANTs (i.e., simply to run the installANTs.sh). I wonder what changes should I make in order to do this? Thank so much!!!!

**Comment by ntustison** [comment]
If using the script, please add what @gdevenyi specified (``-DUSE_VTK=ON``), somewhere in [this section](https://github.com/cookpa/antsInstallExample/blob/master/installANTs.sh#L40-L47) of the script.

**Comment by Fionayjx** [comment]
Thank you so much for the detailed instruction. Yes, it works!!

**Comment by cookpa** [comment]
I updated the Wiki and the canned example script to make note of this.
