### ISSUE TITLE
ANTs report mismatched version numbers

### ISSUE THREAD

**Issue by weiwei2021** [ANTsX/ANTs#1109]
**Describe the problem**
Hellow,
    I compiled and installed ANTs 2.3.4 according to ANTs wiki. But when I use the command (N4BiasFieldCorrection --version) to query the version number of ANTs, the version number obtained is 0.0.0. This makes nipype exit abnormally due to the failure of checking the ANTs version. I avoided this error by installing ANTs 2.3.1, but the reported version is 2.2.0, which still does not match. This may be caused by the incorrect configuration of the software version in the ANTs/CMakeLists.txt file.

**To Reproduce**
Download the release code package, compile and install through cmake, and then query the software version.

**System information (please complete the following information)**
 - OS: Ubuntu
 - OS version: 18.04.5
 - Type of system: Desktop

**ANTs version information**
 - ANTs code version: 2.3.4 / 2.3.1
 - ANTs installation type: Compiled from source

**Comment by ntustison** [comment]
You might want to try recompiling.  I just did a fresh install and I couldn't reproduce the error:

```
% ./N4BiasFieldCorrection --version
ANTs Version: 2.3.4.dev203-g952e7
Compiled: Oct 29 2020 08:11:24
```

**Comment by cookpa** [comment]
Did you get the source from a git clone? CMake uses git to find version information, so if you downloaded a ZIP file, it won't know what to do.

You can add a manual version string with the CMake advanced option "ANTS_SNAPSHOT_VERSION". I don't know if this will help nipype, because I made the formatting different - this was so I could tell how version information was encoded into binaries.

**Comment by weiwei2021** [comment]
@ntustison @cookpa Thanks for your help. I downloaded the source code from the release package for hoping that the functions used are stable.  The download entry is the link on the right side of the ANTs project github homepage. The file i downloaded is ANTs-2.3.4.tar.gz, the url is https://github.com/ANTsX/ANTs/archive/v2.3.4.tar.gz.
@cookpa I follow your suggestion to compile the source with “cmake -DCMAKE_INSTALL_PREFIX=/opt/ANTs -DANTS_SNAPSHOT_VERSION=2.3.4 ..”.  This is effective to solve nipype's error. thanks.
The version query result:
$N4BiasFieldCorrection --version
ANTs Version: snapshot-2.3.4
Compiled: Oct 30 2020 10:10:00
