### ISSUE TITLE
Is there GPU accelerated method?

### ISSUE THREAD

**Issue by NeuZhangQiang** [ANTsX/ANTs#1112]
I am use antsRegistration method, and I find it's very useful. However, I find the cost time is very long. Is there any GPU based antsRegistration method?

Best wishes,
Qiang

**Comment by ntustison** [comment]
No, there is not a GPU version of ``antsRegistration``.  However, the "long" processing time might be due to suboptimal parameters.  I would start with the ``antsRegistrationSyNQuick.sh`` script which is relatively quick while providing good results.
