### ISSUE TITLE
How to incorporate lesion masks in antsLongitudinalCorticalThickness.sh?

### ISSUE THREAD

**Issue by dbrennan44** [ANTsX/ANTs#1113]
where should a lesion mask be specified during a call to antsLongtiduinalCorticalThickness.sh?

**Comment by ntustison** [comment]
That feature is not implemented yet and I don't know how soon we'll get to it.  But we can certainly add this as a feature request.

**Comment by dbrennan44** [comment]
Thanks, it would be helpful as a feature.

Workaround is just to do the individual steps of the pipeline, but adding in lesion masks during registration, correct?

**Comment by ntustison** [comment]
No, there's more to it than that.

**Comment by dbrennan44** [comment]
do you have any recommendations on starting or how to build this pipeline (what to read)? I have longitudinal data but want to incorporate the lesions during cortical thickness estimation

**Comment by ntustison** [comment]
If you can sort out how the lesion masking is organized in ``antsCorticalThickness.sh`` and you're familiar with the longitudinal steps discussed [here](https://pubmed.ncbi.nlm.nih.gov/31356207/), then you might be able to figure it out.

**Comment by dbrennan44** [comment]
that's enough to get me started. Thanks again as always for your help

**Comment by jeffduda** [comment]
I actually have some code that incorporates lesion masks into the
longitudinal pipeline. However it was designed for the following criteria
1) Lesion masks only exist for the first time-point (or not at all)
2) Masks are not used for the subject specific template creation, only for
registration between the SST and the group template
Let me know if that is aligned with what you are looking for.
-Jeff Duda

**Comment by dbrennan44** [comment]
Hi Jeff,
I am actually in Hoon Kim's lab and was hoping to recreate your pipeline on his dataset, which I believe is the same one you're referring to. Let me know what is a good way to reach you.

Daniel

**Comment by jeffduda** [comment]
email me at jeffrey.duda@pennmedicine.upenn.edu
