### ISSUE TITLE
Optimal parameters for BSplineSyN and Atropos

### ISSUE THREAD

**Issue by antogeo** [ANTsX/ANTs#1117]
[ants_params.txt](https://github.com/ANTsX/ANTs/files/5608412/ants_params.txt)
Dear ANTs developers,

I would like to use structural MRIs (gray matter modulated images) of healthy subjects from many datasets. In order to achieve better generalization and permit in the future adding subjects from new datasets in the analysis, I used ICBM templates and did not create one from data.
I performed the steps described here [1] adapting the idea of segmenting in the native space. For the involved parameters I tried to extract information from your papers and the forums (sourceforge and github). Those parameters that I could not find specific information for or I was not sure about, I kept the default values. For setting the parameters of BsplineSyn I used your paper [2] but not everything was clear to me e.g in the listing script you mention "--convergence 100x70x50x20" but in the Results' session it is written "The number of iterations per level were {100, 100, 70, 20}". Is not the same thing or have I missed something?
Following your recommendation regarding evaluation of scientific software [3], "demand that the algorithm developers provide default parameters for the comparative context being investigated", I would like to ask you to provide me with the optimal parameters for the AntsRegistration (I use Translation, Rigid, Affine, BSplineSyN) and the Atropos commands, so that I can extract the GM modulated volumes for healthy subjects of wide age range. I have attached a text file with the parameters I currently use in case that it facilitates the discussion.

Thank you for your time!
Georgios

[1]: https://sourceforge.net/p/advants/discussion/840261/thread/a568bf63/
[2]: Explicit B-spline regularization in diffeomorphic image registration
[3]: Instrumentation bias in the use and evaluation of scientific software: recommendations for reproducible practices in the computational sciences

**Comment by ntustison** [comment]
The scripts ``antsRegistrationSyN.sh`` and ``antsRegistrationSyNQuick.sh`` were written in conjunction with the publication [2] and constitute sets of recommended parameters.  I would start with ``antsRegistrationSyNQuick.sh`` because it is *much* faster and is sufficient for most applications.

**Comment by antogeo** [comment]
Thank you for replying so fast!
Assuming that time of processing not a problem, would you still recommend antsRegistrationSyNQuick.sh?
I noticed that starting with a translation helps avoiding some misalignment (in the attached image u can see results with translation and without). 
What about Atropos' parameters?
![misaligned](https://user-images.githubusercontent.com/7447851/100469985-a3414e00-30d7-11eb-8b82-a644dbe88536.jpeg)

**Comment by ntustison** [comment]
> Assuming that time of processing not a problem, would you still recommend antsRegistrationSyNQuick.sh?

Perhaps, depends on the problem.

Translation is already included in both scripts.

For Atropos, check out the script ``antsAtroposN4.sh``.
