### ISSUE TITLE
Lesion labeling and counting during lesion filling

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#1118]
I only have a single lesion mask for a brain. The single lesion mask contains multiple lesions. 

When I attempted 'LesionFilling' with the lesion mask and its corresponding T1W image, I observed that 'lesion count' was displayed. But I could not find a way to save the lesion count. 

It would be great if the displayed lesion count and the counted lesions saved as an image file with individual lesion labels. (Probably, individual lesion labeling by some sort of continuity measure.)

If the 'LesionFilling' can count the lesions from the input lesion mask, it may have some sort of algorithms to count the lesions by distinguishing one lesion from others. If that is possible, it might be also possible to save each counted lesion as a separate label. Then, collect them all and save them as a single image file, something like lesion_labels.nii.gz along with a lesion filled image. Hence, two outputs from the 'LesionFilling' process.

**Comment by ntustison** [comment]
You can use ``LabelGeometryMeasures``, ``LabelClustersUniquely``, ``ThresholdImage``, and other programs in ANTs to do what you want.

**Comment by s-j-choi** [comment]
Thank you for your reply. I will try those modules.

**Comment by s-j-choi** [comment]
The LabelClusterUniquely does the work that I needed. However, I could not find some details about the options. 

Usage:  
LabelClustersUniquely ImageDimension clustersin.hdr labeledclustersout.hdr   sizethresh optionalBoolFullyConnected

Could you guide me on the options: 
1. sizethresh - Is this based on voxel count or volume? 
2. optionalBoolFullyConnected - Could you explain this option and how I can use it properly? An example line of a script will be greatly helpful. 

Or could you point me to what link that I can lookup?

Thank you

**Comment by ntustison** [comment]
1.  Voxel count
2.  FullyConnected =  face connectivity (vs. face+edge+vertex connectivity)

https://itk.org/Doxygen/html/classitk_1_1RelabelComponentImageFilter.html

"By default, the relabeling will also sort the labels based on the size of the object: the largest object will have label #1, the second largest will have label #2, etc. If two labels have the same size their initial order is kept."

**Comment by s-j-choi** [comment]
Thank you!

**Comment by cookpa** [comment]
> Could you suggest any method or approach? It does not need to be a script-based approach (I prefer scripts though). Will ITK-SANP be helpful on this?

ITK-SNAP and its command line companion `c3d` are very good for label manipulation. You can use the `-replace` option to merge or rename labels.

**Comment by sj-choi** [comment]
Is 'LesionFilling' available in ANTsR or ANTsRNet? I could not find it using "LesionFilling" or similar words.

**Comment by stnava** [comment]
in ANTsR, there is basicInPaint and exemplarInpainting

which are basically lesion filling.

brian
