### ISSUE TITLE
few questions/clarifications regarding antsMultivariateTemplateConstruction

### ISSUE THREAD

**Issue by dbrennan44** [ANTsX/ANTs#1120]
Hello ANTs experts, 
In trying to build a study-specific template for longitudinal CT, I ran into some issues: 

with skull, template construction failed (completed, but was not a brain image). 

without skull, worked fine.

However, I do believe the template needs skull for ensuing calls to antsCorticalThickness (-e option), and is shown as such in the paper. But, the example uses skull-stripped images. 

command is simply: 
antsMultivariateTemplateConstruction.sh -d 3 -c 2 -j 5 -r 1 -o T_skull files_skull.csv

where files_skull.csv is a csv of direct paths.

I've checked the images and they are oriented in the same direction and really not far from each other.

antsMultivariateTemplateConstruction2.sh gets stuck with "suspicious return value (2) from SVDC" when run on these data, if that's any clue.

Thanks in advance
Daniel Brennan

**Comment by cookpa** [comment]
If your images are in Hounsfield units, I can think of a couple of possibilities right away:

N4 will not work with negative intensities so you will need to turn that off.

It’s also possible that the center of mass calculation could be thrown off by negative intensities, which could undermine registration.


Sent from my iPhone

On Dec 3, 2020, at 6:36 PM, Daniel Brennan <notifications@github.com> wrote:

﻿

Hello ANTs experts,
In trying to build a study-specific template for longitudinal CT, I ran into some issues:

with skull, template construction failed (completed, but was not a brain image).

without skull, worked fine.

However, I do believe the template needs skull for ensuing calls to antsCorticalThickness (-e option), and is shown as such in the paper. But, the example uses skull-stripped images.

command is simply:
antsMultivariateTemplateConstruction.sh -d 3 -c 2 -j 5 -r 1 -o T_skull files_skull.csv

where files_skull.csv is a csv of direct paths.

I've checked the images and they are oriented in the same direction and really not far from each other.

antsMultivariateTemplateConstruction2.sh gets stuck with "suspicious return value (2) from SVDC" when run on these data, if that's any clue.

Thanks in advance
Daniel Brennan

**Comment by dbrennan44** [comment]
Thank you very much @cookpa , I recall seeing a warning regarding negative values. However, I'm not sure that explains why skull-stripped brains are processed completely fine. I will investigate and update promptly.

**Comment by dbrennan44** [comment]
dropping N4 was successful, so I believe that was the problem. 

However, the execution of the actual template is less successful than when N4 was included (without skull). So I'd like to investigate further -

The warning said "non-positive values", so can N4 not handle data where empty space is value 0?

**Comment by ntustison** [comment]
Image intensities are log-transformed.

**Comment by dbrennan44** [comment]
@ntustison still strange behavior across these images. I've run antsCorticalThickness on these images which uses N4 I believe.

is there a meaningful difference between the image intensity ranges of these two images?

[images.zip](https://github.com/ANTsX/ANTs/files/5643508/images.zip)

**Comment by cookpa** [comment]
In the case of background set to zero, you can apply a mask to only correct foreground voxels (-x). 

The difference in performance with and without skull may be more difficult to solve, because the skull is such a dominant feature in the image, and there may not be much soft tissue contrast to compete with it. 

This article may be of interest

https://www.frontiersin.org/articles/10.3389/fninf.2019.00061/full

For antsCorticalThickness, you can use a brain-extracted template as long as you skip the brain extraction step. You can do this by putting a brain mask into the output directory ahead of time. If you run with `-o ${OUTPUT_PREFIX}`, and `${OUTPUT_PREFIX}BrainExtractionMask.nii.gz` already exists, then brain extraction won't be run.

I've never run antsCorticalThickness on CT data though. It relies on accurate segmentation of white and gray matter, which might be very difficult to do.

**Comment by dbrennan44** [comment]
@cookpa apologies, bad acronym. I have longitudinal MRI data, hoping to process with longitudinal cortical thickness (CT)

**Comment by ntustison** [comment]
> is there a meaningful difference between the image intensity ranges of these two images?

There's no meaning in the absolute intensity scale in MRI.

**Comment by dbrennan44** [comment]
@ntustison I understand. I'm just not sure why the skull stripped has no issue with N4 correction when the with-skull image fails when they both include 0 as background

**Comment by ntustison** [comment]
> I'm just not sure why the skull stripped has no issue with N4 correction when the with-skull image fails when they both include 0 as background.

N4 most likely is not the issue.

> I've checked the images and they are oriented in the same direction and really not far from each other.

How are you verifying this?

**Comment by dbrennan44** [comment]
@ntustison opening them in itksnap and overlaying. I'm using only ten scans for the template

**Comment by ntustison** [comment]
Then I'd have to look at the data myself.  Can you post it?

**Comment by dbrennan44** [comment]
[here you go](https://drive.google.com/drive/folders/1Mfrj5nvQkNne4L8Qc9psk_hjhRzyK3TF?usp=sharing)

**Comment by dbrennan44** [comment]
@ntustison any insights after trying with the data? It might help my SST construction where I'm also having subpar results.

**Comment by ntustison** [comment]
I "requested access" when you first posted the data but you never responded.  And it looks like access is still restricted.

**Comment by dbrennan44** [comment]
Hi again, sorry about that. I've just accepted the request

**Comment by ntustison** [comment]
Using the following command with N4 and other typical parameters (I minimized the number of top level iterations to reduce computational time):

```
antsMultivariateTemplateConstruction2.sh -d 3 -o $PWD/T_ -r 1 -n 1 -c 2 -j 4 -i 4 -g 0.25 -t SyN -w 1 -k 1 -q 50x30x0x0 -f 6x4x2x1 -s 3x2x1x0 ./*.nii.gz
```

I get the following result

<img width="1142" alt="Screen Shot 2020-12-08 at 5 04 37 PM" src="https://user-images.githubusercontent.com/324811/101560283-c55c8b00-3977-11eb-88ae-4a604d8a1584.png">

which is in line with expectations.

**Comment by dbrennan44** [comment]
Nick,
Thank you for your commitment to helping users. This looks similar to when I ran without N4 on the skull. I will try with your command and see if it improves things.

**Comment by dbrennan44** [comment]
I ran with your command and was successful, but only after copying all images to the current folder and using *.nii.gz instead of passing a CSV with absolute paths. That seems to be the issue. Thanks again
