### ISSUE TITLE
CreateTiledMosaic producing weird output

### ISSUE THREAD

**Issue by thomshaw92** [ANTsX/ANTs#1121]
**Describe the problem**
I'm trying to create some 2D mosaics of 3D niftis.
The data are small cropped regions. When I called CreateTiledMosaic the output was mostly white with some black spots.

I rescaled the intensities between 0-100, but the output of CreateTiledMosaic is just white background again.
The images (3d) look like first attachment, the output (i used .tif) looks like second attachment)

**To Reproduce**

CreateTiledMosaic -i sub-002S0413/sub-002S0413_ses-01_T1w_N4corrected_norm_preproc_to_template_chunk_left.nii.gz -o test1.tif

(i tried the different orientations) - no errors in any output

**System information (please complete the following information)**
Many issues are specific to a particular system. Please include all information
about your computing environment.

 - OS: Ubuntu18
 - OS version: LTS
 - Type of system: Desktop
 
Using module (lmod), with the underlying ANTs build using Singularity 

**ANTs version information**

 - ANTs code version: [
ANTs Version: 2.3.3.dev168-g29bdf
Compiled: Jun  9 2020 03:44:55
]
 - ANTs installation type: [compiled from Neurodocker]

**Additional information**
![2](https://user-images.githubusercontent.com/31721414/101443074-4b70d580-3968-11eb-9ec0-0676e13f9b6f.png)
![1](https://user-images.githubusercontent.com/31721414/101443075-4c096c00-3968-11eb-8d7c-363756964ac7.png)

**Comment by ntustison** [comment]
Try using nifti as the output format.

**Comment by gdevenyi** [comment]
CreateTiledMosiac is a bit complex. Here's an example that generates some images with a label overlay.

https://github.com/CoBrALab/antsRegistration-MAGeT/blob/master/bin/mb_qc.sh

**Comment by thomshaw92** [comment]
Ok that's a good workaround @ntustison :)
```
CreateTiledMosaic -i sub-002S0413/sub-002S0413_ses-01_T1w_N4corrected_norm_preproc_to_template_chunk_left.nii.gz -o test1.nii.gz && ConvertToJpg test1.nii.gz test.jpg
```
Output looks good! 
![3](https://user-images.githubusercontent.com/31721414/101707086-3d40c780-3ad6-11eb-95d5-b28befee3c0c.png)

**Comment by ntustison** [comment]
Yes, see output description

https://github.com/ANTsX/ANTs/blob/master/Examples/CreateTiledMosaic.cxx#L1065

**Comment by thomshaw92** [comment]
Ah, so .tif wouldn't have worked anyway... Thanks again!! 😄
