### ISSUE TITLE
Persistent small shift using antsRegistrationSyNQuick.sh or antsRegistrationSyN.sh

### ISSUE THREAD

**Issue by valeryozenne** [ANTsX/ANTs#1122]
Hi, 

The code/data to replicate the issue is available 30 days at this link:
https://filesender.renater.fr/?s=download&token=5472c8db-cf91-4a68-b7e6-a7d2650742d5

### Context

Following my template issue , I'm struggling for some weeks in the registration of a mean_B0 image (moving images) on the anatomical data (fixed image). The ex-vivo sample "moved" between both acquisition, non -linear deformation is expected to give the best result but all results looks slightly shifted. 

 ### Method

I'm not incriminating antsRegistration (I'm incriminate myself) but I cannot find why I have a persistent shift after applying the transformation. The code I used is pretty simple.

* Apply N4 
* Estimate a initial transform with itksnap
* Apply the initial transform
* Check estimation
* Run antsRegistrationSyNQuick using rigid / affine / syn with the initial transform 
* ApplyTransform
* Run antsRegistrationSyN using rigid / affine / syn with the initial transform
* ApplyTransform

* Compare the results

### Initial guess using ITKsnap

![Capture d’écran de 2020-12-09 18-16-21](https://user-images.githubusercontent.com/7050315/101669722-9404bd80-3a52-11eb-869f-58ff3726b545.png)

### antsRegistrationSyN  ( -t s) 
![Capture d’écran de 2020-12-09 18-17-05](https://user-images.githubusercontent.com/7050315/101669838-b991c700-3a52-11eb-9fed-0116fad791ce.png)

### antsRegistrationSyN  ( -t a) 
![Capture d’écran de 2020-12-09 19-12-52](https://user-images.githubusercontent.com/7050315/101670171-20af7b80-3a53-11eb-855d-dfd571826e25.png)

Any help to solve this issue will be welcome

Thanks in advance,
Valéry

**Comment by ntustison** [comment]
The data is ~700 MB.  Can you provide a smaller example which demonstrates the issue?

**Comment by valeryozenne** [comment]
It is not needed anymore , I checked again my code before submitting a smaller dataset, I did one stupid mistake in applying the transformation due to a confusion in the output of ./antsRegistration call and  antsRegistrationSyN.sh.  
I still have one ongoing issue and it should be fine for some weeks
You can close the issue.

**Comment by ntustison** [comment]
Great.  Thanks.

**Comment by gdevenyi** [comment]
@valeryozenne in the future, if you had provided the complete set of commands you ran to get from inputs to the pictures you showed we likely could've caught that, but great that you did :+1:
