### ISSUE TITLE
N4BiasFieldCorrection problem 

### ISSUE THREAD

**Issue by bramcal** [ANTsX/ANTs#1123]
Hi, 

I am trying to perform Biasfield correction on a T1 anatomical image: 2D image with 2 slices. 
When I use the command: 

N4BiasFieldCorrection -d 2 -i /mnt/c/Users/.../Documents/input.nii -o /mnt/c/Users/.../Documents/input_N4_bias_corr.nii -v 

I get a 2D bias field corrected image of the first slice. 

When I run the same command with -d 3 I get the following error message: 

Running N4 for 3-dimensional images.
Mask not read.  Using the entire image as the mask.
Original intensity range:  [0, 30.9173]

   1. rescale your image to positive values e.g., [10,100].
   2. run N4 on your rescaled image.
   3. (optional) rescale the N4 output to the original
      intensity range.

Exception caught:
itk::ExceptionObject (0x7fffcd8be910)
Location: "unknown"
File: /home/.../build/staging/include/ITK-5.1/itkImageBase.hxx
Line: 177
Description: itk::ERROR: Image(0x7fffcd8bd880): A spacing of 0 is not allowed: Spacing is [197.917, 197.917, 0]

However when I split my image in two separate Nifti files (one for each slice) input_1.nii and input_2.nii and run the N4biasFieldCorrection with -d 2 i don't get an error message. 

Am I doing something wrong? 

Kind regards, 

Bram

**Comment by gdevenyi** [comment]
You need to split the image up and correct each seperately.

**Comment by bramcal** [comment]
Is there a specific reason why it works like that?

**Comment by gdevenyi** [comment]
You have essentially a 2D timeseries, this is not a typical type of data, so it wasn't handled in the design.

**Comment by cookpa** [comment]
Exactly a @gdevenyi says, the program will compute a bias field over the dimensionality passed with `-d`. If you pass a stack of 2D images with `-d 3`, it will try to find a 3D bias field. What you want is independent estimates of the 2D bias field for every slice. So you would pass them one at a time with `-d 2`. 

If it's important to have the same bias field correction for both slices, you can either average them or take the first one, run N4 on it, output the bias field (see usage for --output), and then apply the field to each slice by dividing the images by the bias field (ImageMath will do that for you).

**Comment by bramcal** [comment]
Thanks!

**Comment by bramcal** [comment]
I generated the biasfield using -0 [output.nii, biasfield.nii]

When I apply the  field to each slice using: 
ImageMath 2 /path/to/ouptu/output.nii / path/to/input/input.nii path/to/biasfield/biasfield.nii 

i get: "/ not found or not supported for dimension 2"

I also tried with v/ 

When I use the exact same command with v+ instead of / or v/ it does work. 
as input I tried both the splitted image and the combined image.

**Comment by gdevenyi** [comment]
Looks like you have some kind of issue with your shell.

Try running `bash` and then trying the same command instead.
