### ISSUE TITLE
Does changing a boolean in ITK require recompiling of ANTS?

### ISSUE THREAD

**Issue by thomshaw92** [ANTsX/ANTs#1124]
Bit of a noob C++ question here, but I want to change a boolean in the ITK Histogram MatchingImageFilter.h file, and don't really know what to do...

3 questions: 
1) Which is the correct file? 
```
./ITKv4/Modules/Filtering/ImageIntensity/include/itkHistogramMatchingImageFilter.h
./ITKv4-install/include/ITK-4.12/itkHistogramMatchingImageFilter.h
```
2) why that one?
3) if I change the boolean at line 243, do I have to recompile ANTs or anything, or will it just work?

**Comment by gdevenyi** [comment]
ANTs in its default configuration is statically linked and as such, any changes to upstream libraries require recompilation.,
