### ISSUE TITLE
Generating 2D strain field from displacement field

### ISSUE THREAD

**Issue by ArthurJ1** [ANTsX/ANTs#1130]
Hi all,

I am working on 2D+t abdominal MRI.
I am computing magnitude of displacement maps from an initial 2D slice to a deformed one.
To do so I am using antsregistration and antsdeformationmag.sh.

In order to differentiate locations of high strain from locations of high displacement, I would like to generate 2D strain maps from those magnitude of displacement maps.
I would like to know what would be the appropriate Ants script, if existing, to do this?

Thank you.

**Comment by ntustison** [comment]
We don't have anything that you can use directly.  I have [code](https://github.com/ntustison/Utilities/blob/master/src/CreatePrincipalStrainImages.cxx) in my own sandbox but I've only ported the decompose tensor functions to ANTs.  Why don't you add this as a feature request and I'll see if I can add that to ``ImageMath`` soon-ish.

**Comment by ArthurJ1** [comment]
That is great news, thank you for your answer. 
I am not very familiar with GitHub, how should I proceed to create a feature request ?

**Comment by ntustison** [comment]
You should close this issue and then open another issue and select the "Feature request" option.
