### ISSUE TITLE
2D Registration

### ISSUE THREAD

**Issue by mindmap2** [ANTsX/ANTs#1131]
Dear Ants community,

I have 200, 2D MRI images and I want to do internal registration( registering all the images into one of the images to make sure they are aligned).It is basically intensity based registration since all the 200 images are from one slice but having different signal intensity.I think only rigid registration should be ok.Can I do that with Ants?If yes could you please help me with the instruction?

Regard

**Comment by ntustison** [comment]
``antsMotionCorr`` should do what you want.  Take a look and let us know if you have any questions about usage.

**Comment by mindmap2** [comment]
Thanks Nick,
I printed the header of my nifti files and it shows 3 dimension.I am confused now.let me explain it to you.
I have 200 images with matrix size 64x64.These 200 images have different frequencies.They are Not in time series.Image 1 is at offset frequency 1.2 microHz,image 2 at offset frequency 1.3,images 3 at 1.4 and so on.All of these 200 images are from one same slice within brain.Now I want to align all these 200 images together(not to any reference image)
Can I still use antsMotionCorr command? should I do 2D or 3D registration?

Thanks,

**Comment by mindmap2** [comment]
Hi Nick,
I am not sure about the command for antsMotionCorr that works for my project.It does not have any fixed and moving image,so how can I align all my images?should I do that one by one? Not sure what number to choose for -n
-d 2
-n ?
-u fixed reference image
-t Rigid
-o output

Thanks,

**Comment by ntustison** [comment]
If all the images are separate and small, you could also simply build a template and use the final warped images.    Look at [these examples](https://github.com/ntustison/TemplateBuildingExample).

**Comment by mindmap2** [comment]
Should I use both motioncorr and template?

**Comment by ntustison** [comment]
No.  You just need one.

**Comment by mindmap2** [comment]
I tried this command for antsMotionCorr but stopped me with this error.
antsMotionCorr -d 2\ -n 50\ -u AntsRegistration/averaged/CEST_1.nii.gz\ -t Rigid -o motion.nii.gz -p Linear

libc++abi.dylib: terminating with uncaught exception of type itk::ExceptionObject: /Users/helmaheidari/ants/ANTs/Utilities/antsCommandLineParser.h:126:
itk::ERROR: CommandLineParser(0x7fadf3aa3b40): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert 'Rigid' to type 'j' as unsigned int

**Comment by mindmap2** [comment]
Hi Nick,
I do not understand the concept of the antsMotionCorr command. I choose the fixed image in -u .Where can I put the rest of the volumes? Imagine I have 50 2D volume that want to register all to the first volume.

Thanks,
Helma

**Comment by ntustison** [comment]
It would be easiest if you posted the data and I can provide the commands needed.

**Comment by mindmap2** [comment]
[CEST_1.nii.gz](https://github.com/ANTsX/ANTs/files/5849888/CEST_1.nii.gz)
[CEST_2.nii.gz](https://github.com/ANTsX/ANTs/files/5849891/CEST_2.nii.gz)
[CEST_3.nii.gz](https://github.com/ANTsX/ANTs/files/5849892/CEST_3.nii.gz)
[CEST_4.nii.gz](https://github.com/ANTsX/ANTs/files/5849894/CEST_4.nii.gz)
[CEST_5.nii.gz](https://github.com/ANTsX/ANTs/files/5849896/CEST_5.nii.gz)
[CEST_6.nii.gz](https://github.com/ANTsX/ANTs/files/5849899/CEST_6.nii.gz)
[CEST_7.nii.gz](https://github.com/ANTsX/ANTs/files/5849901/CEST_7.nii.gz)

**Comment by mindmap2** [comment]
Hi Nick,
That would be great.Thanks for your help.I have been stuck in it.Attached in the previous box is some of my 2D volumes.I have 50 files of them and need to register them together.These images are produced at different offset frequency from a single slice of brain.

**Comment by ntustison** [comment]
You might need to play with the parameters but this should get you started.

```
$ TileImages 3 CEST_stack.nii.gz 1x1x0 CEST_?.nii.gz
$ antsMotionCorr -d 2 -a CEST_stack.nii.gz -o CEST_average.nii.gz
$ antsMotionCorr -d 2 -m "MI[CEST_average.nii.gz,CEST_stack.nii.gz,1,32,Regular,0.25]" -t "Rigid[0.25]" -i 1000x500 -f 2x1 -s 1x0 -v 1 -o "[CEST_warped,CEST_warped.nii.gz]"
```

**Comment by mindmap2** [comment]
Thanks a lot Nick.I'll try that.

**Comment by mindmap2** [comment]
Hi Nick,
Thanks for your help.It went well except the last line of the code that you wrote.This error comes:
no matches found: MI[CEST_average.nii.gz,CEST_stack.nii.gz,1,32,Regular,0.25]
