### ISSUE TITLE
Generating 2D strain field from displacement field

### ISSUE THREAD

**Issue by ArthurJ1** [ANTsX/ANTs#1132]
Hi all,

I am working on 2D+t abdominal MRI.
I am computing magnitude of displacement maps from an initial 2D slice to a deformed one.
To do so I am using antsregistration and antsdeformationmag.sh.

In order to differentiate locations of high strain from locations of high displacement, I would like to generate 2D strain maps. 

It would be  great to have a script allowing the calculation of strain maps from those magnitude of displacement maps.

Thank you.

**Comment by cookpa** [comment]
@ntustison adding the enhancement label as you had indicated you wanted this flagged as a feature request

**Comment by ArthurJ1** [comment]
@ntustison Have you had the opportunity to add it from your sandbox to ImageMath ?
https://github.com/ANTsX/ANTs/issues/1130#issuecomment-761033507

**Comment by ntustison** [comment]
I have that on my to-do list for later this work.  Can't guarantee anything but I'll try to get to it.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/pull/1158/files

For additional work, you'll have to specific about what you would like.

**Comment by ArthurJ1** [comment]
Thank you very much, I will try it right away.

**Comment by ArthurJ1** [comment]
Hi, I apologise for the inconvenience, but I am not familiar with how to update my ANTs version from the Kinematics or Master code snapshots .zip.  And then how should I call the KinematicTensor function ? Could you help me please?

**Comment by ntustison** [comment]
Did you see these instructions?

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

**Comment by ArthurJ1** [comment]
Thank you, I was able to do it with the instructions. KinematicTensor works great. 
If you are interested, I tested it on a displacement field that I get by registrating an axial slice of the abdomen of a volunteer in relaxed condition toward the same axial slice at full inhalation.
The results of the different KinematicTensor options are visible in the pdf attached. All I have to do now is to decide which option best suits my needs.
[KinematicTensor_options_strain.pdf](https://github.com/ANTsX/ANTs/files/6131065/KinematicTensor_options_strain.pdf)

Just one small thing, I believe that the usage "Usage        : StrainTensor displacementField whichTensor" should be replaced by "Usage        : **KinematicTensor** displacementField whichTensor"

Thanks again.

**Comment by ntustison** [comment]
Thanks.

**Comment by ArthurJ1** [comment]
Hi, 
Could you help me as I am having trouble interpreting the deformation fields I get using KinematicTensor. 
Here is a description my work and what I would like to obtain :

I am doing 2D+t axial imaging of the abdomen. 
From these images I generate displacement fields between the reference image at t0 and successive images at time t. 
These displacement fields contain the distance between each pixel at time t and their reference position at time t0. 
=>This distance is a positive quantity which does not give any information on the direction of the displacement in the x/y reference frame of the image (which is fine).

I would like to obtain an easily interpretable information on the local change of distance (strain) in order to locate the high strain areas where the points close to each other strongly changed their relative position.

To do so, I generated the strain fields using the RightStretch parameter and I have trouble interpreting them.
The displacement fields given as input are very similar on the right and left side of the image (same amplitude and same distribution). However the strain fields are not the same on the right and on the left sides of the image. 
=> I mainly get rightstretch <1 on the right side of the image and rightstrech>1 on the left side of the image while the strain levels should be similar. 
I feel like the strain is taking into account the direction of displacement, which I don't want.

Could you please help me to interpret these results and advise me on how tu use the KinematicTensor function ?

Thanks.

**Comment by ntustison** [comment]
> Could you help me as I am having trouble interpreting the deformation fields I get using KinematicTensor.

The KinematicTensor option returns a tensor field, not a deformation field.  

> I would like to obtain an easily interpretable information on the local change of distance (strain) in order to locate the high strain areas where the points close to each other strongly changed their relative position.

You have to specify a direction in order to get a "local change of distance"  from a tensor field.

If you don't have a background in continuum mechanics, I would recommend starting with something a little easier to visualize, like the Jacobian determinant --- ``CreateJacobianDeterminantImage``.
