### ISSUE TITLE
ImageMath with mrtrix output

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTs#1134]
Hey @cookpa,

I'm trying to compute diffusivity in an arbitrary direction using the output dti images from mrtrix.  I was simply going to hack my local copy of ``ImageMath``but it looks like it's a bit more involved than that.  Specifically, it doesn't appear that mrtrix output and ANTs tensor images have the same definition but I'm guessing there's some sort of conversion I would just need to know.  Do you know that "recipe"?

Thanks,
Nick

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/wiki/Importing-diffusion-tensor-data-from-other-software ?

**Comment by ntustison** [comment]
Perfect.  Thanks @gdevenyi

**Comment by cookpa** [comment]
That's part of it, but you might need to adjust for the coordinate system

https://mrtrix.readthedocs.io/en/latest/getting_started/image_data.html?highlight=coordinate#coordinate-system
