### ISSUE TITLE
Optimizing registration of BOLD image and T1

### ISSUE THREAD

**Issue by carolin31** [ANTsX/ANTs#1135]
Hello Ants experts,

I have been using antsRegistration coregister a BOLD image to a T1. After reading through the issues here and on source forge I decided to first bias correct both images and to skull-strip both images and create masks that were dilated by 4 voxels. After trying antsRegistrationSyN (which deformed the brain weirdly, antsRegistrationSyNQuick (which did not give a good result) and  antsRegistrationSyN with only the rigid and affine transformation, I got the best result using the following: 

antsRegistration --verbose 1 \
                  --dimensionality 3 \
                  --float 0 \
                  --interpolation Linear \
                  --use-histogram-matching 0 \
                  --winsorize-image-intensities [0.005,0.995] \
                  --output [${outputPrefix},${outputPrefix}Warped.nii.gz,${outputPrefix}InverseWarped.nii.gz] \
                  --initial-moving-transform [${fixedImage},${movingImage},1] \
                  --transform translation[0.1] \
                    --metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
                    --convergence [50,1e-6,10] \
                    --shrink-factors 1 \
                    --smoothing-sigmas 0vox \
                   --masks [${anatmaskImage},${EPImaskImage}]\
                  --transform Rigid[0.1] \
                    --metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
                    --convergence [500x500x250x50,1e-6,10] \
                    --shrink-factors 6x4x2x1 \
                    --smoothing-sigmas 3x2x1x0vox \
                   --masks [${anatmaskImage},${EPImaskImage}]\
                  --transform SyN[0.1,3,0] \
                    --metric MI[${fixedImage},${movingImage},1,32] \
                    --convergence [100x20,1e-6,10] \
                    --shrink-factors 2x1 \
                     --smoothing-sigmas 1x0vox \
                    --masks [${anatmaskImage},${EPImaskImage}]

however, the result is still not very good. The overlap of the ventricles is good but the wm in particular still does not overlap very well. As I want to create a wm and csf mask for aCompCor (nuisance regression) I would need a better wm overlap. 
<img width="1253" alt="Screen Shot 2021-01-20 at 6 22 26 PM" src="https://user-images.githubusercontent.com/41706947/105271534-7dbb4880-5b4c-11eb-9a8a-362484aacee4.png">

I tried to improve the result by using only skull stripped images without mask, by increasing or decreasing convergence levels for SyN and accordingly increasing or decreasing shrink factors and smoothing sigma levels, I tried it with CC as metric and I tried to flip what is reference and what is moving image and registered the anatomical to the functional image instead. I understand that the registration will never be perfect but I am honestly not sure how good it can get realistically. Is there anything else that you can recommend that would be worth trying in order to get a better overlap for the wm?

I would appreciate any thoughts on that!
Thank you very much in advance!
Carolin

**Comment by cookpa** [comment]
Can you share data? These two images plus the segmentation you want to transform to the EPI space?

Are the EPI images distortion corrected? The best way to solve the EPI distortion problem is with field maps. If these aren't available, you can attempt to approximate a solution with registration, but it will require some experimentation. BSplineSyN and / or -g can help regularize the registration by reducing deformation that is perpendicular to the phase encoding axis.

**Comment by carolin31** [comment]
Hello Philip,
thank you very much for your response! You can find the images below. 
And no, the EPI image is not distortion corrected. Unfortunatelly no field maps were collected for this dataset. I only skull stripped the image and ran N4BiasFieldCorrection before antsRegistration.
What is the -g option? I can not find it in the antsRegistrationSyN.sh help menu. I am using ANTs version 2.3.3.dev168-g29bdf

[T1_FS_P1002.nii.gz](https://github.com/ANTsX/ANTs/files/5869584/T1_FS_P1002.nii.gz)
[corrected_minOutlier_masked.nii.gz](https://github.com/ANTsX/ANTs/files/5869586/corrected_minOutlier_masked.nii.gz)
[fs_ap_wm.nii.gz](https://github.com/ANTsX/ANTs/files/5869602/fs_ap_wm.nii.gz)

Thank you very much in advance!
Carolin

**Comment by cookpa** [comment]
`-g` is an advanced option that requires running `antsRegistration` directly. Its long form is `--restrict-deformation`. You'd do something like `--restrict-deformation 0.1x1x0.1` for a phase-encode gradient along the y-axis in the fixed (BOLD) space.

When you run the script, it will print the full `antsRegistration` call, which you can copy and customize.
