### ISSUE TITLE
ANTS program can't be found. Please (re)define $ANTSPATH in your environment

### ISSUE THREAD

**Issue by xiaoai995** [ANTsX/ANTs#1136]
Hi experts! 
I'm having trouble running an ANTs command. I'm using win10 sub linux system and I've installed ANTs without bugs. After setting up the environment path, I can find antsRegistration and run most commands (running the name of the script will show the 'help' file of the command). However, I can't run one ANTs command: antsIntroduction.sh, the error said 'ANTS program can't be found. Please (re)define $ANTSPATH in your environment.'. However, the other ANTs commands work well, so It's very confusing to me. 

I opened antsIntroduction.sh and this error located at line 38:

if [ ! -s ${ANTSPATH}/ANTS ] ; then
  echo "ANTS program can't be found. Please (re)define \$ANTSPATH in your environment."
  exit
fi

but the path ${ANTSPATH}/ANTS (which is '/opt/ANTs/bin/ANTS') doesn't exist. There is no 'ANTS' folder under bin folder. Did I make any mistake installing the APP? Does anyone know why this happens? Thank you so much!

**Comment by cookpa** [comment]
What are the contents of "/opt/ANTs/bin/"?

**Comment by dorianps** [comment]
Looks like you have added ANTs in the system path (i.e., $PATH) but have
not defined $ANTSPATH. In that case the easiest is to do "which
antsRegistration" to find where are the binaries, and then use the folder
to define ANTPATH. The following command should do it for your current
session, you can set it properly in your ~/.bash_profile for the long term:

export ANTSPATH=$(dirname $(which antsRegistration))

**Comment by xiaoai995** [comment]
Hi! I've run ls under this path and it shows:(contains antsIntroduction.sh)

xzc5220@DESKTOP-2I43317:/opt/ANTs/bin$ ls
ANTSpexec.sh            antsApplyTransforms                   antsMotionCorrStats
Atropos                antsApplyTransformsToPoints           antsMultivariateTemplateConstruction.sh
DenoiseImage           antsAtroposN4.sh                      antsMultivariateTemplateConstruction2.sh
KellyKapowski          antsBOLDNetworkAnalysis.R             antsNetworkAnalysis.R
LabelClustersUniquely  antsBrainExtraction.sh                antsNeuroimagingBattery
LabelGeometryMeasures  antsCorticalThickness.sh              antsRegistration
N3BiasFieldCorrection  antsIntermodalityIntrasubject.sh      antsRegistrationSyN.sh
N4BiasFieldCorrection 
 antsIntroduction.sh
                  antsRegistrationSyNQuick.sh
ResampleImage          antsJointFusion                       sccan
SurfaceBasedSmoothing  antsJointLabelFusion.sh               waitForPBSQJobs.pl
ThresholdImage         antsLaplacianBoundaryCondition.R      waitForSGEQJobs.pl
antsASLProcessing.sh   antsLongitudinalCorticalThickness.sh  waitForSlurmJobs.pl
antsAffineInitializer  antsMotionCorr                        waitForXGridJobs.pl

> What are the contents of "/opt/ANTs/bin/"?

**Comment by xiaoai995** [comment]
Thank you @dorianps ! I've run 'export ANTSPATH=$(dirname $(which antsRegistration))' but my 'antsIntroduction.sh' still shows the same error ('ANTS program can't be found. Please (re)define $ANTSPATH in your environment.'), while other scripts(antsRegistrationSyN.sh etc.) run well.

Besides, I found that there is no 'ANTS' folder under ANTSPATH, I guess that could be the reason. Did I install ANTs wrong so that some modules were missing?

**Comment by cookpa** [comment]
Did you turn off the "BUILD_ALL_ANTS_APPS" option in CMake? You can check your CMakeCache.txt. More details in the build problems issue template.

**Comment by dorianps** [comment]
Aha, I see your error comes because your are missing the ANTS binary, check
is here:
https://github.com/ANTsX/ANTs/blob/master/Scripts/antsIntroduction.sh#L37-L39

Not sure if there is some change in ANTS or your installation is
incomplete. Phil might help you there.

Dorian

**Comment by xiaoai995** [comment]
@cookpa Thank you so much for your help! Actually, I'm not sure if I changed that by mistake. However, I'm really unfamiliar with CMake... How can I find that CMakeCache.txt? It doesn't work to run 'which  CMakeCache.txt' in the root path.

**Comment by cookpa** [comment]
It would be in the directory where you compiled ANTs.

**Comment by xiaoai995** [comment]
@cookpa Found it! It said:
...
...

//Build all ANTs apps
BUILD_ALL_ANTS_APPS:BOOL=OFF
...
...

Can I turn it on by changing it to ' BOOL=ON' in  CMakeCache.txt? Or do I need to reinstall the app?

**Comment by cookpa** [comment]
You need to run cmake again, set that to ON, then re-do `make` and `make install`. If that doesn't work, it'd be easiest to just start over from a clean install directory.

**Comment by xiaoai995** [comment]
I've reinstalled it and now it works! Thank you for your help! @cookpa
