### ISSUE TITLE
Registration of vector volumes

### ISSUE THREAD

**Issue by NitramNimod** [ANTsX/ANTs#1140]
Hi!

I'm currently trying to register the output of FSL's DTIFIT across several subjects. This output contains several volumes with 3 subvolumes each, depicting a vector. These are the V1, V2 and V3 of the decomposed tensor matrix.
Is there a way in ANTs to use this higher order information during registration in way that vectors are realigned and not just scalars?

Thanks and all the best,
Martin

**Comment by cookpa** [comment]
Unfortunately we do not have vector or tensor-valued similarity metric available. You can use multiple scalar channels, like axial and radial diffusivity.

There is code to reorient tensors after applying a warp. Similar code could exist for vectors, but it's not currently implemented.

**Comment by NitramNimod** [comment]
Ok, thanks for clarification.
