### ISSUE TITLE
NIFTI-1 I/O changes in ITK, sform preferred

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1141]
Just wanted to add a usage note. The sform is now the preferred method of defining the rotation and translation from voxel to physical space. Previously, the quaternion was preferred. When creating NIFTI files, ANTs will now set the sform and qform to equivalent transforms with the code NIFTI_XFORM_SCANNER_ANAT.

Many other software packages prefer sform to qform when both are defined. Also, the sform convention can represent the transform more precisely than the quaternion.

I've attempted to summarize the new I/O behavior at in more detail at the Wiki page

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

**Comment by ntustison** [comment]
Thanks @cookpa .  I noticed this in the ITK release announcement so good to have it here.
