### ISSUE TITLE
Brain mask from ATROPOS result

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTs#1142]
Using deepAtropos (R package) results, I attempted to make a brain mask. 
The reason for doing this, antsBrainExtraction was not good enough for me and its results include non-brain tissues such as CSF and dura here and there.
Merging a few labels of deepAtropos' result seems to be good for my use. However, there are still small and isolated pixels that need to be trimmed in the area outside the cortex. 

![image](https://user-images.githubusercontent.com/1088166/106776107-c7f2fe00-6611-11eb-8fc1-7bdced38c45e.png)

Q1. I wonder if there are any options to suppress such isolated island pixels in the ATROPOS result. ( I used deepAtropos in ANTsRNet package.) 

Q2. I wonder if ANTs provide such utilities for BASH script (not R package). 

Thank you.

**Comment by cookpa** [comment]
If you need a self-contained executable that can run deep Atropos, you could use a container.

I've made some basic containers for ANTsXNet

https://hub.docker.com/u/cookpa

https://github.com/cookpa/ANTsXContainers

@stnava has some more advanced features such as RStudio integration

https://github.com/stnava/ANTsRDocker

**Comment by sj-choi** [comment]
Thanks for your reply. Actually, I can run deepAtropos. What I am trying to is making a brain mask using labels from deepAtropos selectively. The apparent problem is the small pixels that you see in the image shown above. I wonder if any good way to remove those small pixels outside of the brain tissue area using any ANTs command that can be used in a BASH script. (I am making a processing pipeline using ANTs commands/functions in BASH. That's why I am seeking for ANTs commands not ANTsR functions.) 

Thank you.

**Comment by ntustison** [comment]
``LabelClustersUniquely ``

**Comment by sj-choi** [comment]
I wonder if any brain extraction example with which I can remove dura matter.

**Comment by ntustison** [comment]
We don't use ``deepAtropos`` or ``Atropos`` for brain extraction.   That means we won't have an example for brain extraction using these tools.  We use the designated tools for that---``ANTsRNet::brainExtraction`` or ``antsBrainExtraction.sh``.  If you want to do something unique, then you're going to have to put it together yourself.

**Comment by s-j-choi** [comment]
I got some promising combining deepAtropos results and ANTsRNet::brainExtractio ("t1nobrainer"). Not perfect, but close to what I wanted.

**Comment by sj-choi** [comment]
I got some promising results by combining results of deepAtropos and ANTsRNet::brainExtraction ("t1nobrainer"). Not perfect, but close to what I wanted.

I wonder if ANTs or ANTsRNet provides a way or functions to (selectively) remove "blood vessels."
