### ISSUE TITLE
Ants Cortical Thickness missing Gray Matter - perhaps contrast issue?

### ISSUE THREAD

**Issue by dbrennan44** [ANTsX/ANTs#1143]
Hi ANTs team,

antsCorticalThickness seems to be estimating 0 or near-0 gray matter for large portions of cortex. Could this be a contrast issue, or is that something that would be optimized within N4?

I know this is a difficult image, is there a parameter that can be tweaked to help?

![p029_axial](https://user-images.githubusercontent.com/39420777/107546610-8e367000-6b9a-11eb-840e-0ed1bb9dcc3d.png)

**Comment by cookpa** [comment]
The usual reason for thickness to be inaccurate is segmentation problems. What does the BrainSegmentation.nii.gz image look like?

**Comment by dbrennan44** [comment]
@cookpa it looks similar, in that it is estimating the entire gyrus as white matter

**Comment by dbrennan44** [comment]
for example:

![t1](https://user-images.githubusercontent.com/39420777/107547395-64ca1400-6b9b-11eb-9220-23be9cdff6a2.png)
![t1_with_seg](https://user-images.githubusercontent.com/39420777/107547397-6562aa80-6b9b-11eb-90c7-809a8e15cddc.png)

seems to be over-estimating white matter

**Comment by cookpa** [comment]
If you're running antsCorticalThickness.sh, you could try turning on denoising, and boosting the number of Atropos iterations. I think the default is 5 but more is recommended, I use 25.

**Comment by dbrennan44** [comment]
@cookpa excellent suggestion, I will run and report results

**Comment by ntustison** [comment]
An important option would be the prior weight, ``-w``.  Also, increasing the number of Atropos iterations might iterate away from the ideal solution.

**Comment by dbrennan44** [comment]
should the prior weight be decreased or increased?

**Comment by ntustison** [comment]
Increase---it refers to the prior probability images and, in the absence of contrast, you want to emphasize the spatial priors while de-emphasizing the actual data.

**Comment by dbrennan44** [comment]
Increasing Atropos iterations seemed to help, I am still experimenting with the prior weight. Thanks again!

**Comment by dbrennan44** [comment]
I am finding a similar issue with antsJointLabelFusion, where the gray matter is underestimated (white matter takes over the gyrus), leaving very little "labelled" data. Any suggestions for JLF, as it doesn't use the atropos segmentation?

**Comment by cookpa** [comment]
JLF performance is going to depend strongly on the atlases and on the registration quality. What was your atlas set, and what was your call to the script?

**Comment by dbrennan44** [comment]
I'm using OASIS labelled brains which were at one point available. 

my call is: 

antsJointLabelFusion.sh -d 3 -t ${sub_dir}/STRUC/00*t1*.nii -x  ${sub_dir}/CT_BrainExtractionMask.nii.gz \
-o ${sub_dir}/malf_ -c 2 -j 5 \
-g Brain -l Segmentation \
... etc


I'm currently experimenting with q 0 option
