### ISSUE TITLE
Intensity normalization

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTs#1144]
I wonder if any commands/functions are available to normalize intensities of (intra-subject) images between visits (in a longitudinal study setting). I also looking for a good way (or example processing flow or script) to normalize intensities of images before and after contrast agent administration. 

If you have any suggestions or working examples, please share your experience with me.

**Comment by ntustison** [comment]
Not great but it's probably the closest thing we have in the toolkit:

```
$ ImageMath | grep HistogramMatch
  HistogramMatch    : 
      Usage        : HistogramMatch SourceImage ReferenceImage {NumberBins-Default=255} {NumberPoints-Default=64} {useThresholdAtMeanIntensity=false}
```

**Comment by sj-choi** [comment]
Thank you for your quick reply! I will give it a try.
