### ISSUE TITLE
ATLAS for brain normalization

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTs#1147]
I wonder if ANTs (ANTsR/ANTsRNet) has brain atlases for space normalization. If so, could anyone point me out to the location of the images? 

Thank you

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsRNet/blob/master/R/getANTsXNetData.R#L33-L39

https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436

https://figshare.com/articles/dataset/Multi-modal_super_resolution_isotropic_and_cropped_Kirby/12083871

**Comment by cookpa** [comment]
Some of these and others are also available in templateflow

https://www.templateflow.org

**Comment by sj-choi** [comment]
Thank you so much!
