### ISSUE TITLE
Motion correction of time-series with multiple contrasts

### ISSUE THREAD

**Issue by dangom** [ANTsX/ANTs#1150]
Hi all,

I'm trying to motion correct a T1w EPI time-series, where the acquisition order of the slices is shuffled in each repetition, such that in each volume the slices have slightly different contrasts. 
As you can appreciate in the gif below, this change in contrast leads to an apparent "motion", characterized by a moving "nulling/dark band". 

![t1wEPI](https://user-images.githubusercontent.com/7881842/109561395-1a0d2f00-7aab-11eb-9a3b-9c02e95b9c8c.gif)

Some ideas that I have tried have included:

- Registering to the mean image where the band dissapears
- Using MI as a metric as it isn't completely driven by contrast
- Strongly winsorizing image intensities
- Pre-processing the images before motion correction by e.g. taking the square root (to reduce the difference in contrast)
- Using both smoothing/non-smoothing

The best results I have so far are the output time-series looking pretty much like the input series, i.e., not affected by the dark band but also not correcting for the actual motion. These were achieved with the following command:

```sh
fslsplit T1wEPI.nii.gz  # will output vol*.nii.gz
fslmaths T1wEPI.nii.gz -Tmean T1wEPI_tmean.nii.gz

fixed=T1wEPI_tmean.nii.gz

for moving in vol*.nii.gz; do

antsRegistration --dimensionality 3 \
                            --float 0 \
                            --output [${moving}reg,${moving}reg.nii.gz] 
                            --interpolation LanczosWindowedSinc \
                            --winsorize-image-intensities [0.35,0.55] \
                            --use-histogram-matching 0  \
                            --transform Rigid[0.1] \
                                --metric MI[$fixed,$moving,1,32,Random,0.75] \
                                --convergence [1000x500x250x100,1e-6,10] \
                                --shrink-factors 8x4x2x1 \
                                --smoothing-sigmas 3x2x1x0vox & ;
done
```

I decided not to use the antsMotionCorr tool because antsRegistration gave me more flexibility (I can winsorize image intensities, for example).

Would you guys have any more ideas that I could try? 

Thank you again.

**Comment by cookpa** [comment]
That's a tough problem. You could try a metric mask on the moving image to exclude the dark slices.
