### ISSUE TITLE
N4 rescale intensity question

### ISSUE THREAD

**Issue by CommanderCody** [ANTsX/ANTs#1152]
I have a question about intensity rescaling aspects when using N4BiasFieldCorrection. Is the rescaling performed only after the last iteration is performed or after each grid level is finished? It seems to be performed only after the last iteration but the rescale flag seems to be out of order.

The commands I have been comparing is 

a:

N4BiasFieldCorrection -i "${DIR}/FLAIR.nii.gz"  -s 2 -c [130x130x100, 0.0003] -b [220] -o "${DIR}/Flair_N4c3.nii.gz" 

b:

N4BiasFieldCorrection -i "${DIR}/FLAIR.nii.gz"  -s 2 -c [130, 0.0003] -b [220] -o "${DIR}/Flair_N4_03tmp.nii.gz"

N4BiasFieldCorrection -i "${DIR}/Flair_N4_03tmp.nii.gz"  -s 2 -c [130, 0.0003] -b [110] -o "${DIR}/Flair_N4_03tmp2.nii.gz" 

N4BiasFieldCorrection -i "${DIR}/Flair_N4_03tmp2.nii.gz" -s 2 -c [100, 0.0003] -b [55] -o "${DIR}/Flair_N4_c03_3st.nii.gz"

The b  alternative above seems to entail much less intensity drift for some acquisitions which leads to the suspicion that the rescaling is only performed after a N4 command is finished. However the rescaling flag -r 0 or -r 1 do not seem to make any difference (  and rescaling is supposed to be default) so I am  a bit confused about what is going on regarding the rescaling.

best regards

**Comment by ntustison** [comment]
Rescaling is performed after the last iteration.

**Comment by cookpa** [comment]
The rescaling is relative to the contrast in the corrected region. If you don't include a mask with `-x` then that region is the whole image. It takes the maximum and minimum values, so it is sensitive to outliers. Winsorizing outliers before N4 and using a mask might stabilize the output across different settings.

https://github.com/ANTsX/ANTs/blob/91529e6414fc6e5186b1a63b03a4da2bc1c7b9d2/Examples/N4BiasFieldCorrection.cxx#L532-L563

**Comment by CommanderCody** [comment]
Thanks for your answer.

The images are skull stripped so nearly no skull or neck remains which I guess eliminates the need for the -x mask.

By winsorizing outliers do you mean for example a hard clipping of the intensities over the 99 percentile (or a symmetrical approach also hard clipping below the 1 percentile, although the lowest intensity is 0 and containing lots of voxels) ?

Is it possible that the -r 0 flag might not be working? ( I see no preliminary differences between default, -r 1 and -r 0 .)

best regards
________________________________

**Comment by cookpa** [comment]
I checked the code and you're right, rescaling is being turned off automatically because you don't have a mask. 
I'll update the usage to clarify this.

Try using `ThresholdImage` to make a mask including voxels > 0. This will set the lower bound in the rescale to whatever is in your brains, rather than 0, and will allow rescaling to happen.

**Comment by CommanderCody** [comment]
Thanks again!

So ThresholdImage FLAIRbrain.nii.gz zeromask.nii.gz 3 1
will produce a suitable mask I can use with the -x flag in the N4 command?

But there seem to be a default rescaling (regardless of the nonworking -r 0 or -r 1 flags) because I get different intensity drift for the a. command and the b. commands (which would give the same results if no rescaling were performed) , see the first message in this thread.

best regards
________________________________

**Comment by cookpa** [comment]
For making a mask:

`ThresholdImage 3 FLAIRbrain.nii.gz nonZeroMask.nii.gz 0.01 Inf 1 0`

Regarding different intensity drift in scenario a. vs scenario b., I don't think the two are equivalent because in the second one you're starting over at each step, rather than continuing to refine the estimated bias field on the original data. But @ntustison is the real expert on the algorithm.

**Comment by ntustison** [comment]
Phil is right---the initial B-spline fields for (a) and (b) are set up differently.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/blob/master/Examples/N4BiasFieldCorrection.cxx#L522-L563

**Comment by ntustison** [comment]
I don't understand what you mean by "making it clearer" if you're looking at the code itself?

**Comment by CommanderCody** [comment]
OK, I now realize the rescaling is fine. But my problem is that some FLAIR images (probably due to the mentioned image distortions) in the sample have a larger intensity drift and N4 with the lowest intensity drift is with the b. option (regardless of the value of the convergence criterion or number of iterations). The a. option results in WM being brighter than GM in the T2FLAIR with low image quality and this is not going away with the rescaling. Do you have any doubts about using the b. option?

best regards
________________________________

**Comment by cookpa** [comment]
Wow that's interesting. Can you share an example image that does this?

**Comment by CommanderCody** [comment]
Can I send it to a private email?
________________________________

**Comment by cookpa** [comment]
It's OK, if it can't be shared publicly. I've not seen contrast inversion from N4 but then I've not run it on very many FLAIR images. 

It sounds like your problem is with the bias field itself, rather than the rescale specifically. You can output both the corrected image and the bias field (see the -o option in the usage). The original image divided by the bias field is the corrected image, before rescaling.

**Comment by cookpa** [comment]
@CommanderCody , your email attachments were removed by my organization IT, but to answer your question, the bias field is defined over the whole image domain. Its parameters are updated based on the voxels inside the mask, and in the output image, it is applied only in voxels inside the mask.

Also, Otsu segmentation has not been used in N4 for a while. So if you have an older version, you might try upgrading.
