### ISSUE TITLE
Correct for offset induced by ResampleImageBySpacing

### ISSUE THREAD

**Issue by gjheij** [ANTsX/ANTs#1155]
Dear ANTs experts,

First off, thank you for this wonderful toolbox. It has worked magic so far for me.

I have a slice of the brain with dimensions `720x720x1` (pixdim `0.25x0.25x2.5`) through which I'm sticking a beam (green) consisting of 16 voxels (8 voxels below center of the image, 8 voxels above center) of the original slice image. This corresponds to a size of 16x0.25=4 mm thickness. 

![beam1](https://user-images.githubusercontent.com/61841072/109937707-794b8900-7ccf-11eb-8564-1a4e5db564f0.png)

Thus, this beam is 720x16x2.5 and I'd like to collapse the 16 voxels into 1 voxel of 4mm giving my beam voxel dimensions of 0.25x4x2.5. For that, I'm running:

 `ResampleImageBySpacing 3 sub-001_ses-2_task-LR_run-7_bold_FH.nii.gz sub-001_ses-2_task-LR_run-9_bold_FH.nii.gz 4 0.25 2.5`.

This results in the following blue beam:

![beam2](https://user-images.githubusercontent.com/61841072/109938084-ebbc6900-7ccf-11eb-8652-36a9f1b4ac1f.png)

As you can see from the image, the command induced a slight offset relative to the green image (x=-1,342,y=-1,312,z=-0,022 in ITK-Snap). Is there a way to calculate this offset from the affine and correct for it?

I eagerly await your reply.

Thanks and all the best,
Jurjen

slice: [sub-001_ses-2_acq-1slice_run-1_T1w.nii.gz](https://github.com/ANTsX/ANTs/files/6082242/sub-001_ses-2_acq-1slice_run-1_T1w.nii.gz)
green beam: [sub-001_ses-2_task-LR_run-7_bold_FH.nii.gz](https://github.com/ANTsX/ANTs/files/6082247/sub-001_ses-2_task-LR_run-7_bold_FH.nii.gz)
blue beam: [sub-001_ses-2_task-LR_run-9_bold_FH.nii.gz](https://github.com/ANTsX/ANTs/files/6082248/sub-001_ses-2_task-LR_run-9_bold_FH.nii.gz)

**Comment by ntustison** [comment]
I don't know how ITK-SNAP is calculating that offset.  It's questionable as to whether or not an offset actually exists.  For example, the voxel-based centroids along the axis in question appear to be identical:

```
% LabelGeometryMeasures 3 sub-001_ses-2_task-LR_run-9_bold_FH.nii.gz
Label  Volume(voxels)SurfArea(mm^2) Eccentricity   Elongation     Orientation    Centroid                      Axes Length                   Bounding Box                  
100000000720       1533.16        0.999753       45             0              [22, 359.5, 0]                [1.1547, 18.4752, 51.9615]    [0, 44, 352, 367, 0, 0]       
% LabelGeometryMeasures 3 sub-001_ses-2_task-LR_run-7_bold_FH.nii
Label  Volume(voxels)SurfArea(mm^2) Eccentricity   Elongation     Orientation    Centroid                      Axes Length                   Bounding Box                  
10000000011520     2275.06        0.999999       720            0              [359.5, 359.5, 0]             [1.1547, 18.4752, 831.384]    [0, 719, 352, 367, 0, 0]      
```

**Comment by cookpa** [comment]
Yeah, and the BoundingBox returned by `PrintHeader` is identical for the original and downsampled images.

BTW, the default interpolation is linear so if you want a binary image do

`ResampleImageBySpacing 3 sub-001_ses-2_task-LR_run-7_bold_FH.nii.gz sub-001_ses-2_task-LR_run-9_bold_FH.nii.gz 4 0.25 2.5 0 0 1`
