### ISSUE TITLE
Normalization to JHU atlas template

### ISSUE THREAD

**Issue by marivas-MRI** [ANTsX/ANTs#1161]
Dear all, 

My goal is to normalize lesion binary maps to the JHU templated included in FSL (see attached). For that purpose I normalized the T1-weighted images of my subjects using the to the antsRegistrationSyNQuick.sh and then the antsApplyTransforms function in order to apply the deformation fields over the T1 and the binary lesion maps. All have worked fine, binary lesion maps looks fine but, although the normalization of t1 images was very good (see screenshot), the normalized t1 image has some deformation in the skull. This is not a problem for me since I am only going to use the normalized binary maps in my analysis but although this is not at all problematic for me I would like to know if there is something wrong in my commands that gave to me the same output but without having that deformation in the skull of the T1 image. 

These were the commands employed: 

antsRegistrationSyNQuick.sh -d 3 -f JHU-ICBM-T2-1mm.nii.gz -m t1_4001.nii.gz -o 4001_jhu_les_reg_ -t s

antsApplyTransforms -d 3 -i t1_4001.nii.gz -r JHU-ICBM-T2-1mm.nii.gz -t 4001_jhu_les_reg_1Warp.nii.gz -t 4001_jhu_les_reg_0GenericAffine.mat -o t1_4001_JHU.nii.gz

antsApplyTransforms -d 3 -i bles_4001.nii.gz -r t1_4001_JHU.nii.gz -t 4001_jhu_les_reg_1Warp.nii.gz -t 4001_jhu_les_reg_0GenericAffine.mat -o lesion_4001_JHU.nii.gz -n NearestNeighbor

Thank you so much in advance.

Best regards, 

[JHU-ICBM-T2-1mm.nii.gz](https://github.com/ANTsX/ANTs/files/6166691/JHU-ICBM-T2-1mm.nii.gz)
![jhu_t1_norm](https://user-images.githubusercontent.com/78478818/111684342-e5c59c80-8826-11eb-9e49-9fb2d3c1183d.png)

**Comment by ntustison** [comment]
I see that JHU template but I don't see your input image.

**Comment by dorianps** [comment]
Fyi, I have included a routine for registration of lesions in LESYMAP via
ANTsR. It includes skull stripping, denoisng, etc, so no skull issues
hopefully (see registerLesionToTemplate). You will need a couple of other
brain and head masks to take advantage of skull stripping though.
