### ISSUE TITLE
Add ANTs to path using ANTs 2.3.5

### ISSUE THREAD

**Issue by amsinha9** [ANTsX/ANTs#1162]
I just downloaded ANTs 2.3.5 from the source code zip file on Github. When adding ANTs to my path, would I just do the following:

export ANTSPATH=~/ANTs-2.3.5/Scripts/
export PATH=${ANTSPATH}:$PATH

since there is no bin folder? Or am I missing something?

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

**Comment by amsinha9** [comment]
To confirm, is the Scripts folder in the downloaded zip file from Github equivalent to the bin folder? The directory structure seems a little different. Given that I just downloaded the zip file, I don't need to go through the compiling steps and can go straight to the post-installation, correct?

**Comment by cookpa** [comment]
It's a source code zip. You have to build it.
