### ISSUE TITLE
image registration using label input

### ISSUE THREAD

**Issue by hosuchong** [ANTsX/ANTs#1163]
Hi all,

In the registration process between images, the whole brain mask is received and processed with input.
However, is there a function to receive and process a label image as input?
For example, I need a function for deformable mapping between template and moving image, focused on whole brain mask and ventricle mask. Is there a function already implemented in ANTS? If so, which function should I use?

Thanks,

**Comment by ntustison** [comment]
The use of masks is limited to a single label.  But you can use label images directly as input in any pairwise image registration stage.

**Comment by hosuchong** [comment]
Then, does the label image entering the input act like a boundary condition? Does registration proceed by matching the part corresponding to 1 in the label?

**Comment by ntustison** [comment]
Suppose you have an image pair where the fixed image and moving image have a set of regional labels in common (e.g., {1, 2, 3}.  If you use the mean squares metric, the registration process will try to minimize the sum of the voxelwise label differences within the constraints of the specified transformation.
