### ISSUE TITLE
Error: NWAD while doing ants.registration

### ISSUE THREAD

**Issue by vkyprmr** [ANTsX/ANTs#1164]
**Describe the problem**
I am performing registration on MRI Images. When I used `type_of_transform` as `Rigid`, the script ran smoothly. I wanted to test other types of transform. So, I changed it to `SyN`. I am running the script in a loop for multiple images. For most of the images, I am getting the following error: `** ERROR: NWAD: wrote only 0 of 42958848 bytes to file`. 

**To Reproduce**
Unfortunately, I cannot share the data. The code used:
```
        fixed_image = ants.image_read(self.fixed_path)
        moving_image = ants.image_read(self.moving_path)
        reg_iter = (30, 15, 5)
        affine_iter = (15, 15, 10, 5)
        try:
            self.registered_dct = ants.registration(fixed=fixed_image, moving=moving_image, type_of_transform=transform,
                                                    reg_iterations=reg_iter, aff_iterations=affine_iter)
            registered_image = self.registered_dct['warpedmovout']
            return registered_image, fixed_image
        except:
            pass
```
It was taking a long time to run, almost around 10 mins. I also tried to reduce the iterations, which didn't make any difference.

**System information (please complete the following information)**
Many issues are specific to a particular system. Please include all information
about your computing environment.

 - OS: Ubuntu
 - OS version: 18.04
 - Type of system: Desktop
 
**ANTs version information**
 - ANTs code version: antspyx 0.2.7
 - ANTs installation type: pip install antspyx

**Additional information**
I have a workstation with 32 GB RAM and have 1 TB of hard drive where the images are located. Can this be a /tmp/ issue?

There is a similar closed issue [here](https://github.com/ANTsX/ANTs/issues/564#issue-313099434). But it didn't help me.

**Comment by ntustison** [comment]
Unfortunately, if we can't reproduce the results then it's difficult for us to diagnose.   My suggestion would be to find publicly available data with which you can reproduce the issue.  Also, given as how this is a well-tested script, you might want to explore possible system-specific issues.  Specifically, see if any of the other transform types which output a displacement field also fail.  That would seem to indicate something on your machine which we would be unable to fix.

**Comment by cookpa** [comment]
This is really an ANTsPy issue, but can happen with ANTs too.

If you see that error, the registration has all happened but there's no space to write the warp fields. It's likely due to running out of disk space. 

Try running the command again but set "outprefix" to somewhere other than /tmp, where you can write and you know there is plenty of disk space.

**Comment by vkyprmr** [comment]
Sorry was in a hurry and posted it here.
