### ISSUE TITLE
ANTs Build Error During Compilation

### ISSUE THREAD

**Issue by hookeba** [ANTsX/ANTs#1167]
[build.log](https://github.com/ANTsX/ANTs/files/6199943/build.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/6199945/CMakeCache.txt)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/6199947/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/6199948/CMakeOutput.log)

Hello Everyone!

During a recent “SuperBuild” I encountered an issue with compilation which may be related to an incorrect URL assignment.  I have attached the requested files.  Your expert assistance is greatly appreciated!

Respectfully yours

Bradley A. Hooker

**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)
[X] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS:  Red Hat Enterprise Linux Workstation
 - OS version:  7.9 (Maipo)
 - Type of system:  Workstation
  
**ANTs version**
v2.3.5 (Ecphorella)

**Build configuration and logs**
I have attached the following files:

  - build.log
  - CMakeCache.txt
  - CMakeError.log
  - CMakeOutput.log

**Additional context**
None

**Comment by gdevenyi** [comment]
```
    http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=37aaa33029410941bf4affff0479fa18 ("Timeout was reached")
    https://data.kitware.com:443/api/v1/file/hashsum/MD5/37aaa33029410941bf4affff0479fa18/download ("HTTP response code said error")
    http://www.itk.org/files/ExternalData/MD5/37aaa33029410941bf4affff0479fa18 ("HTTP response code said error")
```

Network connection timeout. Try again.

**Comment by hookeba** [comment]
@gdevenyi Thank you for your diagnosis.  I will try again.

**Comment by hookeba** [comment]
Just trying to go directly to the URLs, here's what I see:
http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=37aaa33029410941bf4affff0479fa18:
This one worked, so I'll try the build again.

The other two appears to have other issues and perhaps the URLs need to be updated?

https://data.kitware.com:443/api/v1/file/hashsum/MD5/37aaa33029410941bf4affff0479fa18/download:
{
    "message": "Invalid value for algo: \"md5\". Allowed values: sha512.",
    "type": "rest"
}
http://www.itk.org/files/ExternalData/MD5/37aaa33029410941bf4affff0479fa18:
Error 404, not found

**Comment by cookpa** [comment]
I think the download is failing for some reason. When I run this, I get

```
Scanning dependencies of target ANTSFetchData
[  0%] Generating /Users/pcook/tmp/NOT_BACKED_UP/antsTesting/build/ANTS-build/ExternalData/TestData/Data/r16slice.nii.gz
-- Fetching "file:////Users/pcook/tmp/NOT_BACKED_UP/antsTesting/ANTs/.ExternalData/MD5/37aaa33029410941bf4affff0479fa18"
-- Fetching "http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=37aaa33029410941bf4affff0479fa18"
-- [download 21% complete]
-- [download 39% complete]
-- [download 63% complete]
-- [download 65% complete]
-- [download 82% complete]
-- [download 98% complete]
-- [download 100% complete]
* Closing connection 0
-- Downloaded object: "/Users/pcook/tmp/NOT_BACKED_UP/antsTesting/build/ANTS-build/ExternalData/Objects/MD5/37aaa33029410941bf4affff0479fa18"
```

In your build.log, you get as far as `-- [download 100% complete]` but then it tries to get the same file from the other servers, so it seems that it couldn't complete the download for some reason.

**Comment by gdevenyi** [comment]
Out of disk space and/or permissions?

**Comment by hookeba** [comment]
Yes, that's a separate issue my Linux support person said they need to work with networking on (downloads stall right near completion, perhaps firewall or IPS related), but if the other sources worked, it may also be able to use those and not fail (as an example, he said they've seen this with yum updates as well, where downloading a package from one source stalls, but then it moves to another mirror and is able to get it, thus it doesn't fail). Any comment on resolving issues with the other sources/mirrors of those source files?

**Comment by cookpa** [comment]
I don't know the status of the other mirrors. You may have to turn testing off in CMake until you can resolve the download problem.
