### ISSUE TITLE
ANTs functions/commands equivalent to those of FSL 

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTs#1168]
It would be great to know ANTs functions/commands equivalent to those available in FSL in a table. It might expedite migration from FSL to ANTs more time/effort-efficiently.

I like ImageMath in ANTs. It replaces many FSL commands that I am familiar with. 

Where could I get a list of ANTs functions/commands for FSL-equivalents like:
fslreorient2std, fslswapdim, fslorient, fslcpgeom, etc. 

Thank you.

**Comment by ntustison** [comment]
>  It would be great to know ANTs functions/commands equivalent to those available in FSL in a table. It might expedite migration from FSL to ANTs more time/effort-efficiently.

This would be a great pull request.  I don't think many, if any, of the major developers use FSL extensively so you would have to put together such a list yourself.

**Comment by gdevenyi** [comment]
My experience is that ANTs doesn't cover the full range of features covered by FSL or minc-toolkit, though what it does cover it does better.

**Comment by sj-choi** [comment]
Thanks for your feedbacks.
