### ISSUE TITLE
TODO: fix masking standards in ITK & ANTs

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTs#117]
background, courtesy @ntustison 

Here’s the relevant code for sampling that’s done in ImageRegistrationMethodv4

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx#L651-L771

Specifically, here’s the two options RANDOM and REGULAR

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx#L709-L758

All we do is use the iterators to get physical points and add them to the
sample point set.  I’m pretty sure that those points are verified against
the mask within the metric but I’d have to check.

(1)  it would seem that we would want to collect samples from within the mask.   the post-hoc mask check currently means lots of samples may fall outside the mask because the samples are collected without knowledge of the mask.  this , combined with some safety check, leads to unnecessary failures.

(2) we also want to allow the user to directly pass the point set over which we will optimize.  so, we need a third option USERDEFINED.   in the mask case, this might mean we sample just once from the mask and then keep these same points all the way through the registration.  this relatively simple change would let us test lots of different sampling strategies.

**Comment by spinicist** [comment]
Just a comment that I think I have had this issue while trying to register pre-clinical images with masks. I gave up and registered them unmasked.

**Comment by ntustison** [comment]
No, I think this is a different issue.

**Comment by gdevenyi** [comment]
Fixed by b872ef3
