### ISSUE TITLE
Basic questions about usage of StackSlices and ImagePad

### ISSUE THREAD

**Issue by valeryozenne** [ANTsX/ANTs#1170]
Dear ANTs experts,

I have two really basic questions regarding ANTs tools:

1) I wish to create a 3D volume from a stack of 2D slices. I would like to know if StackSlices command was designed for ? 
If so, I didn't find a way to use StackSlices with my data. Please find the script and the data at this link.
I also tried to convert my image in Nifti before creating the stack but the output message is the same.

https://filesender.renater.fr/?s=download&token=ffb45ded-08fa-4083-82a4-876e550c878c

2) The ROI of interest in the images is relatively small in comparison to the FOV. To save disk space and time , I would like to crop them before stacking but  ImageMath + Pad is not compatible with 2D images, is there an alternative in ANTs ? 

Thanks in advance,

Best 
Valéry

```
#!/bin/bash

LIST_OF_FILES=$(find Data/ -name "*bmp")

echo ${LIST_OF_FILES}

PrintHeader Data/UNMASC_90356__rec00000281.bmp

echo '---------'
StackSlices  volume.nii.gz -1 -1 30 ${LIST_OF_FILES}

```
return 
```


 Spacing [1, 1]
 Origin [0, 0]
 Direction 
1 0
0 1

 Size : 3392 3016 

  Image Dimensions   : [3392, 3016]
  Bounding Box       : {[0 0], [3392 3016]}
  Voxel Spacing      : [1, 1]
  Intensity Range    : [0, 170]
  Mean Intensity     : 0.978794
  Direction Cos Mtx. : 
1 0
0 1

  Voxel->RAS x-form  : 
  Image Metadata: 
    ITK_original_direction of unsupported type N3itk6MatrixIdLj2ELj2EEE
    ITK_original_spacing of unsupported type St6vectorIdSaIdEE


---------
  Input is a set of 3-D volumes.
  Output region size = [3392, 3016, 20]
 Slice 0 :: Data/UNMASC_90356__rec00000281.bmp
terminate called after throwing an instance of 'itk::InvalidRequestedRegionError'
  what():  /home/vozenne/Dev/antsInstallExample/build/staging/include/ITK-5.2/itkImageFileReader.hxx:339:
ImageIO returns IO region that does not fully contain the requested regionRequested region: ImageRegion (0x7ffd596a8370)
  Dimension: 3
  Index: [0, 0, 30]
  Size: [3392, 3016, 1]
StreamableRegion region: ImageRegion (0x7ffd596a8330)
  Dimension: 3
  Index: [0, 0, 0]
  Size: [3392, 3016, 1]

./command_stask_slice.sh : ligne 10 : 66906 Abandon                 (core dumped) StackSlices volume.nii.gz -1 -1 30 ${LIST_OF_FILES}

```

**Comment by ntustison** [comment]
> 1.  I would like to know if StackSlices command was designed for ?

designed for what?

> 2. The ROI of interest in the images is relatively small in comparison to the FOV. To save disk space and time , I would like to crop them before stacking but ImageMath + Pad is not compatible with 2D images, is there an alternative in ANTs ?

``ExtractionRegionFromImage``

**Comment by valeryozenne** [comment]
Thanks for the quick answer .

1. Sorry,  I'm not 100% sure if StackSlices was designed for merging 2D stack of slices in a 3D volume. If so, I didn't find a way to use StackSlices with my data. Either I didn't use it correctly but the instruction looks simple or either it is related to my dataset . They looks ITK/ANTs compatible, I tried with 2 images in .bmp format and in nifti format. I also output the result of PrintHeader for one image in case it is helpfull.

Thanks for your help.

**Comment by ntustison** [comment]
``StackSlices`` is for extracting a specified slice from multiple 3D volumes to create a single 3D volume.  If you're starting with a set of 2D slices you probably want ``TileImages``.

**Comment by valeryozenne** [comment]
Thanks a lot, this is exactly what I looking for.
I close the issue
