### ISSUE TITLE
Is it possible to obtain the absolute residual image between a noisy image and noise-free image using ANTs?

### ISSUE THREAD

**Issue by sam-eb** [ANTsX/ANTs#1171]
Hi, 

There is no doubt about the capabilities of ANTs, however, I need to represent the impact of pre-processing in my manuscript to convince the reviewer how much the volumes have been improved after pre-processing step that I used ANTs N4 bias correction and `DenoiseImage`  commands. I thought it is better to represent visually in an image, sth similar to the (fig 9) in [this paper](https://onlinelibrary.wiley.com/doi/full/10.1002/jmri.22003)

![fig9](https://user-images.githubusercontent.com/81946511/113538283-11e76880-95f0-11eb-991f-13d43c1f76b4.png)

Is there any command in ANTs that I can obtain the residuals (last row) between noisy (first row) and noise-free (second row) image?

Thank you in advance

**Comment by gdevenyi** [comment]
DenoiseImage --help

**Comment by cookpa** [comment]
You can also output the bias field and noise images directly as shown in the usage for those programs under `-o`. This will show the scaling factor for bias correction from N4, and the estimated noise for DenoiseImage.

If you want to directly compute the difference between two images, then

```
ImageMath 3 diff.nii.gz - noisy.nii.gz noiseFree.nii.gz 
ImageMath 3 absDiff.nii.gz abs diff.nii.gz
```

**Comment by sam-eb** [comment]
@cookpa  Thank you very much for your help. This worked.
