### ISSUE TITLE
Jacobian determinant images from h5 files

### ISSUE THREAD

**Issue by cgaiser1** [ANTsX/ANTs#1173]
This is maybe more of a question concerning fmriprep files but I was wondering if someone here has done something similar previously and is able to comment on this.

I want to create jacobian determinant images by using the fmriprep output files, which are composite transform files (h5), in the following way:

(1) using the h5 file from the fmriprep output together with the MNI152NLin2009cAsym template atlas to apply the transform:
antsApplyTransforms -i sub-1_ses-F13_acq-0003_run-0000_T1w.nii.gz -t sub-1_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5 -r tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz -o sub-1_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm-transfT1.nii.gz

(2) using this output to create the jacobian determinant image:
createJacobianDeterminantImage 3 sub-1_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm-transfT1.nii.gz jacobian.nii.gz

Is this the correct way to go about this?

Thanks!

**Comment by ntustison** [comment]
The input to ``CreateJacobianDeterminantImage`` should be a displacement field and I'm pretty sure that your ``antsApplyTransforms`` call  isn't producing a displacement field.   Please look at the ``-o`` option in the ``antsApplyTransforms`` help menu.

**Comment by cookpa** [comment]
`antsApplyTransforms -i sub-1_ses-F13_acq-0003_run-0000_T1w.nii.gz -t sub-1_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5 -r tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz -o [ sub-1_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm-transfT1.nii.gz, 1 ]`

You might also want to look at options for the CreateJacobianDeterminantImage. 

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians#computing-the-jacobian
