### ISSUE TITLE
still itkLabelImageGenericInterpolateImageFunction.h requirement

### ISSUE THREAD

**Issue by ddddg929** [ANTsX/ANTs#1177]
**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)

**Build environment**
 - OS: [linux]
 - OS version: [Ubuntu 20.04]
 - Type of system: [ cloud instance]
**cmake version**
3.20.1
**ANTs version**
latest
**ITKversion**
InsightToolkit5.1.2

**Problem description**

I am having issues building ANTs (which depends on ITK), and the issue seems to be the following:
```
[  0%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsUtilities.cxx.o
[  1%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o
In file included from /home/duzh/ANT/ANTs/Examples/antsRegistrationTemplateHeader.cxx:1:
/home/duzh/ANT/ANTs/Examples/antsRegistrationTemplateHeader.h:21:10: fatal error: itkLabelImageGenericInterpolateImageFunction.h: No such file or directory
   21 | #include "itkLabelImageGenericInterpolateImageFunction.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/build.make:90: Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/Makefile2:2827: Examples/CMakeFiles/antsUtilities.dir/all] Error 2
make[3]: *** [Makefile:166: all] Error 2
make[2]: *** [CMakeFiles/ANTS.dir/build.make:88: ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/ANTS.dir/all] Error 2
make: *** [Makefile:121: all] Error 2
```
I learned that this problem was once mentioned in #817, and I tried the solution showed in it at first
![image](https://user-images.githubusercontent.com/61380549/115106259-4e26ab80-9f96-11eb-8c57-b02f1774b606.png)
I found it was already 'on' state
Secondly, https://github.com/InsightSoftwareConsortium/ITK/issues/1200 said I should turn on the cmake flag 'Module_ITKReview'
So, I recompiled ITK with following cmake flag,
![image](https://user-images.githubusercontent.com/61380549/115106336-cf7e3e00-9f96-11eb-8876-57d1b1b07e30.png)
But I can not find the flag 'Module_ITKReview', I turned on the flag ‘ModuleSimpleITKFilters ’,

But there was still an error compiling ANTs

**Comment by ddddg929** [comment]
ANTs cmake error
[build.txt](https://github.com/ANTsX/ANTs/files/6328854/build.txt)

**Comment by ddddg929** [comment]
ITK compile output in command line:
[ITK_complie_file.txt](https://github.com/ANTsX/ANTs/files/6328860/ITK_complie_file.txt)

**Comment by ddddg929** [comment]
**Build configuration and logs**
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/6328932/CMakeOutput.log)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/6328935/CMakeError.log)
[build.log](https://github.com/ANTsX/ANTs/files/6328937/build.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/6328938/CMakeCache.txt)

**Comment by ntustison** [comment]
I would suggest using the Superbuild mechanism to build ANTs.  This ensures that the ITK configuration is done correctly.

**Comment by cookpa** [comment]
If you have the correct version of ITK, as explained here

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#using-system-itk-or-vtk

the module is definitely available. If you are configuring with `ccmake` you need to display advanced options (hit t).

Unless there is a reason to use your own system ITK, you can just leave USE_SYSTEM_ITK to its default value of OFF and the SuperBuild will compile it correctly for you.

**Comment by ddddg929** [comment]
Before, git clone always failed due to network reasons, so I used local ITK compilation.I successfully compiled ANTs through superbuild.  Thank you @cookpa and @ntustison
