### ISSUE TITLE
Unable to BUILD

### ISSUE THREAD

**Issue by vaidehithakre21** [ANTsX/ANTs#1179]
I am able to do everything until the build step.

As soon as I enter **'make > build.log 2>&1'** I get an error which is listed in the wiki headed **'The build completed but I forgot to set the install prefix and can't write to the default'.**

When I tried to do as suggested in that heading, it still gave me the same error after I command 'make install'. How do I solve this?
Please help me! 

![Screenshot from 2021-04-22 16-04-31](https://user-images.githubusercontent.com/52854465/115701738-b7872f80-a385-11eb-931e-ef870c483afc.png)

**Comment by cookpa** [comment]
You need to replace the placeholder path `/new/install/dir` with a real path where you have write permission.
