### ISSUE TITLE
Registration of high resolution T1 to high res EPI (partial head)

### ISSUE THREAD

**Issue by kmullinger** [ANTsX/ANTs#1182]
Hi

I've been trying to register 7T partial head T1 anatomical to a mean EPI image (which has already been distortion corrected). We have the 2 images in almost the same space but the activation from the EPI doesn't overlay on the GM mask of the T1 very well so we are trying to improve the registration. I have the code below which is adapted from https://layerfmri.com/2019/02/11/high-quality-registration/. However the EPI data in the laynii blog is T1 weighted whereas our EPI data is T2* weighted.

antsRegistration --dimensionality 3\
 --float 1\
 --collapse-output-transforms 1\
 --interpolation BSpline[5]\
 --output [${data_dir}/registered1_,${data_dir}/registered1_Warped.nii,${data_dir}/registered1_InverseWarped.nii]\
 --use-histogram-matching 0\
 --winsorize-image-intensities [0.005,0.995]\
 --initial-moving-transform PSIR_onto_EPIhr_init_identity.tfm\
 --transform Rigid[0.1] --metric MI[${static_img},${moving_img},1,32,Regular,0.25]\
 --convergence [1000x500x250x100,1e-6,10]\
 --shrink-factors 12x8x4x2\
 --smoothing-sigmas 4x3x2x1vox\
 --transform Affine[0.1] --metric MI[${static_img},${moving_img},1,32,Regular,0.25]\
 --convergence [1000x500x250x100,1e-6,10]\
 --shrink-factors 12x8x4x2\
 --smoothing-sigmas 4x3x2x1vox\
 --transform SyN[0.1,3,0] --metric CC[${static_img},${moving_img},1,4]\
 -g .5x.1x.1\
 --convergence [50x50x70x50x20,1e-6,10]\
 --shrink-factors 10x6x4x2x1\
 --smoothing-sigmas 5x3x2x1x0vox\
 -x ${mask_vis}

The rigid and the Affine registrations run and improve the registration, however I wanted the SyN to run as that was the part I was hoping might provide the most benefit.... However it consistently gives me this error after running through the first set of convergences (i.e. will stop after 50 iterations) saying that the images do not occupy the same physical space

![ANTs_SyN_error](https://user-images.githubusercontent.com/31032977/116219633-b8341300-a743-11eb-924d-dfefe22fc192.PNG)

as you will see I have set -g and played around with this between .5 and 1 in the phase encode. I have also tried BSplineSyN. I have also tried changing convergence from [50x50x70x50x20,1e-6,10] to [10x50x70x50x20,1e-6,10] and lots of things in between. I have also tried a number of different masks: none, whole of the brain area, just the visual area of interest

Is it simply that the 2 images I am trying to register are too different and can't be done? 

I am happy to share the images for you to have a look but they are too big to drop on here so will have to share a different way.

thanks

Karen

**Comment by ntustison** [comment]
> Is it simply that the 2 images I am trying to register are too different and can't be done?

No, actually this error originates from relatively deep within the ITK framework.  The basic conceptual idea is that anytime the user does anything with a pair of images (e.g., something simple like voxelwise addition), the images should have the exact same geometry and sampling.  This error is one of those checks failing.  But, as you can see, your images are simply failing due to precision issues.   Unfortunately, I can only guess as to where your floating point values are "drifting."  If you do share your data, I can take a look but this is one of those issues that is system-specific and I might not be able to reproduce.

**Comment by cookpa** [comment]
It looks like you're using a rather old version of ANTs. There have been various efforts to reduce this problem in ITK, so you might benefit from updating to the latest version.

**Comment by kmullinger** [comment]
> > Is it simply that the 2 images I am trying to register are too different and can't be done?
> 
> No, actually this error originates from relatively deep within the ITK framework. The basic conceptual idea is that anytime the user does anything with a pair of images (e.g., something simple like voxelwise addition), the images should have the exact same geometry and sampling. This error is one of those checks failing. But, as you can see, your images are simply failing due to precision issues. Unfortunately, I can only guess as to where your floating point values are "drifting." If you do share your data, I can take a look but this is one of those issues that is system-specific and I might not be able to reproduce.

Thank you, do you have an email and then I can share a link to where the files are? I can't upload them I don't think as they are too big I believe

**Comment by kmullinger** [comment]
> It looks like you're using a rather old version of ANTs. There have been various efforts to reduce this problem in ITK, so you might benefit from updating to the latest version.

Ok thank you I will look into getting this updated, it's on a central computer facility so not a quick process

**Comment by kmullinger** [comment]
@ntustison Thank you, do you have an email and then I can share a link to where the files are? I can't upload them I don't think as they are too big I believe

**Comment by ntustison** [comment]
Given that you're using an old version of ANTs, there's not much we can do until you recompile to the latest ANTs/ITK combination.  If the problem persists after you've updated, then we can take a look at your particular situation.

**Comment by kmullinger** [comment]
Thank you, I'll get the latest versions and see if it solves the problem (I'll be happy if it does)
