### ISSUE TITLE
ANTs v0.0.0.0

### ISSUE THREAD

**Issue by sdesutter** [ANTsX/ANTs#1183]
**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)
[x] After

**Build environment**
Mac OS, Mojave, version 10.14.6, laptop
 
**ANTs version**
v2.3.5
(downloaded source: ANTsX-ANTs-v2.3.5-30-g1759e5e.tar.gz, downloaded on 27.04.2021)

**Build configuration and logs**
[build.log](https://github.com/ANTsX/ANTs/files/6391654/build.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/6391655/CMakeCache.txt)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/6391661/CMakeOutput.log)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/6391662/CMakeError.log)

**Additional context**
Hi!

I installed recently installed ANTs on my mac (macOS Mojave 10.14.6) from the source tarball.
The name of the tarball specified that the version was v2.3.5.

Installation was successful and I could perform N4 Bias Field Correction, however, when I wanted to add rescaling, I got the error that the required version was 2.1.0, while mine was 0.0.0.
Indeed, `antsRegistration --version` in the terminal outputted:
`ANTs Version: 0.0.0.0`

I tried completely reinstalling it, but this didn't seem to help.

Thanks in advance for any help or suggestions!

**Comment by gdevenyi** [comment]
Please provide the information requested in the issue template.

**Comment by sdesutter** [comment]
> Please provide the information requested in the issue template.

Information was added!

**Comment by gdevenyi** [comment]
> (downloaded source: ANTsX-ANTs-v2.3.5-30-g1759e5e.tar.gz, downloaded on 27.04.2021)

Do you have git available? The build code extracts the version from the git repository, since you didn't clone you don't have that information.

**Comment by cookpa** [comment]
>Installation was successful and I could perform N4 Bias Field Correction, however, when I wanted to add rescaling, I got the error that the required version was 2.1.0, while mine was 0.0.0.

@ntustison have you seen this error before? I've never seen anything in the code that would require a particular version.

**Comment by ntustison** [comment]
I have not.  @sdesutter --- please post the full screen output because I don't recognize this behavior.

**Comment by sdesutter** [comment]
> I have not. @sdesutter --- please post the full screen output because I don't recognize this behavior.

To be clear, I use ANTs through the Nipype interface (https://nipype.readthedocs.io/en/latest/#)
When trying to call N4 Bias Field Correction, I got the following error:
`Exception: Trait rescale_intensities (N4BiasFieldCorrection) (version 0.0.0 < required 2.1.0)`

In the docs of nipype.interfaces.ants (https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.ants.segmentation.html), there is also specified (under N4BiasFieldCorrection > Optional inputs > rescale_intensities): `[NOTE: Only ANTs>=2.1.0]`

**Comment by ntustison** [comment]
Thanks.  In this case, you'd have to talk to the Nipype people.  That's a constraint that they put on their interface to N4 and not an issue with N4 itself.

**Comment by sdesutter** [comment]
> Thanks. In this case, you'd have to talk to the Nipype people. That's a constraint that they put on their interface to N4 and not an issue with N4 itself.

Makes sense! But doesn't it mean there was a problem with my installation if the version of ANTs is 0.0.0.0?

**Comment by ntustison** [comment]
@cookpa or @gdevenyi would have to answer this---I believe @cookpa (or perhaps @stnava) set up the versioning.  I always compile from source.

**Comment by gdevenyi** [comment]
The build code extracts versions from the git environment, otherwise, the user can manually provide the versioning during build:
https://github.com/ANTsX/ANTs/blob/master/ANTS.cmake#L34-L51

**Comment by cookpa** [comment]
The version of 0.0.0.0 is a placeholder used when CMake can't find git information to populate the version fields. It will go away if you use `git clone` and checkout the version you want to build.

**Comment by sdesutter** [comment]
> The version of 0.0.0.0 is a placeholder used when CMake can't find git information to populate the version fields. It will go away if you use `git clone` and checkout the version you want to build.

That did the trick, now it works! Thanks everyone for the help!
