### ISSUE TITLE
 N4BiasFieldCorrection - Incorrect command line specification - using path with spaces

### ISSUE THREAD

**Issue by bramcal** [ANTsX/ANTs#1184]
I wrote a simple for loop to perform Bias field correction on all images in a certain folder. 
The code works fine until there are spaces within the path. 
I used the following command:  
path = "/path/to/data/with spaces/in/path"
IFS=$'\n'
for file in `find $path -name "*.nii"`; do
N4BiasFieldCorrection -d 2 -i $file -o ["corrected.nii", "BiasField.nii"] -v ;
done

error message:  
terminate called after throwing an instance of 'itk::ExceptionObject'
what():  /home/u0135611/ANTs/Utilities/antsCommandLineParser.cxx:304:
itk::ERROR: CommandLineParser(0x7fffe5446b30): Incorrect command line specification.
Aborted (core dumped)

I have tried both $path, "$path", "${path}",.... 

System info: windows subsystem for linux (ubuntu 18.04 LTS) on a windows 10 computer

**Comment by gdevenyi** [comment]
Please test a non loop command

**Comment by bramcal** [comment]
I've tried it without a loop: 

N4BiasFieldCorrection -d -i /path/with/spaces/in  the/path/test.nii -o ["corrected.nii", "BiasField.nii"] -v; 

N4BiasFieldCorrection -d -i /path/with/spaces/'in  the'/path/test.nii -o ["corrected.nii", "BiasField.nii"] -v; 

N4BiasFieldCorrection -d -i "/path/with/spaces/'in  the'/path/test.nii" -o ["corrected.nii", "BiasField.nii"] -v;

N4BiasFieldCorrection -d -i "/path/with/spaces/in  the/path/test.nii" -o ["corrected.nii", "BiasField.nii"] -v;  

None of the above worked. 
It does work when I navigate to the correct folder and run: 
N4BiasFieldCorrection -d -i "test.nii" -o ["corrected.nii", "BiasField.nii"] -v;

**Comment by ntustison** [comment]
Did you try escaping the space with a backslash?

**Comment by cookpa** [comment]
Double quoting the path works for me, but I'm not using Windows.

`N4BiasFieldCorrection -d 3 -i "dir space/MNI152_T1_1mm.nii.gz" -o [ "corrected.nii", "BiasField.nii" ] -v`

The for loop example will fail because bash expects a space separated list, and if you have paths with spaces, it will break them up. You would need to get `find` to quote the strings it outputs, or use xargs.

What happens if you do

ls -l "/path/with/spaces/in the/path/test.nii"

**Comment by bramcal** [comment]
> Did you try escaping the space with a backslash?

Yes I tried using a backslash but this did not work. 



> Double quoting the path works for me, but I'm not using Windows.
> 
> `N4BiasFieldCorrection -d 3 -i "dir space/MNI152_T1_1mm.nii.gz" -o [ "corrected.nii", "BiasField.nii" ] -v`
> 
> The for loop example will fail because bash expects a space separated list, and if you have paths with spaces, it will break them up. You would need to get `find` to quote the strings it outputs, or use xargs.
> 
> What happens if you do
> 
> ls -l "/path/with/spaces/in the/path/test.nii"

when I do: 
 ls -l "/path/with/spaces/in the/path/test.nii" 

i get -rwxrwxrwx 1

**Comment by cookpa** [comment]
Not sure what to make of this, but maybe some other WSL users have figured it out (@dorianps if you have time to take a look).

The literal quoted string works for me on Linux and Mac:

`N4BiasFieldCorrection -d 3 -i "dir space/MNI152_T1_1mm.nii.gz" -o [ "corrected.nii", "BiasField.nii" ] -v`

As does the backslash

`N4BiasFieldCorrection -d 3 -i dir\ space/MNI152_T1_1mm.nii.gz -o [ "corrected.nii", "BiasField.nii" ] -v`

With variables, bash does not protect variables like some other languages do, so you can't do

`myPath="dir space/MNI152_T1_1mm.nii.gz"
N4BiasFieldCorrection -d 3 -i $myPath -o test.nii.gz --verbose`

but you can use the variable if you quote its expansion:

`myPath="dir space/MNI152_T1_1mm.nii.gz"
N4BiasFieldCorrection -d 3 -i "$myPath" -o test.nii.gz --verbose`

**Comment by dorianps** [comment]
I don't have ANTs ready to go in WSL, but can install and try this. The problem does not seem to be related to WSL because there is nothing special there, it's just a regular bash shell in Ubuntu. I am starting to suspect the real path @bramcal uses has some special characters. Quotes and escapes usually do the trick for paths with spaces. So, what is the real path you are using, does it have any unsual german/chinese/russian characters?

Let me know if you think it's still worth trying separately on WSL.

**Comment by dorianps** [comment]
The only other thing is the last suggestion by @cookpa , wrap quotes around the variable. But @bramcal seem to not make it work even with a straight call of the path.

**Comment by cookpa** [comment]
Thank you @dorianps . I was just wondering if you had seen this issue before. It's strange that the quoted literal string doesn't work. No need to build ANTs just for this, unless you'd like to.

I missed that the bash variable `IFS` is set to a custom value in the original post. I'm not sure how it would change things but maybe unset that as well, just to see if it helps any when typing out the literal path.

One more suggestion for @bramcal: type `set -x` before calling N4. That should print what the command line is after shell expansion.

**Comment by gdevenyi** [comment]
Setting non standard IFS is definitely gonna break something. It's almost never solved anything, just introduced new problems.

**Comment by bramcal** [comment]
@dorianps the path doesn't contain unusual characters

@cookpa  and @gdevenyi  tried with IFS because it wasn't working, but previously I tried without. 

I 'solved' or avoided the issue by using: 

`path = "/path/to/data/with spaces/in/path"
cd "$path"
for file in *.nii; do
N4BiasFieldCorrection -d 2 -i $file -o ["corrected.nii", "BiasField.nii"] -v ;
done`
