### ISSUE TITLE
MNI normalisation of cortical thickness maps

### ISSUE THREAD

**Issue by marivas-MRI** [ANTsX/ANTs#1186]
Dear ANTs experts, 

I ran the antsCorticalThickness.sh script and obtained the cortical thickness images of my subjects. Now I would like to normalise these native maps towards the MNI space in order to perform statistical analyses. However I am a bit confused about how is the most appropiated way to normalise these cortical thickness images. To do that I was planning to use the deformation fields (ApplyTransforms) obtained when I registered my t1 images towards a MNI template (antsRegistrationSyN). My questions are:

1. Is correct to normalise the cortical thickness images using the deformation fields?
2. Normalising these cortical thickness images using the def. fields will change the thickness values of each voxel or not? 
3. When I have worked with other toolboxes (e.g. CAT12) the normalized surface data is smoothed with larger gaussian kernels (e.g. 12 mm). After normalizing these images should I also use this filter?

I would really appreciate some help about what could be a good approach to normalise these cortical thickness images in native space. 

Best regards,

**Comment by ntustison** [comment]
> Is correct to normalise the cortical thickness images using the deformation fields?

You can.  That's why we included such an option in the cortical thickness script.

> Normalising these cortical thickness images using the def. fields will change the thickness values of each voxel or not?

Not outside of the normal interpolation considerations.

> When I have worked with other toolboxes (e.g. CAT12) the normalized surface data is smoothed with larger gaussian kernels (e.g. 12 mm). After normalizing these images should I also use this filter?

We don't have much, if any, experience with CAT12 so that would be difficult to say.  However, you should always be cautious about combining elements from different pipelines.
