### ISSUE TITLE
Applying a saved nonliner transformation to other images 

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTs#1187]
So far, I have no issue in applying a saved AFFINE transformation matrix to other images.
However, I encountered an issue in applying a transformation matrix saved during SyNQuick registration (non-linear). I applied a save transformation (individual T1 to MNI152) to other images (a few FLAIR images in the individual T1 space). This did not go well. The T1 and FLAIR images do not well overlay while the T1 overlays well over the MNI152 template image. 

I am not sure if I can simply apply the saved matrix (linear or non-linear transformation) to any images in the same initial space.  If I am doing something incorrectly, please correct me. 

Thank you.

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

**Comment by sj-choi** [comment]
Thank you! I see what/where I missed.
