### ISSUE TITLE
antsApplyTransformsToPoints does not match antsApplyTransforms

### ISSUE THREAD

**Issue by mibur1** [ANTsX/ANTs#1193]
**Problem**

Dear experts,
I want to transform a brain atlas (defined by seed coordinates) into a different space  (MNI to T1w), by using a composite .h5 transform provided by fMRIprep. This is not working correctly with antsApplyTransformsToPoints but antsApplyTransforms seems to work fine (but is no solution because many seeds vanish because of the displacement field).

**To Reproduce**

To simplify it, I used a csv with one 3D coordinate [27, -97, -13] -> single.csv
![mni](https://user-images.githubusercontent.com/61502279/118252597-39f8a000-b4a9-11eb-9a62-0934d10f868a.png)

1. antsApplyTransformsToPoints (incorrect result):

      I transformed the poinit with a composite .h5 file provided by fMRIprep:
      
      `antsApplyTransformsToPoints -d 3 -i single.csv -o single_transformed.csv -t transform.h5`

      Result:
      ![points](https://user-images.githubusercontent.com/61502279/118252876-8a6ffd80-b4a9-11eb-8b03-ef591f2e481e.png)

      As recommended here https://sourceforge.net/p/advants/discussion/840261/thread/ba6a10b0/ I also decomposed the transform.h5 into its components using 'CompositeTransformUtil --disassemble' with identical results.

     `antsApplyTransformsToPoints -d 3 -i single.csv -o single_transformed.csv -t field.nii.gz -t affine.mat`

2. antsApplyTransforms (correct result):

      I created a nifti file in the original space, in which I only set the specific voxel to 1 -> single.nii.gz
      I used a reference file from the output space -> ref.nii.gz

      `antsApplyTransforms -e 3 -d 3 -i single.nii.gz -r ref.nii.gz -o single_transformed.nii.gz -t transform.h5 -n nearestNeighbor -v`

      -v shows me the order of transformations (I used the same order for antsApplyTransformsToPoints):
      ```
      ======================================================================
      The composite transform comprises the following transforms (in order):
        1. transform.h5[0] (type = DisplacementFieldTransform)
        2. transform.h5[1] (type = AffineTransform)
      ======================================================================
      ```

      Result:
      ![transforms](https://user-images.githubusercontent.com/61502279/118252892-91970b80-b4a9-11eb-8fe1-12ba616b23f7.png)

Am I missing something important here, or is this indeed an issue? Any help/feedback would be greatly appreciated. Thank you!

I uploaded all the files I used here: https://mega.nz/file/lJ10SDJA#A20S9EtaM4mbLBsyND8MTsYKo_thpuYBm8J4FBOoSyk

**System information**
 - OS: Ubuntu 20.04.1 LTS in WSL2
 - ANTs Version: 2.3.5.dev238-g1759e, Compiled: May  5 2021 19:46:27

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

**Comment by mibur1** [comment]
Thank you for your answer! Could you maybe elaborate? Sorry if I missed something, but after carefully reading the reference, I think I've done it that way?

I have two composite transform files:
1. moving to fixed: T1w_to-MNI152Lin_mode-image_xfm.h5
2. fixed to moving: MNI152Lin_to-T1w_mode-image_xfm.h5

So the second file already contains the inverse of the warp and affine from the first file. This second file is what I named transform.h5 (or after decomposing) affine.mat/field.nii.gz in my initial post.

**Comment by stnava** [comment]
we believe that you have a mistake in either (a) your construction of transformations or (b) the way you've defined the point coordinates.    they both have to be right for this to work.

in ANTsR or ANTsPy we have functions that will turn segmentations into coordinates that you can use to help check your point representation `get_centroids` and `getCentroids`

**Comment by mibur1** [comment]
Thank you for your patience, I think I found the issue.

1. I tried `get_centroids()` in ANTsPy and got the following result for the `antsApplyTransforms()` input:
      ```
      ANTsImage (RPI)
               Pixel Type : float (float32)
               Components : 1
               Dimensions : (91, 109, 91)
               Spacing    : (2.0, 2.0, 2.0)
               Origin     : (-90.0, 126.0, -72.0)
               Direction  : [ 1.  0.  0.  0. -1.  0.  0.  0.  1.]
      
      [[-28.  98. -14.   0.]]
      ```

2. My `antsApplyTransformsToPoints()` .csv input is:
      ```
      X,Y,Z
      27,-97,-13
      ```

Does that mean it is an issue with the coordinate space (RAS/LPS)? And if so, do you have any hints for me in how to approach this?

**Comment by gdevenyi** [comment]
You input coordinates are in RAS. Convert them to LPS (-x, -y, +z)

**Comment by mibur1** [comment]
So [-27,97,-13] as the .csv input? That still does not seem to work.
