### ISSUE TITLE
consistency of transformation image orientation for dbm analysis

### ISSUE THREAD

**Issue by zswgzx** [ANTsX/ANTs#1194]
Hi, I wonder how the orientation of the ANTs transformation images works.
My goal is to register a cohort of T1 scans (in two time points) to a template nonlinearly, and extract jacobian of the deformations for statistical analysis.
My concern is that some of the scans has LPI orientation and others RPI (after niis are converted from DICOM, but they're consistent, meaning they're correct in terms of physical left & right). So I wonder if the output transformation images are ready for analysis directly, or should I enforce the same orientation before even running ANTs?
My guess is they can be used directly without changing before running, but just want to confirm. Any insight appreciated.

**Comment by stnava** [comment]
the output physical space is defined by the template you use.

brian

**Comment by gdevenyi** [comment]
Hi @zswgzx 

I have a complete implementation of a DBM pipeline (with longitudinal support) written as a wrapper around the ANTs unibased template builder at https://github.com/CoBrALab/twolevel_ants_dbm
