### ISSUE TITLE
Cook my template for priors

### ISSUE THREAD

**Issue by andmark110** [ANTsX/ANTs#1195]
Dear ANTs team,

I get a bad template priors from antsMultivariateTemplateConstruction2.sh as follow:
[prior1.nii.gz](https://github.com/ANTsX/ANTs/files/6487453/prior1.nii.gz)
[prior2.nii.gz](https://github.com/ANTsX/ANTs/files/6487454/prior2.nii.gz)
[prior3.nii.gz](https://github.com/ANTsX/ANTs/files/6487456/prior3.nii.gz)
[prior4.nii.gz](https://github.com/ANTsX/ANTs/files/6487457/prior4.nii.gz)
[prior5.nii.gz](https://github.com/ANTsX/ANTs/files/6487458/prior5.nii.gz)
[prior6.nii.gz](https://github.com/ANTsX/ANTs/files/6487459/prior6.nii.gz)

This is my template:
[T_template0.nii.gz](https://github.com/ANTsX/ANTs/files/6487358/T_template0.nii.gz)

This is my Cooktemplate command:

[Cookmytemplate.txt](https://github.com/ANTsX/ANTs/files/6487405/Cookmytemplate.txt)

I can not solve it, please help me. Thank you.

**Comment by ntustison** [comment]
Priors look pretty good to me.  Why do you believe they are "bad"?

**Comment by andmark110** [comment]
Template priors have some defects except prior1. 
Such as:
<img width="629" alt="Screen Shot 2021-05-16 at 10 48 40 AM" src="https://user-images.githubusercontent.com/48010812/118383856-507f3280-b634-11eb-9f54-2156885dce0a.png">

I thought these defects might be uncorrected, right?

**Comment by ntustison** [comment]
Use ITK-SNAP to view the results.  That's not what I see.

**Comment by andmark110** [comment]
I have viewed the prior6 in ITK-SNAP as follow:
![image](https://user-images.githubusercontent.com/48010812/118384389-3e9f8e80-b638-11eb-9fa9-d920750b8984.png)

There are still some defects in prior6.

**Comment by ntustison** [comment]
Again, that's not what I see in your prior6 file.

<img width="1080" alt="Screen Shot 2021-05-15 at 8 34 32 PM" src="https://user-images.githubusercontent.com/324811/118384690-ff802780-b5bc-11eb-947f-d8244d16b8d7.png">

**Comment by andmark110** [comment]
I notice you view the priors6 file, but I viewed the prior6(not priors6). Might be the issue with the file upload? 
I reupload them.
[prior1.nii.gz](https://github.com/ANTsX/ANTs/files/6488662/prior1.nii.gz)
[prior2.nii.gz](https://github.com/ANTsX/ANTs/files/6488663/prior2.nii.gz)
[prior3.nii.gz](https://github.com/ANTsX/ANTs/files/6488664/prior3.nii.gz)
[prior4.nii.gz](https://github.com/ANTsX/ANTs/files/6488665/prior4.nii.gz)
[prior5.nii.gz](https://github.com/ANTsX/ANTs/files/6488666/prior5.nii.gz)
[prior6.nii.gz](https://github.com/ANTsX/ANTs/files/6488667/prior6.nii.gz)

Thank you for viewing them again.

**Comment by ntustison** [comment]
Okay, now I can see it.   

Please prepare a complete example.  Specifically, I want to be able to download a single folder with all the necessary input data.  Also, please include just the command call.  I want to be able to simply `cd` to the downloaded directory and run a single command to try to reproduce your output data.

**Comment by andmark110** [comment]
Thank you. Can you give me an email? The input data was a bit big. 

Actually, I have uploaded my new_template and the other files come from 'MICCAI2012-Multi-Atlas-Challenge-Data'.
[new_template.nii.gz](https://github.com/ANTsX/ANTs/files/6490841/new_template.nii.gz)

If that is ok, you may need to modify my command (Cookmytemplate.txt) and try to run it.

**Comment by ntustison** [comment]
You can find my email in my profile.  And, again, please put together a sufficiently complete example that I can just navigate to the downloaded directory and run a single command without having to modify anything.

**Comment by andmark110** [comment]
Hi Nick,


I have attached the input data and command. Thank you for your help.


Hope you are having a good week and Looking forward to your reply.


Lin



Yanlin Wang


Postgraduate


Huaxi MR Research Center(HMRRC)


Department of Radiology


West China Hospital


Sichuan University


Chengdu, China, 610041






从QQ邮箱发来的超大附件

Cooktemplateprior.zip (753.04M, 2021年06月17日 10:02 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=78303735cb248cb547e731291763514a56555103570152521f020156504e570454541a0d055a56480203065100065a570a015406317663265d5f5c41540e130953445245430a0c171c4a5e45315e&code=20751cce

**Comment by ntustison** [comment]
Thanks for this.  Quick question, though---is there a reason why you just didn't call the ANTs script [antsCookTemplatePriors.sh](https://github.com/ANTsX/ANTs/blob/master/Scripts/antsCookTemplatePriors.sh)?

**Comment by andmark110** [comment]
I did my 'Cooktemplateprior.sh' by referring to this command. In addition, I also have tried this script and the issue still existed. I think it might be caused by incorrect input data? Thanks for your help.

**Comment by ntustison** [comment]
The problem is not the input data but rather numerical imprecision and this [line](https://github.com/ANTsX/ANTs/blob/master/Scripts/antsCookTemplatePriors.sh#L615).  In your case, the max for these prior images is just greater than 1 so this line is removing those voxels.  If you replace in your code (line 207) this

``${ANTSPATH}ThresholdImage 3 $prior $tmp 0 1 1 0``

with

``${ANTSPATH}ThresholdImage 3 $prior $tmp 0 1 1.1 0``

hen it should work.

**Comment by cookpa** [comment]
This was also a problem in `antsCorticalThickness.sh` some time ago, I think @jeffduda discovered it. I think it was caused by the new implementation of Gaussian smoothing. The recursive algorithm can sometimes map data in the range of [0,1] to values just outside those ranges. Spline interpolation of warped priors can cause the same issue, but I don't think that's used in our scripts.

I fixed it with ImageMath's WindowImage, eg

`${ANTSPATH}/ImageMath ${DIMENSION} $PRIOR WindowImage $PRIOR 0 1 0 1`

I will make a PR to do the same for the cooking script.

**Comment by ntustison** [comment]
Thanks @cookpa

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/pull/1197

**Comment by gdevenyi** [comment]
> I fixed it with ImageMath's WindowImage, eg
Oh wow, I missed this existing, this will simplify a number of things I write with the ThresholdImage/ImageMath multiply right now.
