### ISSUE TITLE
Apply Transforms In Different Resolutions

### ISSUE THREAD

**Issue by ddrrnn123** [ANTsX/ANTs#1198]
Hey guys, I got a question about implementing the transforms on sequences in different resolutions. 

My strategy is to use low-resolution image sequences to get the affine matrices and apply them to a high-resolution version of these sequences because of the time-consuming and computation. 

I have a sequence of the affine matrices in .mat files, which is from the low-resolution images (4000 * 4000). They can register well to the same space when using "antsApplyTransformsCMD" with these matrices. However, if I simply use these matrices on the higher-resolution version (same image contents but a larger size 10000 * 10000), the results will show good rotation performances (the angles of patterns on images are matched), but fail to align the center well. They somehow shift to left-bottom or right-top and can not align to the same space.

I am wondering whether antsApplyTransforms can directly use affine matrices between different sizes of images? If not, how can we modify our matrices to match the new size of the image? The matrices can read with "sitk.ReadTransform(affine_mtx_file)". Thank you very much!

**Comment by cookpa** [comment]
Are you using ANTs or some other implementation (like ANTsPy)?

antsApplyTransforms should work with different reference space resolutions, but the physical space needs to be the same in both cases. It sounds like the origin of physical space in your downsampled and upsampled reference spaces might differ.

How did you create them?

**Comment by ddrrnn123** [comment]
> Are you using ANTs or some other implementation (like ANTsPy)?
> 
> antsApplyTransforms should work with different reference space resolutions, but the physical space needs to be the same in both cases. It sounds like the origin of physical space in your downsampled and upsampled reference spaces might differ.
> 
> How did you create them?

Thanks for your reply! I created the affine matrices by other keypoint registration (like SIFT) on low-resolution images. First, I got matched keypoint pairs and used cv2.estimatedAffine2D to create inverse affine matrices M_inv. After that, I used low-resolution image sizes (4000 * 4000) to set up FixParameters and use the parameters to compute M_vector for Transform (m) in sitk. Here is the code.

    M_inv, rigid_mask_inv = cv2.estimateAffine2D(target_matched_kpts_new, source_matched_kpts_new)
    M_vector = np.zeros([6])
    
    #world coordinate to itk
    FixParameters = [img2_highres.shape[1]/2.0, img2_highres.shape[0]/2.0]
    M_vector[0] = M_inv[0, 0]
    M_vector[1] = M_inv[0, 1]
    M_vector[2] = M_inv[1, 0]
    M_vector[3] = M_inv[1, 1]
    M_vector[4] = (FixParameters[0] * M_inv[0, 0] + FixParameters[1] * M_inv[0, 1] - FixParameters[0]) + M_inv[0, 2]
    M_vector[5] = (FixParameters[0] * M_inv[1, 0] + FixParameters[1] * M_inv[1, 1] - FixParameters[1]) + M_inv[1, 2]

    m = sitk.ReadTransform('test.mat')

    m.SetParameters(M_vector)
    m.SetFixedParameters(FixParameters)

    sitk.WriteTransform(m, os.path.join(overlay_dir, 'sift_affine_init.mat'))

This sift_affine_init.mat can be loaded as an initial affine matrix when doing 'antsRegistrationSyN.sh' in the next step. I m wondering whether we can directly change low-resolution FixParameters with a high-resolution size (10000*10000) and the new matrices can fix this issue? Thank you very much!

**Comment by cookpa** [comment]
You can test your initial affine transform by calling `antsRegistration` with the -r option, and 0 iterations. 

```
antsRegistration -d 2 -r initialAffine.mat -t Rigid[0.1] \
-m MI[ fixed.nii.gz, moving.nii.gz, 1, 32] -c 0 -f 4 -s 2 \
-o [movingInit, movingInit_deformed.nii.gz] 
```

If `antsApplyTransforms` works correctly on the downsampled images but not the full-resolution images, I would check that the physical space of the two images agree. If you place a point on the same feature in both images (eg, the same anatomical location in a brain), the physical coordinates should agree.
