### ISSUE TITLE
Possible issues with GradientDescentOptimizerv4

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#1200]
https://github.com/InsightSoftwareConsortium/ITK/issues/2570

**Comment by cookpa** [comment]
Thanks @gdevenyi . It looks like the metric values and transform parameters would be offset by one iteration. So hopefully this would have a small effect on results but it would be good to resolve.

**Comment by gdevenyi** [comment]
Ref: https://github.com/InsightSoftwareConsortium/ITK/pull/2572
