### ISSUE TITLE
`SmoothDisplacementField` not outputting inverse

### ISSUE THREAD

**Issue by NadiaBlostein** [ANTsX/ANTs#1202]
**The problem**
We are not able to obtain the inverse of the smoothed version of a non-linear (NL) warp field. We were able to obtain the forward warp output by `SmoothDisplacementField` (setting the last option to 0). However, we were not able to obtain the inverse of the warp output `SmoothDisplacementField` (setting the last option to 1). We kept getting the following error:

```
terminate called after throwing an instance of 'itk::ExceptionObject'
 what(): /opt/quarantine/minc-toolkit/1.9.17/src/build/ITKv4/Modules/Core/Common/src/itkMultiThreader.cxx:395:
itk::ERROR: MultiThreader(0x3015890): Exception occurred during SingleMethodExecute
Aborted
```

**To Reproduce**
Unable to upload an example NL warp field file, but we ran the following command on an input NL warp field (ex: `NL_warp_field.mnc`):
```
SmoothDisplacementField 3 NL_warp_field.mnc output_field_inverse.mnc 1x1x1 4 3 1
```

**System information**

NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.6 LTS"
VERSION_ID="14.04"

**ANTs version information**
 - ANTs Version: 2.2.0.dev89-g5decc
 - Compiled from source: Apr 11 2019 10:09:39

**Comment by ntustison** [comment]
I'm able to run it without issue on a randomly selected data set.  You might want to try updating your repo.  April 2019 is quite old relative to our update frequency.

**Comment by NadiaBlostein** [comment]
I am still getting errors with a newer version of ANTS:
```
ANTs Version: 2.3.1.dev160-g4658c
Compiled: Apr 10 2020 15:16:02
```
Whether I use a NL Warp Field in NIFTI (.nii.gz) or MNC (.mnc) format, I get the following error:
```
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /opt/quarantine/ANTs/20200410/src/ANTs-build/staging/include/ITK-5.1/itkBSplineScatteredDataPointSetToImageFilter.hxx:506:
itk::ERROR: BSplineScatteredDataPointSetToImageFilter(0x2810280): The reparameterized point component 1.00001 is outside the corresponding parametric domain of [0, 1).
Aborted
```

**Comment by ntustison** [comment]
Okay, that error is more helpful.  It indicates a data-specific issue so in order for me to help, I'd actually need access to the data.

**Comment by NadiaBlostein** [comment]
Sounds good, thank you! I am not able to upload MNC or NIFTI files onto the Github comment section so here is a link to the same NL warp field, in both MNC and NIFTI format: https://drive.google.com/drive/folders/1Mz4vZNrOOUIfq_h6zmHYUG9b_Cp0lglx?usp=sharing

**Comment by ntustison** [comment]
Thanks.

The *code* problem is that one of the voxelwise displacement vectors is mapping to the boundary of the image.  It is being included in the inverse field calculation but floating point precision is causing it to map outside that domain resulting in the thrown exception.  

More conceptually, though, you have significant nonzero displacement on the boundaries of the field, as your data isn't centered in the domain of interest, so the inverse is ill-defined given the specified domain.  

Instead of trying to address the code problem, you would be best served by trying to address the problem of centering your data in the domain.
