### ISSUE TITLE
Improve result of using ANTs to map/register high resolution 3d brain photos stack to MRI

### ISSUE THREAD

**Issue by LGUMI** [ANTsX/ANTs#1203]
Hello,

I am doing research in neurology and need to register/map some high resolution brain images (partial hemisphere, postmodern tissue slices stacks, I reference it as "blockface") to the patient's MRI scan. My pipeline is the following:

First I use the transformation tool in Freeview (part of fsl suite), to get a rough alignment/scale of the blockface to the MRI, I only use rotations on the MRI, and I used rotation, translation, and scaling on the tissue slices stacks. I then saved the transformed MRI and blockface (I saved the resampled MRI, I did not resample the blockface, only updated its header, since I did not downsample the blockface and resample with such high resolution will generate a very large file)

Second, I skull-striped the resampled MRI with FSL's recon-all function, and using it as the fixed image, I also did a histogrammatch to match the voxel intensity of the updated-header-blockface to the respected fixed image (full or skull-stripped MRI) prior the antRegistration. Lastly, I use antsRegistration to register the blockface with updated header to the skull-striped, resampled MRI.

I tried a couple pipeline of the antsRegistration but the result is still not optimal, I can provide results of all my attempts in hope of some advice from your experience to improve the result, please let me know your email address, I can share the code and result files (in nifti) via google drive.

Please ask if anything above is unclear, thank you very much!
Jonathan

**Comment by ntustison** [comment]
Why don't you illustrate the results and the problems you're having with a slide-type graphic showing the different steps of the pipeline?  It is still rather unclear to me.

**Comment by LGUMI** [comment]
> Why don't you illustrate the results and the problems you're having with a slide-type graphic showing the different steps of the pipeline? It is still rather unclear to me.

Hello Nick! Thanks for your quick replay, here are some slides I made, hope fully that clear out some of your questions, I am happy to provide raw data as well if you would like to take a look at them. Thanks again!

<img width="2346" alt="original_overlap" src="https://user-images.githubusercontent.com/30706555/123583160-01303400-d794-11eb-905b-a6f79e1b6084.png">
<img width="2349" alt="overlap_after_freeview_transform_volume" src="https://user-images.githubusercontent.com/30706555/123583167-042b2480-d794-11eb-99d6-814cc9fbaf5c.png">
<img width="2348" alt="ANTs_attempt_#1" src="https://user-images.githubusercontent.com/30706555/123583170-05f4e800-d794-11eb-983d-be4d95239d1c.png">
<img width="2346" alt="ANTs_attempt_#2" src="https://user-images.githubusercontent.com/30706555/123583175-07261500-d794-11eb-9557-99f95285b42e.png">
<img width="2344" alt="ANTs_attempt_#3" src="https://user-images.githubusercontent.com/30706555/123583180-08574200-d794-11eb-8fcc-e9eb18bfd05d.png">
<img width="2348" alt="ANTs_attempt_#4" src="https://user-images.githubusercontent.com/30706555/123583184-09886f00-d794-11eb-8c50-c264669e9b7e.png">
<img width="1832" alt="Header_of_full_MRI" src="https://user-images.githubusercontent.com/30706555/123583189-0ab99c00-d794-11eb-97d8-93175e6021b0.png">
<img width="1703" alt="Header_of_skull_stripped_MRI" src="https://user-images.githubusercontent.com/30706555/123583195-0beac900-d794-11eb-9cd1-9bc1b3e74214.png">
<img width="1565" alt="Header_of_blockface_after_freeview_transformation" src="https://user-images.githubusercontent.com/30706555/123583199-0d1bf600-d794-11eb-8574-f312e66bebc2.png">
<img width="1267" alt="Header_of_blockface_original" src="https://user-images.githubusercontent.com/30706555/123583201-0db48c80-d794-11eb-85e4-038635e02b79.png">

**Comment by LGUMI** [comment]
> Why don't you illustrate the results and the problems you're having with a slide-type graphic showing the different steps of the pipeline? It is still rather unclear to me.

For the last 4 slides, they are the headers of the following images:
Header_of_full_MRI
Header_of_skull_stripped_MRI
Header_of_blockface_after_freeview_transformation
Header_of_blockface_original

**Comment by ntustison** [comment]
To ensure there are no differences due to the way the header info is read, please use ITK-SNAP when looking at ANTs results.    [Here](https://github.com/ntustison/PartialSlabEpiT1ImageRegistration) is an example of T1-w slab image registration, both rigid and deformable.  Let's start with those parameters.

**Comment by LGUMI** [comment]
> To ensure there are no differences due to the way the header info is read, please use ITK-SNAP when looking at ANTs results. [Here](https://github.com/ntustison/PartialSlabEpiT1ImageRegistration) is an example of T1-w slab image registration, both rigid and deformable. Let's start with those parameters.

Hello Nick,

Thanks a lot for the code, I tried to view my previous result in ITK snap, the overlay looks the same as what I saw in Freeview

I first ran the Rigid code from your example, and the result is quite dramatic:
<img width="2329" alt="Screen Shot 2021-06-28 at 9 57 56 AM" src="https://user-images.githubusercontent.com/30706555/123676840-476bae80-d7f9-11eb-92a9-897664a69b97.png">

I did not run the SyN one, since I don't think SyN would works well without a proper alignment.

This is the result of my old Rigid 
<img width="2329" alt="Screen Shot 2021-06-28 at 9 55 54 AM" src="https://user-images.githubusercontent.com/30706555/123677074-88fc5980-d7f9-11eb-891c-09f8d0a12974.png">
code, more or less at the same location of my moving image, not much changed (which does not necessarily means good result either)

Thank you!
Jonathan

**Comment by ntustison** [comment]
I'll take a look at the data if you upload it but you might not have enough information to get a good pairwise information and so might have to use manual landmarking to get the alignment you want.

**Comment by LGUMI** [comment]
> I'll take a look at the data if you upload it but you might not have enough information to get a good pairwise information and so might have to use manual landmarking to get the alignment you want.

Hello Nick,

Thanks a lot for the reply, I just sent you the data I used for ANTs registration.
I agree with you on the potential need of manual landmarking, I used mipav by nih for 2d manual landmarking, never had experience with 3d land marking though, is there a software/tutorial that you would recommend me to try with and paired well with ANTs?

Thanks again!
Jonathan

**Comment by LGUMI** [comment]
> I'll take a look at the data if you upload it but you might not have enough information to get a good pairwise information and so might have to use manual landmarking to get the alignment you want.

Oh I sent the google drive invitation to your gmail: ntustison@gmail.com

**Comment by ntustison** [comment]
Yeah, looking at the data, I think you're going to need to landmark your data.  For something like this, we would typically use ITK-SNAP.  Simply paint 3-D blobs of the same color in each image to designate corresponding landmarks.  You can then use ``antsLandmarkBasedTransformInitializer`` to get a corresponding linear or B-spline transform.

**Comment by LGUMI** [comment]
> Yeah, looking at the data, I think you're going to need to landmark your data. For something like this, we would typically use ITK-SNAP. Simply paint 3-D blobs of the same color in each image to designate corresponding landmarks. You can then use `antsLandmarkBasedTransformInitializer` to get a corresponding linear or B-spline transform.

Thank you Nick, I will give that a shoot!

**Comment by LGUMI** [comment]
> Yeah, looking at the data, I think you're going to need to landmark your data. For something like this, we would typically use ITK-SNAP. Simply paint 3-D blobs of the same color in each image to designate corresponding landmarks. You can then use `antsLandmarkBasedTransformInitializer` to get a corresponding linear or B-spline transform.

Hello Nick,

So I used ITK-SNAP to generate the label/segmentation for both the MRI and blockface, something like this:
<img width="1570" alt="Screen Shot 2021-06-28 at 1 57 14 PM" src="https://user-images.githubusercontent.com/30706555/123703081-c8866e00-d818-11eb-827a-5f2b55ded7ac.png">

And save the following files:
<img width="524" alt="Screen Shot 2021-06-28 at 2 00 15 PM" src="https://user-images.githubusercontent.com/30706555/123703404-2dda5f00-d819-11eb-907e-51e8e0928c17.png">

Then for the antsLandmarkBasedTransformInitializer:

antsLandmarkBasedTransformInitializer dimension fixedImage movingImage transformType outputTransform [meshSize[0]xmeshSize[1]x...=1x1x1] [numberOfLevels=4] [order=3] [enforceStationaryBoundaries=1] [landmarkWeights]

I am not sure if the "fixingImage" and "movingImage" would be the original images or the segmentation nifti images I saved, and how would I input the label file (vtk, stl or byu) into this script (or the script does not need any of these file)?

Thanks again!
Jonathan

**Comment by ntustison** [comment]
This is not what I meant by "landmarked" data, which is *not* a segmentation.  What you need to do is identify corresponding points between the two images.  Mark these points with a paint blob (the program calculates the centroid of each label).  Each point pair should be a different label (color).  Then you can use ``antsLandmark...``.

**Comment by LGUMI** [comment]
Hello Nick,

Thanks for clarifying that, I suppose this is what you mean by "making point with paint blob"

<img width="2347" alt="Screen Shot 2021-06-28 at 4 27 15 PM" src="https://user-images.githubusercontent.com/30706555/123715713-ba8f1800-d82d-11eb-9fc5-9ba0caf644ea.png">

and after I made several pairs of them across the two volume, do I save the segmentation image like that

<img width="385" alt="Screen Shot 2021-06-28 at 4 37 15 PM" src="https://user-images.githubusercontent.com/30706555/123716398-55d4bd00-d82f-11eb-8bab-4dbbea7cb6d6.png">

and use them in "antsLandmarkBasedTransformInitializer" as fixed and moving images? I think I am a bit confused of what to save as output from ITK-SNAP for putting into the antsLandmarkBasedTransformInitializer, and does the antsLandmarkBasedTransformInitializer output an transform nifti images or some sort of the transformation matrix?

Thank again for your explanation
Jonathan

**Comment by ntustison** [comment]
Yes, the fixed and moving images should be the "segmentation images" saved with ITK-SNAP.  The output is either an ITK transform file for the linear transform or a displacement field image in the case of a b-spline transform.

**Comment by LGUMI** [comment]
> Yes, the fixed and moving images should be the "segmentation images" saved with ITK-SNAP. The output is either an ITK transform file for the linear transform or a displacement field image in the case of a b-spline transform.

Hello Nick,

Thanks! I tried the landmark registration with Mipav, works well! 
Additional question I have is that I would like to have a better understand of the parameter that antRegistration use, are there any readings/text that you recommend for me to read?

Thank you again!
Jonathan

**Comment by ntustison** [comment]
[This](https://www.frontiersin.org/articles/10.3389/fninf.2014.00044/full) paper is probably the closest journal article to what you're requesting.  Otherwise, you should consult the help menu in ``antsRegistration`` as well as the class documentation in ITK.
