### ISSUE TITLE
Formatting of GenericAffine.mat file

### ISSUE THREAD

**Issue by daphneneuro17** [ANTsX/ANTs#1207]
**Describe the problem**
Greetings, hopefully this is just a small confusion of mine. I created a rigid transform using the following antsRegistration call:

`antsRegistration --collapse-output-transforms 1 --dimensionality 3 --initial-moving-transform [ /data/mni_1mm_t1w_lps_brain.nii.gz, /scratch/highres001_N4Corrected0.nii.gz, 1 ] --initialize-transforms-per-stage 0 --interpolation LanczosWindowedSinc --output [ transform, transform_Warped.nii.gz ] --transform Rigid[ 0.2 ] --metric Mattes[ /data/mni_1mm_t1w_lps_brain.nii.gz, /scratch/highres001_N4Corrected0.nii.gz, 1, 32, Random, 0.25 ] --convergence [ 10000x1000x10000x10000, 1e-06, 10 ] --smoothing-sigmas 7.0x3.0x1.0x0.0vox --shrink-factors 8x4x2x1 --use-histogram-matching 1 --winsorize-image-intensities [ 0.025, 0.975 ]  --write-composite-transform 0`

It output transform0GenericAffine.mat, which I am trying to load into [mrtrix's transformconvert](https://mrtrix.readthedocs.io/en/latest/reference/commands/transformconvert.html), which claims to "convert a plain text transformation matrix file produced by ITK’s affine registration (e.g. ANTs, Slicer) into a format usable by MRtrix3". I get an error on this command, however:

`transformconvert: [ERROR] invalid first line for key/value file "/data/transform0GenericAffine.mat" (expected "#Insight Transform File V1.0")`

I see for example [here](https://itk.org/pipermail/insight-developers/2013-May/022764.html) that at least some ITK transform files have this line/format, which it looks like mrtrix is expecting. 

Could someone kindly explain what might be going wrong here? Am I wrong for using the GenericAffine.mat file as the "plain text transformation matrix file produced by ITK's affine registration (e.g. ANTs)"? Or is this a problem on mrtrix's end that the format of matrix they're looking for is outdated?

**System information (please complete the following information)**
RHEL 7

**ANTs version information**
 - ANTs code version: 2.3.5.dev246-ga7eca
 - ANTs installation type: Compiled from instructions on this Github

**Additional information**
Apologies if this question is better suited for mrtrix folks.

Thank you :)

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/issues/1099

**Comment by cookpa** [comment]
The `.mat` file is a binary ITK transform. `ConvertTransformFile 3 Affine.mat Affine.txt` will change to the text format.

**Comment by daphneneuro17** [comment]
Excellent, thank you! Sorry if this was a dumb question.
