### ISSUE TITLE
Question about antsRegistrationSyN.sh 

### ISSUE THREAD

**Issue by Fittrue** [ANTsX/ANTs#1208]
Hello. I am trying image registration using antsRegistrationSyN.sh. I made my first try with affine registration using

`antsRegistrationSyN.sh -d 2 -f flair.nii.gz -m t2.nii.gz -o output -t a`

and obtained the files "OutputWarped.nii.gz" and "output0GenericAffine.mat"

It got good results, I want to register another image ("t1.nii.gz") to "flair.nii.gz" using "output0GenericAffine.mat".

For some reason, t1 and t2 are collected at the same time, they are aligned. 

`antsRegistrationSyN.sh -d 2 -f flair.nii.gz -m t1.nii.gz -o output1 -t a`

I use the same code to register "t1.nii.gz",  it didn't get good results. I hope it could only apply the matrix to this image instead of continuing to generate it as an initial standard

How can I do that?

Thanks a lot.

**Comment by ntustison** [comment]
``antsRegistrationSyN.sh`` is used to compute the correspondence between image pairs but if that correspondence has already been calculated and you want to use it to warp another image, then you want to use ``antsApplyTransforms``.  So, in your case you would do 

``$ antsApplyTransforms -d 3 -i t1.nii.gz -r flair.nii.gz -o t1WarpedToFlair.nii.gz -n Linear -t output0GenericAffine.mat``

**Comment by Fittrue** [comment]
Thaks bro @ntustison ,

I am sorry for not replying to you in time. Your suggestion solved my problem. In addition, where should I search these commonly used tools?

Thanks again for your suggestions.

**Comment by ntustison** [comment]
We have a number of links in the README.md file of this GitHub repo.  You can also invoke the help menu for the programs from the command line, typically using the -h or --help option.

**Comment by cookpa** [comment]
There's also the Wiki:

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

**Comment by Fittrue** [comment]
Thank you so much for your suggestions.@ntustison @cookpa
