### ISSUE TITLE
Warped output merge and convert to tiff?

### ISSUE THREAD

**Issue by ckosse** [ANTsX/ANTs#1211]
Hi community,

I am still very new to ANTs and already learned so much from other posts! I have a timeseries of the same 2D frame from an imaging experiment and would like to remove the motion artefacts. It is basically a 3D tiff that I slice into single 2D frames and align to reference frame. Very similar to this post: https://github.com/ANTsX/ANTs/issues/1041 and it works great! 

My problem is now that my warped output files consist of thousands of single zipped nii files. Is there a way to merge them back into one 3D file, ideally a tiff? 

Thank you! 
Christin

**Comment by cookpa** [comment]
Try `TileImages`. Be sure to verify that the output is correctly oriented (especially no left-right flips)
