### ISSUE TITLE
High-resolution 3D image registration error in Ants

### ISSUE THREAD

**Issue by wangniannw** [ANTsX/ANTs#1213]
Dear All,
I'm trying to register a 3D images at **(18um*18um*18um)** spatial resolution to a template 3D image at (43um*43um*43um) resolution. First, I save the 3D images to .nii format in matlab using save_nii. Then I run the command below but got the error message:
/Users/XXX/install/bin/antsRegistration -d 3 -o /Users/XXX/Documents/ANTs_test/affine_mag  -m MI[/Users/XXX/Documents/ANTs_test/template.nii, /Users/XXX/Documents/ANTs_test/mag_wop1.nii, 1,32,Regular,0.75] -t Affine[0.05]  -c [500x500x500x500,1e-6,15] -s 0x0x0x0 -f 1x1x1x1 -u
Exception caught during reference file reading 

itk::ExceptionObject (0x7f97f79aa330)
Location: "unknown" 
File: /Users/XXX/build/ITKv5/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Line: 1972
Description: itk::ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

 file /Users/XXX/Documents/ANTs_test/mag_wop1.nii
 /Users/XXX/install/bin/antsRegistration -d 3 -o /Users/XXX/Documents/ANTs_test/affine_mag  -m MI[/Users/XXX/Documents/ANTs_test/template.nii, /Users/XXX/Documents/ANTs_test/mag_wop1.nii, 1,32,Regular,0.75] -t Affine[0.05]  -c [500x500x500x500,1e-6,15] -s 0x0x0x0 -f 1x1x1x1 -u: Segmentation fault

However, if I save the 3D images to .nii format in matlab with the voxel size of **[25um*25um*25um]**, I can run the registration with no error pops up. I use Mac and I never try to do the registration at such high resolution. Any suggestions are greatly appreciated! 

Thanks,
Nian

**Comment by cookpa** [comment]
What does `PrintHeader` say about your two images?

**Comment by wangniannw** [comment]
For the template image:
 Spacing [0.043, 0.043, 0.043]
 Origin [-0.043, -0.043, 0.043]
 Direction 
-1 0 0
0 -1 0
0 0 1

 Size : 284 460  214

  Image Dimensions   : [284, 460, 214]
  Bounding Box       : {[-0.043 -0.043 0.043], [12.169 19.737 9.245]}
  Voxel Spacing      : [0.043, 0.043, 0.043]
  Intensity Range    : [0, 0.897694]
  Mean Intensity     : 0.0502424
  Direction Cos Mtx. : 
-1 0 0
0 -1 0
0 0 1

  Voxel->RAS x-form  : 
  Image Metadata: 
    ITK_original_direction of unsupported type N3itk6MatrixIdLj3ELj3EEE
    ITK_original_spacing of unsupported type NSt3__16vectorIdNS_9allocatorIdEEEE
    aux_file = none
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    dim[0] = 3
    dim[1] = 284
    dim[2] = 460
    dim[3] = 214
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 0.043
    pixdim[2] = 0.043
    pixdim[3] = 0.043
    pixdim[4] = 1
    pixdim[5] = 1
    pixdim[6] = 1
    pixdim[7] = 1
    qform_code = 0
    qform_code_name = NIFTI_XFORM_UNKNOWN
    qoffset_x = 0
    qoffset_y = 0
    qoffset_z = 0
    quatern_b = 0
    quatern_c = 0
    quatern_d = 0
    scl_inter = 0
    scl_slope = 0
    sform_code = 1
    sform_code_name = NIFTI_XFORM_SCANNER_ANAT
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = 0.043 0 0 0.043
    srow_y = 0 0.043 0 0.043
    srow_z = 0 0 0.043 0.043
    toffset = 0
    vox_offset = 352
    xyzt_units = 0

**Comment by wangniannw** [comment]
For the 18um isotropic high resolution image, PrintHeader shows cannot read for some reason.  The matrix size is 640*900*420. This is the command I save the image to nii in matlab:
save_nii(make_nii(single(mag_wop1),[0.018 0.018 0.018],[0 0 0],16),'mag_wop1.nii');

Here is the image info I got from Fiji ImageJ:

(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_202 [64-bit]; Mac OS X 10.15.7; 1017MB of 36212MB (2%)
 
Title: mag_wop1.nii
Width:  11.5200 pixels (640)
Height:  16.2000 pixels (900)
Depth:  7.5600 pixels (420)
Size:  923MB
Resolution:  55.5556 pixels per pixel
Voxel size: 0.0180x0.0180x0.0180 pixel^3
ID: -2
Bits per pixel: 32 (float)
Display range: 0 - 5582.7017
Frame: 1/420
Frame interval: 1 sec
No threshold
Magnification: 0.75
ScaleToFit: false
Calibration function: None
  Unit: "gray value"
Path: /Users/nianwang/Documents/ANTs_test/B10406/mag_wop1.nii
Screen location: 519,118 (1600x900)
SetMenuBarCount: 2 (0ms)
Coordinate origin:  0,0,0
No properties
No overlay
No selection

**Comment by cookpa** [comment]
`PrintHeader` tries to read the volume, and might run out of memory with such a large volume. I am wondering if there is some numerical issue in the test of the sform matrix. ITK tries to extract a rigid rotation from the sform, if that is failing somehow it will report the error you saw.

Can you dump the full nifti header somehow from Matlab? Alternatively, if you have R, you can try the RNifti package. I believe that reads headers only (ie, it just reads the first 352 bytes of the file).

**Comment by wangniannw** [comment]
Hi cookpa, 
Thanks for your quick reply! It may be related to the large matrix size. I'm wondering whether there is any limitation to the data size/resolution for ANTs registration?
BTW, My Mac has 128Gb RAM.

Here is what I got from matlab. Hope it helps:
  struct with fields:

       sizeof_hdr: 348
        data_type: ''
          db_name: ''
          extents: 0
    session_error: 0
          regular: 'r'
         dim_info: 0
         
  
    dim: [3 640 900 420 1 1 1 1]
         intent_p1: 0
         intent_p2: 0
         intent_p3: 0
       intent_code: 0
          datatype: 16
            bitpix: 32
       slice_start: 0
            pixdim: [0 0.0180 0.0180 0.0180 1 1 1 1]
        vox_offset: 352
         scl_slope: 0
         scl_inter: 0
         slice_end: 0
        slice_code: 0
        xyzt_units: 0
           cal_max: 0
           cal_min: 0
    slice_duration: 0
           toffset: 0
             glmax: 33683
             glmin: 0      
             

        descrip: ''
       aux_file: 'none'
     qform_code: 0
     sform_code: 1
      quatern_b: 0
      quatern_c: 0
      quatern_d: 0
      qoffset_x: 0
      qoffset_y: 0
      qoffset_z: 0
         srow_x: [0.0180 0 0 0.0180]
         srow_y: [0 0.0180 0 0.0180]
         srow_z: [0 0 0.0180 0.0180]
    intent_name: ''
          magic: 'n+1'
     originator: [256 0 0 0 0]

**Comment by wangniannw** [comment]
The registration worked pretty well the spatial resolution up to 25um x 25um x 25um (from 100um, 50um, to 25um). I only got the issue when I go to 18um*18um*18um images. The data size and matrix size become larger at this spatial resolution. These are MRI images.

**Comment by cookpa** [comment]
If `PrintHeader` is returning an error then it's likely `antsRegistration` would too. So maybe the orthonormal error is a result of failing to load the data properly.

To reduce memory usage, you could try adding `--float` to your `antsRegistration` call.

**Comment by wangniannw** [comment]
I just tried, but still got the same error.

Thanks,
Nian

Description: itk::ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

**Comment by cookpa** [comment]
OK. 

I think the clue is in `PrintHeader` not working on your full-resolution image. 

To check it wasn't the size, I made synthetic images, which read successfully:

`CreateImage 3 moving18.nii.gz 0x0x0mm 0.018x0.018x0.018mm 600x940x420 0 0
CreateImage 3 fixed43.nii.gz 0x0x0mm 0.043x0.043x0.043mm 284x460x214 0 0`

**Comment by cookpa** [comment]
I think I've got it. If I remove the qform (using RNifti), it doesn't work:

```
PrintHeader moving18NoQ.nii.gz   
 cant read moving18NoQ.nii.gz
```

**Comment by cookpa** [comment]
The error is in ITK, I have not found an obvious cause yet.

One workaround would be to write a NIFTI image that has a valid qform. So something like:

```
    qform_code = 1
    qoffset_x = 0.0180
    qoffset_y = 0.0180
    qoffset_z = 0.0180
    quatern_b = 0
    quatern_c = 0
    quatern_d = 0
```

Another trick would be to upscale the voxel resolutions of the fixed and moving images by the same amount.

**Comment by cookpa** [comment]
I think for your data you'd just need to set `qform_code = 1` and then `qoffset` to wherever you want the origin to be. Maybe your Matlab code can do that?

You might also be able to use [c3d](http://www.itksnap.org/pmwiki/pmwiki.php?n=Downloads.C3D) to read and write your nii file. I think the currently available binaries are built with ITK v4, which uses the qform. Current ITK tries to use the sform where possible, and something is going wrong in that decision tree.

As always, whenever manipulating headers be very careful of accidentally flipping the images; I recommend ITK-SNAP to check that the anatomical orientation is and remains correct.

**Comment by wangniannw** [comment]
Thanks for the suggestions. I set qform_code =1 and it works now!
I'll let you know if I have further questions. 

Thanks,
Nian

**Comment by cookpa** [comment]
@ntustison possibly relevant to the mouse atlas work. Very small voxels can cause ITK to throw an exception when trying to use the sform. It will fall back on the qform if the qform exists.

**Comment by ntustison** [comment]
Thanks @cookpa .  Good to know.

**Comment by cookpa** [comment]
This has been fixed in ITK, so this issue can be resolved in a future release. 

https://github.com/InsightSoftwareConsortium/ITK/pull/2701

Not worth bumping ITK now, since we have ITK at a stable version and should have at least one ANTs release to use it.

Meanwhile, if anyone else finds this issue, the workaround is to ensure NIFTI images with small voxels have a valid qform.
