### ISSUE TITLE
Templates not sized according to the largest input image

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1216]
As part of some changes described here

https://github.com/ANTsX/ANTs/pull/1149

I changed the population average initial template to be median instead of mean

https://github.com/ANTsX/ANTs/blob/61e9501f639663cdd3ae08b8840a85c7b805a8d3/Scripts/antsMultivariateTemplateConstruction2.sh#L1012

But this has the undesired effect of not making the initial template the size of the largest input image.

Possible solutions:

- Compute median in AverageImages. This would be ideal from a scripting perspective as they would no longer need ImageSetStatistics at all

- Resize output in ImageSetStatistics, matching behavior of AverageImages

- Find some better way to initialize templates

- Revert to using mean. I'd like to avoid this because the initial template can be pretty bad if the input images are not roughly aligned.

**Comment by gdevenyi** [comment]
I found `ImageSetStatistics` to be incredibly slow in implementation when I use it, I would prefer adding the feature to AverageImages,

Having said that, I have a "dumb" COM initialization I use to setup modelbuilds which don't have a reference image to start with; https://github.com/gdevenyi/yucatan_minipig_template/blob/master/make-dumb-average.sh

**Comment by cookpa** [comment]
Average, align COM to average, and average again? I could implement that, what do you think @ntustison ?

**Comment by ntustison** [comment]
So would this be in addition to the rigid initialization option for template building?

**Comment by gdevenyi** [comment]
> So would this be in addition to the rigid initialization option for template building?

Yes, this is my initialization for a starting average when there's no target available for rigid. Generally I would run a rigid init against this average afterwards.

**Comment by cookpa** [comment]
Right, it would come first. Currently we just call AverageImages and rely on there being enough images in roughly the same place to make it work. But sometimes that isn't the case and the contrast can be wiped out, or you get outlier images that just align to the outline of themselves in the initial average, and don't converge.

Median reduces the outlier problem, but doesn't fix the bounding box. It's also slow for large input data sets.

An initial COM alignment wouldn't help with rotations, but it would reduce blurring from translation, which is often substantial for no good reason (eg, origins set inconsistently).

**Comment by ntustison** [comment]
Sure---it can't hurt.

**Comment by cookpa** [comment]
Also @gdevenyi I have found the Laplacian sharpening that is built into `AverageImages 3 ${output} 1 ...` can exacerbate false edges at the initialization stage. You can turn it off now with `AverageImages 3 ${output} 2 ...`.

**Comment by gdevenyi** [comment]
> Also @gdevenyi I have found the Laplacian sharpening that is built into `AverageImages 3 ${output} 1 ...` can exacerbate false edges at the initialization stage. You can turn it off now with `AverageImages 3 ${output} 2 ...`.

Yup, thanks. This script was written before this feature was added :+1:

**Comment by gdevenyi** [comment]
Another problem with sizing I just realized is how AverageImages computes "largest". It assumes all slices are the same size, since it only compares the number of slices:

https://github.com/ANTsX/ANTs/blob/de5c8e75e9ea34d4425a0d86b287a35010f90bbe/Examples/AverageImages.cxx#L58-L81

I think this might need to be adjusted to consider averaging images with non-equal slice sizes.

**Comment by gdevenyi** [comment]
Another thought however, shouldn't AverageImages instead be constructing an image that is the size of the union of the bounding boxes of all the input images?

**Comment by cookpa** [comment]
Maybe, but you could inadvertently create some very large images that way.

**Comment by gdevenyi** [comment]
I've been playing with this, right now I've found a combination of PadImage, ThresholdImage, and ExtractRegionFromImageByMask along with the 2 rounds of COM allows me to converge on a sensible FOV during initial alignment.

**Comment by cookpa** [comment]
Perhaps an antsTemplateInitializer program / script would be useful.

My worry is, that if the input data is so variable, then building a nice initial average might not be sufficient because you still have to go back to the original images and make them all register to the template.

At some level, we have to expect that users curate the template input population a little bit.

**Comment by gdevenyi** [comment]
I ended up implementing the template FOV here: https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction/pull/20
