### ISSUE TITLE
Ambiguity about  transformation order in "Advanced Normalization Tools (ANTS)  Release 2.x" 

### ISSUE THREAD

**Issue by zoelir729** [ANTsX/ANTs#1217]
**pdf: Advanced Normalization Tools (ANTS)  Release 2.x**
Page 15. The underlined code. 

**If the ABWrap and ABAffine indicate A to B, that is A2BWrap, A2BAffine, B2CWrap and B2CAffine.**
The the underlined code confused me.

I think (from information I obtained so far): 

To wrap **C to A** (means transform C into the space of A to get **CtoAdeformed.nii**): 
**antsApplyTransforms -t [BCAffine,1] -t BCInverseWrap -t [ABAffine,1] -t ABInverseWrape**

To wrap **A to C** (means transform A into the space of C to get **AtoCdeformed.nii**): 
**antsApplyTransforms -t BCWrap -t BCAffine -t ABWrap -t ABAffine**

If the order is right.
Can you provide a more detailed explanation ？

![image](https://user-images.githubusercontent.com/36666968/127748750-d134412d-4f8f-4da5-a36f-55ee026ad699.png)

Thanks!
-zoe

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians
