### ISSUE TITLE
TimeVaryingVelocityField vs Geodesic SyN

### ISSUE THREAD

**Issue by Firecrackle** [ANTsX/ANTs#1221]
Hello ANTs team.

I've been trying to track down the name and implementation of ANTs' time varying velocity field (TVVF) registration. 
Page 10 of the ANTs documentation (I'm using this version: https://issuu.com/brianavants/docs/ants2) and table 1 of an ANTs paper (this one: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3065962/) make it seem like TVVF is also referred to as "Geodesic SyN". A paper for ITK also references a TVVF algorithm (in section 2.4 of this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4009425/) as an alternative to LDDMM. I assume this is the same version as the one used in ANTs.

Is TVVF the same as Geodesic SyN? 

Any help would be appreciated!

**Comment by ntustison** [comment]
Geodesic SyN is not available in ``antsRegistration``.  However, it's asymmetric analog, TimeVaryingVelocityField, as well as a B-spline variant, is available.  It might be available in ``ANTS``---@stnava?

**Comment by Firecrackle** [comment]
Thanks for the clarification! It looks like geodesic is a flag in [ANTS](http://manpages.ubuntu.com/manpages/bionic/man1/ANTS.1.html) that can be used with SyN as the transformation model. I'll check that out along with TimeVaryingVelocityField.
