### ISSUE TITLE
Collapse warps after running multiple serial antsRegistration calls

### ISSUE THREAD

**Issue by chrisadamsonmcri** [ANTsX/ANTs#1223]
I'm registering subject T1 images to a template using multiple antsRegistration calls with refinements at each call.

At each stage I initialise the moving transform with the sequence of previously generated warps. I warp images in the template space to native space using the reverse sequence of InverseWarp images. That all works fine.

What I was wondering is if it would be possible to collapse the collections of XWarp.nii.gz and XInverseWarp.nii.gz images into a single forward (native->template) and backward warp (template->native) using a standalone tool. I tried ComposeTransformUtil as follows:

CompositeTransformUtil --assemble forward1Warp.nii.gz orig1Warp.nii.gz orig2Warp.nii.gz...

But it kept segfaulting.

I was originally using the default --collapse-output-transforms 1 but at each stage it was giving me two warps: One forward *reg1Warp.nii.gz, second forward *reg2Warp.nii.gz and second inverse *reg2InverseWarp.nii.gz. I couldnt get antsApplyTransforms to work using any sequence of those warps (2 -> 1) (1 -> 2) and I couldn't work out why it was giving two warp outputs.

Thanks in advance,

Chris.

**Comment by gdevenyi** [comment]
```
$ antsApplyTransforms --help
<CLIP>
     -o, --output warpedOutputFileName
                  [warpedOutputFileName or compositeDisplacementField,<printOutCompositeWarpFile=0>]
                  Linear[genericAffineTransformFile,<calculateInverse=0>]
          One can either output the warped image or, if the boolean is set, one can print 
          out the displacement field based on the composite transform and the reference 
          image. A third option is to compose all affine transforms and (if boolean is 
          set) calculate its inverse which is then written to an ITK file. 

```

**Comment by cookpa** [comment]
I'm not sure why you're getting multiple warps, but it may be because you input an initial warp. I don't use that feature much.

Can you show an example command that produces two warp outputs?

**Comment by chrisadamsonmcri** [comment]
Oh thank you I'll try that.

As an example 
                antsRegistration -v -d 3 -u 1 -w [ 0.025,0.975 ] --verbose 1 --float 1 --collapse-output-transforms 1 --write-interval-volumes 10 \
                        --initial-moving-transform $P/${OUTPUTPREFIX}_skullstrip_reg2Warp.nii.gz \
                        --initial-moving-transform $P/${OUTPUTPREFIX}_skullstrip_reg1Warp.nii.gz \
                        --initial-moving-transform $P/${OUTPUTPREFIX}_skullstrip_affine0GenericAffine.mat \
                        --transform SyN[0.1,3,0.25] \
                        --metric MI[ $T1TEMPLATE,$P/${OUTPUTPREFIX}_t1w_restore.nii.gz,0.1,32,Regular,0.8 ] \
                        --metric Demons[ $TEMPLATEDIR/Finaltemplate5Masked.nii.gz,$P/${OUTPUTPREFIX}_skull_orig.nii.gz,0.45 ] \
                        --convergence [ 100x0,1e-6,100 ] --shrink-factors 2x1 --smoothing-sigmas 1x0vox --masks [NULL,$P/${OUTPUTPREFIX}_majority_dkt_affine_reg_postmask.nii.gz] \
                        --output [$P/${OUTPUTPREFIX}_skullmask_reg,$P/${OUTPUTPREFIX}_skullmask_regWarped.nii.gz,$P/${OUTPUTPREFIX}_skullmask_regInverseWarped.nii.gz]

This would produce the two warp outputs: $P/${OUTPUTPREFIX}_skullmask_reg1Warp.nii.gz $P/${OUTPUTPREFIX}_skullmask_reg2Warp.nii.gz, $P/${OUTPUTPREFIX}_skullmask_reg2InverseWarp.nii.gz  . But its fine it looks like I can use the antsApplyTransforms solution.

**Comment by chrisadamsonmcri** [comment]
It worked nicely thank you.

> ```
> $ antsApplyTransforms --help
> <CLIP>
>      -o, --output warpedOutputFileName
>                   [warpedOutputFileName or compositeDisplacementField,<printOutCompositeWarpFile=0>]
>                   Linear[genericAffineTransformFile,<calculateInverse=0>]
>           One can either output the warped image or, if the boolean is set, one can print 
>           out the displacement field based on the composite transform and the reference 
>           image. A third option is to compose all affine transforms and (if boolean is 
>           set) calculate its inverse which is then written to an ITK file. 
> ```
