### ISSUE TITLE
Error: transform file does not exist for unbiased pairwise registration

### ISSUE THREAD

**Issue by adrimoraless** [ANTsX/ANTs#1224]
**Describe the problem**
Hi! I'm running the script unbiased_pairwise_registration with the following command:
`unbiased_pairwise_registration.sh -d 3 -f $Image1 -m $Image2 -o $OUT`

It seems to run well and creates expected outputs until lines 116-122 in the script, where I get the following error:
`now do deformable expecting /mnt/c/Users/Adria/HalfwayReg/240379_outputs_2d/PLS_initB and /mnt/c/Users/Adria/HalfwayReg/240379_outputs_2d/PLS_initA to exist
/home/adri/install/bin/unbiased_pairwise_registration.sh: line 122:   161 Killed                  $reg -d $dim --initial-fixed-transform $midaaff --initial-moving-transform $midbaff -m mattes[ $A, $B , 1 , 32 , none , 0.25 ] -t syn[ 0.25, 3, 0.0 ] -c [ ${synits},1.e-8,10 ] -s 2x1x0 -f 4x2x1 -o [ ${nm},${nm}_diff_symm.nii.gz] 
Transform file does not exist: 
/mnt/c/Users/Adria/HalfwayReg/240379_outputs_2d/PLS_B_to_A1Warp.nii.gz
Transform file does not exist: 
/mnt/c/Users/Adria/HalfwayReg/240379_outputs_2d/PLS_B_to_A1InverseWarp.nii.gz`

Here is the full output printed to the terminal:
[unbiased_pairwise_registration_fulloutput.txt](https://github.com/ANTsX/ANTs/files/6978000/unbiased_pairwise_registration_fulloutput.txt)

**System information**
I'm using Ubuntu-20.04 on Windows 10 computer

**ANTs version information**
 - ANTs code version: ANTs Version: 2.3.5.dev254-gde5c8
 - ANTs installation type: Compiled from source

Thanks in advance for any help!

**Comment by ntustison** [comment]
I don't have a problem running it.  Can you post the input data?
