### ISSUE TITLE
T1 Population Template Time-out

### ISSUE THREAD

**Issue by ldipnall** [ANTsX/ANTs#1228]
**Describe the problem**

Hi,
I ran the command "antsMultivariateTemplateConstruction2.sh -c 0 -d 3 -o output *.nii.gz" to build a population T1 template on 58 IDs that are representative of a larger sample. This sample is also the same that was used to create a diffusion imaging template so I would prefer not to reduce the sample size. 
The job ran for 160 hours and timed-out as it was being run on an HPC platform and that was the time limit I had set. My question is, can I re-commence the command from where it ended at the time-out? And if so, how?
I have attached the output file that outlines what steps were run until time-out. Thank you.

**To Reproduce**

- antsMultivariateTemplateConstruction2.sh -c 0 -d 3 -o output *.nii.gz
- [output_poptemp3_Template.txt](https://github.com/ANTsX/ANTs/files/7010791/output_poptemp3_Template.txt)

**System information (please complete the following information)**

- Max of 8 tasks per allocated node
- CPU Memory: 64G of memory
 - Type of system: HPC

**ANTs version information**
 - ANTs code version: ANTs Version: 2.3.4.dev170-g11953
 - ANTs installation type: module loaded to environment

**Additional information**

**Comment by gdevenyi** [comment]
the ANTs template builder does not have any resume capability. The best you can do is use the last-round average as the `-z` value to start again.

You may be interested in https://github.com/cobralab/optimized_antsMultivariateTemplateConstruction/ which is a re-implementation which has updated cluster supprt and resume capability.

**Comment by cookpa** [comment]
It looks like it completed two iterations of the 4 (I searched the output for "shapeupdatetotemplate---voxel"). You can run two more iterations by passing the template with `-z`. 

You can also save some time by running N4 before passing your images to the script.

**Comment by ldipnall** [comment]
Thanks for the replies. I'll take all this on board. 
Something else I wanted to ask was whether the process can be sped up in any way? For example, by increasing the number of cores and memory available, or will this not help as the jobs operation appears more in/out bound?

**Comment by gdevenyi** [comment]
Each individual antsRegistration call is multi threaded and independent per round of model building. Changing '-c' to a value for cluster submission will submit every registration as a seperate job. Otherwise, my pipeline uses qbatch to do job submission which you can configure to talk to your particular cluster.

**Comment by cookpa** [comment]
If you're running in series, 8 cores is the most you can effectively use. In an HPC environment, it's usually necessary to set the environment variable ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS even with `-c 0`. So if you don't have ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=8, you should set that. Buried in the standard output will be records of how long each registration takes (search for "Total elapsed time").

You can try parallel execution with `-c 2`. Then you would set "-c 2 -j M" and ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=N as needed. So if you have allocated 8 cores, you could try N=4 and `-c 2 -j 2`, which might be slightly faster. After 8 cores per job, you won't see much benefit.
