### ISSUE TITLE
Can you combine the CC and MI metric for a single registration

### ISSUE THREAD

**Issue by Tss20** [ANTsX/ANTs#1229]
I want to write an SyN registration call that combines a cross correlation metric and a mutual information metric. I noticed in the antsRegistration wiki that there is an example of code where two MI metrics are used in a single registration with different weights (https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-call#inline-code-explained). Could you combine a CC and MI metric similarly and if so, how would you specify the weight of the CC metric?

**Comment by ntustison** [comment]
That's an empirical question that you'd have to decide based on your data.  Just know that you can weight each metric however you want but they get normalized such that they sum to 1.

**Comment by Tss20** [comment]
I think you have misinterpreted my question. My question is regarding the code itself. I am asking how to specify weights in the line for the cross correlation metric.

**Comment by ntustison** [comment]
```
antsRegistration --help 
```

```
# just picked two values for demonstration purposes
ccWeight=1.0 
miWeight=1.5

antsRegistration \
    ...
    --metric MI[$t1brain,$template,${miWeight},32,Regular,0.25] \
    --metric CC[$t1brain,$template,${ccWeight},4] \
    ...
```

**Comment by cookpa** [comment]
I updated the wiki page to try to make this clearer

https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-call

(I made quite a few other changes to that page, hopefully improvements, while I was there)

**Comment by ntustison** [comment]
Thanks for this, @cookpa .

**Comment by Harry-Zzz** [comment]
Thanks for cookpa's explanation on the wiki page, but I have a question. As shown in the screenshot, what I see from the example code is that the weight of CC is 0.6 and the weight of MI is 0.4. Why does the last sentence in the screenshot say that the weight of CC on T1 is equal to that of MI on T2? How should the weight be defined?
![image](https://user-images.githubusercontent.com/38092166/132471466-4d710930-e8fa-4e36-9c02-ccc43056b1c5.png)
