### ISSUE TITLE
Version information in ANTs build

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1231]
**Is your feature request related to a problem?**

Version information in ANTs builds is only available when building from a cloned git repo. This is a problem for people trying to build from a tarball.

Also, the version information is not checked for local modifications. This could be fixed by the use of the `--dirty` option to `git describe`. 

**Proposed new features**

A system that provides accurate version information however the source was obtained.

I don't think we can help people who hit the download snapshot version to get the current HEAD revision. But we can attach our own tarballs to releases, so we can include version information there.

* If a git repo, output version information from git describe and use `--dirty` to catch local modifications
* If building from a release tarball, have version information embedded in the tarball somehow (maybe CircleCI can do this?) 
* Some kind of checksum built into release tarballs to catch local modifications? Too much?

If a tagged release is built, the version information should say "vX.Y.Z" whether built from Git or a tarball, and this information should be propagated to the libraries (no more 0.0.0).

**Alternatives you've considered**

* Adapting existing code to allow version information to be set manually at build time, such that the user has full control over the version info. But this could lead to confusion, as there's no guarantee the user-supplied info is correct.

**Additional context**

The versioning behavior affects all of ANTsX, and builds in other packages.

Related:

https://github.com/ANTsX/ANTs/issues/1059
https://github.com/ANTsX/ANTs/issues/1183
https://github.com/ANTsX/ANTs/issues/1199

and others.

**Comment by cookpa** [comment]
I tried and failed to get the `-dirty` tag included in locally modified repos, but my main goal is to have a means to put version information into a release tarball, so that ANTs can be built with version information.

**Comment by cookpa** [comment]
Ideally I'd like an automated way for releases to be published with the correct version information, without having it hard-coded into the repository. Looking at Github Packages

https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages

**Comment by oesteban** [comment]
@cookpa just to understand the problem. You basically want an automated way to stick the version information into the tarball when you create a new release, so that the tarballs attached to each release [here](https://github.com/ANTsX/ANTs/releases) have the version information.

At the moment, that is handled by the git-archive built-in into GitHub, and therefore, once you create the tag the archive is generated automatically without the possibility of modification - correct?
