### ISSUE TITLE
Timing of AntsregistrationSyn

### ISSUE THREAD

**Issue by rosella1234** [ANTsX/ANTs#1233]
Hi, I am applying AntsregistrationSyn.sh script to register my structural T1 image to MNI space . However, this is taking several (12) hours per subject. I have sent one script per each core of the server I am using, but I fear this, instead of speeding up, is slowing the computation.

Is there a way to increase speed of this script? 

My OS information are:
 LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

 This happens for two different ANTs version: 2.3.5.dev257-ga4668 and 2.3.1.dev108-g76b0c
thank you very much 
Rosella

**Comment by ntustison** [comment]
The ``antsRegistrationSyN.sh`` script is known to be very time-consuming due to the chosen parameters which are very conservative.  That prompted the creation of the script ``antsRegistrationSyNQuick.sh`` which you should test and see if that suits your needs.

**Comment by rosella1234** [comment]
Ok thank you very much! One more question, my server has up to 90 cores, would it be suitable for antsRegistrationSyNQuick.sh to be run with multithreading? Or using single thread is better? 
thanks

**Comment by ntustison** [comment]
Although it would probably depend on the details of your set-up, I personally would do the latter as it's easier to organize and single-subject jobs are pretty quick with `` antsRegistrationSyNQuick.sh``.

**Comment by rosella1234** [comment]
ok thank you very much 
Rosella
