### ISSUE TITLE
Apply motion to an ants image

### ISSUE THREAD

**Issue by eilin123** [ANTsX/ANTs#1234]
Hi, 
I am trying to figure out a way to add motion to an ants image such that the image moves in x and y direction by a set parameter. 
I tried doing the following but motion image is the same as fixed image. Can anyone help me figure it out or please adviseme if there is a simpler  way to add motion to an image. 

tx      = ants.new_ants_transform(dimension=2)
tx.set_parameters((0.9,0,0,1.1,10,11))
ants.write_transform(tx, '~/desktop/tx.mat')
tx2    = ants.read_transform('~/desktop/tx.mat')
motion =ants.apply_transforms( fixed=img1, moving=img2, transformlist= '~/desktop/tx.mat')
ants.plot(motion,overlay = img1)

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTsPy/blob/master/tutorials/Transform%20Generators.ipynb

this looks like an antspy question which should be raised there.  please open a new issue there if you need further help.
