### ISSUE TITLE
ANTs on the new Apple M1 chip set

### ISSUE THREAD

**Issue by nSpotorno** [ANTsX/ANTs#1235]
Hi All,
does anybody have experience with building and running ANTs with the new Apple M1 chip set? I have heard that several imaging packages had/have some troubles and, before buying a new laptop, I would like to know if ANTs would run smoothly on it.
Thanks,
Nicola

**Comment by cookpa** [comment]
A nice discussion of the issues here, with some tests, but unfortunately no ANTs.

https://github.com/neurolabusc/AppleSiliconForNeuroimaging

It would be great to test ANTs, perhaps by running `antsCorticalThickness.sh`. But I don't have access to an M1 machine

**Comment by nSpotorno** [comment]
Thanks @cookpa 
I can ask around my lab if someone with an M1 would let me play with it for a bit but I cannot guarantee.

**Comment by andreped** [comment]
I see that this issue is closed, but have anyone gotten ANTs to work with the new M1 CPUs?

**Comment by cookpa** [comment]
I don't know. Since ITK builds on M1, it is a good sign that ANTs will build also. But I don't have an M1 machine to test.

**Comment by ntustison** [comment]
This was a motivating issue for the equipment requests in the ANTs grant.  Hopefully that will come through soon.

**Comment by nSpotorno** [comment]
I have ANTs v2.3.5 running on a mac based on M1 chip. I run a couple of registrations and basic commands and they worked fine but I haven't tested extensively.

**Comment by andreped** [comment]
> I have ANTs v2.3.5 running on a mac based on M1 chip. I run a couple of registrations and basic commands and they worked fine but I haven't tested extensively.

Do you have any instructions on how to build ANTs on the macs wth M1 chip? Anything specific we need to do to get it working? Should it work if I just following the build instructions [here](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS)?

**Comment by nSpotorno** [comment]
Yes, if I remember correctly it should simply work following the normal instructions.

**Comment by citystrawman** [comment]
I am also trying to run ANTs on m1 macbook, has anyone solved this issue ?

**Comment by andreped** [comment]
Hello, @citystrawman! Yes, this has been solved. The latest release of Raidionics should run just fine on ARM CPUs. Just be sure to download the installer with _arm in the name.

**Comment by andreped** [comment]
Hello, @citystrawman! We have had success building ANTs ourselves on ARM chip, as well as using the latest ARM-compatible python wrapper binary. So ANTs work fine on ARM chip!

**Comment by cookpa** [comment]
It seems ANTs builds on M1 chips following this method:

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

@citystrawman please let us know if you come across anything M1 specific that needs mentioning

**Comment by citystrawman** [comment]
> It seems ANTs builds on M1 chips following this method:
> 
> https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS
> 
> @citystrawman please let us know if you come across anything M1 specific that needs mentioning

Thanks! I just managed to run the ANTs release version of  [ants-2.5.0-macos-12-X64-clang.zip](https://github.com/ANTsX/ANTs/releases/download/v2.5.0/ants-2.5.0-macos-12-X64-clang.zip) on my M1 macbook pro 16 inch version. As the release version is compiled at x86 platform, I have to use `arch x86_64 ` command to run it. It tooks me more than 2 hours to run the  `antsRegistrationSyN.sh -d 3 -f .\TestFiles\mprage.nii -m .\TestFiles\flash.nii -o output `.

So may I know how long it takes you to run the command when using the original M1 compiled executions? If the time reduction is not too big, I think I'll just use the release verion, if the time reduction is big, I will have to compile the source code although I am not familiar with programming

**Comment by citystrawman** [comment]
> Hello, @citystrawman! We have had success building ANTs ourselves on ARM chip, as well as using the latest ARM-compatible python wrapper binary. So ANTs work fine on ARM chip!

Thanks! I just managed to run the ANTs release version of [ants-2.5.0-macos-12-X64-clang.zip](https://github.com/ANTsX/ANTs/releases/download/v2.5.0/ants-2.5.0-macos-12-X64-clang.zip) on my M1 macbook pro 16 inch version. As the release version is compiled at x86 platform, I have to use arch x86_64  command to run it. It tooks me more than 2 hours to run the antsRegistrationSyN.sh -d 3 -f .\TestFiles\mprage.nii -m .\TestFiles\flash.nii -o output .

So may I know how long it takes you to run the command when using the original M1 compiled executions? If the time reduction is not too big, I think I'll just use the release verion, if the time reduction is big, I will have to compile the source code although I am not familiar with programming

**Comment by cookpa** [comment]
The execution time is going to depend on various factors including memory, number of threads, and the data being processed.

From what I've read, M1 chips emulating x86 are still faster than the x86 CPUs they replaced. The native compiled version should be faster still, but I don't know how big the difference is.

**Comment by citystrawman** [comment]
> The execution time is going to depend on various factors including memory, number of threads, and the data being processed.
> 
> From what I've read, M1 chips emulating x86 are still faster than the x86 CPUs they replaced. The native compiled version should be faster still, but I don't know how big the difference is.

Thank you!

**Comment by citystrawman** [comment]
> The execution time is going to depend on various factors including memory, number of threads, and the data being processed.
> 
> From what I've read, M1 chips emulating x86 are still faster than the x86 CPUs they replaced. The native compiled version should be faster still, but I don't know how big the difference is.

Just found that there's a parameter -n which assigns how many cores the executor use. the default is 1, I set it to 4 and now it is much faster.

**Comment by RichardLStudent** [comment]
Hi, from the above comments it seems that ANTs builds on M1, however when I run the standard superbuild from this website [here](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS) (shell script attatched) I get an error message saying: "error: unknown target CPU 'apple-m1'unknown target CPU 'apple-m1'"

This occures when building ITKv5.

Attatched are the build.log and cmake.log 

[build.log](https://github.com/ANTsX/ANTs/files/14947158/build.log)
[cmake.log](https://github.com/ANTsX/ANTs/files/14947160/cmake.log)
[installANTs.sh.zip](https://github.com/ANTsX/ANTs/files/14947225/installANTs.sh.zip)

Thanks for any helpful comment :)

**Comment by cookpa** [comment]
I don't have an M1 so I've never tried this myself. But I think the problem is here in build.log

```
-- Arch detected: 'x86_64'
-- Basearch of 'x86_64' has been detected as: 'x86'
```

There's ARM64 binaries here

https://github.com/ANTsX/ANTs/releases/tag/v2.5.1

which were built using Github Actions but it uses the same cmake call as x86_64, so I'm not sure what's going on.

**Comment by cookpa** [comment]
Could try adding

```
  -DCMAKE_OSX_ARCHITECTURES=arm64
```

to the cmake call?

**Comment by cookpa** [comment]
More info here

https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html

Is it possible you've installed an x86_64 version of CMake?

**Comment by AlfredSwitchog** [comment]
@cookpa Thanks a lot for the guidance here. When I moved to the new M1 machine I forgot to change to the proper cmake installation. After switching to the proper cmake version and adding 

`-DCMAKE_OSX_ARCHITECTURES=arm64`

to the call the build was executed properly.

**Comment by cookpa** [comment]
Thanks for the update, I'll put this info into the wiki.
