### ISSUE TITLE
Longitudinal ANTs CT underestimating individual scans, not template

### ISSUE THREAD

**Issue by dbrennan44** [ANTsX/ANTs#1238]
Good afternoon ANTs team,

I've got a strange issue and wondering if it's been observed before. I am running a study with longitudinal and cross-sectional components, and having some trouble comparing longitudinally-derived measures with normal ANTs CT. 

Specifically, it appears that the "individual timepoints" which make up the SST are being under-estimated relative to the subject-specific template itself: 
![image](https://user-images.githubusercontent.com/39420777/133677410-15b6e24b-0584-4553-be98-f4faff6fd8da.png)

this is seen across many different ROIs, and leads me to believe something is going on during the iterative process of Longitudinal ANTs CT. 

As I understand it, longitudinal ANTs goes:

OASIS priors > ANTS-CT > Study Template posteriors
Study template priors > ANTS-CT > SST posteriors
SST priors > ANTS-CT > subject-level posteriors 

.... with the " -p CT_BrainSegmentationPosteriors%d.nii.gz " input to each iteration of ANTs CT. Is there something I'm missing here? (by the way, I just created my own SST and ran regular ANTs-CT at each of these steps)

Thanks for your help in advance.

**Comment by cookpa** [comment]
There's definitely differences between the two pipelines. You can call `antsLongitudinalCorticalThickness.sh` with one session, it will denoise the input image and then treat that as the SST:

https://github.com/ANTsX/ANTs/blob/0a08209784896a797dfb366b7c0cef083533b454/Scripts/antsLongitudinalCorticalThickness.sh#L587-L592

This will give you a closer approximation to a cross-sectional version of the longitudinal pipeline.

**Comment by ntustison** [comment]
> Specifically, it appears that the "individual timepoints" which make up the SST are being under-estimated relative to the subject-specific template itself:

I'm not surprised.  I don't believe the SST thickness values have ever been used in any type of analysis coming from our group.  Regardless, this is a problematic comparison and very much relates to earlier work (e.g.,  Freesurfer and FSL papers and Paul Yushkevich).  See the introduction in the [2019 longitudinal thickness paper](https://pubmed.ncbi.nlm.nih.gov/31356207/).  Essentially, if you don't treat all time points the same in your thickness pipeline, you potentially introduce artificial changes in values such as cortical thickness.  In this case, the SST is essentially a smoothed version of any single time point which will artificially affect the relative thickness measurements.  Note that Paul's paper looks specifically at the effects of interpolation (which results in a type of smoothing).

**Comment by dbrennan44** [comment]
@ntustison thanks for this insight. It makes sense that the SST would reveal thicker values given the info you've shared.

Do you suggest the same as @cookpa and basically run the cross-sectional data (e.g., single "control" scan) twice, using it as its own SST?

Perhaps my motivation can clarify: my group has been investigating a strange lack of correspondence between versions of the pipeline, where cross-sectional/control data have a near 1:1 correspondence while patients do not eg: 

![image](https://user-images.githubusercontent.com/39420777/133692405-4949b4dc-08ab-4511-9b85-5d23207d7750.png)

is there anything else that could be causing the under-estimation of patients (yellow)? Something in "antsLongitudinalCorticalThickness.sh" that is not captured by sequentially running "antsCorticalThickness.sh" on a study-template, single-subject-template, then on individual timepoints? 

Thanks again for your time.

**Comment by ntustison** [comment]
Sure, and yes to Phil's suggestion.  I'm pretty sure it was @jeffduda who discovered this issue early on and led to its correction in the current longitudinal script.  I believe he posted it as a GitHub issue and showed related plots.

**Comment by dbrennan44** [comment]
sorry, what was the issue that was resolved? Single-subject longitudinal processing? I am unable to find the issue currently

**Comment by ntustison** [comment]
[Yes.](https://github.com/ANTsX/ANTs/pull/502).  Perhaps it was an email Jeff sent and not an issue.

**Comment by dbrennan44** [comment]
Got it. Strangely, it seems that the “cross Sectional ” data is perfectly fit, with the longi data being under estimated. Still not sure why that’s happening. 

Anyways, what is the role of “cooking” the priors? i believe I’m missing that step in my custom pipeline, perhaps this is the problem..

**Comment by cookpa** [comment]
Just so I'm clear on what's going on, your purple (control) and yellow (patient) dots are sessions processed with `antsCorticalThickness.sh` (y-axis) and then the same sessions processed with `antsLongitudinalCorticalThickness.sh`?

The prior "cooking" involves using a set of labeled atlases to create a consensus segmentation in the SST space (using joint fusion). These labels are then smoothed and used as priors for classes 2-6 (CSF is derived from a segmentation of the SST, for historical reasons). The default behavior without these atlases is to use the SST segmentation as a prior for all classes.

The group template priors in `antsCorticalThickness.sh` are by default weighted at 0.25. The SST priors in the long script are by default weighted at 0.5. This regularizes longitudinal change, and will affect the estimates.

**Comment by dbrennan44** [comment]
@cookpa , you're correct other than X-axis is @jeffduda's pipeline and an older version of ANTs (I believe antsLongitudinalCorticalThickness.sh), y-axis is my custom pipeline which was made to emulate antsLongitudinalCorticalThickness via multiple iterations of antsCorticalThickness.sh. My custom script was made to 1. make SST outside of a single call to ANTs and 2. accommodate lesion masking more easily. I don't have labelled atlases of 6-tissue priors, so I believe I am using the "default behavior" of using the SST segmentation as a prior. My code is approximately as follows:

`
#get study template priors
antsCorticalThickness.sh -d 3 -a $Group_Template/t1.nii \ 
-e $OASIS/t1.nii \
-m $OASIS/mask.nii \
-p $OASIS/labelsPriors%02d.nii.gz \
-x 25 \
-w 0.25 \
-o $Group_Template/T_

#get SST priors
antsCorticalThickness.sh -d 3 -a $SST/T_template0.nii.gz \ 
-e $Group_Template/t1.nii \
-m $Group_Template/mask.nii \
-p $Group_Template/labelsPriors%02d.nii.gz \
-x 25 \
-w 0.25 \
-o $SST/T_

#get subject time-point cortical thickness
antsCorticalThickness.sh -d 3 -a $Patient_s1/T_template0.nii.gz \ 
-e $SST/t1.nii \
-m $SST/mask.nii \
-p $SST/labelsPriors%02d.nii.gz \
-x 25 \
-w 0.25 \
-o $Patient_s1/T_

`

The main difference i'm seeing between this procedure is that 1. SST prior-weight is 0.25 not 0.5, and 2. posteriors are not smoothed before being used as priors. If I had to guess, the weight parameter may be to blame for underestimation. 

Thanks again for your response, this was really informative.
