### ISSUE TITLE
poor coregistration of T1 and partial FOV image with antsRegistration.sh

### ISSUE THREAD

**Issue by vanessambrown** [ANTsX/ANTs#1239]
Hi, 

I have an anatomical scan (neuromelanin-sensitive magnetization transfer) with a partial FOV that I am trying to register to each subjects' T1 image in native space. This is working for most subjects but I have run into one subject whose images will not co-register correctly, possibly due to some motion-related artifacts in the T1 image. We have just started collecting data so I anticipate running into this problem with future subjects' data as well. I have tried several suggested approaches that I have found on here and the old sourceforge page - swapping the fixed and moving image; supplying masks - with no luck. My most recent attempt reproduced the code suggested here: https://github.com/ANTsX/ANTs/issues/1110. This results in the following:

commands: 
fixedImage=${processed_path}/${ID}_NMBrainExtractionBrain.nii.gz
fixedImageN4=${processed_path}/${ID}_NMBrainExtractionBrainN4.nii.gz
movingImage=${processed_path}/${ID}_T1BrainExtractionBrain.nii.gz
maskImage=${processed_path}/${ID}_NM_bet_mask.nii.gz
outputPrefix=${processed_path}/${ID}_NM_bet_nativeT1

N4BiasFieldCorrection -d 3 -i $fixedImage -o $fixedImageN4 -b [100] -c [200x200x200x200,0] -v  -s 4

ThresholdImage 3 ${fixedImageN4} ${maskImage} 100 Inf

antsRegistration --verbose 1 \
--dimensionality 3 \
--float 0 \
--interpolation Linear \
--use-histogram-matching 0 \
--winsorize-image-intensities [0.005,0.995] \
--output [${outputPrefix},${outputPrefix}Warped.nii.gz,${outputPrefix}InverseWarped.nii.gz] \
--initial-moving-transform [${fixedImageN4},${movingImage},1] \
--transform translation[0.2] \
--metric MI[${fixedImageN4},${movingImage},1,32,Random,0.5] \
--convergence [400x200x100,1e-6,10] \
--shrink-factors 8x4x2 \
--smoothing-sigmas 0x0x0vox \
--masks [${maskImageN4},NULL] \
--transform Rigid[0.2] \
--metric MI[${fixedImageN4},${movingImage},1,32,Random,0.5] \
--convergence [500x500x250x50,1e-6,10] \
--shrink-factors 6x4x2x1 \
--smoothing-sigmas 2x1x0x0vox \
--masks [${maskImage},NULL] 

-NM-MT (copper) and T1 images prior to co-registration:
![image](https://user-images.githubusercontent.com/26512306/134238292-8c80dfa8-3565-487f-93bf-c69dd5c4c05d.png)

-NM-MT (blue) after co-registration:
![image](https://user-images.githubusercontent.com/26512306/134238400-18e8d198-6ef5-4e15-91fc-e98674ebdb6a.png)

I also don't feel I understand how the masks help with registration. I've tried masking the NM-MT image as above and/or supplying a T1 mask excluding the superior part of the brain not covered by the NM-MT mask, but in general supplying masks does not seem to change the co-registration much. 

Thank you in advance for your help!

**Comment by cookpa** [comment]
> I also don't feel I understand how the masks help with registration. I've tried masking the NM-MT image as above and/or supplying a T1 mask excluding the superior part of the brain not covered by the NM-MT mask, but in general supplying masks does not seem to change the co-registration much.

The mask prevents any point outside the mask from contributing to the similarity metric. But it won't save you if the initialization is bad. I think `--initial-moving-transform [${fixedImageN4},${movingImage},1]` is putting you out of reach of a correct solution.

**Comment by vanessambrown** [comment]
thanks for the clarification on the masks - makes sense. 

I tried making the edits you suggested, but ran into this error: 
"*** Running Euler3DTransform registration ***

Exception caught: 
itk::ExceptionObject (0x4e49650)
Location: "unknown" 
File: /ihome/crc/build/ants/ANTs_20190225/antsbin/ITKv5-install/include/ITK-5.0/itkMattesMutualInformationImageToImageMetricv4.hxx
Line: 197
Description: itk::ERROR: MattesMutualInformationImageToImageMetricv4(0x48f3fb0): Joint PDF summed to zero"

commands: 
antsRegistration --verbose 1 \
--dimensionality 3 \
--float 0 \
--interpolation Linear \
--use-histogram-matching 0 \
--winsorize-image-intensities [0.005,0.995] \
--output [${outputPrefix},${outputPrefix}Warped.nii.gz,${outputPrefix}InverseWarped.nii.gz] \
--initial-moving-transform [${fixedImageN4},${movingImage},2] \
--transform Rigid[0.2] \
--metric MI[${fixedImageN4},${movingImage},1,32,None,1] \
--convergence [50x50x50,1e-6,10] \
--shrink-factors 3x2x1 \
--smoothing-sigmas 1x0x0vox \
--masks [${maskImage},NULL]

I've attached the skull-stripped NM-MT and T1 images, let me know if you need anything else. 
[440243_NMBrainExtractionBrain.nii.gz](https://github.com/ANTsX/ANTs/files/7206082/440243_NMBrainExtractionBrain.nii.gz)
[440243_T1BrainExtractionBrain.nii.gz](https://github.com/ANTsX/ANTs/files/7206083/440243_T1BrainExtractionBrain.nii.gz)

**Comment by cookpa** [comment]
The mask is in the moving space, not the fixed space. I don't think it will be very useful in that context. 

I'm not sure why aligning the origins didn't help - but if I remove the `--initial-moving-transform` argument entirely, it works for me:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/611507/134245589-a5ad8ba5-c5ae-4b24-9114-4b606d755ea3.png">

The registered images is green, original blue. Visualized with ITK-SNAP

**Comment by vanessambrown** [comment]
excellent, removing the --initial-moving-transform worked for me as well. thanks for the help!

**Comment by cookpa** [comment]
Excellent. As a reminder to myself, the initialization option 2 actually translates the moving origin to the fixed origin. 

If the moving and fixed images are already aligned in physical space, as in this case, then no initial moving transform is needed.
