### ISSUE TITLE
Accuracy of the template ?

### ISSUE THREAD

**Issue by valeryozenne** [ANTsX/ANTs#1240]
Hi,

## Question

I have a general question related to template creation, it slightly out of topics on this forum, and I'm sharing partial information, I admit. But in case, you already meet/answer to this question, feel free to share any suggestion:

When performing template creation, do you have a way to performed a quality assessment of the template. In my attempt to publish some work made thanks to ANTs, I naively thought that a visual agreement was sufficient. I'm asking because it is a recurrent question. In addition, the template and associated transformation are then used for registering DWI and streamlines, so I thought that showing the preservation of the FA distribution in the diffusion tensor template was the right way. 

- Option 1 could be to compute the similarity between images (using MeasureImageSimilarity with MeanSquares or CC or MI for instance ) and create a 2D matrix for the initial image in native space and the warped image in template space. Is it more convincing than the preservation of FA ? 

- Option 2 ?.

Thanks in advance,
Valéry

## Comment of the reviewer :

"It is very difficult to understand if the authors were successful at their stated aim of generating a template of the heart. The template is described as having 'excellent anatomical consistency', yet this assessment was not performed with any rigor. Assessment of the accuracy of the template was performed visually, and without quantitative reporting of image-based metrics or using multiple expert raters, in different regions of the heart."

## Corresponding figure: 

![page10](https://user-images.githubusercontent.com/7050315/134386158-39009d1b-e16e-431f-98b0-64ebeef377ad.png)

**Comment by stnava** [comment]
your templates look great to me.   obviously, that's not sufficient.   two ideas of how to evaluate:

* segmentation results ---  1. label some anatomical region(s) manually in several images in their original space;   2. register these images to each template;  3. compute overlap between the registered segmentations .... in the ideal world, these will be "perfect" but you will see the numbers improve with the template quality.   

* detection of some effect:   similar to above but the target is a correlation with some other factor(s):  age , pathology, etc .... you have to be careful here to make sure that the effects that you are detecting are stronger for a "good reason" ie the registration is better.     e.g.  bad registration can lead to very large effect sizes - although these should be considered spurious.

so, doing both above (or some variation thereof) would be a reasonable way to address the reviewer concerns.   hard to say more without seeing the full paper etc.

**Comment by cookpa** [comment]
Good suggestions @stnava 

> * segmentation results ---  1. label some anatomical region(s) manually in several images in their original space;   2. register these images to each template;  3. compute overlap between the registered segmentations .... in the ideal world, these will be "perfect" but you will see the numbers improve with the template quality.

An example of this kind of evaluation: https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC3065962/

**Comment by valeryozenne** [comment]
Thanks a lot for your answers and suggestions. It helps me a lot. 
Best,
Valéry

I close the issue
