### ISSUE TITLE
ANTs Install error on CentOS 7

### ISSUE THREAD

**Issue by eburkevt** [ANTsX/ANTs#1242]
I am trying to install ANTs using the installANTs.sh script from

**When did the error occur?**

I get the following error messages after '[51%] Built target itkvnl' 
.
.
.
[ 51%] Built target itkvnl
make[3]: *** [all] Error 2
make[2]: *** [ITKv5-prefix/src/ITKv5-stamp/ITKv5-build] Error 2
make[1]: *** [CMakeFiles/ITKv5.dir/all] Error 2
make: *** [all] Error 2

**Build environment**
Linux CentOS 7.5 (64-bit)
using 
gcc version 4.8.5
git version 2.30.1
cmake version 3.21.3
(the last two were updated and replaced the standard installed versions)

**Build configuration and logs**

I attached the log files from the attempted build in the following zip file.

[install_failure.zip](https://github.com/ANTsX/ANTs/files/7238899/install_failure.zip)
 
Anyone have ideas why the build is failing?

Thanks

**Comment by cookpa** [comment]
From build.log:

```[ 42%] Building CXX object Modules/ThirdParty/MetaIO/src/MetaIO/src/CMakeFiles/ITKMetaIO.dir/metaContour.cxx.o
/bin/sh: line 1: 28821 Illegal instruction     (core dumped) /opt/ANTs/build/ITKv5-build/Modules/ThirdParty/GDCM/src/gdcm/bin/H5detect > /opt/ANTs/build/ITKv5-build/Modules/ThirdParty/HDF5/src/itkhdf5/H5Tinit.c```

Try adding

```
-DSuperBuild_ANTS_C_OPTIMIZATION_FLAGS="-mtune=native -march=native" \
-DSuperBuild_ANTS_CXX_OPTIMIZATION_FLAGS="-mtune=native -march=native"
```

to the call to cmake

**Comment by eburkevt** [comment]
That fixed it! The build was successful. Thanks!
