### ISSUE TITLE
Question about segmentation for cortical thickness 

### ISSUE THREAD

**Issue by jsebgiudice** [ANTsX/ANTs#1244]
Hello,

We're trying to run some cortical thickness calculations using antsCorticalThickness.sh. We see that this requires priors for 4 tissue types (CSF, WM, cortical GM, and subcortical GM). What are the best practices for obtaining these priors for a new image (e.g., a template we created for our study)? We've tried running antsAtroposN4.sh with 4 tissue classes and the output was not what we expected (looked like the cortical GM was split into two regions). We've also tried 6 tissue classes with similar results.

Thanks,
Sebastian

**Comment by cookpa** [comment]
You could use an existing template to segment your population, then average the posteriors in the template space. You can get templates from here

https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436
