### ISSUE TITLE
antsBrainExtraction cut off part of the brain

### ISSUE THREAD

**Issue by carolin31** [ANTsX/ANTs#1245]
**Describe the problem**
Hello ants experts, I am running antsBrainExtraction on brains of older subjects. It worked well for all subjects except of one where it cut off part of the brain. I tried running it with the Kirby template instead of the template for older subjects but I get the same result. Are there any parameters I could try to change? I could not find anything in the -help option. Also at least based on visual inspection I can not see anything wrong with the anatomical image.

**To Reproduce**
The command I ran: $SANTS antsBrainExtraction.sh -d 3 -a /mnt/yassamri/BEACoN/ProcessedData/rsfMRI/RSFA/$1/anat/$1_T1.nii.gz -e /mnt/yassamri/BEACoN/ProcessedData/rsfMRI/RSFA/templates/T_template0.nii -m /mnt/yassamri/BEACoN/ProcessedData/rsfMRI/RSFA/templates/T_template0_BrainCerebellumProbabilityMask.nii -o $1_ -k 1

I attached a pdf with the output.
I ran it in an ants container using singularity.

<img width="1109" alt="Screen Shot 2021-09-29 at 10 04 27 AM" src="https://user-images.githubusercontent.com/41706947/135316497-f71edef4-7c3f-47a5-93ad-9ef997a916c8.png">

[antsBrainExtr14598.pdf](https://github.com/ANTsX/ANTs/files/7253834/antsBrainExtr14598.pdf)

**Comment by cookpa** [comment]
With `-k 1` you should still have the registration warps between the template and the subject image. So you can warp the template to the subject space and see if the alignment is reasonable. If the alignment looks close to correct, the problem is the segmentation step.

**Comment by dorianps** [comment]
If I remember correctly, these cases benefit by adding a brain+skull
registration mask with the -f argument:

-f:  Brain extraction registration mask    Mask used for registration to
limit the metric computation to
                                                a specific region.

Dorian

**Comment by cookpa** [comment]
Yes, a mask might work. 

BTW, what version of ANTs is this?

**Comment by carolin31** [comment]
Hello,

thank you very much for the quick reply. Its version 2.3.4. 
So if I would want to try adding the brain+skull mask it will be basically the anatomical image, which is already the input image that I want to get skull stripped with ants right?

**Comment by cookpa** [comment]
The registration mask would be in the template space. If you have the OASIS template, it's `T_template0_BrainCerebellumRegistrationMask.nii.gz`. You pass this with `-f T_template0_BrainCerebellumRegistrationMask.nii.gz`.

The idea is to mask out regions that are causing a mismatch. For example, if your template has the face removed, but the moving image does not, you would want to mask out the regions where the facial features would go in the template.

If your template doesn't have such a mask, you can usually make one that's a fairly good approximation by thresholding and dilating the brain + skull image. Here's one I made recently

<img width="363" alt="image" src="https://user-images.githubusercontent.com/611507/135553620-7b485226-c613-4f6c-b97f-a657069f49ad.png">

**Comment by dorianps** [comment]
Hey Phil, looks like you are including a bit of the edge of the removed
face, which may confuse the registration, right?

**Comment by cookpa** [comment]
It's something of a trade-off. Anything outside the mask is ignored, including anything that would match better if it were inside the mask. So it can be better if the mask is not tight to the head.

**Comment by dorianps** [comment]
I see. The skull edge is good to have actually. I only thought the anterior
area by the face, which is included in the mask, may be awkward to
register. But maybe that's a trade off as you said.

Thanks.

**Comment by carolin31** [comment]
Hi! 
thank you very much for your help! I ran he subject with the registration mask and it worked. The brain extraction looks very good!
For another subject where the brain was cut-off previously (when running without registration mask), it now produced a results where there is non-brain tissue remaining when running with the registration mask. I have two more subjects where some non-brain tissue remained after brain extraction and running those subjects with the registration mask did not fully resolve that issue. Is there another fix for the instances when there is not enough tissue removed around the brain? 

<img width="1450" alt="Screen Shot 2021-10-01 at 6 03 44 PM" src="https://user-images.githubusercontent.com/41706947/135699170-6f6d8ead-1120-4403-b0c0-33dc246c2daa.png">
<img width="1274" alt="Screen Shot 2021-10-01 at 5 38 08 PM" src="https://user-images.githubusercontent.com/41706947/135699175-c8764d6b-7e0a-4a31-802d-e9651df5a612.png">

**Comment by ntustison** [comment]
Although it performs well, ``antsBrainExtraction.sh`` is build on relatively simplistic priors and so one might find themselves frequently having to adjust input parameters (e.g., template).  Have you looked at the [ANTsPyNet brain extraction function](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/brain_extraction.py)?  This is much faster, has no tuning required, and offers several modalities and a FreeSurfer-like extraction available as well.
