### ISSUE TITLE
 antsCorticalThickness : cannot find operation : ReplaceVoxelValue 

### ISSUE THREAD

**Issue by cubalimpre** [ANTsX/ANTs#1249]

**Comment by cookpa** [comment]
Have you set ANTSPATH correctly? If you run

`${ANTSPATH}ImageMath 3 someOutput.nii.gz ReplaceVoxelValue someImage.nii.gz 1 1 2`

It should run without problems.

**Comment by cookpa** [comment]
> I run the _: ${ANTSPATH}ImageMath 3 someOutput.nii.gz ReplaceVoxelValue someImage.nii.gz 1 1 2_ and I had the error : _cannot find operation : ReplaceVoxelValue_
> 

OK, so you don't need to test the script further. This command needs to work before you can run `antsCorticalThickness.sh`.

```
# Should output /path/to/ants/bin/, wherever you installed ANTs
# Needs to end with a slash
echo ${ANTSPATH}

# should print 2.3.5.dev212-g44225
${ANTSPATH}antsRegistration --version

#   ReplaceVoxelValue: replace voxels in the range [a,b] in the input image with c
#   Usage        : ReplaceVoxelValue inputImage a b c 
${ANTSPATH}ImageMath | grep ReplaceVoxelValue
```

**Comment by cubalimpre** [comment]
So running the above lines : 
# Should output /path/to/ants/bin/, wherever you installed ANTs
# Needs to end with a slash
echo ${ANTSPATH}

_/home/medpsychws2/ANTs/install/bin_

# should print 2.3.5.dev212-g44225
${ANTSPATH}antsRegistration --version

_ANTs Version: 2.3.5.dev212-g44225
Compiled: Feb  2 2021 12:28:42_

#   ReplaceVoxelValue: replace voxels in the range [a,b] in the input image with c
#   Usage        : ReplaceVoxelValue inputImage a b c 
${ANTSPATH}/ImageMath | grep ReplaceVoxelValue

and then i run the antsCorticalThickness.sh. but again : 

_BEGIN >>>>>>>>>>>>>>>>>>>>
/home/medpsychws2/ANTs/install/bin/ImageMath 2 /home/medpsychws2/antsCorticalThicknessExample-master/OutputT1Only/exampleCorticalThicknessSegmentation.nii.gz ReplaceVoxelValue /home/medpsychws2/antsCorticalThicknessExample-master/OutputT1Only/exampleBrainSegmentation.nii.gz 4 4 3
 cannot find operation : ReplaceVoxelValue
END   <<<<<<<<<<<<<<<<<<<<


The brain segmentation image doesn't exist:
   /home/medpsychws2/antsCorticalThicknessExample-master/OutputT1Only/exampleCorticalThicknessSegmentation.nii.gz_

it seems like the grep did not work

**Comment by cubalimpre** [comment]
Here it is:
[exampleOutput.txt](https://github.com/ANTsX/ANTs/files/7311766/exampleOutput.txt)

**Comment by ntustison** [comment]
Yeah, I agree with @cookpa .

**Comment by ntustison** [comment]
no
