### ISSUE TITLE
reference for TVMSQ

### ISSUE THREAD

**Issue by colddie** [ANTsX/ANTs#1251]
Hi,

Is there any reference to the type-of-transforms below? I couldn't find anywhere.
“TVMSQ”: time-varying diffeomorphism with mean square metric
“TVMSQC”: time-varying diffeomorphism with mean square metric for very large deformation

Thanks

**Comment by ntustison** [comment]
https://www.frontiersin.org/articles/10.3389/fninf.2014.00044/full
