### ISSUE TITLE
Reusing antsMTC2 warps/affines

### ISSUE THREAD

**Issue by araikes** [ANTsX/ANTs#1253]
Hi all,

I had a quick question. I'm sure I've seen answer to this somewhere but can no longer find it.

I'm using antsMultivariateTemplateCreation2.sh to develop study-specific templates on mice. Given the sample sizes, I'm using our whole study to generate the templates (< 50 mice, typically). 

Since I'm using all of the available mice for a given study, is it valid to re-use the antsMTC2 warp and affine files to warp other modalities  (e.g., coregistered NODDI outputs) to template space or conversely to warp template-registered atlas to native space? Is independent re-registration to template space necessary in this particular use case?

Thanks

**Comment by cookpa** [comment]
The one complication with this is that the template is updated after every iteration. So if you make N candidate templates, the warps left behind at the end are registered to template (N-1). If things worked well this is only a very small difference.

We've made some changes to the template scripts lately, so they also save the templates from every iteration by default. Thus you would be able to keep both the warps and the exact template to which they refer.
