### ISSUE TITLE
LesionFilling seems not to save the resultant image.

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTs#1258]
I was running LesionFilling command on Linux VM (Xubuntu VBox). 
It is a very simple and straightforward script, but I got an error message shown below:
"""
Number of lesions: 174
./WML_filling_counting_labeling_volume-recording_Data_since_2019.sh: line 18: 21602 Floating point exception(core dumped) ${ANTSPATH}/LesionFilling 3 ./${i}-pre-denoised-T1W_0p5.nii.gz ./${i}-FLAIR_WML.nii.gz ./${i}-lesion_filled_T1W_0p5.nii.gz
'
"""
And the result (supposed to be a lesion-filled T1 image) was not saved.

I would like to know what may cause 'Floatingpoint exception(core dumped)'?
Are there any conditions for input data? (nii.gz or nii etc.)

Thank you,
SC

**Comment by cookpa** [comment]
Thanks - I think there is a divide by zero happening somewhere. I'll work on a fix for `LesionFilling`.

**Comment by sj-choi** [comment]
In the meantime, is there any similar implementation (in ANTsR or ANTsRNet) of LesionFilling so that I can use it instead of LesionFilling (in ANTs)?
