### ISSUE TITLE
General questions about memory consumption and ANTs for large dataset

### ISSUE THREAD

**Issue by valeryozenne** [ANTsX/ANTs#1262]
Hi,

I have general questions about memory consumption and ANTs. 

## Context

I'm setting up a new pipeline for processing uCT cardiac datasets. One step of the pipeline require the downsampling of the tensor images. The simple solution (for me) was to do it with ANTs to use the log space computation. The pipeline is the following:

- 1) Compute Tensor from anatomical images (using home made code) and save each tensor components in nifti format.

- 2) Create the Tensor (ANTs compatible):  ImageMath 3 $TENSOR ComponentTo3DTensor $COMPONENTS_

- 3) Resample the tensor : AntsApplyTransforms -e 2 -i $TENSOR -t $IDENTITY_MATRIX.mat -r $REF -o $NEW_TENSOR  with REF a reference image at the desired resolution. 

ps:  I also try with the  "RebaseTensorImage" command but it has not effect as a linear transformation is used.

My dataset is quite large "matrice size: 3016 x 3392 x 3993" (18um), so I started with lower matrices. While it is perfectly running using a lower dataset "matrice size: 1005 x 1130 x 1331" (18um*3), step 2 failed when my matrices become too large. 

I have tried different workaround. 

* The first solution was to just crop the data. It allows me to validate few things (see screeshot 1-2) but I now need the full dataset. 

* I checked that my RAM is sufficient to concatenate my 6 components [xx, xy, xz, yy, yz, zz] (17 Gb each) in a 5D nifti file (98 Gb) using another package but the resulting nifti header is not compatible with the tensor format of ITK (see screenshot 3). 

* Finally, to my knowledge, ANTs is the only high level toolbox that allow manipulation/registration/averaging of tensor images. 

## Questions

1) Is there any magic solution to decrease the memory consumption with ANTs ? For instance 'AntsApplyTransforms' have a "--float" option , is there any hidden option for ImageMath ? 
  
2) One solution would be to not use ANTs and use directly the ITK function behind ANTs. I would like to avoid this solution because it could be a solution where I recode badly what you did with no final improvement. But in case, does ANTs (in bash) could create a overcost in memory in comparison with a direct use of ITK in python for instance ? 

3) For step 1, we are using a python package named DASK (https://dask.org/) and .zarr format(https://zarr.readthedocs.io/en/stable/), do you know if anyone has already tried to combine DASK and ANTs in Python or know if it would be possible, there are few posts suggesting compatibility with ITK (https://blog.dask.org/2019/08/09/image-itk) ?  

Thanks in advance for your help

Valéry

## System

I'm using a ubuntu computer with 377Gi 

## Data

Data is available.

### Screenshot 

Typical results after cropping the data
![Example_uCT_1 ](https://user-images.githubusercontent.com/7050315/138881989-a67034b9-de1c-44ba-8a67-4c41b9873e7c.png)
![Example_uCT_2 ](https://user-images.githubusercontent.com/7050315/138882003-4d1a6df6-bf0b-40e3-b770-3ca862b92bc3.png)

PrintHeader of a tensorImage versus a 5D nifti
![Capture](https://user-images.githubusercontent.com/7050315/138882011-f1e65642-ea01-48ff-909d-054938fb0e4f.png)

**Comment by cookpa** [comment]
> * could you confirm that the ITK framework for Tensor Reorientation behind ANTs is the following:
> 
> https://www.insight-journal.org/browse/publication/742
> 

This is Slicer's algorithm, ours is another implementation but it's similarly based on PPD by Alexander et al.


> * As even the "tensor creation" operation crash with ImageMath [...] ComponentTo3DTensor [...]. I made an attempt to replicate this function using ITK in python and I will investigate the use of zarr. The beginning was relatively easy even if I'm not really familiar with ITK except for the last point: I haven't been able to mimic the fonction `WriteTensorImage` in Python (simply without computing  exp(D)). Could you describe/explain the fonction: NiftiDTICheck() and the following line in https://github.com/ANTsX/ANTs/blob/master/Utilities/ReadWriteData.h line 547 to 560 ?

I think that function was to change the ordering of the components. ITK eventually fixed this, so that function currently does nothing. NIFTI specifies symmetric matrix data such as tensors should be in lower-triangular order. VTK, ITK, FSL use upper-triangular internally. ITK now reads and writes lower-triangular tensors.
