### ISSUE TITLE
Registration of two identical images still produces transformation

### ISSUE THREAD

**Issue by IlvaHou55** [ANTsX/ANTs#1264]
Hi everyone,

As a matter of testing before using it for my specific application, I tried to use ANTs to register two identical images (i.e. moving image is the same as fixed image). In theory you would think that the transformation for this would be the identity matrix, resulting in an identical image after registration. However, in my case, the image was deformed to quite some extend. 

For the registration I used ANTsPy: ants.registration(fixed=fixedmri, moving=fixedmri, type_of_transform='SyN'). The 'SyN' transform defaults to using mutual information as a similarity metric (https://antspy.readthedocs.io/en/latest/registration.html).

I was wondering if someone else encountered this as well and if there is a reason for this, as you would think that mutual information is highest if the moving image is not moved at all.

Thank you in advance.

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues

**Comment by cookpa** [comment]
There's several levels of downsampling and smoothing happening in a usual `antsRegistration` call, which could move the result slightly. But I would not expect large deformations.

If you can make a reproducible example with `antsRegistration`, I'll look into it. Or if you want an answer specific to ANTsPy, please open an issue there https://github.com/ANTsX/ANTsPy/issues

**Comment by IlvaHou55** [comment]
@cookpa I work with sensitive data, so I cannot share that as an example. Let me check if I can find some openly available that shows the same issue.

**Comment by ntustison** [comment]
I'm sure @stnava can weigh in with a more informative explanation concerning mutual information vs. the other metrics (feature space vs. image space), but you might want to compare the following calls:

```
$ MeasureImageSimilarity -d 3 -m MSQ[identicalImage.nii.gz,identicalImage.nii.gz,1,1] -o gradientImageMSQ.nii.gz
$ MeasureImageSimilarity -d 3 -m CC[identicalImage.nii.gz,identicalImage.nii.gz,1,1] -o gradientImageCC.nii.gz
$ MeasureImageSimilarity -d 3 -m MI[identicalImage.nii.gz,identicalImage.nii.gz,1,32] -o gradientImageMI.nii.gz
```

and observe that MI does not result in a zero gradient field like MSQ and CC.  Different from other commonly used metrics, MI measures relative intensity distributions as opposed to localized intensity differences.  Thus, whereas two sets of  identical image pairs will have a maximum cross-correlation of 1 or a minimum mean-squared value of 0 (regardless of image content), if the identical image pairs are different, the MI between the two pairs will have different values depending on the intensity distributions.

**Comment by IlvaHou55** [comment]
@ntustison I understand what you are saying, but I am not sure if it holds if using two identical images as fixed and moving image. Like you said: '_if the identical image pairs are different, the MI between the two pairs will have different values depending on the intensity distributions_'. The thing is that in my case, the identical image pairs are **not** different, so there should not be different intensity distributions..

**Comment by ntustison** [comment]
I'm referring to two sets of identical image pairs, (A', A') and (B', B').  Try reading my comment with that in mind.

**Comment by IlvaHou55** [comment]
@ntustison I think I see what you mean now yes. Thank you.

**Comment by IlvaHou55** [comment]
@cookpa it took me a while to get access to an open dataset similar to my application, but I found something for you to maybe reproduce. From [here](https://figshare.com/s/2904b1ee61c3240f9291) I downloaded a 3D MRI dataset of the heart. I used [MedPy](https://pypi.org/project/MedPy/) to read the image:

`from medpy.io.load import load`
`img = load('path/to/data/MRI_4.nii')`
`img = img[0][:220,50:220,:]`

On the last line I use only the actual image data, not the header (i.e. img[0]) and I crop the image a bit. 
The next step is to convert the image into an ants image:

`import ants`
`movingmri = ants.from_numpy(img)`
`fixedmri = ants.from_numpy(img)`

You see that I use the same image for both the moving as the fixed image. 
Next I will apply the registration and extract the transformation map:

`regis3d = ants.registration(fixed=fixedmri,moving=movingmri,type_of_transform='SyN')`
`transformation=regis3d['fwdtransforms']`

I apply the transformation now on the same images:

`movingmask=ants.from_numpy(img)`
`fixedmask=ants.from_numpy(img)`
`reg=ants.apply_transforms(fixed=fixedmask,moving=movingmask,transformlist=transformation)`
`reg=reg.numpy()`

Now I can compare the images _img_ and _reg_, which should be the same in theory. I also add a difference map (right image below), computed by `np.subtract(img,reg)`:

![image](https://user-images.githubusercontent.com/93598891/140087761-80355141-48a8-44ef-8e85-371e43321274.png)

Although visually there is not much of a difference, the right (subtraction) image let us observe an apparent difference at the borders and at some specific structures. 
I used an interactive tool to scroll through the images and took a screenshot of a slice where this clear difference was present.

@ntustison following your advice, I also applied another transformation with cross-correlation as similarity metric:

`regis3d_CC = ants.registration(fixed=fixedmri,moving=movingmri,type_of_transform='SyNCC')`
`transformation_CC=regis3d_CC['fwdtransforms']`
`reg_CC=ants.apply_transforms(fixed=fixedmask,moving=movingmask,transformlist=transformation_CC)`
`reg_CC=reg_CC.numpy()`

Which resulted in the following:

![image](https://user-images.githubusercontent.com/93598891/140096766-8548a7d1-f811-4871-8ab7-dd049dce70fc.png)

Indeed, for this slice almost no difference is observed. However, especially at the edges, we could still see some difference present:

![image](https://user-images.githubusercontent.com/93598891/140097061-2252e4cd-477f-4df1-89e5-d14cd266cada.png)

Would this residual difference then be a result of smoothing and downsampling?

For my application cross-correlation cannot work (for multiple reasons). Therefore I am restricted to use mutual information as a similarity metric. 

What are the main things to tweak here that could improve the results (at the cost of a longer registration time perhaps)? In the [ANTsPy docs](https://antspy.readthedocs.io/en/latest/registration.html) I could see that in the registration step I could tweak the _grad_step, flow_sigma, total_sigma, aff_sampling, syn_sampling_ and _reg_iterations_. For the transformation step I could tweak the _interpolator_.

Thank you in advance.

**Comment by cookpa** [comment]
With `type_of_transform='SyNCC'` you're doing affine and then SyN, each at subsampled resolution. 

I tried the most reproducible registration I could think of:

```
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
antsRegistration -d 3 -u 0 -v 1 \
   -t SyN[0.1] \
   -m Mattes[ MRI_4.nii , MRI_4.nii , 1, 64, Regular ] \
   -c [ 25, 1e-8 ,10 ] -f 1 -s 0 \
   -o [ MRI_4ToSelf, MRI_4ToSelfDeformed.nii.gz ] 
```   
   
Here I am using dense sampling, single threaded (avoids variability due to summation errors), at full resolution (no downsampling or smoothing). The raw image diffs are probably not the best metric of convergence. If there are sharp edges in the image, even a tiny displacement can make large changes in the output intensities after interpolation. The scale of the displacement (bottom right) is 0 - 0.005 mm.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/611507/140113451-418e8c89-3b83-46c5-8f45-7aca3687168c.png">

The correct solution should be 0 displacement, but convergence is assessed numerically, and all these computations have numerical errors. It only takes a slight gradient to peturb the deformation from zero. The deformation field itself is discretely sampled and smoothed, and the mutual information is computed on a histogram with a discrete number of bins.

**Comment by IlvaHou55** [comment]
@cookpa thank you for your reply. For reproducing this in ANTsPy, do I use the following parameters:

`grad_step=0.1` because of `-t SyN[0.1]` ?
`aff_sampling=64` and `syn_sampling=64` because of `-m Mattes[ MRI_4.nii , MRI_4.nii , 1, 64, Regular ]` ?
`reg_iterations=(25, 1e-8, 10)` because of `-c [ 25, 1e-8 ,10 ]` ?

In the [ANTsPy docs](https://antspy.readthedocs.io/en/latest/registration.html) it states: _we will set the smoothing and multi-resolution parameters based on the length of this_ (reg_iterations) _vector_ 
Does that mean I cannot tweak those parameters manually and not make sure that no smoothing and/or downsampling is applied?

Thank you.

**Comment by IlvaHou55** [comment]
@cookpa thank you for your reply. Now I am wondering how I can implement this using ANTsPy, so I will therefore open a new issue there.
