### ISSUE TITLE
Outermost coronal slices are not registered to fixed image

### ISSUE THREAD

**Issue by bfranx** [ANTsX/ANTs#1267]
Hi , I'm working with antsRegistration on preclinical MRI NIFTIs, so far everything runs like a breeze. However, for some reason the non-linear registration algo ignores the outer coronal slices of some smaller 3D volumes. Any idea what is causing this and how to force ANTs to process the outer slices?
Attached data my with output [here](https://surfdrive.surf.nl/files/index.php/s/RGrPuFc7fTbQZkr)

So I'm talking specifically about slice 1 and slice 5, the other slices in between look good.

Apologies in advance if this is a copy, my search came up with nothing

**To Reproduce**

antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [ B74_bolus-3tot2w-3_,B74_bolus-3tot2w-3_Warped.nii.gz,B74_bolus-3tot2w-3_InverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ]   --initial-moving-transform [ B74_t2w-3_bet_cut.nii.gz,B74_bolus-3_bet.nii.gz,0 ]  --transform BSplineSyN[0.1,15,0,1] -g 1x1x1  --metric CC[ B74_t2w-3_bet_cut.nii.gz,B74_bolus-3_bet.nii.gz,1,4 ] --convergence [ 1000x200,1e-8,10 ] --shrink-factors 2x1 --smoothing-sigmas 1x0vox 

(I'm skipping the affine transformation stage because the images already overlap well, the deformation is caused by the fact that the moving image is a gradient echo image. Rigid transform steps actually cause misregistrations due to poor contrast)

**System**
Ubuntu 20.04.3 LTS
Server

**ANTs version information**
ANTs Version: 2.3.5.dev219-gc73f4
Compiled: Mar  3 2021 10:26:08

Thanks in advance!

**Comment by cookpa** [comment]
I can't look at the data right now, but have you tried padding the images before registration? Something like 

```
ImageMath 3 padded.nii.gz PadImage input.nii.gz 20
```

The deformation field is constrained to be zero at the edges of the fixed image bounding box. So tissue right at the edge is sometimes not well registered.

**Comment by cookpa** [comment]
I looked at the data, I think a pad would help. But it's a challenging problem. You have dropout in addition to distortion at the edge slices. Also, the slice thickness is relatively large, so a 3D metric like CC (which uses a neighborhood of 4 voxels in all dimensions) may not be optimal.

You might get better results with `antsSliceRegularizedRegistration`. You would need to re-orient your data to do this, because it expects the slice direction to be along the z-axis. I do this with `c3d` (available with ITK-SNAP):

`c3d B74_t2w-3_bet_cut.nii.gz -orient LIP -o axialT2w.nii.gz`

**Comment by bfranx** [comment]
Thanks for your replies and recommendations!

As luck would have it, our server broke down yesterday. I'll get back on this ASAP.

**Comment by bfranx** [comment]
It's up and running again.

Thanks again for your suggestions. The padding of the image works and allows me to finish the pipeline, so I'm ready to close the issue.

However I'm now interested to hear what you think about the problem, so I was wondering if you had a few more pointers for me.

You are right that there are some challenges with this dataset, for example the signal dropout near the earholes (I don't care much for that slice though). An advantage with preclinical data is that I can be sure the slices from the same MRI session presented here (t2-weighted anatomical and t2* weighted gradient echo images) overlap pretty much exactly, as animals are anesthetized and fixed with a headbar, and therefore need no for translation / rigid registration. I assume all the other deformations are  are non-linear, due to MR physics. In my experience, affine registrations make things worse by causing excessive global scaling that blows distal slices out of proportion . I just did a few test runs on other samples and the non-linear registration looks looks quite good to me. Taking the above info into account, and that `antsSliceRegularizedRegistration` appears to be a low DOF linear registration tool, how can it help me achieve better registrations?

You make a good point about the SyN metric being 3D, it would be better if it was 2D (like fnirt), can I fix this by changing the radius to 1? I tried to look this up on the ITK Toolkit insight page but the documentation doesn't make much sense to me. Is there a manual that describes what each of the metrics and their parameters do?

**Comment by gdevenyi** [comment]
> and fixed with a headbar, and therefore need no for translation / rigid registration
From our experience doing similar similar, there's still a lot of possible wiggle room during loading that should be accounted for with a rigid registration. I don't have any specific suggestions for your other questions.

**Comment by cookpa** [comment]
You can certainly do `antsRegistration` in 2D. If you're sure that there is a correspondence between the slices, and you want to correct each slice independently with SyN or BSplineSyN, you can use `ExtractSliceFromImage` and then `antsRegistration -d 2`.

**Comment by bfranx** [comment]
Alright I will try these things, thank you both!
