### ISSUE TITLE
Update LabelGeometryMeasures to use improved ITK filter

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1269]
**Is your feature request related to a problem?**

Possibly,

https://discourse.itk.org/t/trying-to-access-labelgeometryimagefilter-in-itk-5-2-1-post1-python-package/4538/6

**Proposed new features**

Use updated new implementation

https://itk.org/Doxygen/html/classitk_1_1LabelImageToShapeLabelMapFilter.html

**Comment by ntustison** [comment]
Sounds like a good idea.  I didn't know the current version doesn't take into account image orientation information.  Do you want to make this change or would you like me to put it on my to-do list?

**Comment by cookpa** [comment]
I can do it. I did a little more exploring, it looks like it uses index space for some calculations

https://discourse.itk.org/t/labelgeometryimagefilter-not-using-physical-space/1566/3

**Comment by ntustison** [comment]
Thanks.  I don't think the changes should affect us to much as most usage, I would imagine, are the volume and surface area calculations which should be unaffected, the latter being a completely separate filter.

**Comment by cookpa** [comment]
@ntustison correct, it looks like you already replaced LabelGeometryImageFilter with LabelImageToShapeLabelMapFilter specifically for the surface area computation. I might actually need help as I can't understand this label map structure.

The rest of the stats apart from surface area still come from LabelGeometryImageFilter. The ShapeLabelObject provides elongation, centroid, bounds but not eccentricity. And it gets more complicated still once a grayscale image is involved. The Insight article says to use a [StatisticsLabelMapFilter](https://itk.org/Doxygen/html/classitk_1_1StatisticsLabelMapFilter.html) but I don't understand it as that appears to want a label image as input rather than a label map.

**Comment by ntustison** [comment]
Thanks @cookpa .  Now I remember making these changes.  Gaetan had originally written a really nice digital [perimeter estimation filter](https://www.insight-journal.org/browse/publication/852) which, if I remember correctly, was eventually integrated into the LabelObject framework and so I switched over.  I'm pretty sure I looked at moving everything over but it wasn't clear to me what the [equivalent calls were](https://itk.org/Doxygen410/html/classitk_1_1ShapeLabelObject.html) or what do with what appears to be additional measures, so I punted.   Perhaps we should create something like ``LabelGeometryMeasures2`` with the possibility of deprecating the original at some point.  What do you think?

**Comment by cookpa** [comment]
Makes sense. It's a lower priority than I first thought.

**Comment by cookpa** [comment]
Fixed by #1737
