### ISSUE TITLE
ANTS 2.3.5 super slow after 18.04 Ubuntu upgrade

### ISSUE THREAD

**Issue by anagrammarian** [ANTsX/ANTs#1271]
**Describe the problem**

I recently upgraded my old server from *gasp* 14.04 to 18.04. I then installed ANTs 2.3.5 Ecphorella from https://github.com/ANTsX/ANTs/releases. Whilst installing, compilation failed due to the MD5 suffix issue and I fixed that by adding -DBUILD_TESTING=OFF as suggested here https://github.com/ANTsX/ANTs/issues/1236.
When I ran my usual test code (this is my own thalamic segmentation code which has worked over multiple versions of python, ubuntu and ANTs, I noticed it was super slow even for the first rigid registration step (several minutes vs. seconds).

I checked the CPU usage using _htop_ and noticed many CPUs were idle. Then, when I set ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS to 16, it sped up a bit at least the CPUs were all cranking but it was still very slow (minutes vs. seconds)

As a sanity check, I did the following-
Ran the same registration using a docker container I had build months ago with 2.3.4 (the previous version) and it ran super fast like it used to (seconds)

Then I downloaded and recompiled ANTS 2.3.4 Dorymyrmex using the same -DBUILD_TESTING=OFF flag and it compiled fine. Now it also runs fast comparable to the docker version above.

While at the moment, I am happy it is back to how things used to be, I just thought I will report this strange behaviour with 2.3.5. Not sure what is going on as the ITK threads seem to be set OK. I don't believe 2.3.5 has any bug fixes that pertain to my code (I use antsRegistration not ANTS) but still wondering.

**To Reproduce**

**System information (please complete the following information)**

 - OS: Linux
 - OS version: Ubuntu 18.04
 - Type of system: Desktop

**ANTs version information**
 - ANTs code version: 2.3.5 (Ecphorella)
 - ANTs installation type: Built from source code here https://github.com/ANTsX/ANTs/releases/tag/v2.3.5

**Additional information**

The rigid command (from the python file) with cost set to MI was

cmd = 'antsRegistration -d 3 --float 0 --output rigid -t Rigid[0.1] -r [%s,%s,1]  --metric %s[%s,%s,1,32,None] --convergence [1000x500x250x100, 1e-6,10] -v -f 8x4x2x1 -s 3x2x1x0vox' % (fixed, moving, cost, fixed, moving)

**Comment by cookpa** [comment]
Thanks for the report.

I'm not sure the Ubuntu version is the cause, since it appears 2.3.4 works fine for you on 14.04 and 18.04.

My guess would be something about ITK thread handling changed, question is what could be affecting your system and not others.

When you say:

> I checked the CPU usage using htop and noticed many CPUs were idle. Then, when I set ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS to 16, it sped up a bit at least the CPUs were all cranking but it was still very slow (minutes vs. seconds)

what was ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS before? Was it unset, or set to something different than 16?

How many processors do you have on your system (`nproc --all`)?

**Comment by anagrammarian** [comment]
Yes, not ubuntu as 2.3.4 works thankfully.

I never explicitly set the ITK thread variable before. I can check inside the Docker container to see what it defaults to. I set it to 4 and then 16 in 2.3.5 (16 processors total). It was unset also.

**Comment by anagrammarian** [comment]
Thanks for trying this out. Hmm not sure why it is not using all the threads automatically like in 2.3.4. I am sticking to 2.3.4 for now as I have decided for other reasons to soon move to Ubuntu 20.04. Thanks

**Comment by cookpa** [comment]
No problem. I tried again with 8 threads (on a machine with 8 virtual cores), and no difference.

My speculative guess would be ITK refactoring that only becomes apparent at large numbers of threads. Possibly related to #1017 

Might also be data dependent, though.

**Comment by anagrammarian** [comment]
Except that it is super slow even during affine registration. What takes10 min took 2.5 hrs for the whole process. Mysterious and unknown/unsolved indeed !

**Comment by cookpa** [comment]
I was testing affine with the `-t a` option to `antsRegistrationSyNQuick.sh`. It took about 30 seconds total with 8 cores. 
The extreme nature of the slowdown suggests something specific to your machine or data.

I have 2.3.4 and 2.3.5 compiled locally and can run a test if you can share data and a runnable script.

You're not compiling in debug mode or something, are you? That will cause a big slowdown.
