### ISSUE TITLE
Stitching 2D transforms together for application on a 3D volume

### ISSUE THREAD

**Issue by bfranx** [ANTsX/ANTs#1272]
I have virtually no knowledge of ANTs inner workings, so please bear with me...

I'm working on a difficult registration problem: I have preclinical gradient-echo images with lots of distortion and signal dropout that I'm trying to register to a T2 anatomical using non-linear registration only. I've been dicing up the moving and fixed 3D volumes into individual coronal slices to perform sequential 2D registrations, as was proposed to me [here](https://github.com/ANTsX/ANTs/issues/1267#issuecomment-970473437). The results were interesting enough to try and work them into a pipeline. 

Data and code are [over here](https://surfdrive.surf.nl/files/index.php/s/zYKZlXBG5jnDJrG) (I've scripted in R and you'd need the RNifti package and ANTs on the command line to be able to replicate)

The results of elastic method BSplineDisplacementField look quite good, almost too good to be true. In any case, I tried to stitch the individual warps back into a 3D transform volume and test it on the original fixed image, and the output (*_test.nii.gz) looks nothing like the original *_Warped file (no matter which non-linear transform and metric I choose).

Am I doing something wrong or is it not possible to stitch transforms together like this? 
(bonus question: why is there no inverted warpfield output when using the elastic as opposed to diffeomorphic methods?)

Cheers,

Bart

**Comment by cookpa** [comment]
I'm not sure why it's necessary to try to concatenate the warps. Could you not do:

1. Split image into slices
2. for each slice i, antsRegistration -d 2 -i slice${i}.nii.gz -o [ slice${i}Warp, slice${i}Deformed.nii.gz ] ... (long form -o here is a short cut, alternatively call antsApplyTransforms -d 2)
3.  Combine slice${i}Deformed.nii.gz back into 3D image

**Comment by bfranx** [comment]
It's not so much about the *_Warped output, I need *_0Warp to be applicable on the original 3D volume, it has parametric maps associated to it.
I need the 3D transform to apply on masks from higher resolution modalities, align the fixed image to common template space, etc...

**Comment by cookpa** [comment]
OK. I think then you would be best to read the 2D warp fields into R, and write them into a 3D grid of 3D vectors. The warp vector **v2**=(x,y) in a voxel is stored in the physical space of the 2D image. Its representation in the physical space of the 3D image might be **v3**=(x,y,0) or (x,0,y) or something else, depending on how the slices are oriented.

**Comment by bfranx** [comment]
I've done that, but applying that newly 'stitched' warpfield produces unexpected results (see data and code). The dimensions of the stitched 3D transform (128x5x128x1x2) do not match the output from a regular 3D transform call (128x5x128x1x3), so I think I'm tyring to ask something of ANTs it cannot do.

No matter, I'm now working with an alternative approach that gives me acceptable results.
Thanks for your time!

**Comment by cookpa** [comment]
Yes, the 2D warp only has two components, you'd have to add the third yourself.
