### ISSUE TITLE
4D registration question

### ISSUE THREAD

**Issue by jimxin0218** [ANTsX/ANTs#1273]
Hello, I am trying to register a time series 4D image (224x224x28x119) to a 3D template (224x224x28) using 'antsRegistration'. My code posted in below. It always generated this error “Description: ITK ERROR: SmoothingRecursiveGaussianImageFilter(0x7fdbae82e710): The number of pixels along dimension 3 is less than 4. This filter requires a minimum of four pixels along the dimension to be processed.” 

Anyone may know the problem? Thanks in advance!

${ANTsPATH}/antsRegistration -d 4 \
                 -o ${outputimg} \
                 -r [${ctfix},${ctmov},1] \
                 -t BSplineSyN[0.2,14,0] \
                 -m CC[${ctfix},${ctmov},1,4] \
                 -c 20x5 \
                 -s 1x0 \
                 -f 2x1 \
                 -v 1 \
                 -x [${maskfixDilated},${maskfixDilated}]

**I ran a 'Printheader' of fixed and moving images, the results in below.** 

Spacing [1, 1, 2]
 Origin [-88.7812, 6.78125, 82.8]
 Direction 
1 0 0
0 -1 0
0 0 1

 Size : 224 224  28

  Image Dimensions   : [224, 224, 28]
  Bounding Box       : {[-88.7812 6.78125 82.8], [135.219 230.781 138.8]}
  Voxel Spacing      : [1, 1, 2]
  Intensity Range    : [-1024, 3071]
  Mean Intensity     : -357.556
  Direction Cos Mtx. : 
1 0 0
0 -1 0
0 0 1

  Voxel->RAS x-form  : 
  Image Metadata: 
    ITK_original_direction of unsupported type N3itk6MatrixIdLj3ELj3EEE
    ITK_original_spacing of unsupported type NSt3__16vectorIdNS_9allocatorIdEEEE
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    dim[0] = 3
    dim[1] = 224
    dim[2] = 224
    dim[3] = 28
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 1
    pixdim[2] = 1
    pixdim[3] = 2
    pixdim[4] = 0
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 1
    qform_code_name = NIFTI_XFORM_SCANNER_ANAT
    qoffset_x = 88.7812
    qoffset_y = -6.78125
    qoffset_z = 82.8
    quatern_b = -0
    quatern_c = 1
    quatern_d = 0
    scl_inter = 0
    scl_slope = 1
    sform_code = 0
    sform_code_name = NIFTI_XFORM_UNKNOWN
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = 0 0 0 0
    srow_y = 0 0 0 0
    srow_z = 0 0 0 0
    toffset = 0
    vox_offset = 352
    xyzt_units = 2
 Spacing [1, 1, 2, 1]
 Origin [-88.7812, 6.78125, 82.8, 0]
 Direction 
1 0 0 0
0 -1 0 0
0 0 1 0
0 0 0 1

 Size : [224, 224, 28, 119]

  Image Dimensions   : [224, 224, 28, 119]
  Bounding Box       : {[-88.7812 6.78125 82.8 0], [135.219 230.781 138.8 119]}
  Voxel Spacing      : [1, 1, 2, 1]
  Intensity Range    : [-1024, 3071]
  Mean Intensity     : -347.369
  Direction Cos Mtx. : 
1 0 0 0
0 -1 0 0
0 0 1 0
0 0 0 1

  Voxel->RAS x-form  : 
  Image Metadata: 
    ITK_original_direction of unsupported type N3itk6MatrixIdLj4ELj4EEE
    ITK_original_spacing of unsupported type NSt3__16vectorIdNS_9allocatorIdEEEE
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    dim[0] = 4
    dim[1] = 224
    dim[2] = 224
    dim[3] = 28
    dim[4] = 119
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 1
    pixdim[2] = 1
    pixdim[3] = 2
    pixdim[4] = 1
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 1
    qform_code_name = NIFTI_XFORM_SCANNER_ANAT
    qoffset_x = 88.7812
    qoffset_y = -6.78125
    qoffset_z = 82.8
    quatern_b = -0
    quatern_c = 1
    quatern_d = 0
    scl_inter = 0
    scl_slope = 1
    sform_code = 0
    sform_code_name = NIFTI_XFORM_UNKNOWN
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = 0 0 0 0
    srow_y = 0 0 0 0
    srow_z = 0 0 0 0
    toffset = 0
    vox_offset = 352
    xyzt_units = 2

**Comment by ntustison** [comment]
Thanks @jimxin0218 .  Why is your fixed image only 3-D?  If I'm not mistaken, it also needs to be 4-D.

**Comment by jimxin0218** [comment]
> Thanks @jimxin0218 . Why is your fixed image only 3-D? If I'm not mistaken, it also needs to be 4-D.

Thank you Nick! So i should change my fixed image to 224x224x28x1? How can I do this in ANTs?

**Comment by ntustison** [comment]
Is the objective to register all the 3-D volumes in your moving image to the single fixed 3-D volume?

**Comment by jimxin0218** [comment]
Yes. To do the motion correction.

**Comment by ntustison** [comment]
Did you look at ``antsMotionCorr``?

**Comment by jimxin0218** [comment]
Will check this out. Thank you again!
