### ISSUE TITLE
Warping additional subjects to previously built template

### ISSUE THREAD

**Issue by mvemaas** [ANTsX/ANTs#1274]
Dear all,

I used the BuildTemplateParallel script (30x50x20 iterations, Greedy SyN) to generate a template based on 100 individual scans derived from a MRI sequence focused on the brainstem. The output template looks very nice, and the individual images warped into the template space are properly deformed.

Now I have a few additional subjects that I would like to bring into the template space, but without re-generating a template from all data. I tried to simply use the antsRegistrationSyN script (with default options) to separately warp the new data to the existing template, but while it seems to work for part of the subjects, a few others are clearly mis-registered or 'corrupted' (e.g. blank image with negative values in the histogram).

I guess my overall question is the following: what would be the most appropriate way to 'mimick' the steps from the BuildTemplateParallel script and apply them to new data, but without going through the whole template generation again? 

Thank you very much in advance for your help,

Sincerely,
Maxime

**Comment by ntustison** [comment]
First, what are you using to visualize the results?

**Comment by mvemaas** [comment]
I observe the same misregistration with FSLeyes, SPM Display, or simply MRIcron

**Comment by ntustison** [comment]
A general rule is to always check ANTs results using ITK-SNAP.  ITK (and ANTs) often treat header information differently from FSL, SPM, etc.

**Comment by ntustison** [comment]
Okay, well at least we eliminated a common explanation.  In order to probe further, we're going to need more information.  ANTs is pretty robust for typical usage so simply stating that a few images are badly misregistered or corrupted is not sufficient to diagnose the issue.  [Please use the issue templates](https://github.com/ANTsX/ANTs/issues/939).

**Comment by cookpa** [comment]
Inside your template output directory, there should be files named job[...].txt that contain the ANTS command used to register the image to the template. 

If some images are failing badly, it's probably some issue with those images specifically. It could be a problem with the headers. Beware that `ANTS` and `antsRegistration` behave differently. The older buildtemplateparallel.sh script uses ANTS, which is no longer maintained. `antsRegistration` uses newer ITK implementations and has additional features.

To help further we'd need more details (as explained in the issue templates) and preferably access to the template and a problematic image, along with the exact command that is failing. 

See also

https://github.com/ANTsX/ANTs/wiki/Tips-for-improving-registration-results

**Comment by mvemaas** [comment]
Thanks for the inputs. 
I will gather the information and update you with a proper issue template as soon as possible.

**Comment by mvemaas** [comment]
Sorry for the delay in my reply. Please find below a more detailed/illustrated description of my issue:

**Describe the problem**
I am having unexpected registration outputs, e.g. complete mis-registration (screenshot 1), partial mis-registration/local deformation (screenshot 2), or 'corrupted' image (screenshot 3), when trying to register additional individual data to a previously built template focused on the brainstem (template generated with the BuildTemplateParallel script and based on 100 individuals, 30x50x20 iterations, Greedy SyN). All individual data come from a 7T magnetization transfer weighted MRI sequence with a FoV centered on the brainstem. I unfortunately cannot share the template image nor the individual images that are failing to register, sorry.

![Screenshot_1](https://user-images.githubusercontent.com/95347666/145382880-c573d8f2-40d1-4bf4-ad9c-243bfb4cf974.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/95347666/145382886-01be50a3-fcfe-47c4-9eeb-a6529c0f47ff.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/95347666/145382894-9b7f6e36-1008-4a4c-9058-8befbd1afb01.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/95347666/145382897-adb30aa8-2af9-4cbd-8206-7200210dbd7b.jpg)

Description of the screenshots: 
- Screenshot 1: The registered output for one individual (right image) is mis-placed at the top of the destination template (left image). The cursor position is the same between the two images. 
- Screenshot 2: The registered output (right image) is slightly misplaced/deformed compared to the destination template (left image). The cursor position is the same between the two images. The misplacement is particularly evident when looking at the 'brighter' spots for reference, but the whole brainstem boundaries appear distorted on the registered output.
- Screenshot 3: The registered output for another individual is a 'blank' image containing mostly zeros or negative values.
- Screenshot 4: Example of what could be considered as a correct registration output for another individual (right image)

**To Reproduce**
Command used: antsRegistrationSyN.sh -d 3 -n 6 -f Target_template -m Individual_image -o Output_image
Interestingly, when attempting to re-run the subject with 'blank' misregistration (i.e. subject from screenshot 3), I managed to get a correct output image. I therefore attach the verbose output from both the bad ('sub-XXX_Blank.log') and correct ('sub-XXX_Correct.log') registration process.

[sub-XXX_Blank.log](https://github.com/ANTsX/ANTs/files/7684388/sub-XXX_Blank.log)
[sub-XXX_Correct.log](https://github.com/ANTsX/ANTs/files/7684389/sub-XXX_Correct.log)

**System information**
Virtual machine OS: Ubuntu 18.04.6 LTS
Host system OS: Windows 10
Type of system: Desktop

**ANTs version information**
ANTs version: v2.3.5.post76-g28dd25c
ANTs installation type: compiled following the steps described here: https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

**Additional information**
Beside some potential inconsistencies in my registration outputs, may I ask again what steps would you recommend in order to properly register additional subjects to a template previously built with the BuildTemplateParallel script (e.g. should I use N4BiasFieldCorrection before registration if my template creation included it?).


Thank you very much for your help,

Maxime

**Comment by ntustison** [comment]
Okay, it's clearer why you are getting poor results.  This is a partial slab scenario for which we actually [have an example](https://github.com/ntustison/PartialSlabEpiT1ImageRegistration/blob/master/commandSyN.sh).  After performing a rigid alignment (using intensity-driven or landmark-based tools), deformable registration can be applied but only using the full image resolution (or only the top layers of the resolution pyramid).  Take a look at the parameters in the example, try them out on your data set and see if you get better results.

**Comment by cookpa** [comment]
It looks from the screen shots that this is a slab-to-slab registration like in #1267. It can be unstable because slices translated out of the FOV are disregarded by the registration, and because the deformation is constrained to be zero at the edges of the FOV. The "corrupted" image is the result of the moving image being shifted outside the FOV of the fixed image, and the missing voxels are filled in with a default value (usually 0). 

To alleviate these problems, you can try padding the images (see `ImageMath | grep PadImage`) and then using a mask (`ThresholdImage`) in the template space, which you pass to antsRegistration (-x). If possible, I would exclude the material outside the head, because the registration will attempt to align its features as well.

I would also recommend using only full-resolution or close to full-resolution (maybe -f 2x1 or just -f 1), as suggested in @ntustison's example. 

The usual way to initialize registration is by aligning the center of mass (-r [ fixed, moving, 1 ]). If your images are already well aligned in physical space by operator alignment of the FOV, you can try omitting this.
