### ISSUE TITLE
how to let antsRegistration pay more attention to low intensity regions

### ISSUE THREAD

**Issue by huangnick** [ANTsX/ANTs#1277]
Dear all,

I was trying to perform nonlinear registration between longitudinal images from the same subject. There are several changes in the brain, including brain atrophy, lesion growth/regression. I was interested in the lesion changes so I don't want to include nonlinear warps for these areas (nonetheless, warping neighboring voxels would certainly pull/push the lesion regions outward/inward). Unfortunately, it is quite difficult to accurately segment all the lesion regions so I can not rely on using masks to restrict registration.
As the lesions were all hyperintense compared to other tissues, so I think maybe I could do this by letting the method pay more attention to low-intensity regions. 
Do you have any suggestions on this issue? like how to weight areas with different intensity levels, choosing metrics, etc.

Best regards,
Peiyu

**Comment by gdevenyi** [comment]
Modifying the radius of the CC algorithm would probably be the first choice.

**Comment by huangnick** [comment]
> Modifying the radius of the CC algorithm would probably be the first choice.

Dear Gabriel, Thanks for your reply. I would try it. 
As the lesions are located in white matter, I was trying to use CSF masks to limit registrations, then perhaps the brain atrophy effect could be corrected, without imposing too much transformation in the white matter? But I'm not sure about how ANTS manipulates those regions outside the CSF mask. Apparently, the white matter needs to be pulled towards the ventricle during this process. Does ANTS evenly distribute the warping distance to voxels located on the line from the ventricle to sulcus?

**Comment by gdevenyi** [comment]
Personally, I would not be restricting the registration if these scans are from the same individual, the most accurate measure will be accounting for all changes.

After a successful registration you can post process the fields if there are things to account for.
