### ISSUE TITLE
--interpolation: command not found

### ISSUE THREAD

**Issue by pratham42** [ANTsX/ANTs#1278]
Hello, 

I am trying to run antsRegistration as:

antsRegistration \
        --verbose 0 \
        --random-seed 13 \
        --dimensionality 3 \
        --float 0 \
        --collapse-output-transforms 1 \
        --output [ ${subjid}_reg_0p9-to-0p8_,${subjid}_reg_0p9-to-0p8_Warped.nii.gz,1 ] \ 
        --interpolation BSpline[3] \
        --use-histogram-matching 1 \
        --winsorize-image-intensities [ 0.005,0.995 ] \
        --initial-moving-transform [${temp087},${temp097},1] \
        --transform Rigid[ 0.1 ] \
        --metric MI[ ${temp087},${temp097},1,64,Regular,0.25 ] \
        --convergence [ 250,1e-6,10 ] \
        --shrink-factors 1 \
        --smoothing-sigmas 0vox

which spits out an error

--interpolation: command not found

Can i know what am i missing??

**Comment by cookpa** [comment]
An extra backslash, or white space after the backslash, will cause the command to terminate and then the next arg will be treated as a new command.

**Comment by pratham42** [comment]
Got it!!
Thanks
