### ISSUE TITLE
Any methods to better the registration between T2* functional and T1 anatomical brain image 

### ISSUE THREAD

**Issue by younghoo** [ANTsX/ANTs#128]
Currently, the most common practice to register a T2\* functional MRI image to a T1 anatomical image seems to use 6 DOF rigid transformation, which at most times performs not well (I believe), probably (I guess) due to geometric distortion or signal loss during the acquistion process. So my problem is that are there any methods to better the matching between func and anat image in ANTs or ANTs' rigid transformation is better than that implemented in other software packages like FSL? or any related paper I can refer to?
Many thanks!

**Comment by sufkes** [comment]
I wonder if you could show an example of the actual calls, especially for the steps:
- rigidly register the images together - preferably t1 to bold
- register the two images together using syn with --restrict-deformation
1x1x0
There are so many options to set and I'm not sure I completely understand what you are suggesting.

**Comment by gdevenyi** [comment]
Please don't resurrect 6 year old threads. Examples are here: xanmod

**Comment by lmidriganciochina** [comment]
Hi, 
How would I call antsApplyTransforms to apply the transforms obtained from T1 to average_BOLD and T1 to Template , in order to apply these to the time series data? Would I have to replicate the displacement maps in 4D?

**Comment by WangRoss** [comment]
Does antsRegistrationSyN.sh or antsIntermodalityIntrasubject.sh include rigid registration? How does they call antsRegistration, what parameters?>

**Comment by cookpa** [comment]
antsRegistrationSyN.sh includes rigid registration by default; see the usage for options (-t). It will print the exact call to `antsRegistration` to the terminal.

**Comment by WangRoss** [comment]
Thanks, Cookpa.
My confusion is that is there twice rigid registration between fun and T1 images when the antsRegistration is called with SyN for distortion correct, following rigidly register the T1 to the BOLD space (step 1)?
