### ISSUE TITLE
distortion correction using antsIntermodalityIntrasubject.sh

### ISSUE THREAD

**Issue by christiane1708** [ANTsX/ANTs#1281]
Hi, 
I would like to use the method from the Wang paper (https://pubmed.ncbi.nlm.nih.gov/28270762/) for distortion correction of a DTI data set. As I am new to the ANTS toolbox I am not sure which template is required when using the antsIntermodalityIntrasubject script. I assumed that I need to create a template from the T1 data sets of my cohort of human subjects. Is this correct?

I then went on and started to create a template with antsMultivariateTemplateConstruction2. 
In the first step I only included 2 subjects to verify if the script would work. 
Unfortunately I get the following error while the script is running the SynRegistration:

Exception caught: 
itk::ExceptionObject (0x21f3c70)
Location: "void itk::ImageToImageFilter<TInputImage, TOutputImage>::VerifyInputInformation() [with TInputImage = itk::Image<itk::Vector<float, 3u>, 3u>; TOutputImage = itk::Image<itk::Vector<float, 3u>, 3u>]" 
File: /usr/include/ITK-4.7/itkImageToImageFilter.hxx
Line: 248
Description: itk::ERROR: ImageToImageFilter(0x23b3a30): Inputs do not occupy the same physical space! 
InputImage Origin: [1.2303952e+02, 1.4901731e+02, -3.4233576e+01], InputImage_1 Origin: [1.2303952e+02, 1.4901732e+02, -3.4233578e+01]
	Tolerance: 2.8000000e-06

This is the command I used:
./antsMultivariateTemplateConstruction2_cw_20211215.sh -d 3 -c 0 -r 1 -o newtemp *_anat_t1_ROBEX.nii.gz

Might the problem be related to the different dimensions of the input images? 

-system: ANTS (2.1.0-1~nd80+1) installed within the Oracle toolbox - NeuroDebian 8 64bit v3 from the ants for debian webpage (http://neurodebian.ovgu.de/pkgs/ants.html)

-Link to the T1 images and the error message: https://owncloud.gwdg.de/index.php/s/kEoyBoEo7DrmAAv

Many thanks for your help!

christiane

**Comment by ntustison** [comment]
This issue is discussed [here](https://github.com/ANTsX/ANTs/wiki/Inputs-do-not-occupy-the-same-physical-space).  I'm guessing it's an outdated script as the more recent version uses the proposed solutions to avoid running into this during template building.

**Comment by christiane1708** [comment]
Thanks a lot for the reply. 
Do you have a link to a recent version of ANTS for NeuroDebian? I have installed the current version from the debian webpage 
Debian GNU/Linux 8.0 (jessie) | 2.1.0~rc2+git3-g9103999-4 | 2.1.0-1~nd80+1 | i386, amd64.

**Comment by ntustison** [comment]
We don't coordinate at all with the NeuroDebian folk so you'd have to ask over there.

**Comment by christiane157** [comment]
We set up a new NeuroDebian version 8 machine and installed a current version of ANTS from the GitHub webpage (https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#get-the-latest-code)(https://github.com/ANTsX/ANTs/releases).

With this package I was able to create a template of 2 example subjects with antsMultivariateTemplateConstruction2.sh

Concerning my initial question of using antsIntermodlityIntrasubject.sh for distortion correction according to the pipeline introduced by the Wang et. al paper (https://pubmed.ncbi.nlm.nih.gov/28270762/) I found another issue on sourceforge where you already raised the critical point (https://sourceforge.net/p/advants/discussion/840261/thread/31e9196dcc/). According to this comment I 
1. performed a "simple" registration between the template created with antsMultivariateTemplateConstruction2.sh and the T1 image of a given subject with (antsRegistrationSyNQuick.sh -d 3 -f T1image -m TemplateImage -o QuickOut=prefix of T1 to template) and 
2. used the prefix of this output as the input of the -w option of the antsIntermodalityIntrasubject.sh script to perform the registration between the T1 image and the brain extracted and eddy and motion corrected B0 image of the DTI data (antsIntermodalityIntrasubject.sh -d 3 -i eddy_brainextracted_b0.nii.gz -r anat_t1_brain_bc_restore.nii.gz (brain extracted and bias corrected T1) -x anat_t1_ROBEX_mask.nii.gz (T 1 mask) -w QuickOut (prefix from output of step 1) -t 2 -o out)

for distortion correction between T1 and B0. After visual inspection that this worked fine I will now proceed with applying this transform to the whole DTI image data set.

Does this make sense to you?

**Comment by mblesac** [comment]
Hi,

I'm interested in this. I've been reading about this topic and I found that there are some pipelines that say that the registration should be restricted to the phase encoding direction. However, in the first paper mentioned in the topic, the authors don't same to do this. Any thoughts about why they don't do it?

Best regards,

Manuel

**Comment by christiane1708** [comment]
Hi Nick,

the antsMultivariateTemplateConstruction2.sh script worked fine. Unfortunately there was an unexpected power failure in our department and a not intended shut down of the computer during the last iteration of the long process during the last iteration and the script was interrupted. Is there a way to use the data acquired so far when restarting the process or will the script redo/overwrite all the steps that has been done so far? Many thanks for your help!

**Comment by ntustison** [comment]
The core outcome of the template building process is the template itself.   So if you have the last estimate of the template, you can continue the process by modifying the number of iterations to how many are left and using the ``-z`` option.

**Comment by christiane1708** [comment]
Hi Nick, this is very helpful!!! Great news!! Thanks

**Comment by christiane1708** [comment]
Hi all,

I was now able to perform the registration between the B0 image and the T1 image. However, I am not sure how to apply the transform between Bo and T1 to the whole DTI data set. I tried to use the -b option in the antsIntermodalityIntrasubject.sh script and included the eddy and motion corrected DTI data.

Command used: 
antsIntermodalityIntrasubject.sh -d 3 -i 001_eddy_b0.nii.gz -r 001_anat_t1_brain_bc_restore.nii.gz -x 001_anat_t1_ROBEX_mask.nii.gz -w t12templateTRY -t 2 -o outDTI0605 -b 001_eddy_out.nii.gz 

Unfortunately I get the following error:

DTI
+ [[ -f 001_eddy_out.nii.gz ]]
+ /home/brain/install/bin//antsApplyTransforms -d 3 -i 001_eddy_out.nii.gz -r 001_anat_t1_brain_bc_restore.nii.gz -t outDTI06051Warp.nii.gz -t outDTI06050GenericAffine.mat -n Linear -o outDTI0605dt_anatomical.nii.gz -e 2
Exception caught during reference file reading
 
itk::ExceptionObject (0x3d1a7c0)
Location: "unknown"
File: /home/brain/build/staging/include/ITK-5.2/itkConvertPixelBuffer.hxx
Line: 144
Description: ITK ERROR: No conversion available from 1 components to: 6 components
 
file 001_eddy_out.nii.gz
./antsIntermodalityIntrasubject_tryDTI_setx_20220506_3: line 338:  1752 Segmentation fault      ${ANTSPATH}/antsApplyTransforms -d $DIMENSION -i ${DTI} -r $ANATOMICAL_SPACE $warp -t ${OUTPUT_PREFIX}0GenericAffine.mat -n Linear -o ${OUTPUT_PREFIX}dt_anatomical.nii.gz -e 2
+ /home/brain/install/bin//antsApplyTransforms -d 3 -e 2 -i 001_eddy_out.nii.gz -r -n Linear -o outDTI0605dt_template.nii.gz -t t12templateTRY1Warp.nii.gz -t t12templateTRY0GenericAffine.mat -t outDTI06051Warp.nii.gz -t outDTI06050GenericAffine.mat
Exception caught during reference file reading
 
itk::ExceptionObject (0x3831ff0)
Location: "unknown"
File: /home/brain/build/staging/include/ITK-5.2/itkConvertPixelBuffer.hxx
Line: 144
Description: ITK ERROR: No conversion available from 1 components to: 6 components
 
file 001_eddy_out.nii.gz
./antsIntermodalityIntrasubject_tryDTI_setx_20220506_3: line 338:  1757 Segmentation fault      ${ANTSPATH}/antsApplyTransforms -d $DIMENSION -e 2 -i ${DTI} -r ${TEMPLATE} -n Linear -o ${OUTPUT_PREFIX}dt_template.nii.gz -t ${TEMPLATE_TRANSFORM}1Warp.nii.gz -t ${TEMPLATE_TRANSFORM}0GenericAffine.mat $warp -t ${OUTPUT_PREFIX}0GenericAffine.mat
+ /home/brain/install/bin//ImageMath 3 outDTI0605fa_template.nii.gz TensorFA outDTI0605dt_template.nii.gz
file outDTI0605dt_template.nii.gz does not exist .
./antsIntermodalityIntrasubject_tryDTI_setx_20220506_3: line 338:  1762 Segmentation fault      ${ANTSPATH}/ImageMath 3 ${OUTPUT_PREFIX}fa_template.nii.gz TensorFA ${OUTPUT_PREFIX}dt_template.nii.gz
+ /home/brain/install/bin//ImageMath 3 outDTI0605md_template.nii.gz TensorMeanDiffusion outDTI0605dt_template.nii.gz
file outDTI0605dt_template.nii.gz does not exist .
./antsIntermodalityIntrasubject_tryDTI_setx_20220506_3: line 338:  1763 Segmentation fault      ${ANTSPATH}/ImageMath 3 ${OUTPUT_PREFIX}md_template.nii.gz TensorMeanDiffusion ${OUTPUT_PREFIX}dt_template.nii.gz
+ [[ -f 001_anat_t1_ROBEX_mask.nii.gz ]]
+ /home/brain/install/bin//antsApplyTransforms -d 3 -i 001_anat_t1_ROBEX_mask.nii.gz -o outDTI0605brainmask.nii.gz -r 001_eddy_b0.nii.gz -n NearestNeighbor -t '[' outDTI06050GenericAffine.mat, 1 ']' -t outDTI06051InverseWarp.nii.gz
+ [[ -f '' ]]
++ date +%s
+ time_end=1651841773
+ time_elapsed=73
+ echo
 
+ echo --------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
+ echo ' Done with ANTs intermodality intrasubject processing pipeline'
Done with ANTs intermodality intrasubject processing pipeline
+ echo ' Script executed in 73 seconds'
Script executed in 73 seconds
+ echo ' 0h 1m 13s'
0h 1m 13s
+ echo --------------------------------------------------------------------------------------
------------------------------
