### ISSUE TITLE
Upsampling 4D images (ResampleImage)

### ISSUE THREAD

**Issue by pratham42** [ANTsX/ANTs#1283]
**My goal is to upsample datasets (both 3D and 4D). ResampleImage was able to upsample 3D data, but gave an error when i tried upsampling 4D data.

**Are there any solutions or alternatives for this?? **

The command i used was**

ResampleImage 4 BOLD_roi.nii.gz BOLD_roi_rs.nii.gz 0.2x0.2x0.2 0 4

and

ResampleImage 4 BOLD_roi.nii.gz BOLD_roi_rs.nii.gz 0.2x0.2x0.2 1 4

**and this was the error:**

terminate called after throwing an instance of ‘itk::ExceptionObject’
what(): /usr/local/build/staging/include/ITK-5.2/itkImageFileWriter.hxx:254:
itk::ERROR: itk::ERROR: ImageFileWriter(0x3432770): Largest possible region does not fully contain requested paste IO regionPaste IO region: ImageIORegion (0x7ffc34b78de0)
Dimension: 4
Index: 0 0 0 0
Size: 0 0 0 0
Largest possible region: ImageRegion (0x7ffc34b78e60)
Dimension: 4
Index: [0, 0, 0, 0]
Size: [0, 0, 0, 0]

**Thank you**

**Comment by ntustison** [comment]
If you're resampling in 4-D, you need to specify the appropriate 4-D parameters.  ``0.2x0.2x0.2`` contains only 3 elements.

**Comment by pratham42** [comment]
@ntustison tried 0.2x0.2x0.2x208  > 208 is the total slices. It worked but only 3 slices were resampled
The command was

ResampleImage 4 file1.nii.gz file_rs.nii.gz 0.2x0.2x0.2x208 0 4

**Comment by ntustison** [comment]
> ```
> ResampleImage 4 file1.nii.gz file_rs.nii.gz 0.2x0.2x0.2x208 0 4
> ```

If you look at the help information, this command indicates that you want to resample the input image with a spacing of 0.2 in the first three dimensions and a spacing of 208 in the fourth dimension (presumably the temporal dimension).  I assume that is *not* what you want.

**Comment by pratham42** [comment]
Got it, need to specify the TR for the fourth dimension.
