### ISSUE TITLE
Skull Stripping Too Aggressive -- fmriprep ants

### ISSUE THREAD

**Issue by keithcdodd** [ANTsX/ANTs#1284]
Not certain of best area to ask about this (here, NITRC? Somewhere else?). But I am running fmriprep on my data, which uses ANTS for skull stripping (among other things) and I have found for some of my data, the skull stripping is too aggressive (I assume due to subject motion) and leaves out large portions of the brain. According to fmriprep, the only options I can easily change with skull stripping would be the template, and if a random or fixed seed is used. 

I assume I should try another template for the skull stripping, but I admit I am struggling to find the correct templates, or what might be the best one. I am not even sure which template it is already using (says Nipype implementation of antsBrainExtraction.sh). I assume changing the template for skull stripping does not change the template for normalization, but not certain on that either.

Here is an image (below) of how skull stripping is currently looking for one of my subjects (pink is the skull strip I believe). Please let me know if I should be posting to some other forum or if more information is needed.

Thanks!
![skullstrippedsub](https://user-images.githubusercontent.com/61259563/149006306-5eb4b104-011a-4a1c-adcf-643dfd2951e0.png)

**Comment by ntustison** [comment]
Unfortunately, I don't know what template is being used in fmriprep, either.  However, if you look at our [cortical thickness paper](https://pubmed.ncbi.nlm.nih.gov/24879923/) you'll see the different templates used (Figure 2) and the guiding criterion was how similar the subject image is to the template.  Specifically, the defacing protocol was different between the data sets and so the templates reflected those differences.  It looks like no defacing protocol was employed for your data so I would probably try the MMRR (or Kirby) template which are available for download [here](https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436).  

Having said all that, though, our current go-to for brain extraction is the deep learning-based utilities in both ANTsPyNet (for Python) and ANTsRNet (for R).  This approach is much faster and more robust.
