### ISSUE TITLE
File location of itkNonLocalPatchBasedImageFilter.h/.hxx

### ISSUE THREAD

**Issue by KKnoernschild** [ANTsX/ANTs#1289]
I am currently looking through the code of itkWeightedVotingFusionImageFilter to look at metric calculation implementation for antsJointFusion. This code has an includes statement for itkNonLocalPatchBasedImageFilter.h, which I presume contains the methods to compute either Pearson's or MeanSquares calculation. I have looked everywhere in my repository for the itkNonLocalPatchBasedImageFilter, in my itk build, and on this git repository for a possible location to no avail.

I have however found a branch from another user that does contain the file: https://github.com/KevinScholtes/ANTsX/blob/master/Utilities/itkNonLocalPatchBasedImageFilter.h

Has the script been moved or am I overlooking something?

Thank you in advance for your help

**Comment by ntustison** [comment]
A portion of these patch-based classes (discussed [here](https://www.insight-journal.org/browse/publication/979)), including the file in question, was migrated to an [ITK remote module](https://github.com/ntustison/ITKAdaptiveDenoising) given its usage by other packages, such as FreeSurfer.

**Comment by KKnoernschild** [comment]
This is exactly what I was looking for, thank you
