### ISSUE TITLE
joint optimization for correcting time series

### ISSUE THREAD

**Issue by satra** [ANTsX/ANTs#129]
@stnava - the issue on motion parameters raised the following thought process:

the BOLD or DWI epi timeseries is a product of motion, field inhomegeneity, susceptibility, slice-acquisition order and other artifacts, field of view. the impact of these issues varies based on age, head coil and sequence used. yet for most part these are addressed separately in the field. while there exists one algorithm currently to rectify slice acquisition timing and motion together (roche et al.) nothing takes all of this into account. i think the ITK/ANTS registration framework could potentially be augmented to address all of the above issues simultaneously. would love to hear your thoughts on this.

**Comment by stnava** [comment]
much easier to do now with antsr and/or antspy.   recommend someone write pseudo-code for a recommended algorithm.
