### ISSUE TITLE
Build error Pop!_OS 21.10

### ISSUE THREAD

**Issue by greydongilmore** [ANTsX/ANTs#1291]
**When did the error occur?**

[X ] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: Pop!_OS
 - OS version: 21.10
 - Type of system: Desktop

**ANTs version**

master

**Build configuration and logs**

**Additional context**
[CMakeError.log](https://github.com/ANTsX/ANTs/files/7915406/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/7915407/CMakeOutput.log)

[build.log](https://github.com/ANTsX/ANTs/files/7915403/build.log)
[cmake.log](https://github.com/ANTsX/ANTs/files/7915404/cmake.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/7915405/CMakeCache.txt)

**Comment by cookpa** [comment]
I think it's related to your compiler. There is a fix in ITK

https://github.com/InsightSoftwareConsortium/ITK/pull/2618

and this will eventually be incorporated into ANTs, meanwhile I would try an earlier version of GCC.

**Comment by greydongilmore** [comment]
can confirm using GCC version 10.3 solved this issue
