### ISSUE TITLE
ITK cannot read nifti image

### ISSUE THREAD

**Issue by MostafaI** [ANTsX/ANTs#1294]
**The problem**
When I try to register images I get this error: 
Exception caught during reference file reading itk::ExceptionObject (0x558db62fe5a0)
Location: "unknown" 
File: ...../ANTs/antsbin/ITKv5/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx 
Line: 1972 
Description: itk::ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

**To Reproduce**
The whole problem is the itk version. When using SimpleITK Version: 2.1.1 (ITK 5.2) I get the same error when I try to read the image using python:  
SimpleITK.ReadImage(filename) or itk.imread(filename)

However downgrading the simpleitk version to 2.0.2 solves the problem. How can I implement this in ANTs? 

**System information**

 - OS: Ubuntu
 - OS version: 20.04.3 LTS (Focal Fossa)
 - Type of system: Desktop

**ANTs version information**
 - ANTs code version: 2.3.5.dev212-g44225

**Comment by ntustison** [comment]
Did you try reading it in with SimpleITK, immediately writing it to disk using SimpleITK, and then reading that file using ``ants.ImageRead``?

**Comment by MostafaI** [comment]
Yes. Didn't work. 

Note that `ants.imread()` (version 0.2.4) works fine and can read the image. However, antspy version 0.3.1 cannot read it and produces the same problem.

The problem is with ITK that ANTs uses. Newer versions of ITK have this bug while older version of ITK are fine. So the whole problem is with itk not ants. I want to force ants to use a specific version of itk (2.0.2) and this will solve the problem. I think the problem will be solved if I just download older version of ants that uses older version of ITK. Can I do that or force the new ants to use old version of ITK?

**Comment by ntustison** [comment]
Sure, you can try to do that and I'm guessing it would work.  Compile ITK separately and set the ``USE_SYSTEM_ITK`` option during the cmake makefile generation.  But you'd have to figure out which ITK version to use.

**Comment by cookpa** [comment]
What size are your voxels? This issue was found with small voxel sizes #1213 and has been fixed in ITK, but we haven't updated the ANTs ITK version to incorporate the fix yet.

If it's the same issue, you can avoid the problem by adding a qform transform to your NIFTI header.

**Comment by MostafaI** [comment]
Oh wow The problem is solved when I set qform_code to 1. @cookpa Thank you so much. 
I don't think my voxel size is that small; Spacing [0.695312, 0.695312, 0.5]. 

Here's the output of PrintHeader

Spacing [0.695312, 0.695312, 0.5]
 Origin [-177.652, -342.652, -358.5]
 Direction 
1 0 0
0 1 0
0 0 1

 Size : 512 512  644

  Image Dimensions   : [512, 512, 644]
  Bounding Box       : {[-177.652 -342.652 -358.5], [178.348 13.3477 -36.5]}
  Voxel Spacing      : [0.695312, 0.695312, 0.5]
  Intensity Range    : [-1024, 3070]
  Mean Intensity     : -539.95
  Direction Cos Mtx. : 
1 0 0
0 1 0
0 0 1

  Voxel->RAS x-form  : 
  Image Metadata: 
    ITK_original_direction of unsupported type N3itk6MatrixIdLj3ELj3EEE
    ITK_original_spacing of unsupported type St6vectorIdSaIdEE
    bitpix = 16
    cal_max = 0
    cal_min = 0
    datatype = 4
    dim[0] = 3
    dim[1] = 512
    dim[2] = 512
    dim[3] = 644
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 0.695312
    pixdim[2] = 0.695312
    pixdim[3] = 0.5
    pixdim[4] = 1
    pixdim[5] = 1`
    pixdim[6] = 1
    pixdim[7] = 1
    qform_code = 1
    qform_code_name = NIFTI_XFORM_SCANNER_ANAT
    qoffset_x = 177.652
    qoffset_y = 342.652
    qoffset_z = -358.5
    quatern_b = 0
    quatern_c = 0
    quatern_d = 1
    scl_inter = 0
    scl_slope = 1
    sform_code = 2
    sform_code_name = NIFTI_XFORM_ALIGNED_ANAT
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = -0.695312 -0 0 177.652
    srow_y = -0 -0.695312 0 342.652
    srow_z = 0 0 0.5 -358.5
    toffset = 0
    vox_offset = 352
    xyzt_units = 2

**Comment by cookpa** [comment]
Thanks. I suppose it's not strictly small voxels, the test that fails is on the determinant of the sform, and small voxels was just a straightforward way to trigger it in previous issues / tests.

I made a note of this error in the Wiki

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F
