### ISSUE TITLE
Resampling binary masks

### ISSUE THREAD

**Issue by pratham42** [ANTsX/ANTs#1296]
Hello All,

My aim is to resample some masks to a higher resolution. I tried using ResampleImage and it works fine, but the surface of the mask is patchy and rough with holes and bubbles which were not present in the initial version of the mask. I used this 

ResampleImage 3 file.nii file.nii 0.2x0.2x0.2 0 4 (Bspline) >> which gave out a horrible version of the mask.

Hence I did this:

antsApplyTransforms -d 3 -n GenericLabel -r file01_rs.nii.gz -i file02.nii.gz -o file02_rs.nii.gz -t identity -v 1 >> which produced better version than the previous command. (screenshot attached)

Is there any solution which can resample my masks without compromising the surface texture of the mask??

Thank you and Best Regards,
Prathamesh

![image](https://user-images.githubusercontent.com/72960560/151308183-233e6b46-5be2-4306-8a94-e8affe066f4f.png)

**Comment by cookpa** [comment]
After resampling with `ResampleImage`, your mask is no longer binary unless you use NN interpolation. You should look at the resampled mask as a scalar overlay, not a segmentation image, and decide how best to restore the binary segmentation. 

In `antsApplyTransforms`, the GenericLabel interpolation independently resamples each label into the fixed space with linear interpolation. The interpolated label the maximum probability in a voxel is the final label for that voxel. In the binary case, this should be equivalent to resampling with linear interpolation and then thresholding at 0.5.
