### ISSUE TITLE
Paper of 3D rigid registration using MI to reference

### ISSUE THREAD

**Issue by BarryLiu97** [ANTsX/ANTs#1298]
Hi, I'm using ANTsPy' 3D rigid registration based on MI, and I want to describe the algorithm of it and reference related paper.
Which paper should I reference when using 3D rigid registration based on MI?

Thank you
Barry

**Comment by ntustison** [comment]
For ANTs-based registration, I would use either one of the following papers:

* https://pubmed.ncbi.nlm.nih.gov/20851191/
* https://pubmed.ncbi.nlm.nih.gov/24817849/

**Comment by BarryLiu97** [comment]
Thanks a lot. I'm not sure whether the algorithm of rigid registration in ANTs is consistent with what I know.
Is the picture describe the workflow of the registration in ANTs?
![image](https://user-images.githubusercontent.com/65115609/151457476-c4c00305-5b0c-4add-9dbc-1cb8d13bdc7a.png)

**Comment by ntustison** [comment]
Yes.

**Comment by BarryLiu97** [comment]
Thanks a lot!
