### ISSUE TITLE
DKT Parcellation on an already skull stripped data set?

### ISSUE THREAD

**Issue by Jeffotter** [ANTsX/ANTs#1300]
Hi, I am very new to all this and might have somewhat of a novice question. I am attempting to DKT parcellate a brain from a well-known ANDI Dataset in python. I understand that the preprocessing for the Desekan_Killany_Tourville function uses "croppedMni152" to aid in registration during its preprocessing. Is it wrong for me to utilize this preprocessing on an already skull-stripped data set? Or does the Ants account for this? Thank you in advance!

**Comment by cookpa** [comment]
Please post this issue to the ANTsPy page

https://github.com/ANTsX/ANTsPy/issues

**Comment by ntustison** [comment]
Probably the better option is ANTsPyNet where the function resides

https://github.com/ANTsX/ANTsPyNet/issues

**Comment by cookpa** [comment]
Thanks Nick.

**Comment by cookpa** [comment]
I guess I should update the issue templates to help people find the correct forum.

**Comment by Jeffotter** [comment]
Thank you, will do
