### ISSUE TITLE
antsJointFusion memory use

### ISSUE THREAD

**Issue by C-Willard** [ANTsX/ANTs#1306]
**Describe the problem**

I'm trying to run antsJointFusion, but the process is killed due to memory use. 
When running antsJointFusion on an MRI scan (256 x 320 x 320) the antsJointFusion command requires more than 16GB of memory and is killed (observing the system memory use whilst running the command, the memory use increases to 16GB (100%) before the antsJointFusion process is killed). Adding a mask (-x) does not reduce this memory requirement. Cropping the scan in half to (128 x 320 x 320) will result in a successful completion (and the memory use of this does not seem to change whether or not a mask is used). 

Is there any way to reduce the memory requirements of the antsJointFusion command without cropping?

**To Reproduce**

command: 
antsJointFusion -v 1 -d 3 -t t1.nii.gz -o jlf.nii.gz -v 1 -x mask.nii.gz -g registered_atlas_1.nii.gz -l label_1.nii.gz -g registered_atlas_2.nii.gz -l label_2.nii.gz

output:
Running antsJointFusion for 3-dimensional images.

Killed

**System information (please complete the following information)**

OS: Ubuntu
OS Version: 20.04.2 LTS (Focal Fossa)
Type of system: cloud instance 

Memory: 16GB

**ANTs version information**

ANTs Version: 2.3.5.dev246-ga7eca
Compiled: Jul  2 2021 11:27:47

**Comment by ntustison** [comment]
Those images are fairly large and since all images are loaded into memory during processing, there isn't anything you can do if you don't want to crop.

**Comment by cookpa** [comment]
Do you have a lot of atlases?

The mask will reduce CPU time, because the joint fusion algorithm won't be run outside the mask. But it won't reduce memory use.

**Comment by C-Willard** [comment]
Thanks for your replies, the process is killed when using only 2 atlases.

If it helps, I have attached .txt files with header information for the files used.

[label_1_hdr.txt](https://github.com/ANTsX/ANTs/files/8023235/label_1_hdr.txt)
[label_2_hdr.txt](https://github.com/ANTsX/ANTs/files/8023236/label_2_hdr.txt)
[mask_hdr.txt](https://github.com/ANTsX/ANTs/files/8023237/mask_hdr.txt)
[registered_atlas_1_hdr.txt](https://github.com/ANTsX/ANTs/files/8023238/registered_atlas_1_hdr.txt)
[registered_atlas_2_hdr.txt](https://github.com/ANTsX/ANTs/files/8023240/registered_atlas_2_hdr.txt)
[t1_hdr.txt](https://github.com/ANTsX/ANTs/files/8023241/t1_hdr.txt)

**Comment by cookpa** [comment]
I don't see any clues there. Do you have a very large number of labels? 

I could try to reproduce if you can post data.
