### ISSUE TITLE
Registration between two volumes produces distorted, cut off output 

### ISSUE THREAD

**Issue by kyleo05** [ANTsX/ANTs#1307]
**Describe the problem**

I am attempting to perform a nonlinear registration between to volumes. One is a DTI atlas created with MRTRIX, the other is a synthetic atlas of structural MRI images created using ANTS. When I run registration, both output volumes are highly distorted and seem cropped, with only small parts of the image showing. 

**To Reproduce**

The following is the script as run. The commandline output was quite terse, showing only a "Registering..." line with the names and file paths of the two volumes. I attempted to add a "--verbose" flag, but this returned a "command not found". 

${ants_bin}/antsRegistration \
-d 3 \
-m MI[$base,$match,1,100,Random,.02] \
-t Affine[.01] \
-c [500x500x50,1e-8,20] \
-s 4x2x1vox \
-f 3x2x1 \
-l 1 \
-m CC[$base,$match,1,4] \
-t SyN[0.25] \
-c [50x50x50, 0, 5] \
-s 1x0.5x0vox \
-f 4x2x1 \
-l 1 \
-u 1 \
-z 1 \
-o [$out_dir]
-verbose 1

${ants_bin}/antsApplyTransforms -d 3 \
-i $match \
-o ${out_dir}match_to_base.nrrd \
-r $base \
-t ${out_dir}1Warp.nii.gz \
-t ${out_dir}0GenericAffine.mat

${ants_bin}/antsApplyTransforms -d 3 \
-r $match \
-o ${out_dir}base_to_match.nrrd \
-i $base \
-t [${out_dir}0GenericAffine.mat,1] \
-t ${out_dir}1InverseWarp.nii.gz
-verbose 1

**System information (please complete the following information)**

 - OS: [e.g. Mac OS]
 - OS version: [e.g. 10.15.1]
 - Type of system: [Desktop, laptop, HPC cluster, cloud instance,
   other]

The registration was run in a Putty terminal on a Windows 10 machine (Windows version 10.0.19041.1415), connected to a Linux HPC cluster running openSUSE Leap 15.3 w/ kernel Linux 5.3.18-59.34-default

**ANTs version information**
 - ANTs code version: [output of antsRegistration --version]
 - ANTs installation type: [Compiled from source, downloaded binary
   (from where?), installed by another package (which?), installed in
   container (URL?), other (please specify)]

ANTs Version: 2.1.0.post734-gf8bcb
compiled from source 

**Additional information**

Please see the link below for the two volumes in question, as well as the output files produced by ANTS. 
https://uofu.box.com/v/ANTSreg-files-share

I appreciate any help or advice in resolving this issue! I am new to ANTS and still learning how it works.

**Comment by ntustison** [comment]
I'm unable to access the files.

**Comment by ntustison** [comment]
Okay, what would be most helpful if you provided a *complete* working example.  Please provide the fixed and moving image and a script which reproduces the issue.

**Comment by kyleo05** [comment]
The fixed and moving images are in the shared folder (allpatients_wmnull_atlas_adjusted.nii.gz and wmfod_tempalte_h.nii.gz, respectively). 

The registration is being performed using the following function (function and definition below) which points to the ANTS script I pasted in my original post. I believe that's everything, but please let me know if there is any additional information that would be helpful in troubleshooting. Thanks!

butson_py.registration.ants_match_to_base(ants_bin,
                                        in_dir	+ "allpatients_wmnull_atlas_adjusted.nii.gz",
                                        in_dir + "wmfod_template_h.nii.gz",
                                        out_dir,
                                        ants_script, 8, mask_fi=None)



def ants_match_to_base(ants_bin, base_fi, match_fi, out_dir, ants_script, cores, mask_fi=None):

    '''
    function to calls ants scripts to do image registration. Outputs transform(s) that moves match image to
    base image and match to base file and base to match file
    ants_scripts that can be used are located in Butson_Lab/butson_py/butson_py/scripts/ants_scripts.
    ANTs scripts that you want to write should be compatible with this syntax.


    '''
    ants_script = os.path.join(os.path.dirname(__file__), "scripts/ants_scripts", ants_script)

    os.environ['ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS'] = str(cores)
    os.environ['match'] = match_fi
    os.environ['base'] = base_fi
    os.environ['ants_bin'] = ants_bin
    if mask_fi:
        os.environ['mask1'] = mask_fi
        os.environ['mask2'] = mask_fi
    else:
        os.environ['mask1'] = base_fi
        os.environ['mask2'] = match_fi


    matchRoot = os.path.splitext(os.path.split(match_fi)[1])[0]
    baseRoot = os.path.splitext(os.path.split(base_fi)[1])[0]

    transPrefix = matchRoot + "_to_" + baseRoot

    transPrefixFull = os.path.join(out_dir,
            transPrefix)

    os.environ['out_dir'] = transPrefixFull


    print("Registering " + match_fi +
            " to " + base_fi)

    subprocess.call(ants_script, shell = True)

**Comment by ntustison** [comment]
I don't know where you got your parameters for ``antsRegistration`` but I would start with some of the scripts that we provide, e.g., ``antsRegistrationSyNQuick.sh``.  Part of the screen dump is the actual ``antsRegistration`` call and you're probably better off starting with those parameters.

When I run 

```
antsRegistrationSyNQuick.sh -d 3 -f allpatients_wmnull_atlas_adjusted.nii.gz -m wmfod_template_h.nii.gz -n 8 -o test -t s
```

I get something reasonable considering the quality of the images.  

A couple issues:

* The template and atlas don't match well outside the brain.  You might want to try brain extracting your data first.
* The posterior portion of the structural template is cut off so you might want to fix that. 
*  The anatomical orientation is flipped Anterior <---> Posterior.  That's probably something you want to avoid.
