### ISSUE TITLE
antsRegistrationSyN - 32 moving images to 1 fixed images

### ISSUE THREAD

**Issue by marivas-MRI** [ANTsX/ANTs#1308]
Dear ANTs experts, 

I want to register 32 moving images towards 1 fixed image. For that purpose, I created a 4D.nii file and applied this command:

antsRegistrationSyN.sh -d 3 -f t1_15217.nii -m 4D.nii -t r -o reg_

However, this rigid registration only created one image instead of 32 images coregistered to the fixed image. How can I register multiple moving images towards one fixed image?

Thank you very much in advance and apologies for asking this basic question. I am a beginner in neuroimaging preprocessing. 

Best regards,

**Comment by ntustison** [comment]
Why not do a separate 3-D registration for each of the 32 images?

**Comment by marivas-MRI** [comment]
Thank you for your reply!. Yes, I also tried to run the following for loop to conduct registration in several subjects but it gave me this error:

**Number of fixed images is not equal to the number of moving images.**


#!/bin/bash

subjects="
15217
15233"

mov_images="
_Multi_echo_01_M.nii
_Multi_echo_02_M.nii
_Multi_echo_03_M.nii
_Multi_echo_04_M.nii
_Multi_echo_05_M.nii
_Multi_echo_06_M.nii
_Multi_echo_07_M.nii
_Multi_echo_08_M.nii
_Multi_echo_09_M.nii
_Multi_echo_10_M.nii
_Multi_echo_11_M.nii
_Multi_echo_12_M.nii
_Multi_echo_13_M.nii
_Multi_echo_14_M.nii
_Multi_echo_15_M.nii
_Multi_echo_16_M.nii
_Multi_echo_17_M.nii
_Multi_echo_18_M.nii
_Multi_echo_19_M.nii
_Multi_echo_20_M.nii
_Multi_echo_21_M.nii
_Multi_echo_22_M.nii
_Multi_echo_23_M.nii
_Multi_echo_24_M.nii
_Multi_echo_25_M.nii
_Multi_echo_26_M.nii
_Multi_echo_27_M.nii
_Multi_echo_28_M.nii
_Multi_echo_29_M.nii
_Multi_echo_30_M.nii
_Multi_echo_31_M.nii
_Multi_echo_32_M.nii
"



for subject in subjects

do

	for image in mov_images
	do

		antsRegistrationSyN.sh -d 3 -f ./t1/t1_${subjects}.nii -m ./multi_echo/${subjects}${mov_images} -t r -o ./output/${subjects}_reg_

	done

done



Best,
