### ISSUE TITLE
How to register brain images with lesions to standard space (lesion masks included)

### ISSUE THREAD

**Issue by Cometa98** [ANTsX/ANTs#1309]
Hi! 

I was going through the ANTs' documentation trying to figure out how to create a command to register brain images with lesions to standard space (lesion masks included). I would like to know which one of these versions is the correct to register the images: 

antsRegistrationSyN.sh -d 3 -f <MNI_standard_space> -m <strippedbrain> -o <output_MNI> -j 1 -x <inverted_lesion> 

or 

antsRegistrationSyN.sh -d 3 -m <MNI_standard_space> -f <strippedbrain> -o <output_MNI> -j 1 -x <inverted_lesion> 

As you can notice, the only difference is whether the moving image is the strippedbrain or the MNI space (and viceversa).

Thank you very much in advance!

**Comment by stnava** [comment]
There is no substitute for experimenting and looking at results when it comes to registration problems.   You should try both on several examples and see what you think.    This will help you think through how you've designed your solution and what these different calls mean.

Also, switch to`quick` so you don't have to wait too long to see results.

**Comment by Cometa98** [comment]
Okay, I really appreciate your answer. However, just to clarify, this is the correct option, or the one you would use right? : 

antsRegistrationSyN.sh -d 3 -m <MNI_standard_space> -f -o <output_MNI> -j 1 -x <inverted_lesion>

**Comment by Cometa98** [comment]
Okay, I really appreciate your help, however, and just to clarify, this is the option you would use right? 

antsRegistrationSyN.sh -d 3 -m <MNI_standard_space> -f <extracted_brain> -o <output_MNI> -j 1 -x <inverted_lesion>

**Comment by stnava** [comment]
if the lesion is in the fixed space, then yes.  some choose to estimate the lesion in the MNI space and then use the other approach.

**Comment by dorianps** [comment]
If that helps, there is a function for that in Lesymap, built on ANTsR.

https://github.com/dorianps/LESYMAP/blob/master/R/registerLesionToTemplate.R

**Comment by Cometa98** [comment]
Great, that is very helpful!!
