### ISSUE TITLE
Successfully compile and install ANTs by SuperBuild, but cannot import ants in the python script

### ISSUE THREAD

**Issue by mikami520** [ANTsX/ANTs#1310]
**When did the error occur?**

[ ] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: [e.g. Mac OS] 
    MacOS Monterey
 - OS version: [e.g. 10.15.1]
    Version 12.2.1
 - Type of system: [Desktop, laptop, HPC cluster, cloud instance,
   other]
   Laptop

**ANTs version**
latest ANTs 

**Build configuration and logs**

The ANTs is built and installed successfully, but cannot import when writing python scripts
**Additional context**

![Screen Shot 2022-02-23 at 20 10 39](https://user-images.githubusercontent.com/70731556/155437919-52c34491-583f-42c5-944f-e427d019c5a9.png)

**Comment by gdevenyi** [comment]
ANTs is not ANTspy, https://github.com/ANTsX/ANTsPy/
