### ISSUE TITLE
Skull-strip template image?

### ISSUE THREAD

**Issue by birkenstonks** [ANTsX/ANTs#1311]
Hello,

I tried running affine and deformable registration on some MRI images, but the results are very odd, and it seems pretty apparent it's because of the Template image I'm using. The template image is not skull-stripped, so the warped brain images are in the shape of the whole head. Should I skull-strip the template before using it in other commands?

![Warped](https://user-images.githubusercontent.com/66442660/156092421-59aea24f-8175-4372-aa1e-1a6dc3d1846b.png)

Template image: 
![template](https://user-images.githubusercontent.com/66442660/156092607-4c07526a-9dc8-43f1-9049-0120965b0f5f.png)

**Comment by ntustison** [comment]
>  Should I skull-strip the template before using it in other commands?

Yes.

**Comment by birkenstonks** [comment]
Ok. I'm planning to use antsBrainExtraction with the skull-stripped MNI152 image as a template for my own template. Is that a reasonable approach?

**Comment by ntustison** [comment]
Sure.  Try it and see.

**Comment by birkenstonks** [comment]
I tried but ran into a different issue...
<img width="375" alt="Screen Shot 2022-02-28 at 11 21 37 PM" src="https://user-images.githubusercontent.com/66442660/156104397-a49a5f02-a85e-420e-88cf-fbdde04cee2a.png">

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/Tips-for-improving-registration-results

You cannot, at any point, register a brain with skull to a brain without skull. If you want to transfer a brain mask from the MNI152 template to another, do:

1. Register MNI152 with skull to moving image with skull
2. Apply the warp to the MNI152 brain mask
3. Multiply the moving image by the deformed mask

**Comment by ntustison** [comment]
And to add to what @cookpa  said, the problem with your scenario is that whole-skull MNI doesn't really match with your whole-skull subject, specifically the heads are at different angles so your initial registration isn't likely to be adequate.  That's the key to doing brain extraction with this approach---use a template which has a similar appearance as your subject.  [Here](https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436) are some publicly available templates that we put together for [a paper](https://pubmed.ncbi.nlm.nih.gov/24879923/) that you should try.

**Comment by ntustison** [comment]
[Here](https://drive.google.com/drive/folders/0B4SvObeEfaRyaUlYZ1VueFlCSkU?resourcekey=0-QQfutO2aDb-ZcynbApeM2w&usp=sharing) are all the files associated with the ADNI template including the brain extraction mask (``T_template0BrainExtractionMask.nii.gz``).

**Comment by birkenstonks** [comment]
Hm I can't seem to find the T_template0BrainExtractionMask.nii.gz file. Thank you for sending those over!
