### ISSUE TITLE
ITK exception when using antsApplyTransforms on RHEL

### ISSUE THREAD

**Issue by gecthomas** [ANTsX/ANTs#1312]
**Describe the problem**

I am trying to run antsApplyTransforms to bring some magnitude images into a template space created from T1 images using buildtemplateparallel.sh

Moving magnitude images are first warped to T1 space, then brought in to template space in one call.
Outputs from buildtemplateparallel.sh and antsRegistrationSyN are used in the call to antsApplyTransforms.

However, the call is unsuccessful and no output images are written. Any advice on what might be going wrong would be much appreciated. Output of call is below: 

antsApplyTransforms --verbose 1 -d 3 -i QSM_v1.nii.gz -r T1template.nii.gz -o wQSM_v1 -n BSpline -t t12template_Warp_v1.nii.gz t12template_Affine_v1.txt magn2t1_v1_1Warp.nii.gz magn2t1_v1_0GenericAffine.mat
Using double precision for computations.
Input scalar image: QSM_v1.nii.gz
Reference image: T1template.nii.gz

The composite transform comprises the following transforms (in order): 
  1. magn2t1_v1_0GenericAffine.mat (type = AffineTransform)
  2. magn2t1_v1_1Warp.nii.gz (type = DisplacementFieldTransform)
  3. t12template_Affine_v1.txt (type = MatrixOffsetTransformBase)
  4. t12template_Warp_v1.nii.gz (type = DisplacementFieldTransform)

Default pixel value: 0
Interpolation type: BSplineInterpolateImageFunction
Output warped image: wQSM_v1
Caught an ITK exception: 

itk::ImageFileWriterException (0x3dfdb10)
Location: "unknown" 
File: /tmp/ANTs/build/ITKv5-install/include/ITK-5.0/itkImageFileWriter.hxx
Line: 148
Description:  Could not create IO object for writing file wQSM_v1
  Tried to create one of the following:
    BMPImageIO
    BioRadImageIO
    Bruker2dseqImageIO
    GDCMImageIO
    GE4ImageIO
    GE5ImageIO
    GiplImageIO
    HDF5ImageIO
    JPEGImageIO
    JPEG2000ImageIO
    LSMImageIO
    MGHImageIO
    MINCImageIO
    MRCImageIO
    MetaImageIO
    NiftiImageIO
    NrrdImageIO
    PNGImageIO
    StimulateImageIO
    TIFFImageIO
    VTKImageIO
  You probably failed to set a file suffix, or
    set the suffix to an unsupported type.

 /tmp/ANTs/source/ANTsX-ANTs-1d89092/Examples/antsApplyTransforms.cxx 729

**To Reproduce**

antsApplyTransforms --verbose 1 -d 3 -i QSM_v1.nii.gz -r T1template.nii.gz -o wQSM_v1 -n BSpline -t t12template_Warp_v1.nii.gz t12template_Affine_v1.txt magn2t1_v1_1Warp.nii.gz magn2t1_v1_0GenericAffine.mat

**System information (please complete the following information)**

 - OS: RHEL
 - OS version: 7.9
 - Type of system: Desktop

**ANTs version information**
 - ANTs code version: ANTs Version: 3.0.0.0
Compiled: Feb 13 2019 15:17:07
 - ANTs installation type: complied from source

**Additional information**

**Comment by ntustison** [comment]
Try adding ``-o -o wQSM_v1.nii.gz``

**Comment by ntustison** [comment]
The problem is that the IO mechanism doesn't know what file format you want without specifying a file suffix.

**Comment by gecthomas** [comment]
That has done the job, thank you!
