### ISSUE TITLE
Cannot read HDF5 transforms created with antsApplyTransforms

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1315]
**Describe the problem**

I'm trying to create HDF5 transforms from with `antsApplyTransforms`, but the files I create are not read successfully.

**To Reproduce**

```
antsApplyTransforms -d 3 \
  -i ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-01_atlas-Schaefer2018_desc-100Parcels7Networks_dseg.nii.gz \
  -t ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_from-MNI152NLin6Asym_mode-image_xfm.h5 \
  -r ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_desc-brain_T1w.nii.gz \
    -o mni2009cLabels.nii.gz --verbose 
```

This works successfully, using an existing .h5 file in templateflow. But if I try to make my own, it fails to read. For example:

```
antsApplyTransforms -d 3 \
-i ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-01_atlas-Schaefer2018_desc-100Parcels7Networks_dseg.nii.gz \
  -t ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_from-MNI152NLin6Asym_mode-image_xfm.h5 \
  -r ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_desc-brain_T1w.nii.gz \
  -o [ mni2009cFrom6.h5, 1 ]  --verbose 
```

appears to work but then

```
antsApplyTransforms -d 3 -i ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-01_atlas-Schaefer2018_desc-100Parcels7Networks_dseg.nii.gz -t mni2009cFrom6.h5 -r ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_desc-brain_T1w.nii.gz -o schaefer100x7_2009c.nii.gz --verbose
```

fails with

```
Using double precision for computations.
Input scalar image: /Users/pcook/tmp/NOT_BACKED_UP/templateflow/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-01_atlas-Schaefer2018_desc-100Parcels7Networks_dseg.nii.gz
Reference image: /Users/pcook/tmp/NOT_BACKED_UP/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_desc-brain_T1w.nii.gz

Transform reader for mni2009cFrom6.h5 caught an ITK exception:

itk::ExceptionObject (0x7fefca29b330)
Location: "unknown" 
File: /Users/pcook/tmp/NOT_BACKED_UP/antsMasterBuild/build/ITKv5/Modules/IO/TransformBase/src/itkTransformFileReader.cxx
Line: 128
Description: ITK ERROR: TransformFileReaderTemplate(0x7fefc86057e0): Could not create Transform IO object for reading file mni2009cFrom6.h5
  Tried to create one of the following:
    HDF5TransformIOTemplate
    HDF5TransformIOTemplate
    MatlabTransformIOTemplate
    MatlabTransformIOTemplate
    TxtTransformIOTemplate
    TxtTransformIOTemplate
  You probably failed to set a file suffix, or
    set the suffix to an unsupported type.


Can't read initial transform mni2009cFrom6.h5
```

And this happens with any warp I try to output as h5.

**System information (please complete the following information)**

 - OS: Mac OS
 - OS version: Big Sur
 - Type of system: Laptop

**ANTs version information**
 - ANTs code version: v2.3.5.post95-g6f07ac5
 - ANTs installation type: Compiled from source

**Comment by cookpa** [comment]
Thanks. I should add that `PrintHeader` reads the file correctly:

```
% PrintHeader mni2009cFrom6.h5 
 Spacing [1, 1, 1]
 Origin [96, 132, -78]
 Direction 
-1 0 0
0 -1 0
0 0 1

 Size : 193 229  193

  Image Dimensions   : [193, 229, 193]
  Bounding Box       : {[96 132 -78], [289 361 115]}
  Voxel Spacing      : [1, 1, 1]
  Intensity Range    : [-3.51691, 2.03663]
  Mean Intensity     : -0.190853
  Direction Cos Mtx. : 
-1 0 0
0 -1 0
0 0 1

  Voxel->RAS x-form  : 
  Image Metadata: 
    ITK_original_direction of unsupported type N3itk6MatrixIdLj3ELj3EEE
    ITK_original_spacing of unsupported type NSt3__16vectorIdNS_9allocatorIdEEEE
```

**Comment by gdevenyi** [comment]
I notice a lack of a command which shows how you're making your transforms, do you have an example of that?

**Comment by gdevenyi** [comment]
antsApplyTransforms only generates output transforms when run without an input doesn't it? Aren't you transforming 
`${TEMPLATEFLOW_HOME}/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-01_atlas-Schaefer2018_desc-100Parcels7Networks_dseg.nii.gz`

in your second command?

**Comment by cookpa** [comment]
It outputs transforms when given `-o [ transform, 1 ]` but you are correct, the `-i` part is superfluous. I forgot to take it out when I changed the command from transforming labels to outputting the transform.

But i still get the same error when I write the transforms without -i, 

```
antsApplyTransforms -d 3 \
  -t ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_from-MNI152NLin6Asym_mode-image_xfm.h5 \
  -r ${TEMPLATEFLOW_HOME}/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_desc-brain_T1w.nii.gz \
  -o [ mni2009cFrom6.h5, 1 ]  --verbose 
```

**Comment by cookpa** [comment]
A promising lead: a warp converted to h5 with SimpleITK works

```
>>> import SimpleITK as sitk
>>> reader = sitk.ImageFileReader()
>>> reader.SetFileName('subjectToTemplate1Warp.nii.gz')
>>> image = reader.Execute();
>>> disp = sitk.DisplacementFieldTransform(image)
>>> outFile = 'subjectToTemplate1Warp.h5'
>>> sitk.WriteTransform(disp, outFile)
```

**Comment by cookpa** [comment]
I think the problem is that `antsApplyTransforms` uses an image writer to write transforms, rather than a transform writer.

https://github.com/ANTsX/ANTs/blob/6f07ac55569d0d085d2adf7888d1c7a2bd563bfe/Examples/antsApplyTransforms.cxx#L571

This works for NIFTI images and produces HDF5 warps that are valid images (which can be read with PrintHeader), but the HDF5 warps are not valid ITK _transforms_ - hence why they will fail when read with `antsApplyTransforms` or `antsTransformInfo`.

Using a [TransformFileWriter](https://itk.org/Doxygen44/html/classitk_1_1TransformFileWriter.html) might work, but we'd have to be careful to check it is backwards compatible for NIFTI transforms.
