### ISSUE TITLE
Why `inverse transform` do not recunstruct excactly the same image data?

### ISSUE THREAD

**Issue by kondratevakate** [ANTsX/ANTs#1318]
Hi all! I want to resample images from the heterogeneous dataset to equal voxel spacing [1,1,1]. Yet I want to save the transformation to do `invtransform` and get **the same image** by  `np.allclose()` . How can I do that?

### 1. I found that if I will resample the image to the original spacing, I will not get the original image (it will be considerable MAE):
```

img = ants.image_read(test_path + 'T1.nii.gz')
img_res = ants.resample_image(img, (1, 1, 1), False, 4)
img_res_reverse = ants.resample_image(img_res, img.spacing, False, 4)
np.allclose(img_res_reverse.numpy(), img.numpy())
```
**False**
```
mae = np.sum(np.absolute(img_res_reverse.numpy() - img.numpy()))
mae, img_res_reverse.numpy().mean(),  img.numpy().mean()
```
**(1987788.2, 172.29662, 172.29372)**

### 2. I found, that if I will do it with `registration`, the error will be still huge:

```
img_res = ants.resample_image(img, (1, 1, 1), False, 0)
resample = ants.registration(fixed=img_res, moving=img, type_of_transform='Rigid')
img_res = ants.apply_transforms(img_res, img, transformlist = resample['fwdtransforms'][0])
img_res_reverse = ants.apply_transforms(img, img_res, transformlist = resample['invtransforms'][0])
mae = np.sum(np.absolute(img_res_reverse.numpy() - img.numpy()))
mae, img_res_reverse.numpy().mean(),  img.numpy().mean()
```
**(9012015.0, 172.40034, 172.29372)**

**Comment by gdevenyi** [comment]
Interpolation error during resampling causes changes to the data. This is why when resampling multiple transforms they should be composed together to apply all of them together.

**Comment by kondratevakate** [comment]
I see, but can you please help me - how to do the resampling transformation in ‘ants’ in order to get exactly the same image by appointing inverse transform?

**Comment by ntustison** [comment]
I will try but please post over at the appropriate repo.  The help that we provide is not just for the individual asking the question but also others with similar questions.

**Comment by kondratevakate** [comment]
Ok. I was not sure about the appropriate repo and started [the same thread in discussions.](https://github.com/ANTsX/ANTs/discussions/1321) 

Is it ok? Maybe you can navigate me if it is not.
