### ISSUE TITLE
Translation of padded region of interest to source fails /  antsApplyTransform won't read edited .mat file

### ISSUE THREAD

**Issue by bfranx** [ANTsX/ANTs#1319]
Hi,

I'm trying to register a region of interest that has been padded (outer slices are padded with zeroes) to the original source image. The job should be a simple translation in the y-direction but the result is consistently off by apparently one slice. I tried various metrics and convergence thresholds but it doesn't help. The problem here seems to be the padded slices because when I remove those the result looks fine, but I need them for non-linear warping further down the pipeline.

While the registration may be wrong, it seems to be _consistently_ wrong. So I hoped to fix the offset in the *0GenericAffine.mat after each registration call, adding 1 or 2 to the transform in the y-direction (tried in matlab and R), but now antsApplyTransform won't read the edited .mat.

Any idea what might be happening here and how to fix it?

I have some example data [here](https://surfdrive.surf.nl/files/index.php/s/4ak7Vi2RfAo0Al9).
*edit_0GenericAffine.mat is the manually edited .mat file that aAT can't read.

To Reproduce

`antsRegistration -v 1 -d 3 --float 0 --collapse-output-transforms 1 -o [ B20_t2w-1_bet_cut_padded_to_t2w-1_, B20_t2w-1_bet_cut_padded_to_t2w-1_Warped.nii.gz ] -n NearestNeighbor --use-histogram-matching 1  --initial-moving-transform [ B20_t2w-1_bet.nii.gz, B20_t2w-1_bet_cut_padded.nii.gz,0 ]  -t Translation[ 0.15 ] -g 0x1x0 --metric CC[ B20_t2w-1_bet.nii.gz, B20_t2w-1_bet_cut_padded.nii.gz,1,4,None,1 ] -c [ 150x100x75,1e-6,10 ] -f 3x2x1 -s 2x1x0vox`

`antsApplyTransforms -d 3 -r B20_t2w-1_bet.nii.gz -t [ B20_t2w-1_bet_cut_padded_to_t2w-1_edit_0GenericAffine.mat,0 ]  -n NearestNeighbor -i B20_t2w-1_bet_cut_padded.nii.gz -o test.nii.gz`

aAT error message:
Transform reader for /home1/bart/projects/study1-embolic/regfiles/B20_t2w-1_bet_cut_padded_to_t2w-1_edit_0GenericAffine.mat caught an ITK exception:

itk::ExceptionObject (0x5634131b1020)
Location: "unknown" 
File: /home1/bart/bin/ants/build/ITKv5/Modules/IO/TransformBase/src/itkTransformFileReader.cxx
Line: 144
Description: itk::ERROR: itk::ERROR: TransformFileReaderTemplate(0x5634131aea50): Transform IO: MatlabTransformIOTemplate
   failed to read file: /home1/bart/projects/study1-embolic/regfiles/B20_t2w-1_bet_cut_padded_to_t2w-1_edit_0GenericAffine.mat

System
Ubuntu 20.04.3 LTS
Server

ANTs version information
ANTs Version: 2.3.5.dev219-gc73f4
Compiled: Mar 3 2021 10:26:08

Thanks in advance!

**Comment by stnava** [comment]
how did you pad the image?

try: PadImage in ImageMath

brian

**Comment by bfranx** [comment]
The above is exactly how I padded

**Comment by stnava** [comment]
can you do the padding after you do the registration?   or at the point of
when you "need it"

brian

**Comment by bfranx** [comment]
Hi Brian, thanks for your suggestion, a sensible workaround.
You gave me the idea of nulling all irrelevant slices outside the region of interest in the source image, now the translation succeeds
