### ISSUE TITLE
The inverse ROI to subject space wont work

### ISSUE THREAD

**Issue by sKinreich** [ANTsX/ANTs#1322]
I  tried several ways that were suggested here and declared that it worked without success.
My aim was to define an ROI in structural atlas space and map it into the subject space.

My steps:
ROI- left thalamus
Atlas - MNI152_T1_1mm_brain

1. Mapping the subject structural brain into the atlas space. (1mm as the resolution of the subject structural)
1. antsRegistrationSyn.sh -d 3 -f MNI152_T1_1mm_brain.nii.gz -m ccc-00708-MPRAGE_brain.nii.gz –o subj2template

2. Create a left thalamus mask with the same atlas (MNI152_T1_1mm_brain)
   left_thalamus_1mm_thr.nii.gz

3. Using the inverse files created in step 1 and the mask file created in step 2 to create left thalamus mak (ROI2subj.nii.gz) fits for the subject space:
antsApplyTransforms -d 3 -i left_thalamus_1mm_thr.nii.gz -o ROI2subj.nii.gz  -r ccc-00708-MPRAGE_brain.nii.gz -t [subj2template0GenericAffine.mat,1] -t subj2template1InverseWarp.nii.gz -n NearestNeighbor

However, when I overlay the left thalamus mask created by the 3 step ( ROI2subj.nii.gz) in the subject space it doesn't cover the left thalamus.

Any help will be much appreciated !!!!!!

SK

**Comment by cookpa** [comment]
Does the template thalamus in `subj2templateInverseWarped.nii.gz` align well with the thalamus in `ccc-00708-MPRAGE_brain.nii.gz`?

**Comment by sKinreich** [comment]
This is the data

ROI- left thalamus
Atlas - MNI152_T1_1mm_brain

subject brain - ccc-00708-MPRAGE_brain.nii.gz

ROI left thalamus from the atlas - left_thalamus_1mm_thr.nii.gz

I understand that the output mask file from antsApplyTransforms (-o ROI2subj.nii.gz) is supposed to be the inverse

left thalamus to the subject space. Am I wrong ? But when I overlay it (ROI2subj.nii.gz) on the subject brain (ccc-00708-MPRAGE_brain.nii.gz)

It doesn't work

To your question

Does the template thalamus in subj2templateInverseWarped.nii.gz align well with the thalamus in ccc-00708-MPRAGE_brain.nii.gz?

What is the " template thalamus in subj2templateInverseWarped.nii.gz"

Thanks so much for this support!

Sivan



Sivan Kinreich, Ph.D.

Department of Psychiatry

Henri Begleiter Neurodynamics Laboratory

SUNY Downstate Medical Center

450 Clarkson Ave.

Brooklyn, NY 11203

Tel: 718-270-2231

       646-775-8509<tel:212-241-3638>

Email: ***@***.******@***.***>

           ***@***.***


________________________________
From: Philip Cook ***@***.***>
Sent: Thursday, March 17, 2022 12:59 PM
To: ANTsX/ANTs ***@***.***>
Cc: Sivan Kinreich ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ANTsX/ANTs] The inverse ROI to subject space wont work (Issue #1322)


External email

Do not click links, open attachments or provide your User ID or Password if the sender is unknown.


Does the template thalamus in subj2templateInverseWarped.nii.gz align well with the thalamus in ccc-00708-MPRAGE_brain.nii.gz?

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FANTsX%2FANTs%2Fissues%2F1322%23issuecomment-1071089488&data=04%7C01%7Csivan.kinreich%40downstate.edu%7Cb10c28d347cd4d63d58308da083780b0%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831331729632377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DqDOrTp4yA%2BdQ9%2BXcNJUBiu9xkT6sgUsZF31QgxUlDo%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATAILTBECXQ7FIUIATUXNDTVANQHDANCNFSM5Q4HQUPQ&data=04%7C01%7Csivan.kinreich%40downstate.edu%7Cb10c28d347cd4d63d58308da083780b0%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831331729632377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P82mkT2Y%2BT3EH04%2Bw%2FtjsPHlyP5RnfeXCa8DVL8rvMk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csivan.kinreich%40downstate.edu%7Cb10c28d347cd4d63d58308da083780b0%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831331729632377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cjN47%2FVGFzyoDoondoz8QRFcTocWV2F8L%2Bhb5qhdyAA%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csivan.kinreich%40downstate.edu%7Cb10c28d347cd4d63d58308da083780b0%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831331729632377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y368W6ZJ2t0%2BUNbEYDK8btIOmRTEt8mP1u0xPR0dMIQ%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

The contents of this email message and any attachments are confidential and are intended solely for the addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify sender by reply email or by (718) 270-HELP.

**Comment by cookpa** [comment]
If you ran

`antsRegistrationSyn.sh -d 3 -f MNI152_T1_1mm_brain.nii.gz -m ccc-00708-MPRAGE_brain.nii.gz –o subj2template`

You should see deformed images `subj2templateWarped.nii.gz` (in MNI space) and `subj2templateInverseWarped.nii.gz` (in subject space), which can be used to assess the registration accuracy.

**Comment by sKinreich** [comment]
I opened the subj2templateInverseWarped.nii.gz brain and the atlas brain (MNI152_T1_1mm_brain) and realized that they are in opposite direction (left right frontal occipital)

The original files (the atlas brain (MNI152_T1_1mm_brain) and the subject brain were in the same directions)

Thanks again, Sivan


Sivan Kinreich, Ph.D.

Department of Psychiatry

Henri Begleiter Neurodynamics Laboratory

SUNY Downstate Medical Center

450 Clarkson Ave.

Brooklyn, NY 11203

Tel: 718-270-2231

       646-775-8509<tel:212-241-3638>

Email: ***@***.******@***.***>

           ***@***.***


________________________________

**Comment by sKinreich** [comment]
I opened the subj2templateInverseWarped.nii.gz brain and the atlas brain (MNI152_T1_1mm_brain) and realized that they are in opposite direction (left right frontal occipital)

The original files (the atlas brain (MNI152_T1_1mm_brain) and the subject brain were in the same directions

To summarize:
open subj2templateInverseWarped.nii.gz with the output file from antsApplyTransforms (-o ROI2subj.nii.gz) it fits but on the opposite side ---> right instead of left.

open subj2template1Warp.nii (MNI space) with the original left thalamus --- > doesnt fit.


Thanks again, Sivan


Sivan Kinreich, Ph.D.

Department of Psychiatry

Henri Begleiter Neurodynamics Laboratory

SUNY Downstate Medical Center

450 Clarkson Ave.

Brooklyn, NY 11203

Tel: 718-270-2231

       646-775-8509<tel:212-241-3638>

Email: ***@***.******@***.***>

           ***@***.***


________________________________

**Comment by cookpa** [comment]
Sounds like a variety of possible issues. There's some resources in the Wiki for getting started with registration. Also if you can upload the data somewhere I will take a look. 

https://github.com/ANTsX/ANTs/wiki/Tips-for-improving-registration-results

**Comment by sKinreich** [comment]
Hi Philip,
Here is a link to My drive.
(let me know if you weren't able to see them)
There are   three 3 files over there:

https://drive.google.com/drive/folders/1tBDaohoMbOKmcNVVv02NENdnXOXsxe72?usp=sharing


  1.  The subject structural file
  2.  The Atlas I used to create the left thalamus ROI
  3.  The left thalamus ROI mask based on the atlas

The main aim is to transform the left thalamus ROI mask (based on the atlas) to the subject space
(to get left thalamus mask fits the subject space).

Thanks so much for your help!!!


Sivan Kinreich, Ph.D.

Department of Psychiatry

Henri Begleiter Neurodynamics Laboratory

SUNY Downstate Medical Center

450 Clarkson Ave.

Brooklyn, NY 11203

Tel: 718-270-2231

       646-775-8509<tel:212-241-3638>

Email: ***@***.******@***.***>

           ***@***.***


________________________________
From: Philip Cook ***@***.***>
Sent: Thursday, March 17, 2022 3:54 PM
To: ANTsX/ANTs ***@***.***>
Cc: Sivan Kinreich ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ANTsX/ANTs] The inverse ROI to subject space wont work (Issue #1322)


External email

Do not click links, open attachments or provide your User ID or Password if the sender is unknown.


Sounds like a variety of possible issues. There's some resources in the Wiki for getting started with registration. Also if you can upload the data somewhere I will take a look.

https://github.com/ANTsX/ANTs/wiki/Tips-for-improving-registration-results<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FANTsX%2FANTs%2Fwiki%2FTips-for-improving-registration-results&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C4fa70708a1cc4e6aa10f08da08500297%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831437003547975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hh%2F1DuXv3ibMGPuaaO8AfAwKDZP8Y0tFWml5zy%2Fu9rA%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FANTsX%2FANTs%2Fissues%2F1322%23issuecomment-1071313445&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C4fa70708a1cc4e6aa10f08da08500297%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831437003704221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oA23JMcBq01YaJga0zG5%2FfvUwJlbGKGOmXHvhhgTB%2F0%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATAILTGLYCKX3GW2MGDEYTLVAOEY7ANCNFSM5Q4HQUPQ&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C4fa70708a1cc4e6aa10f08da08500297%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831437003704221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2qH5548vEnd59g0BFFa31gb2S88ufZJZWvhJ1A7M5Zw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C4fa70708a1cc4e6aa10f08da08500297%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831437003704221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5gpnp39IC8zhqaBXxTYjKkJupooXKvso%2FrdZSvgW5T4%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C4fa70708a1cc4e6aa10f08da08500297%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831437003704221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dvUEpPtSAyhwko8JEDkXKkKHK6w4lYGns7UUdTUpvyE%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

The contents of this email message and any attachments are confidential and are intended solely for the addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify sender by reply email or by (718) 270-HELP.

**Comment by cookpa** [comment]
Thanks for the data. I think the problem is that your moving image has different information in the qform and sform, with both set to `NIFTI_XFORM_SCANNER_ANAT`.

I thought this was a bug but I'm not sure it is. The header contains contradictory information. ANTs / ITK ought to use the sform in this case, but other software might use the qform, and they don't produce the same transformation. So even if the registration worked, it might look incorrect in an image viewer.

I would recommend going back to the original DICOM if you can, converting with dcm2niix, and then using those NIFTIs. If you don't have DICOM but there is some way to verify that there's been no left-right orientation (eg fiducial markers before brain extraction), definitely check the image has not been flipped. 

That said, to make the moving image qform consistent with the current sform, you can do

`ImageMath 3 ccc-00708-MPRAGE_brain.nii.gz m ccc-00708-MPRAGE_brain_setQformFromSform.nii.gz 1`

This will overwrite the old qform with the values derived from the sform transform. After this, the registration should work.

To go the other way, you'd have to edit the headers manually somehow to set the sform_code to zero. I use RNifti for this kind of thing.

More NIFTI background info if you're interested

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

**Comment by sKinreich** [comment]
Thank you so so much !!!!!!!! it now seems to work.


Sivan Kinreich, Ph.D.

Department of Psychiatry

Henri Begleiter Neurodynamics Laboratory

SUNY Downstate Medical Center

450 Clarkson Ave.

Brooklyn, NY 11203

Tel: 718-270-2231

       646-775-8509<tel:212-241-3638>

Email: ***@***.******@***.***>

           ***@***.***


________________________________
From: Philip Cook ***@***.***>
Sent: Thursday, March 17, 2022 6:10 PM
To: ANTsX/ANTs ***@***.***>
Cc: Sivan Kinreich ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ANTsX/ANTs] The inverse ROI to subject space wont work (Issue #1322)


External email

Do not click links, open attachments or provide your User ID or Password if the sender is unknown.


Thanks for the data. I think the problem is that your moving image has different information in the qform and sform, with both set to NIFTI_XFORM_SCANNER_ANAT.

I thought this was a bug but I'm not sure it is. The header contains contradictory information. ANTs / ITK ought to use the sform in this case, but other software might use the qform, and they don't produce the same transformation. So even if the registration worked, it might look incorrect in an image viewer.

I would recommend going back to the original DICOM if you can, converting with dcm2niix, and then using those NIFTIs. If you don't have DICOM but there is some way to verify that there's been no left-right orientation (eg fiducial markers before brain extraction), definitely check the image has not been flipped.

That said, to make the moving image qform consistent with the current sform, you can do

ImageMath 3 ccc-00708-MPRAGE_brain.nii.gz m ccc-00708-MPRAGE_brain_setQformFromSform.nii.gz 1

This will overwrite the old qform with the values derived from the sform transform. After this, the registration should work.

To go the other way, you'd have to edit the headers manually somehow to set the sform_code to zero. I use RNifti for this kind of thing.

More NIFTI background info if you're interested

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FANTsX%2FANTs%2Fwiki%2FHow-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%253F&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C807c931907c849e452d808da0862e90f%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831518188062393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ee4Z266WB9ld2gpWIqdwwuEzHv7PeXJq2mz%2BX3hu%2FL8%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FANTsX%2FANTs%2Fissues%2F1322%23issuecomment-1071612625&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C807c931907c849e452d808da0862e90f%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831518188062393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TUEOBC4U0PTHuN%2BDupy%2F3SR3SN3FFXesqsGwJPbNf%2FM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATAILTDJK7VZYK3BTJZEUIDVAOUUJANCNFSM5Q4HQUPQ&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C807c931907c849e452d808da0862e90f%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831518188062393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=leo7uGXzkXJq1a2udRmbFSaejBabjapKNwdIAAS8uwA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C807c931907c849e452d808da0862e90f%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831518188062393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q211Q%2Bmo8JKI8ZbDJeFlOoHng5ZFpgA6ubN1OhI5FWo%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csivan.kinreich%40downstate.edu%7C807c931907c849e452d808da0862e90f%7C22670793760f482993153e427c362e69%7C0%7C0%7C637831518188062393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FvSQi1zo5Q84ZPgo9G7fe4jEQKmatLonOSeuB96k3kA%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

________________________________

The contents of this email message and any attachments are confidential and are intended solely for the addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify sender by reply email or by (718) 270-HELP.
