### ISSUE TITLE
Github security changes for git:// breaks SuperBuild

### ISSUE THREAD

**Issue by liamtimms** [ANTsX/ANTs#1323]
This issue should be a quick fix but currently running the ANTs SuperBuild results in the following:
```
 -- SuperBuild - ANTS => Requires VTK, ITKv5,
-- SuperBuild -   VTK[OK]
-- SuperBuild -   ITKv5[OK]
-- SuperBuild - ANTS[OK]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ripley/.cache/paru/clone/ants-git/src/ants-git/antsBuild
[  4%] Performing download step (git clone) for 'VTK'
Cloning into 'VTK'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

which is fairly self-explanatory. This change went into effect yesterday: 

> Last year, GitHub [announced](https://github.blog/2021-09-01-improving-git-protocol-security-github/) the deprecation of the unsecured Git protocol due to security reasons. This change will be made permanent on March 15, 2022.

https://blog.readthedocs.com/github-git-protocol-deprecation/

So the clone steps for ITKv5 and VTK are currently borked. That blog suggests simply changing to clone off `https://` rather than `git://`,  but I haven't tested it yet. 

**When did the error occur?**

[ ] CMake configuration (cmake / ccmake)
[ X] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: Linux (Arch)
 - OS version: rolling
 - Type of system: desktop
 

**ANTs version**

git master branch

**Comment by cookpa** [comment]
Thanks for letting us know. Does it work if you set ANTS_USE_GIT_PROTOCOL to OFF?

**Comment by liamtimms** [comment]
Yep, @cookpa, that option appears to bypass this (as might be expected).

**Comment by cookpa** [comment]
Great, time to make that the default then I think.
