### ISSUE TITLE
run in windows os

### ISSUE THREAD

**Issue by amirreza1998** [ANTsX/ANTs#1329]
hi 
is it possible to run ants in windows os 
i have program in python and in part of it i need to run ants in windows and use registration does ants have capability to run in windows ?

**Comment by gdevenyi** [comment]
Your best bet is to do things under WSL

**Comment by cookpa** [comment]
Yes, ANTs can be run in the Linux subsystem. I don't know of anyone building native Windows executables.

**Comment by cookpa** [comment]
Update: Windows binaries are attached to 2.4.4

https://github.com/ANTsX/ANTs/releases/tag/v2.4.4
