### ISSUE TITLE
Suggestions for improving a registration

### ISSUE THREAD

**Issue by kyleo05** [ANTsX/ANTs#1330]
Hello,

I am attempting to nonlinearly register a single brain image to a synthetic atlas created from a handful of brains. The registration of the outer boundaries comes out looking reasonable, but interior structures- specifically the thalamus- seem to be stretched outward in the moving brain image. The exact syntax I used to run the registration is as follows: 

antsRegistration -v -d 3 --float 0 --output 7t_wmn_to_template0_V2 --use-histogram-matching 1 -t Rigid[0.1] --metric Mattes[template0.nii.gz,wmnull_7t_in_wmnull_sv_t2space.nii.gz,1,32,None] --convergence [500x500x500x500x500,4e-7,10] -f 5x5x5x5x4 -s 1.685x1.4771x1.256x1.0402x0.82235mm -t Affine[0.1] --metric Mattes[template0.nii.gz,wmnull_7t_in_wmnull_sv_t2space.nii.gz,1,64, None] --convergence [450x150x50,1e-7,10] -f 3x2x1 -s 0.60056x0.3677x0mm -t SyN[0.4,3.0] --metric MI[template0.nii.gz,wmnull_7t_in_wmnull_sv_t2space.nii.gz,1,32,None] --convergence [200x200x90x50,1e-10,10] -f 4x3x2x1 -s 0.82x0.6x0.3677x0.0mm

I've also run this registration using antsRegistrationSyNQuick, with similar results (the thalamus in the moving brain being overly stretched along the left-right axis). My question is, how should I go about improving the registration of interior details of the brain? Is there a way I can increase sensitivity in the thalamic region to ensure a better match between the individual brain and the atlas image? Any advice is much appreciated! The two files in question are available at the link below. 

https://www.dropbox.com/sh/dmfu81l3r1r5bvb/AACRcTG6zuQLnOaPDswc1ySLa?dl=0

**Comment by kyleo05** [comment]
I do have a segmentation for the thalamus, as well as nuclei within it. Is there a way of using this to help the registration?

**Comment by ntustison** [comment]
You can include the segmentations as a fixed/moving image pair in an additional ``--metric``.  So, for example, in your deformable registration stage, you would have something like

```
$ antsRegistration \
...
-t SyN[0.4,3.0] \
--metric MI[template0.nii.gz,wmnull_7t_in_wmnull_sv_t2space.nii.gz,${weightIntensity},32,None] \
--metric MSQ[fixedMask.nii.gz,movingMask.nii.gz,${weightMasking}] \
...
```

**Comment by cookpa** [comment]
Some thoughts after looking at the images

1. Pad all the images. Images that are tightly cropped to the bounding box often have problems with deformable registration. For example, `ImageMath 3 padded.nii.gz PadImage input.nii.gz 20`

1. Improve the template. It looks like part of the head is cut off in the template space. Padding the inputs can help with this.

2. Try to reduce intensity bias. See `N4BiasFieldCorrection`. 

3. Consider different registration parameters. I'm not sure histogram matching is a good idea here. Also, Mattes, while much faster than CC, might not do as well for deformable registration. I would experiment by not doing any iterations at full resolution and only a few at the second level, until you are confident things are in the right direction.

**Comment by jaliladde** [comment]
Hello
I am working on fMRI images (4 dimension)
I want to register them on MNI template 
antregistration works very well on 3D, but when I want to apply the transformation on 4D image, it doesn't!
This my code:

**antsRegistration -d 3 -n BSpline -t Affine[0.1] -m MI[MNI152_T1_2mm, SBRef.nii.gz,1,32,Regular,0.25] -c [1000x500x250,1e-6,20] -s 4x2x1vox -f 3x2x1 -u 0 -z 1 -o [Aff_Trasfrm, WarpedImage.nii.gz, InvWarpedImage.nii.gz]

antsApplyTransforms -d 3 -e 3 -i EPI_Image.nii.gz -r WarpedImage.nii.gz
-o Aff_Reg_EPI.nii.gz -n BSpline -t Aff_Trasfrm0GenericAffine.mat -v 1**

Can anyone help ?

Regards

**Comment by gdevenyi** [comment]
Please don't randomly comment on old threads with copy and pasted comments

**Comment by ntustison** [comment]
Yes, please post as a new issue.  However, be sure to consult [this example](https://stnava.github.io/fMRIANTs/) before you do.
