### ISSUE TITLE
Denoise changing orientation

### ISSUE THREAD

**Issue by Nsk97** [ANTsX/ANTs#1337]
I have been using denoise from ANTs for a while now, but I have recently started analysing new data and for some reason with these subjects the denoising is changing the orientation of the scans.

Do you have any idea why this could be and how to fix the issue?

**Comment by cookpa** [comment]
If it's working normally for some data but not this new data, I think it's probably something about the new data. It might not be specific to `DenoiseImage`.

Can you share an example of data that changes orientation?

**Comment by ntustison** [comment]
Does the ITK IO change direction info during read/write from the perspective of an, eg, FSL user?

**Comment by Nsk97** [comment]
I’m not sure how to check this?
I have attached images showing the issue with 2 subjects from different sites.

Thank you,
Nathan

From: Nick Tustison ***@***.***>
Date: Wednesday, 13 April 2022 at 14:21
To: ANTsX/ANTs ***@***.***>
Cc: Nathan Kindred (PGR) ***@***.***>, Author ***@***.***>
Subject: Re: [ANTsX/ANTs] Denoise changing orientation (Issue #1337)

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

Does the ITK IO change direction info during read/write from the perspective of an, eg, FSL user?

**Comment by Nsk97** [comment]
That’s odd.
Thank you, I have pasted them below, before is first then after.

Spacing [0.5, 0.5, 0.5]
Origin [-64, 63.5, -49.2199]
Direction
1 0 0
0 -1 0
0 0 1

Size : 256 256  128

  Image Dimensions   : [256, 256, 128]
  Bounding Box       : {[-64 63.5 -49.2199], [64 191.5 14.7801]}
  Voxel Spacing      : [0.5, 0.5, 0.5]
  Intensity Range    : [0, 842666]
  Mean Intensity     : 54380.6
  Direction Cos Mtx. :
1 0 0
0 -1 0
0 0 1

  Voxel->RAS x-form  :
  Image Metadata:
    ITK_original_direction of unsupported type N3itk6MatrixIdLj3ELj3EEE
    ITK_original_spacing of unsupported type St6vectorIdSaIdEE
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    dim[0] = 3
    dim[1] = 256
    dim[2] = 256
    dim[3] = 128
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 0.5
    pixdim[2] = 0.5
    pixdim[3] = 0.5
    pixdim[4] = 0
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 1
    qform_code_name = NIFTI_XFORM_SCANNER_ANAT
    qoffset_x = 64
    qoffset_y = -63.5
    qoffset_z = -49.2199
    quatern_b = -0
    quatern_c = 1
    quatern_d = 0
    scl_inter = 0
    scl_slope = 1
    sform_code = 2
    sform_code_name = NIFTI_XFORM_ALIGNED_ANAT
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = -0.499375 0.0249896 0 60.4963
    srow_y = 0.0244914 0.489421 0.0993347 -69.8011
    srow_z = -0.00496471 -0.0992105 0.490033 -8.0486
    toffset = 0
    vox_offset = 2480
    xyzt_units = 2

Spacing [0.5, 0.5, 0.5]
Origin [-64, 63.5, -49.2199]
Direction
1 0 0
0 -1 0
0 0 1

Size : 256 256  128

  Image Dimensions   : [256, 256, 128]
  Bounding Box       : {[-64 63.5 -49.2199], [64 191.5 14.7801]}
  Voxel Spacing      : [0.5, 0.5, 0.5]
  Intensity Range    : [0, 780291]
  Mean Intensity     : 54033.1
  Direction Cos Mtx. :
1 0 0
0 -1 0
0 0 1

  Voxel->RAS x-form  :
  Image Metadata:
    ITK_original_direction of unsupported type N3itk6MatrixIdLj3ELj3EEE
    ITK_original_spacing of unsupported type St6vectorIdSaIdEE
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    dim[0] = 3
    dim[1] = 256
    dim[2] = 256
    dim[3] = 128
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
   dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 0.5
    pixdim[2] = 0.5
    pixdim[3] = 0.5
    pixdim[4] = 0
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 1
    qform_code_name = NIFTI_XFORM_SCANNER_ANAT
    qoffset_x = 64
    qoffset_y = -63.5
    qoffset_z = -49.2199
    quatern_b = -0
    quatern_c = 1
    quatern_d = 0
    scl_inter = 0
    scl_slope = 1
    sform_code = 0
    sform_code_name = NIFTI_XFORM_UNKNOWN
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = 0 0 0 0
    srow_y = 0 0 0 0
    srow_z = 0 0 0 0
    toffset = 0
    vox_offset = 352
    xyzt_units = 2

Thank you,
Nathan

From: Philip Cook ***@***.***>
Date: Wednesday, 13 April 2022 at 16:03
To: ANTsX/ANTs ***@***.***>
Cc: Nathan Kindred (PGR) ***@***.***>, Author ***@***.***>
Subject: Re: [ANTsX/ANTs] Denoise changing orientation (Issue #1337)

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

I don't think the attachment worked.

To check image orientation, you can use PrintHeader. If you can paste the output of PrintHeader before and after denoising, I will take a look.

**Comment by cookpa** [comment]
Thanks. I think you have a similar issue as #1322 - the header contains a valid qform and sform, and this often leads to confusion as some software will privilege one over the other.

From the output header, I see you are using an older version of ANTs, which uses the qform, and then overwrites the sform with zeros. As far as ITK has concerned, the image orientation has not changed. However, software which used the sform would notice the difference.

I don't know which transform is the correct one for your image, I would think qform since that has code NIFTI_XFORM_SCANNER_ANAT. 

If you update ANTs, I think qform would still be used, but the output would contain an equivalent sform with code NIFTI_XFORM_SCANNER_ANAT. The logic is complicated but I've tried to explain it here

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

One limitation of ITK's NIFTI I/O is that other header information (such as a transform to MNI space) cannot persist in the NIFTI headers. The header must contain a rigid transformation from voxel to physical space, and only one transform will be represented in any derived output.

**Comment by cookpa** [comment]
Just to be clear, this is an ITK I/O issue, and not about DenoiseImage specifically. You can see the same thing with  

`ImageMath 3 output.nii.gz m Input.nii.gz 1`

**Comment by Nsk97** [comment]
Thank you so much for your help, I’ll update ANTs and re-run to see if this fixes the issue.

Best wishes,
Nathan

From: Philip Cook ***@***.***>
Date: Wednesday, 13 April 2022 at 16:44
To: ANTsX/ANTs ***@***.***>
Cc: Nathan Kindred (PGR) ***@***.***>, Author ***@***.***>
Subject: Re: [ANTsX/ANTs] Denoise changing orientation (Issue #1337)

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

Just to be clear, this is an ITK I/O issue, and not about DenoiseImage specifically. You can see the same thing with

ImageMath 3 output.nii.gz m input.nii.gz 1
