### ISSUE TITLE
Mutual information of two identical images lower than two images of which one was registered

### ISSUE THREAD

**Issue by IlvaHou55** [ANTsX/ANTs#1340]
Hi everyone,

For my application I wanted to know the final mutual information after registration. I found that this value was very low (-0.069, which is actually 0.069). However, as mutual information is unbounded (i.e. there is no value that states 'perfect registration'), I wanted to compare it with the mutual information of two identical images. For this, I used the fixed image I used during the registration. For some reason the mutual information was even lower for these two identical images (-0.059 --> 0.059). Can someone explain me why this is possible? 

Thank you!

**Comment by ntustison** [comment]
The MI metric also considers the information content of the individual images.  An identical pair of blank images will have a different MI value than an identical pair of images with content.

**Comment by IlvaHou55** [comment]
Thank you @ntustison. I see, but wouldn't you then still expect the mutual information of two identical images (let's say the fixed image I use) to be higher than two images of which one was registered to this fixed image? The information content of the individual images seems quite similar then.

**Comment by ntustison** [comment]
Not necessarily.  As I said above, it depends on the content of the individual images.

**Comment by IlvaHou55** [comment]
Would there be another method to evaluate the registration? Other than creating masks and calculating dice index etc. I would like to also be able to say something about the 'inside'..

**Comment by ntustison** [comment]
Landmarks?

**Comment by IlvaHou55** [comment]
Hmm, that will not work for my application I am afraid. But thank you for the suggestion!
