### ISSUE TITLE
Why the origin nii file information is  complete, but after registraion to MNI152, the several bottom pictures have information loss?

### ISSUE THREAD

**Issue by sd0809** [ANTsX/ANTs#1341]
such as the origin nii file size is: 24 * 512 * 512, after registration to the MNI152, the nii file size is: 182 * 218 * 182, and there maybe information lackage happens in the 0~10 slices. i don't know why it happened and if some methods could be helpful to avoid the problem? 
Thank you.

**Comment by cookpa** [comment]
When you warp a moving to a fixed image, the moving image is resampled into the space of the fixed image - in this case, the MNI152 template. So it will have the dimensions of the fixed image. 

But sometimes the FOV of the registered images don't overlap fully. So a point in MNI space might be transformed outside the moving image bounding box. In that case, a default voxel value (0, unless you change it) is filled in.
