### ISSUE TITLE
git clone needs README.txt

### ISSUE THREAD

**Issue by ialpayo** [ANTsX/ANTs#1342]
**When did the error occur?**

[ ] CMake configuration (cmake / ccmake)
[X ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: [e.g. Mac OS] ubuntu
 - OS version: [e.g. 10.15.1] 20.04
 - Type of system: [Desktop, laptop, HPC cluster, cloud instance,
   other] workstation

**ANTs version**
 git clone on 23apr22

**Build configuration and logs**

During build got an error message saying the README.txt file is missing,
copied from the tar file I downloaded Dec 2020, which seems to have solved the problem.
Compiled and installed afterwards...

**Additional context**

**Comment by cookpa** [comment]
Sorry that was me, I wanted to direct people's attention to the newer README.md.

I did not know it was required to build.

**Comment by ialpayo** [comment]
No problem. You might want to try to compile to see the error and double check.
On a different subject, the changes at github connection protocols makes the release versions of ANTs impossible to compile. git clone seems to be the only way for installation at the moment.  Cheers...

**Comment by cookpa** [comment]
Right, we are overdue for a new release. But you can turn of the git protocol in older versions with the option ` -DSuperBuild_ANTS_USE_GIT_PROTOCOL=OFF`

**Comment by cookpa** [comment]
I set README.md as the package README - should fix the build problem

**Comment by ialpayo** [comment]
Just for information to anyone who might attempt a compile from the release files, in regard to an earlier answer:
"... you can turn of the git protocol in older versions with the option
-DSuperBuild_ANTS_USE_GIT_PROTOCOL=OFF"
 The suggestion does not work as the fix does not apply to the external file git downloads (at least this is my guess) resulting in compilation errors. 

The only solution at this point is compiling after git clone.

Thanks...

**Comment by ialpayo** [comment]
Thank you for fixing the issue quickly. My team and myself appreciate highly ANTs and its contributions...

Best regards...
