### ISSUE TITLE
fMRI registration using antsRegistrationSyN.sh

### ISSUE THREAD

**Issue by jaliladde** [ANTsX/ANTs#1345]
Hello
I applied "antsRegistrationSyN.sh" to T1-weighted MRI image
it gives three outputs:
1- Syn_outout1Rigid.mat
2-Syn_outout2Affine.mat
3-Syn_outout3Warp.nii.gz

I used these transformations step by step to fMRI 4D image using "antsApplyTransforms"
but the final result is different.
Can anyone help me with this?
How to apply "antsRegistrationSyN.sh" for fMRI 4D image registration to MNI152?

Regards

**Comment by jaliladde** [comment]
sh $ANTs_Regist_Syn -d $ImageDimension -f $FixedImage -m $MovingImage -z 0 -o ${Path_output}Syn_outout

antsApplyTransforms -d 3 -e 3 -i EPI -r Ref ... -t Syn_outout1Rigid.mat 
antsApplyTransforms -d 3 -e 3 -i EPI -r Ref ... -t Syn_outout2Affine.mat 
antsApplyTransforms -d 3 -e 3 -i EPI -r Ref ... -t Syn_outout3Warp.nii.gz

The output result (for fMRI image) is not similar to registered T1 image  !

**Comment by ntustison** [comment]
Please look at [this example](https://stnava.github.io/fMRIANTs/).
