### ISSUE TITLE
Build error: Object SHA512 for Initializer_0.05_antsRegistrationTest_SimilarityRotationNoMasks and Initializer_0.05_antsRegistrationTest_SimilarityScaleNoMasks

### ISSUE THREAD

**Issue by JayChang91** [ANTsX/ANTs#1356]
When did the error occur?

[ ] CMake configuration (cmake / ccmake)
[X ] Compilation (make)
[ ] Installation (make install)

Build environment

OS: Ubuntu
OS version: 18.04
Type of system: laptop, in WSL2 (Windows
Subsystem for Linux) of Windows 11 (22000.613)
ANTs version: v2.1.0
Author: Arman Eshaghi
Date: 23 Jan 2015

cmake version: 3.22.1
make version: 4.1
gcc version: 7.5.0

Build configuration and logs

[CMakeError.log](https://github.com/ANTsX/ANTs/files/8648907/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/8648908/CMakeOutput.log)
[build.log](https://github.com/ANTsX/ANTs/files/8648909/build.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/8648910/CMakeCache.txt)

Additional context
Hello, experts! @cookpa @bcdarwin I have tried to change the hash md5 to sha512 as shown in 221dad7 as said in #1237 , but still failed in two files (the others seem worked well): Object SHA512=875b7adb24f8958648a4b6ec495dcf00, and Object SHA512=42cd2424c063ac3be1aa469ad4f1d2db. They are just the two files that you marked as File renamed without changes: Initializer_0.05_antsRegistrationTest_SimilarityRotationNoMasks and Initializer_0.05_antsRegistrationTest_SimilarityScaleNoMasks. Should they change the content when converting from md5 to sha512? If so, what's the sha512 hash value for the two?

**Comment by cookpa** [comment]
I don't know why these images were overlooked before. Perhaps they were used in ANTs 2.1.0 but not in later versions. I located the files and put the hashes into #1357, which I'll merge later.
