### ISSUE TITLE
Understanding the command in antsMultivariateTemplateConstruction2.sh

### ISSUE THREAD

**Issue by zoelir729** [ANTsX/ANTs#1359]
Hi!
I understood the following paragraphy (paper) explaining the iterations and resolutions.

`-q 50x50x50 -f 8x4x1`
We used Ants Multivariate Template Construction script (Avants et al., 2011) for the steps listed above. Maximum iterations for each pair-wise registration were set to 50 × 50 × 50, based on previous reports (Bhalerao et al., 2018); it means that a maximum value of 50 iterations was performed consecutively at the coarsest resolution (shrink factor 8), middle resolution (shrink factor 4), and fine resolution (shrink factor 1).

However, I do not know how to understand the command (examples in antsMultivariateTemplateConstruction2.sh -h) turned into four resolutions `-f 6x4x2x1 -s 4x2x1x0vox -q 50x100x70x20`. 
Three resolutions seems to be more referred in papers.
What's the difference between three resolutions and four resolutions ?  Saving time ?

And  how can I explain the command `-f 6x4x2x1 -s 4x2x1x0vox -q 50x100x70x20`?
A maximum of 50 iterations at the coarsest level, 100 at the next coarsest, 70 at the coarest after next, and 20 at full resolution ?

Thanks!

**Comment by cookpa** [comment]
Both template scripts rely on pairwise registration between a candidate template and each moving image. antsMultivariateTemplateConstruction.sh uses ANTS, and antsMultivariateTemplateConstruction2.sh uses antsRegistration. Understanding those will help you understand the scripts.

https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-call

https://github.com/ANTsX/ANTs/wiki/ANTS-and-antsRegistration

**Comment by zoelir729** [comment]
> antsMultivariateTemplateConstruction.sh uses ANTS, and antsMultivariateTemplateConstruction2.sh uses antsRegistration.

Thanks a lot for your suggestion.
