### ISSUE TITLE
Problem: Not overlapping images after rigid registration -  antsRegistrationSyn.sh

### ISSUE THREAD

**Issue by Zntznkv** [ANTsX/ANTs#1360]
Hi everyone,
I'm struggling with antsRegistrationSyN -> I want to rigidly register one image of sequence to subject's native space. It went smoothly with others over 100 subjects but I can't figure out what could be the problem with this particular one. They are shiffted.
Now I'm working with antsRegistrationSyNQuick.sh only to speed up the work, here is the code:

antsRegistrationSyNQuick.sh -d 3 -f /5182A/5182A_*t1_mprage_sag_0iso85_p2_from_HCP.nii -m /5182A/*T1_tse_IRENEUROMELATIC_SN.nii -o /5182A/SYNQUICK_SN_NMS_toT1_ -t r

/_tools/ANTs/bin//antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [ /5182A/SYNQUICK_SN_NMS_toT1_,/5182A/SYNQUICK_SN_NMS_toT1_Warped.nii.gz,/SYNQUICK_SN_NMS_toT1_InverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] --initial-moving-transform [ /5182A_06s_t1_mprage_sag_0iso85_p2_from_HCP.nii,/5182A/5182A_18s_T1_tse_IRENEUROMELATIC_SN.nii,1 ] --transform Rigid[ 0.1 ] --metric MI[ /5182A/5182A_06s_t1_mprage_sag_0iso85_p2_from_HCP.nii,/5182A/5182A_18s_T1_tse_IRENEUROMELATIC_SN.nii,1,32,Regular,0.25 ] --convergence [ 1000x500x250x0,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox

I also tried to use image from brainextraction and also brainextractionMask but with no difference.
Thanks

![img](https://user-images.githubusercontent.com/56439115/168150891-cabbaf2e-ef9e-41f5-b87b-d02598ea1206.png)

**Comment by ntustison** [comment]
It would be most simple if you uploaded the data and the commands you used to create the output.

**Comment by cookpa** [comment]
Yes a packaged example with data and code, with simple file names, will help us.

**Comment by Zntznkv** [comment]
[Images.zip](https://github.com/ANTsX/ANTs/files/8682633/Images.zip)

And the code:
antsRegistrationSyNQuick.sh -d 3 -f /T1.nii -m /NMS.nii -o /NMS_to_T1 -t r

**Comment by ntustison** [comment]
This appears to be partial slab registration.  Have you checked out [this example](https://github.com/ntustison/PartialSlabEpiT1ImageRegistration)?

**Comment by cookpa** [comment]
I'd try out the rigid command in the above example. If the physical space of the images is reasonably closely aligned, you might want to remove the `--initial-moving-transform [${fixedImage},${movingImage},1] \` part. This aligns the center of mass, in physical space, of the two images, which can move the slab some way from its original location.

In ITK-SNAP, I see the slab looks pretty close to correct

<img width="763" alt="image" src="https://user-images.githubusercontent.com/611507/168198993-659f256e-d3ed-40e8-afc6-33e1623ab281.png">

So I would not use a COM alignment here.

**Comment by Zntznkv** [comment]
Worked perfectly, thank you both very much!
