### ISSUE TITLE
Atropos segmentation problem. White matter instead of gray matter

### ISSUE THREAD

**Issue by antogeo** [ANTsX/ANTs#1362]
Dear ANTs developers, 
I am aware that you are not responsible/related to nipype and I hope not be taking up a lot of your time. However, I thought that you might have came across to sth similar before and by seeing the parameters you could figure out what the problem is. So, in my processing approximately 90% of the times the third tissue of the saved posteriors is Gray matter and the rest 10% is White matter. Might be worth it to mention that this ratio is about 50-50 when it comes to IXI (IOP center).
I am running an ANTs (v2.2.0) pipeline, including ATROPOS, using nypipe. I am using the following parameters in ATROPOS
```
    atropos.inputs.initialization = 'KMeans'
    atropos.inputs.number_of_tissue_classes = 4
    atropos.inputs.prior_probability_threshold = 0.0000001
    atropos.inputs.prior_weighting = 0
    atropos.inputs.likelihood_model = 'Gaussian'
    atropos.inputs.mrf_smoothing_factor = 0.1
    atropos.inputs.mrf_radius = [1, 1, 1]
    atropos.inputs.n_iterations = 5
    atropos.inputs.convergence_threshold = 0.000001
    atropos.inputs.posterior_formulation = 'Socrates'
    atropos.inputs.use_mixture_model_proportions = True
    atropos.inputs.save_posteriors = True
```
Prior to ATROPOS I m using N4BiasFieldCorrection with:
```
    n4bc.inputs.bspline_fitting_distance = 300
    n4bc.inputs.shrink_factor = 3
    n4bc.inputs.n_iterations = [40, 40, 40, 40]
```
and BrainExtraction using brain and gray matter templates from ICBM 

Thank you in advance for you time, 
Georgios

**Comment by ntustison** [comment]
If they're all the same acquisition type (e.g., T1-w), then the swapping shouldn't happen.  And there's nothing in the parameters which deviate from the default native implementation.  So I don't know why this is happening.  If you don't want to go through the Nipype folk, you'll need to try to reproduce the issue with the native Atropos implementation.  Note that we would just need one image where posterior 3 is gray matter and poster 2 is white matter (which is swapped from what we'd expect).

**Comment by cookpa** [comment]
What's the purpose of the fourth class? If this class captures the brightest WM voxels, it could result in the rest of WM having a lower mean intensity than GM, which would cause GM to become class 3.

**Comment by gdevenyi** [comment]
I see you're initializing your segmentations with kmeans. You'll have a far more reproducible segmentation using some sort of probabilistic prior such as the MNI priors or something from the ANTs guys.

**Comment by ntustison** [comment]
We definitely recommend priors when available (as described [here](https://pubmed.ncbi.nlm.nih.gov/24879923/)).  However, there's a bit of artistry associated with [generating priors](https://github.com/ANTsX/ANTs/blob/master/Scripts/antsCookTemplatePriors.sh).  [Here](https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436) are some examples of complete sets of images for processing, including priors.  

Note that we've developed parallel deep learning tools in our ANTsXNet packages (ANTsPyNet and ANTsRNet) such that much of our current processing uses these alternative tools.  [Here](https://www.nature.com/articles/s41598-021-87564-6) is a recent write-up, in case of interest.
