### ISSUE TITLE
Image orientation changing due to header issue

### ISSUE THREAD

**Issue by Nsk97** [ANTsX/ANTs#1363]
Hi,

I submitted an issue a couple of months ago: https://github.com/ANTsX/ANTs/issues/1337

I have since tried running DenoiseImage on this data with a fresh install of ANTs (which I would assume to be the latest version possible) and I am still having the same issue. Is there anything else I can do to try to fix this?

Best,
Nathan

**Comment by cookpa** [comment]
I don't think there is a way to avoid information loss if the qform and sform are not consistent. I think the only solution is to decide which transform in your input is correct (qform or sform) and either make them identical or zero out the other one.

**Comment by Nsk97** [comment]
Ah okay, what would be the easiest way to make them identical?

Best,
Nathan

From: Philip Cook ***@***.***>
Date: Friday, 20 May 2022 at 16:46
To: ANTsX/ANTs ***@***.***>
Cc: Nathan Kindred (PGR) ***@***.***>, Author ***@***.***>
Subject: Re: [ANTsX/ANTs] Image orientation changing due to header issue (Issue #1363)

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

I don't think there is a way to avoid information loss if the qform and sform are not consistent. I think the only solution is to decide which transform in your input is correct (qform or sform) and either make them identical or zero out the other one.

**Comment by cookpa** [comment]
This ought to resolve the confusion

`ImageMath 3 sformOnly.nii.gz m input.nii.gz 1`

It will definitely harmonize them, but I'm not sure whether it will copy qform into sform or vice versa. The logic gets complicated when both exist. You will need to ensure that the transform is correct both in ITK and in other tools you're using. For ITK, you can check the interpretation of physical space with ITK-SNAP. In FSL, fsleyes. If the anatomical labels (R, L, A, P, I, S) are correct in both contexts, you should be good.

**Comment by Nsk97** [comment]
Ah I believe I initially misinterpreted the line of code, sformOnly.nii.gz is a new file that is created? If that is the case then I think the sform is the incorrect transformation for my files as running this code creates a file with the same incorrect orientation as my denoised output. Is there a way I can overwrite the sform with the qform?

Best,
Nathan

From: Philip Cook ***@***.***>
Date: Friday, 20 May 2022 at 20:37
To: ANTsX/ANTs ***@***.***>
Cc: Nathan Kindred (PGR) ***@***.***>, Author ***@***.***>
Subject: Re: [ANTsX/ANTs] Image orientation changing due to header issue (Issue #1363)

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

This ought to resolve the confusion

ImageMath 3 sformOnly.nii.gz m input.nii.gz 1

It will definitely harmonize them, but I'm not sure whether it will copy qform into sform or vice versa. The logic gets complicated when both exist. You will need to ensure that the transform is correct both in ITK and in other tools you're using. For ITK, you can check the interpretation of physical space with ITK-SNAP. In FSL, fsleyes. If the anatomical labels (R, L, A, P, I, S) are correct in both contexts, you should be good.

**Comment by cookpa** [comment]
For that I would recommend RNifti:

```
library(RNifti)
im = readNifti("input.nii.gz")
transform = xform(im, useQuaternionFirst = T)
sform(im) = transform
writeNifti(im, "output.nii.gz")
```

**Comment by Nsk97** [comment]
Hi Philip,

Just wanted to email to thank you for all of your help, this has now fixed the issue I was having!

Best wishes,
Nathan
From: Philip Cook ***@***.***>
Date: Monday, 23 May 2022 at 13:47
To: ANTsX/ANTs ***@***.***>
Cc: Nathan Kindred (PGR) ***@***.***>, Author ***@***.***>
Subject: Re: [ANTsX/ANTs] Image orientation changing due to header issue (Issue #1363)

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

For that I would recommend RNifti:

library(RNifti)

im = readNifti("input.nii.gz")

transform = xform(im, useQuaternionFirst = T)

sform(im) = transform

writeNifti(im, "output.nii.gz")

**Comment by Nsk97** [comment]
Thank you so much for your help, just to clarify how do I get the sformonly.nii.gz image?

Best,
Nathan

From: Philip Cook ***@***.***>
Date: Friday, 20 May 2022 at 20:37
To: ANTsX/ANTs ***@***.***>
Cc: Nathan Kindred (PGR) ***@***.***>, Author ***@***.***>
Subject: Re: [ANTsX/ANTs] Image orientation changing due to header issue (Issue #1363)

⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

This ought to resolve the confusion

ImageMath 3 sformOnly.nii.gz m input.nii.gz 1

It will definitely harmonize them, but I'm not sure whether it will copy qform into sform or vice versa. The logic gets complicated when both exist. You will need to ensure that the transform is correct both in ITK and in other tools you're using. For ITK, you can check the interpretation of physical space with ITK-SNAP. In FSL, fsleyes. If the anatomical labels (R, L, A, P, I, S) are correct in both contexts, you should be good.

**Comment by cookpa** [comment]
> Thank you so much for your help, just to clarify how do I get the sformonly.nii.gz image? 

I'm not sure why I typed that, possibly cut and paste from an older issue. The format of ImageMath commands is

`ImageMath 3 <output> <operation> <input> [ additional args]`

The command

`ImageMath 3 output.nii.gz m input.nii.gz 1`

just multiplies voxels in `input.nii.gz` by 1, and then writes `output.nii.gz` with a harmonized transform. After this, sform and qform should say the same thing. But if both qform_code > 0 and sform_code > 0, it gets complicated as to which one is chosen. 

In the R code above, I explicitly give priority to the qform.
