### ISSUE TITLE
Cannot complie ANTs in Linux (CentOS 7): ITKv5-build Error 2

### ISSUE THREAD

**Issue by hmonsivais12** [ANTsX/ANTs#1370]
Hello, I have been trying to install ANTs in my university's interactive computing environment which runs Linux CentOS 7. At first I was having trouble with the cmake version, but I managed to install a cmake version that I can run locally. However, when I try to compile ANTs I keep getting an error for building ITKv5. I've tried it using the super build script and also by following the instructions [here](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS).

I've attached the log files below. Any help would be greatly appreciated! 

[build.log](https://github.com/ANTsX/ANTs/files/8824244/build.log)
[cmake.log](https://github.com/ANTsX/ANTs/files/8824246/cmake.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/8824250/CMakeCache.txt)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/8824251/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/8824253/CMakeOutput.log)

**Comment by cookpa** [comment]
I've not used the Intel compiler. Can you use GCC? 

If not, try building ITK by itself (https://github.com/InsightSoftwareConsortium/ITK). If it doesn't work, you can ask on ITK's Discourse site. Let them know the exact compiler version you are using and the config / logs as above.

**Comment by hmonsivais12** [comment]
I'm not sure if I can use GCC. Is there a way to check? Sorry I'm very new to this stuff still. 

I've tried building ITK by itself but I ran into some issues as well. I will probably have to post it on ITK's discourse site.

**Comment by cookpa** [comment]
If you're lucky, you can try

`which gcc`

If that exists, you can set

```
export CC=/path/to/gcc
export CXX=/path/to/g++
```

before running cmake in a clean build directory. 

It's possible that GCC exists on your system but isn't on the PATH, so if you can't find it, you might want to check in with your system admins.

**Comment by gdevenyi** [comment]
I regularly successfully build with icc2019, prior to that I used icc2018.

ICC2017 may not support new enough versions of the C++ spec with the most recent ANTS/ITK C++ code use.

**Comment by hmonsivais12** [comment]
Thank you all for your help and suggestions. It seems the error was coming from the intel compiler. I tried intel 19.0.3.199 but got the same error. Switching to GCC 6.3.0 worked beautifully.
