### ISSUE TITLE
Blurriness in big FOV template

### ISSUE THREAD

**Issue by barbrakr** [ANTsX/ANTs#1372]
**Describe the problem**

We have been using ANTs to generate a big FOV template. Specifically we used the recommended settings, such as synStep=0.1, synUpdateVariancePenalty=3, synTotalVariancePenalty=0, genLocalTmp=0.

However, we found that the occipital GM regions look blurry on our template (see attached figure). Is there something you could suggest to avoid this?

![figure3](https://user-images.githubusercontent.com/50030195/172571785-2d6c543e-cc0c-41ed-953c-300a1a83776d.jpg)

**To Reproduce**
    cmd+=" -a 1" # write out composite transform
    cmd+=" -n BSpline" # interpolation
    cmd+=" --use-histogram-matching 1" # if within modality
    cmd+=" --winsorize-image-intensities [0.005,0.995]" # clip extreme values
    cmd+=f" --initial-moving-transform [{reference},{infile},1]" # match by center of mass

    # now comes the transformations, rigid first
    if doRigid:
        cmd+=" --transform Rigid[0.1]"
        cmd+=f" --metric {costFunc[0]}[{reference},{infile},1,32,Regular,0.25]"
        cmd+=" --convergence [1000x500x250x100,1e-6,10]"
        cmd+=" --shrink-factors 8x4x2x1"
        cmd+=" --smoothing-sigmas 3x2x1x0vox"
        if useMasks:
           cmd+=f" --masks [{refMskfile[0]},{inMskfile[0]}]" # put the masks

    # then affine
    if doAffine:
        cmd+=" --transform Affine[0.1]"
        cmd+=f" --metric {costFunc[1-(1-doRigid)]}[{reference},{infile},1,32,Regular,0.25]"
        cmd+=" --convergence [1000x500x250x100,1e-6,10]"
        cmd+=" --shrink-factors 8x4x2x1"
        cmd+=" --smoothing-sigmas 3x2x1x0vox"
        if useMasks:
           cmd+=f" --masks [{refMskfile[1-(1-doRigid)]},{inMskfile[1-(1-doRigid)]}]" # put the masks

    # then SyN
    if doSyn:
        cmd+=f" --transform SyN[{synStep},{synUpdateVariancePenalty},{synTotalVariancePenalty}]"
        cmd+=f" --metric {costFunc[2-(1-doRigid)-(1-doAffine)]}[{reference},{infile},1,4]"
        cmd+=" --convergence [100x70x50x20,1e-6,10]"
        cmd+=" --shrink-factors 8x4x2x1"
        cmd+=" --smoothing-sigmas 3x2x1x0vox"
        if useMasks:
           cmd+=f" --masks [{refMskfile[2-(1-doRigid)-(1-doAffine)]},{inMskfile[2-(1-doRigid)-(1-doAffine)]}]" # put the masks

**System information (please complete the following information)**

 - OS: Linux
 - OS version: 3.10.0-1160.59.1.el7.x86_64  |  1 SMP Tue Feb 22 10:57:56 CST 2022
 - Type of system: HPC cluster

**ANTs version information**
 - ANTs code version: 2.3.1.dev159-gea5a7
 - ANTs installation type: Compiled from source

**Additional information**

**Comment by ntustison** [comment]
Are you not using the antsMultivariateTemplateConstruction.sh / antsMultivariateTemplateConstruction2.sh scripts?

**Comment by barbrakr** [comment]
No, we were not using those. Do you ha[[en to have advice on our approach? 
Kind wishes,
Barbara
