### ISSUE TITLE
7 Parameter Registration with Constrained Scaling?

### ISSUE THREAD

**Issue by Jorshk** [ANTsX/ANTs#1375]
Hello,
I am trying to use a template brain to segment (skull-strip) fetal head images. Rigid registering with the antsRegistrationSyn script works pretty well, but I would like to include a 7th scaling parameter, constrained such that it will only change by a few % or so to account for smaller/larger individual brains, without trying to scale the template to the whole volume (surrounding maternal tissue). Can someone let me know if this is possible/suggest how one would go about including and constraining the scaling parameter?
Thank you!
Joshua

**Comment by gdevenyi** [comment]
@Jorshk sounds like what you need is to either use masks, or actually extract the tissues of interest so they sit isolated in background. I don't think ANTs has explicit constraints for the optimizer.

I've found through mostly experimentation that you can constrain things a bit by controlling at what scales how many parameters are allowed to vary (Rigid vs Similarity vs Affine), I encoded all of that into `antsRegistration_affine_SyN.sh` and `ants_generate_iterations.py` available here, https://github.com/cobralab/minc-toolkit-extras

**Comment by Jorshk** [comment]
@gdevenyi thank you and absolutely! I was checking to see if I could create the brain mask straight from an aligned template without any manual masking steps, but will likely be tough without at least some touch ups. That is good to know about the optimizer, and I appreciate you linking your scripts -- I will check them out!
Cheers
