### ISSUE TITLE
concerting ANTS movment parameters to AFNI

### ISSUE THREAD

**Issue by garincle** [ANTsX/ANTs#1378]
Dear ANTS Users,

I would like to convert an affine transformation (Warp nonlinear and linear if possible) generated with ANTS for use with AFNI.
Is there a way to do it? 
If not I believe that it could be very useful.
Is it difficult? impossible? 

Thank you very much for your help.

**Comment by cookpa** [comment]
It might have been done, but not by us

https://neurostars.org/t/converting-affine-matrices-from-afni-3dvolreg-to-fsl-or-itk-ants/338
