### ISSUE TITLE
Brain tumor segmentation [example]

### ISSUE THREAD

**Issue by LucSam** [ANTsX/ANTs#1379]
Hi, I wanted to check the linked suggestion for _**"Brain tumor segmentation [example](https://github.com/ntustison/BRATS2013/SimpleExample/)"**_, however, the link under _[https://github.com/ANTsX/ANTs#learning-about-ants-examples-etc]_ doesn't work.
Is there still an opportunity to use ants for tumor or lesion segmentation? I couldn't find an example.
I'm happy to test.
Best

**Comment by cookpa** [comment]
Others may have more recent links to share, but here's the original example 

https://github.com/ntustison/BRATS2013/tree/master/SimpleExample
