### ISSUE TITLE
How to register the brain nii file and the ground truth(brain tumor mask) simultaneously？

### ISSUE THREAD

**Issue by sd0809** [ANTsX/ANTs#1380]
hello, i have register the origin brain nii file A , which size is (24, 512, 512) into the normal brain template ,which size is (182, 218 ,182), and i have gotten the brain tumor ground truth B which size is (24, 512, 512), how could i register the mask/ ground truth  B precisely to match the tumor in the registred brain file A ?
Thank you!

**Comment by ntustison** [comment]
``antsApplyTransforms -d 3 -i ${B} -r ${template} -o ${BWarpedToTemplate} -n NearestNeighbor -t ${AtoTemplate}1Warp.nii.gz -t ${AToTemplate}0GenericAffine.mat``
