### ISSUE TITLE
antsMultivariateTemplateConstruction.sh taking too long. GPU option available?

### ISSUE THREAD

**Issue by michalecbdavid** [ANTsX/ANTs#1384]
I am attempting to create a template from c. 100 scans and antsMultivariatTemplateConstruction.sh is taking longer than the maximum 6 days our cluster allows. Are there any ways of accelerating for example using GPUs instead of CPUs?

Thanks

**Comment by gdevenyi** [comment]
No, but you may be interested in my re-implementaton which supports file based resume, so runtime isn't an issue.

https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction
