### ISSUE TITLE
how to fix a bad antsRegistration result (EPI to T1)

### ISSUE THREAD

**Issue by carolin31** [ANTsX/ANTs#1386]
**Describe the problem**
Hi ants experts. I ran antsRegistration to coregister an EPI image to a T1. It worked ok for most of my subjects but for some the result is not good (see image). I already optimized the function as good as I could with previous help from you guys. I use the  Biasfield correction on the EPI before running the registration, I include a dilated mask for the T1 and the EPI. And both images are skull stripped. What else can I try to improve the result for some subjects? I also saw that it is recommended to pad the images with ImageMath but I don t fully understand what the padding will do? Is it dilating the images? Also would it be worth to switch to antsR instead? Is the coregistration algorithm in antsR better?

**To Reproduce**

fixedImage=${baseDirectory}/outputBrainExtractionBrain.nii.gz
movingImage=${baseDirectory}/corrected_minOutlier_masked.nii.gz
anatmaskImage=${baseDirectory}/automask_d_anat.nii
EPImaskImage=${baseDirectory}/automask_minOutlier_d.nii

antsRegistration --verbose 1 \
                  --dimensionality 3 \
                  --float 0 \
                  --interpolation Linear \
                  --use-histogram-matching 0 \
                  --winsorize-image-intensities [0.005,0.995] \
                  --output [${outputPrefix},${outputPrefix}Warped.nii.gz,${outputPrefix}InverseWarped.nii.gz] \
                  --initial-moving-transform [${fixedImage},${movingImage},1] \
                  --transform translation[0.1] \
                    --metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
                    --convergence [50,1e-6,10] \
                    --shrink-factors 1 \
                    --smoothing-sigmas 0vox \
                   --masks [${anatmaskImage},${EPImaskImage}]\
                  --transform Rigid[0.1] \
                  --metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
                    --convergence [500x500x250x50,1e-6,10] \
                    --shrink-factors 6x4x2x1 \
                    --smoothing-sigmas 3x2x1x0vox \
                   --masks [${anatmaskImage},${EPImaskImage}]\
                  --transform SyN[0.1,3,0] \
                    --metric MI[${fixedImage},${movingImage},1,32] \
                    --convergence [100x20,1e-6,10] \
                    --shrink-factors 2x1 \
                     --smoothing-sigmas 1x0vox \
                    --masks [${anatmaskImage},${EPImaskImage}]

I am using a singularity container. Ants v234

<img width="1427" alt="Screen Shot 2022-07-08 at 11 29 11 AM" src="https://user-images.githubusercontent.com/41706947/178054550-dbc7f2d4-f1f0-4219-8a49-7b87b578d0dd.png">

<img width="1455" alt="Screen Shot 2022-07-08 at 11 31 57 AM" src="https://user-images.githubusercontent.com/41706947/178054826-70072b1d-ca99-42c1-8ea4-b903a607abad.png">

<img width="1455" alt="Screen Shot 2022-07-08 at 11 33 00 AM" src="https://user-images.githubusercontent.com/41706947/178054850-aa5f5ec1-c708-4f54-851c-4755fa3871dd.png">

**Comment by cookpa** [comment]
The padding is needed when the bounding box of the images are very close to the head / brain.

The deformation field at the edges of the virtual space (usually the fixed image) is constrained to be zero. Padding the image allows for anatomy near the edges of the original FOV to be deformed, while still allowing space for the deformation to smoothly approach zero at the edge of the padded FOV.

Additionally, padding the images reduces the number of moving voxels that are outside the FOV after the initial alignment, which also improves stability.

**Comment by carolin31** [comment]
oh ok. Sorry for this stupid question but how can I check if the bounding box is too close to the head/brain so that I know if padding could help in this case?

**Comment by cookpa** [comment]
If you open the image in SNAP, then scroll as far as you can to the six sides of the image - if there's brain within 10mm or so of the edge, padding can help.

**Comment by cookpa** [comment]
In answer to your other questions, ANTsR uses the same underlying code, but its options and defaults may differ. I wouldn't switch for performance reasons.

How does the rigid registration alone look? If that's bad, then the deformable registration will likely also be bad.

If the rigid is good but the deformable has problems, you can try switching to BSplineSyN and / or introducing some regularization to the transform term.

**Comment by carolin31** [comment]
Hi! I checked the bounding box and there is definitely more than 10 mm distance between the brain and the bounding box in all planes. I reran the coregistration with only using the translation and then with using the translation + rigid. The result after just using the translation is already not good at all. The same after running translation+rigid. So looks like something is going wrong at the beginning of the coreg.
Any idea what else I could try? I don t understand why this script worked ok for most of my subjects but does not seem to work at all for this one.

$SANTS antsRegistration --verbose 1 \
                  --dimensionality 3 \
                  --float 0 \
                  --interpolation Linear \
                  --use-histogram-matching 0 \
                  --winsorize-image-intensities [0.005,0.995] \
                  --output [${outputPrefix},${outputPrefix}Warped.nii.gz,${outputPrefix}InverseWarped.nii.gz] \
                  --initial-moving-transform [${fixedImage},${movingImage},1] \
                  --transform translation[0.1] \
                    --metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
                    --convergence [50,1e-6,10] \
                    --shrink-factors 1 \
                    --smoothing-sigmas 0vox \
                   --masks [${anatmaskImage},${EPImaskImage}]\
                  #--transform Rigid[0.1] \
                  #--metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
                  #  --convergence [500x500x250x50,1e-6,10] \
                  #  --shrink-factors 6x4x2x1 \
                  #  --smoothing-sigmas 3x2x1x0vox \
                  # --masks [${anatmaskImage},${EPImaskImage}]\
                  #--transform SyN[0.1,3,0] \
                   # --metric MI[${fixedImage},${movingImage},1,32] \
                    #--convergence [100x20,1e-6,10] \
                    #--shrink-factors 2x1 \
                    # --smoothing-sigmas 1x0vox \
                    #--masks [${anatmaskImage},${EPImaskImage}]



<img width="1162" alt="Screen Shot 2022-07-15 at 11 57 10 AM" src="https://user-images.githubusercontent.com/41706947/179293464-a3ba0221-6c6d-4da9-af12-f44970ea941a.png">

**Comment by ntustison** [comment]
Would you be able to share the images?

**Comment by cookpa** [comment]
I've often found that the Translation model is unstable. Rigid normally works better.

The other thing I would check is that the COM is not too far off; this can happen with different contrasts / FOVs. You can get the COM transform with

`antsAI  -d 3 -t AlignCentersOfMass -m Mattes[ fixed.nii.gz , moving.nii.gz, 32, Random ] -o com.mat`.

**Comment by gdevenyi** [comment]
I can always sneak in an recommend my antsRegistration_affine_SyN.sh script with an optimized transformation stack and pyramid, https://github.com/CoBrALab/minc-toolkit-extras

It's being used for EPI-T1 registration for mice and rats in another pipeline.

**Comment by carolin31** [comment]
Yes, I can share the images. What is the best way to do it?

If the translation model is unstable are you suggesting to run the coregistration with just using rigid and SyN? I checked the COM. the numbers for that subj are [-2.186965012583417;-5.969216774192791;7.806534489414684]. They are higher in comparison to another subject where the coregistration worked well [-1.944301716293708;-1.797295952230644;4.549823506861442] But I am not sure if this difference is meaningful

**Comment by carolin31** [comment]
when I apply the transform it makes the alignment a little better. 
So should I now try to run the coregistration on these aligned images?

<img width="1151" alt="Screen Shot 2022-07-15 at 2 17 36 PM" src="https://user-images.githubusercontent.com/41706947/179312070-179baa79-c9e9-4421-81ae-01e916ecddc2.png">
<img width="1112" alt="Screen Shot 2022-07-15 at 2 18 34 PM" src="https://user-images.githubusercontent.com/41706947/179312081-0456f920-6683-4681-9b6c-1b3233f29173.png">

**Comment by cookpa** [comment]
No, you can use the original images. It was just to visualize what `-r` was doing.
