### ISSUE TITLE
Making a weighted mean (average) image of a 4D-MRI image

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTs#1394]
Dear ANTs experts,

I wonder if there is a simple way (or command) to create a weighted mean (average) image of 4D MRI (time series data, multi-echo, etc.) data. 
Any advice or suggestions will be appreciated. 

Regards,
SC

**Comment by cookpa** [comment]
Not that I know of in base ANTs. It's the kind of thing we would do in ANTsR or ANTsPy.

**Comment by gdevenyi** [comment]
You'll have an easier job writing some simple code in python with SimpleITK and numpy.
