### ISSUE TITLE
ANTs affine to ASCII format

### ISSUE THREAD

**Issue by tmspvn** [ANTsX/ANTs#1395]
Dear Developers, 

Is it possible to convert/output a .txt file from an affine registration? This could be useful when using wb_command -surface-apply-affine
Thanks

Best,
Tommaso

**Comment by ntustison** [comment]
If I remember correctly, ``wb_command`` uses FSL which does not use the same transform definitions as the underlying ITK transform definitions.  You would have to use a 3rd party conversion program like the c3d affine tool.

**Comment by tmspvn** [comment]
Hi, thanks for your answer, 

`wb_command -surface-apply-affine` requires a world affine [1], but indeed to get it I must convert it somehow.  `wb_command` uses `-convert-affine` to convert and ITK affine to a world affine. However, the .mat of ants cannot be loaded and the HCP developer told me that that function converts an ASCII ITK and not binary [3].

Do you confirm that the only solution is to use c3d? thanks

[1] https://www.humanconnectome.org/software/workbench-command/-surface-apply-affine
[2] https://www.humanconnectome.org/software/workbench-command/-convert-affine
[3] https://groups.google.com/a/humanconnectome.org/g/hcp-users/c/Ht2z1ZX0n1o

**Comment by ntustison** [comment]
``ConvertTransformFile``

**Comment by tmspvn** [comment]
Thanks!
