### ISSUE TITLE
antsApplyTransforms do not produce exactly the same '_Warped' image as antsRegistration

### ISSUE THREAD

**Issue by devDonnn** [ANTsX/ANTs#1398]
I run the default antsRegistrationSyn.sh script which by default uses linear interpolation (-n Linear) and outputs **movingToFixed_Warped.nii.gz**. Now, I want to replicate this volume by using antsApplyTransforms and linear interpolation: 

`antsApplyTransfroms -d 3 -i movingImage.nii.gz -r fixedImage.nii.gz -t movingToFixed_1Warp.nii.gz -t movingToFixed_0GenericAffine.mat -movingToFixed_Deformed.nii.gz -n Linear`. 

It does output the image volume very close to the movingToFixed_Warped.nii.gz but with some small differences in the voxel values, of an order of 0.000X. Most of the differences are observed in the non-brain areas but almost none in the brain region. What does it cause such behavior?  

 - OS: Red Hat Enterprise Linux Server
 - OS version: 7.9
 - Type of system: HPC cluster

**ANTs version information**
 - ANTs code version: v2.4.0
 - ANTs installation type: Compiled from source

**Comment by cookpa** [comment]
I believe this is because `antsRegistrationSyN.sh` writes the warped images directly from within `antsRegistration`, rather than writing the composite transform and then calling `antsApplyTransforms`.

**Comment by gdevenyi** [comment]
To expand on this, my suspicion is that this has to do with the limitations of the NIFTI file format in terms of numerical precision for header entries, where the full precision is maintained inside the ITK objects while running. One way to test this would be to use the `--minc` transform outputs which don't suffer the same file-format issues.

**Comment by cookpa** [comment]
The NIFTI header is definitely also an issue. I don't know if the transform stack gets composed before the warped output gets written. It would be interesting to test and document if `--minc` produced identical output with and without `-z`.

**Comment by gdevenyi** [comment]
>  It would be interesting to test and document if --minc produced identical output with and without -z.

The `-z` composing into a single transform shouldn't change vs no `-z` because the `.xfm` files are text files, so all this would do is literally concat the two text components together into a single text file (the warp field is just referred to by a filename inside the .xfm file)

**Comment by devDonnn** [comment]
Thanks for the comments! I tested using the `--minc` flag and the `antsApplyTransforms` yielded exactly the same output as the main `antsRegistration` executable.

**Comment by cookpa** [comment]
That's good to know, thanks for reporting back.
