### ISSUE TITLE
ANTsRegistration not registering the T1w to b=0 image correctly

### ISSUE THREAD

**Issue by akelkar26** [ANTsX/ANTs#1403]
**Describe the problem**
I am using AntsRegistrationSyn to register the T1w to the b=0 DWI image. However it fails for 2 subjects and runs for 30 others. The output T1wtob0Warped.nii.gz image is not registering perfectly to the b=0 image

![Capture_T1overlayedonDWIb0](https://user-images.githubusercontent.com/40644674/180288325-cfcc55c7-8f37-4207-8dc8-42f206d90701.PNG)

**To Reproduce**
movingImage=T1w_brainextracted.nii.gz
fixedImage=sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz
maskImage=sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_desc-brain_mask.nii.gz

Command:

antsRegistrationSyn.sh -d 3 -f ${fixedImage} -m ${movingImage} -x ${maskImage} -o /Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-${sub}/dwi/T1wtob0

ANTs version information

ANTs code version: ANTs Version: 2.3.5.dev224-g5f1fa
Compiled: Mar 5 2021 23:24:29
ANTs installation type: Compiled from source

I have shared the data on this dropbox link:
https://www.dropbox.com/scl/fo/2pg19j3x66uu61bwpmvaz/h?dl=0&rlkey=705z1pmflb2ckgd62yoq12gl7

Could you please advise?
Thank you
Best,
Apoorva

**Comment by cookpa** [comment]
If you run the registration with `-t r`, can you get a decent rigid alignment? If not, I would suggest using `antsAI` to get a good initial registration - let me know if you need help with that.

**Comment by cookpa** [comment]
Oh - also you need to be clear that the mask is for the moving image, `-x [ NULL, $maskImage ]`

**Comment by akelkar26** [comment]
Thank you for the suggestions.

I gave the mask image for the moving image with this updated command:

antsRegistrationSyn.sh -d 3 -f ${fixedImage} -m ${movingImage} -x NULL,${maskImage_moving} -o T1wtob0

The mask image_moving variable is the mask for the T1w_brainextracted.nii.gz

Here is the updated registration output:
![Capture_registration](https://user-images.githubusercontent.com/40644674/180836669-a8d3295f-aea8-4c63-b608-4f7c0374c199.PNG)

Is there any other parameter I could add to make it conform to the base image even better?
I haven't tried antsAI yet. 

Thank you in advance for the help.

Best,
Apoorva

**Comment by cookpa** [comment]
If you quote code with single backquotes inline like `ls` or triple backquotes for paragraphs

```
ls -l
```

it will be easier to read.

Your argument to `-x` needs the square brackets, `-x [ NULL,${maskImage_moving} ]`

**Comment by akelkar26** [comment]
So sorry about the code readout. I will add it in the single backquotes.
When I give the `-x [ NULL,${maskImage_moving} ]` in the code, it gives me an itk error.
Here is the error:

`mkdir: /Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline: File exists
mkdir: /Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38: File exists
mkdir: /Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38/dwi: File exists

--------------------------------------------------------------------------------------
 Mapping parameters
--------------------------------------------------------------------------------------
 ANTSPATH is /Users/neurouser1/opt/ANTs/bin/

 Dimensionality:           3
 Output name prefix:       /Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38/dwi/T1wtob0
 Fixed images:             /Users/neurouser1/Documents/TMS_Aphasia/qsiprepout_dwionly/qsiprep/sub-TMSA38/ses-BRAINRESEARCHCOSLETT/dwi/sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz
 Moving images:            /Users/neurouser1/Documents/TMS_Aphasia/Impute/sub-TMSA38/sub-TMSA38_ImputedImage_22controls_rad1.nii.gz
 Mask images:              [NULL,/Users/neurouser1/Documents/TMS_Aphasia/ANTsbrainextract/sub-TMSA38/BrainExtractionMask.nii.gz]
 Initial transforms:
 Number of threads:        1
 Spline distance:          26
 SyN gradient step:        0.1
 Transform type:           s
 CC radius:                4
 Precision:                d
 Use histogram matching    0
======================================================================================
 antsRegistration call:
--------------------------------------------------------------------------------------
/Users/neurouser1/opt/ANTs/bin//antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [ /Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38/dwi/T1wtob0,/Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38/dwi/T1wtob0Warped.nii.gz,/Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38/dwi/T1wtob0InverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] -x [ [NULL,/Users/neurouser1/Documents/TMS_Aphasia/ANTsbrainextract/sub-TMSA38/BrainExtractionMask.nii.gz], NULL ] --initial-moving-transform [ /Users/neurouser1/Documents/TMS_Aphasia/qsiprepout_dwionly/qsiprep/sub-TMSA38/ses-BRAINRESEARCHCOSLETT/dwi/sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz,/Users/neurouser1/Documents/TMS_Aphasia/Impute/sub-TMSA38/sub-TMSA38_ImputedImage_22controls_rad1.nii.gz,1 ] --transform Rigid[ 0.1 ] --metric MI[ /Users/neurouser1/Documents/TMS_Aphasia/qsiprepout_dwionly/qsiprep/sub-TMSA38/ses-BRAINRESEARCHCOSLETT/dwi/sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz,/Users/neurouser1/Documents/TMS_Aphasia/Impute/sub-TMSA38/sub-TMSA38_ImputedImage_22controls_rad1.nii.gz,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[ 0.1 ] --metric MI[ /Users/neurouser1/Documents/TMS_Aphasia/qsiprepout_dwionly/qsiprep/sub-TMSA38/ses-BRAINRESEARCHCOSLETT/dwi/sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz,/Users/neurouser1/Documents/TMS_Aphasia/Impute/sub-TMSA38/sub-TMSA38_ImputedImage_22controls_rad1.nii.gz,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[ 0.1,3,0 ] --metric CC[ /Users/neurouser1/Documents/TMS_Aphasia/qsiprepout_dwionly/qsiprep/sub-TMSA38/ses-BRAINRESEARCHCOSLETT/dwi/sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz,/Users/neurouser1/Documents/TMS_Aphasia/Impute/sub-TMSA38/sub-TMSA38_ImputedImage_22controls_rad1.nii.gz,1,4 ] --convergence [ 100x70x50x20,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox
--------------------------------------------------------------------------------------
Exception Object caught:

itk::ExceptionObject (0x7ff76f0a75b0)
Location: "unknown"
File: /Users/neurouser1/Applications/ANTs/Utilities/antsCommandLineParser.cxx
Line: 257
Description: itk::ERROR: itk::ERROR: CommandLineParser(0x7ff76f0a0c40): Incorrect command line specification. Missing leftDelimiterPosition? [NULL,/Users/neurouser1/Documents/TMS_Aphasia/ANTsbrainextract/sub-TMSA38/BrainExtractionMask.nii.gz],


niiRead(): error opening file /Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38/dwi/T1wtob0Warped.nii.gz`

Could you please advise?

Thank you

**Comment by cookpa** [comment]
Doh! I told you the wrong thing, mixing my syntax between the scripts and program. Sorry.

Also, I got confused by the `space-T1w` in the mask name - it's actually in the DWI space.

So I ran

`antsRegistrationSyN.sh -d 3 -f sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz -m T1w_brainextracted.nii.gz -t sr -x sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_desc-brain_mask.nii.gz -o t1wToDWI_`

I find the `-t sr` works well for EPI <-> T1w because it solves motion with the rigid part, and then distortion with SyN, skipping the affine step. It also doesn't do a lot of SyN iterations at coarse resolution - useful for finer scale registration like this intra-subject case. I think the alignment is pretty good for the most part but I see some local overfitting. 

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/611507/180896873-c640cdb5-3721-4c19-bc87-8491076d10ac.png">

To improve upon this you could try B-spline SyN (-t br) or edit the antsRegistration command, as printed by the script:

```
antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [ t1wToDWI_,t1wToDWI_Warped.nii.gz,t1wToDWI_InverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] -x [ sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_desc-brain_mask.nii.gz, NULL ] --initial-moving-transform [ sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz,T1w_brainextracted.nii.gz,1 ] --transform Rigid[ 0.1 ] --metric MI[ sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz,T1w_brainextracted.nii.gz,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[ 0.1,3,0 ] --metric CC[ sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz,T1w_brainextracted.nii.gz,1,4 ] --convergence [ 50x20,1e-6,10 ] --shrink-factors 2x1 --smoothing-sigmas 1x0vox
```

For example you could replace ` --transform SyN[ 0.1,3,0 ] ` with ` --transform SyN[ 0.1,3,0.5 ]`.

**Comment by cookpa** [comment]
You can also get a sense of how much deformation is needed by just applying the rigid transform

```
antsApplyTransforms -d 3 -i T1w_brainextracted.nii.gz -o t1wRigidDeformed.nii.gz -t t1wToDWI_0GenericAffine.mat -r sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz 
```

This looks pretty close to good - so maybe fewer deformable iterations are called for.

**Comment by akelkar26** [comment]
Thank you so much for your suggestions Dr. Cook. Sorry, took me a while to implement them.

I tried them but the registration seems to look better only for the rigid transformation. It is still not perfect though
Here is the command I gave using ANTsRegistrationSyn:

`/Users/neurouser1/opt/ANTs/bin//antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [ /Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38/dwi/T1wtob0,/Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38/dwi/T1wtob0Warped.nii.gz,/Users/neurouser1/Documents/TMS_Aphasia/DWIPreprocPipeline/sub-TMSA38/dwi/T1wtob0InverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] -x [ /Users/neurouser1/Documents/TMS_Aphasia/qsiprepout_dwionly/qsiprep/sub-TMSA38/ses-BRAINRESEARCHCOSLETT/dwi/sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_desc-brain_mask.nii.gz, NULL ] --initial-moving-transform [ /Users/neurouser1/Documents/TMS_Aphasia/qsiprepout_dwionly/qsiprep/sub-TMSA38/ses-BRAINRESEARCHCOSLETT/dwi/sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz,/Users/neurouser1/Documents/TMS_Aphasia/Impute/sub-TMSA38/sub-TMSA38_ImputedImage_22controls_rad1.nii.gz,1 ] --transform Rigid[ 0.1 ] --metric MI[ /Users/neurouser1/Documents/TMS_Aphasia/qsiprepout_dwionly/qsiprep/sub-TMSA38/ses-BRAINRESEARCHCOSLETT/dwi/sub-TMSA38_ses-BRAINRESEARCHCOSLETT_space-T1w_dwiref.nii.gz,/Users/neurouser1/Documents/TMS_Aphasia/Impute/sub-TMSA38/sub-TMSA38_ImputedImage_22controls_rad1.nii.gz,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox`

Here is the output:
![Capture_TMSA38_rigidtransformonly](https://user-images.githubusercontent.com/40644674/182455725-dc3759c5-7941-41ac-99dc-5c20a10294d2.PNG)

The other transformations or changing the SyN parameters gave the following output:

t = sr

![Capture_TMSA38 sr](https://user-images.githubusercontent.com/40644674/182455859-532af607-73dd-44a8-bc0c-695c5692d960.PNG)

t = br
![Capture_TMSA38 br](https://user-images.githubusercontent.com/40644674/182455894-6bf86969-e845-4ec9-890f-e89e9428a8a5.PNG)

t= a

![Capture_TMSA38_a](https://user-images.githubusercontent.com/40644674/182455957-b2ed5721-e48e-47d7-9013-3eaed0f27c1d.PNG)

Is there a way to change any parameters in the rigid transform code to make the images better aligned? Should I change the Rigid 0.1 value or the shrink factor? 

Thank you
Best,
Apoorva

**Comment by gdevenyi** [comment]
Rather than attempting to hard-code some appropriate calls, may I suggest:
https://github.com/CoBrALab/minc-toolkit-extras/blob/master/antsRegistration_affine_SyN.sh
+ the required https://github.com/CoBrALab/minc-toolkit-extras/blob/master/ants_generate_iterations.py

for an optimized registration pyramid. See `--help` for much control of what kind of registrations to do.

**Comment by cookpa** [comment]
It's hard to tell with the overlays how good or bad the alignment is. The T1w is tightly masked, and the contrasts are different, so seeing some "stuff" on the EPI under the T1w might not be a sign of bad registration. How do the sulcal and gyral boundaries look?

**Comment by akelkar26** [comment]
The sulcal and gyral boundaries of the two images align well with each other. 

Thank you for the resources @gdevenyi. I will go through them
