### ISSUE TITLE
bugs of antsMultivariateTemplateConstruction2.sh

### ISSUE THREAD

**Issue by gylao** [ANTsX/ANTs#1404]
Hi, 
I tried to use two modalities (T1 and QSM) to construct template. I followed the example and write a .csv file [here](https://github.com/ANTsX/ANTs/files/9180415/group6_table_new.csv), which contains the absolute path of two modalities of different subjects.
However, I met problem when the script tried to initialize the template of the second modality while the template of the first modality was successfully initialized. Here is the logs and the command.
![1658746330861](https://user-images.githubusercontent.com/45264218/180760930-69a5e512-80d2-4e8c-a134-134e51cbed76.png)

![1658746330851](https://user-images.githubusercontent.com/45264218/180760656-1dbc3f49-4e1f-4aab-a59d-d4937e3fea38.png)

`antsMultivariateTemplateConstruction2.sh -d 3 -o {save_name} -a 0 -n 0 -c 2 -g 0.1 -b 1 -t SyN -m CC -i 5 -j 10 -r 1 -w 1x0.5 -q 80x60x40x20 -k 2 {table_name}`

It seems that the script read the .csv file by mistake (the .nii file become ".niiii" file). I have checked the .csv file for many time but still cannot find out the problem. I can share the example of the data if necessary.

Thanks in advance!

**Comment by gdevenyi** [comment]
Looks like your CSV is broken, it has non-standard line terminators:
```
$ file group6_table_new.csv 
group6_table_new.csv: ASCII text, with CRLF line terminators
```

Use a different piece of software to generate it.

In the future, to get proper support, please provide the *complete* command used, and *complete* log, in text, rather than screenshots.

**Comment by cookpa** [comment]
Excel (at least on Mac) writes CSV files with CRLF line terminators even if you don't choose the MS DOS CSV format. This can be fixed by `dos2unix`, or try

```
cat input.csv | tr -d '\r' | tee inputFixed.csv
```

**Comment by gylao** [comment]
> Looks like your CSV is broken, it has non-standard line terminators:
> 
> ```
> $ file group6_table_new.csv 
> group6_table_new.csv: ASCII text, with CRLF line terminators
> ```
> 
> Use a different piece of software to generate it.
> 
> In the future, to get proper support, please provide the _complete_ command used, and _complete_ log, in text, rather than screenshots.

Thanks a lot for your advice! The format of .csv file is the key! I will take care to provide complete log and command in text next time. Thanks again!

**Comment by gylao** [comment]
> Excel (at least on Mac) writes CSV files with CRLF line terminators even if you don't choose the MS DOS CSV format. This can be fixed by `dos2unix`, or try
> 
> ```
> cat input.csv | tr -d '\r' | tee inputFixed.csv
> ```

This command help a lot! Thank you for your help!
