### ISSUE TITLE
No impact of the --use-estimate-learning-rate-once (-l) flag

### ISSUE THREAD

**Issue by devDonnn** [ANTsX/ANTs#1405]
The flag `--use-estimate-learning-rate-once` does not seems to provide any changes to the final output of the `antsRegistration`. Isn't it fully implemented? I see it is part of the `parser` but cannot find where it is implemented. Thanks!

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/blob/04a018dc5308183b455194a9a5b14ffe1b0edf5f/Examples/antsRegistrationTemplateHeader.h#L442-L454

**Comment by devDonnn** [comment]
Thanks. I have found this too but why this option does not have any impact on the final results?

**Comment by cookpa** [comment]
It doesn't have any impact at all? You get the exact same results both ways?

**Comment by devDonnn** [comment]
Yes. I ran twice in repro mode with `--use-estimate-learning-rate-once` and without. The verbose output did not change as well.

**Comment by cookpa** [comment]
That's interesting. Can you share a reproducible example with code and data?

**Comment by devDonnn** [comment]
I have used the following code to enable `--use-estimate-learning-rate-once`:


antsRegistration 
  --verbose 1 
  --dimensionality 3 
  --float 0 
  --collapse-output-transforms 1 
  --output [ movingToFixed_, movingToFixed_Warped.nii.gz, movingToFixed_ InverseWarped.nii.gz ] 
  --interpolation Linear 
  --use-histogram-matching 0 
  --use-estimate-learning-rate-once 1 
  --winsorize-image-intensities [ 0.005,0.995 ] 
  
  --initial-moving-transform [ fixedImage.nii.gz,movingImage.nii.gz,1 ] 
  
  --transform Rigid[ 0.1 ] 
  --metric MI[ fixedImage.nii.gz,movingImage.nii.gz,1,32,Regular,0.25 ] 
  --convergence [ 1000x500x250x100,1e-6,10 ] 
  --shrink-factors 8x4x2x1 
  --smoothing-sigmas 3x2x1x0vox 
 
  --transform Affine[ 0.1 ] 
  --metric MI[ fixedImage.nii.gz,movingImage.nii.gz,1,32,Regular,0.25 ] 
  --convergence [ 1000x500x250x100,1e-6,10 ] 
  --shrink-factors 8x4x2x1 
  --smoothing-sigmas 3x2x1x0vox 
  
  --transform SyN[ 0.1,3,0 ] 
  --metric CC[ fixedImage.nii.gz,movingImage.nii.gz,1,4 ] 
  --convergence [ 100x70x50x20,1e-6,10 ] 
  --shrink-factors 8x4x2x1 
  --smoothing-sigmas 3x2x1x0vox

I may misunderstand how to use this option. Here is an example with the code and data: [Example](https://drive.google.com/drive/folders/1wlkYScFM6YSExUbqvLj9ZFl6evxh6oB-?usp=sharing)

**Comment by cookpa** [comment]
Thanks for the example, I'll look into it.

**Comment by cookpa** [comment]
I can reproduce this. `--use-estimate-learning-rate-once 1` and `--use-estimate-learning-rate-once 0` produce identical results for me. I don't think it's a feature we use much, but pinging @ntustison @stnava in case they have knowledge of why this could be.

**Comment by ntustison** [comment]
See [here](https://github.com/ANTsX/ANTs/pull/1411).  Let me know if you have any additional questions.

**Comment by cookpa** [comment]
I think this is resolved now. Thanks for the report @devDonnn.
