### ISSUE TITLE
MeasureImageSimilarity syntax issues

### ISSUE THREAD

**Issue by mbenabou** [ANTsX/ANTs#1408]
**Describe the problem**

I am trying to use the MeasureImageSimilarity function to compare a T1-weighted MRI volume to a diffusion MRI volume which I registered to the T1-weighted volume (to see how well the registration worked). When I follow the syntax that `MeasureImageSimilarity --help` describes, I run into problems when I try to type inside of the brackets. I can't seem to type the paths to my nii.gz files. When I click tab to auto-complete, the options that come up are ARGC, CDPATH, etc. (143 possibilities total if that helps clarify the potential source of error).

**To Reproduce**

Here is what I type in the terminal:

`MeasureImageSimilarity -d 3 -m MI[...` 

The bracket is where I get the problems described above.

**System information (please complete the following information)**

 - OS: Mac OS
 - OS version: 12.4
 - Type of system: Laptop

**ANTs version information**
 - ANTs code version: v2.4.0.post3-gf5e6679
 - ANTs installation type: Compiled from source

**Comment by gdevenyi** [comment]
This sounds like an issue with your shell configuration.  Since it's OSX, I'm guessing Zsh. Try bash instead.

**Comment by mbenabou** [comment]
> This sounds like an issue with your shell configuration. Since it's OSX, I'm guessing Zsh. Try bash instead.

I changed to a bash shell and had the same issue. However, I did just try now to type the paths to the nii.gz files in quotes and I can now type them. However, the issue now is that it says that the fixed image file doesn't exist even though the path is correct and the file does exist. Thank you for your help!

Here is what I typed and the corresponding error:
`MeasureImageSimilarity -d 3 -m MI["T1w/T1w_acpc_dc_restore_brain","Outcome/ANTs/diffusion2T1w_ANTs_Aging1.nii.gz",1.0,32,Random,1] -v 1
`
` file T1w/T1w_acpc_dc_restore_brain does not exist . `
`ERROR:  The fixed image file T1w/T1w_acpc_dc_restore_brain does not exist.`

**Comment by cookpa** [comment]
Just to be clear, `MeasureImageSimilarity` doesn't do anything except read the information the shell gives it after you press enter. Any issues before that are shell issues, not ANTs issues.

Macs now use zsh by default, which handle square brackets and auto complete differently than bash. I've found that bash will autocomplete if there is a space after the square brackets. For example, `-m MI[ t1` followed by tab will autocomplete `t1.nii.gz` on my machine.

I think the error above, 

```ERROR: The fixed image file T1w/T1w_acpc_dc_restore_brain does not exist.```

is caused by a missing extension, it should be `T1w/T1w_acpc_dc_restore_brain.nii.gz`.

**Comment by mbenabou** [comment]
> Just to be clear, `MeasureImageSimilarity` doesn't do anything except read the information the shell gives it after you press enter. Any issues before that are shell issues, not ANTs issues.
> 
> Macs now use zsh by default, which handle square brackets and auto complete differently than bash. I've found that bash will autocomplete if there is a space after the square brackets. For example, `-m MI[ t1` followed by tab will autocomplete `t1.nii.gz` on my machine.
> 
> I think the error above,
> 
> `ERROR: The fixed image file T1w/T1w_acpc_dc_restore_brain does not exist.`
> 
> is caused by a missing extension, it should be `T1w/T1w_acpc_dc_restore_brain.nii.gz`.

Thank you so much! I just overlooked the suffix on that T1 image haha. The command works now.
