### ISSUE TITLE
How to use antsRegistration just for ACPC alignment?

### ISSUE THREAD

**Issue by zhengchencai** [ANTsX/ANTs#1409]
Hello,

Thanks for developing this nice tool. I'd like to reorient (ACPC alignment) and crop (remove the neck and even some shoulder) T1w using ANTs, since some of my T1w are tilted and FOV is quite large even covering the shoulder. One simple way I could think of is to do a rigid body registration to an MNI template. So I tried the following,

```
antsRegistrationSyN.sh -d 3 -f tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz -m input_T1w.nii.gz -o mni.nii.gz -n 16 -t r -p f
```

It works but it seems linear interpretation is also applied which makes the reoriented image looks smoothed. I might be wrong, do you think there is a better way to do this task?

Thanks a lot

**Comment by gdevenyi** [comment]
1. Technically speaking, AC-PC alignment is a two-point manual registration using landmarks, and not equivalent to rigid registration. I'm not aware of an "automatic" AC-PC method.
2. The only way to do a non-resampled transformation is to modify the sform/qform of the image, which ANTs does not have the feature set to do. You will need to investigate other tools.

**Comment by zhengchencai** [comment]
Thanks @gdevenyi. I agree that ACPC alignment should not resample T1w but only modify sform/qform. In HPCpipelines there is a sort of alignment based on rigid body registration [ACPCAlignment.sh](https://github.com/Washington-University/HCPpipelines/blob/master/PreFreeSurfer/scripts/ACPCAlignment.sh), but spline interpolation is used to resample T1w. I guess if it is necessary to preserve the original intensity, I will need to apply a transformation matrix to modify the sform/qform as you mentioned.

**Comment by gdevenyi** [comment]
> In HPCpipelines there is a sort of alignment based on rigid body registration ACPCAlignment.sh,

Yeah I'm aware that HCP calls their registration is called ACPC, but if you look at what they do, their use FLIRT to generate a full affine (12-parameter) registration to the FSL1MM MNI model, followed by a call to `aff2rigid` on that transform, which approximates a rigid ACPC transform by assuming perfect registration between the image and the template using the FLIRT registration, and re-computing a transform using the approximated matching points.

**Comment by cookpa** [comment]
Linear interpolation is hard coded into the `antsRegistrationSyN.sh` script, but you can change `--interpolation Linear` to something else like `BSpline`.
