### ISSUE TITLE
Is there a way to preserve original resolution?

### ISSUE THREAD

**Issue by Immiora** [ANTsX/ANTs#1410]
I am trying to align a CT to and MRI scan. The CT is sub-millimeter resolution, which I would like to preserve. MRI is 1x1x1, and the CT is .45x.45x1.

Is it possible to perform antsRegistration while preserving the original resolution of the CT?

**Comment by gdevenyi** [comment]
Upsample the MRI either before or after registration and use that as the reference `-r` for antsApplyTransforms

**Comment by cookpa** [comment]
Correct, you can upsample the reference image before calling `antsApplyTransforms`.
