### ISSUE TITLE
--initial-moving-transform argument

### ISSUE THREAD

**Issue by sourena-s** [ANTsX/ANTs#1413]
I have been using SyN to register a batch of T1-weighted brain images to a template. In some cases (less than ~5% of subjects), the affine part of the registration fails. So for these subjects, I tried to convert a third-party affine matrix into iTK and then initialize SyN using the --initial-moving-transform argument.

Even though the affine seems to work well (as I checked with antsApplyTransforms, below figure: above), plugging it into SyN doesn't provide good results (bottom).

-The original registration command:

_antsRegistration -d 3 --float 1 --verbose 1 -u 1 -w [ 0.01,0.99 ] -z 1 \
                -r [ template.nii.gz,subject-t1.nii.gz,1 ] -x [ template-mask.nii.gz,subject-t1-mask.nii.gz] \
      		--initial-moving-transform affine-full-FOV.mat \
	        -t SyN[ 0.1,3,0 ]  -m CC[ template.nii.gz,subject-t1.nii.gz,1,4 ] -c [ 100x100x70x20,1e-9,15 ] -f 6x4x2x1 -s 4x2x1x0vox  \
		-o ./[syn_a_,syn_a_warped.nii.gz]_

-I reduced the SyN iterations/gradient step size to investigate the registration components:

_antsRegistration -d 3 --float 1 --verbose 1 -u 1 -w [ 0.01,0.99 ] -z 1 \
		-r [ template.nii.gz,subject-t1.nii.gz,1 ] -x [ template-mask.nii.gz,subject-t1-mask.nii.gz] \
       		--initial-moving-transform affine.mat \
	        -t SyN[ 0.001,3,0 ]  -m CC[ template.nii.gz,subject-t1.nii.gz,1,4 ] -c [ 1,1e-9,15 ] -f 6 -s 4vox  \
		-o ./[syn_b_,syn_b_warped.nii.gz]_

![Screenshot from 2022-08-12 15-06-39](https://user-images.githubusercontent.com/24783447/184361354-7c492f52-8440-4f6f-b20d-7a481b771e9c.png)

**Comment by cookpa** [comment]
Try removing the -r option, you may be overriding your initial transform with the default center of mass initialization.

**Comment by sourena-s** [comment]
Thanks a lot, problem solved!
Sourena

**Comment by stnava** [comment]
ants initialization will fail if the images have negative intensities.    I usually normalize to [0,1].

**Comment by sourena-s** [comment]
The results look great:
![Screenshot from 2022-08-12 17-49-05](https://user-images.githubusercontent.com/24783447/184900518-aeb07531-bfea-4265-8ca0-0a6d1aa3c9a1.png)
