### ISSUE TITLE
Transform Field for ANTSJacobian / CreateJacobianDeterminantImage Troubleshooting

### ISSUE THREAD

**Issue by isabelannwingert** [ANTsX/ANTs#1423]
Hello,

My team and I are interested in creating Jacobian images to compare different registration methods. 

I have ran registrations with the following types of transformations: `(-sr, -br, -a, and -s)` with `antsRegistrationSyN.sh` and `antsRegistrationiSyNQuick.sh`. I was then comparing the two functions, `CreateJacobianDeterminantImage` and `ANTSJacobian`. 

I have created what looks like a Jacobian image and attached a screenshot of the image (created with `ANTSJacobian`, with the command:

`ANTSJacobian 3 100007_t0_antsSynQuick_rigid_deformableWarped.nii.gz 100007_t0_antsSynQuick_rigid_deformable_Jacobian.nii.gz 1 /gpfs/fs001/cbica/comp_space/wingerti/Test-Retest/Protocols/brainmage_batch_t1/100007_t0/100007_t0_t1_brain_mask.nii.gz 1`

 However, upon closer inspection of my output and the arguments for the command, I was expecting a transformation field/control point to be required, and am therefore now doubtful of my output from the above command. **Is there a way to change the command to get the Jacobian? And, is there a way to get a transform field after running deformable type transformation with ANTS?**

Thanks,

Isabel

![image](https://user-images.githubusercontent.com/43824649/191825998-1dffdd25-5f92-4c71-a56e-2127055840ec.png)
![image](https://user-images.githubusercontent.com/43824649/191826297-e122263b-92f4-45ff-be5a-935d755d52e2.png)

**Comment by cookpa** [comment]
ANTSJacobian is deprecated, use `CreateJacobianDeterminantImage`. It needs to be given the warp field produced by `antsRegistration`. The warp fields are output from the `antsRegistrationSyN[Quick].sh` scripts for all deformable registrations.

More details here, with links to examples

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

**Comment by isabelannwingert** [comment]
Hello again, thank you for your reply! This webpage helps a lot.

Just to be clear, the warp fields / transform fields are the outputs `*1Warp.nii.gz` and `*InverseWarp.nii.gz`?

And I would set up the following command?
`CreateJacobianDeterminantImage imageDimension deformationField outputImage [doLogJacobian=0] [useGeometric=0]`
`CreateJacobianDeterminantImage 3 100007_t0_antsSynQuick_rigid_deformable1Warp.nii.gz 100007_t0_antsSynQuick_rigid_deformable_logjacobian.nii.gz 1`

Does this apply to other types of transformations (affine, syn, and rigid)? I assume it's only for affine as of right now, as for rigid it should be 0 since it doesn't distort the voxel shape, but not sure for syn. It also helps that the Jacobian is global, so if there's any other suggestions you have, feel free to let me know!

**Comment by cookpa** [comment]
> *1Warp.nii.gz and *InverseWarp.nii.gz

These are the warp fields for the deformable registration.

> CreateJacobianDeterminantImage 3 100007_t0_antsSynQuick_rigid_deformable1Warp.nii.gz 100007_t0_antsSynQuick_rigid_deformable_logjacobian.nii.gz 1

This would produce a log Jacobian output using the default method, yes.


>Does this method of creating a Jacobian image only apply to other types of transformations (affine, syn, and rigid)? I assume it's only for affine as of right now, as for rigid it should be 0 since it doesn't distort the voxel shape, but not sure for syn. It also helps that the Jacobian is global, so if there's any other suggestions you have, feel free to let me know!

I believe the program only works on deformation fields, but you can convert / compose transforms into a single warp field with `antsApplyTransforms`.  Call it the same way you would to resample the moving image - but instead of `-o deformedimage.nii.gz` use `-o [ compositeDeformationField.nii.gz, 1 ]`.


> And finally, for future registrations: Would I not have to set up the -z argument in my registration command for ANTs (referred to below)? It looks like that option suppresses "transforms" which I'm not sure if they are the same thing as transform fields or something else (sorry for my naivete).

It's unlikely you would want to change this from its default.

**Comment by isabelannwingert** [comment]
Awesome. Thank you so much for your clarification. 

As for one last request, can you provide an explanation on the arguments doLogJacobian and UseGeometric?
