### ISSUE TITLE
antsRegistrationSyN.sh providing inconsistent results

### ISSUE THREAD

**Issue by lbailey25** [ANTsX/ANTs#1426]
Dear users,

I am using antsRegistrationSyN.sh to register some 3D functional data to a template (MNI152) image. Here is the call:

```
  antsRegistrationSyNQuick.sh -d 3 \
                              -t s \
                              -f template_image.nii.gz \
                              -m func_image.nii.gz \
                              -o func2standard_mat_ \
                              > ${temp_log} 2>&1 # this line prints output to a temporary txt file instead of terminal 
```

If I run this command, I get the func image transformed to the template (with some margin of error). If I run the command again, _making no changes whatsoever_,  I get slightly different results. I've run this many times, always with slightly differing results.

Is this normal behaviour for antsRegistrationSyN.sh? If so, would it be possible/logical to run the command many times and then implement the "average" transformation matrices?

**EDIT** The attached image shows 2 sets of results generated by the above call. One set of results is shown in red, the other in blue, the purple area shows where they overlap.

![Screenshot from 2022-09-30 18-41-13](https://user-images.githubusercontent.com/39773668/193360088-412c66b2-20c7-4565-a20e-ace5b09c57c1.png)

**Comment by gdevenyi** [comment]
It's in the wiki.

https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues

**Comment by cookpa** [comment]
Directly registering BOLD to a group template T1w is likely to have high uncertainty. You can implement an ensemble averaging approach of repeat runs but it would be better to constrain the problem by using other information from each individual. It's best to distortion-correct the BOLD data using field maps, then do a rigid registration to a structural image acquired in the same session, then use the structural image to do a nonlinear registration to one of the MNI152 atlases. You can combine all these warps to get the BOLD data into MNI space.

**Comment by lbailey25** [comment]
Thank you both, these comments were very helpful
