### ISSUE TITLE
CMake Error at ANTS.cmake:41 (find_package)

### ISSUE THREAD

**Issue by neurosurd** [ANTsX/ANTs#1430]
Hi All,
Im getting the following error during both Superbuild or manual build.
```-- Building ANTS version "v2.4.1.post7-g71c9890"
CMake Error at ANTS.cmake:41 (find_package):
  By not providing "FindITK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ITK", but
  CMake did not find one.

  Could not find a package configuration file provided by "ITK" with any of
  the following names:

    ITKConfig.cmake
    itk-config.cmake

  Add the installation prefix of "ITK" to CMAKE_PREFIX_PATH or set "ITK_DIR"
  to a directory containing one of the above files.```
I've attached the following files. Please advise.


[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/9790046/CMakeCache.txt)
[cmake.log](https://github.com/ANTsX/ANTs/files/9790047/cmake.log)
[build.log](https://github.com/ANTsX/ANTs/files/9790048/build.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/9790061/CMakeOutput.log)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/9790062/CMakeError.log)

**Comment by gdevenyi** [comment]
Please share the exact commands you are running and the complete logs.

**Comment by cookpa** [comment]
And also the system you're trying to build on.

**Comment by cookpa** [comment]
I've compiled [77b8f2a](https://github.com/ANTsX/ANTs/commit/77b8f2ad1fa0c4172edba451e8e52d3a1bff33ac) on my Mac, and the CI build has completed successfully (Ubuntu). So I think it's something about this particular system.

**Comment by cookpa** [comment]
Is `CMAKE_PREFIX_PATH` or `ITK_DIR` set in the environment? I'm just guessing at why it's not looking in the usual place. It seems to build ITK just fine, but then somehow can't find it. Very odd

**Comment by neurosurd** [comment]
Thank you for the response. Im trying to install it on RHEL8. Previously i installed it on a RHEL7 system without any issues. I used the superbuild script and tried the installation without the script as well. 
The above paths are not set in the environment. Ive attached all the relevant logs. Is there anything else that i need to attach?

**Comment by gdevenyi** [comment]
Please provide the complete commands and logs.

**Comment by cookpa** [comment]
The latest release failed to build on CentOS, so I will be looking into this further when I have time https://github.com/ANTsX/ANTs/actions/runs/3269597905

I think it must be something to do with the recent ITK bump, because [v2.4.1](https://github.com/ANTsX/ANTs/releases/tag/v2.4.1) built successfully.

**Comment by cookpa** [comment]
I think it might be fixable by installing Python3 - will check

**Comment by neurosurd** [comment]
Confirmed! Thank you !
