### ISSUE TITLE
antsRegistration fails without specifications.

### ISSUE THREAD

**Issue by smoia** [ANTsX/ANTs#1433]
**Describe the problem**

I'm trying to run an old antsRegistration snippet on a fresh build (ANTs 2.4.1), but the program fails calling for a segmentation error.
I tried on a real dataset, and then tried again trying to register a template to itself (to be able to share data), with the same results.
I even re-built ants, just in case. 

**To Reproduce**

CMD:
```
antsRegistration -d 3 -r [../reg/MNI152_1mm_T1_brain.nii.gz,../reg/MNI152_1mm_T1_brain.nii.gz] -o [../reg/sub-TIMESwp11s001_ses-T1_acq-mp2rage_T1w_brain2std,../reg/sub-TIMESwp11s001_ses-T1_acq-mp2rage_T1w_brain2std.nii.gz,../reg/sub-TIMESwp11s001_ses-T1_stdd2acq-mp2rage_T1w_brain.nii.gz] -x [../reg/MNI152_1mm_T1_brain_mask.nii.gz,../reg/MNI152_1mm_T1_brain_mask.nii.gz] -n Linear -u -w [0.005,0.995] -t Rigid[0.1] -m MI[../reg/MNI152_1mm_T1_brain.nii.gz,../reg/MNI152_1mm_T1_brain.nii.gz,1,48,Regular,0.1] -c [1000x500,1e-6,10] -f 8x4 -s 3x2vox -z 1 -v 1
```
Note that I used both `-u 0` and `-u` to the same result.

"Verbose" output:
```
All_Command_lines_OK
Segementation error (core dump created)
```

Files attached.

**System information (please complete the following information)**

 - OS: Ubuntu
 - OS version: 20.04.5
 - Type of system: laptop

**ANTs version information**
 - ANTs code version: v2.4.1
 - ANTs installation type: Compiled from source

**Additional information**

[MNI152_1mm_T1_brain.nii.gz](https://github.com/ANTsX/ANTs/files/9802934/MNI152_1mm_T1_brain.nii.gz)
[MNI152_1mm_T1_brain_mask.nii.gz](https://github.com/ANTsX/ANTs/files/9802935/MNI152_1mm_T1_brain_mask.nii.gz)

**Comment by smoia** [comment]
I tried to add `--float 0` as recommended, and I get this issue (same with `--float 1`):

```
All_Command_lines_OK
Using double precision for computations.
Exception Object caught: 

itk::ExceptionObject (0x555891501f30)
Location: "unknown" 
File: /home/nemo/bin/ANTs-2.4.1/Utilities/antsCommandLineParser.h
Line: 133
Description: ITK ERROR: CommandLineParser(0x5558915009d0): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert '../reg/MNI152_1mm_T1_brain.nii.gz' to type 'b' as Unmapped Type
```

**Comment by cookpa** [comment]
I think there's two problems here. One is that the argument to `-r` is bad, it should be `-r [ fixed, moving, initOpt ]`, eg `-r [ [../reg/MNI152_1mm_T1_brain.nii.gz,../reg/MNI152_1mm_T1_brain.nii.gz,1 ]`.

The other problem is that `antsRegistration` now appears to fail unless `--float 1/0` is used.

**Comment by ntustison** [comment]
Okay, you found a bug (fix [here](https://github.com/ANTsX/ANTs/commit/4123595a089b5bc48bcb6f73782e956a4b1eeaed)) which my suggestion circumvents.  That fact that you got an error with my suggestion points to a separate issue.  Is this a zsh issue in which case you would need to do (omit relative paths to simplify debugging):

```
antsRegistration -d 3 -r "[MNI152_1mm_T1_brain.nii.gz,MNI152_1mm_T1_brain.nii.gz,1]" -o "[sub-TIMESwp11s001_ses-T1_acq-mp2rage_T1w_brain2std,sub-TIMESwp11s001_ses-T1_acq-mp2rage_T1w_brain2std.nii.gz,sub-TIMESwp11s001_ses-T1_stdd2acq-mp2rage_T1w_brain.nii.gz]" -x "[MNI152_1mm_T1_brain_mask.nii.gz,MNI152_1mm_T1_brain_mask.nii.gz]" -n Linear -u -w "[0.005,0.995]" -t "Rigid[0.1]" -m "MI[MNI152_1mm_T1_brain.nii.gz,MNI152_1mm_T1_brain.nii.gz,1,48,Regular,0.1]" -c "[1000x500,1e-6,10]" -f 8x4 -s 3x2vox -z 1 -v 1
```

**Comment by smoia** [comment]
@cookpa indeed fixing the argument to the `-r` flag fixed the issue, but without `--float` it fails. I guess that once the bug fix gets released, that'll do!

@ntustison that was fast! Thank you for the fix!
Will there be a new tag/release with your fix? I'm building a container and I'm trying to be as reproducible as possible.

**Comment by cookpa** [comment]
@smoia yes this warrants a bump to 2.4.2, I will try to do that today or tomorrow

**Comment by smoia** [comment]
Thank you both very much!
I'll build the new version and test it tomorrow, and if it works I'll close this issue!

**Comment by cookpa** [comment]
Fix in, release done. Thanks everyone
