### ISSUE TITLE
Inputs do not occupy the same physical space

### ISSUE THREAD

**Issue by MRIDude** [ANTsX/ANTs#1440]
I have been getting an unexpected error

"
*Stage3_level3_Iter0020.nii.gz
1DIAGNOSTIC,    20, -7.742549015046e-01, 3.934743917494e-04, 4.0730e+02, 1.7051e+01, 
  Elapsed time (stage 2): 419.245

itk::ExceptionObject (0x55e6f6406f20)
Location: "unknown" 
File: /data/jsp/human2/fcMRI/Aaron/locals/Ubuntu20.04/src/ANTs-2.4.2/SuperBuild/staging/include/ITK-5.3/itkImageToImageFilter.hxx
Line: 218
Description: ITK ERROR: ImageToImageFilter(0x55e6f619aeb0): Inputs do not occupy the same physical space! 
InputImage Origin: [9.7000000e+01, 1.3300000e+02, -7.1000000e+01], InputImage_1 Origin: [9.8000000e+01, 1.3400000e+02, -7.2000000e+01]
	Tolerance: 2.0000000e-06
InputImage Spacing: [2.0000000e+00, 2.0000000e+00, 2.0000000e+00], InputImage_1 Spacing: [1.0000000e+00, 1.0000000e+00, 1.0000000e+00]
	Tolerance: 2.0000000e-06
"

From the following command

`antsRegistration -d 3 -r ${outroot}_affine0GenericAffine.mat \
		--write-interval-volumes 10 \
		-m CC\[ $refT1, $movT1, 1 , 4 \] \
		-m CC\[ $refT2, $movT2, 1 , 4 \] \
		--write-interval-volumes 10 \
		-x [ $refmask,$movmask ] \
		-t SyN\[ 2, 3, 2 \] \
		-c 200x200x200x200x100 \
		-s 5x4x3x2x1vox \
		-f 10x8x6x4x2\
		-m CC\[ $refT1, $movT1, 1 , 4 \] \
		-m CC\[ $refT2, $movT2, 1 , 4 \] \
		-t SyN\[ .5, 3, 2 \] \
		-c 200x200x100 \
		-s 3x2x1vox \
		-f 6x4x2\
		-m CC\[ $refT1, $movT1, 1 , 4 \] \
		-m CC\[ $refT2, $movT2, 1 , 4 \] \
		-t SyN\[ .1, 3, 0 \] \
		-c 50x30x20 \
		-s 2x1x0vox \
		-f 4x2x1 \
		--random-seed 1 \
		-o [ $outroot, test_nonlinear.nii.gz ] \
		-v 1`

This only happens when i added the shrink factor of 1 to the very last stage.  I have the programs outputting the warped images every 10 iteration. The images look great at the end

**Comment by gdevenyi** [comment]
You need 0 iterations in the prior syn at shrink 1 so the deformation field is resampled to that resolution.

I.e. adjacent SyN transforms in registration must have matching shrinks

**Comment by cookpa** [comment]
That's correct, the shrink factors define the resolution of the virtual space where the registration happens, to avoid these problems without doing registration at full resolution you can use `-s NxMx....x1` with `-c AxBx....x0`.
