### ISSUE TITLE
Warp and reorient a diffusion tensor image tutorial -- ReorientTensorImage

### ISSUE THREAD

**Issue by aplumley** [ANTsX/ANTs#1441]
Hello,

I was following the **_Warp and reorient a diffusion tensor image_** instructions, and at the last stage (Reorienting the tensor), the instruction says use the command "**ReorientTensor**", which (at least on my ANTs - 2.1.0) does not exist, but **ReorientTensorImage** does. I think this could be a typo in the tutorial? 

Thanks!
Alix

**Comment by cookpa** [comment]
Yes that's a mistake, fixed now. Thanks
