### ISSUE TITLE
Script folder not installed when compiling with -DCMAKE_BUILD_TYPE=RelWithDebInfo

### ISSUE THREAD

**Issue by mathdugre** [ANTsX/ANTs#1448]
I am trying to build the source with the cmake flag `-DCMAKE_BUILD_TYPE=RelWithDebInfo` to have debug information for ANTs.
The compilation succeed. However, the bash scripts from the [Scripts](https://github.com/ANTsX/ANTs/tree/v2.4.2/Scripts) folder are not install in `/opt/ants/bin`.

My question is: How can I build with `-DCMAKE_BUILD_TYPE=RelWithDebInfo` have still have the file from Scripts folder installed?
I thought of copying them from the source folder to the install folder (`/op/ants/bin`), but I was sure if that would cause issues.

**When did the error occur?**

[ ] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)
[x] Post-installation

**Build environment**
 - Dockerfile from commit https://github.com/ANTsX/ANTs/commit/6c729710ab2f545d0ab8f07393d180eb3eeb1900 (v2.4.2)

**ANTs version**

https://github.com/ANTsX/ANTs/commit/6c729710ab2f545d0ab8f07393d180eb3eeb1900 (v2.4.2)

**Build configuration and logs**

`-DCMAKE_BUILD_TYPE=RelWithDebInfo` passed during cmake configuration.

**Additional context**

When running the Dockerfile without modification, everything works as expected.
With that extra flag, the scripts are no longer installed.

**Comment by cookpa** [comment]
Copying them would be fine, but I think this is an easy fix in ANTS.cmake. I'm testing now
