### ISSUE TITLE
ERROR:  Invalid flag provided l ERROR:  Invalid command line flags found! Aborting execution.

### ISSUE THREAD

**Issue by Ahmed93Saber** [ANTsX/ANTs#1451]
**Describe the problem**

I get the following error messages:
ERROR:  Invalid flag provided l 
ERROR:  Invalid command line flags found! Aborting execution.

**To Reproduce**

the error appears when I run the example [here](https://github.com/JanaLipkova/s3)
specifically: line 114 in src/skull.py

**System information (please complete the following information)**

I am using Ubuntu 22.04
 - OS: [e.g. Mac OS]
 - OS version: [e.g. 10.15.1]
 - Type of system: [Desktop, laptop, HPC cluster, cloud instance,
   other]

I am running Ubuntu 22.04 using virtual box inside a windows 10 

**ANTs version information**
 - ANTs code version: [output of antsRegistration --version]
 - ANTs installation type: [Compiled from source, downloaded binary
   (from where?), installed by another package (which?), installed in
   container (URL?), other (please specify)]

ANTs Version: v2.4.2.post17-geb026b4

**Additional information**

**Comment by cookpa** [comment]
Does the tool you are using print an ANTs command that you can use to reproduce the error?

**Comment by Ahmed93Saber** [comment]
I am not sure if I completely understood you statement. 
I hope you get the answer from the ANTs command that produces the error:

`#!/bin/bash

# ANTS Registration
#-----------------------
m="$2"
out="$3"
f_in="$1"
m_in=${m}/atlas_t1.nii
name="$4"
out_this=${out}/${name}_atlas_reg.nii 
imgs=" $f_in, $m_in"
its=10000x1111x5
dim=3
antsRegistration -d $dim -r [ $imgs ,1] \
                         -m mattes[  $imgs , 1 , 32, regular, 0.05 ] \
                         -t translation[ 0.1 ] \
                         -c [1000,1.e-8,20]  \
                         -s 4vox  \
                         -f 6 -l 1 \
                         -m mattes[  $imgs , 1 , 32, regular, 0.1 ] \
                         -t rigid[ 0.1 ] \
                         -c [1000x1000,1.e-8,20]  \
                         -s 4x2vox  \
                         -f 4x2 -l 1 \
                         -m mattes[  $imgs , 1 , 32, regular, 0.1 ] \
                         -t affine[ 0.1 ] \
                         -c [$its,1.e-8,20]  \
                         -s 4x2x1vox  \
                         -f 3x2x1 -l 1 \
                         -o ${out_this}


antsApplyTransforms -d $dim -i $m_in -r $f_in -t ${out_this}0GenericAffine.mat -o ${out_this} --float 1 


# Apply transformation to the brain mask:
m_tmp=${m}/atlas_mask.nii
out_tmp=${out}/${name}_mask.nii
antsApplyTransforms -d $dim -i $m_tmp -r $f_in -t ${out_this}0GenericAffine.mat -o ${out_tmp}.gz --float 1
echo "Basic brain mask is saved to: ${out_tmp}.gz"

# Apply transformation to the brain tissue:
labels=(wm gm csf)
for label in ${labels[*]}
     do
     m_tmp=${m}/atlas_${label}.nii
     out_tmp=${out}/${name}_${label}.nii
     antsApplyTransforms -d $dim -i $m_tmp -r $f_in -t ${out_this}0GenericAffine.mat -o ${out_tmp}.gz --float 1
done`

**Comment by cookpa** [comment]
The `antsApplyTransforms` calls look quite wrong, but that might be a formatting error. To include code, enclose code blocks in triple backticks, like this

'''
your code
'''

but using backquotes ` in place of single quotes '.

**Comment by Ahmed93Saber** [comment]
sorry for the previous messy reply.
```
#!/bin/bash

# ANTS Registration
#-----------------------
m="$2"
out="$3"
f_in="$1"
m_in=${m}/atlas_t1.nii
name="$4"
out_this=${out}/${name}_atlas_reg.nii 
imgs=" $f_in, $m_in"
its=10000x1111x5
dim=3
antsRegistration -d $dim -r [ $imgs ,1] \
                         -m mattes[  $imgs , 1 , 32, regular, 0.05 ] \
                         -t translation[ 0.1 ] \
                         -c [1000,1.e-8,20]  \
                         -s 4vox  \
                         -f 6 -l 1 \
                         -m mattes[  $imgs , 1 , 32, regular, 0.1 ] \
                         -t rigid[ 0.1 ] \
                         -c [1000x1000,1.e-8,20]  \
                         -s 4x2vox  \
                         -f 4x2 -l 1 \
                         -m mattes[  $imgs , 1 , 32, regular, 0.1 ] \
                         -t affine[ 0.1 ] \
                         -c [$its,1.e-8,20]  \
                         -s 4x2x1vox  \
                         -f 3x2x1 -l 1 \
                         -o ${out_this}


antsApplyTransforms -d $dim -i $m_in -r $f_in -t ${out_this}0GenericAffine.mat -o ${out_this} --float 1 


# Apply transformation to the brain mask:
m_tmp=${m}/atlas_mask.nii
out_tmp=${out}/${name}_mask.nii
antsApplyTransforms -d $dim -i $m_tmp -r $f_in -t ${out_this}0GenericAffine.mat -o ${out_tmp}.gz --float 1
echo "Basic brain mask is saved to: ${out_tmp}.gz"

# Apply transformation to the brain tissue:
labels=(wm gm csf)
for label in ${labels[*]}
     do
     m_tmp=${m}/atlas_${label}.nii
     out_tmp=${out}/${name}_${label}.nii
     antsApplyTransforms -d $dim -i $m_tmp -r $f_in -t ${out_this}0GenericAffine.mat -o ${out_tmp}.gz --float 1
done


```

**Comment by cookpa** [comment]
Ah yes, the `-l` flag was deprecated and removed some time ago, as it didn't do anything. It can be safely removed from scripts.

**Comment by Ahmed93Saber** [comment]
Big thanks

**Comment by cookpa** [comment]
For background reference, #1411
