### ISSUE TITLE
N4BiasFieldCorrection parameters

### ISSUE THREAD

**Issue by marinaferalv** [ANTsX/ANTs#1466]
Dear experts,

I would like to use your N4BiasFieldCorrection algorithm to correct B1+ intensity inhomogeneities in 3T T1w and T2w images. I have several basic questions:

- Should I use the same N4BiasFieldCorrection parameters with T1w and T2w (3T) images? Could you recommend me some starting parameters for each pulse sequence?

- I have several datasets (i.e., comprised by T1w and T2w images) acquired in different 3T MRI scanners, how could I determine the optimal N4BiasFieldCorrection parameters for each of these datasets?

- Is there any quality control to confirm that B1+ intensity inhomogeneities have been reasonably corrected from T1w and T2w images?

Many thanks in advance.

Best regards,
Marina

**Comment by ntustison** [comment]
All these questions are related and, briefly, establishing definitively optimal bias correction parameters is difficult.  People have obviously proposed certain quantitative metrics but they're not a substitute for 1) simply looking at the images and see if they look better and 2) contextualizing performance in terms of downstream performance metrics, e.g., are these bias correction parameters improving segmentation?  My advice would be to start with the default parameters (which are pretty robust) and refine accordingly.

**Comment by marinaferalv** [comment]
Thank you very much for your response.

In our case (applying N4BiasFieldCorrection to T1 and T2 images), is it advisable to use the -x flag with a binary brain mask to perform the bias correction within the mask voxels?  

Best regards,
Marina

**Comment by ntustison** [comment]
It's probably not crucial but you should try it out to see if it helps for your data.
