### ISSUE TITLE
template building: ordering of shapeupdatetotemplate

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#1467]
I've been thinking again about template construction, and trying to wrap my head around certain steps in the process, before I ask my question, I summarize the steps as I understand them, reading through `antsMultivariateTemplateConstruction2.sh`, but `buildtemplateparallel` appears to be the same.

1. Register subjects to `template0`
2. Average subjects to produce `template1`
3. Sharpen `template1` to produce `template1_sharpen`
4. Average forward transforms (`*0GenericAffine` and `*1Warp.nii.gz`) to produce `average_affine` and `average_warp`
5. Multiply `average_warp` with negative gradient step to produce scaled pseudo inverse, `average_pseudo_inverse_warp`
6. Transform `average_pseudo_inverse_warp` by inverse of `average_affine` to produce `scaled_average_psuedo_inverse_warp`
7. Shape update `template1_sharpen` by applying 4 x `scaled_average_psuedo_inverse_warp` followed by inverse of `average_affine`

So, my question/confusion arises from the order of transformation application in step 7.

Consider the following situation:

- the translations and rotations of the subject to `template0` forward affines are large and mostly similar in direction and magnitude
- averaging is performed with `AverageAffineTransform` so that translations/rotations are retained

Under these conditions, I think it is obvious the `scaled_average_psuedo_inverse_warp` produced in step 6 no longer overlaps the anatomy in `template1` over which it is intended to shape update, as the inverse affine is applied after the warps.

Adjusting my example to the general case, I would expect in general the applied warp fields don't overlap their intended anatomy.

My questions are thus
- did I miss something else fundamental in the process? With averaging and pseudo-inverse, can I no longer concretely conceptualize the fields in this way?
- does my example violate some approximation in the conceptualization of the method such that under smaller affines it works?

Or:
- should the affine be applied first in step 7?
Or
- why scale the warp fields at all and keep step 7 as-is

Thanks for your help.

**Comment by cookpa** [comment]
The transforms are added to a stack. If you resample an image, internally a regular grid of points are warped from the reference space to the input space, to find the interpolated values at the corresponding locations in the input space.

The image is "pulled" into the reference space in this way. 

In the shape update case, the inverse affine is applied to both `scaled_average_psuedo_inverse_warp` and the template, which should align the physical coordinates - BUT the application of `average_affine` to `scaled_average_psuedo_inverse_warp` does not rotate the warp vectors. So if the initial template has a large net rotation, the shape update vectors may be in the correct location, but in the wrong direction.

This is one reason I always build an affine template before doing deformation - the template will converge closer to the average location / rotation of the inputs. 

It would be better to deal with this problem explicitly, of course. A general `antsReorientVectorImage` tool, to go with an updated `ReorientTensorImage`, would have multiple applications.

**Comment by gdevenyi** [comment]
> In the shape update case, the inverse affine is applied to both `scaled_average_psuedo_inverse_warp` and the template, which should align the physical coordinates 

But doesn't the order that its applied matter? In the shape update step above, the `scaled_average_psuedo_inverse_warp` is moved by the inverse of `average_affine` and then applied to `template1`, but at that point the `template1` has not had the inverse of `average_affine` applied yet, as it is the last step in the stack:

https://github.com/ANTsX/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L483

> This is one reason I always build an affine template before doing deformation - the template will converge closer to the average location / rotation of the inputs.

This is great advice, thanks.

**Comment by cookpa** [comment]
Yes, the order matters.

This stuff always melts my brain but I think the function is setting up what would be expected by `antsApplyTransforms` to apply an inverse transform. 

In a pairwise registration, the 1Warp and 1InverseWarp vectors are both stored in the physical space of the fixed image (of course, the vectors themselves are different). If the affine transform is A, and the forward warp is W, then to resample the moving to fixed space, for a point p in fixed space we need a point to interpolate at in moving space, A(W(p)). In moving space, applying inverse warp X and inverse affine B, we need to take point p' to an interpolated point in fixed space with X(B(p')). This is why the pseudo-inverse has the inverse of `average_affine` applied to it. 

I'm basing this logic on 

https://itk.org/Doxygen/html/classitk_1_1CompositeTransform.html

**Comment by cookpa** [comment]
I think part of the confusion is that it's hard not to mix the ideas of "push" and "pull" operations, because the image appears to be "pushed" to fixed space, and it makes sense to think of the transform stack that way.

Also, the "scaled_average_psuedo_inverse_warp" is not really an inverse warp, it's an approximation initially defined in the space of the old template, which is now the "moving" image. 

Here's a quick example where I compressed a template along y, then rotated it, then registered back with rigid + SyN (so the scaling is reflected in the warp field not the affine transform). Forward transform W is then bottom left, and X bottom right.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/611507/208768861-671acf64-cd24-4b75-8fc9-960003863a94.png">
