### ISSUE TITLE
Radius parameter

### ISSUE THREAD

**Issue by ninusch** [ANTsX/ANTs#1471]
I still don't really understand what the radius parameters (aff_sampling/syn_sampling) do, since shouldn't the size of a point that is moved for registration be determined by the resolution, thus change for each level in multi-resolution? So which sizes are actually denoted by the radius parameters?

**Comment by cookpa** [comment]
The radius is the neighborhood, in voxels, over which the metric is calculated. So `CC[4]` uses a 9x9x9 grid of points (radius of 4 in all directions, plus the center). The physical spacing of those points will vary based on the resolution.

**Comment by ninusch** [comment]
Ah okay, thanks! But then next, the metric will be calculated for a 9x9x9 grid of points that is 1 pixel further? or 9 pixel further? So will the image be scanned by 9x9x9 grids or divided into 9x9x9 grids that are then treated respectively, independent from each other?
And is this done only to save computational power in order to not look at the whole image at once?

**Comment by cookpa** [comment]
I think it's more like convolution, the neighborhood is centered around each point.

https://itk.org/Doxygen/html/classitk_1_1ANTSNeighborhoodCorrelationImageToImageMetricv4.html

The points are the voxel centers in the downsampled space. So the radius will cover a larger physical volume at coarser resolutions. If this is a problem, you'd have to set up multiple stages and change the radius for each one.
