### ISSUE TITLE
Bug? antsRegistration: Warps provided to --initial-moving-transform are not merged with estimated warps from registration with --collapse-output-transforms 1

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#1472]
Reopening as a sub question of #1223 since a workaround was provided, but the original question never answered either way.

When I provide additional affine transforms to `--initial-moving-transform` they are merged into a single transform on output (when adjacent). However, providing an warp field as part of the --initial-moving-transform stack results in a `<prefix>1Warp.nii.gz` and `<prefix>2Warp.nii.gz` output.

Is this a bug, or as intended? If as intended, can the help be updated to reflect it explicitly.

**Comment by gdevenyi** [comment]
Followup, one reason not to do this is that if an inverse warp transform is provided, the inverse isn't immediately available, so one can't merge the InverseWarp.nii.gz

**Comment by ntustison** [comment]
This is exactly why.  An invertible transform is not “collapsible” with a single displacement field.  And instead of mucking with the command line syntax to specify both displacement fields for this infrequent use case, we left it as it is currently.
