### ISSUE TITLE
Continuing before reaching #iterations predetermined by reg_iterations?

### ISSUE THREAD

**Issue by ninusch** [ANTsX/ANTs#1476]
Does the code include a threshold value for the metric, e.g. Mutual Information, and if the value between fixed and moving image does not exceed a certain threshold anymore within a few iterations, is then proceeded to the next resolution level BEFORE reaching the number of iterations predetermined by reg_iterations?
That would sound logical to me, but I am confused since sometimes I get better results when decreasing the number of iterations per resolution level, as if it would always finish the predetermined iterations, no matter what.

**Comment by gdevenyi** [comment]
```
     -c, --convergence MxNxO
                       [MxNxO,<convergenceThreshold=1e-6>,<convergenceWindowSize=10>]
          Convergence is determined from the number of iterations per level and is 
          determined by fitting a line to the normalized energy profile of the last N 
          iterations (where N is specified by the window size) and determining the slope 
          which is then compared with the convergence threshold. 
```

**Comment by gdevenyi** [comment]
Convergence is determined by the similarity metric. There are lots of degenerate cases you can imagine where the metric "improves" but your human-informed evaluation is that the registration got "worse".

**Comment by ninusch** [comment]
And is there an option to turn the convergence check off? So making sure that the code runs through all the predetermined iterations by reg_iterations and NOT prematurely stopping because of convergence?

**Comment by cookpa** [comment]
A convergence threshold of 0.0 should do it. It might still stop early if the solution starts to get worse.

**Comment by gdevenyi** [comment]
I think I asked this long ago somewhere else and a large negative convergence threshold can force it. Test it and see.

**Comment by cookpa** [comment]
That sounds right. Also, if the window is set to the number of iterations, it should never get to a point of testing convergence. Agree that trying it out is good

**Comment by ninusch** [comment]
Thank you all! And do you by any chance know how to turn it off when using AntsPy? I really can't find it i.e. I don't know which function to give the input to.

**Comment by ninusch** [comment]
So I mean where do I adjust the convergence threshold when using antspy

**Comment by ntustison** [comment]
ANTsPy ``ants.registration`` is not meant to provide user access to the entire set of command line options.  If you want to do that, I would advise you to stick with the original version.
