### ISSUE TITLE
rescale intensities - N4BiasFieldCorrection 

### ISSUE THREAD

**Issue by marinaferalv** [ANTsX/ANTs#1480]
Dear experts,

I'm going to use N4BiasFieldCorrection algorithm to correct B1+ intensity inhomogeneities in 3T T1w and T2w images, in order to calculate T1w/T2w ratio.
Is it advisable to rescale the intensities for this purpose ? (using " -r, --rescale-intensities 1 " when N4 is applied to each of the images, before calculating the ratio)

Thank you very much in advance.
Best regards,
Marina

**Comment by ntustison** [comment]
That's the default recommendation.  Otherwise, the tendency is for the intensity scale of the entire image to "drift" upwards or downwards.

**Comment by marinaferalv** [comment]
Thank you for your quick response.

I am using CLEAR during T1w and T2w image acquisition, a Philips MR technique to achieve homogeneity correction by using coil sensitivity maps acquired in a reference scan. Should I still apply N4BiasFieldCorrection despite of using CLEAR during acquisition?

Best regards,
Marina

**Comment by ntustison** [comment]
You should just test N4 and see if it improves the images and your outcomes.

**Comment by marinaferalv** [comment]
Thank you.

Last question. I am applying N4BiasFieldCorrection to skull-stripped T1w 
and T2w brain images. Do you think that I should exclude CSF and ventricular spaces before applying bias field correction?

**Comment by ntustison** [comment]
It's not necessary and would probably not make much difference.

**Comment by cookpa** [comment]
Some papers that might be of interest:

https://pubmed.ncbi.nlm.nih.gov/35697132/

This details the HCP pipeline and also has some useful theoretical background. 

https://pubmed.ncbi.nlm.nih.gov/34848300/

This is a multi-site evaluation of bias correction strategies, including N3 and N4. Though the data was available, I was unable to find a link to the code, so I'm not sure what options were used.
