### ISSUE TITLE
Superbuild with ITK ZLIB module?

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1481]
Hi @stnava @ntustison @gdevenyi and other interested developers,

I am trying to build native Windows binaries, and had to find a solution for zlib. We've required system zlib for a long time, but ITK now has an [updated zlib module](https://github.com/InsightSoftwareConsortium/ITK/pull/2803) based on [zlib-ng](https://github.com/zlib-ng/zlib-ng). 

Is there any reason why we would want to continue using system zlib? 

If not, I'll try to use ITK's version consistently, and will test compression performance on image I/O.

**Comment by dorianps** [comment]
I had asked about this topic some years ago, happy to see it implemented.

https://github.com/ANTsX/ANTs/issues/702

**Comment by cookpa** [comment]
Hi @dorianps , might you be able to try out the Windows binaries here?

https://github.com/cookpa/ANTs/releases/tag/testActions-0.1

I built the same source on Mac and it compiles OK, but I don't see a performance gain in I/O speed vs my system (zlib 1.2.11). Are there any use cases you or @gdevenyi know of where zlib-ng might perform better? Just curious, either way I still think it's a good thing to use ITK's version for multiple reasons outlined above.

**Comment by cookpa** [comment]
BTW the test I did was simply reading a largeish (104x104x72x478) image (.nii.gz) with ImageMath and then writing it back out in either .nii.gz or .mha format.

**Comment by gdevenyi** [comment]
I think the zlib-ng performance is "statistical", in the sense its in the low-percentage range right now. ZLIB has already had many optimizations done over the years. I also know that not all the hardware-acceleration features have been merged yet. We should also check the current state of the build config for ITK to ensure its both optimized and generic for distribution purposes.

**Comment by dorianps** [comment]
I never really used ANTs on Windows but can try if it helps. What exactly
should I try? I can do I/o commands like imageRead/imageWrite but I would
do that on a laptop compared to a Linux workstation, and there is a lot
more than Ants changing between the two scenarios.

Dorian

P.s. I have not puty hands on Ants commands for a while now.

**Comment by cookpa** [comment]
Thanks, sorry for mixing streams @dorianps - just I was more wanting to test basic functionality of the Windows binaries, something like does `antsRegistration.exe` work for a somple test case. 

ZLIB was kind of a means to an end, I'm not looking to do extensive benchmarking. 

I don't have a Windows VM handy

**Comment by dorianps** [comment]
Got it. The scripts will not work in windows but I can try few binaries.

Would you mind pasting a couple of registration/bias correction commands?
Setting up all iterations without the sh scripts is not straightforward for
me.

**Comment by cookpa** [comment]
I'm not sure I can even write a command in powershell (recent experience suggests not), but it occurs to me that I could try to run the built-in short tests - I'll try that first. Thanks!
