### ISSUE TITLE
Blurred T1 template output of antsMultivariateTemplateConstruction2.sh

### ISSUE THREAD

**Issue by khazarAhmadi** [ANTsX/ANTs#1483]
**Describe the problem**

Dear experts, 
I used antsMultivariateTemplateConstruction2.sh to generate a "test" T1 template from anatomical images of 3 healthy controls. Each T1 image is acquired at 7T (MP2RAGE sequence) with isotropic resolution of 0.75 mm. Before running the script, I used PreSurfer to remove the noisy background in each image but kept them in native space (didn't perform any prior alignment e.g. to MNI space or T1 of the 1st subject as the reference image). The code ran with no errors but when I check the template0.nii.gz file, I notice that the image is blurry while individual T1s are sharper. Any suggestions on how to build a cleaner template is greatly appreciated!    

**To Reproduce**

I ran the script with the following parameters. 

antsMultivariateTemplateConstruction2.sh -d 3 -o SST_ -c 2 -j 4 -k 1 -r 1 -t SyN -m CC T1w-Sub0*.nii.gz

![template0](https://user-images.githubusercontent.com/69059866/211876113-db674284-0719-461a-aa4f-d6b10d1ac57e.png)
![native-T1](https://user-images.githubusercontent.com/69059866/211876128-dabc6263-bbd7-4c51-adb3-ebe02c3cc130.png)

**System information (please complete the following information)**

 - OS: Linux
 - OS version: Ubuntu 20.04

**ANTs version information**
 - ANTs code version: v2.3.5.post130-gaacdc61
 - ANTs installation type: Compiled from source

**Additional information**

Smoothing and max iterations were kept as default. Do you think I should change either of -s or -q arguments? Can this blurring be due to lack of initial alignment. I'd be happy to hear your thoughts. Thank you!

**Comment by ntustison** [comment]
The results don't look unreasonable.  Is your assessment of "blurriness" based on any specific region?  

Although sharpening is performed on the template at each iteration, you have to understand that you're averaging multiple images to create the template such that sharpness of any template is bound to be less than the individual subjects.
