### ISSUE TITLE
Diffusion (FA) -> Atlas (T1) registration suggestions

### ISSUE THREAD

**Issue by samcartmell** [ANTsX/ANTs#1487]
Hello,

I am attempting to register individual subject FA images to the ICBM 152 2009a T1 atlas space. Unfortunately, I only have access to the diffusion data and do not have individual subject structural T1 scans to use as an intermediate step in the registration.  Thus, I am hoping to go directly from the subject FA -> T1 atlas space.

I have attempted this process using the antsRegistrationSyN.sh tool with poor results (although it worked well when going within modality from the subject FA -> FMRI58 FA template).

Do you have any suggestions for how to best approach this problem?

Best,
Sam

**Comment by cookpa** [comment]
The FMRIB58_FA template is designed to be aligned to the MNI152 Nonlinear 6th Generation T1w template. Could you align to FMRIB58_FA and then apply an additional warp from [MNI152NonLin6Asym](https://github.com/templateflow/tpl-MNI152NLin6Asym/) to [tpl-MNI152NLin2009aAsym](https://github.com/templateflow/tpl-MNI152NLin2009aAsym)?

I don't know if anyone has made the mapping between MNI versions already. Templateflow has a [registration framework](https://github.com/templateflow/registration-framework) to do it (though I've not used it myself).

**Comment by samcartmell** [comment]
Thank you for this suggestion! I'll give it a try.
