### ISSUE TITLE
BraTS-Reg22 evaluation

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTs#1491]
Hey @cookpa (and anyone else who is interested),

Recently, I was asked to evaluate ANTs-based performance for the [BraTS-Reg 2022 Challenge](https://www.med.upenn.edu/cbica/brats-reg-challenge/).  I actually logged the process and organized it in a dedicated [GitHub repo](https://github.com/ntustison/BraTS-Reg22).  I can't remember if we have a wiki page where we refer reviewers looking for performance evaluations but just wanted a record here of this particular evaluation.

**Comment by cookpa** [comment]
This is great, thanks. I think there's some evaluation page somewhere, I'll take a look.

**Comment by cookpa** [comment]
Adding a link to the container for those interested https://github.com/cookpa/ANTsXBratsReg22Singularity

**Comment by ntustison** [comment]
Awesome.  Thanks @cookpa .  I'll post the link over on the repo.
