### ISSUE TITLE
Metric sampling strategy: number of voxels

### ISSUE THREAD

**Issue by petr-henys** [ANTsX/ANTs#1493]
Hi,
I want to sample the MI metric in every third voxel in each dimension. Shall I use a regular sampling strategy with 33 per cent of voxels included? I need clarification on whether the percentages refer to the total number of voxels or voxels per dimension.

Thanks for your answer,

Petr

**Comment by ntustison** [comment]
Total number of voxels.

**Comment by petr-henys** [comment]
Understood,
therefore how are the dimensions of the regular grid (num. voxels or voxel size per each dim.) computed from the total number of voxels?
Enough point me to the relevant piece of code in repo...
Petr

**Comment by ntustison** [comment]
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx#L1020-L1051

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/antsRegistration-metric-sampling-strategies
