### ISSUE TITLE
Python's SyNCC equivalent in the bash version

### ISSUE THREAD

**Issue by seralouk** [ANTsX/ANTs#1495]
I have used the [`SyNCC`](https://antspy.readthedocs.io/en/latest/registration.html) algo in the python package.

What is the equivalent option in the bash package? 

Is it `s: rigid + affine + deformable syn (3 stages)` or `b: rigid + affine + deformable b-spline syn (3 stages)` in ` -t:  transform type (default = 's')` input argument?

**Comment by ntustison** [comment]
[Here's](https://github.com/ANTsX/ANTsPy/blob/master/ants/registration/interface.py#L770-L823) the command line call.  So it's the first one.  Note that we've added a set of transform options ( ``antsRegistrationSyN*``) that are coordinated with the bash scripts.
