### ISSUE TITLE
Question about LesionFilling algorithm

### ISSUE THREAD

**Issue by enrit** [ANTsX/ANTs#1496]
Hello All,

I have a quick question about the LesionFilling tool. Can someone please suggest how the filling is done ? How are the lesional voxels being replaced with the normal voxels ? Is the algorithm using local intensities from the voxels that are surrounding the lesions or global WM intensities from the whole brain or some combination between the two approaches ? 

Many thanks

Ri

**Comment by cookpa** [comment]
The lesion voxels are filled with values from the surrounding voxels, with a restriction that any filled value must be greater than the mean in the lesion itself. So it will only work for lesions that are darker than the surrounding tissue.
