### ISSUE TITLE
Issue with the Installation

### ISSUE THREAD

**Issue by ShibaPrasad** [ANTsX/ANTs#1497]
Having an Issue with the Installation.

I followed the ANTs installation steps provided at URL: https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/  
•	cloned ANTs directory to my local Download directory 
•	created “antsbin” directory and cd to antsbin directory 
•	From “antsbin” executed “cmake3 ../ANTs” instead of  ccmake ../ANTs 
Most of the cmake3 output was successful and a very few failed 

-- Performing Test C_HAS_WARNING-Wno-long-double – Failed 

-- Performing Test CXX_HAS_WARNING-Wno-long-double – Failed 

-- Performing Test CXX_HAS_WARNING-Wno-undefined-var-template – Failed 

-- Performing Test CXX_HAS_DISABLE_OPTIMIZATION_FLAG - Failed 

• Then executed “make -j 4” 
No error I found during the “make -j 4” step.
------------------------------
To run the script:  

1. need to copy the Scripts/* to antsbin/bin/ 
I copied “/home/mxxxx/Downloads/ANTs/Scripts/*” to /home/mxxxxx/Downloads/antsbin/bin 

2. set the ANTSPATH to point to the antsbin/bin/ directory. e.g., in your profile, add: 
I included below two lines in .bashrc file 
export ANTSPATH=/home/mxxxx/Downloads/antsbin/bin 
export PATH=${ANTSPATH}:$PATH 

Then I tried to execute the "which antsRegistration" from the command line to verify whether the installation was correctly done.

Getting below error: 

(base) [xxxxxx]$ which antsRegistration 
/usr/bin/which: no antsRegistration in (..../antsbin/bin:/usr/local/dcm2niix/bin:.../anaconda3/bin:/)

**Comment by cookpa** [comment]
That page is quite old, there are several ways to get ANTs now.

Updated instructions to build from source are here

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

Binaries here

https://github.com/ANTsX/ANTs/releases/tag/v2.4.3

Docker containers here

https://hub.docker.com/repository/docker/antsx/ants/general

**Comment by ShibaPrasad** [comment]
Thank you. Able to resolve the issue.
