### ISSUE TITLE
Question on availability of public template, mask and priors for age range 8-18 years

### ISSUE THREAD

**Issue by akelkar26** [ANTsX/ANTs#1501]
Hi, 

I have a question about using the ANTs scripts on my dataset. My dataset consists of ADHD subjects and age matched controls from the age range of 8 years- 18 years. 
I want to get cortical thickness for the controls and the ADHD subjects using ANTsCorticalThickness.sh

My procedure is as follows:
1. Create my own templates for ADHD/control subjects using buildtemplateparallel.sh
2. Use FSL bet2 to get the brain extraction mask for the template
3. Extract each brain from each T1w that makes up my template using ANTsbrainextraction.sh
4. Make priors for my template using antsCookTemplatePriors.sh
5. Then I will have all the files I need to run ANTsCorticalThickness.sh

I was able to run steps 1 and 2 successfully.

From step 3 onwards, I need a pre-existing template, mask and priors.

I couldn't find a template that matched the age group I am looking for here: https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436

Could you please advise on how to get the pre-existing template, mask and priors?

Also, once I am done running ANTsCorticalThickness.sh, how do I get the cortical thickness values from each ROI in my atlas (eg: Schaefer atlas)?

Thank you for your help in advance.

Best,
Apoorva

**Comment by ntustison** [comment]
> Could you please advise on how to get the pre-existing template, mask and priors?

I would try using one of the existing templates even if it doesn't match your demographic subset.  The registration might be able to overcome that mismatch.  

> Also, once I am done running ANTsCorticalThickness.sh, how do I get the cortical thickness values from each ROI in my atlas (eg: Schaefer atlas)?

Register your atlas to each subject and calculate the mean from the non-zero thickness values in each ROI.

**Comment by akelkar26** [comment]
Thank you so much for the input. I will test your suggestions.

Best,
Apoorva
