### ISSUE TITLE
`cmake -DCPACK_BINARY_DEB=ON` and `CPACK_PACKAGE_VERSION`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [ANTsX/ANTs#1503]
I am attempting to build a local DEB package, loosely following [Compiling ANTs on Linux and Mac OS](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS):

```
workingDir=${PWD}
git clone https://github.com/ANTsX/ANTs.git
mkdir build install
cd build

cmake \
    -DCMAKE_INSTALL_PREFIX=${workingDir}/install \
    -DCPACK_BINARY_DEB=ON -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TZ=OFF \
    -DBUILD_TESTING=OFF -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=OFF \
    ../ANTs

make -j 16 package
```
The resulting DEB package version starts with `v`. From the resulting file `ANTS-build/CPackConfig.cmake`:
```cmake
[...]
set(CPACK_PACKAGE_FILE_NAME "ANTs-v2.4.3.post10-g871cad0-Linux")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/ANTsX/ANTs")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "ANTS_Install")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "ANTS_Install")
set(CPACK_PACKAGE_NAME "ANTs")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "CMake.org")
set(CPACK_PACKAGE_VERSION "v2.4.3.post10-g871cad0")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "4")
set(CPACK_PACKAGE_VERSION_PATCH "3")
[...]
```

Unfortunately, recent versions of `dpkg`, such as [dpkg 1.21 available on Ubuntu 22.04](https://launchpad.net/ubuntu/+source/dpkg/1.21.1ubuntu2.1), complain if the **_upstream-version_ of a DEB package does not start with a digit**. From the [deb-version(7)](https://manpages.ubuntu.com/manpages/jammy/man7/deb-version.7.html) man page:
> ```
>            The upstream-version may contain only alphanumerics (“A-Za-z0-9”) and the characters .
>            + - : ~ (full stop, plus, hyphen, colon, tilde) and should start with a digit.  If
>            there is no debian-revision then hyphens are not allowed; if there is no epoch then
>            colons are not allowed.
> ```

Typical resulting error message:
```
$ sudo dpkg -i ANTs-v2.4.3.post10-g871cad0-Linux.deb
dpkg: error processing archive ANTs-v2.4.3.post10-g871cad0-Linux.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 374 package 'ants':
 'Version' field value 'v2.4.3.post10-g871cad0': version number does not start with digit
Errors were encountered while processing:
 ANTs-v2.4.3.post10-g871cad0-Linux.deb
```

**When did the error occur?**

[X] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: GNU/Linux Ubuntu
 - OS version: 22.04
 - Type of system: desktop

**ANTs version**

_master_ branch

**Build configuration and logs**

**Additional context**

Projects I know of on GitHub start version tags with a `v`, but drop the `v` when building tarballs or DEB/RPM packages.

**Comment by DimitriPapadopoulos** [comment]
Indeed, `Version.cmake` adds a leading **`v`** to `${PROJECT_NAME}_VERSION`:
https://github.com/ANTsX/ANTs/blob/871cad073908952b095e4b520335fc441e059264/Version.cmake#L65
https://github.com/ANTsX/ANTs/blob/871cad073908952b095e4b520335fc441e059264/Version.cmake#L79
which is then used by `ANTS.cmake`:
https://github.com/ANTsX/ANTs/blob/871cad073908952b095e4b520335fc441e059264/ANTS.cmake#L30

**Comment by cookpa** [comment]
I think we could do this but interested in other opinions, particularly if external users (eg neurodebian) are reading

**Comment by DimitriPapadopoulos** [comment]
DEB packages from Neurodebian lack the `'v'`:

https://neurodebian.inm7.de/debian/pool/main/a/ants/

As far as I know, Neurodebian do not use `cmake package` to create a DEB file, they have their own [rules](https://salsa.debian.org/med-team/ants/-/blob/master/debian/rules).

**Comment by cookpa** [comment]
Turns out I have to migrate the ANTs docker repositories in April anyway, so I will work on this also.

**Comment by cookpa** [comment]
Yes it's part of the solution, thanks. That label is ambiguous, I might change it to better distinguish when we need implementation help vs feedback on proposed changes.
