### ISSUE TITLE
Issue with Registering ROIs from T2 slab to MNI

### ISSUE THREAD

**Issue by catherine-tallman** [ANTsX/ANTs#1508]
**Describe the problem**

I’m unable to successfully move a hippocampal ROI originally in T2 space into MNI space. I'm using the T1 acquired on the same scan day to move to MNI space. The T2 was acquired oblique and as a slab. Before using ANTS, I deobliqued the T2 slab and reoriented it to LPI to match the MNI template. I also reoriented the T1 to LPI to match the MNI template. All references to the T1 and T2 are these images moving forward.

**To Reproduce**

I’ve tried two approaches. The T1, T2, and MNI template I’m using are attached as well as the commands, log output, and a screenshot of the results.

_Option 1_
- Affine registration of T1->T2 
- Use inverse matrix of T1->T2 to put hippocampal ROI in T1 space
- Nonlinear transform of T1 to MNI space
- Apply nonlinear transform to hippocampal ROI in T1 space to move it to MNI space

Result (red in attached image): roughly in the correct area but registration is poor and enlarged/catching white matter

_Option 2_
- Nonlinear transformation of T1 -> MNI
- Nonlinear transformation of T2 -> T1 in MNI space
- Apply transformation of T2 to T1 in MNI space to hippocampal ROI

Result (blue in attached image): Not in the correct part of the brain and looks like an issue of registering to a slab in the sagittal view.

**System information (please complete the following information)**

Type of system: Linux server
Linux squirelab.ucsd.edu 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**ANTs version information**
ANTs Version: 2.2.0.dev244-ga45da
Compiled: Oct  3 2018 09:29:04

**Additional information**

[tse_lpi.nii.gz](https://github.com/ANTsX/ANTs/files/10902704/tse_lpi.nii.gz)
[mprage_lpi.nii.gz](https://github.com/ANTsX/ANTs/files/10902708/mprage_lpi.nii.gz)
[tpl-MNI152NLin2009aAsym_res-1_T1w_bet.nii.gz](https://github.com/ANTsX/ANTs/files/10902710/tpl-MNI152NLin2009aAsym_res-1_T1w_bet.nii.gz)
[Option1_log.txt](https://github.com/ANTsX/ANTs/files/10902714/Option1_log.txt)
![Option1_Result](https://user-images.githubusercontent.com/43822276/223228572-b8d541ff-2dd5-4804-a2f1-602d6de83656.png)
[Option2_log.txt](https://github.com/ANTsX/ANTs/files/10902715/Option2_log.txt)
![Option2_Result](https://user-images.githubusercontent.com/43822276/223228585-13e89334-83b3-498f-b2b9-6322e71b2bce.png)

[Option1_Commands.txt](https://github.com/ANTsX/ANTs/files/10902733/Option1_Commands.txt)
[Option2_Commands.txt](https://github.com/ANTsX/ANTs/files/10902734/Option2_Commands.txt)
[Uploading hipp_lpi_bin.nii.gz…]()

**Comment by ntustison** [comment]
Have you seen this example?

https://github.com/ntustison/PartialSlabEpiT1ImageRegistration

**Comment by catherine-tallman** [comment]
Thank you for the link. I did use an ANTs example of a partial slab epi to T1 registration for some of the commands included in Option 1. I had only tried the rigid version and not the SyN version. 

After trying that, I still received similar results as pictured in red. The registration is generally in the right part of the brain but the ROI looks enlarged and not aligned to the gray matter well.

**Comment by ntustison** [comment]
You haven't included all the data necessary to run your example.  I was able to run the first part.  I trimmed down the number of iterations and resolution levels to make it faster (below) which worked as expected.  So what I would suggest you do now is run through each registration stage and figure out which phase is causing problems.  Then come back with that self-contained, simplified example and we'll be able to help you from there.  

```
	OUTPUT_PREFIX=T1toT22
	FIXED=tse_lpi.nii.gz
	MOVING=mprage_lpi.nii.gz
	MOVING2=T1toMNI2Warped.nii.gz
 
	antsRegistration --verbose 1 \
                 --dimensionality 3 \
                 --float 0 \
                 --interpolation Linear \
                 --use-histogram-matching 0 \
                 --winsorize-image-intensities [0.005,0.995] \
                 --output [${OUTPUT_PREFIX},${OUTPUT_PREFIX}Warped.nii.gz,${OUTPUT_PREFIX}InverseWarped.nii.gz] \
                 --initial-moving-transform [${FIXED},${MOVING},1] \
                 --transform Rigid[0.1] \
                   --metric MI[${FIXED},${MOVING},1,32,Random,0.25] \
                   --convergence [500x100x0x0,1e-6,10] \
                   --shrink-factors 6x4x2x1 \
                   --smoothing-sigmas 3x2x1x0vox # >> ${datapath}/Option1_output.txt \
```

**Comment by cookpa** [comment]
With slab-to-volume registration, this is often the cause of errors

```
                 --initial-moving-transform [${FIXED},${MOVING},1]
```

because the center of mass of the slab often doesn't align well with the COM of the whole brain. In this case, the COM alignment moves the slab in the wrong direction a bit, but the registration above recovers.

If you remove the above line, the slab and brain must be close to aligned in physical space already (in your case, they are).

I think a variation of option 1 is the correct way to go:

1. Rigidly align the slab to T1w
2. Non-linear alignment of T1w to MNI
3. Combine warps from (1) and (2) to resample slab into MNI space.

It's better to warp the t2 image to MNI space directly, rather than resampling it into T1w space, and then again into MNI space. Example here:

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians#warping-multiple-modalities-to-a-common-template

I'm not sure where the red hippocampal outline is coming from. If this is a label in the t2w space, you can warp it to MNI space using the same antsApplyTransforms call, but you should use `-n GenericLabel`.

The final alignment will only be as good as the registrations in (1) and (2), so inspect the output of those registration steps to see what to optimize.

**Comment by catherine-tallman** [comment]
Hello,

Thank you very much for the instructions! I gave that a try and the hippocampal ROI registration improved greatly (commands below; picture attached). It still looks like it's not properly aligned and I believe the issue is the registration between the T1 and MNI template. The T2 to T1 registration looks good.

I took a look at the wiki and the issues tab but I'm stuck on how to improve the the T1 to MNI transformation. Please let me know if you need any additional information.
![Screen Shot 2023-04-04 at 3 53 36 PM](https://user-images.githubusercontent.com/43822276/229942103-0fbd8146-5183-4b0b-83a1-645f1e570928.png)



Input files (attached in first message)

```
movingImage=${baseDirectory}/tse_lpi.nii.gz
fixedImage=${baseDirectory}/mprage_lpi.nii.gz
template=/usr/local/mridata/Smith_Merit/Processed_Data/derivatives/FMRI_Sentences/Group_Level/tpl-MNI152NLin2009aAsym_res-1_T1w.nii.gz
outputPrefix=T2toT1
roi=hipp_final_lpi.nii.gz
```

1) Rigidly align the slab to T1w

```
antsRegistration --verbose 1 \
                --dimensionality 3 \
                 --float 0 \
                 --interpolation Linear \
               --use-histogram-matching 0 \
                 --winsorize-image-intensities [0.005,0.995] \
                --output [${outputPrefix},${outputPrefix}Warped.nii.gz,${outputPrefix}InverseWarped.nii.gz] \
                 --transform translation[0.1] \
                --metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
                 --convergence [50,1e-6,10] \
                 --shrink-factors 1 \
                 --smoothing-sigmas 0vox \
                 --transform Rigid[0.1] \
                 --metric MI[${fixedImage},${movingImage},1,32,Random,0.25] \
                 --convergence [500x250x50,1e-6,10] \
                 --shrink-factors 2x2x1 \
                --smoothing-sigmas 2x1x0vox \
                 --transform SyN[0.1,3,0] \
                 --metric MI[${fixedImage},${movingImage},1,32] \
                 --convergence [50x10,1e-6,10] \
                 --shrink-factors 2x1 \
                 --smoothing-sigmas 1x0vox
```

2) Non-linear alignment of T1w to MNI

```
antsRegistrationSyNQuick.sh \
  -d 3 \
  -f ${template} \
  -m mprage_lpi.nii.gz \
  -o t1ToTemplate_ \
  -t s
```

3) Combine warps from (1) and (2) to resample slab into MNI space.

```
antsApplyTransforms \
    -d 3 \
    -i ${roi} \
    -o hippDeformedToTemplate_test.nii.gz \
    -r ${template} \
    -n GenericLabel \
    -t t1ToTemplate_1Warp.nii.gz \
    -t t1ToTemplate_0GenericAffine.mat \
    -t ${outputPrefix}0GenericAffine.mat

```

**Comment by cookpa** [comment]
```
antsRegistrationSyNQuick.sh \
  -d 3 \
  -f ${template} \
  -m mprage_lpi.nii.gz \
  -o t1ToTemplate_ \
  -t s
  ```
  
I would try `antsRegistrationSyN.sh` instead
