### ISSUE TITLE
Issue with brain segmentation image after using ImageMath

### ISSUE THREAD

**Issue by akelkar26** [ANTsX/ANTs#1510]
Hi, 

I am trying to get Cortical Thickness values from my atlas. My age group is 8-18 year old. I was able to get my own template, segmentation and priors as well as run ANTsCortical thickness and get the cortical thickness map for my subject.

I read a similar post on the ANTs Sourceforge forum which I am following.
https://sourceforge.net/p/advants/discussion/840261/thread/6711594b27/

I get a good binary mask and have a good atlas. 

I am using the ImageMath step so that it computes the mean cortical thickness correctly.

Command:

```
ImageMath 3 /Users/neurouser1/Documents/ADHD_200/xcp/fmriprep_out/freesurfer/sub-8191384/mri/sub-8191384yeo2011_seg_out.nii.gz m /Users/neurouser1/Documents/ADHD_200/ant_temp/Peking_3_healthy/sub-8191384/sub-8191384CorticalThickness_binarymask.nii.gz /Users/neurouser1/Documents/ADHD_200/xcp/fmriprep_out/freesurfer/sub-8191384/mri/sub-8191384_yeo2011_seg.nii.gz

```
My input files are:

Binary mask:

![image (7)](https://user-images.githubusercontent.com/40644674/223777870-e234e50e-af09-4b07-8c64-5b71b4a3af71.png)

Atlas file:

![image (8)](https://user-images.githubusercontent.com/40644674/223777955-83d50774-6a17-4b71-953a-b1045d06cec5.png)

Output of ImageMath:

![image (9)](https://user-images.githubusercontent.com/40644674/223778047-87357bc0-1aea-4dd4-b32c-c909e453c609.png)

ANTs Version: 2.3.5.dev224-g5f1fa
Compiled: Mar  5 2021 23:24:29

ProductName:    macOS
ProductVersion: 11.6.8
BuildVersion:   20G730

Could you tell me why I don't get a good output image? 
Any insight would be appreciated.

Thank you
Best,
Apoorva

**Comment by ntustison** [comment]
> I am using the ImageMath step so that it computes the mean cortical thickness correctly.

This is unclear.  What exactly are you trying to do?

**Comment by j-dengler** [comment]
We're trying to extract cortical thickness values from specific regions within an atlas. The ImageMath step is to extract only non-zero values by masking out any zero values from the label file.

**Comment by j-dengler** [comment]
Yes, we used Freeview to get the above images. 
The binary mask is made from the output of ants cortical thickness using threshold image. 
`ThresholdImage 3 /path/sub-#/sub-#CorticalThickness.nii.gz /path/sub-#/sub-#CorticalThickness_binarymask.nii.gz .001 Inf 1 0`

**Comment by ntustison** [comment]
>  Yes, we used Freeview to get the above images.

I noticed which is why I made the recommendation that I did.  Many issues are caused by header discrepancies and those can be easily discovered without our help when using something that conforms to ITK/ANTs standards such as ITK-SNAP.  
Try looking at all the images using ITK-SNAP and let us know if the output is the same as you're showing above.

**Comment by j-dengler** [comment]
I looked at all the images on ITK-SNAP and they look the same as they do above. I think the atlas seg image I am using is not registered to the same space as the template cortical thickness binary mask. Is there a way to register it to the same space?
