### ISSUE TITLE
antsRegistration Method

### ISSUE THREAD

**Issue by StephDocTUM** [ANTsX/ANTs#1511]
Dear all,

how does the method antsRegistration exactly work? in the Docs of fmriprep it is said that antsRegistration shrinks brain lesions when registering lesional brains to an atlas? How does this exactly work?

Cheers

**Comment by ntustison** [comment]
This question is a bit too open-ended to answer as an issue in the GitHub forum.  Here's a set of core [references](https://github.com/ANTsX/ANTs#references) that might help you hone in on what you'r looking for.

**Comment by StephDocTUM** [comment]
Mhh I see, I looked into the references but couldn’t find something which explains it properly. Maybe it would help to clarify the registration method which is used in ANTS?

**Comment by stnava** [comment]
I would recommend reading this [paper](https://www.frontiersin.org/articles/10.3389/fninf.2014.00044/full)
