### ISSUE TITLE
Build fails if test data is present on `=ants-2.4.1`

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#1518]
The build fails if the testdata is present: https://ppb.chymera.eu/f3608d.log
The build succeeds if the testdata is not present: https://ppb.chymera.eu/edeb6a

As far as I can tell the only thing I'm doing differently is creating a directory for the testdata:

```
        mkdir -p "${S}/.ExternalData/MD5" || die "Could not create test data directory."
        tar xvf "${DISTDIR}/ants_testdata-2.3.4.tar.xz" -C "${S}/.ExternalData/MD5/" > /dev/null || die "Could not unpack test data."
```

The version inconsistency stems from the fact that the test data [allegedly doesn't change](https://github.com/ANTsX/ANTs/issues/878#issuecomment-668595537) and that I [can't get newer test data](https://github.com/ANTsX/ANTs/issues/878#issuecomment-1487345359).

**Comment by cookpa** [comment]
I think the data has to be hashed by SHA512 now

https://github.com/ANTsX/ANTs/blame/09599352304559fd74aae894e54db2f1b41e88ce/CMake/ANTSExternalData.cmake#LL45C5-L45C30

**Comment by TheChymera** [comment]
Ok, the issue was that the data was indeed downloaded as SHA512, but was still put under `.ExternalData/MD5` instead of `.ExternalData/SHA512`.
