### ISSUE TITLE
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS and the real number of the thread used

### ISSUE THREAD

**Issue by Silvesterrpi** [ANTsX/ANTs#1523]
Hello,
I am running ANTs on a desktop computer with 4 physical cores (Intel Core i7), but I set the ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS to 5 by mistake, may  I know the real number of threads will be employed when I run antsRegistration (-Affine or -SyN) in this case?

**Comment by cookpa** [comment]
It's OK, this isn't a compile time parameter, you can change it any time you like. If you do

```
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=4 
```

it will use 4 threads. Actually it might create one extra thread to organize the others, but only the four will be "workers" that occupy 100% of a CPU.

**Comment by Silvesterrpi** [comment]
This is great to know. Thanks a lot!

**Comment by citystrawman** [comment]
> It's OK, this isn't a compile time parameter, you can change it any time you like. If you do
> 
> ```
> export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=4 
> ```
> 
> it will use 4 threads. Actually it might create one extra thread to organize the others, but only the four will be "workers" that occupy 100% of a CPU.

Hi, when I read `antsRegistrationSyn.sh `and `antsRegistrationSynQuick.sh`, I found that the ` number of threads` is not used when calling the antsRegistration.exe(this exe does not have number of threads option). the shell script only export `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS`. So why changing this `number of threads` improve calculation speed? (from my perspective, a shell script is only a shell, and the execution time only depends on the actual exe file execution time)
