### ISSUE TITLE
antsCorticalThickness Output

### ISSUE THREAD

**Issue by j-dengler** [ANTsX/ANTs#1527]
Problem: 
[sub-1056121_corticalthickness.txt](https://github.com/ANTsX/ANTs/files/11288547/sub-1056121_corticalthickness.txt)
[sub-1056121_yeoLUT.txt](https://github.com/ANTsX/ANTs/files/11288548/sub-1056121_yeoLUT.txt)

I am trying to pull out cortical thickness in specific ROIs defined by a look-up table I created. When I run the subjects through the steps as outlined below, I get an output file that has more labels than there are labels in my look-up table. I believe this may be part of a default output and my labels are getting added later, but wanted to confirm. My table has values from 1-699, 1000-1041, and 2000-2041. However, my output file has values for the values in between those, so 700-999 and 1042-1999. I created my own template, but used Oasis to get priors. I am including the output file and look-up table for one of the subjects in my pipeline. 

Steps: 
- Run antsCorticalThickness 
`antsCorticalThickness.sh -d 3 -a /path/sub_ses-1_run-1_T1w.nii.gz -e /path/template.nii.gz -m /path/owntemplate_templateBrainExtractionMask_smoothed.nii.gz -p /path/owntemplatepriors/owntemplatepriorsPriors%d.nii.gz -o /path/sub/sub`
- Make Binary Mask
`ThresholdImage 3 /path/sub/subCorticalThickness.nii.gz /path/sub/subCorticalThickness_binarymask.nii.gz .001 Inf 1 0`
- Image Math to remove 0 valued cortical thickness
`ImageMath 3 /path/sub/subreregistered_yeo_out.nii.gz m /path/sub/subCorticalThickness_binarymask.nii.gz /path/sub/subreregistered_yeo.nii.gz`
- Image Intensity to pull out cortical thickness with atlas
`ImageIntensityStatistics 3 /path/sub/subCorticalThickness.nii.gz /path/sub/subreregistered_yeo_out.nii.gz > /path/CorticalThicknessValues/sub_corticalthickness.txt`

System information:
 - OS: Mac OS
 - OS version: 11.6.8
 

ANTs version information:
 - ANTs code version: 2.3.5.dev224-g5f1fa

**Comment by ntustison** [comment]
How are you determining the unique labels in ``/path/sub/subreregistered_yeo_out.nii.gz``?  If the unexpected labels are not there (my guess is that they are), you'll have to post an example for us to take a look.

**Comment by j-dengler** [comment]
I'm using the the individual network ROIs overlay files fro the output of Li 2019 to the Freesurfer lable files. I then created indivdualized look up tables compatible with Freesurfer and created annotation and segmentation files for each individual.  Here is the `subreregistered_yeo_out.nii.gz` image with the look up table I made attached. It doesn't include the values as specified above. All the files needed to run this are too big to be attached here, so if you need them I can find another way to get them to you. 
![image](https://user-images.githubusercontent.com/73361030/233802813-c6ec9d28-8ef5-4023-aa8e-5989b832b260.png)

**Comment by ntustison** [comment]
This looks like the label image was warped to the subject space *not* using a label-friendly interpolation method.  That would definitely produce extraneous labels.

**Comment by j-dengler** [comment]
There is a step where we register the label image back to the T1w because we were having issues extracting cortical thickness without it. This is what the original label image looks like. 
![image](https://user-images.githubusercontent.com/73361030/233803485-1dc4e480-e3d6-4f02-ad07-96007f2db376.png)

**Comment by ntustison** [comment]
So it looks like my guess is correct.

**Comment by j-dengler** [comment]
Thanks! I removed the registration step, but I am now only getting right hemispheric values. Any ideas on why this might be happening? 
[sub-1056121_corticalthickness.txt](https://github.com/ANTsX/ANTs/files/11302204/sub-1056121_corticalthickness.txt)
[sub-1056121_yeoLUT.txt](https://github.com/ANTsX/ANTs/files/11302205/sub-1056121_yeoLUT.txt)

**Comment by ntustison** [comment]
You don't want to *remove* the registration step.  You simply want to warp the label image using the appropriate interpolation method (e.g. ``antsApplyTransforms ... -n nearestNeighbor ...``).  This is basic stuff which you should have a handle on before you try to do more complicated tasks.  Have you worked through the various ANTs tutorials?
