### ISSUE TITLE
ANTsCorticalThickness.sh gives error in Step 6

### ISSUE THREAD

**Issue by akelkar26** [ANTsX/ANTs#1528]
Hi,

I am using ANTsCorticalThickness.sh to get cortical thickness maps and eventually get cortical thickness values. 

The ANTsCT script however throws an error in the 6th step.
I have created my own template and masks and priors of my population data.

Here are the inputs:

Raw T1w:

![image (10)](https://user-images.githubusercontent.com/40644674/234353110-44359ed8-cff1-492e-9c06-5905aa27c92a.png)

Brain mask:

![image (11)](https://user-images.githubusercontent.com/40644674/234353191-31c2b412-5bb6-4f98-8651-b458b405b930.png)

Brain mask smoothed:

![image (12)](https://user-images.githubusercontent.com/40644674/234353378-3a4d9d3d-b2e7-4241-8b4f-17668844b727.png)

Population Template:

![image (13)](https://user-images.githubusercontent.com/40644674/234353429-28b1baf3-3c49-410a-abd7-b67b10e5a096.png)

Prior 1 and 2 examples:

![image (14)](https://user-images.githubusercontent.com/40644674/234353679-d4b04ca6-d10f-4c65-96ed-ab32b437ad86.png)

![image (15)](https://user-images.githubusercontent.com/40644674/234353705-ec1a397f-9724-4fe1-9ae8-368a6e83ff2d.png)

The error and warning is as follows:

![image (16)](https://user-images.githubusercontent.com/40644674/234353971-7b1865f8-2bcc-4c30-ba9f-64198bf9ba62.png)

![image (17)](https://user-images.githubusercontent.com/40644674/234353996-ef7e5882-ba59-4baf-b4ed-de4dbec01746.png)

ANTs Version: 2.3.5.dev224-g5f1fa
Compiled: Mar 5 2021 23:24:29

ProductName: macOS
ProductVersion: 11.6.8
BuildVersion: 20G730

Could you please help with this issue?
Any insight is appreciated. 

Thank you
Best,
Apoorva

**Comment by cookpa** [comment]
I've not seen this before. Can you attach the full output of the call to `antsCorticalThickness.sh` as a text file?

**Comment by akelkar26** [comment]
Hi,

Here is full output of the command:
[antsCorticalThickness_out.txt](https://github.com/ANTsX/ANTs/files/11325775/antsCorticalThickness_out.txt)

Please let me know if you need anything else. 

Thank you for helping me troubleshoot this.

Best,
Apoorva

**Comment by cookpa** [comment]
Is there a reason you are running with `-d 2`?

**Comment by akelkar26** [comment]
Oh, realized the mistake, it should be `-d 3`
I tested it out with that and it worked. 

So sorry for the oversight. Thank you for helping me figure that minor mistake fast and apologies again. 

I will close this ticket.

Thank you once again. 
Best,
Apoorva
