### ISSUE TITLE
Limiting CPU use

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#1536]
Is there any way to tell ANTs to limit its CPU use? I am experiencing some unexplained ANTs-induced system reboots, which might be due to the service provider detecting ANTs CPU load as suspicious (or perhaps some other issue I wasn't able to track down, in any case no indicators of OOM or segfaults are anywhere in my logs).

It would be great if I could just tell ANTs itself to take it a bit slower :)

Here's the code that induces the breakage: https://github.com/IBT-FMI/mouse-brain-templates_generator/blob/41616b3b8c2d246da47557e77023aa7fda8b04d6/code/abi2dsurqec_40micron.sh#L29

It can be run by cloning the repo and running `make abi2dsurqec`.

This is the stdout I get from that: https://ppb.chymera.eu/724617.log

Here is a small script (and output) I set up to monitor CPU load and memory until the system goes down: https://ppb.chymera.eu/878f14.log

**Comment by gdevenyi** [comment]
Besides the ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS it is not an application's responsibility to reduce CPU usage. Use something like cgroups if you want to resource constrain software.

**Comment by cookpa** [comment]
`ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS` should control CPU load.

I haven't used `-n MultLabel` in some time, I don't know if `-n GenericLabel` is more efficient.

If you have a very large number of labels, label interpolation (other than nearest neighbor) can use a lot of RAM.
