### ISSUE TITLE
Any displacement field transform crashes with error

### ISSUE THREAD

**Issue by chrisadamsonmcri** [ANTsX/ANTs#1537]
**Describe the problem**

The displacement field and bspline transformations (BSpline, BSplineDisplacementField, GaussianDisplacementField) don't start with an error like this:
DisplacementFieldTransform(0x56116c2bb9d0): Input parameters size (22150920) does not match internal size (0).

**To Reproduce**

Any command of the following form:
antsRegistration -v -d 3 -u 1 --verbose 1 --float 1 --collapse-output-transforms 1 \
	--initial-moving-transform [affine.mat,0] \
	--transform BSpline[0.5,26] \
	--metric MI[ fixed1.nii.gz,moving1.nii.gz,0.3,64 ] \
	--metric Demons[ fixed2.nii.gz,moving2.nii.gz,1 ] \
	--convergence [ 100x0,1e-6,60 ] --shrink-factors 2x1 --smoothing-sigmas 4x0vox --masks mask.nii.gz \
        --output warp

**System information (please complete the following information)**

 - OS: Ubuntu
 - OS version: 22.04
 - Type of system: Desktop
 - 

**ANTs version information**
 - ANTs code version: ANTs Version: 2.4.4.dev4-gd0ddc46
Compiled: May 14 2023 18:56:09
 - ANTs installation type: Compiled from source, no modifications

**Additional information**

**Comment by ntustison** [comment]
I can't reproduce.  Please provide a complete example including images and the initial transform.

**Comment by cookpa** [comment]
Demons requires a displacement field transform so it won't work with `-t BSpline`, but `-t BSplineDisplacementField` works for me

**Comment by chrisadamsonmcri** [comment]
Sorry for the delay I will send some examples soon.

**Comment by chrisadamsonmcri** [comment]
Sorry for the delay. I tried to reproduce again but it isnt happening. You are right my original example did use BSpline only which doesnt work with Demons. Since I can't reproduce any more I will close the issue.
