### ISSUE TITLE
antsAI seg fault on 2D input

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1538]
EDIT: the floating point exception is fixed, a problem remains with seg faulting on 2D input, see posts below

**Describe the problem**

`antsAI` fails with a floating point exception.

**To Reproduce**

```

git clone https://github.com/ntustison/antsCorticalThicknessExample
cd antsCorticalThicknessExample

antsAI \
  -d 2 \
  -v 1 \
  -m Mattes[ OutputT1Only/exampleBrainExtractionInitialAffineFixed.nii.gz, OutputT1Only/exampleBrainExtractionInitialAffineMoving.nii.gz,32,Regular,0.2 ] \
  -t Affine[ 0.1 ] \
  -s [ 20,0.12 ] \
  -g [ 40,0x40x40 ] \
  -p 0 \
  -c 10 \
  -o OutputT1Only/exampleBrainExtractionInitialAffine.mat
```

**System information (please complete the following information)**

 - OS: Mac OS
 - OS version: 12.6.5
 - Type of system: Desktop
 

**ANTs version information**
 - ANTs code version: 2.4.4.post4-gd0ddc46
 - ANTs installation type: Compiled from source

**Comment by gdevenyi** [comment]
Compile with debug and launch with gdb to see if we can catch the lines where it fails?

**Comment by cookpa** [comment]
Found the bug: `antsCorticalThickness.sh` sets a 3D translation search on 2D images

**Comment by cookpa** [comment]
Upon closer inspection, the 2D / 3D parameter thing is a separate problem.

Another problem is that it crashes if there's less than 10 starting points. I think that might be related to the progress tracker I added, so I'll look into that.

That aside, with > 10 start points, this runs on Mac and on Linux via Docker (Ubuntu 18.04, GCC 7.5.0)

```
antsAI \
  -d 2 \
  -v 1 \
  -m Mattes[ Template/template_slice80.nii.gz , IXI002-Guys-0828-T1_slice90.nii.gz, 32,Regular,0.2 ] \
  -t Affine[ 0.1 ] \
  -s [ 5,0.4 ] \
  -p 0 \
  -c 10 \
  -o OutputT1Only/exampleBrainExtractionInitialAffine.mat
```

But fails on Ubuntu 20.04 GCC 9.4.0 with debug symbols. When I run GDB, it reports

```
Thread 1 "antsAI" received signal SIGSEGV, Segmentation fault.
0x0000555555824c52 in ants::antsAI<2u> (parser=0x55555796f570) at /home/vagrant/tmp/antsBuild/ANTs/Examples/antsAI.cxx:1047
1047	        axis1[d] = fixedTertiaryEigenVector[d];
```

It only seems to affect 2D images, 3D images work fine on all platforms.

**Comment by cookpa** [comment]
#1539 fixes the problem of `antsAI` crashing with a floating point exception if there are < 10 start points

**Comment by cookpa** [comment]
I revisited this but can no longer reproduce the error on Ubuntu 22.04 with GCC 11.4 using ANTs 2.5.0.post12-g9516f51, or on my usual Mac (OS 12.6.7) build.
