### ISSUE TITLE
Converting my NiftyReg commands to ANTs- Spline grid spacing

### ISSUE THREAD

**Issue by lukevano** [ANTsX/ANTs#1546]
**Describe the problem**

Dear ANTs team,
As I really enjoy using ANTs I am trying to get my NiftyReg MRI processing scripts to run using ANTs.
In order to analyse my QSM data I have to coregister a magnitude with a T1 weighted image. As the MRI protocol to acquire the magnitude image picks up a lot of distortion around the orbital frontal region it has been recommended that I use a low resolution B-spline grid for non-linear registration between the images using the code below:

# use low resolution for spline grid (-sx 15) to only correct distortions caused by large B0 inhomogeneities
reg_f3d -ref 01_T1_N3.nii.gz -flo 01_mag_firstTE.nii.gz -res 02_mag_firstTE_nonlin.nii.gz -aff 02_mag2T1_affine.xfm -cpp 02_mag2T1_cpp.nii.gz -pad 0 -nopy -sx 15 -voff

This works very well for my data but I end up with a control point grid that I can't work out how to use this with antsApplyTransforms.

As I want to use ANTs for my entire analysis pipeline, could you let me know how to set the final grid spacing along the x axis in ANTs, or how I can use the control point grid generated by NiftyReg in antsApplyTransforms.

Thanks again for all your help with ANTs!
Best wishes,
Luke

**To Reproduce**

I have attached the data used for this coregistration. I can't attach the .xfm file but it has the following values in it.
0.9994869 -0.002942922 0.005194017 0.2384432
0.002128954 0.9992614 -0.05240593 -1.315948
-0.01334963 0.04986078 0.972747 1.649201
0 0 0 1

[02_mag2T1_cpp.nii.gz](https://github.com/ANTsX/ANTs/files/11635817/02_mag2T1_cpp.nii.gz)
[01_T1_N3.nii.gz](https://github.com/ANTsX/ANTs/files/11635819/01_T1_N3.nii.gz)
[01_mag_firstTE.nii.gz](https://github.com/ANTsX/ANTs/files/11635820/01_mag_firstTE.nii.gz)

**Comment by cookpa** [comment]
I'm not sure this is what you're asking but if you're using `BSplineSyN`, you can specify the initial mesh size in 3D, eg `-t BSplineSyN[ 0.2, AxBxC, 0, 3 ]`.

**Comment by lukevano** [comment]
Thanks for letting me know. I've had play around with the parameters and my results are now much better!
