### ISSUE TITLE
File extension determination failure if input filename contains dots in antsMultivariateTemplateConstruction2.sh

### ISSUE THREAD

**Issue by sufkes** [ANTsX/ANTs#1551]
https://github.com/ANTsX/ANTs/blob/dd359c0a0a4bba3934464335e6dd1552cd73f21d/Scripts/antsMultivariateTemplateConstruction2.sh#LL907C4-L907C44

If doing multivariate template construction with input files specified in a CSV file, this line will get the extension incorrect if the input CSV file name contains more than one dot (e.g. my.list.of.files.csv). 

I usually do something like `extension=$(echo $filename | rev | cut -d '.' -f 1 | rev)` to handle this case.

**Comment by ntustison** [comment]
A pull request would be welcome.

**Comment by cookpa** [comment]
@sufkes would you mind copying the scripts from #1552 and seeing if this fixes the problems for you?

**Comment by cookpa** [comment]
Please reopen if there's still problems
