### ISSUE TITLE
Template construction script choice

### ISSUE THREAD

**Issue by jacobsanz97** [ANTsX/ANTs#1553]
Hi!

I have a question about which of '_antsMultivariateTemplateConstruction.sh_' and '_antsMultivariateTemplateConstruction2.sh_' to use, and was hoping this would be a good place to ask it.

My goal is to replicate [this 2014 study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6868950/) as faithfully as I can, and see if the results hold up (as part of the [LivingPark project](https://github.com/LivingPark-MRI)).

The 2014 study uses ANTs to construct a group template, presumably with one of the two aforementioned scripts, but doesn't specify which one, or any parameters I can use to identify it. The study references this [ANTs publication](https://www.sciencedirect.com/science/article/pii/S1053811909010611) for the group template construction algorithm, but the reference doesn't specify the exact script either.

It is my understanding from reading [an issue](https://github.com/ANTsX/ANTs/issues/1359) on here that while the two scripts are theoretically similar, one uses ANTS and the other uses antsRegistration, which according to [the wiki](https://github.com/ANTsX/ANTs/wiki/ANTS-and-antsRegistration) can perform certain computations differently.

I have a NeuroDocker-generated ANTs 2.0.3 container running (I assume this was likely the version used at the time of the 2014 study), and both scripts are accessible in it.

Do you have any suggestion on which of the two scripts I should use for my replication purposes?

Thanks a ton for your time :)
-Jacob.

**Comment by ntustison** [comment]
Either one would probably work and produce similar results.  However, ``amvtc.sh`` probably has less of a memory footprint so you could start there.

**Comment by jacobsanz97** [comment]
Thank you both for your answers! :)
