### ISSUE TITLE
multi-subject registration consumes all memory

### ISSUE THREAD

**Issue by russellu** [ANTsX/ANTs#1557]
**Describe the problem**

i'm running antsRegistration followed by antsApplyTransform on a group of 22 subjects using a recent Ubuntu install. the problem is, the memory load is cumulative meaning the OS doesn't seem to give up memory used for previous subjects. so after around 8 subjects it crashes with out of memory. i got around this by simply restarting my OS and running my loop 3 times on subjects 1-8, 9-16, and 17-22 but i would like to avoid doing this in the future. i don't know if this is an ANTs issue or a ubuntu issue. thanks

**To Reproduce**

**System information (please complete the following information)**

 - OS: [e.g. Mac OS]
 - OS version: [e.g. 10.15.1]
 - Type of system: [Desktop, laptop, HPC cluster, cloud instance,
   other]

**ANTs version information**
 - ANTs code version: [output of antsRegistration --version]
 - ANTs installation type: [Compiled from source, downloaded binary
   (from where?), installed by another package (which?), installed in
   container (URL?), other (please specify)]

**Additional information**

**Comment by gdevenyi** [comment]
You haven't provided any actual commands.

**Comment by russellu** [comment]
> You haven't provided any actual commands.

actually i'm running into the same problem with afni so i guess you can just delete this thread, it's most likely the OS

**Comment by cookpa** [comment]
I'll close for now but feel free to update if you'd like
