### ISSUE TITLE
No output files after antsRegistrationSyN.sh

### ISSUE THREAD

**Issue by NewAnts** [ANTsX/ANTs#1559]
Hello,

I am new to ants. I was trying to register 3D T1w images to MNI space for practice with input as follow:

 antsRegistrationSyN.sh -d 3 -f /mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/mni_t1.nii -m /mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/all_tissues_masked_n4corrected.nii -o /mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/t1_mni.nii

It took some hours to process and complete affine, rigid and SyN registration, and I got the output as follows:

/usr/bin/antsRegistrationSyN.sh: line 670:  1999 Killed                  $COMMAND
 Registration finished. The antsRegistration call was:
--------------------------------------------------------------------------------------
/usr/bin//antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [ /mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/t1_mni.nii,/mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/t1_mni.niiWarped.nii.gz,/mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/t1_mni.niiInverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] --initial-moving-transform [ /mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/mni_t1.nii,/mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/all_tissues_masked_n4corrected.nii,1 ] --transform Rigid[ 0.1 ] --metric MI[ /mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/mni_t1.nii,/mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/all_tissues_masked_n4corrected.nii,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[ 0.1 ] --metric MI[ /mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/mni_t1.nii,/mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/all_tissues_masked_n4corrected.nii,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[ 0.1,3,0 ] --metric CC[ /mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/mni_t1.nii,/mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/all_tissues_masked_n4corrected.nii,1,4 ] --convergence [ 100x70x50x20,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox
--------------------------------------------------------------------------------------
Moving image resampled into fixed space: /mnt/c/Users/xxx/Downloads/Mri_data/Template_standard_space/t1_mni.niiWarped.nii.gz
Fixed image resampled into moving space: /mnt/c/Users/xx/Downloads/Mri_data/Template_standard_space/t1_mni.niiInverseWarped.nii.gz
------------------------------------------------------------------------------------------------------------------------------------------------
However, when I tried to check the output files, they were not there at the mentioned output location. I wonder what's the issue?

Any help would be appreciated. Thanks!

**Comment by cookpa** [comment]
> /usr/bin/antsRegistrationSyN.sh: line 670: 1999 Killed $COMMAND

This means something went wrong. It could mean the process ran out of memory, or exceeded some resource limitation like max run time.

**Comment by NewAnts** [comment]
Any suggestions would be appreciated. Should I try to rerun it again with antsRegistrationSyNQuick.sh?

**Comment by cookpa** [comment]
You can try quick, or downsample the data. If that works, it's probably memory

**Comment by NewAnts** [comment]
Thanks!
