### ISSUE TITLE
Problem installing ANTs via SuperBuilder

### ISSUE THREAD

**Issue by LancePhysicsCoding** [ANTsX/ANTs#1560]
Hello. I have problems using Superbuilder. I have windows 11 and WSL. When I run installANTs.sh it goes well at the beginning but when the program starts to build CXX Objects Examples it stops at 1%. Here what's written in the terminal: 

[ 52%] Performing forcebuild step for 'ANTS'
[ 58%] Performing build step for 'ANTS'
[  0%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistration3DDouble.cxx.o
[  0%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DDouble.cxx.o
[  0%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DFloat.cxx.o
[  1%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistration3DFloat.cxx.o   

I have a good internet connection but it stays forever at 1% ... what could be the problem? Thanks in advance :)

**Comment by cookpa** [comment]
There's no Internet access at that point, something is causing the compiler to go slowly or hang entirely. Could be disk related, or something to do with the build environment.

I don't have Windows 11 but if you provide the information requested in the issue template for build problems, it's possible that someone might be able to help.

**Comment by LancePhysicsCoding** [comment]
I opened a new issue with all the requested information, sorry for this one.
