### ISSUE TITLE
Issue in template construction of T1w images using antsMultivariateTemplateConstruction

### ISSUE THREAD

**Issue by NewAnts** [ANTsX/ANTs#1565]
I am trying to create a template of 5 T1w images using antsMultivariateTemplateConstruction

antsMultivariateTemplateConstruction.sh -d 3 -b 1 -i 3 -g 0.25 -j 2 -c 2 -k 1 -w 1 -m 30x50x20 -t SyN -n 0 -r 1 -o /mnt/d/MY_ /mnt/d/selection/*T1w.nii

It takes all the files and process it for couple of minutes
--------------------------------------------------------------------------------------
 Creating template /mnt/d/MY_template0.nii.gz from a population average image from the inputs.
   /mnt/d/selection/sub-11001_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii /mnt/d/selection/sub-11004_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii /mnt/d/selection/sub-11009_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii /mnt/d/selection/sub-11012_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii /mnt/d/selection/sub-11018_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii

then it runs to a problem
--------------------------------------------------------------------------------------
summarizeimageset: ERROR - output file /mnt/d/MY_template0.nii.gz could not be created

I wonder what's the issue here? The memory can't be the issue as I have 2TB space. Any help would appreciated.

Thanks!

**Comment by ntustison** [comment]
Were you able to run this 2-D example:

https://github.com/ntustison/TemplateBuildingExample

?

**Comment by NewAnts** [comment]
I tried running the 2-D images after your comment using antsMultivariateTemplateConstruction.sh and it give me the same error

**Comment by ntustison** [comment]
Are you sure you have write access to the output location?

**Comment by NewAnts** [comment]
Yes I am sure that I have the write access to the output location

**Comment by NewAnts** [comment]
Any help would be appreciated! Thanks

**Comment by ntustison** [comment]
I can't reproduce and without further information, I'm out of ideas.

**Comment by NewAnts** [comment]
Hi, I rechecked the write access to the output location and it's in order. Still stuck on this issue, not sure what's wrong :(

**Comment by cookpa** [comment]
Let's try to learn more from the example.

```
git clone https://github.com/ntustison/TemplateBuildingExample.git
cd TemplateBuildingExample/BrainSlices
bash ./templateCommandSyN.sh 2>&1 | tee brainSlices.out
```

You can attach `brainSlices.out` by dragging and dropping it here.

Also, what OS are you running on? What's your ANTs version?

**Comment by NewAnts** [comment]
Hi, Thanks for reaching out. Here is the brainSlices.out file which I got after running the above lines. 
[brainSlices.docx](https://github.com/ANTsX/ANTs/files/12103146/brainSlices.docx)

My OS is Windows 10, running on 18.04.5 Ubantu with ANTs version: 2.1.0-gGIT-N

**Comment by cookpa** [comment]
It appears to be failing when trying to make the initial template. It seems you have a script that is newer than your ANTs version.

Try updating your ANTs binaries to the current version (build instructions on Wiki, binaries available on the release page).

**Comment by NewAnts** [comment]
Thanks very much Philip!! It works pretty well now. Just to confirm that this is the main file that I should be interested in Mytemplate0.nii.gz?
Thanks a lot again!

**Comment by cookpa** [comment]
The template is the output of the script, yes. The script will also leave behind intermediate templates, and the last set of registrations (done before the final template update). You can review these to check convergence and if there are any outliers.

**Comment by NewAnts** [comment]
Thank you very much!
