### ISSUE TITLE
Segmentation Fault when running antsRegistration

### ISSUE THREAD

**Issue by zqsha** [ANTsX/ANTs#1570]
Hi experts,
This question is similar to #1266. Previously, I used the following command line to register two images within a small region, the command line works very well.
antsRegistration \
--dimensionality 3 \
--float 1 \
--collapse-output-transforms 1 \
--output [ vol_1_,vol_1_Warped.nii.gz,1] \
--interpolation BSpline[2] \
--use-histogram-matching 1 \
--winsorize-image-intensities [ 0.005,0.995 ] \
-x moma.nii \
--initial-moving-transform [ nn_reference.nii,vol_1.nii,1 ] \
--transform Rigid[ 0.1 ] \
--metric MI[ nn_reference.nii,vol_1.nii,1,32,Regular,0.25 ] \
--convergence [ 250x100,1e-6,10 ] \
--shrink-factors 2x1 \
--smoothing-sigmas 1x0vox \
--transform SyN[ 0.1,3,0 ] \
--metric CC[ nn_reference.nii,vol_1.nii,1,2 ] \
--convergence [ 50x0,1e-6,10 ] \
--shrink-factors 2x1 \
--smoothing-sigmas 1x0vox

But, this time I wanted to register two brains by using the following command line, and then it only showed "Segmentation fault (core dumped)", even though I added "export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=10". There is no other output indicating where the issue is. Our server has 28 cores and 500GB of memory. So, I set 10 threads. But, I think it might be a multi-threading issue.
antsRegistration \
--dimensionality 3  \
--float 0  \
--collapse-output-transforms 1  \
--interpolation BSpline[5] \
--output [registered1_mask_,registered1_Warped_mask.nii,registered1_InverseWarped_mask.nii]  \
--use-histogram-matching 0  \
--winsorize-image-intensities [0.005,0.995]  \
--initial-moving-transform initial_matrix.txt \
--transform Rigid[0.1]  \
--metric MI[EPI.nii,ANAT.nii,1,32,Regular,0.25]  \
--convergence [1000x500x250x100,1e-6,10]  \
--shrink-factors 12x8x4x2  \
--smoothing-sigmas 4x3x2x1vox  \
--transform Affine[0.1]  \
--metric MI[EPI.nii,ANAT.nii,1,32,Regular,0.25]  \
--convergence [1000x500x250x100,1e-6,10]  \
--shrink-factors 12x8x4x2  \
--transform SyN[0.1,3,0]  \
--metric CC[EPI.nii,ANAT.nii,1,4]  \
--convergence [50x50x70x50x20,1e-6,10]  \
--shrink-factors 10x6x4x2x1  \
--smoothing-sigmas 5x3x2x1x0vox

Do you have any thoughts on fixing this issue?

Thanks,
Cain

**Comment by zqsha** [comment]
Thanks for your feedback. I just now checked that my test data is about 85MB, when I upload the file, Github shows "File size too big: 25MB" are allowed. Do you have any thoughts about how to upload these big files? Thanks.

**Comment by ntustison** [comment]
A link to DropBox or other such online storage would be fine.  WeTransfer would also work.

**Comment by ntustison** [comment]
You forgot a "--smoothing-sigmas" option.  There are three stages and you only have two.

**Comment by cookpa** [comment]
Good catch @ntustison . I will update the checks so that there's a defined error if the number of smoothing, shrink, convergence args do not match the number of stages.

**Comment by zqsha** [comment]
Thank you so much @ntustison and @cookpa. I really appreciated it. I just now tried again and it's working now. Sorry for missing one option.

**Comment by cookpa** [comment]
Fixed by #1571
