### ISSUE TITLE
ANTs on the new Apple M2 chip

### ISSUE THREAD

**Issue by akira425** [ANTsX/ANTs#1572]
Hi All,
Does anybody have experience with building and running ANTs with the new Apple M2 chip set? 
It seems to me that antsRegistration does not work well for some reason.

 Thanks,
akira

**Comment by akira425** [comment]
Error message is shown below.


_________



*** Running B-spline SyN registration (updateMeshSizeAtBaseLevel = [10, 10, 7], totalMeshSizeAtBaseLevel = [4294967295, 4294967295, 4294967295]) ***

Exception caught: 
itk::ExceptionObject (0x600001234080)
Location: "unknown" 
File: /Users/toga/ANTS/build/staging/include/ITK-5.4/itkBSplineScatteredDataPointSetToImageFilter.hxx
Line: 223
Description: ITK ERROR: BSplineScatteredDataPointSetToImageFilter(0x110e0aa80): The number of control points must be greater than the spline order.

**Comment by ntustison** [comment]
What's the actual command call?

**Comment by akira425** [comment]
Thank you for your comment.
The actual command call is shown below.

+++


toga@togaMacBook-Pro build % antsRegistrationSyN.sh -d 3 -f drnT1.nii -m standard_T1.nii -o move_ -n 32 -t b

**Comment by ntustison** [comment]
What about 

```
$ antsRegistrationSyN.sh -d 3 -f drnT1.nii -m standard_T1.nii -o move_ -n 32 -t s
```

?

**Comment by akira425** [comment]
Thank you for your repley.
Files shown below were made.

move_InverseWarped.nii.gz
move_Warped.nii.gz
move_1InverseWarp.nii.gz
move_1Warp.nii.gz
move_0GenericAffine.mat


____________



Total elapsed time: 525
 Registration finished. The antsRegistration call was:
--------------------------------------------------------------------------------------
/Users/toga/ANTS/install/bin/antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [ move_,move_Warped.nii.gz,move_InverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] --initial-moving-transform [ drnT1.nii,standard_T1.nii,1 ] --transform Rigid[ 0.1 ] --metric MI[ drnT1.nii,standard_T1.nii,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[ 0.1 ] --metric MI[ drnT1.nii,standard_T1.nii,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[ 0.1,3,0 ] --metric CC[ drnT1.nii,standard_T1.nii,1,4 ] --convergence [ 100x70x50x20,1e-6,10 ] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox
--------------------------------------------------------------------------------------
Moving image resampled into fixed space: move_Warped.nii.gz
Fixed image resampled into moving space: move_InverseWarped.nii.gz
--------------------------------------------------------------------------------------

**Comment by akira425** [comment]
Thanks for your help. 
I hope this file is helpful for solving the problem. 

[entire.txt](https://github.com/ANTsX/ANTs/files/12166411/entire.txt)

**Comment by ntustison** [comment]
The issue should be resolved with [this commit](https://github.com/ANTsX/ANTs/pull/1575).  Thanks for pointing this out.

**Comment by akira425** [comment]
Thank you.
Could you please how I fix this problem.
Should I copy this commit to somewhere?

**Comment by ntustison** [comment]
You have to [reinstall from source](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS).
