### ISSUE TITLE
Do we still need ANTSPATH?

### ISSUE THREAD

**Issue by ghisvail** [ANTsX/ANTs#1573]
With ANTs now available for Conda, I was wondering whether there is any use for `ANTSPATH`?

Right now, some bash scripts cannot be run without explicitly setting `ANTSPATH` to the Conda env bin directory, despite the guarantee that all binaries will be present under `PATH`. I am actually wondering what use cases for `ANTSPATH` are not already covered by `PATH` overrides? 

I am tempted to patch all scripts to strip `ANTSPATH` from the Conda package, but it looks like other distributions of ANTs, like Homebrew, Debian or RPM packages, could benefit from this change too.

WDYT?

**Comment by cookpa** [comment]
#650 @gdevenyi once again ahead of the curve

I was against changing ANTSPATH back then, but now I think I would be in favor of it. With scripts automatically installed to the PATH, and the availability of containerized solutions, I don't find ANTSPATH to be as useful as I once did.

**Comment by ghisvail** [comment]
My bad, I only searched through the opened issues 😅

**Comment by ghisvail** [comment]
> I was against changing ANTSPATH back then, but now I think I would be in favor of it.

Happy to submit a patch for it and apply it to the Conda package whilst waiting for a new release.

Several people already complained for it privately.

**Comment by cookpa** [comment]
Pinging other external devs for opinions: @mattcieslak @satra @oesteban @jcohenadad

**Comment by cookpa** [comment]
@ntustison @stnava @jeffduda LMK if there's any use cases we might need to think about

**Comment by ntustison** [comment]
I don't other than being generally in favor of simplification.  Thanks for this @cookpa.

**Comment by cookpa** [comment]
Looks like everyone is in agreement @ghisvail , I'll test your PR when you're ready. Thanks

**Comment by ghisvail** [comment]
I grepped my way to a patch in #1574. It's ready for you to review @cookpa 👍
