### ISSUE TITLE
Dealing with memory issues

### ISSUE THREAD

**Issue by NewAnts** [ANTsX/ANTs#1576]
Hi,
I am relatively new to ANTs. 

I am currently registering a template to MNI space, and I am running into 'out of memory error'

/usr/bin/antsRegistrationSyN.sh: line 485:  1868 Killed
Out of memory: Killed process 6293 (antsRegistratio) total-vm:20068384kB, anon-rss:14888744kB, file-rss:4kB, shmem-rss:0kB, UID:1000 pgtables:37784kB oom_score_adj:0

I am using Ants 2.1.0 with RAM of 32GB (available physical memory 18.8GB and 20.8GB virtual memroy) in 18.04.5 Ubantu on windows 10.

What would be the best option, increase RAM or to update the ANTs version? Or are there any better options here?

**Comment by cookpa** [comment]
What size are the images?

**Comment by NewAnts** [comment]
Template is around 77MB and MNI around 132MB

**Comment by cookpa** [comment]
What is the grid size in voxels? That is what will determine memory use in registration.

**Comment by NewAnts** [comment]
257x305x257 i.e., 20144945 voxels for template and 394x466x378 i.e., 69402312 voxels for MNI

**Comment by cookpa** [comment]
OK those are big images, so it's expected that it requires a lot of memory. First thing to try would be using `--float`

**Comment by NewAnts** [comment]
Not sure if I followed you there on using --float

**Comment by NewAnts** [comment]
So using the float the new code should look like this: antsRegistrationSyN.sh --float 1 -d 3 -f fixed.nii -m moving.nii -o outputPrefix ? Especially using single precision float?

**Comment by cookpa** [comment]
Sorry, `--float` is when calling `antsRegistration` directly. When using the script, you would add `-p f`

**Comment by NewAnts** [comment]
Unfortunately, it went out of memory again even after including --float command!  :(
I have noticed that it goes out of memory in the last section especially during the SyN process

**Comment by gdevenyi** [comment]
For details on typical human-brain registration memory requirements, I did some benchmarking, https://github.com/gdevenyi/antsRegistration-benchmarking it was a long time ago, so, consider it more of scaling ideas that hard values.

**Comment by NewAnts** [comment]
Thank you very much for your time! Will look into it and will share further details soon
