### ISSUE TITLE
Does ANTs could register two 3D brains that have different z-lengths?

### ISSUE THREAD

**Issue by seokjin9804** [ANTsX/ANTs#1579]
I am trying to use ANTs to register two bee-brain.
One bee-brain has 20 slices(cover half of brain).
Another bee-brain has 3 slices(cover only little part of brain). 
Two images are came from different bees. (Also have different resolution)
By registering small images(3 slices) to big images (20 slices), I want to know relative z-position of small images in full bee-brain model.
Is it possible to register that two bee-brain with ANTs?
Thanks!

**Comment by cookpa** [comment]
It's possible to do a slab-to-whole brain registration like this. It may require some work to initialize the registration correctly.

Can you share example images?

**Comment by seokjin9804** [comment]
Oh that sound's cool.
Basically I have this 20 slices.
![image](https://github.com/ANTsX/ANTs/assets/140678281/495ade84-f4b2-48f4-8adf-ab7f805ed63e)
And for example, I want to find the relative z-level of this target slice.
![image](https://github.com/ANTsX/ANTs/assets/140678281/4e812eb9-9c2e-4b2a-a4d3-72443e81def4)

My current strategy is run 2D to 2D registration for each 20 slice to target slice with affine registration and check the NCC value of aligned image to find the best match slice.

If there is automatic 2D to 3D registration, it would be great!!

**Comment by cookpa** [comment]
Are the three slices in the small brain contiguous?
