### ISSUE TITLE
using CompositeTransformUtil for multisite TBM

### ISSUE THREAD

**Issue by EmilyLars** [ANTsX/ANTs#1581]
I am using CompositeTransformUtil for the first time and want to make sure I'm setting this up right. My goal is multisite TBM analyses and the set up I've done so far is:
1. make site specific templates with antsMultivariateTemplateConstruction2
2. run antsRegistration on all subjects to their respective site templates
3. create overall template of the templates
4. register the site templates to overall template to get warp info

I think my next step is
5. concatenate warp info from steps 2 and 4 to apply to the individual subject data 
6. antsApplyTranforms using the output affine and warp files from step 5
7. CreateJacobianDeterminantImage

So 2 questions, one general - does this set up make sense? And specifically, when concatenating warp info with CompositeTransformUtil would I include the affine.mat and warp.nii.gz files for both steps, so 4 input files?
Thanks!

**Comment by gdevenyi** [comment]
Hi, you may be interested in https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction which offers a multilevel-DBM based implementation similar to what you're proposing. I designed it for longitudinal DBM, but your multisite model would fit nicely into the two-level construction.

Regarding `CompositeTransformUtil` I think `antsApplyTransforms` has subsumed the functions.

**Comment by ntustison** [comment]
> 1.  So 2 questions, one general - does this set up make sense? 

Sure.

> 2.  And specifically, when concatenating warp info with CompositeTransformUtil would I include the affine.mat and warp.nii.gz files for both steps, so 4 input files?

Yes, as @gdevenyi mentioned, ``antsApplyTransforms`` is the only program you need here.

**Comment by EmilyLars** [comment]
Thanks all! Though I just realized I should use `unbiased_pairwise_registration` instead so I'll redo with that
