### ISSUE TITLE
Fail To Install ANTs with This Error Message! Please Help!

### ISSUE THREAD

**Issue by tawwang** [ANTsX/ANTs#1586]
### Discussed in https://github.com/ANTsX/ANTs/discussions/1585

<div type='discussions-op-text'>

<sup>Originally posted by **tawwang** August 11, 2023</sup>
After the installation step, I received the following message:

"Install the project...
-- Install configuration: "Release"
CMake Error at Examples/cmake_install.cmake:41 (file):
  file cannot create directory: /new/install/dir/lib.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)"

I tried to fix the problem above using the following 3 ways but none of them works:

1.  based on the suggestions in the manual, I input: make install DESTDIR=/new/install/dir

2. alternatively, I input: cmake -DCMAKE_INSTALL_PREFIX=/new/install/dir .
make install

3. add sudo in front of make install instead of just using make install

If you have any answers to this problem, please help! 

Much appreciated,
Tao
</div>

**Comment by gdevenyi** [comment]
It is inappropriate to spam the issue tracker after also opening a discussion.

**Comment by tawwang** [comment]
> It is inappropriate to spam the issue tracker after also opening a discussion.

sorry.. I should have only asked this question in the Issue tracker.

**Comment by cookpa** [comment]
Are you actually trying to install to `/new/install/dir`? This is a placeholder, you should change it to somewhere you have write permission.
