### ISSUE TITLE
Request for a new point release

### ISSUE THREAD

**Issue by ghisvail** [ANTsX/ANTs#1589]
I have had to resort to packaging an intermediate commit of the development branch to get rid of the ANTSPATH issues. However, Conda's packaging policy strongly favors building from source tarballs corresponding to a released version.

Would it be possible to distribute a new point release (version 2.4.5?) corresponding to the current tip of the development branch? This way I can revert the Conda package to use release tarballs again, and let Conda's CI handle future updates automatically.

**Comment by cookpa** [comment]
Yes, we can make a release. I'm traveling right now but can get this done in a week or so

**Comment by ghisvail** [comment]
That would be awesome. Thank you so much 🙏

**Comment by cookpa** [comment]
No problem, 2.5.0 now up. Thanks for all your help
