### ISSUE TITLE
antsMultivariateTemplateConstruction2.sh repeats N4 on every iteration

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#1590]
The location of the N4 code for template construction:
https://github.com/ANTsX/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L1490-L1492

Results in N4 being re-run on the input files for every iteration of the template construction. Computational time could be saved if it were moved to a step beforehand, or if a file check were added to see if the N4 processed files already exist.

**Comment by ntustison** [comment]
Thanks @gdevenyi .  Do you want to put together a pull request or should I put it on my to-do list?

**Comment by gdevenyi** [comment]
If you agree this is worth addressing, I can do a PR.

Shall I check the other model scripts as well?

**Comment by ntustison** [comment]
Sure, as to the PR.  But what model scripts are you referring to?

**Comment by gdevenyi** [comment]
Btp and antsMultivariateTemplateConstruction.sh

**Comment by cookpa** [comment]
Thanks for this @ntustison and @gdevenyi 

Should we also remove the default `-b [ 200 ]`? It will cause problems for non-human images.

**Comment by gdevenyi** [comment]
> Should we also remove the default -b [ 200 ]? It will cause problems for non-human images.

I agree that's an issue, but I'm not sure what the default would do without that. In general the tools I write which wrap around ANTs, I usually calculate the largest physical scale of the image and start with that as the N4 distance.

**Comment by ntustison** [comment]
IMO, ideally we would remove N4 entirely from the template building scripts and simply leave it to the user to do any preprocessing.  Outside of that, I agree with @gdevenyi in calculating it on the fly.
