### ISSUE TITLE
The documentation about script command parameters and their meanings for ANTs

### ISSUE THREAD

**Issue by angolin22** [ANTsX/ANTs#1595]
Thanks for your excellent work!

Could you please tell me where is the documentation about the script command parameters and their meanings for each function of ANTs?

many thanks!

**Comment by cookpa** [comment]
Additional background in the wiki

https://github.com/ANTsX/ANTs/wiki

and this collection of ANTs examples

https://github.com/stnava/ANTsTutorial/blob/master/handout/antsGithubExamples.Rmd

**Comment by angolin22** [comment]
many thanks
