### ISSUE TITLE
ANTs - ImageMath error loading shared libraries

### ISSUE THREAD

**Issue by kjobson-neuro** [ANTsX/ANTs#1598]
**Describe the problem**

I originally compiled ANTs myself. However, I was receiving this error today:
/opt/ANTs/bin/ImageMath: error while loading shared libraries: libitkhdf5_cpp-shared-5.4.so.1: cannot open shared object file: No such file or directory

I had assumed it had something to do with an error in my installation, [as this seemed to be addressed in a previous thread](https://github.com/gdevenyi/neuralabc_modules/issues/2). I then deleted my compiled version and used the conda command to install ANTs instead (hoping the issue stemmed from an incorrect installation).

When I try to run ANTs Brain Extraction now, I get this error:
ImageMath: error while loading shared libraries: libITKIOTransformMINC-5.3.so.1: cannot open shared object file: No such file or directory

**To Reproduce**

The data cannot be shared, but this is the command: antsBrainExtraction.sh -d 3 -a fmriresults01/rel3_derivatives/rel3_dhcp_anat_pipeline/sub-CC00065XX08/ses-18600/anat/sub-CC00065XX08_ses-18600_T2w.nii.gz -e NKI10AndUnder/T_template0.nii.gz -m NKI10AndUnder/T_template0_BrainCerebellumProbabilityMask.nii.gz -o derivatives/ants/sub-CC00065XX08/anat_Stripped.nii

I did test the command with a T1w image to be sure it was not the modality, with the same resulting error.

**System information (please complete the following information)**

 - OS: Ubuntu 
 - OS version: 22.04.2 (jammy)
 - Type of system: Desktop
 

**ANTs version information**
 - ANTs code version: [output of antsRegistration --version]
 - ANTs installation type: [Compiled from source, downloaded binary
   (from where?), installed by another package (which?), installed in
   container (URL?), other (please specify)]

When I try and use 'antsRegistration --version', I also receive this error: antsRegistration: error while loading shared libraries: libITKIOTransformMINC-5.3.so.1: cannot open shared object file: No such file or directory

I installed ANTs today using 'conda install -c conda-forge ants'.

**Additional information**

ITK-5.2 is installed and available on my machine. My compiled version of ANTs worked fine previously for another individual a month ago. I am wondering if there was an update to the packages on the Linux machine that caused this issue.

**Comment by gdevenyi** [comment]
Any reason you can't use the compiled binaries available attached to the releases?

**Comment by kjobson-neuro** [comment]
> Any reason you can't use the compiled binaries available attached to the releases?

I was originally using the compiled binaries but was still receiving the error, so I downloaded ITK in case there was some issue there.

> I don't know why a build that worked once would stop working, unless the libraries were moved, or your environment changed. Does `LD_LIBRARY_PATH` still include the ANTs libraries?

It was for different users - I think I potentially reset my bash profile recently, which may have removed my ```LD_LIBRARY_PATH```. I just recompiled ANTs. With ```LD_LIBRARY_PATH``` blank, I got the same error as before. I set the library path and now it is working!

Thank you for your help!

**Comment by demidenm** [comment]
@kjobson-neuro - may you share how you were able to get this to work? RUnning into a similar issue -- `error while loading shared libraries: libITKIOTransformMINC-5.3.so.1`
