### ISSUE TITLE
Issue running 

### ISSUE THREAD

**Issue by CallowBrainProject** [ANTsX/ANTs#1599]
When running antsIntermodalityIntrasubject.sh  I am getting the following odd output.

bash-3.2$ antsIntermodalityIntrasubject.sh 
/Users/danielcallow/install/bin/antsIntermodalityIntrasubject.sh: line 8: syntax error near unexpected token `fi'
/Users/danielcallow/install/bin/antsIntermodalityIntrasubject.sh: line 8: `fi'

However, I can run antsRegistrationSyN.sh without issue.

**Comment by cookpa** [comment]
Thanks, looks like this got missed while updating the scripts to use PATH rather than ANTSPATH - PR should fix it.

**Comment by CallowBrainProject** [comment]
Thank you, what should I do to fix it/should I wait for a patch of some
sort?

Thank you for letting me know,
Daniel

**Comment by cookpa** [comment]
I just merged the PR, you can update the script
