### ISSUE TITLE
ANTs compilation failure under Linux

### ISSUE THREAD

**Issue by servoz** [ANTsX/ANTs#1603]
I usually install the various versions of ANTs on linux operating systems using the [installANTs.sh](https://github.com/cookpa/antsInstallExample) file. Things generally go well.

However, the last installation I tried on a station with fedora 37 didn't work and I still haven't understood why. Perhaps the experts here will be able to detect what's wrong very easily?

[This is the stdout](https://github.com/ANTsX/ANTs/files/12701718/stdout.txt)
 
[build.log](https://github.com/ANTsX/ANTs/files/12701525/build.log)

[cmake.log](https://github.com/ANTsX/ANTs/files/12701535/cmake.log)

[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/12701539/CMakeCache.txt)

No build/CMakeFiles/CMakeError.log file
No build/CMakeFiles/CMakeOutput.log

**Comment by cookpa** [comment]
#1291 

The issue is in ITK, and was fixed (#2618) but ANTs 2.3.4 does not have that fix. The most recent ANTs should work.

If you need v2.3.4, you can try to build with an older compiler.

**Comment by servoz** [comment]
Thank you very much for your prompt reply!
I think this ticket can be closed now.
Have a nice WE :-)
