### ISSUE TITLE
Bringing individual image to template space

### ISSUE THREAD

**Issue by NewAnts** [ANTsX/ANTs#1606]
Apologies for a naive question. 

I'm currently exploring the best method to align individual Magnetization Transfer (MT) images to a template space. We've already established an MT template using data from 65 subjects. As we aim to bring individual subject images to this template space for further analysis, I'm considering using linear registration due to its computational efficiency. Would this approach be sufficient, or would there be a significant advantage to utilizing the more computationally demanding non-linear registration? Thanks in advance!

**Comment by gdevenyi** [comment]
Linear registration will be insufficient to align the individual variability of subjects.
