### ISSUE TITLE
"antsRegistration not found" after no errors installation using SuperBuild

### ISSUE THREAD

**Issue by tuongvanpn9** [ANTsX/ANTs#1607]
**Describe the problem**

I installed ANTs using the SuperBuild (the downloadable script) to build and install ANTs without any errors. But when I checked "which antsRegistration" in Terminal it said "antsRegistration not found". Checked for version only command "/Users/mypath/ANTs/install/bin/antsRegistration --version" works (ANTs Version: 2.5.0.post11-gdee5e1a). Wouldn't work if I used "antsRegistration --version" (error zsh: command not found: antsRegistration).

**To Reproduce**

The SuperBuild script is stored in Documents. I navigated to the stored folder in Terminal and bash in installANTs.sh. The last message after it ran:
"Installation complete, running /Users/mypath/Documents/ANTs/install/bin/antsRegistration
ANTs Version: 2.5.0.post11-gdee5e1a
Compiled: Sep 28 2023 12:31:46

Binaries and scripts are located in 
  /Users/mypath/Documents/ANTs/install

Please see post installation instructions at 
  https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS"

**System information (please complete the following information)**

I used Mac OS Ventura 13.4.1 if that helps.

**Comment by gdevenyi** [comment]
You need to manage your PATH yourself. This is not the responsibility of the ANTs installer.

**Comment by cookpa** [comment]
I should clarify that install message.

You need to add the ANTs tools to your PATH:

```
export PATH=/Users/mypath/ANTs/install/bin:$PATH
```

You might also want to control threading by setting `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS`
