### ISSUE TITLE
Can't write transform file for large image

### ISSUE THREAD

**Issue by joshua-gould** [ANTsX/ANTs#1608]
`antsRegistration --verbose 0 --dimensionality 2 --float 0 --collapse-output-transforms 1 --output [ myOutput_ ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] --initial-moving-transform [ image-a.mha,image-b.mha,1 ] --transform Rigid[ 0.1 ] --metric MI[ image-a.mha,image-b.mha,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform Affine[ 0.1 ] --metric MI[ image-a.mha,image-b.mha,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform SyN[ 0.1,3,0 ] --metric CC[ image-a.mha,image-b.mha,1,4 ] --convergence [ 100x100x70x50x20,1e-6,10 ] --shrink-factors 10x6x4x2x1 --smoothing-sigmas 5x3x2x1x0vox`

Can't write transform file myOutput_1Warp.nii.gz
Exception Object caught: 

itk::ExceptionObject (0x3b19e40)
Location: "unknown" 
File: /opt/build/ITKv5/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Line: 1481
Description: ITK ERROR: NiftiImageIO(0x3af4190): Dimension(0) = 37315 is greater than maximum possible dimension 32767

How do I specify a different output format? Thanks.

**Comment by cookpa** [comment]
There is an option `--minc` that will use MINC files instead of NIFTI

**Comment by joshua-gould** [comment]
Adding `--minc` generates the following error:

Can't write transform file output_0_GenericAffine.xfm
Exception Object caught: 

itk::ExceptionObject (0x4d8cdb0)
Location: "unknown" 
File: /opt/build/ITKv5/Modules/IO/TransformMINC/src/itkMINCTransformIO.cxx
Line: 285
Description: ITK ERROR: MINCTransformIOTemplate(0x4db8870): Transform type:AffineTransform_double_2_2is Unsupported


Can't write transform file output_1_NL.xfm
Exception Object caught: 

itk::ExceptionObject (0x4d8cdb0)
Location: "unknown" 
File: /opt/build/ITKv5/Modules/IO/TransformMINC/src/itkMINCTransformIO.cxx
Line: 285
Description: ITK ERROR: MINCTransformIOTemplate(0x4d9b750): Transform type:DisplacementFieldTransform_double_2_2is Unsupported


Can't write transform file output_1_inverse_NL.xfm
Exception Object caught: 

itk::ExceptionObject (0x4d8cdb0)
Location: "unknown" 
File: /opt/build/ITKv5/Modules/IO/TransformMINC/src/itkMINCTransformIO.cxx
Line: 285
Description: ITK ERROR: MINCTransformIOTemplate(0x4dcafd0): Transform type:DisplacementFieldTransform_double_2_2is Unsupported

**Comment by gdevenyi** [comment]
Try removing --collapse-output-transforms, but something looks not quite right here.

What version are you using? Are you using the official binaries?

**Comment by gdevenyi** [comment]
You may want to try --write-composite-transform, which without --minc will write an ITK hdf5 transform.

**Comment by joshua-gould** [comment]
I will try --write-composite-transform. I'm using version 2.5.0, installed from conda-forge

**Comment by joshua-gould** [comment]
Adding --write-composite-transform solved the issue, thanks

**Comment by cookpa** [comment]
Great, glad that worked

@gdevenyi is it your expectation that --minc should write warps as well as affine transforms? If so I will make a new issue

**Comment by cookpa** [comment]
Got it, thanks
