### ISSUE TITLE
AntsRegistration

### ISSUE THREAD

**Issue by tarasepehri** [ANTsX/ANTs#1611]
Hello experts,

I am a newbie and I am struggling in registering lamb brains to a template. The images belong to neonate lambs and the template belong to sheep brain. I used AntsRegistrationSynQuick, followed by AntsRegistrationSyn. I tried SynQuick alone, it's close but not great, both registration one after the other is not good too. I tried moving template, as well as moving the image. none gives a good result. Could anyone please kindly help me solving this puzzle? I attached the template and a T1. T1 is denoised, bias corrected and in the same orientation as the template.
[TSBTA_Mixed_Brain_new1-template.nii.gz](https://github.com/ANTsX/ANTs/files/12926618/TSBTA_Mixed_Brain_new1-template.nii.gz)
[T1-28NL.nii.gz](https://github.com/ANTsX/ANTs/files/12926651/T1-28NL.nii.gz)

**Comment by ntustison** [comment]
Thanks for posting the images.  

I don't know what you expect here but even just looking at the images, there doesn't appear to be an obvious dense correspondence.  Is the template constructed from the same modality as the single subject?

**Comment by tarasepehri** [comment]
Thanks for your response. The template and the lamb brain are both MRI and T1-W. However, The T1-28NL belongs to neonate lamb. So it doesn't have as clear WM, GM structures. But in coregistration, even the ventricles don't align. They both have clear ventricles structure. I tried antsRegistration with T2 images as well which has better correspondence. But it didn't work.
[T2toT1-28NL-masked.nii.gz](https://github.com/ANTsX/ANTs/files/12965381/T2toT1-28NL-masked.nii.gz)

**Comment by ntustison** [comment]
>  But in coregistration, even the ventricles don't align. They both have clear ventricles structure

This might be true but other correspondence ambiguities might contribute to an overall poor registration.

In addition to the images, please provide the command call so that we can reproduce your results on our end.

**Comment by tarasepehri** [comment]
I appreciate your help.
I use the default command. 
antsRegistrationSynQuick.sh -d 3 -f T2toT1-28NL-masked.nii.gz -m TSBTA_Mixed_Brain_new1-template.nii.gz -o templatetoT2-SynQ -n 4
then
antsRegistrationSyn.sh -d 3 -f T2toT1-28NL-masked.nii.gz -m templatetoT2-SynQWarped.nii.gz -o templatetoT2-SynQtoT2 -n 4
Tried those for both T1 and T2 images. 
I understand that there would be poor registration in most regions. If I can get a good registration for wm region around ventricles like Hippocampus, Thalamus, Cerebellum, Corpus Callosum, Internal Capsu I'll be happy.

Attached is the labels.
[TSBTA_Brain_Altas.nii.gz](https://github.com/ANTsX/ANTs/files/12968520/TSBTA_Brain_Altas.nii.gz)


Thanks so much.

**Comment by ntustison** [comment]
Yeah, with these data, it might be too much to ask to get good alignment for all those structures based on intensity alone.  You might actually have to provide subject labelings for the structures.

**Comment by tarasepehri** [comment]
Could you please let me know how can I do that? How can I improve the
coregistration?

**Comment by cookpa** [comment]
If `antsRegistrationSynQuick.sh` appears to be working reasonably, it might be because it uses the Mattes metric. In general we don't recommend this for SyN intra-modality, but because you have quite different contrasts, it might be better. 

Both of the scripts will print a registration command, which you can edit. The quick script uses Mattes but doesn't do many iterations at high resolution. You can try editing it to further refine the output.
