### ISSUE TITLE
Ants post-installation (PATH) on Mac does not work: antsRegistration not found

### ISSUE THREAD

**Issue by leahelene** [ANTsX/ANTs#1614]
Hi, the Ants post-installation on Mac does not work. I ran the command: 

> export PATH=/Users/name/ANTs/bin:$PATH

The following error occurs:

> antsRegistration not found

Do you have any tips how to solve that problem?

Best,
Lea

**Comment by gdevenyi** [comment]
Please provide the full set of commands you used to install ANTS as well as the outputs/logs associated with them.

**Comment by leahelene** [comment]
Hi, I followed the advice on github.

First step: git clone https://github.com/ANTsX/ANTs.git
Build step: make 2>&1 | tee build.log
Running cmake:
mkdir build install
cd build
ccmake ../ANTs

An error occured, because I forgot to set the install prefix:

CMake Error at Examples/cmake_install.cmake:41 (file):
file cannot create directory: /new/install/dir/lib.  Maybe need administrative privileges.
Call Stack (most recent call first):
cmake_install.cmake:42 (include)
make: *** [install] Error 1

Corrected the mistake by entering: make install DESTDIR=/Users/ls/ANTs

Last output/log associated with this command: 
[100%] Built target ANTSFetchData
Install the project...
(a lot of text until:)
-- Installing: /Users/ls/ANTs/new/install/dir/bin/waitForXGridJobs.pl
-- Installing: /Users/ls/ANTs/new/install/dir/bin/waitForSlurmJobs.pl

But if I enter: export PATH=/Users/ls/ANTs/bin:$PATH
And then check this worked correctly: which antsRegistration
The error occurs: antsRegistration not found

Already tried to restart terminal and made sure the path is correct, but still it does not work. 
Do you have any advice on how to resolve the problem?

Best,
Lea

**Comment by leahelene** [comment]
Thanks a lot, it works now! :)
