### ISSUE TITLE
Is it possible to continue to aMTC2.sh  after registrations are complete

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTs#1617]
I am running a very long atlas building process through pexec on a local system. At some point towards the end, the system crashed and a few jobs left incomplete. After the reboot, I ran the individual jobs through the command line, and I think I got the warps, and other things to continue the remaining steps of atlas building.

Unfortunately, I am not entirely sure how I can do that. Any pointers would be much appreciated.

**Comment by cookpa** [comment]
The script isn't really set up to resume mid-iteration.

If you have all the warped images from the latest iteration, you can average them to make a new template. The tricky part is the shape update step, but if you're close to convergence, that update is typically small. So you could create an average with (AverageImages), apply your choice of sharpening to the average with ImageMath, and continue from there (run the template script again with `-z average.nii.gz -i 1`)

Alternatively you can always turn back to a particular iteration by taking the last updated template from the `intermediateTemplates/` directory and using that with `-z`, to restart from that point.

**Comment by gdevenyi** [comment]
You may be interested in https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction which includes file-based resume under a similar template construction process.

**Comment by muratmaga** [comment]
> The script isn't really set up to resume mid-iteration.
> 
> If you have all the warped images from the latest iteration, you can average them to make a new template. The tricky part is the shape update step, but if you're close to convergence, that update is typically small. So you could create an average with (AverageImages), apply your choice of sharpening to the average with ImageMath, and continue from there (run the template script again with `-z average.nii.gz -i 1`)
> 
> Alternatively you can always turn back to a particular iteration by taking the last updated template from the `intermediateTemplates/` directory and using that with `-z`, to restart from that point.

Yes, I ended up doing an averageImage. Thank you.

**Comment by muratmaga** [comment]
> You may be interested in https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction which includes file-based resume under a similar template construction process.

That looks promising. II will check it out. I wonder if it would be simlpe enough to convert the remaining average and sharpening steps as an extra job. that can easily facilitate continuation of the tasks, provided the prior steps were completed. But anyways. thanks for the pointers.
