### ISSUE TITLE
Question about initial-transform in antsRegstrationSyN.sh

### ISSUE THREAD

**Issue by JackyWang22** [ANTsX/ANTs#1618]
Dear Someone may concern,

I am registering two OCT images. I have problem with the initial-transform for antsRegstrationSyN.sh
In my case I have computed the initial Affine provided below "intialAffine.mat" offline, I have trouble getting not identical result if I get the intermediate result and then run the script. I have tried to play around the underlying terminal call it called. It will be great if you can  guide me why I can't separate the intermediate product out.
I get different result of:
1. `antsRegistrationSyN.sh -d 2 -f target.nii -m source.nii -y 1 -n 16 -o reg -i initialAffine.mat` --> This give me awesome result
2. `antsApplyTransform -d 2 -i source.nii -r target.nii -t intialAffine.mat -o affine_source.nii`
    then -> `antsRegistrationSyN.sh -d 2 -f target.nii -m affine_source.nii -y 1 -n 16 -o affine-reg` --> This give me not desirable result.
3. I have also tried:
    `antsRegistration --verbose 1 --random-seed 1 --dimensionality 2 --float 0 --collapse-output-transforms 1 --output [ affine-reg,affine-regWarped.nii.gz,affine-regInverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] --transform SyN[ 0.1,3,0 ] --metric CC[ target.nii,affine_source.nii,1,4 ] --convergence [ 100x100x70x50x20,1e-6,10 ] --shrink-factors 10x6x4x2x1 --smoothing-sigmas 5x3x2x1x0vox`
   --> not working
4. I have also tried:
   `antsRegistration --verbose 1 --random-seed 1 --dimensionality 2 --float 0 --collapse-output-transforms 1 --output [ affine-reg,affine-regWarped.nii.gz,affine-regInverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] --initial-moving-transform [ target.nii,affine_source.nii,1 ] --transform Rigid[ 0.1 ] --metric GC[ target.nii,affine_source.nii,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform Affine[ 0.1 ] --metric GC[ target.nii,affine_source.nii,1,32,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform SyN[ 0.1,3,0 ] --metric CC[ target.nii,affine_source.nii,1,4 ] --convergence [ 100x100x70x50x20,1e-6,10 ] --shrink-factors 10x6x4x2x1 --smoothing-sigmas 5x3x2x1x0vox`
  --> not working.

Any guidance will be appreciated. In the folder, it contains the source.nii, target.nii and initialAffine.mat.

Best,
ANTs Fan
[question.zip](https://github.com/ANTsX/ANTs/files/13192464/question.zip)

**Comment by cookpa** [comment]
I can think of two things:

1. If you don't use `-i initialAffine.mat`, the script will do an initial center of mass alignment, which can undo the alignment you did by applying the initial transform.

2. After applying the initial transform, your data is interpolated, so `affine_source.nii` is not the same as `source.nii`. This can also impact the results.

**Comment by cookpa** [comment]
Also, after resampling the source into the target space, there's a lot of empty voxels - this is probably the main issue and the reason your `antsRegistration` calls failed even after removing the initialization / affine steps

<img width="502" alt="image" src="https://github.com/ANTsX/ANTs/assets/611507/e2204ead-ef1b-4cf2-b66b-1be61c8ff488">

**Comment by JackyWang22** [comment]
Thanks so much for your timely response. I am assuming by passing the `intial-transform` to the script, it did the same step as I did to separate it into intermediate step. I am not sure how the underlying of ANTs handling the `intial-transform` parameter. 
I am wondering if you have any suggestion how can I solve this issue? As I would like to test the result if I manipulate the intermediate image.
Thanks

**Comment by JackyWang22** [comment]
I just tested by providing the masks to the source and target images. It still didn't work well.
[mask.zip](https://github.com/ANTsX/ANTs/files/13192792/mask.zip)

**Comment by cookpa** [comment]
I made a mask that was only foreground voxels in affine_source with `ThresholdImage`, then ran this:

antsRegistration --verbose 1 --random-seed 1 --dimensionality 2 --float 0 --collapse-output-transforms 1 --output [ reg,regWarped.nii.gz,regInverseWarped.nii.gz ] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [ 0.005,0.995 ] --transform Rigid[ 0.1 ] --metric GC[ ${fixed},${moving},1,1,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform Affine[ 0.1 ] --metric GC[ ${fixed},${moving},1,1,Regular,0.25 ] --convergence [ 1000x500x250x100,1e-6,10 ] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform SyN[ 0.1,3,0 ] --metric CC[ ${fixed},${moving},1,4 ] --convergence [ 100x100x70x50x20,1e-6,10 ] --shrink-factors 10x6x4x2x1 --smoothing-sigmas 5x3x2x1x0vox --masks [ none, affine_foreground_mask.nii.gz ]

It seemed to work OK - still doing the rigid and affine registration, but skipping the COM initialization

**Comment by JackyWang22** [comment]
Thanks again your help!
Can you provide me the `ThresholdImage` command you are running. I have tested to keep foreground 1 and `ants.threshold_image(image)` as the mask and got the comparison as below. It did better than w/o passing the mask. But still not as good as the `initial-transform`
Thanks!!

![Screenshot from 2023-10-27 15-44-20](https://github.com/ANTsX/ANTs/assets/24632299/25179cbc-166e-4ce0-a4ff-b8302d983096)

**Comment by cookpa** [comment]
`ThresholdImage 3 affine_source.nii affine_foreground_mask.nii.gz 0.001 Inf`

I agree, in the fine details, the registration performs better when given the original data, which is why we always recommend doing registration that way.
