### ISSUE TITLE
Failed to run antsRegistrationSyN command using macbook m1 Monterey

### ISSUE THREAD

**Issue by citystrawman** [ANTsX/ANTs#1620]
Hi, I am trying to run ANTs antsRegistrationSyN command as my first trial. I am using a macbook 2021 M1 laptop whose OS is Monterey(version 12.5.1).
I found a macos release named [ants-2.5.0-macos-12-X64-clang.zip](https://github.com/ANTsX/ANTs/releases/download/v2.5.0/ants-2.5.0-macos-12-X64-clang.zip)  from https://github.com/ANTsX/ANTs/releases which I think is suitable for my computer.
Thus I downloaded it and start a terminal in bin folder(which has a antsRegistrationSyN.sh file),  and then I put my TestFiles folder, and tried to run `./antsRegistrationSyN -d 3 -f ../TestFiles/mprage.nii -m ../TestFiles/flash.nii -o output `. But I got a error message saying "`zsh: no such file or directory: ./antsRegistrationSyN`" 

I searched this problem in Issues but could find no similar answer and all the related topics are using source code to build binaries. I am wondering if the release work correctly or  Should I build all binaries from the source code?

**Comment by cookpa** [comment]
The script is called `antsRegistrationSyN.sh`.

I think the X86 build will work, but might be slow as the system will need to emulate an X86 system.

If you can build from source, it might perform much better

**Comment by citystrawman** [comment]
> The script is called `antsRegistrationSyN.sh`.
> 
> I think the X86 build will work, but might be slow as the system will need to emulate an X86 system.
> 
> If you can build from source, it might perform much better

thanks.

**Comment by cookpa** [comment]
Going to close this but will note that M1 chips are apparently still pretty good at running x86 code according to [these benchmarks](https://www.macrumors.com/2020/11/15/m1-chip-emulating-x86-benchmark/). The translation to real world performance might not be the same but I thought it was interesting.
