### ISSUE TITLE
Oasia template registration to MNI152 

### ISSUE THREAD

**Issue by zhaolei215** [ANTsX/ANTs#1623]
Do you have the fMRI corresponding to the Oasia template on this website?
The website is: https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436?file=313382
I really hope to receive your reply.  Thanks!

**Comment by ntustison** [comment]
Unfortunately, no.

**Comment by zhaolei215** [comment]
Ok, fine. Thanks for your reply.
