### ISSUE TITLE
running antsRegistrationSyn.sh on a remote server takes too long time

### ISSUE THREAD

**Issue by citystrawman** [ANTsX/ANTs#1629]
**Describe the problem**

Hi, I was trying to execute  antsRegistrationSyn.sh on a remote server(Ubuntu 18).  The same command running on a local macbook (intel cpu based) takes about 15 mins, but the remote server, which has intel Xeon Platinum Cpu, takes much longer time. 
The CPU configuration of the server is as follows:
<img width="517" alt="lQLPJwhl5NhZB-_NBADNBAqw0Nnhbn_uCt4FUI8GIdLvAA_1034_1024" src="https://github.com/ANTsX/ANTs/assets/9004748/14656c03-9238-4f0a-a64d-ed28b01ae272">
and I tried running `antsRegistrationSyn.sh -d 3 -f ./InputFiles/flash.nii -m ./InputFiles/mprage.nii -o ./OutputFiles/output  -n 16`
which means that I allocated 16 threads to this program.  But the total time spent is 30 minutes, as the following output shows:
 
![image](https://github.com/ANTsX/ANTs/assets/9004748/a721d512-1eaf-413c-b9ec-e7fed98b58d8)

I am wondersing how I can speed up the processing time? 

**To Reproduce**

**System information (please complete the following information)**

 - OS: Ubuntu 
 - OS version: 18.04
 - Type of system: Ali Cloud
 - CPU architecture Intel

**ANTs version information**
 - ANTs code version: [ANTs Version: 2.4.4.dev1-gd74bb06  Compiled: May  1 2023 15:46:02]
 - ANTs installation type: 

Compiled from source
Downloaded Github release binaries
Conda (Please show source with `conda list --show-channel-urls | grep ants`)
ANTsX docker image (https://hub.docker.com/repository/docker/antsx/ants/general)
Other (please specify)

**Additional information**

The test files flash.nii and mprage.nii are included in the attachment. Feel free to test it.
[TestFiles.zip](https://github.com/ANTsX/ANTs/files/13454920/TestFiles.zip)

**Comment by gdevenyi** [comment]
This isn't a bug, but rather a question about performance, which should be in the discussions.

You didn't specify how much RAM the machine has. Cache is not RAM.

**Comment by cookpa** [comment]
@gdevenyi it's not always clear what's an issue and what's a discussion topic. I can convert issues to discussions if needed.

@citystrawman as @gdevenyi says, the amount of system memory (as opposed to CPU cache is important. If a process is using virtual memory on disk, it will be much slower.

There are a lot of factors going in to computational performance. If you want to dig further I would start with simple examples, perhaps a 2D registration that can run on a single thread in a reasonable time

**Comment by citystrawman** [comment]
> This isn't a bug, but rather a question about performance, which should be in the discussions.
> 
> You didn't specify how much RAM the machine has. Cache is not RAM.

![image](https://github.com/ANTsX/ANTs/assets/9004748/55f14656-2d5a-4c3b-a9a1-190f44c830f3)
Hi, the memory of the server is 8G. Is it a reasonable RAM for ANTs?  Thank you.

**Comment by citystrawman** [comment]
> @gdevenyi it's not always clear what's an issue and what's a discussion topic. I can convert issues to discussions if needed.
> 
> @citystrawman as @gdevenyi says, the amount of system memory (as opposed to CPU cache is important. If a process is using virtual memory on disk, it will be much slower.
> 
> There are a lot of factors going in to computational performance. If you want to dig further I would start with simple examples, perhaps a 2D registration that can run on a single thread in a reasonable time

Hi cookpa, I would very appreciate if you could show me how to run a 2D registration in a reasonable time. I looked into the antsRegistration wiki but as a starter I only know a few arguments meaning.

**Comment by citystrawman** [comment]
> This isn't a bug, but rather a question about performance, which should be in the discussions.
> 
> You didn't specify how much RAM the machine has. Cache is not RAM.

![image](https://github.com/ANTsX/ANTs/assets/9004748/c90a29a8-6d2c-4654-8a8d-b9c06c94c423)
Here's the CPU and Memory Use when I execute antsRegistration.

**Comment by citystrawman** [comment]
I've increased CPU cores of the server and now it is faster. Thanks
