### ISSUE TITLE
I am not sure I understood the command explanation in ANTsDoc pdf

### ISSUE THREAD

**Issue by citystrawman** [ANTsX/ANTs#1631]
Hi, I am reading the [ANTsDoc pdf book](https://github.com/stnava/ANTsDoc) and on page 12, there's a command as follows:
```
  dim=2
  antsRegistration -d $dim -r [ r16slice.nii.gz , r64slice.nii.gz ,1] \
                             -m mattes[ r16slice.nii.gz , r64slice.nii.gz, 1 , 32, regular,0.1 ] \
                             -t affine[ 0.1 ] \
                             -c [500x500x50,1.e-8,20] \
                             -s 4x2x1vox \
                             -f 3x2x1 -l 1 \
                             -m cc[ r16slice.nii.gz , r64slice.nii.gz, 1 , 4 ] \
                             -t GaussianDisplacementField[ .5, 3, 0.5 ] \
                             -c [ 50x50x50,0,5 ] \
                             -s 1x0.5x0vox \
                              -f 4x2x1 -l 1 -u 1 -z 1 \
                             -o [${op},${op}_diff.nii.gz,${op}_inv.nii.gz]
```
the book explains the above command:
![image](https://github.com/ANTsX/ANTs/assets/9004748/35a65818-85ac-4f03-a1d6-ee2e5c6d5572)

and my questions are : 
1. the book said that CC metric has gradient step length 1.5, but in line ` -m cc[ r16slice.nii.gz , r64slice.nii.gz, 1 , 4 ] \` I could not find it. 
2. the book said that the 3 iterations are 30, 20 and 10, but I could not find it.
3. the book said that 0 is passed as the first parameter to GussianDisplacementField, but in line `-t GaussianDisplacementField[ .5, 3, 0.5 ] \` the first parameter is 0.5? 
4. The command seems to ran two rounds of transformation, first round is affine and second round is GaussianDisplacement. Do I understand it correct?

**Comment by cookpa** [comment]
It looks like there was a mistake when the document changed from using `ANTS` to `antsRegistration` in its examples. 

In the command as shown, step length is specified in the transform option (`-t`), and is 0.5. From the usage for `antsRegistration`


```
     GaussianDisplacementField[gradientStep,updateFieldVarianceInVoxelSpace,totalFieldVarianceInVoxelSpace]
```

The 0.5 is gradient step, 3 is the smoothing on the update field (ie, the similarity gradient) and 0.5 is the smoothing on the deformation. 

The iterations at the deformable stage are 50x50x50, with a zero convergence threshold (it will never converge unless the solution oscillates), and a convergence window of 5 iterations.

And yes, there are two stages of registration, the first with an affine transform, and the second with the GaussianDisplacementField transform. Technically, there's three stages as there is an initial transform with `-r`, which does a translation to align the image centers of mass. But in the output, all the Translation / Rigid / Affine stages (including the initial transform) are composed, so you'll get one `0GenericAffine.mat` file and one `1Warp.nii.gz` in the output.
