### ISSUE TITLE
missing libITKIOTransformMINC-5.3.so.1

### ISSUE THREAD

**Issue by portokalh** [ANTsX/ANTs#1632]
Greetings!

I am trying to install ants on ubuntu 22.04 using this guide
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

using sudo for most every cmd below, i saw a warning on itk git building bc of permissions

workingDir=${PWD}
git clone https://github.com/ANTsX/ANTs.git
mkdir build install
cd build
cmake \
    -DCMAKE_INSTALL_PREFIX=${workingDir}/install \
    ../ANTs 2>&1 | tee cmake.log
make -j 4 2>&1 | tee build.log
cd ANTS-build
make install 2>&1 | tee install.log

The installation appears to succeed but trying to run antsRegistration throws the same error as the conda install

antsRegistration: error while loading shared libraries: libITKIOTransformMINC-5.3.so.1: cannot open shared object file: No such file or directory

Any thoughts on how to fix this missing lib issue?

Many thanks,

Alex

**When did the error occur?**

[ ] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: [e.g. Mac OS]
 - OS version: [e.g. 10.15.1]
 - Type of system: [Desktop, laptop, HPC cluster, cloud instance,
   other]

**ANTs version**

**Build configuration and logs**

**Additional context**

**Comment by portokalh** [comment]
you are correct!!!! thanks so much!
i am running now!
all the best,
Alex

**Comment by portokalh** [comment]
do i have to set the env variable like that, or will it not stick, also is 32 a good number (or my number of cores)? Perhaps if left unspecified ants will use the max no of threads?

(base) alex@kythira:$ $ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=32

**Comment by cookpa** [comment]
For the most recent ANTs, you just have to include the binaries on the PATH.

For multi-threading, optimal performance depends on what you're doing, but as a general rule 8 cores is about the maximum for registration. You can test using more or less and decide the best setting.

If ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS is unset, ANTs will use all available cores.
