### ISSUE TITLE
flags in ANTS to run DenseRigid registration 

### ISSUE THREAD

**Issue by enrit** [ANTsX/ANTs#1633]
I am using the 'ANTS' command to register two PET images. In the python implementation of ants, the program ants.registration can use type_of_transform='DenseRigid' What flags do I use in the original ANTS program to run Dense Rigid transform ?

Can someone plz suggest ?

Thanks

Wri

**Comment by ntustison** [comment]
Use ``verbose=1`` and the equivalent command line call will be printed immediately to the screen.

```
>>> ants.registration(t1, t1, type_of_transform='DenseRigid', verbose=1)
antsRegistration -d 3 -r [0x6000021aa4b0,0x6000021aa4a0,1] -m mattes[0x6000021aa4b0,0x6000021aa4a0,1,32,regular,1.0] -t Rigid[0.25] -c 2100x1200x1200x10 -s 3x2x1x0 -f 6x4x2x1 -u 1 -z 1 -o [/var/folders/5h/62f7bql14zvgx34nqwd7xvnc0000gn/T/tmpnuxb6suw,0x6000021aa9a0,0x600002188aa0] -x [NA,NA] --float 1 --write-composite-transform 0 -v 1
```
