### ISSUE TITLE
Inquiry Regarding Suboptimal Results in Macaque T1 Image Segmentation Using antsbrainextraction.sh

### ISSUE THREAD

**Issue by AnastasiaWen** [ANTsX/ANTs#1638]
**Describe the problem**

Hello,

I hope this message finds you well. I've been using antsbrainextraction.sh for the segmentation of Macaque T1 images. However, the results have not been satisfactory as I can only see a partial representation of the brain, despite using individual images registered to the NMT template and masks. Could you please provide guidance on where I might have gone wrong in my process? Additionally, are there any recommended adjustments or steps I can take to improve the quality of my results?

Thank you for your assistance.

Best regards,
Anne wen

**To Reproduce**

I used this command line:
$ANTSPATH/antsBrainExtraction.sh -d 3 -a ${name}_N4.nii.gz -e ${name}_NMT_prior.nii.gz -m ${name}_NMT_brainmask_prob_prior.nii.gz -o ${name}_ -f ${name}_NMT_brainmask_prior.nii.gz

and the results like this:
<img width="769" alt="image" src="https://github.com/ANTsX/ANTs/assets/108002859/703268fb-8f23-4db8-9226-d0cbb084fad6">

**System information (please complete the following information)**

 - OS: [e.g. Mac OS]
 - OS version: [e.g. 11.7.0]
 - Type of system: [ laptop]
 - CPU architecture (x86)

**ANTs version information**
 - ANTs code version: [output of antsRegistration --version]
 - ANTs installation type: 

Compiled from source

**Additional information**

**Comment by ntustison** [comment]
Can you upload the full input dataset so that we can reproduce the issue on our end?

**Comment by AnastasiaWen** [comment]
> Can you upload the full input dataset so that we can reproduce the issue on our end?

Thanks a bunch for your help. Unfortunately, the file size was too large to upload directly to GitHub，so I've uploaded the files to Google Drive. You can download them using the following link:
[https://drive.google.com/drive/folders/1yf8d0uEasbpz0alxk70H-SM4pMIMQmqa?usp=sharing](url)

Here's the command I used (note:name=vic):
$ANTSPATH/antsBrainExtraction.sh -d 3 -a ${name}_N4.nii.gz -e ${name}_NMT_prior.nii.gz -m ${name}_NMT_brainmask_prob_prior.nii.gz -o ${name}_ -f ${name}_NMT_brainmask_prior.nii.gz

Additionally, my goal is to perform segmentation and utilize the results to generate surfaces in FreeSurfer, following the workflow outlined below:
[https://prime-re.github.io/structural/surfaces_and_flatmaps_notebook/Surfaces_and_Flatmaps.html](url)

Thank you for your time and assistance.

**Comment by cookpa** [comment]
I expect it's because of antsAI downsampling the images too much. I can work on a fix, but in the interim, you could try getting an initial transform with

```
antsRegistrationSyNQuick.sh -f vic_ants/vic_NMT_prior.nii.gz -m vic_ants/vic_N4.nii.gz -t r -o vicToNMT_Affine
```

and then adding

```
-r vicToNMT_Affine0GenericAffine.mat
```

to the `antsBrainExtraction.sh` command.

**Comment by cookpa** [comment]
Initial affine worked for me, BTW

<img width="782" alt="image" src="https://github.com/ANTsX/ANTs/assets/611507/5b2ae39e-f797-48a6-a10c-f586d79c69d4">

**Comment by AnastasiaWen** [comment]
Thanks for your effective help! It works well :D

**Comment by YCHuang0610** [comment]
> I expect it's because of antsAI downsampling the images too much. I can work on a fix, but in the interim, you could try getting an initial transform with
> 
> ```
> antsRegistrationSyNQuick.sh -f vic_ants/vic_NMT_prior.nii.gz -m vic_ants/vic_N4.nii.gz -t r -o vicToNMT_Affine
> ```
> 
> and then adding
> 
> ```
> -r vicToNMT_Affine0GenericAffine.mat
> ```
> 
> to the `antsBrainExtraction.sh` command.

Dear cookpa
I have met the same problem when using _antsBrainExtraction.sh_ and _antsCorticalThickness.sh_ to deal with monkey brains. I tried your solution and It works when using antsBrainExtraction.sh. But I didn't find the same argument (_antsBrainExtraction.sh -r_ to do the Initial moving transform) in _antsCorticalThickness.sh_. Since _antsCorticalThickness.sh_ calls _antsBrainExtraction.sh_  , I am wondering whether the same argument to do the Initial moving transform should be added to _antsCorticalThickness.sh pipeline as well?

**Comment by cookpa** [comment]
The `-t r` is just to do a fast initial transform. It's only a starting point for the rest of the registration, so it's OK if it's not a very good alignment. You can switch to `-t a` if you like.

Regarding `antsCorticalThickness.sh`, it doesn't support an initial transform but it will find an existing brain mask. So if you run it with `-o myOutput_` and there exists `myOutput_BrainExtractionMask.nii.gz`, it will not re-run the brain extraction and will carry on from the next step.
