### ISSUE TITLE
Warnings possibly indicating problems

### ISSUE THREAD

**Issue by dzenanz** [ANTsX/ANTs#1652]
This concatenation of strings is discarded:
https://github.com/ANTsX/ANTs/blob/2d3cefaec09b1652fcc88cdb802b622d32a4cbb5/Examples/Atropos.cxx#L1335-L1344
Maybe a semicolon on the previous line (1334) should be replaced by a plus sign?

Current Visual Studio (17.8.4) reports the following warning:
`C:\Dev\ANTs\Examples\sccan.cxx(2593,8): warning C4858: discarding return value: The 'remove' and 'remove_if' algorithms return the iterator past the last element that should be kept. You need to call container.erase(result, container.end()) afterwards. In C++20, 'std::erase' and 'std::erase_if' are simpler replacements for these two steps.`
That code should be checked, and if it is OK that line should be replaced by:
```cpp
std::ignore = std::remove(args.begin(), args.end(), std::string(""));
```

**Comment by ntustison** [comment]
Yes, that's correct (i.e., the semi-colon should be replaced by a plus sign).

**Comment by dzenanz** [comment]
@cookpa There is just one warning when compiling ANTs normally: `C:\Dev\ANTs\Examples\sccan.cxx(2593,8): warning C4858: discarding return value`. I am not familiar with this code to be able to tell whether we should just ignore the warning.

**Comment by cookpa** [comment]
This looks like it re-orders the args matrix to put non-empty strings first. It discards the returned iterator. I'm not sure what its purpose is, but possibly something to do with ANTsR or ANTsPy. I think the warning is safe to ignore

https://github.com/ANTsX/ANTs/blob/62550fca38c731c20560528f19c65181e211c7d4/Examples/sccan.cxx#L2593
