### ISSUE TITLE
Warnings are raised when ANTs is used via CMake FetchContent

### ISSUE THREAD

**Issue by dzenanz** [ANTsX/ANTs#1655]
I am trying to have an ITK remote module have ANTs as an external dependency. I use:
```cmake
include(FetchContent)
FetchContent_Declare(
  ants_inner
  GIT_REPOSITORY https://github.com/ANTsX/ANTs
  GIT_TAG        62550fca38c731c20560528f19c65181e211c7d4  # 2024-01-12
)
```
During configure step, I get the following:
```log
CMake Warning at VS22/_deps/ants_inner-src/CMake/ProjectSourceVersion.cmake:60 (message):
  git tag: "-128-NOTFOUND" does not match expected version format!
Call Stack (most recent call first):
  VS22/_deps/ants_inner-src/Version.cmake:10 (include)
  VS22/_deps/ants_inner-src/ANTS.cmake:19 (include)
  VS22/_deps/ants_inner-src/CMakeLists.txt:75 (include)
```

**When did the error occur?**
 - [x] CMake configuration (cmake / ccmake)
 - [ ] Compilation (make)
 - [ ] Installation (make install)

**Build environment**
 - OS: Windows 11
 - OS version: 22H2, build 22621.3007
 - Type of system: Desktop

As used here:
https://github.com/dzenanz/ANTsWasm/commit/671920eaeb6a4b76f20a626fd8bd9d642f52dd54

Complete configure log of ANTsWasm:
```log
ITK is setting ANTsWasm's MSVC_RUNTIME_LIBRARY to dynamic
Not using CCache
CMake Warning at VS22/_deps/ants_inner-src/CMake/ProjectSourceVersion.cmake:56 (message):
  git tag: "-128-NOTFOUND" does not match expected version format!
Call Stack (most recent call first):
  VS22/_deps/ants_inner-src/Version.cmake:10 (include)
  VS22/_deps/ants_inner-src/ANTS.cmake:19 (include)
  VS22/_deps/ants_inner-src/CMakeLists.txt:75 (include)


Building ANTS version "2.5.0.dev1-g671920e"
ITK is setting ANTS's MSVC_RUNTIME_LIBRARY to dynamic
antsAffineInitializer 
antsJointFusion 
DenoiseImage 
SurfaceBasedSmoothing 
ThresholdImage 
ResampleImage 
sccan 
N4BiasFieldCorrection 
N3BiasFieldCorrection 
KellyKapowski 
antsRegistration 
antsMotionCorrStats 
antsMotionCorr 
antsApplyTransforms 
LabelGeometryMeasures 
LabelClustersUniquely 
Atropos 
antsApplyTransformsToPoints 
ITK is setting WrapITK's MSVC_RUNTIME_LIBRARY to dynamic
ANTsWasm: Creating module.
ANTsWasm: Creating itkANTSRegistration submodule.
Configuring done
Generating done
```

**Comment by dzenanz** [comment]
The line where the problem occurs is this one: `git_describe(_GIT_TAG "--match=v*")`.

**Comment by cookpa** [comment]
Looking at this now @dzenanz - it looks like it can't find a tag in the call to git_describe. This can happen if CMake is doing a shallow clone. The only consequence is that it won't be able to set all the version information in `ANTsVersionConfig.h`. However, it will still set basic information hard-coded into `Version.cmake`. 

I think I can refactor to avoid this, might take me a few days to get to it.

**Comment by dzenanz** [comment]
I don't think this is that important right now. I think I will not configure ANTs after fetching it (today's current plan calls for using headers only). If plans change later, I will let you know.
