### ISSUE TITLE
Spatial resolution and  antsApplyTransforms

### ISSUE THREAD

**Issue by ndolf** [ANTsX/ANTs#1658]
We are using antsApplyTransforms to reverse ROI templates from MNI to native subject space. Or input is a MNI mask that can have any spatial resolution (from FSL or some atlas) and the reference image is the anatomical image of that subject in subject space. The transform is according the H5 transformation matrix that is created during preprocessing in fmriprep. The spatial resolution of the chosen MNI standard space in fMRIprep was set to 2x2x2, so the H5 file is based on that. 

Here is the code
 os.system("antsApplyTransforms --default-value 0 --float --interpolation NearestNeighbor -d 3 -e 0 \
        --input %s/%s.nii \
        --reference-image %s/ANAT_T1w_images/%s/long_T1.nii \
        --output  %s/%s.nii \
        --transform %s/y_MNI_to_T1w.h5 -v" \
        %(MNImask_dir,labels[label],path,sub,dir,new_labels[label],dir)

While all ROI templates are in MNI space, not all ROI templates have the 2x2x2 resolution (Some have 1x1x1). Is it important that the  spatial resolution of the to be transformed MNI ROI template and the MNI space on which the transformation matrix (the H5 file) is based match?

Should we always first resample the ROI template to a 2x2x2 resolution before applying the transform? 

Thank you! 

Nina

**Describe the problem**

48588372

**To Reproduce**

**System information (please complete the following information)**

 - OS: [e.g. Mac OS]
 - OS version: [e.g. 10.15.1]
 - Type of system: [Desktop, laptop, HPC cluster, cloud instance,
   other]
 - CPU architecture (x86, ARM, other, unknown)

**ANTs version information**
 - ANTs code version: [output of antsRegistration --version]
 - ANTs installation type: 

Compiled from source
Downloaded Github release binaries
Conda (Please show source with `conda list --show-channel-urls | grep ants`)
ANTsX docker image (https://hub.docker.com/repository/docker/antsx/ants/general)
Other (please specify)

**Additional information**

**Comment by cookpa** [comment]
As long as the input images are in the same physical space as the MNI template used in the registration, there's no need to distinguish between 1mm and 2mm resolution.

If you are resampling binary or other label images, you probably want to add `-n GenericLabel` to your command line

**Comment by ndolf** [comment]
Thank you Philip! Wonderful! (sorry for the late reply)
