### ISSUE TITLE
ANTs Version: 2.5.1.post1-g128c124 still requires ANTSPATH

### ISSUE THREAD

**Issue by postnubilaphoebus** [ANTsX/ANTs#1667]
On https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS, it mentions that $ANTSPATH has been deprecated since version 2.5.0. Problem: srun returned "no such file or directory" for antsRegistration when script was run using `srun $PATH/antsRegistration`. echo $PATH did return /u/user_name/ants/install/bin/.

**Comment by gdevenyi** [comment]
This is a misconfiguration of your system, not a problem with the removal of ANTSPATH

**Comment by cookpa** [comment]
It's unusual that $PATH is a single directory. Normally, PATH contains every directory that may be used to execute programs, and you add to PATH for ANTs:

```
export PATH=/opt/ants/bin:$PATH
```

This sets PATH to `/opt/ants/bin:` and whatever PATH was beforehand.

In your case, you would do export `PATH=/u/user_name/ants/install/bin:$PATH`

**Comment by cookpa** [comment]
Also, ANTSPATH was only ever required by scripts. Compiled executables like `antsRegistration` or `ImageMath` should run once added to the PATH. If this doesn't work, it indicates a problem with the PATH variable.

I'm not that familiar with `srun` but I assume it runs with whatever $PATH is at run time. If not, there may be an option to set PATH specifically for the command - but again, you'll want to use all the PATH, `PATH=/u/user_name/ants/install/bin:$PATH`, not just the ANTs bin directory.

**Comment by postnubilaphoebus** [comment]
@cookpa 
I did indeed run a bash script using SLURM instructions on an HPC, and I also specified the PATH as `PATH=/u/user_name/ants/install/bin:$PATH`. My PATH variable also returned other paths, apologies for the confusion. I will try to reproduce the error and be more specific. Fortunately, the bash script is running with ANTSPATH.

**Comment by dorianps** [comment]
srun $PATH/antsRegistration: maybe you need to remove $PATH from that. You
are prepending the entire PATH list to the call for antsRegistration?

Also, you can try running "which antsRegistration" to see where does the
system think antsRegistration should be.
