### ISSUE TITLE
Are Jacobean values log transformed by default in CreateJacobianDeterminantImage command?

### ISSUE THREAD

**Issue by glezin97** [ANTsX/ANTs#1678]
Hi, I was wondering if the outputs of CreateJacobianDeterminantImage command, which comes from ANTs package, are log transformed by default or should such operations be manually applied by the user in subsequent steps of analysis (e.g., for voxel-wise analysis of DBM results)? How can I know for sure; maybe there is a direct mention in documentation? Thanks.

**Comment by ntustison** [comment]
```
 % CreateJacobianDeterminantImage 
Usage: CreateJacobianDeterminantImage imageDimension deformationField outputImage [doLogJacobian=0] [useGeometric=0] [deformationGradient=0]
```

**Comment by glezin97** [comment]
Thank you @ntustison . Appreciate it greatly!
