### ISSUE TITLE
Port antsRegistrationSyN.sh to Windows

### ISSUE THREAD

**Issue by sh-shahrokhi** [ANTsX/ANTs#1679]
**Is your feature request related to a problem?**

Hello, I tried to run  antsRegistrationSyN.sh on windows, because it's the most convenient way to do registrations. However, it doesn't work because it needs bash.

**Proposed new features**

Maybe a PowerShell script, on an exe file with the same functionality could solve the problem.
**Alternatives you've considered**

**Additional context**

It's the same with other bash script from Ants.

**Comment by cookpa** [comment]
Thanks for this idea. I don't think we have the resources to maintain a parallel set of Powershell scripts. Is there a reason you can't use bash in WSL?

I think if we were to rewrite scripts, it would be to Python with a view to making them run on all supported platforms. But I don't have a timeline to actually do that at the moment.

**Comment by gdevenyi** [comment]
bash is also available in something like mobaxterm, should you wish to try to use a natively compiled ANTs for windows for some reason.
