### ISSUE TITLE
Warping MNI Atlas to Native Space Through Single Subject Template 

### ISSUE THREAD

**Issue by hgstephe** [ANTsX/ANTs#1691]
Hello!

I'm trying to use ANTs for a longitudinal pipeline with the following intended steps:
  
1) Make single subject templates with multivariate template construction 
2) Use Syn Registration to register the template with FSL's MNI152 template (prefix MNI_)
3) Pull MNI co-registered atlas labels back to native space (image_a.nii) through the template using the following command: antsApplyTransforms -d 3 -i HarvardOxford-sub-maxprob-thr0-1mm.nii.gz -r image_a.nii -t [ MNI_0GenericAffine.mat , 1] -t MNI_1InverseWarp.nii.gz -t [ image_a_00GenericAffine.mat , 1 ] -t image_a_01InverseWarp.nii.gz -n GenericLabel -o atlas_to_native.nii.gz

However, the resulting image looks a little wonky (see attached image showing poor alignment of hippocampus with atlas labels).

Just applying the first set of transforms to get atlas labels for the template gives the expected results (see other attached image), so I'm wondering if I'm messing up the order of the template to native transforms. 

<img width="588" alt="atlas_to_native" src="https://github.com/ANTsX/ANTs/assets/71710905/ad4f1d5d-286e-499c-9e94-3e412b306fa0">
<img width="451" alt="atlas_to_template" src="https://github.com/ANTsX/ANTs/assets/71710905/e23c9fcb-145e-4fe5-92c2-6fe953b92d4b">

Much appreciated!

**Comment by cookpa** [comment]
Good hypothesis, but we need the registration commands to evaluate the correct order of transforms

**Comment by hgstephe** [comment]
Hello, here are the commands and the resultant atlas image warped from MNI to native space:

<img width="577" alt="temp_call" src="https://github.com/ANTsX/ANTs/assets/71710905/cd8dac60-16f4-43b0-9822-2c1f30d3a0a8">
<img width="572" alt="reg_call" src="https://github.com/ANTsX/ANTs/assets/71710905/a9931372-a0ac-4941-b8b7-e8a990c61b88">
<img width="772" alt="atlas_to_native" src="https://github.com/ANTsX/ANTs/assets/71710905/728b9e03-1319-486d-9136-be4a70829bcc">
<img width="623" alt="atlas" src="https://github.com/ANTsX/ANTs/assets/71710905/419e44d3-ef97-4cd4-b8b4-4b6c15cdad3f">

**Comment by cookpa** [comment]
OK thanks. Yes, I think you have the transforms backwards, the MNI_ pair should be on the right side.

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians#standard-space-through-an-intermediate-template

Also, you should know that the template is updated after every pairwise registration in `antsMultivariateTemplateConstruction*.sh`. So if you are using the warps left in the working directory, they are one template iteration behind. This might be a very small difference (see the intermediateTemplates directory to check) but ideally you would run `antsRegistrationSyN.sh` for each input to the final template.

Running `antsRegistrationSyNQuick.sh` might not be optimal for the template to MNI registration. I would try `antsRegistrationSyN.sh` as well.

The quality of the final registration will depend on all the steps in the pipeline, so to judge results you have to look at

1. The overlap of labels with anatomy in the MNI space (this can vary quite a bit)
2. The quality of registration from the MNI template to the local template.
3. The quality of registration from the local template to the individual subject image.
