### ISSUE TITLE
missing shared libraries when installed from conda / mamba 

### ISSUE THREAD

**Issue by jsbyysheng** [ANTsX/ANTs#1696]
**Describe the problem**

I got error about missing shared libraries when installed from conda / mamba.
```
antsRegistration: error while loading shared libraries: libITKIOBruker-5.3.so.1: cannot open shared object file: No such file or directory
```
There is no problem if I run binary downloaded from github.
**To Reproduce**

```bash
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
bash Miniforge3-$(uname)-$(uname -m).sh
mamba create -n ants_reg python=3.9
mamba activate ants_reg
mamba install -c conda-forge itk ants
antsRegistration --help
```
Then I got:
```
antsRegistration: error while loading shared libraries: libITKIOBruker-5.3.so.1: cannot open shared object file: No such file or directory
```

**System information (please complete the following information)**

 - OS: Linux version 5.15.0-97-generic (buildd@lcy02-amd64-102) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld

**ANTs version information**
 - ANTs code version: [output of antsRegistration --version]
 - ANTs installation type: 
 
```
ants                      2.5.1                h00ab1b0_0    conda-forge
```

**Comment by gdevenyi** [comment]
Please provide the output of `command -v antsRegistration` to confirm the location of the binary you are trying to run

**Comment by gdevenyi** [comment]
Also, the places for bug reports for the ants conda package is at,
https://github.com/conda-forge/ants-feedstock

**Comment by jsbyysheng** [comment]
> Please provide the output of `command -v antsRegistration` to confirm the location of the binary you are trying to run

```bash
(ants_registration) ➜  ~ command -v antsRegistration
/home/myusername/miniforge3/envs/ants_registration/bin/antsRegistration
```

> Also, the places for bug reports for the ants conda package is at, https://github.com/conda-forge/ants-feedstock
Should I move this issue to this place?

**Comment by gdevenyi** [comment]
> Should I move this issue to this place?

Yes. In the meantime, there are static binaries available from the Release page here which do work.

**Comment by cookpa** [comment]
If you're confident that the issue is unique to conda, then yeah, https://github.com/conda-forge/ants-feedstock would be the best place to get help. The developers there will open issues here if there's things that need fixing in ANTs itself.

**Comment by gdevenyi** [comment]
(I did a quick confirmation, the ants conda package is indeed broken as reported right now)

**Comment by jsbyysheng** [comment]
> (I did a quick confirmation, the ants conda package is indeed broken as reported right now)

Alright, I will close this issuse and move it to [https://github.com/conda-forge/ants-feedstock](https://github.com/conda-forge/ants-feedstock).

**Comment by cookpa** [comment]
@gdevenyi where are you seeing the conda build being broken? The status badges on the https://github.com/conda-forge/ants-feedstock are all green
