### ISSUE TITLE
antsRegistrationSyN.sh  -t so  fail

### ISSUE THREAD

**Issue by dulaoda520** [ANTsX/ANTs#1700]
When I use antsRegistrationSyN.sh, the following failures will occur.

 1DIAGNOSTIC,    44, -8.646381557074e-01, 3.249303453703e-05, 2.2829e+03, 4.1049e+01, 
 1DIAGNOSTIC,    45, -8.648112785502e-01, 3.057937711505e-05, 2.3248e+03, 4.1850e+01, 
 1DIAGNOSTIC,    46, -8.649717301127e-01, 2.879024994822e-05, 2.3655e+03, 4.0727e+01, 
 1DIAGNOSTIC,    47, -8.651284099001e-01, 2.712801458962e-05, 2.4061e+03, 4.0581e+01, 
 1DIAGNOSTIC,    48, -8.652767321682e-01, 2.553400046779e-05, 2.4463e+03, 4.0236e+01, 
 1DIAGNOSTIC,    49, -8.654188804281e-01, 2.402791572656e-05, 2.4852e+03, 3.8834e+01, 
 1DIAGNOSTIC,    50, -8.655534980110e-01, 2.257058064183e-05, 2.5250e+03, 3.9813e+01, 
/home/dulaoda/antsbin/Scripts/antsRegistrationSyN.sh: Line 639: 416638 has been killed             $COMMAND
 Registration finished. The antsRegistration call was:
---------------------------------------------------------------

I have two computers, and the other computer running antsRegistrationSyN.sh won't fail. I don't know why.

**Comment by dulaoda520** [comment]
1DIAGNOSTIC,    48, -8.508413874683e-01, 1.812446331906e-05, 2.3856e+03, 3.9874e+01, 
 1DIAGNOSTIC,    49, -8.509384383573e-01, 1.696861165948e-05, 2.4260e+03, 4.0445e+01, 
 1DIAGNOSTIC,    50, -8.510349072949e-01, 1.591570334353e-05, 2.4668e+03, 4.0777e+01, 
**XXDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST**
 1DIAGNOSTIC,     1, -7.985896744347e-01, 1.797693134862e+308, 2.8097e+03, 3.4285e+02, 
 1DIAGNOSTIC,     2, -8.000575042371e-01, 1.797693134862e+308, 3.1423e+03, 3.326

Its failure always happens in the last ,This one won't load.step,
**XXDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST**

**Comment by cookpa** [comment]
If it consistently fails between multi-resolution stages, it could be running out of memory.

**Comment by gdevenyi** [comment]
The killed message makes it clear. Check your system dmesg, or your cluster system logs, you're running out of memory.

**Comment by woainiqdu** [comment]
Thank you very much. I enlarged the memory of the virtual machine, and now it has run successfully.
