### ISSUE TITLE
iMath TruncateImageIntensity segfaults on certain input

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1708]
As reported in https://github.com/ANTsX/ANTsPy/issues/597

**To Reproduce**

See https://github.com/ANTsX/ANTsPy/issues/597 for data and code

**System information (please complete the following information)**

 - OS: Mac
 - OS version: 12.7
 - Type of system: Desktop 
 - CPU architecture: x86

**ANTs version information**
 - ANTs code version: 2.5.1.post24-g6c29d9d
 - ANTs installation type:  Compiled from source

**Comment by cookpa** [comment]
@stnava this appears to be an error with images that have negative intensities. The range of your T1w is [-32768, -31932]. The seg fault goes away if I multiply it by -1.

**Comment by cookpa** [comment]
The mask step will not contain any voxels in an image that is all negative. Should I change it to default to use the full range of pixel type?

https://github.com/ANTsX/ANTs/blob/2236a7589c73bbaf88c8bf34a821ba54e0e545d8/Examples/iMathFunctions1.hxx#L622-L630

**Comment by stnava** [comment]
thanks @cookpa for searching this out
