### ISSUE TITLE
Workflow for building registration using docker

### ISSUE THREAD

**Issue by Schwarao** [ANTsX/ANTs#1711]
I now want to build a project for implementing registration in containers.
Here's how I do it: put the shell script in the base image of ANTs to build a container, start the container and execute the script.
Here is my shell script file:
![a](https://github.com/ANTsX/ANTs/assets/56160281/bfbc1657-5546-47cc-bfec-a49b95c74ef0)
The error in docker is as follows:
![b](https://github.com/ANTsX/ANTs/assets/56160281/4c7dd6b8-7694-440f-9474-3a8238044ef5)

**Comment by Schwarao** [comment]
Can a teacher tell me how to change it?

**Comment by Schwarao** [comment]
against my shell file above，in docker .script.sh:line 6: --use-histogram-mathing,
Here I updated the shell file but not the docker

**Comment by cookpa** [comment]
When writing a multi-line command in bash, you can't have any spaces after the \

**Comment by Schwarao** [comment]
I understand now, there needs to be a format conversion step to convert the line breaks of files in Windows to the format of files in Unix
thinks

> When writing a multi-line command in bash, you can't have any spaces after the \
