### ISSUE TITLE
Ubuntu ANTs build is broken (repository version)

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#1713]
I'm not exactly sure where the logs are etc, but I see this in the automatically generated web manpages:
https://manpages.ubuntu.com/manpages/focal/en/man1/antsTransformInfo.1.html

Might be from the Debian upstream?

**Comment by cookpa** [comment]
Looks like the package has been dormant for some time. I don't know what we can do about it but if any Linux developers are interested in updating, I'd do my best to help out.

**Comment by cookpa** [comment]
Closing but still open to helping with this if a ubuntu developer wants to take it on
