### ISSUE TITLE
antsApplyTransforms on 4D BOLD images 

### ISSUE THREAD

**Issue by lisajeschke** [ANTsX/ANTs#1717]
I want to warp fmri BOLD images (i.e. 4D images) into mni-space using antsApplyTransforms . Before, I have used antsRegistrationSyn for the mapping of my anatomical images into the mni template. My fmri data is also already resampled into T1 space. 

What I now want to do is applying the mni-transformation to my functional data. With 3D-data (such as ROIs) it has worked perfectly fine. 

I have used the following command line (simplified): 

antsApplyTransforms -d 4 -i bold.nii.gz -o mni_bold.nii.gz -r mni.nii.gz -t 0GenericAffine.mat -t 1Warp.nii.gz

I get the reply: "Can't read initial transform 0GenericAffine.mat". 

The command is running though when I a) use -d 3 - however then my output image is just one volume or b) when I don't use the GenericAffine and just the Warp file, but then my output is (obviously) not correct. 

I therefore suspect my command does not work because the GenericAffine is only working with 3 dimensions. 

Is there any way how I can change my command into resampling 4D fmri data? Do I need to change something in the GenericAffine? Or shall I split the whole data set into volumes and then run the transformation on each of them (and then merge it in the end)? 

Thank you so much for your help in advance!

**Comment by cookpa** [comment]
Please see the -e option, you can use it to apply 3D warps to various kinds of multi component images

**Comment by lisajeschke** [comment]
Thank you! I have replaced -d 4 with -e 3 now and here the command is running. The output image though is 10x larger as the input image (when I used -d 4 it was the same size), unfortunately. Do you have an idea why that is?

**Comment by cookpa** [comment]
Two things affect output size. First is the resolution of the reference image, if you resample into a higher resolution space, it makes larger images. Secondly, the command by default writes out double precision (float64), try adding `--float` to use float32.

I don't know why `-d 4` would produce any output, if it couldn't read the transform it should not produce `mni_bold.nii.gz` at all.

Also, I'm not sure you have your transforms the right way around, without the exact commands I can't be sure but you can check the wiki for guidance

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

**Comment by cookpa** [comment]
OK I see now, if you don't use the affine, it doesn't complain about the transform. I'm not sure why that is, but anyway without `-e` it only outputs the first volume.

The use case for `-d 4` is for 4D transforms.  Most users want to keep the time series independent and just iteratively apply the 3D spatial transforms, which is what `-e` does.

**Comment by lisajeschke** [comment]
Thank you so much! :)  I will try 
1) using -e 3 and --float and will check if it keeps the same size (my resolution of my input and the reference image is the same) 
and 
2) as comparison, iterating the command with -d 3 over the single volumes 

The only thing that I wonder is why the -d 4 command is running if I just use 1Warp.nii.gz as transform and leave out 0GenericAffine.mat since both have been created together while registering the anatomical data to mni space.

**Comment by cookpa** [comment]
I don't know why your use of -d 4 works without the affine transform. It should not work at all. 

To clarify, you should use

`-d 3 -e 3` to warp your 4D input image
`-d 3 -e 0` or just `-d 3` to warp one 3D volume extracted from your 4D image

These should produce identical results (or at least very similar, each manipulation of the image can introduce tiny differences in nifti image headers).

Most users will never need `antsApplyTransforms -d 4`, because they don't have 4D transforms (ie, they haven't run `antsRegistration -d 4`). It also makes no sense to use `-d 4` with a 3D reference image. I'll see if I can update the program to check that.
