### ISSUE TITLE
ANTs apply transform for template construction has hardcoded dimension = 3

### ISSUE THREAD

**Issue by mabulnaga** [ANTsX/ANTs#1718]
in the files antsMultivariateTemplateConstruction.sh and antsMultivariateTemplateConstruction2.sh, the calls to antsAI and antsApplyTransforms have hardcoded -d 3, when they should instead be -d ${DIM}. This was causing errors when trying to construct 2D templates.

**Comment by cookpa** [comment]
Oops, my mistake. Workaround with an initial template (-z), I will fix

**Comment by mabulnaga** [comment]
I just sent in a PR
