### ISSUE TITLE
Running into "error while loading shared libraries" while using antsApplyTransforms

### ISSUE THREAD

**Issue by arlenelor** [ANTsX/ANTs#1728]
Hello, I am trying to use the code function antsApplyTransforms. However, I get the following error: 

"antsApplyTransforms: error while loading shared libraries: libITKIOTransformMINC-5.3.so.1: cannot open shared object file: No such file or directory"

Can someone please tell me how this can be resolved? Thanks.

**Comment by gdevenyi** [comment]
Please do not ignore the issue template and provide the requested information.

**Comment by cookpa** [comment]
@arlenelor we need to know more about your system and ANTs installation to help, but it sounds like a problem setting the environment to find shared libraries. Can you resubmit using the template and fill out the information there?

Also, if you have any suggestions as to how we can make the instructions better, please feel free to post them here.

**Comment by atwu** [comment]
Hello! I am having the same issue. Can you direct me to the template that you want us to fill? I am using conda on a linux machine.

**Comment by cookpa** [comment]
Here's the bug report template

https://github.com/ANTsX/ANTs/issues/new?assignees=&labels=&projects=&template=bug_report.yml

I haven't run the conda version myself but usually this error happens when you have built with shared libraries, but not set LD_LIBRARY_PATH.

Sometimes fixable with something like

```bash
antsBin=$( dirname $(which antsRegistration) )
export LD_LIBRARY_PATH=${antsBin%bin}lib:$LD_LIBRARY_PATH
```

**Comment by atwu** [comment]
Done. Thank you! The main problem is that I can't even find it in my library (details in submitted bug report template).
