### ISSUE TITLE
Multivariate template construction with > 10 modalities

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTs#1731]
Just ran into this issue and decided to post to get some feedback.  With the adopted naming convention, when we `ls` the set of images for a particular modality (e.g., [here](https://github.com/ANTsX/ANTs/blob/d9bd815fa981c27e0fcbb6d55fd50cbd21488090/Scripts/antsMultivariateTemplateConstruction2.sh#L390)), the files for modality `1` get listed with `10`.  An immediate solution seems to be adding something like an underscore in the base filename after the modality index but just wanted to see if there was an alternative preferred approach.

**Comment by cookpa** [comment]
An underscore seems like a sensible quick fix, but it would be nice to have more explicit naming, something like {prefix}_template_modality-{i}_ or {prefix}_input-{j}_modality-{i}_ for input images. The trailing underscore prevents the same problem with `1Warp.nii.gz` getting joined to {i}.

**Comment by ntustison** [comment]
Thanks @cookpa .  Sounds good.  I'll work on putting together a pull request.
