### ISSUE TITLE
running ANTs binaries on a windows laptop reports error: "could not find VCRUNTIME140_1.dll"

### ISSUE THREAD

**Issue by citystrawman** [ANTsX/ANTs#1742]
### Operating system and version

windows 10

### CPU architecture

x86_64 (PC, Intel Mac, other Intel/AMD)

### ANTs code version

v 2.5.1

### ANTs installation type

Downloaded Github release binaries

### Summary of the problem

I downloaded ANTs release binaries from https://github.com/ANTsX/ANTs/releases and ran it on windows 10.  I used exactly the same binaries on two different laptop(both use windows 10). On one laptop everything works fine, but on the other one, running .exe (for example, antsRegistration.exe, PrintHeader.exe) I got error messages saying that "could not find VCRUNTIME140_1.dll"

### Commands to reproduce the problem.

open a windows terminal, enter the binary folder, and then just `./antsRegistration.exe`

### Output of the command with verbose output.

could not find VCRUNTIME140_1.dll

### Data to reproduce the problem

no data is required

**Comment by cookpa** [comment]
`VCRUNTIME140.dll` is part of Visual Studio but I didn't think it was required to use ANTs binaries, which should be statically built.

The fact that it's asking for `VCRUNTIME140_1.dll` is odd to me because it suggests there's two copies involved. I don't know if this is to do with your system or the Github runner on which ANTs was built.

I don't have a Windows machine so I can't test directly.

**Comment by citystrawman** [comment]
> `VCRUNTIME140.dll` is part of Visual Studio but I didn't think it was required to use ANTs binaries, which should be statically built.
> 
> The fact that it's asking for `VCRUNTIME140_1.dll` is odd to me because it suggests there's two copies involved. I don't know if this is to do with your system or the Github runner on which ANTs was built.
> 
> I don't have a Windows machine so I can't test directly.

yes. it is very weird and it does not happen on other windows laptops. 

I have installed Visual C++ Redistributable and now it works.
