### ISSUE TITLE
ResampleImage usage

### ISSUE THREAD

**Issue by devDonnn** [ANTsX/ANTs#1744]
Hi,

I have an image with dimensions of 256x256x176 and a voxel size of 1x1x1. Is it possible to convert to 256x256x256 and 1x1x1 resolution by using ResampleImage? If not, is there another command line tool to do so? Thanks.

**Comment by ntustison** [comment]
No, but that functionality is in our ANTsPy extension (ANTsPyNet) through the [``pad_or_crop_image_to_size``](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/cropping_and_padding_utilities.py#L91) function.

**Comment by devDonnn** [comment]
Wonderful @cookpa ! That work very well in my case. Thanks a lot!
