### ISSUE TITLE
REQUEST: rewrite the readme?

### ISSUE THREAD

**Issue by ncullen93** [ANTsX/ANTs#1749]
I wanted to respectfully suggest that the README for ANTs get a nice overhaul. It's currently a brain dump of pictures, links, and references without much explanation about ANTs software and how to use it.  It seems like a pedantic request, but the readme actually has an immense impact on project growth and perception.

A typical format might be as follows:

- Overview
- Installation
- Getting Started
- Examples
- Resources
- Contributing
- Team
- References
- License

I'm happy to rewrite it.  Here is a nice list of good readmes for inspiration - https://github.com/matiassingers/awesome-readme?tab=readme-ov-file

**Comment by ntustison** [comment]
I'd want to include links to the various examples but that would be fine with me.

**Comment by ncullen93** [comment]
Ok, I don't want to change too much so maybe I will just try to organize a bit and identify potentially outdated links that can be updated.

**Comment by ntustison** [comment]
One other thought would be to potentially migrate the links to another section of the ANTsX tutorial.

**Comment by ncullen93** [comment]
What do you mean by ANTsX tutorial? There are essentially three types of link: example scripts, journal articles, and learning resources. I think the learning resources could be moved or consolidated in some way.

**Comment by ntustison** [comment]
https://tinyurl.com/antsxtutorial

**Comment by cookpa** [comment]
I agree it's overdue to be revised. I actually recently added a line near the top with download links. I think ANTs is compiled from source more than most tools (the build instructions are consistently the most popular page on the site), even by people who would rather just download binaries.

**Comment by ncullen93** [comment]
Ok, I am working on a revision on my personal fork and will submit a PR eventually... then go from there.

**Comment by stnava** [comment]
one of my favorite "README" examples:     https://www.cs.cmu.edu/~biglou/   

![image](https://github.com/ANTsX/ANTs/assets/324222/ebd021f9-74a5-4d73-88db-49db9088e2a2)

**Comment by ntustison** [comment]
@stnava --- nice.  Did I ever tell you that Duolingo reached out to me and gave me $50 to take a French test after ~6 months of using the app?  Probably a bar conversation topic when we next meet up.

**Comment by cookpa** [comment]
@stnava 's bio is consistently a top driver of traffic to this site. 

But once they are here I think we could make it easier to navigate.
