### ISSUE TITLE
use in docker

### ISSUE THREAD

**Issue by Schwarao** [ANTsX/ANTs#1755]
Why do I use images of different versions of antsx/ants in Docker and get different results when running the same script shell file?
v:2.5.0、v:2.5.2、latest、master

**Comment by Schwarao** [comment]
Does anyone know that the results of running locally on a computer are consistent with those running in a container? Which version of the image is being used?

**Comment by Schwarao** [comment]
Do you have an image corresponding to the antsRegistration version v2.1.0

**Comment by gdevenyi** [comment]
All tagged releases available via docker are here, https://hub.docker.com/r/antsx/ants/tags

**Comment by cookpa** [comment]
Can you provide more details, like the script that is being run? Some programs vary run-to-run even on the same machine.
