### ISSUE TITLE
About interpolation with tranfomation matric by Ants

### ISSUE THREAD

**Issue by apple1986** [ANTsX/ANTs#1758]

**Comment by cookpa** [comment]
Please resubmit with text, we won't be notified if you edit this.

**Comment by apple1986** [comment]
Hi, developers, May I ask a question? I have two registered images (A1 and A10) by Ants. The pyhical distance is 100um. Is it possible to generate 8 slices (images, like A2, A3...,A9) between these two reigstered images by using transform field, so the distance between each slice (image) is 10 um. Could anyone give me some suggestions ? Thanks so much.
