### ISSUE TITLE
Problem about brain extraction and segmentation

### ISSUE THREAD

**Issue by windyjunfeng** [ANTsX/ANTs#1763]
Hi, I have two questions about brain extraction and segmentation. 

- First, I see the command in antsBrainExtraction.sh.
`bash $0 -d 3 -a t1.nii.gz -e brainWithSkullTemplate.nii.gz -m brainPrior.nii.gz -o output`
Is there any files like brainWithSkullTemplate.nii.gz and brainPrior.nii.gz? I don't find them in ants docker.

- Second, I want to segment scalp and bone in the brain T1w MRI. Could you please give some suggestions? It seems that scalp and bone these two classes are not included when carrying out tissue segmentation. 

Thank you very much!

**Comment by cookpa** [comment]
You can use any brain template and mask, they are not included with ANTs but some are available here

https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436

and there are several more choices in templateflow.

I would also recommend the brain extraction utility in [ANTsPyNet](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/brain_extraction.py), which is faster and usually better.

I don't know of a solution for scalp and bone segmentation on T1w MRI. The bone contrast is not very good on T1w. But there are new cross-modality segmentation models coming out all the time, so maybe something is out there.

**Comment by windyjunfeng** [comment]
I see. Thank you for your answer and suggestion! I'll try it!
