### ISSUE TITLE
Build multiple templates into one

### ISSUE THREAD

**Issue by YUZHENG6** [ANTsX/ANTs#1788]
Hi ANTs Team,

Because my personal resource performance may not be able to handle huge datasets I'm wondering if it would be possible if I separate the many brains into each groups equally, constructed  templates, and then finally did a reconstruction of these templates to build a single template?  

Kind regards,
Yu

**Comment by YUZHENG6** [comment]
> Hi ANTs Team,
> 
> Because my personal resource performance may not be able to handle huge datasets I'm wondering if it would be possible if I separate the many brains into each groups equally, constructed templates, and then finally did a reconstruction of these templates to build a single template?
> 
> Kind regards, Yu

Does this separate construction affect accuracy as opposed to processing all the brain data at once?

**Comment by ntustison** [comment]
Generally, you should be fine.  But note that you can accommodate limited resources with the various options.
