### ISSUE TITLE
Can't find the end-to-end segmentation scripts

### ISSUE THREAD

**Issue by stephen-q-le** [ANTsX/ANTs#1790]
I'm trying to find examples of ANTs-based scripts that do all the steps necessary to segment real medical imaging.

- [avants2011.pdf](https://link.springer.com/article/10.1007/s12021-011-9109-y) mentions these scripts: `atroposBwebRF40FigureExample.sh`, `ants_multitemplate_labeling.sh` and `buildtemplateparallel.sh`. Where are they? If they got renamed/refactored into something else, where is that?
- In the [ANTs Talk](http://stnava.github.io/ANTsTalk/#/) I see several mentions of ANTs being evaluated in various competitions. But I haven't found any competition page that states what exact ANTs script was run, and on what data (and some of the competition pages are dead links). Can someone point me to one?

**Comment by ntustison** [comment]
> * [avants2011.pdf](https://link.springer.com/article/10.1007/s12021-011-9109-y) mentions these scripts: atroposBwebRF40FigureExample.sh, ants_multitemplate_labeling.sh and buildtemplateparallel.sh. Where are they? If they got renamed/refactored into something else, where is that? 

The reusable shell scripts that we have kept around from our published work are located [here](https://github.com/ANTsX/ANTs/tree/master/Scripts).  

> * In the [ANTs Talk](http://stnava.github.io/ANTsTalk/#/) I see several mentions of ANTs being evaluated in various competitions. But I haven't found any competition page that states what exact ANTs script was run, and on what data (and some of the competition pages are dead links). Can someone point me to one?

You'd have to ask about the specific competition.  But, as an example, the source for the BraTS 2013 segmentation competition is located [here](https://github.com/ntustison/BRATS2013). More recently, we participated in the BraTS-Reg 2022 competition and the source is located [here](https://github.com/ntustison/BraTS-Reg22).  As you can see, we've gotten a bit more organized over the years.  

More learning resources for the ANTs library can be found [here](https://github.com/ANTsX/ANTs?tab=readme-ov-file#code-examples).

Note, though, that  much of our current active development has been through our R-based ANTsR and Python-based ANTsPy/ANTsPyNet libraries.  [Here](https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621) is a current set of self-contained code examples for the various functionalities available.
