### ISSUE TITLE
Regarding DBM, in Jacobian group analysis

### ISSUE THREAD

**Issue by JinDJsuper** [ANTsX/ANTs#1794]
### Operating system and version

Ubuntu 20.04

### CPU architecture

x86_64 (PC, Intel Mac, other Intel/AMD)

### ANTs code version

ants-2.5.0

### ANTs installation type

Compiled from source

### Summary of the problem

I would like to know if using DBM methods for two-sample t-tests in group analysis has a significant impact when generating Jacobian data, specifically whether values like 1 0 or 1 1 have substantial effects. I have already generated Jacobian data for two groups. I want to know what software others typically use for analysis. I have tried using FSL's randomise and SPM for general linear model-based two-sample t-tests, but the results still show some differences. Do you have any suggestions for the DBM analysis process?

### Commands to reproduce the problem.

`CreateJacobianDeterminantImage 3 Warp.nii.gz LogJacobian.nii.gz 1 0 ` or
`CreateJacobianDeterminantImage 3 Warp.nii.gz LogJacobian.nii.gz 1 1 `

### Output of the command with verbose output.

-

### Data to reproduce the problem

-

**Comment by ntustison** [comment]
Have you seen [this simple DBM example](https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621#deformation-based-morphometry) in our ANTsR/ANTsPy tutorial?

**Comment by JinDJsuper** [comment]
> Have you seen [this simple DBM example](https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621#deformation-based-morphometry) in our ANTsR/ANTsPy tutorial?

Okay, this is the first time I've seen this. I will check out this example.
 
 thank you

**Comment by ntustison** [comment]
Do you know how to perform a two-sample t-test with covariates in R?  The application in ANTsR is exactly the same.  In particular, study these lines from the example:

```r
> # Create simulated outcomes and covariates
> neuroCondition <- rnorm( numberOfSubjects )
> age <- sample( 40:70, numberOfSubjects, replace = TRUE )
> sex <- sample( c( 0, 1 ), numberOfSubjects, replace = TRUE )
> covariates <- data.frame( neuroCondition = neuroCondition, age = age, sex = sex, brainVolume = brainVolume)
> rformula <- "neuroCondition ~ age + sex + brainVolume + logJacobian"
> 
> # Run image-based regression
> dbm <- ilr( covariates, list( logJacobian = logJacobian ), rformula )
```

**Comment by gdevenyi** [comment]
This summer school documentation on DBM methods in R may be of use
https://mouse-imaging-centre.github.io/summer_school2017/

**Comment by JinDJsuper** [comment]
> perform a two-sample t-test with covariates in R?

thank for your reply

I can use R to perform a two-sample t-test with covariates. I understand that you mean editing the data using a two-sample t-test. However, since this jacobian image has already been converted into matrix format, how should I interpret these results? Should I convert them into visual parameters, such as marking heatmaps in the brain?

**Comment by JinDJsuper** [comment]
> This summer school documentation on DBM methods in R may be of use https://mouse-imaging-centre.github.io/summer_school2017/

Thank you for your response. 
I think this will be very helpful to me. I will carefully review the content on the website.

**Comment by ntustison** [comment]
In the example, I added how to create an overlay image of the actual qvalues.

```r
> # Create overlay q-value image
> logJacobianQvaluesImage <- matrixToImages( matrix( data = logJacobianQvalues, nrow = 1 ), rtemplateGM )
```
