### ISSUE TITLE
antsMotionCorr --write-displacement no output

### ISSUE THREAD

**Issue by toomanycats** [ANTsX/ANTs#1797]
### Operating system and version

CentOS 7

### CPU architecture

x86_64 (PC, Intel Mac, other Intel/AMD)

### ANTs code version

ants-2.5.0

### ANTs installation type

Compiled from source

### Summary of the problem

When I use `antsMotionCorr` with the `--write-displacements` options I see no displacement output.

The input 4D NiFTI is a PET series.

### Commands to reproduce the problem.

antsMotionCorr --write-displacement -m CC -d 3 -o ".nii.gz" -p Linear -t Rigid -o ave.nii.gz  -a  PET_4frames.nii.gz

### Output of the command with verbose output.

ANTSVERSION=ants-2.5.0

ls
ave.nii.gz

### Data to reproduce the problem

[BRAIN_AC_ADNIrecon_2024.02.21.nii.gz](https://github.com/user-attachments/files/17135968/BRAIN_AC_ADNIrecon_2024.02.21.nii.gz)

**Comment by cookpa** [comment]
I think it is `--write-displacement 1`. I will update the usage

**Comment by toomanycats** [comment]
I forgot to add that I already tried adding an explicit "true":

    antsMotionCorr -v --write-displacement 1 1 -d 3  -o ".nii.gz" -w -p Linear -t Rigid -o ave.nii.gz -a ../Sample/ADNIDII-0-3028-1/BRAIN_AC_ADNIrecon_2024.02.21.nii.gz
    ANTSVERSION=ants-2.5.0
    verbose
    average out ave.nii.gz

Still no love.  I keep thinking I'm missing something obvious that I'm not seeing in my call.
Confirming there's really multiple frames:

    fslinfo ../Sample/ADNIDII-0-3028-1/BRAIN_AC_ADNIrecon_2024.02.21.nii.gz | grep -P '^dim4'
    dim4            6

**Comment by cookpa** [comment]
You need to do it in two stages:

```
antsMotionCorr -d 3 -a BRAIN_AC_ADNIrecon_2024.02.21.nii.gz -o ave.nii.gz
```

Then

```
antsMotionCorr -d 3 -o [ moco, moco_corrected.nii.gz, moco_avg.nii.gz ] \
    -v 1 --write-displacement 1  -p Linear -t Rigid[ 0.05 ] \
    -m MI[ ave.nii.gz , BRAIN_AC_ADNIrecon_2024.02.21.nii.gz, 1, 32 ] \
    -i 10x10 -f 2x1 -s 1x0
```

**Comment by toomanycats** [comment]
Ok thanks ! Perhaps the doc needs an example.

**Comment by toomanycats** [comment]
If want motion estimates, should I also use `antsMotionCorrStats` ? 
I was going to compute the rigid motion myself using python.

Cheers  and thanks again.

**Comment by cookpa** [comment]
Yes `antsMotionCorrStats`, but that only works with the CSV parameter file. It doesn't work for warp fields.

**Comment by toomanycats** [comment]
The examples in `Examples/Scripts` solved my misunderstanding. Thank you for your help.
