### ISSUE TITLE
antsTransformInfo fails to read COM alignment from antsAI

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#1819]
### Operating system and version

Mac OS 14

### CPU architecture

x86_64 (PC, Intel Mac, other Intel/AMD)

### ANTs code version

2.5.3.post16-g1892fef

### ANTs installation type

Compiled from source

### Summary of the problem

 Seg fault after using antsAI "AlignCentersOfMass"
 
 The transform is good, readable into antspy
 
```
 >>> import ants
tr = ants.read>>> tr = ants.read_transform('com.mat')
>>> tr
ANTsTransform
	 Type       : TranslationTransform
	 Dimension  : 3
	 Precision  : float
```	 

### Commands to reproduce the problem.

```
antsAI -d 3 \
                 -m Mattes[tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz, moving.nii.gz] \
                  -t AlignCentersOfMass \
                  -o com.mat \
                  --verbose 
 antsTransformInfo com.mat 
 ```
 

### Output of the command with verbose output.

Transform file: com.mat
Number of transforms = 1
zsh: segmentation fault  antsTransformInfo com.mat

### Data to reproduce the problem

Works on any data

**Comment by gdevenyi** [comment]
This is probably my fault #1712

**Comment by gdevenyi** [comment]
Confirmed it works with 2.5.2 so probably my fault.

**Comment by cookpa** [comment]
Thanks, do you want to have a go at fixing it?

The transform type antsAI writes is a `TranslationTransform_double_3_3`. 
 
Normally I expect the usual exception
 
 ```The usual cause of this error is not registering the transform with TransformFactory
Currently registered Transforms:
<every transform in existence except the one you want>
```

Would be good to preclude a seg fault, as well as making it read `TranslationTransform_double_3_3`

**Comment by cookpa** [comment]
In `ccmake`, if you go to `CMAKE_BUILD_TYPE` and hit enter, it will cycle through options. I usually use `RelWithDebInfo` as a first pass, because 'Debug' is very slow at runtime. But in this case you can probably just do `Debug`.

**Comment by cookpa** [comment]
I reckon this is the problem

https://github.com/ANTsX/ANTs/blob/ee84001afbcd6eec5c64504d91dd750fed3a0796/Examples/antsTransformInfo.cxx#L140C40-L140C65

The translation transform is not a subclass of a matrix transform, it only has the translation parameters.

I think you need

```
            if (itktx3d)
            {
              itktx3d->Print(std::cout);
              std::cout << "Determinant: " << vnl_determinant(itktx3d->GetMatrix().GetVnlMatrix()) << std::endl;
            }
```     

like you have in the other parts of the function.

**Comment by gdevenyi** [comment]
Based on advanced print-statement debugging techniques, the segfault happens at:
https://github.com/ANTsX/ANTs/blob/master/Examples/antsTransformInfo.cxx#L161

For probably the reasons of the subclass issue.

It seems to me naively that it *should* be a subclass. (Identity matrix + translation). I'll look into how to properly cast it...
