### ISSUE TITLE
ANTs on Windows: Compile Suggestions from Octavian Soldea

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTs#196]
I am writing you regarding compiling ANTs on Windows ...
<snip>  I will try to summarize my changes. 

In file ITKSetStandardCompilerFlags.cmake after line 125 I have set

```
check_c_compiler_warning_flags(CMAKE_C_WARNING_FLAGS
${VerboseWarningsFlag} #${c_flags} ${c_and_cxx_flags}
  )
  check_cxx_compiler_warning_flags(CMAKE_CXX_WARNING_FLAGS
${VerboseWarningsFlag} #${c_and_cxx_flags} ${cxx_flags}
  )
```

in file ProjectSourceVersion.cmake at line 38 I have commented the Version vars:

```
#include( "${CMAKE_CURRENT_SOURCE_DIR}/CMake/ProjectSourceVersionVars.cmake" )
```

In file antsSliceRegularizedRegistration.cxx at line 362
VImageDimension should be a constant:

```
const unsigned int VImageDimension = ImageDimension - 1;
```

In file itkantsRegistrationHelper.h at line 799 one should use typename:

```
typename itk::ImageBase<VImageDimension>::Pointer
GetShrinkImageOutputInformation(const itk::ImageBase<VImageDimension>
* inputImageInformation,
                                typename const
RegistrationHelper<TComputeType,
VImageDimension>::ShrinkFactorsPerDimensionContainerType
&shrinkFactorsPerDimensionForCurrentLevel) const;
```

Apparently, zlib is also required.

**Comment by dorianps** [comment]
This is good. Will give it a try on latest ANTs.

**Comment by stnava** [comment]
additional comments from a different ANTs contributor:

So, I built ANTs with visual studio 2012 is done using the instruction in ( https://github.com/stnava/ANTs/issues/196 ). But the following need to be added:

* In itkantsRegistrationHelper.hxx line 19 also add the typename before the const same as in the last step in the link:

```
typename itk::ImageBase<VImageDimension>::Pointer
GetShrinkImageOutputInformation(const itk::ImageBase<VImageDimension>* inputImageInformation,
typename const
RegistrationHelper<TComputeType, VImageDimension="">::ShrinkFactorsPerDimensionContainerType
&shrinkFactorsPerDimensionForCurrentLevel) const;
```
* In the antsjointfusion line 534 where there is `std::snprintf` there is no need to use the space name std and instead of `snprinf` add the underscore : `_snprintf`

We have not tested these for compatibility with OSX or Linux and, as such, cannot include these suggestions.  We would appreciate any contributions toward regular testing on windows.

**Comment by tiantian-li** [comment]
I have compiled ANTs on the Linux subsystem of Windows10 according to[https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Windows-10](url),but i don't know how to run it on win10,I mainly want to use N4BiasFieldCorrection which is installed from ANTs. Could you please tell me how to install the N4BiasFieldCorrection from ANTs and how to use it on win10? Thanks @stnava

**Comment by dorianps** [comment]
@tiantian-li

Were the replies @ntustison and I gave you helpful. Please reply to the other thread. Once you install Ants in the Linux subsystem there is no difference with any Linux installations. Try following the instructions, check if binaries are located where they should be, and provide detailed step by step instructions what have you tried on the thread you already opened some days ago.

**Comment by tina-ebi** [comment]
I tried to install ANTs according to the website  https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Windows-10.  During installation on Linux, I got an error (I attached it). I think this error is because RAM is not enough but I am not sure. Could you please help me to fix this error?
Thank you.
Elli

![error](https://user-images.githubusercontent.com/62328344/77677111-e0839800-6fac-11ea-8ff7-090ac6a17a12.JPG)
![Ubuntu propertize](https://user-images.githubusercontent.com/62328344/77677200-fd1fd000-6fac-11ea-8538-87434f7dce80.JPG)
![system properties](https://user-images.githubusercontent.com/62328344/77677245-0dd04600-6fad-11ea-8355-d7c6f610f8af.JPG)

**Comment by cookpa** [comment]
If you are making with multiple threads, please try to make with a single thread
