### ISSUE TITLE
Which version of cmake is actually required?

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#306]
Current CMakeLists.txt lists 2.8.9 as the version required.

.travis.yml manually installs 3.4.0-rc1
.travis.yml "needs 3.2" for the OSX build

Testing on Ubuntu Trusty with a manually downloaded 2.8.9 seems to work.

**Comment by stnava** [comment]
this is a good question - we should provide a link to cmake-to-itk dependencies which would likely clarify this.  i.e. as ITK updates its needed cmake version, so would ants.  is there a place where this is documented for itk?

**Comment by gdevenyi** [comment]
Fixed by e4e5ae2f3ea1df2cd795c816871c5c5b24591c6f
