### ISSUE TITLE
"New release is coming to town" ?

### ISSUE THREAD

**Issue by yarikoptic** [ANTsX/ANTs#329]
Lots of work was done :  v2.1.0-633-g32c0360 , I thought it would be awesome if there was a fresh release

**Comment by yarikoptic** [comment]
anything else I could do to facilitate it happening?  meanwhile I've uploaded a snapshot 2.1.0+git635-g0752c29-1 to debian experimental and -devel of neurodebian.  I didn't look inside in what has changed to state anything about using this version instead of 2.1.0... were there some backward incompatible changes etc?

**Comment by pipitone** [comment]
I would also like to see this. Happy to help.

**Comment by stnava** [comment]
hi guys - i set this up for antsr:  https://github.com/stnava/manageReleases  which permits  "latest releases" with minimal effort.    i would be happy to have something similar for ants - or to hand off this responsibility to an interested party.   @armaneshaghi  was helping with this at one point.

**Comment by armaneshaghi** [comment]
I'll try to automate this over the next month when I get some free time.

**Comment by yarikoptic** [comment]
sorry to pester -- new release is coming? ;)

**Comment by yarikoptic** [comment]
Was fixed by 0740f9111e5a9cd4768323dc5dfaa7c29481f9ef
