### ISSUE TITLE
Output of `-h` should go to STDERR

### ISSUE THREAD

**Issue by TrevorKMDay** [ANTsX/ANTs#337]
The help menu, when asked for, e.g. `antsCorticalThickness.sh` should be sent to STDOUT, not STDERR, so that it can be passed to a pager like `more` or `less`, as suggested by [the GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html)

**Comment by ntustison** [comment]
You're perfectly welcome to contribute a pull request for such issues.
