### ISSUE TITLE
bash scripts don't catch errors

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#397]
If any of the commands in the bash scripts fail, currently the scripts continue on as if things were successful.

It would be beneificial to enable "unofficial bash strict mode" http://redsymbol.net/articles/unofficial-bash-strict-mode/ on the scripts to catch/error out on problems.

This *may* cause scripts to stop due to certain bash programming anti-patterns (which would need to be adjust) so it needs to be tested before being committed.

**Comment by ntustison** [comment]
If you're interested in this, you're certainly welcome to test it and propose a relevant commit.

**Comment by gdevenyi** [comment]
Sure. Can you point out which scripts you consider "maintained"?

Does there exist any small test data for these scripts so I can confirm functionality without rolling my own?

**Comment by ntustison** [comment]
I'm guessing anything with ants*.sh constitutes a subset of "maintained" scripts.

Some of these scripts are exercised with various github examples (including data) that are linked to on the main ANTs github page.

**Comment by gdevenyi** [comment]
@cookpa In the case of calls such as grep where there might not be a match, there is a workaround described at http://redsymbol.net/articles/unofficial-bash-strict-mode/#issues-and-solutions

Essentially, ``|| true`` handles those cases.

It's a bit of a flip in coding style, where you explicitly catch known "might fails" instead of explicitly checking return codes.

**Comment by hjmjohnson** [comment]
Gabriel,

 

Thank you for taking this on.  I have been using this type of scripting approach for many years, and it certainly does make more robust and easier to use scripts.

 

Hans

**Comment by gdevenyi** [comment]
Closed by #1771
