### ISSUE TITLE
register partial (slab) of BOLD brain image to T1 anatomical image

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTs#400]
here we give an example of one way to register partial to full brain data.

 the data is fairly low quality so it's tough to get a "perfect" registration unless you move to customization of the antsRegistration parameters.  here is an approach that may get one close:

```
# make mask of fixed image
ThresholdImage 3 nap_rest_deobl_desp_volreg_1.nii.gz /tmp/mask2.nii.gz 1100 Inf

# register to anat with mask
m=nap_rest_deobl_desp_volreg_1.nii.gz
f=anat_skullstripBrainExtractionBrain.nii.gz
antsRegistration --verbose 1 --dimensionality 3 --float 0 \
  --output [/tmp/2b,/tmp/2bWarped.nii.gz,/tmp/2bInverseWarped.nii.gz] \
  --interpolation Linear --use-histogram-matching 0 \
  --winsorize-image-intensities [0.005,0.995] \
   --initial-moving-transform [$f,$m,1] \
 --transform translation[0.1] --metric MI[$f,$m,1,32,Random,0.25] \
--convergence [50,1e-6,10] --shrink-factors 1 --smoothing-sigmas 0vox \
 --transform Rigid[0.1] --metric MI[$f,$m,1,32,Random,0.25] \
--convergence [500x250x50,1e-6,10] --shrink-factors 2x2x1 --smoothing-sigmas 2x1x0vox \
-x [/tmp/mask2.nii.gz,/tmp/mask2.nii.gz]
```

you might also add a small amount of deformation

```
antsRegistration --verbose 1 --dimensionality 3 --float 0 \
  --output [/tmp/2b,/tmp/2bWarped.nii.gz,/tmp/2bInverseWarped.nii.gz] \
  --interpolation Linear --use-histogram-matching 0 \
  --winsorize-image-intensities [0.005,0.995] \
   --initial-moving-transform [$f,$m,1] \
 --transform Rigid[0.1] --metric MI[$f,$m,1,32,Random,0.25] \
--convergence [500x250x50,1e-6,10] --shrink-factors 2x2x1 --smoothing-sigmas 2x1x0vox \
-x [/tmp/mask2.nii.gz,/tmp/mask2.nii.gz] \
 --transform SyN[0.1,3,0] --metric MI[$f,$m,1,32] \
--convergence [50x10,1e-6,10] --shrink-factors 2x1 --smoothing-sigmas 1x0vox \
-x [/tmp/mask2.nii.gz,/tmp/mask2.nii.gz] 
```

The files, for reference:

[anat_skullstripBrainExtractionBrain.nii.gz](https://github.com/stnava/ANTs/files/716620/anat_skullstripBrainExtractionBrain.nii.gz)
[nap_rest_deobl_desp_volreg_1.nii.gz](https://github.com/stnava/ANTs/files/716621/nap_rest_deobl_desp_volreg_1.nii.gz)

**Comment by AlejandroCallara** [comment]
It works well compared to the combination of things I have done between AFNI and ANTs!

Thank you very much for your help.

Alejandro.

**Comment by stnava** [comment]
maybe this example should move to a github project  /  repo

**Comment by ntustison** [comment]
Probably a good idea.  I'll try to do that sometime today.

**Comment by ntustison** [comment]
https://github.com/ntustison/PartialSlabEpiT1ImageRegistration

**Comment by ntustison** [comment]
Also, posted it on the ANTs [README](https://github.com/stnava/ANTs/commit/271095fa0101a6562055cbd697f4579c5603cb65).
