### ISSUE TITLE
GenericLabelInterpolator has been merged to ITK

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#406]
The label interpolator code that I cherry-picked from the Insight Journal submission has been integrated into the latest release (4.11) of ITK:
https://github.com/InsightSoftwareConsortium/ITKGenericLabelInterpolator

**Comment by cookpa** [comment]
`antsApplyTransforms ... -n GenericLabel`, nice

**Comment by gdevenyi** [comment]
@cookpa I opened this because the GenericLabel in antsApplyTransforms is the original code I stole from the Insight Journal article.

This is my reminder that I should change to using the in-tree code (add it to build etc)

**Comment by cookpa** [comment]
OK sorry, re-opening as a "to-do" issue.

**Comment by gdevenyi** [comment]
Still a todo, should reopen.
