### ISSUE TITLE
LabelGeometryMeasures

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#418]
I was asked about getting cortical surface area for data run through `antsCorticalThickness.sh`, with OASIS labels warped to the subject space. I figured the most sensible way was to use `LabelGeometryMeasures` on the labels directly, after masking with the subject's gray matter segmentation. I did a quick check of volumes, figuring that (regional volume) / (mean thickness) would be approximately the surface area. But I noticed the numbers were way off. 

So I drew a cube in SNAP, with sides of 25mm. The volume of this cube is 25^3 = 15625 mm^3:

```
$c3d cube.nii -dup -lstat
LabelID        Mean        StdD         Max         Min       Count     Vol(mm^3)        Extent(Vox)
    0       0.00000     0.00000     0.00000     0.00000      496375    496375.000     80    80    80
    1       1.00000     0.00000     1.00000     1.00000       15625     15625.000     25    25    25
```

`LabelGeometryMeasures` agrees on the volume but not on the surface area, which I was expecting to be 6 * 25^2 = 3750 mm^2, but instead it reports 2500 mm^2. 

```
$ LabelGeometryMeasures 3 cube.nii 
Label  Volume    SurfArea(mm^2) Eccentricity   Elongation     Orientation    Centroid                      Axes Length                   Bounding Box                  
1      15625     2500           0              1              0              [41, 40, 40]                  [28.8675, 28.8675, 28.8675]   [29, 53, 28, 52, 28, 52]     
```

Here's the image:

https://dl.dropboxusercontent.com/u/20389729/cube.nii.gz

**Comment by cookpa** [comment]
A sphere is closer to what I'd expect: again drawn in SNAP, radius 20mm. 

4/3 * pi * 20^3 = 33510.32
4 * pi * 20^2 = 5026.548

```
LabelGeometryMeasures 3 sphere.nii.gz 
Label  Volume    SurfArea(mm^2) Eccentricity   Elongation     Orientation    Centroid                      Axes Length                   Bounding Box                  
1      32240     4906.67        0.0238843      1.00029        0              [41.5, 39.5, 40]              [35.3348, 35.3348, 35.3449]   [22, 61, 20, 59, 21, 59]      
```

https://dl.dropboxusercontent.com/u/20389729/sphere.nii.gz

**Comment by ntustison** [comment]
Interesting.  There aren't any parameter options I'm leaving for a couple hours but here's the Insight Journal [article](http://www.insight-journal.org/browse/publication/852) detailing the implementation.

**Comment by ntustison** [comment]
Okay, so Gaetan [converts](https://github.com/midas-journal/midas-journal-852/blob/master/lm.cxx#L29-L49) the label image to a label map which then calls the perimeter estimator under the hood somewhere.  I [changed](https://github.com/stnava/ANTs/commit/4e02aa76621698e3513330dd9e863e22917e14b7) to this from calling the perimeter estimator directly which seems to make the measurements closer to expected.

**Comment by cookpa** [comment]
Thanks Nick, this looks better. From the paper, it seems it tries to fit a continuous surface model to the object, to reduce error from aliasing . For my cube image, it reports an area of 3395.34 mm^2 now. If it's positioning the surface at the voxel center, then the true extent of an N-voxel cube is (N-1) voxels, so the ground truth surface area would be 6 * 24^2 = 3456 mm^2. But allowing for some smoothness at the corners, I can see how it would be off by some small amount. But it seems more reasonable.

It seems to make much less difference in brain data. 

Old area:    11234.7    
New area:  10872.4    

Image

https://dl.dropboxusercontent.com/u/20389729/roiMasked.nii.gz

**Comment by ntustison** [comment]
It does a really good job of preventing biased results vs. building a surface and computing the resulting area.  

Compare [this](https://github.com/ntustison/KapowskiChronicles/blob/master/analytics2/LabelThicknessComparison/labelThickness.pdf) with [this](https://github.com/ntustison/KapowskiChronicles/blob/master/analytics2/LabelThicknessComparison/labelThickness2.pdf).

Need to get on the plane but we can talk more tomorrow.  Also, remind me that I want to ask you about a DTI package.
