### ISSUE TITLE
Version Number Incorrect?

### ISSUE THREAD

**Issue by spinicist** [ANTsX/ANTs#443]
Hi,

I just did:

```
git pull
git checkout v2.2.0
```

Git status reports:
```
HEAD detached at v2.2.0
nothing to commit, working directory clean
```

And the exact commit pointed to is 0740f91. Rebuilding in another directory, I get:

```-- Building ANTS version "2.1.0.post789-g0740f"```

In the middle of the output. I assume it should actually say Building ANTS version "2.2.0"?

(This is an incredibly minor problem but I thought you'd like to know)

**Comment by gdevenyi** [comment]
Fixed
