### ISSUE TITLE
Ants for MRtrix3

### ISSUE THREAD

**Issue by LucSam** [ANTsX/ANTs#474]
Hi there, thanks for providing ANTs.

My problem after installation like described [here](https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/) is that I can't call ANTs or ANTs commands.
I want to use it within MRtrix3, where I get the message "Could not find ANTS program N4BiasFieldCorrection".

How can I export the ANTs directory, so I can call the commands via a bash shell? I've read [this](http://www.tech-recipes.com/rx/2621/os_x_change_path_environment_variable/) and [this as well](https://sourceforge.net/p/advants/discussion/840261/thread/18f0a686/).

Within the ANTs directory I can't seem to find a .profile file.
I'm working with Mac OS Sierra 10.12.5. 

I appreciate any help, thanks, Luc

**Comment by ntustison** [comment]
Let's assume that your ANTs directory is 

```
/Users/LucSam/ANTs/
```
After compiling ANTs you need to add the following lines to your ``.profile`` file:

```
PATH=${PATH}:/Users/LucSam/ANTs/bin/bin/

export ANTSPATH=/Users/LucSam/ANTs/bin/bin/
```

If it doesn't exist then you need to create it in ``/Users/LucSam/``.

**Comment by LucSam** [comment]
Thank you very much, that worked now. Could you update this [here](https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/)?
Probably someone else struggles with that...
Thanks again, best, L
