### ISSUE TITLE
Oblique individual images for custom template construction

### ISSUE THREAD

**Issue by younghoo** [ANTsX/ANTs#487]
Hi, I would like to build a custom T1 brain template and I find that the original individual T1 images are oblique (these brains are tilted at certain degrees) when viewed in common image viewers. My questions: (1) Oblique individual images will affect the final output? (2) There is a need to deoblique images before the ANTs process?  Or there is a tool in ANTs to deoblique them? Many thanks!

**Comment by stnava** [comment]
1. custom templates are data-driven:  so, yes, the input will impact the
output

2.  no need to de-oblique, in general.  you can control the orientation by
setting -y 0 and passing an initial template with your desired orientation
via the -z option


brian
