### ISSUE TITLE
incompatible between ANTs and mrTools?

### ISSUE THREAD

**Issue by Heeseung08** [ANTsX/ANTs#492]
Dear ANTs providers,

We have a problem in normalizing individual subject's functional image into the subjects averaged template image. 

We implemented coregistration between functional data and T1 image by using mrTools (http://gru.stanford.edu/doku.php/mrTools/overview). 
Then, we applied warping matrix to the functional data to warp it to subjects averaged template image by using "antsApplyTransforms".
The code we used is as follows.
`antsApplyTransforms -r Ref.nii -i ua.nii -o wua.nii -t brain5Warp.nii.gz -t brain5Affine.txt -e 3 -v 1 --float`

The template images were made by using T1 images and the warping matrix was obtained during generating template image.
But, we found that functional image did not match to the template, even though we confirmed that the functional data was aligned with the T1.
However, when we implemented coregistration by using SPM12, instead of mrTools, the functional data was successfully aligned with the template.

When we investigated .hdr information of the two functional images, one of them is obtained by using mrTools and the other from SPM12, they were rather different especially in the 'qoffset_z' (-56.2731 in mrTools, -35.4935 in SPM12) and originator ([42, 39, 20, 0, -32768] in mrTools, [41, 38, 19, 186, 32764] in SPM12). 
However, the alignment of the two functional images was highly similar, when we checked by using SPM>Check Reg.

I am sorry that I have a little knowledge in the header information. 
So, I don't know why this highly aligned two functional images were warped too differently, even though same warping matrix was applied.
Please help us....

Thanks for your help in advance!
HL

**Comment by ntustison** [comment]
This is a well known [problem](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F)---the header information isn't handled consistently between packages.

**Comment by Heeseung08** [comment]
Oh. now it is cleared. Very thanks!

**Comment by Heeseung08** [comment]
Is there any way to make the functional image from mrTools compatible with ANTs via ANTs function?

**Comment by ntustison** [comment]
Perhaps but we don't have any experience with mrTools.  You might want to ask over at the nipype forum where the developers have to deal with these interfacing issues.
