### ISSUE TITLE
Blank/black priors?

### ISSUE THREAD

**Issue by bth22** [ANTsX/ANTs#493]
Hi, 

So I ran the cook template priors script successfully, and no errors popped up, but for the priors files (prior1.nii.gz etc.) themselves, they all show up blank in afni or freeview.  They seem to have no dimension in the inferior to superior direction according to afni's 3dinfo.  I'm pretty inexperienced though, it might just be my misunderstanding of the purpose of these files.  I will attach the script I used which is a modified version of the cookpriors example script to fit with the data our lab is using.  

Thank you,
Taylor H.

[cook_final.txt](https://github.com/ANTsX/ANTs/files/1267289/cook_final.txt)

**Comment by ntustison** [comment]
The example script is 2-D as are the input files used for that example.  I'm guessing that your template is 3-D.

**Comment by bth22** [comment]
Ah duh, thanks Nick.  I left in a 2 for the ThresholdImage command.

**Comment by ntustison** [comment]
I also see ``-d 2`` on the ``antsJointLabelFusion.sh`` command.

**Comment by bth22** [comment]
Yes, saw that as well, thanks!
