### ISSUE TITLE
Slow registrations using example code, multiple transform files generated

### ISSUE THREAD

**Issue by jmschabdach** [ANTsX/ANTs#494]
I've been running affine and SyN transforms using the parameters outlined in all the ANTs registration examples that I've seen, and I'm encountering a few issues. The registrations are set up using nipype (see their [example](http://nipy.org/nipype/interfaces/generated/nipype.interfaces.ants.registration.html)), but I've been able to replicate them using the output of nipype's 'reg.cmdline()' function. These issues are consistent across 3 computers, all running Ubuntu, with the same nipype and numpy versions (0.12.1 and 1.12.1, respectively). 

1) When I try to run an ['Affine', 'SyN'] registration on a pair of 3D images, the registration never finishes. Usually I end up killing the process after 2+ days. When I run ['Affine'] followed by ['SyN'] for the same pair of 3D images, the registration finishes in 3 hours or less. Is this significant delay normal? If not, do you have any suggestions on how I can fix it?

2) Since the ['Affine', 'SyN'] registration takes so long, I normally run an ['Affine'] registration followed by an ['SyN'] registration. In the last few weeks, I've realized that the ['SyN'] registration sometimes produces an 'output_0Warp.nii.gz' file, but sometimes it produces 'output_0GenericAffine.mat' and 'output_1Warp.nii.gz'. The unknown number of output files is a problem for what I'm doing as I use the 'Warp.nii.gz' file to initialize the next registration between a different pair of images. Is there any way to force the ['SyN'] registration to not run a hidden ['Affine'] registration before running the specified ['SyN'] registration? Or is this type of issue supposed to be addressed by running a combined ['Affine', 'SyN'] registration?

3) Because of the multiple files produced by the ['SyN'] registration, I'm debugging my pipeline using just the ['Affine'] registration. Without changing any of the parameters in my original code (which took 3 hours max to run an ['Affine'] registration followed by a ['SyN'] registration), the ['Affine'] registration suddenly takes hours rather than seconds. I've tried reducing the number of iterations per level from the 1500x200 in the examples to 500x20, but it still takes much longer than it used to. Do you know if there were any updates recently that could have affected this runtime? If not, do you have any suggestions for debugging it?

Any help you can offer would be greatly appreciated.

Thanks,
Jenna

**Comment by ntustison** [comment]
When you say that you are "replicating [the registrations]", is this completely outside the nipype environment with a recent pull and build directly from the ANTs GitHub repo?

**Comment by jmschabdach** [comment]
Yes, this is outside the nipype environment. Two computers have a pull/build from May 8, 2017 and the third has a pull/build from August 15, 2017.

**Comment by ntustison** [comment]
Great.  

Were they built in ``Release`` mode?

**Comment by jmschabdach** [comment]
They were built following the instructions on Brian Avants' [website](https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/), so they were built using the default option from the github. I cannot guarantee that they were or were not built in `Release` mode.

**Comment by ntustison** [comment]
Do you have sufficient permissions w.r.t. those computers such that you can rebuild, if necessary?

**Comment by jmschabdach** [comment]
Yes, I do.

**Comment by ntustison** [comment]
Okay great.  Navigate to the ANTs binary directory and type

```
$ ccmake .
```

You should see something like the following:

![screen shot 2017-08-31 at 9 35 24 am](https://user-images.githubusercontent.com/324811/29934374-c26478c8-8e2f-11e7-9ded-5a318f6b0c06.png)

Make sure that the variable ``CMAKE_BUILD_TYPE`` is set to ``Release``.

**Comment by jmschabdach** [comment]
Yes, `CMAKE_BUILD_TYPE` is set to `Release`

**Comment by ntustison** [comment]
Then it's difficult to say as there's been no major changes that would affect timing.  Do you have any more specific information as to when the differences were noticed?

**Comment by jmschabdach** [comment]
I believe they started around Monday of this week. I ran 2 registrations this afternoon to try to get more information for you regarding the amount of time each registration takes. Here's the commands run and the amount of time each one took: 

`$ time antsRegistration --collapse-output-transforms 1 --dimensionality 3 --initialize-transforms-per-stage 0 --interpolation NearestNeighbor --output [ /path/to/transform/output_, /path/to/registered/img/registered.nii.gz ] --transform SyN[ 0.25, 3.0, 0.0 ] --metric CC[ /path/to/fixed.nii.gz, /path/to/moving.nii.gz, 1, 32 ] --convergence [ 100x50x30, 1e-08, 20 ] --smoothing-sigmas 2.0x1.0x0.0vox --shrink-factors 3x2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --winsorize-image-intensities [ 0.0, 1.0 ]  --write-composite-transform 0

real    22m27.589s
user    85m46.704s
sys     0m3.220s


$ time antsRegistration --collapse-output-transforms 1 --dimensionality 3 --initialize-transforms-per-stage 0 --interpolation NearestNeighbor --output /path/to/transform/output_ --transform Affine[ 2.0 ] --metric CC[ /path/to/fixed.nii.gz, /path/to/moving.nii.gz, 1, 32, Random, 0.05 ] --convergence [ 500x20, 0.01, 20 ] --smoothing-sigmas 2.0x1.0vox --shrink-factors 2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --winsorize-image-intensities [ 0.0, 1.0 ]  --write-composite-transform 0

real    109m45.990s
user    784m37.108s
sys     57m24.756s`

Do these times seem consistent with what you would expect? The amount of time required for the affine transform is concerning to me.

**Comment by ntustison** [comment]
THe radius value on your CC metric is probably the culprit.  I'm guessing you changed it from MI where a value of 32 for that parameter spot is more typical.

**Comment by jmschabdach** [comment]
Ah, gotcha. Just ran an affine transformation and that seems to have solved my timing issue so far. Do you have any suggestions for my second question about the hidden affine transform?

**Comment by ntustison** [comment]
There's no hidden affine transform.  If you specify an initial transform with a single SyN stage, then you'll still get an affine transform file describing that initial transform.

**Comment by jmschabdach** [comment]
Hmm. Can you explain more about what initial transform the affine transform file will describe? I thought the SyN transforms were written as .nii.gz files (or .h5 files if composite outputs is specified)?

**Comment by ntustison** [comment]
See the ``-r`` option in the ``antsRegistration`` help menu.

**Comment by jmschabdach** [comment]
I think this has resolved the problems I was having. Before I close this issue, I have one more question.

Let's say I register image B to image A and ANTs saves "output_0Affine.mat" and "output_1Warp.nii.gz". Next I want to register image C to image A, and I tell ANTs to use "output_0Affine.mat" as the initial transform. ANTs then saves "output_1Affine.mat" and "output_2Warp.nii.gz". Is the change in number following the underscore only due to the use of an initial transform file?

**Comment by ntustison** [comment]
Yes.

**Comment by jmschabdach** [comment]
Great, thanks for all your help!
