### ISSUE TITLE
problem installing ants vtkSampleFunction.h missing

### ISSUE THREAD

**Issue by pdeman** [ANTsX/ANTs#496]
Hi,

I have a problem installing ants on a ubuntu 16.04.

I have this error:
ANTs/Examples/antsVol.cxx:22:31: fatal error: vtkSampleFunction.h: No such file or directory
compilation terminated.
Examples/CMakeFiles/l_antsVol.dir/build.make:62: recipe for target 'Examples/CMakeFiles/l_antsVol.dir/antsVol.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/l_antsVol.dir/antsVol.cxx.o] Error 1
CMakeFiles/Makefile2:699: recipe for target 'Examples/CMakeFiles/l_antsVol.dir/all' failed
make[4]: *** [Examples/CMakeFiles/l_antsVol.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....

If I do locate vtkSampleFunction, I find it in my vtk installation:
"/home/lnppeeg/software/vtk/Imaging/Hybrid/vtkSampleFunction.h"

which is the one specified in ANTs cmake
et VTK_DIR=/home/lnppeeg/software/vtk/build
(in the folder build I did "cmake .." to install vtk).

Any idea how to solve this installation problem ?

Regards

**Comment by ntustison** [comment]
Did you try to build from a brand new repo clone?

**Comment by pdeman** [comment]
hi,
sorry for the delay.
Yes it was from a brand new repo clone.
