### ISSUE TITLE
I download the pre-compile file for Mac OS and I get a bin folder. But what is the net step to install the ANTs.

### ISSUE THREAD

**Issue by Thatfreesky** [ANTsX/ANTs#499]
I download the pre-compile file for Mac OS and I get a bin folder. But what is the net step to install the ANTs.

**Comment by ntustison** [comment]
Start from [here](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#copy-scripts).

**Comment by yarikoptic** [comment]
I think this issue could be closed

**Comment by cookpa** [comment]
Agreed @yarikoptic
