### ISSUE TITLE
Weird Registration Offset [minimal example included]

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#500]
Recently, I have started getting a very strange registration offset for my structural images. The structural images seem to be aligned and scaled properly, but they are offset a bit rostrally and a notable amount dorsally of the template. I am doing this with very many images, and afaict the offset is the same. I only noticed this recently but it happens on all my machines running a series of live ANTs versions, last updated over the past 1-2 months. I updated ANTs to the newest commit from GitHub just now, and I can confirm this is till happening.

To reproduce, download the [minimal example](http://chymera.eu/debug/ANTs/offset.zip), and run:

```
unzip offset.zip
cd offset
bash command.txt
```

I have tried changing many of the parameters, and though I could deteriorate the quality of the registration, nothing was able to reduce this offset. Apparently this issue happens at the first manipulation (`Rigid`).

Below a picture of what my issue looks like. Included in the archive you will also find the output obtained on my machine - exemplifying the issue.

![screenshot from 2017-10-01 13-40-27](https://user-images.githubusercontent.com/950524/31054220-5e2ba934-a6ae-11e7-8b65-a18e4aa4a930.png)

**Comment by ntustison** [comment]
I loaded both images (fixed.nii and warped.nii) in itk-snap and don't see an offset.  ITK-snap is consistent with how ANTs uses header information.  The same cannot be said of other tools.

**Comment by TheChymera** [comment]
Via `fslhd`:

* Header for the template:
```
sizeof_hdr     348
data_type      FLOAT32
dim0           3
dim1           63
dim2           96
dim3           48
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     Unknown
datatype       16
nbyper         4
bitpix         32
pixdim0        0.000000
pixdim1        0.200000
pixdim2        0.200000
pixdim3        0.200000
pixdim4        0.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Aligned Anat
qform_code     2
qto_xyz:1      -0.200000  -0.000000  -0.000000  6.270000
qto_xyz:2      0.000000  0.200000  -0.000000  -10.700000
qto_xyz:3      -0.000000  0.000000  0.200000  -7.900000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Right-to-Left
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Scanner Anat
sform_code     1
sto_xyz:1      -0.200000  -0.000000  0.000000  6.270000
sto_xyz:2      -0.000000  0.200000  -0.000000  -10.700000
sto_xyz:3      0.000000  0.000000  0.200000  -7.900000
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Right-to-Left
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip        
aux_file       
```

* Header for the warped image:
```
sizeof_hdr     348
data_type      FLOAT32
dim0           3
dim1           63
dim2           96
dim3           48
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     Unknown
datatype       16
nbyper         4
bitpix         32
pixdim0        0.000000
pixdim1        0.200000
pixdim2        0.200000
pixdim3        0.200000
pixdim4        0.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      -0.200000  -0.000000  -0.000000  6.270000
qto_xyz:2      0.000000  0.200000  -0.000000  -10.700000
qto_xyz:3      -0.000000  0.000000  0.200000  -7.900000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Right-to-Left
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Unknown
sform_code     0
sto_xyz:1      0.000000  0.000000  0.000000  0.000000
sto_xyz:2      0.000000  0.000000  0.000000  0.000000
sto_xyz:3      0.000000  0.000000  0.000000  0.000000
sto_xyz:4      0.000000  0.000000  0.000000  0.000000
sform_xorient  Unknown
sform_yorient  Unknown
sform_zorient  Unknown
file_type      NIFTI-1+
file_code      1
descrip        
aux_file       
```

It seems ANTs is not setting the `sform`, which somehow makes MRIcroGL set the origin incorrectly. Other than also addressing this issue on the MRIcroGL side (@neurolabusc) - is there a way to tell ANTs to set the `sform` as well as the `qform`?

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

**Comment by TheChymera** [comment]
> When writing NIFTI output, the sform is overwritten with values that match the qform.

@ntustison but in the example at hand clearly this is not happening, The `sform` of the output is different both from the `qform` of the output and both the `sform` and `qform` of the template.

**Comment by cookpa** [comment]
Thanks for including the example. It sounds like something unusual is happening.

There might not be much I can do if it's an ITK issue, but I will take a look and try to see what's going on tomorrow.

On Oct 1, 2017, at 2:58 PM, Horea Christian <notifications@github.com<mailto:notifications@github.com>> wrote:


When writing NIFTI output, the sform is overwritten with values that match the qform.

@ntustison<https://github.com/ntustison> but in the example at hand clearly this is not happening, The sform of the output is different both from the qform of the output and both the sform and qform of the template.

**Comment by ntustison** [comment]
@TheChymera  All IO is handled by ITK so, if it's a bug as opposed to software incompatibility, you'll have to bring it up with them.  You might want to simplify your example to something where you simply read and write an image to and from disk.

**Comment by ntustison** [comment]
Thanks Chris.  Adding your comment to the wiki [page](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F).

**Comment by neurolabusc** [comment]
Fine, I would omit the second paragraph `However, in the example you provided...` as it is specific to this case and follows from the comment `gives precedence to`.  I also do not think you need to attribute this comment to me, I believe this is common knowledge: 

> Note that in cases where both an SForm and QForm are present, ITK gives precedence to the QForm while SPM/MRIcroGL/FSLeyes/Mango give precedence to the SForm. The rationale for the SPM approach is clear: QForms were designed to provide an idea of native space, while the SForm could provide the user an easy way to provide a starting estimate. When informed of this difference the ITK group elected to keep their method to ensure backward compatibility. To support both conventions, recent versions of SPM change both the SForm as well as QForm when the user changes the origin with the "Display" button. While the original intent of the SForm and QForm was to provide a method to encode both native scanner as well as some losslessly re-oriented coordinates, the differences in implementations supports SPM's method of using the same value for both to ensure consistent display and processing.

To verify this, here is an image that looks correct if you use the Q-Form, but where the AP and LR dimensions were swapped in the S-Form:

[s_q_conflict.nii.gz](https://github.com/ANTsX/ANTs/files/1349411/s_q_conflict.nii.gz)

It looks fine with itk-SNAP, but wrong with SPM, FSLeyes, Mango and MRIcroGL. Note that in this example, the QForm is listed as 'Scanner Position' while the SForm is 'Coregistration'. With Mango, it will use the QForm if both are listed as "Scanner Position" (which makes sense, as the QForm was designed for native space). On the other hand, the other tools stick with their preferred orientation as long as it is available.

**Comment by cookpa** [comment]
I reproduced the error with the current ANTs - but this behavior is new. I have an older version of the code from June and it does the expected thing of overwriting sform with the qform rigid transform.

**Comment by ntustison** [comment]
@neurolabusc [Changed](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F).

**Comment by cookpa** [comment]
Yes, it looks like there was a change to remove ambiguity by setting 

```
    qform_code = 1
    qform_code_name = NIFTI_XFORM_SCANNER_ANAT

    sform_code = 0
    sform_code_name = NIFTI_XFORM_UNKNOWN
```

and setting the sform transform to all zeros. See

https://github.com/InsightSoftwareConsortium/ITK/commit/0cf3570be3adb8ee4f9262da67e52aaf38018723#diff-614c78fa46f6db4dd982f8504c665901

by @hjmjohnson 

The fixed and warped images can have different sforms - which was always the case, but prior to this update, the qform and sform were set to identical transforms in the warped output, so this might have gone unnoticed.
