### ISSUE TITLE
Overflow error maybe?

### ISSUE THREAD

**Issue by david-hoffman** [ANTsX/ANTs#503]
I'm running `antsRegistrationSyNQuick.sh` on some large data (10 GB for moving image and 3.4 GB for the fixed image) and I run into the following error:

    itk::ExceptionObject (0x501d980)
    Location: "unknown"                                                               
    File: /home/hoffmand/bin/ants/ITKv4-install/include/ITK-4.12/itkImageMomentsCalculator.hxx                                                                          
    Line: 156
    Description: itk::ERROR: ImageMomentsCalculator(0x501ca90): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.

If I down sample the moving image by 2 in each dimension (there are 3) then everything runs without error.

**Comment by ntustison** [comment]
I'm guessing you're right.  You might want to check it by looking specifically at that [class](https://itk.org/Doxygen/html/classitk_1_1ImageMomentsCalculator.html).

**Comment by david-hoffman** [comment]
I don’t know much about C++ but it looks like this is a template only and I’m not sure how its implemented in ANTs. It looks like the image weight is typed as “double” internally, but I’m not sure if this is overloaded in ANTs somewhere.

I did try converting the data to float explicitly and then running the same command, but it failed in the same way. So maybe its some other type of error.

**Comment by ntustison** [comment]
Alright, in that case let’s work towards a work-around.  That moments calculator is used for determining the initial translation transform.  You don’t need your big image to determine that.  Are you able to use the antsRegistration program outside the wrapper scripts?

**Comment by cookpa** [comment]
Are you using '- p f' with the script call? You want to tell ANTs to use float internally. I don't think changing the images on disk will change the internal precision.

**Comment by david-hoffman** [comment]
@ntustison I made a feeble attempt at using `antsRegistration` directly, I can take another look at that.

@cookpa I didn't use `-p f` because I initially thought (incorrectly) that it was an integer overflow problem so I wanted to try any type of floating point format, I didn't really care about percision. I have started to run into some segfaults that I think are due to too much memory consumption so the `-p f` option will be useful for that.

**Comment by ntustison** [comment]
When you run ``antsRegistrationSyNQuick.sh`` the corresponding command line call is printed to the screen.  You might want to use the wrapper script for running the linear part using the downsampled image (i.e., `-t a`).  You can then use that initial transform for a subsequent call to ``antsRegistrationSyNQuick.sh`` for -i option and only doing the deformable part (e.g., ``-t so``).
