### ISSUE TITLE
antsCorticalThickness and atypical brains

### ISSUE THREAD

**Issue by mgxd** [ANTsX/ANTs#506]
Hi there,

I've been trying to run some brains with lesions / strokes through `antsCorticalThickness.sh`, and would like some suggestions. I have some manually-made lesion masks available, but so far have only used the `OASIS-30 Atropos template` [provided by mindboggle](http://www.mindboggle.info/data.html). 

What would be the best way to improve the segmentation of the structural data?

Thanks!

**Comment by gdevenyi** [comment]
Try using:
```
$ LesionFilling 
Example usage: LesionFilling imageDimension T1_image.nii.gz lesion_mask.nii.gz output_lesion_filled.nii.gz
```

First before the cortical thickness.

**Comment by mgxd** [comment]
@gdevenyi thanks for the tip, I'll try it out a bit later and report back

**Comment by stnava** [comment]
yes - or you might follow some of the strategies used here:

https://github.com/dorianps/LINDA


brian


On Tue, Oct 10, 2017 at 1:18 PM, Mathias Goncalves <notifications@github.com

**Comment by dorianps** [comment]
LINDA is used only to identify the lesion, which you don't need if you have
the manual segmentation.

Not sure what LesionFilling does (or if it alters the healthy voxels at
all) but JointIntensityFusion is another, perhaps better, alternative to
fill lesions. In my experience the fillings I get with JIF are
imperceptible.

This said, the approach to get thickness in stroke might be roughly like
this:

1. Register your subject in template (the template you will use for ACT).
2. Bring the lesion in template space.
3. Edit the six priors of the template to add the lesion as a seventh prior.
3.a. Smooth your lesion mask a bit, subtract if from the other 6, make sure
that the ratios of the other priors are not changed and all sums to 1.
Example, if a voxel has predefined priors of  0.5 GM and 0.5 WM, and your
lesion there has value of 0.8 after smoothing, after integrating the lesion
as a prior you will have values 0.8 lesion, 0.1 GM, 0.1 WM.
4. Run ACT and point to your customized priors. Tell ACT that your 7th
prior is considered white matter with "-c WM[7]".

This process will produce a thickness map with no data in the area of the
lesion, here are some examples:

[image: Inline image 1]



Dorian
