### ISSUE TITLE
longitudinalJointLabelFusion.sh parameters and usage clarification

### ISSUE THREAD

**Issue by dkrozelle** [ANTsX/ANTs#512]
Hi all, as a follow up to a thread I started on the [sourceforge help board](https://sourceforge.net/p/advants/discussion/840261/thread/83b39e80/), I was hoping to get a little insight into parameter usage for the [longJLF script](https://github.com/ANTsX/ANTs/blob/master/Scripts/antsLongitudinalJointLabelFusion.sh) and @ntustison  mentioned @jeffduda might be of some help.

It appears longitudinal timepoints can be passed to longJLF via two methods: appending a list of `<images>` or via the `-b: Timepoint directory parameter`. How are these differentiated, and what purpose does the `-b` method serve? 

Also, is this script able to be run without having already run the longCT to obtain a SST? I assume it'll save the time of generating a SST for a second time if I'm going to eventually run both, just trying to determine the logical order to process subjects. Any suggestions would be greatly appreciated.

```
$ antsLongitudinalJointLabelFusion.sh -h
Usage:
antsLongitudinalJointLabelFusion.sh -d ImageDimension -o OutputPrefix <other options> <images>

Example Case:
antsLongitudinalJointLabelFusion.sh -d 3 -t target.nii.gz -o malf -p malfPosteriors%04d.nii.gz
                                  -g atlas1.nii.gz -l labels1.nii.gz               -g atlas2.nii.gz -l labels2.nii.gz

Example:
antsLongitudinalJointLabelFusion.sh -d 3 -t target.nii.gz -o malf \
              -p malfPosteriors%04d.nii.gz \
              -g atlas1.nii.gz -l labels1.nii.gz \
              -g atlas2.nii.gz -l labels2.nii.gz \
              -g atlas3.nii.gz -l labels3.nii.gz \
              -b timepoint_0_dir \
              -b timepoint_1_dir \
              -b timepoint_2_dir
```

**Comment by dkrozelle** [comment]
I've reviewed the code and I'll take a crack at elaborating on the usage... anyone that understands the process please correct any mistakes. Thanks! Not sure what's going on behind the scenes, but I'm more than happy to help with a PR to edit the usage.  

`
-t:  TargetImage:    <SST> Target image for registrations. For the longitudinal processing all time points are registered to the single subject template. Requires previous generation of SST by antsLongitudinalCorticalThickness.sh

-g/-l:  Atlas and Labels to be SyN warped to SST target image.

-b:  Timepoint directory: Single time point directory created by antsLongitudinalCorticalThickness.sh; the normalized extracted brain image with mask are transformed to SST space followed by JLF segmentation with warped atlases/labels.        
`

**Comment by ntustison** [comment]
Hey Dan.  Just learned that Jeff is on vacation so it might be a couple days.

**Comment by dkrozelle** [comment]
thanks for the update. I've started a few run trials and think I'm in a good place of understanding. I'd appreciate keeping this issue open until Jeff has a chance to chime in. Thanks!

**Comment by jeffduda** [comment]
It looks like you pretty much have it figured out. The example call in the
"Usage" section is incorrect (I'll fix that) as the use of the -b option is
the correct usage. These time-point directories are assumed to be the
output directories from antsLongitudinalCorticalThickness, but they will
work as long as they contain the following files:
*ExtractedBrain0N4.nii.gz
*BrainExtractionMask.nii.gz
*TemplateToSubject1GenericAffine.mat
*TemplateToSubject0Warp.nii.gz
where the *TemplateToSubject transforms map from the passed target image to
ExtractedBrain0N4.nii.gz image.

So the process that happens is:

1) All of the passed atlas images (passed via -g) are registered to the
target (here, an SST)
2) All corresponding labels (passed via -l) are warped into SST space
3) SST is labeled via JLF
4) For each time-point (passed via -b), all atlas images and labels are
transformed into the original time-point space by composing the
atlas-to-SST transforms with the SST-to-timepoint transforms, and then
these are used to perform JLF in the original time-point space.

Hopefully that's clear. I'll work on cleaning up the usage/documentation.
-jeff

**Comment by dkrozelle** [comment]
Thank you very much. I wasn't totally clear on the last step, but now that you spell it out it makes complete sense.
