### ISSUE TITLE
suggested: option to not run N4 in antsBrainExtraction.sh

### ISSUE THREAD

**Issue by chrisadamsonmcri** [ANTsX/ANTs#515]
Would it be possible to have an option to not run N4 in antsBrainExtraction.sh since I run it prior to skull stripping.

**Comment by ntustison** [comment]
You’re welcome to modify your own copy of antsBrainExtraction.  If there’s no degradation in performance, I’d rather not add additional options in the repo script to keep it as simple as possible.
