### ISSUE TITLE
How can I give a initial field when using ants to do registration?

### ISSUE THREAD

**Issue by Barnonewdm** [ANTsX/ANTs#516]
I do registration using this command: ./ANTS 3 -m PR[${fixedImage},${movingImage},1,2] -o ${outputName}_field.nii -r Gauss[2,0] -t SyN[0.5] -i 30x90x11 --use-Histogram-Matching

But I wanna give a initial field, really no idea.

**Comment by ntustison** [comment]
You should use ``antsRegistration`` which is an updated version of ``ANTS``.  With the former, you can specify an initial field (see ``-r`` option).

**Comment by Barnonewdm** [comment]
@ntustison but I cannot find the PR metric in antsRegistration. Is its name changed?

**Comment by ntustison** [comment]
It's basically ``CC``.

**Comment by Barnonewdm** [comment]
@ntustison  I found we can only input a initial transform to antsRegistration.  All I want is to give a initial field as the iterative start point.

**Comment by ntustison** [comment]
Then, no, we don't have those capabilities.

**Comment by Barnonewdm** [comment]
@ntustison Could u give me any suggestion on where and how to modify this?

**Comment by ntustison** [comment]
You probably don't want to modify ``antsRegistration`` as that would be extremely difficult and much too time-consuming for me.  However, you might want to start with the SyN-specific [test](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Registration/RegistrationMethodsv4/test/itkSyNImageRegistrationTest.cxx) from the ITK repo.

**Comment by cookpa** [comment]
Can't you pass a warp field to antsRegistration with `-r`? Something like:

```
antsRegistration -r initialWarp.nii.gz . . .
```

Assuming you have just a warp field, and `initialWarp.nii.gz` is what you would use to warp the moving to the fixed image with `antsApplyTransforms`.

If the original warp is itself generated from `antsRegistration`, it would usually have an affine component too, in which case you'd do:

```
antsRegistration -r initial1Warp.nii.gz -r initial0GenericAffine.mat  . . .
```

**Comment by ntustison** [comment]
@cookpa ---  I suggested this above but I got the impression that this wasn't what was requested.

**Comment by Barnonewdm** [comment]
@cookpa In my view, the r option only can get a initial transform but not a warp field. So I don't think this can work.

**Comment by cookpa** [comment]
I think we are not understanding the terms the same way.

A transform is an object that maps points in one image space into another. So `myTransform0GenericAffine.mat` and `myWarp.nii.gz` are both transforms.

As Nick and I have said above, you can use a warp field transform or an affine matrix transform or both as options to `antsRegistration` with `-r`. So for example, you could do:

```
antsRegistrationSyNQuick.sh -d 3 -f fixedImage.nii.gz -m movingImage.nii.gz -o output
```

which produces `output0GenericAffine.mat` and `output1Warp.nii.gz`. Then you can do

```
antsRegistration -d 3 -r output1Warp.nii.gz -r output0GenericAffine.mat -t SyN  . . . 
```

If this doesn't work for you, then something else is wrong. If you are running the current ANTs, the example above should definitely work.

But if your initial warp field comes from some other software, the warps may not be compatible. Other registration software use different conventions for describing warps.
