### ISSUE TITLE
installing in Win 10 with the Linux subsytem

### ISSUE THREAD

**Issue by newilson** [ANTsX/ANTs#517]
I successfully installed ANTs yesterday in a Linux machine following the instructions here:
 [https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#get-the-latest-code](url)

I am now trying to install on a Windows 10 machine following the instructions here:
[https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Windows-10](url)
which ultimately follow the same steps as in Linux once the subsystem is enabled.

I enabled the Linux Subsystem, installed git, installed CMake, and cloned ANTs. However, when I try to run CMake on ANTs, I get EMPTY CACHE.
![image](https://user-images.githubusercontent.com/20051861/32286088-bc726a48-bf02-11e7-869b-0c01fe6ee760.png)

![image](https://user-images.githubusercontent.com/20051861/32285766-b62a37de-bf01-11e7-96db-aa7aef09b6e8.png)

If I hit 'c', I get the following
![image](https://user-images.githubusercontent.com/20051861/32285883-0cbda374-bf02-11e7-8f4c-5fad3c19d331.png)

Any suggestions?

-Neil

**Comment by gdevenyi** [comment]
Does the linux subsystem even have a compiler? Looks like cmake can't find it.

I suggest you look into how to work with cmake in this system. This isn't an ANTs-specific problem.

**Comment by dorianps** [comment]
I have installed ANTs several times on WLS and g++ was always there on a
fresh install. Never saw the error above.

The instructions for ANTs installation in WLS are a little more detailed on
the ANTsR page (not that different though).

https://github.com/ANTsX/ANTsR/wiki/Installing-ANTsR-in-Windows-10-(along-with-FSL,-Rstudio,-Freesurfer,-etc)
.



On Wed, Nov 1, 2017 at 3:02 PM, Gabriel A. Devenyi <notifications@github.com

**Comment by cookpa** [comment]
@dorianps did I miss anything on the ANTs version? I tried to cut it down to the minimum for just installing ANTs.

@newilson, what Linux distribution did you install? Many of them come with compilers as standard, but to check, you can try

```
gcc -v
```

from the command line.

The specific error you get seems to be about writing a file. So I would check that the directory you're trying to build in is writeable and that the disk is not full.

**Comment by newilson** [comment]
Thanks for the quick replies.

@dorianps I do not notice anything obviously different in the ANTsR installation instructions, but of course, there is a lot more there.

@cookpa I installed the default distribution using lxrun (pre build 16215). It appears to be Ubuntu 14.04.5 LTS. gcc appears to be 4.8. I was also able to write a file to the directory using sudo.

![image](https://user-images.githubusercontent.com/20051861/32293771-97b4384a-bf1a-11e7-97be-9c975d301503.png)

Now when I try to run sudo ccmake ~/code/ANTs, I see the following
![image](https://user-images.githubusercontent.com/20051861/32294020-51fe440c-bf1b-11e7-9554-2c6fe4153229.png)

![image](https://user-images.githubusercontent.com/20051861/32294010-485ab728-bf1b-11e7-8307-a6165a3c8941.png)

**Comment by cookpa** [comment]
OK. It is not normal practice to need `sudo` - it suggests that your directory is not writeable by a normal user, which should not be the case. 

If gcc is on the PATH, then CMake should find it. But CMake can get confused when you try to recover from errors. Maybe starting over will help.

Make a directory that is owned by the user you are logged in as.

```
whoami
echo $HOME
```

Will tell you who you are and where your home directory is.

Then
```
cd $HOME
mkdir antsBuild
ls -ld antsBuild
```
This should make `antsBuild` in your home directory. The `ls -ld` command should show the directory owned by you with read, write and execute permissions. Test write a file
```
echo "test" > antsBuild/test.txt
ls antsBuild
```
If this is all good, try 
```
cd antsBuild
rm test.txt
ccmake /path/to/ANTs
```

**Comment by dorianps** [comment]
I installed ANTs in WLS about 6 weeks ago for the last time. My Ubuntu version is more recent:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.15063 Build 15063
```

@cookpa I don't think you missed anything, just wanted to make sure all the steps were identical. Once I used `cmake` instead of `ccmake` and things didn't work for me (3 years ago).

**Comment by newilson** [comment]
I ended up manually installing zlib `sudo apt-get install zlib1g-dev` (and also build-essentials, but I don't know if that made any difference) and ANTs seemed to install.
![image](https://user-images.githubusercontent.com/20051861/32304255-51c4dc70-bf44-11e7-899f-28633d2e859b.png)

However, the scripts and test data are missing.
![image](https://user-images.githubusercontent.com/20051861/32304449-a7c3f04c-bf45-11e7-95b3-b3a5f335e951.png)
![image](https://user-images.githubusercontent.com/20051861/32304465-ce21d2f4-bf45-11e7-9131-59d4bfd4d423.png)

**Comment by dorianps** [comment]
You need to manually copy them:
```
cp -R ${PWD}/../ANTs/Scripts/* $PWD/bin
```

**Comment by cookpa** [comment]
The build-essential package contains gcc, g++, and make, all definitely needed to build ANTs. I've added this to the Wiki page.

**Comment by newilson** [comment]
@dorianps You are correct. I don't remember having to do this for the Linux install, but maybe I did and forgot.

@cookpa I believe I already had gcc, g++, and make before installing build-essentials, but I guess it couldn't hurt.

Thanks for the help. I am closing the issue.
