### ISSUE TITLE
Memory and parallelization problems with antsMultivariateTemplateConstruction2.sh

### ISSUE THREAD

**Issue by amclarekelly** [ANTsX/ANTs#518]
Hi there,

I am trying to create a template from 10 rat brains. Their native resolution is 0.078 x 0.5 x 0.083mm, but I have augmented the voxel size by a factor of 10 so that it's 0.78 x 5 x 0.83mm. I have also manually reoriented the images.

I am trying to run antsMultivariateTemplateConstruction2.sh on our HPC which uses SLURM. The command is: antsMultivariateTemplateConstruction2.sh -d 3 -o template_20171107 -c 2 -j 12 -v 24 -r 1 *nii

I've had some help from our IT support, which I paste below - but I think the biggest issue is that I am running out of memory, even allotting 24GB. The error is below:
--------------------------------------------------------------------------------------
 Starting ANTS registration on max 12 cpucores. Iteration: 1 of 4
 Progress can be viewed in job*_0_metriclog.txt
--------------------------------------------------------------------------------------
Using max 12 parallel threads
Running sh ./job_00_r.sh
Running sh ./job_01_r.sh
Running sh ./job_02_r.sh
Running sh ./job_03_r.sh
Running sh ./job_04_r.sh
Running sh ./job_05_r.sh
Running sh ./job_06_r.sh
Running sh ./job_07_r.sh
Running sh ./job_08_r.sh
Running sh ./job_09_r.sh
slurmstepd: error: Job 105308 exceeded memory limit (23714100 > 23552000), being killed

I find this odd because I *think* the process was able to get further using the same command on my desktop mac (16GB RAM) before it crashed (but because it crashed, it don't have evidence of how far it got!).

A comment from IT was: If the code supported MPI parallelism, the next thing to try would be to
split the run over multiple nodes, so you would have multiples of 24GB of RAM available to the job. However, ANTS only seems to support threaded parallelism, so it is limited to a single node.

Any help would be very much appreciated.

Clare

**Comment by ntustison** [comment]
How big, in voxels, are the resampled images used as input to template construction?

**Comment by cookpa** [comment]
You appear to be using pexec and not slurm - that would increase memory consumption. If you submit 12 jobs to separate nodes each with one core (-c 5, no -j), it might work better.

I don't think it should be necessary to downsample the images.

**Comment by ntustison** [comment]
And ``-c 2 -j 12`` is not for use on the cluster.  That might be your problem.

**Comment by amclarekelly** [comment]
The images are 384 x 46 x 384 = 6782976
Too big??

With IT support, we were playing around with parameters that were working even though we don't actually have PEXEC.

I've just set it to run in serial, but it still seems to be hitting the RAM issue:
Running N4 for 3-dimensional images.

Mask not read.  Creating Otsu mask.
./job_5_0.sh: line 1:  1079 Killed                  /home/support/apps/apps/ants/ants-2.1.0-redhat/N4BiasFieldCorrection -d 3 -b [200] -c [50x50x40x30,0.00000001] -i anat_reordered_07.nii -o ./template_20171107template0anat_reordered_07.niiRepaired.nii.gz -r 0 -s 2
All_Command_lines_OK
Using single precision for computations.
=============================================================================
The composite transform comprises the following transforms (in order): 
  1. Center of mass alignment using fixed image: template_20171107template0.nii.gz and moving image: anat_reordered_07.nii (type = Euler3DTransform)
=============================================================================
  number of levels = 4
  number of levels = 4
  number of levels = 4
  fixed image: template_20171107template0.nii.gz
  moving image: ./template_20171107template0anat_reordered_07.niiRepaired.nii.gz
 file ./template_20171107template0anat_reordered_07.niiRepaired.nii.gz does not exist . 
./job_5_0.sh: line 2:  4393 Segmentation fault      /home/support/apps/apps/ants/ants-2.1.0-redhat/antsRegistration -d 3 --float 1 -u 1 -w [0.01,0.99] -z 1 -r [template_20171107template0.nii.gz,anat_reordered_07.nii,1] -t Rigid[0.1] -m MI[template_20171107template0.nii.gz,./template_20171107template0anat_reordered_07.niiRepaired.nii.gz,1,32,Regular,0.25] -c [1000x500x250x100,1e-8,10] -f 8x4x2x1 -s 4x2x1x0 -t Affine[0.1] -m MI[template_20171107template0.nii.gz,./template_20171107template0anat_reordered_07.niiRepaired.nii.gz,1,32,Regular,0.25] -c [1000x500x250x100,1e-8,10] -f 8x4x2x1 -s 4x2x1x0 -t SyN[0.1,3,0] -m CC[template_20171107template0.nii.gz,./template_20171107template0anat_reordered_07.niiRepaired.nii.gz,1,4] -c [100x100x70x20,1e-9,10] -f 6x4x2x1 -s 3x2x1x0 -o ./template_20171107anat_reordered_07.nii5
Using single precision for computations.
Input scalar image: ./template_20171107template0anat_reordered_07.niiRepaired.nii.gz
 file ./template_20171107template0anat_reordered_07.niiRepaired.nii.gz does not exist . 
Reference image: template_20171107template0.nii.gz
Transform file does not exist: ./template_20171107anat_reordered_07.nii50GenericAffine.mat
Can't read initial transform ./template_20171107anat_reordered_07.nii50GenericAffine.mat

Thanks for your help!

**Comment by amclarekelly** [comment]
Sorry, don't know why that font came out so big!

**Comment by ntustison** [comment]
Can you show the new command line?  Also, make sure you clean out completely the output directory before running the script again.

**Comment by amclarekelly** [comment]
antsMultivariateTemplateConstruction2.sh -d 3 -o template_20171107 -c 0 -v 24 -r 1 *nii

Yep I cleaned the directory completely before rerunning

**Comment by ntustison** [comment]
And what is ``-v 24``?  Please consult the help menu for clarifications on parameters.

**Comment by spinicist** [comment]
Hi,

How did you change the voxel sizes and what input format are you using? The following is only going to help if you used nifti and altered the wrong transform in the header.

I have seen the N4 step crash with hi-res pre-clin data because the N4 call in antsMTC2.sh has a hard-coded length scale that is appropriate for human heads. For rats/mice it’s 10x too large, so N4 tries to allocate 10^3 too much memory and dies.

I tend to run N4 manually beforehand to avoid this issue.

Toby

**Comment by amclarekelly** [comment]
Thanks for all your help. 

What worked, at first anyway, was to do the N4 step separately. The script no longer crashes.

Now what I'm running into is a not-same-space issue that I've seen posted about before. I've tried most of the fixes mentioned - specifically, I have done  a rigid-body registration of all the images to a single image, then entered only these rigid-registered, N4'ed images, which I output as double, not float, into the template creation script. My version of ANTS was only downloaded last week. I am getting this error:

Exception caught: 
itk::ExceptionObject (0x7ff991f71858)
Location: "unknown" 
File: /Users/mac/Downloads/ants-binaries/ITKv4-install/include/ITK-4.7/itkImageToImageFilter.hxx
Line: 248
Description: itk::ERROR: ImageToImageFilter(0x7ff991f6a840): Inputs do not occupy the same physical space! 
InputImage Origin: [-1.5460938e+01, 1.7374999e+01, -1.6000000e+01], InputImage_1 Origin: [-1.5460938e+01, 1.7375000e+01, -1.6000000e+01]
        Tolerance: 1.5625000e-07

Using single precision for computations.
Input scalar image: anat_reordered_N4_11to01.nii
Reference image: template_20171107template0.nii.gz
Transform file does not exist: ./template_20171107anat_reordered_N4_11to01.nii90GenericAffine.mat
Can't read initial transform ./template_20171107anat_reordered_N4_11to01.nii90GenericAffine.mat
ls: template_20171107*Warp.nii.gz: No such file or directory
ls: template_20171107*GenericAffine.mat: No such file or directory
shapeupdatetotemplate()

Any thoughts? Should I start a new issue thread?

ps. I don't have a -c 5 option for antsMultivariateTemplateConstruction2.sh

**Comment by ntustison** [comment]
Did you try ``CopyImageHeaderInformation``?

**Comment by amclarekelly** [comment]
Nope, will do that and let you know! Thanks for your patience.

**Comment by amclarekelly** [comment]
Thank you - that worked and the result is fantastic. Thanks for your patience.
