### ISSUE TITLE
Latest ADNI template for the antsCorticalThickness

### ISSUE THREAD

**Issue by aghayoor** [ANTsX/ANTs#525]
Hi Brian and Nick,

Brian @stnava I really enjoyed your last week presentation. As our conversation, you mentioned about an ADNI template with priors that was used to generate the cortical thickness results.

I did not find this ADNI template on the ANTs brain template page [here](https://figshare.com/articles/ANTs_ANTsR_Brain_Templates/915436).

However, I found this [google drive link](https://drive.google.com/drive/u/0/folders/0B4SvObeEfaRyaUlYZ1VueFlCSkU), but  I am not sure if it is the template that you were talking about as this template was generated based on 52 ADNI data, and it was referred on a post from 2015.

Nick @ntustison , Brian told me you might know where the latest ADNI template is located. Could you please direct me to this template, if it is not the one in the above google drive link.

Thank you,
Ali

**Comment by ntustison** [comment]
The first rule of the ADNI template is:  You do not talk about the ADNI template.  The second rule of the ADNI template is:  You DO NOT TALK ABOUT THE ADNI TEMPLATE!  

:-)  

Send me a private email with Brian cc'd and I'll help you out.
