### ISSUE TITLE
Defining path in my environment

### ISSUE THREAD

**Issue by MarwaIsmail** [ANTsX/ANTs#530]
Hello experts,

I was trying to register some volumes to MNI space using antsRegistrationSyN script. I have set my ANTSPATH in both the script and the .bash_profile file. It however keeps on getting me his message:

antsRegistration program can't be found. Please (re)-define $ANTSPATH in your environment. 
What else should I do?

Thanks!
Marwa

**Comment by ntustison** [comment]
This is a windows environment, correct?

**Comment by MarwaIsmail** [comment]
No. I am running it on an hpc cluster that is Linux-operated.

**Comment by ntustison** [comment]
Great.  That makes it easier.   How are you doing it?

This is what I have in my .bash_profile.

```
ANTsPATH=$HOME/Pkg/ANTs/bin/bin/
export ANTsPATH
```

**Comment by MarwaIsmail** [comment]
Same here. I do it as:

ANTsPATH=$home/myfolder/Code/ANTs/bin/bin/
export ANTsPATH

**Comment by ntustison** [comment]
* Did you source it?  i.e., ``$ source .bash_profile``
* Also, more basically, did you copy all the scripts to the directory specified by $ANTsPATH?

**Comment by MarwaIsmail** [comment]
Sorry, I am not sure what sourcing means here.

Yes. I have all scripts located with binaries.

**Comment by ntustison** [comment]
http://lmgtfy.com/?q=what+is+sourcing+linux

**Comment by ntustison** [comment]
You basically need to specify that you made changes in your .bash_profile and "sourcing" your file tells the current shell to reflect those changes.

**Comment by MarwaIsmail** [comment]
Thanks for clarifying this. I did all of this and still get same error.

**Comment by ntustison** [comment]
Then I'm guessing it's a system problem.  You'll have to talk to somebody knowledgeable on your end regarding your set-up.

**Comment by caugolm** [comment]
You could try editing the script directly-- opening the antsRegistrationSyN.sh in the text editor of your choice, going down to about line 29 and un-commenting the line: 

export ANTSPATH=${ANTSPATH:="$HOME/bin/ants/"} 

and then replacing the "$HOME/bin/ants/" to the path to your build.

**Comment by MarwaIsmail** [comment]
This was first thing I did. No luck so far. 
Thank you

**Comment by MarwaIsmail** [comment]
Could you clarify which scripts should be included with the binaries? In "antsRegistrationSyN", it is looking for antsRegistration program 

ANTS=${ANTSPATH}/antsRegistration.

This is where it gets stuck. Is this a c++ script? In binaries path, I included only shell scripts which don't have a file with such name.

Thanks

**Comment by ntustison** [comment]
``antsRegistration`` is a program that should be in your binary directory after you compile ANTs.  Did you follow the [instructions](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS)?

**Comment by MarwaIsmail** [comment]
Oh. I didn't compile ANTs. I was working with a pre-compiled version on linux.

I have also tried running it on windows using Cygwin using this version here https://github.com/ANTsX/ANTs/releases    (ANTs_2.1.0_Windws.zip)

Looks like I am doing something wrong here.

**Comment by MarwaIsmail** [comment]
Does this mean I can't work with any pre-built versions? Please clarify so I could move to the next step

**Comment by bkandel** [comment]
If you have a pre-built version, antsRegistration should have been included
in the binaries you received. If you look in the directory with the
binaries, what do you see?

2017-12-15 19:38 GMT-05:00 MarwaIsmail <notifications@github.com>:
