### ISSUE TITLE
segmentation using antsAtroposN4.sh

### ISSUE THREAD

**Issue by younghoo** [ANTsX/ANTs#533]
Hi, I try to segment the T1 image into different tissues using ANTs, which includes 3 steps: (1) brain extraction using antsBrainExtraction.sh, (2) register OASIS (skull-striped) template and tissue priors to my (skull-striped) T1 image using antsRegistrationSyN.sh, (3) using antsAtroposN4.sh for segmentation. 

However, the segmentation totally failed and the command I use is:
bash ${ANTSPATH}/antsAtroposN4.sh \
  -d 3 \
  -a ${DATA_DIR}/mprage.nii.gz \        ## with skull T1 image
  -x ${OUT_DIR}/mprageBrainExtractionMask.nii.gz \
  -p ${OUT_DIR}/priorWarped%d.nii.gz \  ## warped OASIS 6 tissue priors
  -c 6 \
  -y 2 \
  -y 3 \
  -y 4 \
  -y 5 \
  -y 6 \
  -w 0.25 \
  -o ${OUT_DIR}/test

So I tried only to segment the image into 3 tissues and include only 3 tissues priors, and the results are correct. I also tried antsCorticalThicknessStagesCommand.sh by running the first 3 stages and its results are perfect. I must use antsAtroposN4.sh in a wrong way and any help is appreciated.

Many thanks!

**Comment by cookpa** [comment]
If you save the standard output from antsCorticalThickness, you can search it for antsAtroposN4.sh. It will print the exact command line that was run. Since that works, you might be able to use it to figure out how to run antsAtroposN4.sh independently.

**Comment by younghoo** [comment]
@cookpa I finally found that the failure of 6-class tissue segmentation was simply due to a typo in tissue priors. In other words, 3-class segmentation will succeed even if no priors are available, while 6-class segmentation will not. It seems that no errors will be reported, even if 
the prior files could not be found. Thank your for your help and time due to my carelessness.

**Comment by yuki-hoo** [comment]
> Hi, I try to segment the T1 image into different tissues using ANTs, which includes 3 steps: (1) brain extraction using antsBrainExtraction.sh, (2) register OASIS (skull-striped) template and tissue priors to my (skull-striped) T1 image using antsRegistrationSyN.sh, (3) using antsAtroposN4.sh for segmentation.
> 
> However, the segmentation totally failed and the command I use is: 
bash ${ANTSPATH}/antsAtroposN4.sh
-d 3
-a ${DATA_DIR}/mprage.nii.gz \ ## with skull T1 image
-x ${OUT_DIR}/mprageBrainExtractionMask.nii.gz
-p ${OUT_DIR}/priorWarped%d.nii.gz \ ## warped OASIS 6 tissue priors
-c 6
-y 2
-y 3
-y 4
-y 5
-y 6
-w 0.25
-o ${OUT_DIR}/test

I tried to segment the brain into 6 tissues. In the registration step, the template（https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436)  with the skull removed were aligned to the individual space, and the different tissue prior templates were converted to the individual space. and then we obtained 6 priorsWarped.nii.gz files.  Is the output right?
And in the segmentation step, how to get the file priorWarped%d.nii.gz?  How does this file relate to the 6 files obtained in the previous step？

Thanks so much!

**Comment by ntustison** [comment]
Please closely study the [corresponding 2-D example](https://github.com/ntustison/antsAtroposN4Example/) and make sure you can run it correctly.
