### ISSUE TITLE
ants registration matrix used by FSL

### ISSUE THREAD

**Issue by tli3** [ANTsX/ANTs#534]
Dear sir,
I am trying to convert the ants registration matrix (presumed to  be  in  binary format) to N+1 dimensional  transform  matrix  and offset which can be used by the software FSL. I use:
ConvertTransformFile 3 antsSubjectToTemplate0GenericAffine.mat subject2template.mat --hm
and then followed by fsl command:
flirt -in 1.nii.gz -ref template.nii.gz -out reg1.nii.gz -init subject2template.mat  -applyxfm 
But I found that the reg1.nii.gz and template.nii.gz are not at the same space.
while using 
antsApplyTransforms -d 3 --float 0 -i 1.nii.gz -r template.nii.gz -o reg1.nii.gz -n Gaussian -t antsSubjectToTemplate0GenericAffine.mat
will make reg1.nii.gz at the same space with template.nii.gz.
So the generated subject2template.mat cannot be used by FSL? how shall we make this. Could you please help me?

**Comment by ntustison** [comment]
``ConvertTransformFile`` is not used to convert ITK transform to fsl format.  You'd have to use something like ``c3d_affine_tool`` available [here](https://sourceforge.net/projects/c3d/).
