### ISSUE TITLE
Is it possible to set a background color value in antsRegistration ?

### ISSUE THREAD

**Issue by AlexandreLaborde** [ANTsX/ANTs#536]
Hello,

I’m a neuroscience researcher at the Champalimaud Foundation in Portugal and I have been using ANTs for image registration for a while now.

I am trying to register two 2-photon images of zebrafish brains and these images have the peculiarity of having the background level  higher then 0 , let me elaborate.

This images are 16bit grayscale tif stacks. 

When we acquire the images, we set some masks that with value 0 and we add 1000 to the signal to separate it from the masks. These 0 values are converted to NaNs during processing.

Is there any way that I can tell the registration scripts that everything bellow 1000 is background ?
Is it possible to feed to the registration some data format that supports NaNs like a .mat file ?
 
I know I could just go back to the images and subtract 1000 and then register them, the problem is that this is the test for a big dataset that we have and the amount of data I need to generate again to register the entire dataset is no feasible for me at the moment.

Thanks for this great tool that is ANTs!

All the best,
Alexandre

**Comment by ntustison** [comment]
> Is there any way that I can tell the registration scripts that everything bellow 1000 is background ?

There's no requirement that the background be a certain value.  CT images, for example, don't have a 0 intensity value for background.  Have you tried simply registering the data with the 1000 pixel values?

> Is it possible to feed to the registration some data format that supports NaNs like a .mat file ?

A wide range of data formats are acceptable but I don't think .mat is one of them.  Typically, NaN's are converted to some other value before processing.

Can you upload a data set for us to look at?

**Comment by stnava** [comment]
might also pass a mask or pair of masks


brian

**Comment by AlexandreLaborde** [comment]
@ntustison @stnava  Thank you very much for  your reply! I will gather a sample dataset and put it here. In the meanwhile I will try to play it the masks.

Thanks one more time!
