### ISSUE TITLE
Volume-based cortical thickness pipeline

### ISSUE THREAD

**Issue by younghoo** [ANTsX/ANTs#539]
Hello, I try to repeat the cortical thickness pipeline published in NeuroImage 2014 on my data. 

(i) Based on my understanding, there were four steps: (1) build a sample-specific (with skull) template (2) cook template priors for the custom template (3) run "antsCorticalThickness.sh" with custom template and priors as input (4) anatomical labeling using "antsJointLabelFusion.sh" for ROI-based analysis. Is my understanding correct?

(ii) I use ["antsCookTemplatePriorsCommand.sh"](https://github.com/ntustison/antsCookTemplatePriorsExample) to make template priors and I use ["malfCommand.sh"](https://github.com/ntustison/MalfLabelingExample) for anatomical labeling. I find that the recommended prior templates are different for cooking template priors and anatomical labeling. For cooking template priors, the prior templates include 15 images (downloaded in GoogleDrive) while for anatomical labeling, the prior templates include 20 images (downloaded in MindBoggle). So why there is difference?

(iii) In cooking template priors, the first step is running antsCorticalThickness.sh to get the CSF prior. Is it necessary to run all stages of antsCorticalThickness.sh or just tissue segmentation is enough?   

Thanks!

**Comment by ntustison** [comment]
> 1.  Is my understanding correct?

Yes.

> So why there is difference?

Because they're different atlas sets.  

> Is it necessary to run all stages of antsCorticalThickness.sh or just tissue segmentation is enough?

You can just run through the tissue segmentation.

**Comment by younghoo** [comment]
If "antsCookTemplatePriorsCommand.sh" script is based on the 15-image atlas, where could I find more information about this atlas? For example, which label is representing which brain region?

Many thanks!

**Comment by ntustison** [comment]
I believe it's from this [paper](https://www.ncbi.nlm.nih.gov/pubmed/27726243).

**Comment by agisga** [comment]
> I believe it's from this paper.

@ntustison I get "Error occurred: The following PMID is not available: 27726243" when I click on that link...

**Comment by ntustison** [comment]
@agisga I fixed the link.

**Comment by agisga** [comment]
@ntustison Thanks!
