### ISSUE TITLE
itk::ERROR: AddImageFilter(0x7fe7ff0c2ee0): Inputs do not occupy the same physical space!

### ISSUE THREAD

**Issue by vnckppl** [ANTsX/ANTs#540]
Hi ANTs programmars,

Whilst running Atropos I am receiving the following error:

itk::ERROR: AddImageFilter(0x7fe7ff0c2ee0): Inputs do not occupy the same physical space!

Some information:
- I am running ANTs v2.2.0 (c95e77a) built on OS X
- Both the input T1 image and the brain mask for Atropos are FLOAT32 images.
- I made sure the mask and the T1 have the exact same header by copying the info with fslcpgeom (I also tried CopyImageHeaderInformation, but that did not fix the error either).

I have read up on this error message and found the following solution:
https://github.com/ANTsX/ANTs/issues/396#issuecomment-269731486
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/src/itkImageToImageFilterCommon.cxx#L26-L27

I compiled ANTs from scratch, changed the values in itkImageToImageFilterCommon.cxx from 1.0e-6 to 1.0e-4 and then recompiled ANTs:

```
# Source code folder
bDIR=/Users/vincent/Data/tmp/ANTs_build
mkdir -p ${bDIR}
cd ${bDIR}

# Get source code
wget https://github.com/stnava/ANTs/zipball/master

# Unzip
mv master master.zip
unzip master.zip

# Source folder:
source=$(echo ${bDIR}/$(find ${bDIR} -type d -iname "ANTsX-ANTs-*" | xargs basename))

# Run cmake
cmake ${source}
cmake ${source}

# Compile
time(make -j 8)

# Fix ITK tolerance problem
cp \
    ${bDIR}/ITKv4/Modules/Core/Common/src/itkImageToImageFilterCommon.cxx \
    ${bDIR}/ITKv4/Modules/Core/Common/src/itkImageToImageFilterCommon.bkp 
    
cat \
    ${bDIR}/ITKv4/Modules/Core/Common/src/itkImageToImageFilterCommon.bkp \
    | sed 's/1\.0e-6/1\.0e-4/g' \
    > ${bDIR}/ITKv4/Modules/Core/Common/src/itkImageToImageFilterCommon.cxx

# Recompile
cmake ${source}
cmake ${source}
time(make -j 8)
```

Compiling finished without errors. However, I do still get them same error and the toleration is still set to 1.0e-6

> itk::ExceptionObject (0x7fe7ff0c35a8)
> Location: "unknown"
> File: /Users/vincent/Data/tmp/ANTs_build/ITKv4-install/include/ITK-4.12/itkImageToImageFilter.hxx
> Line: 241
> Description: itk::ERROR: AddImageFilter(0x7fe7ff0c2ee0): Inputs do not occupy the same physical space!
> InputImage Origin: [8.7360344e+01, -1.2991930e+02, -1.3226535e+02], InputImage_1 Origin: [0.0000000e+00, 2.9300000e+02, 0.0000000e+00]
> 	Tolerance: 1.0000000e-06
> InputImage Direction: -3.9023210e-02 -1.8386388e-02 -9.9906913e-01
> 9.9923524e-01 1.7585794e-03 -3.9062060e-02
> -2.4751528e-03 9.9982941e-01 -1.8303701e-02
> , InputImage_1 Direction: 1.0000000e+00 0.0000000e+00 0.0000000e+00
> 0.0000000e+00 -0.0000000e+00 -1.0000000e+00
> 0.0000000e+00 -1.0000000e+00 -0.0000000e+00
> 
> 	Tolerance: 1.0000000e-06

How can I fix this?

Thank you for your help.

**Comment by ntustison** [comment]
Can you post the troublesome data and the command line call you're using?

**Comment by vnckppl** [comment]
Hi Nick,

Here is a link to the data (T1, mask, and log file):
https://www.dropbox.com/s/s0ndtzrnt7dz5h7/T1_mask_log.tgz?dl=0

Could you please let me know when you have downloaded it so that I can remove it again?

This is the code I ran:

```
# Environment
dDIR="/Users/vincent/AtroposN4_Test/Data"
pDIR="/Applications/ANTs/ANTs_v2.2.0/Templates/MICCAI2012-Multi-Atlas-Challenge-Data/Priors2"
oDIR="${dDIR}/Output"
if [ -d "${oDIR}" ]; then rm -rf "${oDIR}"; fi
mkdir -p "${oDIR}"

# Setup ANTs
export ANTSPATH=/Users/vincent/Data/tmp/ANTs_build/bin
export PATH="${PATH}":"${ANTSPATH}"
export ANTSTEMPLATES="${ANTSPATH}"/../Templates
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=8

# Make sure the inputs occupy the same physical space
cp ${dDIR}/*.nii.gz ${oDIR}

fslcpgeom \
    ${oDIR}/T1.nii.gz \
    ${oDIR}/mask.nii.gz

fslorient \
    -copysform2qform \
    ${oDIR}/T1.nii.gz

fslorient \
    -copysform2qform \
    ${oDIR}/mask.nii.gz

diff -y \
     <(fslhd ${oDIR}/T1.nii.gz) \
     <(fslhd ${oDIR}/mask.nii.gz) \
     2>&1 | tee -a ${oDIR}/log.txt


# Run atropos
cd ${oDIR}
(time(antsAtroposN4.sh \
          -d 3 \
          -a "${oDIR}/T1.nii.gz" \
          -x "${oDIR}/mask.nii.gz" \
          -c 4 \
          -p ${pDIR}/priors%d.nii.gz \
          -o ${oDIR}/ )) \
    2>&1 | tee -a ${oDIR}/log.txt

exit
```


Thank you!

- Vincent

**Comment by ntustison** [comment]
If you look at the ITK error output, 

```
InputImage Origin: [8.7360344e+01, -1.2991930e+02, -1.3226535e+02], InputImage_1 Origin: [0.0000000e+00, 2.9300000e+02, 0.0000000e+00]
	Tolerance: 1.0000000e-06
InputImage Direction: -3.9023210e-02 -1.8386388e-02 -9.9906913e-01
9.9923524e-01 1.7585794e-03 -3.9062060e-02
-2.4751528e-03 9.9982941e-01 -1.8303701e-02
, InputImage_1 Direction: 1.0000000e+00 0.0000000e+00 0.0000000e+00
0.0000000e+00 -0.0000000e+00 -1.0000000e+00
0.0000000e+00 -1.0000000e+00 -0.0000000e+00
```

You'll see that "InputImage" and "InputImage_1" have completely different headers which indicates something not having to do with the T1 image and the mask.  My guess is that you haven't warped the priors to the space of your T1 image and that is what the error is in reference to.   Please check that and let me know.

**Comment by vnckppl** [comment]
Thank you,

I was not aware that the TPMs needed explicit warping up front. Thank you for pointing this out. Warping the TPMs fixed it.

- Vincent
