### ISSUE TITLE
antsApplyTransformsToPoints: interpolation option for SyN Warp?

### ISSUE THREAD

**Issue by tomomano** [ANTsX/ANTs#541]
I've been using ANTs for rodent brain image registration, and it has been working very well.

My question/problem is: 

Would it be possible to *specify interpolation* option when I use *antsApplyTransformsToPoints* function with 3D warping field obtained by SyN?

My situation is, I have a relatively high resolution image (say 2000x2000x2000 voxels), and from this image I define some landmark points.

When I perform registration, I first downsample the image so that it is around 300x300x300 voxels. Then I run Affine and SyN registration. Once I get the Affine transformation and SyN warp field, I apply these transformations to the above defined landmark points using *antsApplyTransformsToPoints*.

Since my landmark is defined in the high resolution image, I would want a accurate interpolation when I apply 3D warp field (which is low resolution, but interpolation should give slightly better and more continuous warping).

After investigating the source code briefly, I found that at the level of basic ITK functions, it is probably possible. However *antsApplyTransformsToPoints* does not expose that option, and it would be very nice if it supports it.

If anyone is familiar with this topic, would you please instruct me how exactly I can achieve this goal (probably by tweaking antsApplyTransformsToPoints). Thank you very much.

**Comment by ntustison** [comment]
The only ITK vector field interpolators are linear and nearest neighbor (cf inheritance diagram [here](https://itk.org/Doxygen/html/classitk_1_1VectorInterpolateImageFunction.html)).  So there's no point in exposing that option in the program.  However, you can do your own interpolation procedure outside ``antsApplyTransformsToPoints`` by separating your warp field components using ``ConvertImage ... 10``, resampling the component images to whatever size you want using the available interpolators, joining the resized component images using ``ConvertImage .. 9``, and then applying the resized displacement field to your points.

**Comment by tomomano** [comment]
Thank you very much for your suggestion.
I see, I just thought that ITK would have interpolation option since **antsApplyTransforms** does have that option. But it seems that this is not the case for vector images. Is linear interpolation the default interpolation used in **antsApplyTransformsToPoints**?

Your idea sounds like a quick solution to my problem. I will give it a try!

**Comment by ntustison** [comment]
``antsApplyTransforms`` and ``antsApplyTransformsToPoints`` only use what is available in ITK.    

>  Is linear interpolation the default interpolation used in antsApplyTransformsToPoints?

Yes.

**Comment by Dahaniel** [comment]
I am having a similar problem:
- I performed a template registration with my high resolution data
- further processed the data including a down-sampling step
- want to apply the transformation calculated in the first step onto the processed/downsampled data

Why would it be necessary to separate the displacement field components before resampling?

**Comment by stnava** [comment]
@Dahaniel  - i think you may be misinterpreting the original discussion.

nick said "you can do your own interpolation procedure" beyond nearest neighbor or linear.   someone might want windows sinc or something like that.  

in general, transforms are interpolated based on the image domain you pass to -r  so you dont need to resample the warps.  e.g. i have never needed to do that myself.
