### ISSUE TITLE
`antsApplyTransforms` fails for large data

### ISSUE THREAD

**Issue by david-hoffman** [ANTsX/ANTs#544]
If I try to apply a warp to a very large data set the majority of the output is zeros (only the first few z slices have any data). If I take the same reference image and down sample it and then use it for `antsApplyTransforms` then everything works as expected.

This is a problem for the `--float` option as well. I haven't done enough testing to know the point at which the error occurs but somewhere between 101465595 and 13002352976 voxels.

**Comment by ntustison** [comment]
You're going to need to provide more information e.g., command call so we can see what types of transforms and preferably posting of the data so we can try to reproduce on our end.

**Comment by david-hoffman** [comment]
I've tried to make this small enough to fit as an attachment. See the three files below:
[Moving Image](https://github.com/ANTsX/ANTs/files/1776749/Cell6_Fiji_Align_bin4_cool_mito.view_32.nii.gz)
[Fixed Image](https://github.com/ANTsX/ANTs/files/1776751/PALMMito_Hist.view_8.nii.gz)
[Transform file](https://github.com/ANTsX/ANTs/files/1776768/LMtoEM_d00GenericAffine.mat.gz)

This will work:
```
antsApplyTransforms -d 3 -e 0 -i Cell6_Fiji_Align_bin4_cool_mito.view_32.nii.gz -r PALMMito_Hist.view_8.nii.gz -o testwarp_8.nii.gz -t [LMtoEM_d00GenericAffine.mat,1] --float -v
```

But if we resample the reference image
`ResampleImageBySpacing 3 PALMMito_Hist.view_8.nii.gz PALMMito_Hist.view_4.nii.gz 4 4 4 0 0 1`

Then the warp no longer works
```
antsApplyTransforms -d 3 -e 0 -i Cell6_Fiji_Align_bin4_cool_mito.view_32.nii.gz -r 
PALMMito_Hist.view_4.nii.gz -o testwarp_4.nii.gz -t [LMtoEM_d00GenericAffine.mat,1] --float -v
```

` testwarp_4.nii.gz` is blank.

From the little testing I've done, setting the voxel size to 6 and 5 also works.

**Comment by ntustison** [comment]
Are you sure it's not a problem with your image viewer?  I can't get testwarp_4.nii.gz to load in SNAP because of size but if I resample testwarp_4.nii.gz to something more manageable then I get something which looks reasonable which tells me it's not a problem with ``antsApplyTransforms``.  



![screen shot 2018-03-02 at 4 15 36 pm](https://user-images.githubusercontent.com/324811/36927798-f4a085d0-1e34-11e8-9a93-07600885119e.png)

**Comment by david-hoffman** [comment]
You're right. For Amira to read the file correctly it has to be decompressed first.

**Comment by david-hoffman** [comment]
@ntustison as an aside, is it possible to have antsApplyTransform output data with the same bitdepth as the input? i.e., if I input an 8-bit image is there a way to force the output to be 8 bit as well? This would allow me to save quite a bit of space. Thanks,

**Comment by gdevenyi** [comment]
+1 to that, resampling byte labels  results in doubles... Doesn't compress very well after thst

**Comment by david-hoffman** [comment]
@gdevenyi I should have dug around more before asking, but there's a utility called `ConvertImage` that should do the trick. You'll still have to save the double file to disk first but then you can covert it to 8-bit.

**Comment by gdevenyi** [comment]
Yup, I use it post transform :-)
