### ISSUE TITLE
Advice on Linux distribution to use with ANTs in a workstation

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTs#547]
Hi everyone,

I am building a workstation with 32 cores, 224Gb RAM, 40Tb storage. It will be dedicated to neuroimaging processing, so ANTs, ANTsR, Freesurfer, FSL, MRtrix, etc. 

Does anybody have any advice on what kind of Linux distribution to install?

My experience have been that Ubuntu is easier to manage on a Desktop, but I am not sure if other distributions are better for workstations.

Any tip is appreciated.
Dorian

**Comment by s-j-choi** [comment]
You might want to consider Debian Linux distro. Then, use Neurodebian packages. It will make your life easier. If you are interested please check the link: http://neuro.debian.net/

**Comment by dorianps** [comment]
Thanks Seongjin,

From the webpage looks like Neurodebian can be installed on any Ubuntu distro. Is there a reason to go for Debian instead of Ubuntu. 

I have some experience in Ubuntu and almost none in Debian.

**Comment by stnava** [comment]
i use centos7 in a similar context.  it's very stable etc.  however, i do
think ubuntu would be easier esp if you have interest in things like
tensorflow: https://www.tensorflow.org/install/  where only ubuntu install
instrux are available.  and may be easier to stay tight with cutting edge
compilers etc.  i've also used https://linuxmint.com/about.php which is a
pleasure.


brian

**Comment by s-j-choi** [comment]
You can just install the packages on your Ubuntu machine. Of course, there is no need to go for Debian.
In practical use, Debian and Ubuntu have no difference. You can use Debian as you do with Ubuntu. GUI might be different but if you do most of the jobs in the command line, there should be no difference.

**Comment by dorianps** [comment]
Thanks for the inputs, closing issue.
