### ISSUE TITLE
Intensity matching (or normalization)

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#548]
I wonder if there are any intensity matching (or intensity normalization) algorithms (for intra-contrast registration) included in ANTs. 

If so, are there any available template scripts for this purpose?

Any suggestions or sharing information would be appreciated.

**Comment by ntustison** [comment]
```
$ ImageMath | grep Histogram
  HistogramMatch    : 
      Usage        : HistogramMatch SourceImage ReferenceImage {NumberBins-Default=255} {NumberPoints-Default=64} {useThresholdAtMeanIntensity=false}
```

**Comment by s-j-choi** [comment]
I appreciate it. I will give it a shot.
