### ISSUE TITLE
Query regarding understanding of jacobian determinant in itkGeometricJacobianDeterminantImageFilter.hxx 

### ISSUE THREAD

**Issue by Mageshwar** [ANTsX/ANTs#549]
I want to have a deeper insight into the implementation of jacobian determinant in itkGeometricJacobianDeterminantImageFilter.hxx, but I’m unable to find some theory which explains on what basis this code is implemented. It would be nice if someone could refer some books or literature on jacobian implementation, especially the method used here, the connection between triangular area and tetrahedral volume computation and jacobian determinant. It would be of a great help to me, if someone can direct me towards it.

**Comment by ntustison** [comment]
There's not much reading required to understand this approach to estimating the Jacobian determinant.  After @pyushkevich published this [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2823935/) on bias in estimation of atrophy (see section 2.2.4), @stnava suggested that we also implement this in ANTs as an alternative Jacobian estimation strategy to the finite difference approach.

**Comment by stnava** [comment]
The filter just takes the ratio
​of​
the following two measurements:

​A = the size of the Local geometric object in the fixed domain

B = the size of that same​ object after It is mapped
​to the moving image.   ​

​the local estimate ( at a point ) is then B/A

the object is a tiny triangle or tetrahedron​ (3D)

this is consistent with the calculus-based definition if you shrink the
object to a point.

**Comment by Mageshwar** [comment]
Thank you for the references
