### ISSUE TITLE
how to install N4BaisFieldCorrection from ANTs

### ISSUE THREAD

**Issue by tiantian-li** [ANTsX/ANTs#550]
I am a new user of ANTs.I have two problems that I hope you can help me to solve them.
1、I am running the code of brain tumor segmentation,  N4ITK is required to preprocess the image,so i need to install N4BaisFieldCorrection from ANTs. I have compiled ANTs successfully with win10 according to [https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Windows-10],but i don't know how to install N4BaisFieldCorrection from it.
2、I run the code with anaconda and pycharm,they are in the win10, but the ANTs is in the  Linux subsystem of Windows. How can anaconda  and pycharm  use the N4BaisFieldCorrection?What should I do concretely?
I sincerely hope that someone can help me ,thanks

**Comment by ntustison** [comment]
1.  N4BiasFieldCorrection should be available along with the rest of the ANTs compiled programs in the bin/ subdirectory of your install directory.

2. I assume you could run it through whatever system call mechanism is available on those platforms.

**Comment by dorianps** [comment]
I don't think you can call linux commands from a python running on the
windows side. But I've never tried to see if there is a workaround for this.

Note, the latest Windows version allows the installation of linux directly
from the Windows store. No pains with developer mode and manual commands
anymore.

Dorian

**Comment by cookpa** [comment]
I think you would need to install all of your software in the linux subsystem and run Python from Linux, and have that call ANTs the same way it would on a native Linux system. I don't think you can call Linux binaries from Windows binaries, and in any case you should definitely not write output to the Linux file system from Windows binaries

https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/

**Comment by yarikoptic** [comment]
To use ANTs and many other tools from within Python, you might like to consider starting using nipype project which provides unified interfaces, including the one you need: https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/segmentation.py#L258
