### ISSUE TITLE
antsMultivariateTemplateConstruction2.sh

### ISSUE THREAD

**Issue by Yangguoyuan** [ANTsX/ANTs#553]
Hi ANTs experts:
      I want to use ANTs software to do the human brain template, but the antsMultivariateTemplateConstruction2.sh didn't support lsf submission way. Our server was only support lsf work execution. How to modify the code to achieve the antsMultivariateTemplateConstruction2.sh working on the lsf? Is there any suggestion? We have changed some code about job submission way, but there still some error, example: /home/gaojh/software/guoyuan/antsbin1/bin/antsMultivariateTemplateConstruction2.sh: line 270:  6881 Segmentation fault      ${ANTSPATH}/AverageImages $dim $output 1 ${images[*]}
if you can solve this problem, can you pin me?

best, 
Guoyuan
email: yangguoyuan@pku.edu.cn

**Comment by ntustison** [comment]
Hi Guoyuan,

This is a system-specific issue which is very difficult for us to debug.  Let's start off with something small---are you able to run the code in serial on a small data set?  For example, are you able to build the 2-D templates [here](https://github.com/ntustison/TemplateBuildingExample) using ``-c 0``?

Nick

**Comment by Yangguoyuan** [comment]
Hi Nick,
          build the 2-D templates here using -c 0, but it can't run with -c others.  For example SGE qsub, PBS qsub.
Guoyuan

**Comment by ntustison** [comment]
Okay.  Thanks.  

Unfortunately, we don't have access to an lsf system so you're going to have to do any modifications yourself.  In addition to the changes in ``antsMultivariateTemplateConstruction.sh``, you'll need to create a ``waitForXlfJobs.pl`` script similar to the other ``waitFor???Jobs.pl``.  

I see that you've tried to do some code modifications yourself.  However, the error message you posted is uninformative as it relates to your system.

**Comment by Yangguoyuan** [comment]
Hi Nick,
         The last question. We have 189 T1 map, each T1 matrix  was 256x256x256. If we use these parameter to construct the brain template. How long will it take to complete this work?

inputPath=${PWD}/
outputPath=${PWD}/template/
${ANTSPATH}/antsMultivariateTemplateConstruction2.sh \
  -d 3 \
  -o ${outputPath} \
  -i 10 \
  -g 0.25 \
  -c 0 \
  -k 1 \
  -w 1 \
  -f 8x4x2x1 \
  -s 3x2x1x0 \
  -q 100x70x50x10 \
  -n 1 \
  -r 1 \
  -l 1 \
  -m CC[2] \
  -t BSplineSyN[0.1,26,0] \
  ${inputPath}/sub*.nii

**Comment by ntustison** [comment]
It's hard to say.  It depends quite a bit on your system but ~200 images is going to take awhile.  Perhaps a week or more.

**Comment by Yangguoyuan** [comment]
Hi Nick，
         I found the most time consuming thing was the antsRegistration. So do your executable program supports the GPU  framework? Or can we develop the accelerated method? Like GPU porcessing.
