### ISSUE TITLE
ANTs on Solaris

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#558]
Dear ANTs experts,

I wonder if ANTs tools are working well on Solaris environment. 
I have a huge amount of data stored in collaborator's institution (Solaris Linux). So I want to process the data directly on their server. I requested installation of ANTs tools and I checked the installed tool. But it seemed not properly installed. I wonder if ANTs supports Solaris?

Thank you for your reply in advance

**Comment by yarikoptic** [comment]
I have no clue in solaris but google does suggesting [Solaris Containers for Linux Applications](http://www.oracle.com/technetwork/server-storage/solaris/overview/scla-jsp-139748.html) so you could possibly run Linux build (or a container) on Solaris.
