### ISSUE TITLE
N4 bias field correction timing

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#559]
This is not an issue but the question about the proper timing of applying the N4 bias-field correction. 

I have T1W images acquired in the sagittal direction. And I will do the N4 correction for these images. 
Eventually, these N4 corrected images are going to be reoriented to the axial direction in a multi-modal analysis. And I became curious about the timing of N4 correction in the work pipeline. 

My questions are:
1) Should I perform N4 correction prior to the image reorientation? (My gut feeling says yes.)
2) Are there any problems/known issues if I perform N4 correction after the image reorientation?

Thank you for your answers in advance!

**Comment by cookpa** [comment]
I'm not quite clear what you mean by reorientation. If you just mean reslicing (without changing any of the voxel values), it shouldn't make a difference.

If you mean registration, then I would do N4 first.
