### ISSUE TITLE
Skull stripping including Dura stripping in an individual subject space

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#560]
Dear ANTs experts,

I am looking for suggestions to implement a skull stripping with dura stripping in each individual subject space. I am using PWD image (from MP2RAGE images with 2nd inversion time, INV2). I performed N4 correction for INV2 images and I got really greatly improved skull stripped brain area. However, the images still have dura left. Thes dura will affect our study of cortical structure study. Thus, I need to know how to do the dura stripping using algorithms available within ANTs Tools. 

Any suggestions or example templates will be appreciated.

**Comment by cookpa** [comment]
Have you tried `antsBrainExtraction.sh`? Templates available here

https://figshare.com/authors/Nick_Tustison/441144

**Comment by s-j-choi** [comment]
I will give it a try. 
Thank you.
