### ISSUE TITLE
Accelerate antsCorticalThickness run?

### ISSUE THREAD

**Issue by aghayoor** [ANTsX/ANTs#561]
Hi all, 

I am using antsCorticalThickness on a series of preprocessed subjects which are already denoised and bias field corrected, and I have a brain mask for each.
Now, I have two questions about antsCorticalThickness processing:

- Can I turn off the bias field correction process as my subjects are already bias field corrected?
It seems that running denoising is optional through the process; however, I did not find a way to turn off bias field correction.

- Can I use the subject brain mask and turn off antsBrainExtraction?

Thank you

**Comment by aghayoor** [comment]
@ntustison : Hi Nick, do you have any advices on this?

Also, I noticed that brain extraction did not work well on my subjects. The generated mask cuts bottom half of cerebellum.
As I don't see any option to pass the subject brain mask to the program, will it be fine if I just pass the skull stripped subject as my input?

Thank you!

**Comment by ntustison** [comment]
Copy your brain mask to the output directory and call it ``${outputPrefix}BrainExtractionMask.nii.gz``.   The program should skip the brain extraction step.

>  Also, I noticed that brain extraction did not work well on my subjects.

Perhaps because your brain extraction template does not match your data.  We discuss this in our paper.

**Comment by aghayoor** [comment]
Thank you Nick!

**Comment by cookpa** [comment]
N4 is integrated into the segmentation script and it run iteratively, there's no easy way to turn it off without editing the code.

It doesn't take very long to run, though, and it might still improve results. It uses the white matter probability from the segmentation to initialize the bias estimation.

**Comment by aghayoor** [comment]
I thought the same. Thank you!
