### ISSUE TITLE
Template is blurring

### ISSUE THREAD

**Issue by younghoo** [ANTsX/ANTs#562]
Hi, I build a T1 template out of 26 subjects using the following commands:
`${ANTSPATH}/antsMultivariateTemplateConstruction2.sh \
    -d 3 \
    -o T_ \
    -c 1 \
    -r 1 \
    T1*.nii.gz`
The generated template is quite blurring and loses cortical folding details. A snapshot of the template is shown below:
![t](https://user-images.githubusercontent.com/8926978/38538443-7397c290-3cc6-11e8-8454-98179436fa9d.png)
All raw data quality are checked and a snapshot of one typical subject is shown below:
![s1](https://user-images.githubusercontent.com/8926978/38538633-45371bd4-3cc7-11e8-856b-1f012b28adde.png)

How should I tune the parameters to get a better template?
Thanks!

**Comment by ntustison** [comment]
Template building is dependent on image registration which assumes correspondence.  There's not necessarily correspondence across secondary or tertiary gyri/sulci so you might need to temper your expectations.  However, you might want to look at this [example](https://github.com/ntustison/TemplateBuildingExample) and see if you can get better results by matching parameters.

**Comment by younghoo** [comment]
Thank you for your reply. I am using the [ants longitudinal cortical thickness pipeline](https://www.biorxiv.org/content/early/2017/07/30/170209) to analyze my data and I find that the brain extraction is not as good as before and lots of dura is not removed, as shown below:
![fig1](https://user-images.githubusercontent.com/8926978/38597902-ba8741dc-3d8c-11e8-9191-070921254566.png)
![fig2](https://user-images.githubusercontent.com/8926978/38597916-cc237afa-3d8c-11e8-9064-d651f695b822.png)

I also find that the estimated cortical thickness also covers the dura. Furthermore, the dura part is aligned with the SST's dura after normalization, as shown below:
![fig3](https://user-images.githubusercontent.com/8926978/38597923-d4435322-3d8c-11e8-9e8d-504667e4adc8.png)
![fig4](https://user-images.githubusercontent.com/8926978/38597937-e4760456-3d8c-11e8-9a1b-d7633ca78970.png)

I wonder that whether the imperfectness of brain extraction would influence the accuracy of estimated cortical thickness? Whether the value in each voxel represents the cortical thickness in each voxel in the cortical thickness map?

**Comment by ntustison** [comment]
What does your brain extraction mask look like?

**Comment by younghoo** [comment]
@ntustison The processing steps are based on the ANTs biorxiv paper: (1) pool all subjects' data to create a group-specific template using antsMultivariateTemplateConstruction2.sh and commands used are shown above; (2) cook priors for group-specific template using [this example](https://github.com/ntustison/antsCookTemplatePriorsExample), which first perform a cortical thickness pipeline using antsCorticalThickness.sh (OASIS templates used here) and then perform anatomical labeling using antsJointLabelFusion.sh based a set of atlases and labels. Brain extraction mask and six tissue priors are generated finally; (3) antsLongitudinalCorticalThickness.sh is used to estimate cortical thickness for all time point data of a subject. The commands used is `${ANTSPATH}/antsLongitudinalCorticalThickness.sh \
     -d 3 \
     -e ${TEMP_DIR}/T_template0.nii.gz \
     -m ${TEMP_DIR}/priors/BrainExtractionMask.nii.gz \
     -p ${TEMP_DIR}/priors/prior%d.nii.gz \
     -f ${TEMP_DIR}/priors/BrainRegistrationMask.nii.gz \
     -c 2 -j 10 \
     -o ${sub} \
     ${input_images[@]}
` The ${TEMP_DIR} contains the group-specific template and its brain extraction mask & priors. The brain extraction mask is dilated to make a registration mask. A set of snapshots are shown below and should be self-explanatory. The single subject template (SST) and single time point data has been presented earlier above.
![gt_mask](https://user-images.githubusercontent.com/8926978/38653056-50b92d10-3e3b-11e8-8001-5099abb82cf2.png)
![gt_priors](https://user-images.githubusercontent.com/8926978/38653106-99871624-3e3b-11e8-87b8-b3585c314037.png)

**Comment by younghoo** [comment]
@ntustison I also tried the antsBrainExtraction.sh with OASIS templates on the single time point data and still lots of dura remains. The commands are: `${ANTSPATH}/antsBrainExtraction.sh \
  -d 3 \
  -a ${sub}.nii.gz \
  -e ${OASIS_DIR}/T_template0.nii.gz \
  -m ${OASIS_DIR}/T_template0_BrainCerebellumProbabilityMask.nii.gz \
  -f ${OASIS_DIR}/T_template0_BrainCerebellumRegistrationMask.nii.gz \
  -o ${sub}
`

**Comment by younghoo** [comment]
@ntustison Thank you for your kind help and the data has been sent to your e-mail (ntustison@gmail.com).

**Comment by ntustison** [comment]
I'd like to see your template and brain extraction mask.  Can you please send those as well?

**Comment by younghoo** [comment]
@ntustison The data have been sent to your email. Many thanks!

**Comment by ntustison** [comment]
Your registration mask doesn't encompass enough of the head and background.  Try the brain extraction without the registration mask 

```
$ antsBrainExtraction.sh -d 3 -a S001_A.nii.gz -e T_template0.nii -m antsCTBrainExtractionMask.nii -o output
```

and you'll get something similar to

<img width="1008" alt="screen shot 2018-04-13 at 8 53 41 pm" src="https://user-images.githubusercontent.com/324811/38764061-d8405dd6-3f5c-11e8-8042-89d7ad6ce50d.png">

**Comment by younghoo** [comment]
@ntustison Thank you. Even without registration mask, there is still dura left. However, most subject data could get perfect brain extraction results, except this one subject. I also find that antsLongitudinalCorticalThickness.sh will report error without specifying registration mask and I don't know if it is a bug. Another thing is that when I cook group template priors (on SGE cluster), I get a "file 0.8 does not exist" error although the priors are well-cooked.
