### ISSUE TITLE
Problems when installing ANTs

### ISSUE THREAD

**Issue by DavidMolitor92** [ANTsX/ANTs#563]
Hi, 
Unfortunately i have some issues when trying to install ANTs. 
When I'm trying to follow the guide in the Readme, svn cannot find the path when using the following command

> svn checkout https://advants.svn.sourceforge.net/svnroot/advants ANTs

I'll get the following error message

> svn: E170013: Could not connet to project archive under URL »https://advants.svn.sourceforge.net/svnroot/advants« 
svn: E175002: Unexpected HTTP-Status 504 »Gateway Time-out« auf »/svnroot/advants«

And yesterday i got something like "could not find path /svnroot/advants". I tried to download ANTs from github, and installing it manually but then ccmake crashed with a lot of errors, mostly saying things like

>  CMake Error at CMakeLists.txt:15 (install):
   install TARGETS given no ARCHIVE DESTINATION for static library target
   "antsUtilities".

Maybe someone got an idea how to fix this? I need ANTs to generate templates for MAGeTbrain. 
Thanks in advance! 
David

**Comment by cookpa** [comment]
We have been using git for some time now:

```
  git clone https://github.com/ANTsX/ANTs.git
```

**Comment by DavidMolitor92** [comment]
Thanks for the quick reply.
That fixed the downloading problem but when using the ccmake command i still get the same error messages. Maybe i use the wrong cmake version? I just downloaded the newest...
Thank you again! 
David

**Comment by cookpa** [comment]
OK, please start over from a fresh install, and follow these instructions:

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

If it doesn't work, please follow up here with the exact error message, your CMake version and OS, and I'll help further if I can.

**Comment by DavidMolitor92** [comment]
Thank you.
The instructions under the link worked. 
Greetings, David
