### ISSUE TITLE
Convert homogeneous matrix to `.mat` file for `--initial-moving-transform`

### ISSUE THREAD

**Issue by david-hoffman** [ANTsX/ANTs#570]
If I have an affine transform estimated by another program what would be the best way to convert that to a `.mat` file so that I can initialize `antsRegistration` with it?

**Comment by cookpa** [comment]
Very carefully - the convention for describing transform parameters may differ between software and yield unexpected results. 

The command `c3d_affine_tool` can translate a 4x4 matrix to an ITK .mat file. You can get it from

  https://sourceforge.net/projects/c3d/

There's a problem with the Mac build at the moment, but you can get the tool bundled with the latest build of ITK-SNAP

  https://sourceforge.net/projects/itk-snap/files/itk-snap/Experimental/

You should verify that the resulting `.mat` files give the expected initialization for your data.
