### ISSUE TITLE
Command not found.

### ISSUE THREAD

**Issue by drblue3305** [ANTsX/ANTs#573]
Hi Experts

I have compiled the ANTS in MAC OSX.
testing with which "antsregistration" and "antsRegistrationSyN.sh" were both correct.

I am trying to use compositeTransformUtil but could not work.
When typing $ which compositeTransformUtil
it showed "/Users/XXX/bin/ants/bin//compositeTransformUtil"
When typing $  compositeTransformUtil
it showed:
"Usage: CompositeTransformUtil --disassemble <CompositeTransform FileName> <transform name prefix>
or
CompositeTransformUtil  --assemble <CompositeTransform> <transform 1> <transform 2 > ... <transform N>"

However when trying to use it to assemble a .h5 and a .mat from ANTS, 
$CompositeTrasnformUtil --assemble /Users/XXX/Desktop/ANTS_regTest/TwoMMT1w0GenericAffine.mat /Users/XXX/Desktop/ANTS_regTest/sub-001_ses-baseline_T1w_target-MNI152NLin2009cAsym_warp.h5
-bash: CompositeTrasnformUtil: command not found

I have setup the bash profile $ANTSPATH and $PATH according to the installation guide, but I still cannot get it to work.

Could someone please advice me how to correct this problem, or if I am inputing the arguments wrongly for the command?

Thank you very much!

Chen-Chia

**Comment by ntustison** [comment]
Try using ``antsApplyTransforms``.

**Comment by drblue3305** [comment]
Thank you!
The antsApplyTransforms worked for me.
But I would still like to know why I got the command not found error, is it supposed to be like this?
(That I just should not use the command directly from command line? Or is there still something else that is causing the error?)

**Comment by ntustison** [comment]
I know it has worked previously but since it's not really under active development and support, I don't have much motivation to figure out why it's not working for you.   If you're motivated to figure out the problem, and you're able to do so, please post your findings on this thread.

**Comment by ntustison** [comment]
Except, I just noticed that you have ``CompositeTrasnformUtil`` which is not the name of the program.  Perhaps that is why you got that error.
