### ISSUE TITLE
Image display with ANTsR

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#578]
Dear ANTsR expert. 

I am playing with ANTsR and one of my existing images. 
I only used 'plot' and found that this only shows a few sampled coronal images. 
I wonder if there is a way to display selected image slice and viewing direction, e.g., axial direction.

Thank you for your advice in advance.

**Comment by dorianps** [comment]
Yes, sorry, forgot the real function plot is using is not "plot" itself.

There is also some online resources from an earlier version of ANTsR:
https://www.rdocumentation.org/packages/ANTsR/versions/1.0/topics/plot.antsImage

But the most up to date resource is the pdf of all functions:
https://github.com/ANTsX/ANTsR/releases/download/v0.3.1/ANTsR-manual.pdf

@stnava, I couldn't find the pdf manual for the latest version. The link in
the homepage also sends to all released files, not a specific pdf. Perhaps
would be useful to keep the most recent pdf in the github repository itself.

**Comment by s-j-choi** [comment]
Thanks a lot for your replies.
