### ISSUE TITLE
Problems to generate templates for MAGeTbrain using ANTs

### ISSUE THREAD

**Issue by DavidMolitor92** [ANTsX/ANTs#579]
Hi everybody,
I tried to follow the guide under
[](https://github.com/CobraLab/documentation/wiki/ANTs-Multivariate-Template-Construction)
to create templates for usage with MAGeT. Unfortunately i wasn't able to do so and when i opened an issue there, I was referred to this site. Maybe, I still have problems with my ANTs Installation. 
I followed the Wiki
[](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS) 
to install ANTs on my Linux PC (Ubuntu 16.04). 
But when I try to run the my-antsMultivariateTemplateConstruction2.sh I get Error messages saying, that certain files do not exist (and they do not exist in the ~/bin/ants folder). They look like that one

> FILE /home/david/home/bin/ants/bin/waitForPBSQJobs.pl DOES NOT EXIST -- OR -- IS NOT EXECUTABLE !!! ./my-antsMultivariateTemplateConstruction2.sh will terminate.

The ccmake command I used to generate the executables exited without any errors shown. 
Maybe someone can help me? As said before: I just want to generate templates to use them for MAGeTbrain. 
Thanks in advance.
David

**Comment by ntustison** [comment]
Did you follow [this part](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#copy-scripts) from the Wiki write-up?

**Comment by cookpa** [comment]
What do you get if you do

```
  echo $ANTSPATH
  ls -l ${ANTSPATH}waitForPBSQJobs.pl
```

**Comment by DavidMolitor92** [comment]
Hi, I get the following:

> echo $ANTSPATH
/home/david/home/bin/ants/bin

> ls: Access to '/home/david/home/bin/ants/bin/waitForPBSQJobs.pl' not possible: cannot find file or directory

Maybe it is a wrong ANTSPATH, I'll try it out quickly.
Greetings

**Comment by cookpa** [comment]
OK but be careful, I think I have also seen some instances of scripts calling `${ANTSPATH}script` instead of `script`.
