### ISSUE TITLE
Cortical thickness undefined in a few GM voxels

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#580]
After running `antsCorticalThickness.sh`, we sometimes see GM voxels with zero thickness. Example here: green is GM with thickness defined, and red is GM (according to the segmentation) but thickness is zero.

![thickness](https://user-images.githubusercontent.com/611507/39264165-32ce7f56-4892-11e8-9c07-f1cee0fd7807.png)

This tends to happen in places where GM is over segmented. In this example it has missed WM in the gyrus, and the thickness is undefined at the edge.

Is this expected behavior? Is the thickness set to zero when the thickness exceeds the prior maximum passed with `-t`?

**Comment by ntustison** [comment]
Due to lack of convergence and/or regularization, thickness values aren't necessarily going to be propagated to every voxel within the gray matter segmentation mask.  This is expected behavior but the thickness is not set to zero when it exceeds the optionally specified maximum value.

**Comment by cookpa** [comment]
Thanks for the clarification.
