### ISSUE TITLE
IntegratedIntensity in LabelGeometryMeasures

### ISSUE THREAD

**Issue by satra** [ANTsX/ANTs#589]
based on the ITK docs, i'm assuming this is the sum of values of voxels in a label. 

just checking to verify. so mean thickness/intensity/othermeasure would equal `IntegratedIntensity/VolumeInVoxels`?

**Comment by ntustison** [comment]
I guess you could do that.  The thickness measurements that I report in a couple papers are actually calculated a bit differently.  After joint label fusion, I mask out the zero thickness voxels in the label regions and then calculate the mean thickness values in those masked labeled regions.

**Comment by satra** [comment]
@ntustison - thank you  - that should be easy to implement as well.
