### ISSUE TITLE
ANTS and SPM compatibility

### ISSUE THREAD

**Issue by zeynabre** [ANTsX/ANTs#590]
Hello, 
I have an mr image of the iterative averaging with ANTS. When I try to import it in SPM I get this error: 
"There is not enough overlap in the images
        to obtain a solution.
         
        Please check that your header information is OK.
        The Check Reg utility will show you the initial
        alignment between the images, which must be
        within about 4cm and about 15 degrees in order
        for SPM to find the optimal solution."

Do you have any solution how can I have a ANTS average image which is compatible with SPM? 

Thanks

**Comment by satra** [comment]
@zeynabre - if you affine transform the average image to MNI space that should work fine with SPM

**Comment by zeynabre** [comment]
You mean for example using FLIRT?

**Comment by satra** [comment]
FLIRT or ANTs - doesn't matter

**Comment by zeynabre** [comment]
I do not have raw data. I only have average images from ANTs. And if I run FLIRT for this image it works in SPM.

**Comment by cookpa** [comment]
Hi @zeynabre, would you mind sharing the template image before and after you ran FLIRT? I'd like to look at the headers so I can update the ANTs Wiki for other SPM users.

**Comment by cookpa** [comment]
Thanks.

I see in the `FLIRT1.nii.gz` the qform and sform codes are set to 4. This is different to what `antsRegistration` would produce, but it may not matter unless SPM specifically looks for that code.

**Comment by John1231983** [comment]
Dear all, related to flirt. If I want to algin an image to another image, Should I resize (zero padding) to these image to the same size before applying alignment in flirt? My first image size is 120x128x256 and the second is 122x 125x 240. Thanks all
