### ISSUE TITLE
Disagreement between antsAI help and usage in antsBrainExtraction.sh

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#592]
With the new addition of the '-g' parameter there's a divergence in help vs usage, I presume usage is correct.

In the help:
```
     -g, --translation-search-grid [stepSize=25, AxBxC=0x0x0]
          Translation search grid in mm, which will translate the moving image in each 
          dimension in increments of the step size. 
```

But in usage:
```
 exe_initial_align="${exe_initial_align} -g [0x50x50,50]"
```

Looks like the grid and step size parameters are mixed up.

**Comment by cookpa** [comment]
Thanks I will check

Sent from my iPhone

On May 25, 2018, at 10:30 AM, Gabriel A. Devenyi <notifications@github.com<mailto:notifications@github.com>> wrote:


With the new addition of the '-g' parameter there's a divergence in help vs usage, I presume usage is correct.

In the help:

     -g, --translation-search-grid [stepSize=25, AxBxC=0x0x0]
          Translation search grid in mm, which will translate the moving image in each
          dimension in increments of the step size.


But in usage:

 exe_initial_align="${exe_initial_align} -g [0x50x50,50]"


Looks like the grid and step size parameters are mixed up.

**Comment by gdevenyi** [comment]
Wonderful, thanks!
