### ISSUE TITLE
Proposal: user-friendly fix for setting the random seed for registration

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTs#596]
@yarikoptic made a good suggestion that we should use an environment variable to set the random seed for registration in ANTs.  e.g. 

```
export ANTS_GLOBAL_DEFAULT_REGISTRATION_SEED=1
```

this would obviate user-interface code and would allow near immediate porting to ANTsR and ANTsPy.

@cookpa  --- any chance you could to take a stab at implementation via pull request?  i imagine that there are relatively few places (`antsAI`, `antsMotionCorr`, `antsRegistration` that would need a (pseudo-code)

```
registration->reinitializeSeed( std::getenv( " Name Here " ) )
```

or whatever the right ITK way is to do such a thing.

**Comment by stnava** [comment]
@ntustison any thoughts on this?

**Comment by ntustison** [comment]
Yeah, I think it's a good idea.  I'm not sure about the environmental variable, though.  We had a similar issue with Atropos and added a command line option.  As another possibility to mitigating this randomization issue, could we add a command line parameter to these other programs? Not sure which route would be best but it would probably be worth considering standardizing one approach.

**Comment by satra** [comment]
my preference would be for a command line option.

**Comment by cookpa** [comment]
Yes I think a command line option would be best - I can work on this next week.


Sent from my iPhone

On Jun 1, 2018, at 5:08 PM, Satrajit Ghosh <notifications@github.com<mailto:notifications@github.com>> wrote:


my preference would be for a command line option.

**Comment by stnava** [comment]
Ok ... I am impartial to which solution as long as is consistent.

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTs/pull/597  allows envt variable control of seed and can be over-ridden by a command line option when it becomes available.

**Comment by cookpa** [comment]
I made a start with a command line option to antsRegistration:

https://github.com/ANTsX/ANTs/commit/792d6735f063223b73fe92c597e371b4a76f7caf

FYI SyN does call the PrepareRegistration method, so it would not get a fixed seed in the current master. This only matters if you are not using dense sampling for SyN though.

I will work on other executables / scripts next.

**Comment by stnava** [comment]
Nice.

I am thinking we make a release after this gets done.

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/pull/599
