### ISSUE TITLE
Do we fix WarpImageMultiTransform and ANTS (original version) + develop new tests?

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTs#598]
Old `WarpImageMultiTransformFilter` is not functioning well with ITKv5

Same thing for old `ANTS` due to its dependence on the above

Also - the old testing framework is pretty shallow and does not cover a large mass of ANTs tools.

This issue is intended to note current status.  Not sure of best next steps - the few active developers have fairly limited time and are likely to devote that to things other than basic maintenance (ie new tools).

**Comment by ntustison** [comment]
Hey @stnava , 

I hate to deprecate ``ANTS`` just yet specifically because of its relevance in ``antsMultivariateTemplateConstruction.sh``.  I'm a little less tied to ``WarpImageMultiTransform`` so let me take a stab at this and see if I can get it working.  

Nick
