### ISSUE TITLE
BUG? Limited Use of Multithreading during SyN Registration

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#604]
I built a new high-core-count machine to solve some big registration problems I've been working on, it has 20 cores (40 hyperthreads).

It looks like during a typical antsRegistration call, after setting ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=40, the affine stages seem to nicely fill the system. However, when it comes to SyN stages, I only see 4-8 core running at 100% while the rest site idle. This isn't at all what I would've expected. Is there some limitation inherent in the SyN code? Am I invoking something wrong? Or is this a bug?

**Comment by stnava** [comment]
no known limitation - possibly an ITK issue.

but does it vary with size of image?  ie do smaller images ( r16 ) use all
cores?


brian

**Comment by gdevenyi** [comment]
Not sure, will take a look at that.

A followup observation: I can see there are indeed 40 threads that have been spawned by antsRegistration, however only ~4 are use any CPU.

**Comment by gdevenyi** [comment]
Downsampling the images in question by 4x doesn't change the core utilization.

**Comment by cookpa** [comment]
If it works for Rigid but not for SyN, it's possible memory is an issue. What's the RAM on the machine? How large is the image?

Can you also share the command line? Maybe we can test further.

**Comment by gdevenyi** [comment]
```
antsRegistration --dimensionality 3 --float 1 --collapse-output-transforms 1 --verbose --output [output//average.nii.gz-mni_icbm152_t1_tal_nlin_sym_09c.nii,output//resampled.nii.gz] --use-histogram-matching 1 --initial-moving-transform affine.mat \
--transform SyN[0.1] --metric CC[mni_icbm152_t1_tal_nlin_sym_09c.nii,average.nii.gz,1,6] \
--convergence [6400x6400x6400x6400x6400x5400x1600x400x50x50,1e-7,10] \
--shrink-factors 16x14x12x10x8x6x4x2x1x1 \
--smoothing-sigmas 6.7945744023041525x5.945252602016134x5.095930801728114x4.2466090014400955x3.3972872011520763x2.547965400864057x1.6986436005760381x0.8493218002880191x0.42466090014400953x0mm \
--masks [mni_icbm152_t1_tal_nlin_sym_09c_mask.nii,NULL]
```

Definitely not a memory issue, 128GB of RAM on the machine. Currently antsRegistration is on the second-to-last stage and consuming ~2GB of ram.

**Comment by gdevenyi** [comment]
Ah, and the image size:
```
average.nii.gz
 Size : 248 312  270
mni_icbm152_t1_tal_nlin_sym_09c_mask.nii
 Size : 193 229  193

``

**Comment by cookpa** [comment]
Thanks. You may have hit a point where the thread overhead is significant compared to the work that each thread has to do. This might be stage dependent, because splitting the work at a shrink factor of 16 into 40 chunks might be a bad tradeoff, whereas the full resolution might benefit much more from extra threads.

You might try using the ITK default number of threads, which I think is the number of physical cores (ie, 20), see if CPU utilization goes up with fewer threads.

**Comment by gdevenyi** [comment]
Sure, I can definitely expect that at 16 shrink factor I won't be able to fill all the threads.

But... I'm now a 1x shrink factor, and I'm still seeing only 4 threads doing any work.

**Comment by stnava** [comment]
Could be different if you use mattes metric ,,, CC has other issues

**Comment by gdevenyi** [comment]
Small followup, at the beginning of an iteration, there is a sudden spike and all threads are doing work, very quickly this dies down back to 4 threads.

**Comment by stnava** [comment]
Different parts of the algorithm explain this

**Comment by gdevenyi** [comment]
Okay to be clear, the vast majority of the iteration time is spent in the low core utilization stage.

In terms of the algorithm, where should we be looking for a bottleneck?

**Comment by cookpa** [comment]
I ran a test registering two T1 images on a Linux cluster, using ANTs from a couple of weeks ago (after the switch to ITKv5).

```
antsRegistration -d 3 -r initAff0GenericAffine.mat -t SyN[0.1,3,0] -m CC[ ch2.nii.gz , t1.nii.gz , 1, 6 ] -f 2x1 -s 1x0mm -c [200x100, 1e-8, 10] -o testReg --verbose --float
```

with 10 cores, CPU utilization (per top) fluctuates between about 800-1000%, mostly it's about 900%.

**Comment by gdevenyi** [comment]
@cookpa thanks for your measurements

I updated to the latest ANTs HEAD and the ITKv5 to today's HEAD as well, to ensure its not some bug that was recently fixed.

I find that, at my initial stages, all cores are used, however, as antsRegistration progresses down the stages, it uses less and less cores eventually arriving at 4 cores and ~400% CPU. There are still the same number of threads running, but the other 16 are at 0% utilization

However, I've found something interesting, if I change my currently many-level registration to a single level registration (shrink 1, smooth 0), similar to your test, I find that all cores are used!

So, I have hypothesis, perhaps somewhere in the multi-stage code, we're "leaking" threads?

**Comment by cookpa** [comment]
> However, I've found something interesting, if I change my currently many-level registration to a single level registration (shrink 1, smooth 0), similar to your test, I find that all cores are used!
>
>So, I have hypothesis, perhaps somewhere in the multi-stage code, we're "leaking" threads?

That is interesting. I changed my example to this:

```
antsRegistration -d 3 -r initAff0GenericAffine.mat -t SyN[0.1,3,0] -m CC[ ch2.nii.gz , t1.nii.gz , 1, 6 ] -f 2x2x2x2x2x1 -s 5x4x3x2x1x0mm -c [10x10x10x10x10x100, 0, 10] -o testReg --verbose --float
```

And CPU utilization remains high, even in the later stages. Maybe some run-time thread management decisions are being made by ITK based on the first stage, and not updated later? I don't know much about the inner workings of the multi-threading, just a guess.

**Comment by gdevenyi** [comment]
Building against newest ITK this seems to have gone away, so, ITK bug at some point...
