### ISSUE TITLE
Windows 7 Visual Studio 2017 ANTs compilation errors and PATH variable setting

### ISSUE THREAD

**Issue by bfranceschiello** [ANTsX/ANTs#605]
Hello,

I followed all the step for compiling ANTs in windows 7, as explained here:

during the final compilation of SuperBuild_ANTS.sln with Visual Studio 2017 (Cmake properly generated the build for VS 2017 compiler), I got these errors:
Description:

'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadLowerBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadUpperBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadLowerBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadUpperBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadLowerBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadUpperBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
l'expression n'a pas été évaluée en constante [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
l'expression n'a pas été évaluée en constante [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl ants::ANTSGetFilePrefix(char const *)" (?ANTSGetFilePrefix@ants@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) dΘjα dΘfini(e) dans l_iMath.lib(iMath.obj) [C:\Builds\ANTs\ANTS-build\Examples\iMath.vcxproj]
"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl ants::ANTSOptionName(char const *)" (?ANTSOptionName@ants@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) dΘjα dΘfini(e) dans l_iMath.lib(iMath.obj) [C:\Builds\ANTs\ANTS-build\Examples\iMath.vcxproj]
"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl ants::ANTSOptionValue(char const *)" (?ANTSOptionValue@ants@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) dΘjα dΘfini(e) dans l_iMath.lib(iMath.obj) [C:\Builds\ANTs\ANTS-build\Examples\iMath.vcxproj]
un ou plusieurs symboles dΘfinis α diffΘrentes reprises ont ΘtΘ rencontrΘs [C:\Builds\ANTs\ANTS-build\Examples\iMath.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadLowerBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadUpperBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadLowerBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadUpperBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadLowerBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
'void itk::PadImageFilter<TInputImage,TOutputImage>::SetPadUpperBound(const unsigned __int64 [])' : impossible de convertir l'argument 1 de 'unsigned long [3]' en 'const itk::Size<2>' [C:\Builds\ANTs\ANTS-build\Examples\l_CreateTiledMosaic.vcxproj]
l'expression n'a pas été évaluée en constante [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
l'expression n'a pas été évaluée en constante [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
le type de tableau 'double [VImageDimension]' n'est pas attribuable [C:\Builds\ANTs\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]
"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl ants::ANTSGetFilePrefix(char const *)" (?ANTSGetFilePrefix@ants@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) dΘjα dΘfini(e) dans l_iMath.lib(iMath.obj) [C:\Builds\ANTs\ANTS-build\Examples\iMath.vcxproj]
"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl ants::ANTSOptionName(char const *)" (?ANTSOptionName@ants@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) dΘjα dΘfini(e) dans l_iMath.lib(iMath.obj) [C:\Builds\ANTs\ANTS-build\Examples\iMath.vcxproj]
"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl ants::ANTSOptionValue(char const *)" (?ANTSOptionValue@ants@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD@Z) dΘjα dΘfini(e) dans l_iMath.lib(iMath.obj) [C:\Builds\ANTs\ANTS-build\Examples\iMath.vcxproj]
un ou plusieurs symboles dΘfinis α diffΘrentes reprises ont ΘtΘ rencontrΘs [C:\Builds\ANTs\ANTS-build\Examples\iMath.vcxproj]

I've seen the binaries, so maybe they're not crucial, but I'd like to understand if there's any chance to fix them. 

Furthermore, there're some procedures need to be done to set the PATH, save it as permanent, and set the environmental variable in MATLAB as well. I'd need some help in that as well

Thanks a lot

Benedetta

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/commit/97bd0514538c66313db6290e08e08f6c62140f5e
