### ISSUE TITLE
antsRegistration doesn't document default SyN parameters

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#606]
From the ``--help``
```
SyN[gradientStep,updateFieldVarianceInVoxelSpace,totalFieldVarianceInVoxelSpace]
```

However, this works:
```
--transform SyN[0.1]
```

And results in these effective settings:
```
--transform SyN[0.1,3,0]
```

So perhaps help should say:
```
SyN[gradientStep,<updateFieldVarianceInVoxelSpace=3>,<totalFieldVarianceInVoxelSpace=0>]
```

**Comment by cookpa** [comment]
I went through the section on transforms to document the defaults and optional parameters more clearly.

https://github.com/ANTsX/ANTs/commit/216146fca81e5d048383a9f7c858de6c3d956da0

**Comment by ntustison** [comment]
Looks good @cookpa .  Thanks.

**Comment by gdevenyi** [comment]
Thanks @cookpa
