### ISSUE TITLE
Datscan registration to MRI using ANTs

### ISSUE THREAD

**Issue by JavierRojo** [ANTsX/ANTs#607]
Hello everyone,
I'm trying to register a series of Datscan images from PPMI to their corresponding MRI space (standard MNI space would also work). In all articles I've read people use FSL functions in order to do this. However, the striatum is not matching the dopamine signal properly and I was wondering if anyone knows a way to do this using ANTs.

I have access to a Datscans template of healthy subjecs in MNI space and the MNI152_T1 template. Then for each subject I have a MRI-T1 image and a Datscan image (different spaces for each subject and type of image).

Thank you in advance for any help

**Comment by ntustison** [comment]
Can you post a sample data set?

**Comment by JavierRojo** [comment]
Yes, sure. Here's a pair DATscan-MRI of the same subject:
MRI: [subject_MRIT1.nii.gz](https://github.com/ANTsX/ANTs/files/2192522/subject_MRIT1.nii.gz)
DATscan: [subject_SPECT.nii.gz](https://github.com/ANTsX/ANTs/files/2192523/subject_SPECT.nii.gz)

And here are the templates:

DATscan_template: [templateDATscan.nii.gz](https://github.com/ANTsX/ANTs/files/2192524/templateDATscan.nii.gz)
MNI152_T1_1mm: [MNI152_T1_1mm.nii.gz](https://github.com/ANTsX/ANTs/files/2192525/MNI152_T1_1mm.nii.gz)

**Comment by ntustison** [comment]
Yeah, it looks like the header is incorrect for the subject's SPECT image.  Specifically, it looks like the Anterior-Posterior direction is flipped.  I'm assuming that is what you're seeing.  One can change the header by calling ``PermuteFlipImageOrientationAxes`` but that's obviously a hack which would be less preferred than actually getting the header correct in the first place.  Also, perhaps somebody else will have to chime in but, even if you corrected the orientation issue, I wouldn't guess that the two subject images come from the same subject.

![screen shot 2018-07-13 at 7 38 33 pm](https://user-images.githubusercontent.com/324811/42720003-823ef306-86d4-11e8-84eb-629923d914da.png)
