### ISSUE TITLE
Error compiling ANTs on Ubuntu 16.04

### ISSUE THREAD

**Issue by ChenFeiL** [ANTsX/ANTs#609]
Hello ANTs Experts,

I am trying to compile ANTs on Ubuntu 16.04 LTS, but I keep getting the following error:

[  8%] Building CXX object Examples/CMakeFiles/l_GetMeshAndTopology.dir/GetMeshAndTopology.cxx.o
<command-line>:0:0: warning: "vtkRenderingCore_AUTOINIT" redefined
<command-line>:0:0: note: this is the location of the previous definition
/home/lianglab/Ants/ANTs-master/Examples/GetMeshAndTopology.cxx: In function ‘void ants::Display(vtkUnstructuredGrid*, std::__cxx11::string, bool, bool)’:
/home/lianglab/Ants/ANTs-master/Examples/GetMeshAndTopology.cxx:203:26: error: ‘class vtkWindowToImageFilter’ has no member named ‘SetMagnification’
     windowToImageFilter->SetMagnification( 4 );
                          ^
Examples/CMakeFiles/l_GetMeshAndTopology.dir/build.make:62: recipe for target 'Examples/CMakeFiles/l_GetMeshAndTopology.dir/GetMeshAndTopology.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/l_GetMeshAndTopology.dir/GetMeshAndTopology.cxx.o] Error 1
CMakeFiles/Makefile2:611: recipe for target 'Examples/CMakeFiles/l_GetMeshAndTopology.dir/all' failed
make[4]: *** [Examples/CMakeFiles/l_GetMeshAndTopology.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/ANTS.dir/build.make:114: recipe for target 'ANTS-prefix/src/ANTS-stamp/ANTS-build' failed
make[2]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
CMakeFiles/Makefile2:147: recipe for target 'CMakeFiles/ANTS.dir/all' failed
make[1]: *** [CMakeFiles/ANTS.dir/all] Error 2
Makefile:116: recipe for target 'all' failed

Having said this, I do not know what the above error means. How do I fix this error?

Best Regards,

Fei Chen

**Comment by gdevenyi** [comment]
Incompatible vtk version installed?

**Comment by gdevenyi** [comment]
Try the vtk superbuild version

**Comment by shamoons** [comment]
How do I get the vtk superbuild version @gdevenyi ?

**Comment by gdevenyi** [comment]
Check the cmake options.
