### ISSUE TITLE
test the antsMultivariateTemplateConstruction2.sh

### ISSUE THREAD

**Issue by Yangguoyuan** [ANTsX/ANTs#610]
Hi ants experts:
       I have made 3D brain template used code antsMultivariateTemplateConstruction2.sh twice with the same data and the same parameter. But those two template were not completely the same. I don't know why those two templates were not identical ?
Best,
Guoyuan

**Comment by ntustison** [comment]
``antsMultivariateTemplateConstruction2.sh`` depends on ``antsRegistration`` for which there are known reproducibility [issues](https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues).
