### ISSUE TITLE
Dependencies and unbundling

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#612]
I maintain the Gentoo Linux package for ANTs, and would like to try to unbundle some of the dependencies which it ships.

I could not yet find a full list of ANTs dependencies, do you track these somewhere? Also, what would be the best way to prevent the ANTs build system from pulling them in?

**Comment by gdevenyi** [comment]
ITK and (optionally) VTK.

cmake USE_SYSTEM_ITK and USE_SYSTEM_VTK, ITK_DIR and VTK_DIR to point to installations on the system.

**Comment by gdevenyi** [comment]
Also looks like libz, not clear its actually compiled/linked against

**Comment by TheChymera** [comment]
@gdevenyi Where can I get ITKv5 from?

**Comment by gdevenyi** [comment]
ITKv5 is still is RC

**Comment by gdevenyi** [comment]
https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v5.0rc01

**Comment by TheChymera** [comment]
Thank you @gdevenyi  :) How do you guys build ITK internally? I have tried to find some ITK 5.0 building instructions, but couldn't find anything. The build we currently have for 4.* seems to be CMake based and does not seem to work at all any more.

**Comment by TheChymera** [comment]
I have managed to integrate the ITK release candidate into the Gentoo Linux package management structure, and now I am looking to get ANTs to use it.

I am currently compiling ANTs with:

```
cmake -C /var/tmp/portage/sci-biology/ants-2.3.1/work/ants-2.3.1_build/gentoo_common_config.cmake\
    -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr\
    -DUSE_SYSTEM_ITK=ON\
    -DUSE_SYSTEM_VTK=ON\
    -DCMAKE_BUILD_TYPE=Gentoo\
    -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-biology/ants-2.3.1/work/ants-2.3.1_build/gentoo_toolchain.cmake\
    /var/tmp/portage/sci-biology/ants-2.3.1/work/ANTs-2.3.1
```

And this fails with the following [build.log](https://github.com/ANTsX/ANTs/files/3101585/build.log).

Can you help me out?

Also, for the next step, I believe there's quite a few other packages except ITK and VTK which ANTs bundles. I have looked at the source code, and it seems these are iterated on using the `${extProjName}` variable. Any idea where I can find a list of these packages?

**Comment by gdevenyi** [comment]
Error is pretty clear, its the same problem you ran into with ITK, ANTs is trying to download some files for its testsuite.

ANTs doesn't bundle anything, its just ANTs tools.

**Comment by gdevenyi** [comment]
Your other error is VNL is missing, which means your ITK build doesn't have it configured/built/installed or you haven't pointed to the ITK install properly.

**Comment by TheChymera** [comment]
> Error is pretty clear, its the same problem you ran into with ITK, ANTs is trying to download some files for its testsuite.

Ah, so the first step would be to parameterized the testing functionality. You mean to say the package automatically runs the test suite, yes?

> ANTs doesn't bundle anything, its just ANTs tools.

Yes, sorry, I didn't mean that verbatim, it's just that we don't want packages to manage their own deps outside the control of the system package manager. I totally understand that this is handy functionality for systems which are less explicit in their dependency management.

> Your other error is VNL is missing, which means your ITK build doesn't have it configured/built/installed or you haven't pointed to the ITK install properly.

These are the files which ITK installs on Gentoo, can you help me figure out how to correctly point ANTs to it or whether something is missing? [itk_files.txt](https://github.com/ANTsX/ANTs/files/3101888/itk_files.txt)

**Comment by TheChymera** [comment]
@gdevenyi I tried to address these issues, but I'm not making a lot of headway:

Tired to (temporarily) disable the test suite by setting `-DBUILD_TESTING=OFF` and based on my ITK files list by setting `-DITK_DIR=/usr/include/ITK-5.0/`. So currently I'm trying to build ANTs with:

```
cmake
    -C /var/tmp/portage/sci-biology/ants-2.3.1-r1/work/ants-2.3.1_build/gentoo_common_config.cmake 
    -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr
    -DITK_DIR=/usr/include/ITK-5.0/
    -DUSE_SYSTEM_ITK=ON
    -DUSE_SYSTEM_VTK=ON
    -DBUILD_TESTING=OFF 
    -DCMAKE_BUILD_TYPE=Gentoo
    -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-biology/ants-2.3.1-r1/work/ants-2.3.1_build/gentoo_toolchain.cmake
    /var/tmp/portage/sci-biology/ants-2.3.1-r1/work/ANTs-2.3.1
```

And I get the following [build.log](https://github.com/ANTsX/ANTs/files/3193668/build.log). I'm having trouble finding the relevant cmake arguments by browsing the source code. Can you help me out?

**Comment by gdevenyi** [comment]
Okay. So here's the problem.

I see from the log you're trying to build v2.3.1 against a recent ITKv5.

ANTs is very tightly coupled to the ITK version and has had many fixes made to keep it working with the ITKv5 development.

You're going to need to build against either the specific commit of ITKv5 embedded in the SuperBuild, the build may work against v4.13.2.

If you want to build against newer ITK, you need to build newer ANTs master branch versions.

**Comment by TheChymera** [comment]
@gdevenyi it appears GCC-9 requires a newer ITK. Would it be possible to create some ANTs versioned pre-release which supports a GCC-9 dependency stack?

**Comment by gdevenyi** [comment]
I'm not in charge of tags or versions for ANTs. I'm just a contributor.

**Comment by TheChymera** [comment]
@TheChymera :'( oh well, in the absence of that, what commit would you recommend for me to get the ANTs stack to work with GCC-9?

**Comment by gdevenyi** [comment]
As per my suggestions earlier, build master instead of a year old tag.

**Comment by TheChymera** [comment]
@gdevenyi well, master is live. That is ok for some users, but bad for reproducing specific results. Any particular commit I should go for?

**Comment by TheChymera** [comment]
I think this is mostly dealt with. ITK has a number of options for using system libs instead of bundling them. Perhaps some things are still hard-bundled, but I haven't noticed any.
