### ISSUE TITLE
Register fMRI image in lower resolution

### ISSUE THREAD

**Issue by sento4000** [ANTsX/ANTs#613]
Hi,

So I am trying to register a fMRI image of 3x3x3mm to MNI space going through anatomical space. Thing is that, if using an FSL MNI template of 3x3x3mm my registration is bad whereas using a 1x1x1mm MNI template I get a perfect registration. However, I do not want my fMRI image to be in 1x1x1mm resolution in the MNI space, because I am clearly oversampling my data. Is there a way to directly register the image in 3x3x3mm resolution using the 1x1x1mm registration directly without having to downsample the 1x1x1mm fMRI MNI image created by antsApplyTransforms. 

Any suggestions? Thanks in advance.

**Comment by stnava** [comment]
pass the 3mm version to the -r parameter of antsApplyTransforms after you
run the antsRegistration at 1mm


brian

**Comment by sento4000** [comment]
Thanks, Brian, i wasn't aware this was compatible.
