### ISSUE TITLE
How can I register DSC images and rCBV maps to T1-weighted contrast-enhanced images?

### ISSUE THREAD

**Issue by kyuchoi** [ANTsX/ANTs#616]
Hi Nick,

How can I register 4D DSC images and rCBV maps to 3D T1-weighted contrast-enhanced images?
Is there any recommended pipeline doing this?
Actually I'm trying to register DSC images (as well as rCBV maps) with partially covered brain, which seems to make a lot of problems.
Is it recommended to register the initial volume of 4D DSC images to 3D T1-weighted contrast-enhanced images via b0 (diffusion-weighted image) or not?
**_Above all, I cannot register rCBV maps properly to 3D T1-weighted contrast-enhanced images at all._**
Do I have to something else to solve this problem?
Thank you in advance!

All the best,
Kyu Sung

**Comment by stnava** [comment]
since we have not seen your data, it's tough to make a recommendation.   you may need a custom pipeline for this type of data.    these may help you get started on such a pipeline:

https://github.com/ANTsX/ANTs/issues/400

https://github.com/ANTsX/ANTs/wiki/Tips-for-improving-registration-results

as always, we request that you share data if you want more detailed help.

**Comment by kyuchoi** [comment]
Hi stnava,

I uploaded what I've got.
The data is from the cancer imaging archive (TCIA): TCGA-GBM, and TCGA-LGG dataset. 
[](http://www.cancerimagingarchive.net/)
I've downloaded T1, T2, T1ce, FLAIR images as well as 4D DSC images, and made 3D rCBV maps from them.
When you open the DSC file, you can see the brain is only partially covered.
Could you please give me more specific information then (esp. registering rCBV maps to T1WI) ?
Thank you in advance!
All the best,
Kyu Sung

[TCGA-06-0142_CBV_1mm.nii.gz](https://github.com/ANTsX/ANTs/files/2240650/TCGA-06-0142_CBV_1mm.nii.gz)
[TCGA-06-0142_flair.nii.gz](https://github.com/ANTsX/ANTs/files/2240651/TCGA-06-0142_flair.nii.gz)
[Uploading TCGA-06-0142_t1.nii.gz…]()
[Uploading TCGA-06-0142_t1ce.nii.gz…]()
[Uploading TCGA-06-0142_t2.nii.gz…]()
[Uploading TCGA-06-0142_b0.nii.gz…]()
[Uploading TCGA-06-0142_DSC.nii.gz…]()

**Comment by stnava** [comment]
regarding partial registration, see 

https://github.com/ANTsX/ANTs/issues/400

which is similar to your situation.
