### ISSUE TITLE
ITK hyperthreading utility

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTs#620]
Is hyperthreading useful in ITK, i.e., the use of 2 threads coming from a single CPU core? Is it similar or different from having 2 separate CPU cores not hyperthreaded?

Background:
I am asking this because I am setting up gridengine in a workstation. Most admins disable hyperthreading in computing clusters because it doesn't help computations. However, there are cases when the admin keeps hyperthreading on, so that if user asks for 1 computing slot, he can take the full CPU core, which has 2 threads. These threads can be used by programs that benefit the most from hyperthreading. The question, therefore, is whether ITK indeed benefits from hyperthreading, or it requires separate computing cores to benefit from parallelization. I am asking because the ITK variable specifically talks about threads, `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS`.

**Comment by cookpa** [comment]
It might depend on the application, see

  https://github.com/ANTsX/ANTs/issues/604

Also there have been some threading changes in ITKv5:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/ITK5MigrationGuide.md

It is probably worth profiling in your own environment.

**Comment by dorianps** [comment]
Thanks @cookpa 

Will need to check the two variants with the new ITKv5 then (using just cores or double the number using threads).

Closing.
