### ISSUE TITLE
Timeout when cloning ITKv5

### ISSUE THREAD

**Issue by 0rC0** [ANTsX/ANTs#621]
While compiling I receive a  Connection timed out error. I think it depends on, that I'm behind a proxy.

I'm following, as suggested, this [howto](https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/):

```
$ git clone https://github.com/ANTsX/ANTs.git
Cloning into 'ANTs'...
remote: Counting objects: 21340, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 21340 (delta 69), reused 95 (delta 65), pack-reused 21226
Receiving objects: 100% (21340/21340), 19.21 MiB | 15.11 MiB/s, done.
Resolving deltas: 100% (14747/14747), done.
Checking connectivity... done.

$ cd ANTs/
$ mkdir antsbin
$ ccmake ..
$ make -j8
[  5%] Performing download step (git clone) for 'ITKv5'
Cloning into 'ITKv5'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection timed out
github.com[1: 192.30.253.112]: errno=Connection timed out

```

**Comment by gdevenyi** [comment]
Problem with your internet or GitHub, not ants

**Comment by 0rC0** [comment]
@gdevenyi, my `git clone` command works, just in the ANTs' compiling routine it fails (it's the only case so far). 

I was wondering if there are differences...maybe it tries to clone via SSH, so port 22?

**Comment by gdevenyi** [comment]
Take a look at the cmake options, you can switch the clone type.

**Comment by gdevenyi** [comment]
Also, still an issue with your internet, both protocols *should* work.

**Comment by 0rC0** [comment]
Option found.
For the future searches (working behind a proxy or firewall is very common in an academic or corporate and often/always the researcher or local sysadmin cannot modify it):

There is in cmake an option called:
`SuperBuild_ANTS_USE_GIT_PROTOC`
with description:
`SuperBuild_ANTS_USE_GIT_PROTOCOL: If behind a firewall turn this off to use http instead.`

The issue is solved. I close it.
It has to be turned off

**Comment by noisyPixel** [comment]
Even after turning SuperBuild_ANTS_USE_GIT_PROTOCOL, it gets stuck at the same point. 5%.
Anyone else facing this problem?

**Comment by gdevenyi** [comment]
Github or network issue. Not an ANTs issue.

**Comment by kr94-ketch** [comment]
> Even after turning SuperBuild_ANTS_USE_GIT_PROTOCOL, it gets stuck at the same point. 5%.
> Anyone else facing this problem?

Have you figure it out finally

**Comment by kr94-ketch** [comment]
> Github or network issue. Not an ANTs issue.

I met the same problem.I am sure it is not because my internet

**Comment by cookpa** [comment]
Try

```
git config --global url."https://".insteadOf git://
```

**Comment by kr94-ketch** [comment]
> git config --global url."https://".insteadOf git://

I have tried that ,did not work,it is still stuck at 5%

**Comment by MengxingLiu** [comment]
@kr94-ketch   Did you finally make it working? I got the same problem.

**Comment by drs-m** [comment]
I got the same problem

**Comment by imansarwar** [comment]
> Even after turning SuperBuild_ANTS_USE_GIT_PROTOCOL, it gets stuck at the same point. 5%. Anyone else facing this problem?

same problem. Have you found a solution for it?

**Comment by cookpa** [comment]
You can try to get more information with

`export GIT_TRACE=1`
