### ISSUE TITLE
Add the random_seed option in antsRegistrationSyn

### ISSUE THREAD

**Issue by GuillaumeTh** [ANTsX/ANTs#626]
It could be nice to add the random_seed option in antsRegistrationSyn.

Moreover, do you test the reproducibility in multithreading of the registration with a seed. I'm not sure but I think it's not reproducible. Using 1 thread is the solution ?

**Comment by cookpa** [comment]
Yes, I should add that option to the script.

Multithreading will result in some non-reproducibility, but I think this is fairly small. More information here

https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues

For quick registration, the differences introduced by threading with a fixed seed were pretty minimal.

**Comment by GuillaumeTh** [comment]
Ok thanks for your quick response.

**Comment by cookpa** [comment]
Option should be there now (https://github.com/ANTsX/ANTs/commit/5675e454dd2fc4644417372fd507bfdeea7f9c77)

**Comment by GuillaumeTh** [comment]
Thanks
