### ISSUE TITLE
antsRegistration seems to exit stages prematurely

### ISSUE THREAD

**Issue by thefabus** [ANTsX/ANTs#629]
Hello,

I tried to run antsRegistration with the following command:
`export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=36; antsRegistration --verbose 1 -d 3 --float 1 -o [test_ANTs_Elavl3-H2BRFP_rot/test_,test_ANTs_Elavl3-H2BRFP_rot/test_Warped.nrrd] --use-histogram-matching 0 -r [Elavl3-H2BRFP_rot.nrrd,23_0100_ANTs_Elavl3-H2BRFP_rot/test.nrrd,1] -t Rigid[0.1] -m MI[Elavl3-H2BRFP_rot.nrrd,23_0100_ANTs_Elavl3-H2BRFP_rot/test.nrrd,1,32,Regular,1.0] -c [500x500x500x0,1e-10,10] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1 -t Affine[0.1] -m MI[Elavl3-H2BRFP_rot.nrrd,23_0100_ANTs_Elavl3-H2BRFP_rot/test.nrrd,1,32,Regular,1.0] -c [200x200x200x0,1e-10,10] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1`

See attached file for the output:
[log.txt](https://github.com/ANTsX/ANTs/files/2339593/log.txt)

What confuses me, some stages exit before the convergence threshold is met. I tried several things: 

- number of threads=1
- set threshold to 1e-20
- change window size to 5 or 40

In all those cases the issue persists. When changing the threshold to -1, all iterations are always executed (as expected). From the output I also can't confidently infer what "the change in MI value for the last 10 iterations" really means. I hope this is enough information to illustrate the issue.

Regards,
Fabian

**Comment by gdevenyi** [comment]
Maybe this is an issue:
```
--float 1
```

**Comment by thefabus** [comment]
Thanks for the suggestion. I retried with --float 0, but the behaviour stays the same.

**Comment by ntustison** [comment]
I'd like to see the log file for window size = 40.

**Comment by thefabus** [comment]
[log_40.txt](https://github.com/ANTsX/ANTs/files/2340332/log_40.txt)

Here you go.

**Comment by ntustison** [comment]
Thanks.  Can I also see the log file for threshold = -1?

**Comment by thefabus** [comment]
[log_neg1.txt](https://github.com/ANTsX/ANTs/files/2340478/log_neg1.txt)

One can see that at some points the metric does not improve, so it would be reasonable to exit the stage at that point. However, I assumed the condition to be 'convergence < threshold', am I mistaken?

**Comment by ntustison** [comment]
Thanks for the log.  This is what I would expect.  You're correct on the condition but the last set of numbers before it exits isn't printed to the screen which is why you're not seeing that condition being met.

**Comment by thefabus** [comment]
Ok that makes sense. Would be nice then if all lines were printed to avoid confusion, but if you know that then it's not a big deal really.
