### ISSUE TITLE
"Tranform"s in composite transforms file

### ISSUE THREAD

**Issue by effigies** [ANTsX/ANTs#631]
I was looking into the ANTs HDF5 composite transforms file format, and noticed a typo.

```Python
import h5py

file = File(fname, 'r')
list(file.get('TransformGroup/1').keys())
```

Yields (note the lack of "s" in `Tranform[Fixed]Parameters`):

```Python
['TranformFixedParameters', 'TranformParameters', 'TransformType']
```

Not sure if this is known and accepted, or a thing that y'all would want to fix. Might not be worth the hassle of supporting multiple versions at this point. But it took me a while to figure out why I couldn't `.get('TransformFixedParameters')`, so figured at least creating this issue could serve as documentation.

**Comment by effigies** [comment]
I'll also note the typo appears in several places in this repository:

https://github.com/ANTsX/ANTs/search?q=tranform&unscoped_q=tranform

**Comment by ntustison** [comment]
I'm all for correcting this.  @hjmjohnson -- do you see any problems with fixing this?

**Comment by effigies** [comment]
Feel free to upstream it. If I get to it first next week, I'll post a link to the topic here.

**Comment by ntustison** [comment]
http://review.source.kitware.com/#/c/23680/1/Modules/IO/TransformHDF5/src/itkHDF5TransformIO.cxx

**Comment by gdevenyi** [comment]
Updated patchset at http://review.source.kitware.com/#/c/23684/

@effigies I think your reader is going to have to check for both spellings, since there are likely going to be transforms out there with the old spelling for a long time.

**Comment by effigies** [comment]
Yeah, agreed. That's part of why I wasn't sure people would be interested in fixing it. Thanks for looking into this, all.
