### ISSUE TITLE
N4Biascorrection fails when using the mask option

### ISSUE THREAD

**Issue by zeydabadi** [ANTsX/ANTs#633]
Hello all,

I have the same problem mentioned [here](https://github.com/ANTsX/ANTs/issues/396) but even after running  `CopyImageHeaderInformation eddy_corrected_dataup.nii.gz hifi_nodifupdn_brain_mask.nii.gz copied_header.nii.gz 1 1 1 0` I receive the same error:
` N4BiasFieldCorrection -d 3 -x ./copied_header.nii.gz -i ./eddy_corrected_dataup.nii.gz -o ./test_out.nii.gz -v

Running N4 for 3-dimensional images.

Exception caught:
itk::ExceptionObject (0x2c1a7c0)
Location: "unknown"
File: /data1/lib/build/ANTS/CentOS7/antsbin/ITKv5-install/include/ITK-5.0/itkImageToImageFilter.hxx
Line: 240
Description: itk::ERROR: N4BiasFieldCorrectionImageFilter(0x2c044e0): Inputs do not occupy the same physical space!
InputImage Origin: [-9.5968330e+01, 7.5178741e+01, -4.6519180e+01], InputImage_1 Origin: [-9.5723050e+01, 7.0265378e+01, -4.5940466e+01]
        Tolerance: 8.0000000e-06
InputImage Direction: 1.0000000e+00 0.0000000e+00 0.0000000e+00
0.0000000e+00 1.0000000e+00 0.0000000e+00
0.0000000e+00 0.0000000e+00 1.0000000e+00
, InputImage_1 Direction: 9.9634532e-01 8.5416688e-02 -1.9561758e-06
8.2807286e-02 -9.6590231e-01 2.4530730e-01
-2.0951447e-02 2.4441094e-01 9.6944537e-01

        Tolerance: 1.0000000e-06`

Can someone help me with this problem, please?

**Comment by ntustison** [comment]
Did you actually verify that ``copied_header.nii.gz`` has the same header information as ``eddy_corrected_dataup.nii.gz`` after using ``CopyImageHeaderInformation``?

**Comment by zeydabadi** [comment]
I use the sets of FSL commands to compare the headers:

`fslhd eddy_corrected_dataup.nii.gz > eddy.hdr
fslhd hifi_nodifupdn_brain_mask.nii.gz > mask.hdr
CopyImageHeaderInformation eddy_corrected_dataup.nii.gz hifi_nodifupdn_brain_mask.nii.gz copied_header.nii.gz 1 1 1 0
fslhd copied_header.nii.gz > ANTmask.hdr
fslcpgeom eddy_corrected_dataup.nii.gz hifi_nodifupdn_brain_mask.nii.gz -d
fslhd hifi_nodifupdn_brain_mask.nii.gz > FSLmask.hdr`

and here is the results:
comparing the original headers:
` diff eddy.hdr mask.hdr
1c1
< filename       eddy_corrected_dataup.nii.gz
---
> filename       hifi_nodifupdn_brain_mask.nii.gz
5c5
< dim0           4
---
> dim0           3
9c9
< dim4           67
---
> dim4           1
57,59c57,59
< sto_xyz:1      -1.992691  -0.170834  -0.000000  98.968330
< sto_xyz:2      -0.165614  1.931805  -0.490615  -72.178741
< sto_xyz:3      -0.041907  0.488822  1.938891  -49.519180
---
> sto_xyz:1      -1.992691  -0.170833  0.000004  98.968330
> sto_xyz:2      -0.165615  1.931805  -0.490615  -72.178741
> sto_xyz:3      -0.041903  0.488822  1.938891  -49.519180`

comparing when I copied the headers using the `CopyImageHeaderInformation `:

`diff eddy.hdr ANTmask.hdr
1c1
< filename       eddy_corrected_dataup.nii.gz
---
> filename       copied_header.nii.gz
9c9
< dim4           67
---
> dim4           1
14c14
< time_units     s
---
> time_units     Unknown
55,63c55,63
< sform_name     Scanner Anat
< sform_code     1
< sto_xyz:1      -1.992691  -0.170834  -0.000000  98.968330
< sto_xyz:2      -0.165614  1.931805  -0.490615  -72.178741
< sto_xyz:3      -0.041907  0.488822  1.938891  -49.519180
< sto_xyz:4      0.000000  0.000000  0.000000  1.000000
< sform_xorient  Right-to-Left
< sform_yorient  Posterior-to-Anterior
< sform_zorient  Inferior-to-Superior
---
> sform_name     Unknown
> sform_code     0
> sto_xyz:1      0.000000  0.000000  0.000000  0.000000
> sto_xyz:2      0.000000  0.000000  0.000000  0.000000
> sto_xyz:3      0.000000  0.000000  0.000000  0.000000
> sto_xyz:4      0.000000  0.000000  0.000000  0.000000
> sform_xorient  Unknown
> sform_yorient  Unknown
> sform_zorient  Unknown
66c66
< descrip        5.0.11
---
> descrip`

and comparing the headers when I copied the headers using `fslcpgeom`:
` diff eddy.hdr FSLmask.hdr
1c1
< filename       eddy_corrected_dataup.nii.gz
---
> filename       hifi_nodifupdn_brain_mask.nii.gz
5c5
< dim0           4
---
> dim0           3
9c9
< dim4           67
---
> dim4           1`

So, looks like that the `fslcpgeom` does a better job but even that does not solve the problem.

**Comment by ntustison** [comment]
Mixing tools can be problematic.  See [here](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F) for an example and one which might be pertinent here.  Please use ``PrintHeader`` in ANTs to verify.

**Comment by zeydabadi** [comment]
Yes, I know that mixing tools can be problematic but at the moment it's unavoidable.

Here is the info:
 ```
PrintHeader eddy_corrected_dataup.nii.gz
 Spacing [2, 2, 2, 1]
 Origin [-98.9683, 72.1787, -49.5192, 0]
 Direction
0.996345 0.0854167 -1.95618e-06 0
0.0828073 -0.965902 0.245307 0
-0.0209514 0.244411 0.969445 0
0 0 0 1

 Size : [92, 92, 56, 67]

  Image Dimensions   : [92, 92, 56, 67]
  Bounding Box       : {[-98.9683 72.1787 -49.5192 0], [85.0317 256.179 62.4808 67]}
  Voxel Spacing      : [2, 2, 2, 1]
  Intensity Range    : [-0, 2178.74]
  Mean Intensity     : 65.072
  Direction Cos Mtx. :
0.996345 0.0854167 -1.95618e-06 0
0.0828073 -0.965902 0.245307 0
-0.0209514 0.244411 0.969445 0
0 0 0 1

  Voxel->RAS x-form  :
  Image Metadata:
    ITK_FileNotes = 5.0.11
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    descrip = 5.0.11
    dim[0] = 4
    dim[1] = 92
    dim[2] = 92
    dim[3] = 56
    dim[4] = 67
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 2
    pixdim[2] = 2
    pixdim[3] = 2
    pixdim[4] = 1
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 1
    qform_code_name = NIFTI_XFORM_SCANNER_ANAT
    qoffset_x = 98.9683
    qoffset_y = -72.1787
    qoffset_z = -49.5192
    quatern_b = -0.0424198
    quatern_c = 0.991425
    quatern_d = 0.123488
    scl_inter = 0
    scl_slope = 1
    sform_code = 1
    sform_code_name = NIFTI_XFORM_SCANNER_ANAT
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = -1.99269 -0.170834 -7.45058e-09 98.9683
    srow_y = -0.165614 1.9318 -0.490615 -72.1787
    srow_z = -0.0419068 0.488822 1.93889 -49.5192
    toffset = 0
    vox_offset = 352
    xyzt_units = 10
```
 ```
PrintHeader copied_header.nii.gz
 Spacing [2, 2, 2]
 Origin [-98.9683, 72.1787, -49.5192]
 Direction
0.996345 0.0854167 -1.95618e-06
0.0828073 -0.965902 0.245307
-0.0209514 0.244411 0.969445

 Size : 92 92  56

  Image Dimensions   : [92, 92, 56]
  Bounding Box       : {[-98.9683 72.1787 -49.5192], [85.0317 256.179 62.4808]}
  Voxel Spacing      : [2, 2, 2]
  Intensity Range    : [0, 1]
  Mean Intensity     : 0.20569
  Direction Cos Mtx. :
0.996345 0.0854167 -1.95618e-06
0.0828073 -0.965902 0.245307
-0.0209514 0.244411 0.969445

  Voxel->RAS x-form  :
  Image Metadata:
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    dim[0] = 4
    dim[1] = 92
    dim[2] = 92
    dim[3] = 56
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 2
    pixdim[2] = 2
    pixdim[3] = 2
    pixdim[4] = 1
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 1
    qform_code_name = NIFTI_XFORM_SCANNER_ANAT
    qoffset_x = 98.9683
    qoffset_y = -72.1787
    qoffset_z = -49.5192
    quatern_b = -0.0424198
    quatern_c = 0.991425
    quatern_d = 0.123488
    scl_inter = 0
    scl_slope = 1
    sform_code = 0
    sform_code_name = NIFTI_XFORM_UNKNOWN
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = 0 0 0 0
    srow_y = 0 0 0 0
    srow_z = 0 0 0 0
    toffset = 0
    vox_offset = 352
    xyzt_units = 2
```
```
PrintHeader hifi_nodifupdn_brain_mask.nii.gz
 Spacing [2, 2, 2]
 Origin [-98.9683, 72.1787, -49.5192]
 Direction
0.996345 0.0854167 -1.95618e-06
0.0828073 -0.965902 0.245307
-0.0209514 0.244411 0.969445

 Size : 92 92  56

  Image Dimensions   : [92, 92, 56]
  Bounding Box       : {[-98.9683 72.1787 -49.5192], [85.0317 256.179 62.4808]}
  Voxel Spacing      : [2, 2, 2]
  Intensity Range    : [0, 1]
  Mean Intensity     : 0.20569
  Direction Cos Mtx. :
0.996345 0.0854167 -1.95618e-06
0.0828073 -0.965902 0.245307
-0.0209514 0.244411 0.969445

  Voxel->RAS x-form  :
  Image Metadata:
    ITK_FileNotes = 5.0.11
    bitpix = 32
    cal_max = 0
    cal_min = 0
    datatype = 16
    descrip = 5.0.11
    dim[0] = 3
    dim[1] = 92
    dim[2] = 92
    dim[3] = 56
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 2
    pixdim[2] = 2
    pixdim[3] = 2
    pixdim[4] = 1
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 1
    qform_code_name = NIFTI_XFORM_SCANNER_ANAT
    qoffset_x = 98.9683
    qoffset_y = -72.1787
    qoffset_z = -49.5192
    quatern_b = -0.0424198
    quatern_c = 0.991425
    quatern_d = 0.123488
    scl_inter = 0
    scl_slope = 1
    sform_code = 1
    sform_code_name = NIFTI_XFORM_SCANNER_ANAT
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = -1.99269 -0.170834 -7.45058e-09 98.9683
    srow_y = -0.165614 1.9318 -0.490615 -72.1787
    srow_z = -0.0419068 0.488822 1.93889 -49.5192
    toffset = 0
    vox_offset = 352
    xyzt_units = 10
```

**Comment by ntustison** [comment]
``eddy_corrected_dataup.nii.gz`` is a four-dimensional image.

**Comment by zeydabadi** [comment]
I was using `dwibiascorrection` in MRTRIX and as they [recommended ](https://mrtrix.readthedocs.io/en/latest/fixel_based_analysis/st_fibre_density_cross-section.html)with the -ants switch and over there I used a 3D mask.

**Comment by ntustison** [comment]
In general, you can’t process mixed images of different dimensionalities.  For example, you can’t copy a header of a four dimensional image into a three-dimensional image.

**Comment by cookpa** [comment]
From the MRtrix page:

> Because we recommend a global intensity normalisation, bias field correction is required as a pre-processing step to eliminate low frequency intensity inhomogeneities across the image. DWI bias field correction is perfomed by first estimating the bias field from the DWI b=0 data, then applying the field to correct all DW volumes. This can be done in a single step using the dwibiascorrect script with the -ants option in MRtrix. The script uses a bias field correction algorithm available in ANTS (the N4 algorithm). Don’t use the -fsl option with this script in this fixel-based analysis pipeline. T

You could look at their scripts to confirm, but it looks like they are applying the correction to the b=0 image, then applying it to the rest of the images. So I think you want to run N4 on the b=0 image (or perhaps the average of all the b=0 images). This would be a 3D image with a corresponding 3D mask.

If you run `N4BiasFieldCorrection` with `-d 4`, it will attempt to fit a 4D bias field, and I don't think that makes sense.

**Comment by zeydabadi** [comment]
Philip,

That's correct and indeed that made me think that accepts a
N4BiasFieldCorrection 3D mask.

Thanks,
Mahmoud
