### ISSUE TITLE
Scripts: Greedy extension stripping removes parts of filenames

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#634]
Greedy extension stripping such as https://github.com/ANTsX/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L1330

Will remove parts of files that have "." in them. Such as

``Subject01.extracted.nii.gz``
will be stripped to
``Subject01``
instead of
``Subject01.extracted``

sed/awk with a list of possible extensions to strip or splitting using IFS or other methods would avoid this.

**Comment by coretemp** [comment]
You can better open an issue to replace the whole script. It should not be used by people.

**Comment by gdevenyi** [comment]
Closed by #658
