### ISSUE TITLE
antsRegistrationSyN.sh not using ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTs#635]
I was trying to use `antsRegistrationSyN.sh` in an SGE cluster, using `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS` to control the threads. But it doesn't look like it has an effect, the script always uses it's internal default and requires an explicit setting of `-n` argument to change the number of threads. 

```
dpustina@compute-0-0:dpustina$ echo $ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS
2
dpustina@compute-0-0:dpustina$ FIXED=/data/jux/dpustina/templates/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c.nii
dpustina@compute-0-0:dpustina$ MOVING=/data/jux/dpustina/templates/OASIS30/Brains/1000_3.nii.gz
dpustina@compute-0-0:dpustina$ antsRegistrationSyN.sh -d 3 -f $FIXED -m $MOVING -o /dev/null

--------------------------------------------------------------------------------------
 Mapping parameters
--------------------------------------------------------------------------------------
 ANTSPATH is /home/dpustina/antsbin/bin/

 Dimensionality:           3
 Output name prefix:       /dev/null
 Fixed images:             /data/jux/dpustina/templates/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c.nii
 Moving images:            /data/jux/dpustina/templates/OASIS30/Brains/1000_3.nii.gz
_Number of threads:_______1_
 Spline distance:          26
 Transform type:           s
 CC radius:                4
 Precision:                d
 Use histogram matching    0
======================================================================================
 antsRegistration call:
--------------------------------------------------------------------------------------
/home/dpustina/antsbin/bin//antsRegistration --verbose 1 --dimensionality 3 --float 0 --output [/dev/null,/dev/nullWarped.nii.gz,/dev/nullInverseWarped.nii.gz] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [0.005,0.995] --initial-moving-transform [/data/jux/dpustina/templates/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c.nii,/data/jux/dpustina/templates/OASIS30/Brains/1000_3.nii.gz,1] --transform Rigid[0.1] --metric MI[/data/jux/dpustina/templates/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c.nii,/data/jux/dpustina/templates/OASIS30/Brains/1000_3.nii.gz,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[0.1] --metric MI[/data/jux/dpustina/templates/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c.nii,/data/jux/dpustina/templates/OASIS30/Brains/1000_3.nii.gz,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform SyN[0.1,3,0] --metric CC[/data/jux/dpustina/templates/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c.nii,/data/jux/dpustina/templates/OASIS30/Brains/1000_3.nii.gz,1,4] --convergence [100x70x50x20,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox
--------------------------------------------------------------------------------------
All_Command_lines_OK
Using double precision for computations.
```
  
Is this how is it supposed to be or is it a bug? Looks like `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS` is replaced in the script by the `-n` argument without checking if `-n` was actually set by the user. https://github.com/ANTsX/ANTs/blob/master/Scripts/antsRegistrationSyN.sh#L394-L396

**Comment by cookpa** [comment]
I didn't write this so I can't tell you if its a feature or bug. My preferred order, highest priority first, is:

1. Command line option
2. Environment variable
3. Script default

I can set up a similar scheme for threads if everyone's agreeable.

**Comment by ntustison** [comment]
That's fine with me.

**Comment by gdevenyi** [comment]
@cookpa That's why I assume when interaction with such settings.

**Comment by hjmjohnson** [comment]
FYI: This can be tricky.  And changing the behavior in static variables from the command line (command line wrapper functions to project into R or other environments) (particularly when using shared libraries that are shared in one execution environment) is quite problematic.

We had an issue with the Slicer tool where BRAINSTools would be called with a single thread to reset the ITK Global number of threads, and then all of the reset of Slicer became single threaded!

https://github.com/BRAINSia/BRAINSTools/blob/master/BRAINSCommonLib/BRAINSThreadControl.h
https://github.com/BRAINSia/BRAINSTools/blob/master/BRAINSCommonLib/BRAINSThreadControl.cxx

Feel free to copy/modify this solution in ANTs.

**Comment by stnava** [comment]
@muschellij2  in case you havent seen this discussion

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/pull/638

This fixes the scripts to use the value passed with `-n` first. If that fails, use ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS, and if that fails, run single thread.

This also enables multi-threading in the joint fusion scripts, which call `antsRegistrationSyN.sh`.

Hans' code additionally checks NSLOTS, would help for SGE / PBS users in the absence of ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS. We could also check SLURM_NPROCS. But I think it would only make sense to do more layers of checking if we could centralize the thread selection process somehow.

**Comment by gdevenyi** [comment]
My testing has previously found that "nproc" from coreutils is properly constrained by SLRUM/SGE etc
