### ISSUE TITLE
Worse quality for 4D data than 3D data using PartialSlabEpiT1ImageRegistration?

### ISSUE THREAD

**Issue by kyuchoi** [ANTsX/ANTs#636]
Hi, Nick

Thanks to your comments, I've used the code below to register my DSC data to T1 contrast enhanced image.
(https://github.com/ntustison/PartialSlabEpiT1ImageRegistration)
The sample data given in the above code was 3D fMRI data (i.e. 1 volume), which was working good.
However, when I test 4D DSC data with the code, I get worse registration quality than 3D DSC data (i.e. first volume).
1. Do I have to change the code with some option such as time-series input?
(more specifically,

antsRegistration --verbose 1 \
                 --dimensionality 3 \
                 --float 0 \
                 --interpolation Linear \
                 --use-histogram-matching 0 \
                 --winsorize-image-intensities [0.005,0.995] \
                 --output [${outputPrefix},${outputPrefix}Warped.nii.gz,${outputPrefix}InverseWarped.nii.gz] \
Above is the first part of the code, however, **what does the dimensionality 3 mean? is it the dimension of moving image or fixed image? or both the image should have the same dimension?**)

2. Do I have to **input non-skull stripped fMRI (or DSC) data** to the code?
Thanks in advance!
BR,
Kyu 

p.s. My 4D DSC data is too big to upload

**Comment by ntustison** [comment]
If you have a time series, it's no longer of dimensionality 3.  You could create a 4-D series of your T1 data using ``ImageMath ... TimeSeriesAssemble`` and do a 4-dimensional registration, ``antsRegistration -d 4 ...``. Or, conversely, you can disassemble the fMRI series and register each volume one-by-one.
