### ISSUE TITLE
Converting warp + affine to composite .h5 file

### ISSUE THREAD

**Issue by checkoutchap** [ANTsX/ANTs#641]
Hi there, 

I have some old affine + non-linear warps (a .nii.gz file for the non-linear warp, and a .txt file for the affine step) which were generated using ANTs version 1.9. 

I would like to convert these warps into a composite .h5 file, to be compatible with the most up to date version of ANTs. 

Is it possible to convert the separate .nii.gz + .txt files into a composite .h5 file? 

Thanks

**Comment by ntustison** [comment]
``CompositeTransformUtil``

**Comment by checkoutchap** [comment]
Great, thanks!
