### ISSUE TITLE
Tensor orientation strategy (and vectors too)

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#642]
I've been working a bit lately on translating tensor images between different software packages, which has led me to look at the ANTs code a bit. I think we have some inconsistencies that can lead to wrong results.

In `antsApplyTransforms`, a tensor image is rotated before resampling by the [CorrectImageTensorDirection](https://github.com/ANTsX/ANTs/blob/master/Examples/antsApplyTransforms.cxx#L35) function. But I think the transform is incorrect: 

```
MatrixType direction =
    movingTensorImage->GetDirection().GetTranspose() * referenceImage->GetDirection().GetVnlMatrix();
```

This looks backwards to me, because the direction cosine matrix of the reference image is on the right, then we apply the transpose of the moving image direction matrix. 

This would correct a tensor in the reference space by first transforming to physical space, then back into voxel space with the transpose (ie, inverse) of the moving image matrix.

But since we're resampling in the reference space, I think we'd want to do

```
MatrixType direction =
    referenceImage->GetDirection().GetTranspose() * movingTensorImage->GetDirection().GetVnlMatrix();
```
After warping, we need to apply a separate reorientation with `ReorientTensorImage`. This is distinct from the header transforms, and corrects for the rotation of the brain from the registration, via the Preservation of Principal Directions (PPD) algorithm. 

There's different ways we can handle this.

**Option 1: physical space throughout**

The `RebaseTensorImage` program by @jeffduda can be applied before warping, to orient the tensors in physical space. `antsApplyTransforms` and then `ReorientTensorImage` would be called afterwards, all working in physical space with no additional corrections. Then one could call `RebaseTensorImage` again to get back into voxel space.

**Option 2: Voxel space, with correction internally as needed by ANTs**

Tensors start off in the voxel space of the moving image. They are transformed to the voxel space of the reference image by `antsApplyTransforms`. Then `ReorientTensorImage` transforms to physical space, computes the PPD from the registration transforms (which are in physical space) and outputs the result in the voxel space.

My personal preference is for option 2, because dcm2niix will provide bvecs in the voxel space of the DWI image, as expected by FSL and several other tools.

**Comment by ntustison** [comment]
Hi @cookpa ,

Thanks for finding this.  I would simply defer to you and follow whatever you prefer.  

Nick

**Comment by stnava** [comment]
I am happy to defer to Phil & Jeff as well... it would be nice to see some
accompanying documentation of before and after these changes

**Comment by cookpa** [comment]
@stnava definitely. I have some experiments that I will make available. 

I think if you only look at FA, or if your fixed and moving space have identity transforms, you'd never notice the issue. 

I'm using some older data acquired with and without orthogonal imaging planes, that was used to validate `dcm2nii`. Also, warping things to a non-axial template (eg, OASIS) definitely highlights the problems.

**Comment by dorianps** [comment]
Since we are on this topic, I have a question. Can ANTs currently do
tensor-based registration?

Dorian

**Comment by cookpa** [comment]
Here's some tests with data. I haven't uploaded the results as they are fairly large.

I've used the Prisma data from here

https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging

which is distributed under a BSD license.

https://github.com/cookpa/antsDTOrientationTests

I think `ReorientTensorImage` works correctly, and the problem was incorrect orientation of the tensors within `antsApplyTransforms`. I will put up some screen shots and make a PR.

**Comment by cookpa** [comment]
The "ortho" series after rigid alignment to the OASIS template, viewd in fsleyes. Master:

![image](https://user-images.githubusercontent.com/611507/49767128-57582d00-fca5-11e8-9fc8-9bcec70e47be.png)

Proposed fix:

![image](https://user-images.githubusercontent.com/611507/49767130-5a531d80-fca5-11e8-9588-70ea752a3458.png)

The "roll" series (slices rotated about the A-P axis) registered to the "ortho" series. Master:

![image](https://user-images.githubusercontent.com/611507/49767294-ea916280-fca5-11e8-9cdc-64597ed2a16c.png)

Proposed fix:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/611507/49767300-f54bf780-fca5-11e8-929e-b6417bb09ac1.png">

**Comment by cookpa** [comment]
I updated the Wiki pages on tensor stuff. I think this bug is fixed now.

**Comment by ntustison** [comment]
Thanks for this, @cookpa

**Comment by cookpa** [comment]
A final note on this: the resampling / reorientation only works if the bvec coordinate system agrees with the voxel ordering. FSL requires left-handed (radiological) orientation for bvecs, regardless of the image orientation. This can result in left-right flips and problems for ANTs, which expects the tensors to be rotatable using the direction matrix in the NIFTI header. 

I am not sure of the best way to deal with this but I think getting the data into radiological orientation before processing is probably the best way, with careful validation to ensure that the resulting orientation of the brain in physical space is maintained.

**Comment by ihnorton** [comment]
Related discussion, in particular this comment: https://github.com/MRtrix3/mrtrix3/issues/1139#issuecomment-334934895
