### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by katedamme** [ANTsX/ANTs#644]
(Segmentation fault: 11).

Command Run:
ANTS 3 -m MI[c_struc_brain_masked.nii, SUIT.nii, 1, 32] -i 100x75x50
Command Output:
 Run Reg
 values 1
  Fixed image file: c_struc_brain_masked.nii
  Moving image file: SUIT.nii
Metric 0:  Not a Point-set
  Fixed image file: c_struc_brain_masked.nii
  Moving image file: SUIT.nii
  similarity metric weight: 1
  Radius: [32, 32, 32]
  radius: [32, 32, 32]
Segmentation fault: 11

**Comment by cookpa** [comment]
You might try `antsRegistrationSyNQuick.sh`, which may work or at least provide more informative output.

If you can provide data, I will try to investigate further.

**Comment by katedamme** [comment]
That command ran without error.

Unfortunately, the thing that is going to be irritating to you and I is
that I need to replicate a pipeline as exactly as possible. The previous
pipeline command was: "ANTS 3 -m MI[c_struc_brain_masked.nii, SUIT.nii, 1,
32] -i 100x75x50" and the expectation is that this would result in a Warp
image and an affline  transformation text file to warp masks contained in
SUIT to subject space using WarpImageMultiTransform to ultimately extract
label volumes.


Is there a way to use the antsRegistrationSyNQuick.sh command to get the
desired output? What would be the closest approximation of the previously
used command?

**Comment by cookpa** [comment]
An exact correspondence between `ANTS` and `antsRegistration` is probably not possible, but I've tried to provide some guidance here:

  https://github.com/ANTsX/ANTs/wiki/ANTS-and-antsRegistration

It may be possible to run `ANTS`. I think I see a problem in your command line now. There is no output option (-o) in your call to ANTS. Try adding that.

**Comment by cookpa** [comment]
Closing this because the `ANTS` call above works for me once you add an output prefix with `-o`. 

Feel free to re-open if you still have problems and can provide data for us to test.
