### ISSUE TITLE
N4BiasCorrection for 4D images (i.e. fMRI or multi-echo GRE) and apply bias correction

### ISSUE THREAD

**Issue by braincharter** [ANTsX/ANTs#647]
Hi guys, fantastic work, ANTs is amazing!

I've been using N4 for quite some time on 3D images, and I wanted to use it on fMRI and multi-echo GRE-MRI acquisitions. However, the fourth dimension seems to be treated as another spatial dimension and thus gives us weirdresults (and a tremendous padding in 't').

Is there a set of parameters which would work for 4D data? Now I'm processing one 3d at a time and stiching them back up, but for fMRI it seems to worsen the time series. More specifically, I'm not sure what to put for "-b" (I've try for 3D -b [200] or for 4D [1x1x1x200], where 200 is the number of 3D epi). Or if I should deactivate normalization.

Also, id the biasfield is computed from the first 3D image only, would it be possible to apply the extracted biasfield to all the time serie?

**Comment by ntustison** [comment]
Although N4 has 4-D capabilities, not much has been done with trying to figure out a set of parameters that work.

> Also, id the biasfield is computed from the first 3D image only, would it be possible to apply the extracted biasfield to all the time serie?

Yes.  See [here](https://github.com/ANTsX/ANTs/blob/master/Examples/N4BiasFieldCorrection.cxx#L445-L454).  Just divide the input volume by the bias field.
