### ISSUE TITLE
ANTS not building with ITKv5 - configure error

### ISSUE THREAD

**Issue by avapirev** [ANTsX/ANTs#648]
Hi,
I have installed ITV 4.13.1 and VTK 8.0.1 installed. When trying to use them I get a configure error:

-- SuperBuild - ANTS => Requires ITKv5,
-- SuperBuild -   ITKv5[OK]
CMake Error at SuperBuild/External_ITKv5.cmake:178 (find_package):
  Could not find a configuration file for package "ITK" that is compatible
  with requested version "5".

  The following configuration files were considered but not accepted:

    /software/ITK/4.13.1-foss-2018a-Python-2.7.14/lib/cmake/ITK-4.13/ITKConfig.cmake, version: 4.13.0

No matter which CMake I use it is all the same.
Any ideas?
Many thanks.

**Comment by cookpa** [comment]
Can you try the superbuild? It will install the correct ITK. I believe you can turn on VTK as well.

If you need ITK v4 you will need to check out an older ANTs. I think anything before June 2018 should work, based on the history here

https://github.com/ANTsX/ANTs/commits/master/Common.cmake
