### ISSUE TITLE
ANTs/ANTsR Brain Templates

### ISSUE THREAD

**Issue by kurodasho** [ANTsX/ANTs#651]
Hello,
I recently read your paper " Optimal Symmetric Multimodal Templates and Concatenated Random Forests for Supervised Brain Tumor Segmentation (Simplified) with ANTsR".And I am trying to implement  ANTs/ANTsR on BRATS 2013 3-D dataset to reproduce your  results.

1.I have download the "ANTs/ANTsR Brain Templates" which you provided at figshare include T1 symmetric template. Could you give me some details about how can I get the T2 and flair symmetric template?  

2.I have run your 2-D example with input seven brain/tumor tissue labels to creat RF model  and get good  segmentation result ,but not get a good result with BRATS2013 3-D data .I only input four tumor labels(edema,enhancing tumor...) with the construction of RF model .  Is  this a wrong input   cause my   result？How can I get seven brain/tumor tissue labels like your 2-D example? I have no idea about this currently. 

Thank you so much!

**Comment by ntustison** [comment]
Hi,

1)  You can download the other modalities from [here](https://drive.google.com/file/d/1tGETTazKUzkOy_00696WrFlfeJSc5GXp/view?usp=sharing).  Hey @stnava , a couple people have asked about the other modalities so I trie to upload a KirbyMultiModal archive to the ANTs/ANTsR Brain Templates on Figshare but I'm not a collaborator.  Can you make me a collaborator or upload this archive?  It's only ~250 MB.  

2) To get the seven labels for the brats data, I ran the training data through our brain segmentation protocol.  Check out the "stages" capabilities of the ``antsCorticalThickness.sh`` script.  [Here](https://github.com/ntustison/antsCorticalThicknessExample)'s an example.

Nick

**Comment by stnava** [comment]
i think you are listed as collaborator - but i cant find out how to check this or "upgrade" your status or anything.  i will download and add this file though as a stopgap measure.

**Comment by ntustison** [comment]
Thanks Brian.

**Comment by kurodasho** [comment]
> Thanks Brian.
Thank you for your help ! I have get segmentation label of csf ,corticalgm ,wm,deep gm  as you suggested with antsCorticalThickness,but how can I mask this segmentation results with  provided brats tumor label and finally  get the seven  labels?

**Comment by stnava** [comment]
you should open a new issue and ask this question more clearly if you are still wondering.
