### ISSUE TITLE
Problem of cloning int ’itkv5‘

### ISSUE THREAD

**Issue by gqaffect** [ANTsX/ANTs#653]
Hi, I am trying to install ANTs according to the instructions (https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS). However, I found out that it requires ITK Version 5, which is not public yet. 
I am using Linux 16.04 with GCC 5.4, and have turned off the `SuperBuild_ANTS_USE_GIT_PROTOC`. The report stopped at 'cloning into itkv5...' long time, and did not move. Here is the error that I got.
![image](https://user-images.githubusercontent.com/26057198/47264672-d9519280-d54d-11e8-97af-cf0ab9753b2b.png)

Thank you very much.

**Comment by cookpa** [comment]
The CMake option usually works for me but depending on the build options there might be some call to git that is not being correctly changed to https.

You could try

```
git config --global url."https://".insteadOf git://
```

but beware this will affect all calls to git, not just ANTs.

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/blob/ee49602fa0b58e0416078ef9d4f495a6df9776ba/SuperBuild.cmake#L20

**Comment by kr94-ketch** [comment]
I have met the same problem ,does anyone sovle it?
