### ISSUE TITLE
ROI Registration

### ISSUE THREAD

**Issue by 0rC0** [ANTsX/ANTs#657]
Hi all,

I'm having some trouble with registering ROI to a subject T1, I'm trying to do something similar to what is described [here](https://github.com/ANTsX/ANTs/wiki/simple-case:-T1-to-MNI-mapping-for-both-structure-and-pre-registered-fMRI). 

I register the FLAIR the ROIs come from with the using:
```
antsRegistrationSyNQuick.sh -d 3 -n 7 -f T1.nii.gz -m FLAIR.nii.gz -o XXX
```

when I apply the transformation from antsRegistrationSyn.sh to the FLAIR (the ROIs comes from it), everything works perfectly:

```
antsApplyTransforms -d 3 -r T1.nii.gz -i FLAIR.nii.gz -e 0 -t XXX1Warp.nii.gz -t XXX0GenericAffine.mat -o out_flair.nii.gz -v 1
```

when I try to register the ROI to the T1:

```
antsApplyTransforms -d 3 -r T1.nii.gz -i ROI.nii.gz -e 3 -t XXX1Warp.nii.gz -t XXX0GenericAffine.mat -o out_flair.nii.gz -v 1
```

the ROI is in another position as it was before... The same trasformation should bring my ROI in the same position respect the FLAIR. I tried also the command from [here](https://sourceforge.net/p/advants/discussion/840261/thread/69435569/), but no luck.

Maybe I'm doing some noob mistake I cannot notice.

Thanks in advance for any help/suggestion

**Comment by cookpa** [comment]
There are a few possibilities here but I could take a look if you can share data

**Comment by stnava** [comment]
Here is an ANTsPy example but it should be the same thing in regular ants.

https://github.com/ANTsX/ANTsPy/blob/master/tutorials/concatenateRegistrations.ipynb

**Comment by 0rC0** [comment]
I found some strange stuff with my ROIs.... maybe that is the problem. 
For now I close the issue
