### ISSUE TITLE
ANTs compiling on mac

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#660]
I am a bit confused when I was about to compile ANTs after reading the instructions for compiling ANTs on macOS.
CMake on Mac came with GUI. But there are a few options available.  
What option should I have to choose for 1) Generator: UNIX make or XCode, 2) compiler: DEFAULT NATIVE or SPECIFY NATIVE? 

Thanks in advance.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

**Comment by cookpa** [comment]
I don't change any defaults on my system (OS X High Sierra), except for the git protocol.

If you want to follow our instructions you can run the command line `ccmake`. Google suggests it should be in 

```
  /Applications/CMake.app/Contents/bin
```

**Comment by cookpa** [comment]
By default the binaries are statically built, so you can move them wherever you like. 

I don't think an ANTs build will interfere with ANTsR, which compiles its own ANTs internally. But ANTsR questions would be best asked on the ANTsR page.

https://github.com/ANTsX/ANTsR
