### ISSUE TITLE
ANTsR installation error

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#663]
Dear ANTsR users and developers,

I encountered the following error at my first attempt to install ANTsR on my Mac. 

> library(devtools)
> install_github("neuroconductor/ANTsR")
Downloading GitHub repo neuroconductor/ANTsR@master
Error in info[!to_ignore, ] : incorrect number of dimensions

Any helps would be appreciated.

Best,
SC

**Comment by ntustison** [comment]
This should be discussed over at the ANTsR repo.

**Comment by stnava** [comment]
use:

```
devtools::install_github( "ANTsX/ANTsR" )
```
