### ISSUE TITLE
antsRegistration Anatomical image to CBF image

### ISSUE THREAD

**Issue by Sailadd** [ANTsX/ANTs#669]
Hello everyone!

I'm trying to make a registration from a map of Labels (high resolution image) to a CBF image (low resolution image).
To do it, I'm using two steps:
- An affine registration with antsaffine.sh
- a SyN registration

Since registrations are usually made from a low resolution image to a high resolution image, my idea was to record the CBF image (CBF.nii.gz) on the Labels map(JLFLabels.nii.gz), and finally apply the inverse in the antsApplyTransforms command.

The four commands I use are as follows:

antsaffine.sh 3 JLFLabels.nii.gz CBF.nii.gz CBF2LabelsAff

WarpImageMultiTransform 3 CBF.nii.gz CBFaff.nii.gz -R JLFLabels.nii.gz CBF2LabelsAffdeformed.nii.gz CBF2LabelsAffAffine.txt

antsRegistrationSyN.sh -d 3 -f JLFLabels.nii.gz -m CBFaff.nii.gz -o oputCBFSyN

antsApplyTransforms -d 3 -o CBF2labels.nii.gz -i JLFLabels.nii.gz -r CBFaff.nii.gz -t oputCBFSyN1InverseWarp.nii.gz -t oputCBFSyN0GenericAffine.mat

I do not know if, above all, the last command can be written in a better way, but the images are completely deformed. I'd like to know if I'm proceeding in the right way.

Perhaps a Nearest Neighbor interpolation was needed or is there anything wrong with the commands above?

**Comment by cookpa** [comment]
The standard way to map different modalities intra-subject to a high-resolution anatomical image is basically first correct any modality-specific distortions, then rigidly align to the structural image using an appropriate metric (eg, mutual information) and a good initialization.

The images you pass to antsRegistration or the associated scripts should have as much anatomical information as possible. For ASL you would probably want the mean of the ASL time series. After computing and checking the alignment, you can use `antsApplyTransforms` to warp CBF into the structural space. Then you would apply ROIs to get mean CBF in the JLF labels, or whatever labels in the structural space you care to use.

**Comment by Sailadd** [comment]
ok, I thank you for the explanations.
I would like to understand if the right thing, also because I'm seeing everywhere on the tutorials that are occurring before making a recording.
For me, the initialization is in the related registration that I have implemented. The antsaffine command allows you to make the rigid or similar one, a second of the number of parameters that are inserted.
So, my first question is:

- should you first make a rigid registration and then a similar registration with an anistration and then switch to that SyN?
When you talk about initialization do you mean this?

On a site there is written:
"Initialization can be tested by performing a rigid registration with zero iterations, for example:

antsRegistration -d 3 -r [fixed.nii.gz, moving.nii.gz, 1] -t Rigid [0.1] \
-m MI [fixed.nii.gz, moving.nii.gz, 1, 32] -c 0 -f 4 -s 2 \
-o [movingInit, movingInit_deformed.nii.gz] "

Is this or is it initialized and is it tested with strict registration?

Another question that leaves me in doubt is the correction of distortions. All the anatomical images used in the recordings derive from the antsCorticalThickness.sh command, which I saw already contains a biasCorrection, so my second question is:

Is this correction sufficient, or is it necessary to carry out a further correction? If yes, always with the same command?

These questions will surely seem trivial, but unfortunately my times do not allow me to experience all that I would like in a meticulous way, so I prefer to ask direct questions.


Thank you so much for your answer.

**Comment by cookpa** [comment]
Bias and distortion are different things, the former affecting intensity, the latter affecting shape and intensity.

By initialization for (Modality X) -> (T1) I mean the starting point for the registration is as close to the true solution as possible. There's a variety of ways to do this, including the use of specialized tools to pre-process the data so that the registration to T1 can be more accurate. But at a minimum, you would want to ensure that the two images are correctly positioned. The use of ` -r [fixed.nii.gz, moving.nii.gz, 1] ` means that the center of mass of the two images will be aligned. This may or may not be the best solution, you have to try it out. See the usage for `antsRegistration` for other options.

`antsIntermodalityIntrasubject.sh` may be a good starting point, it will allow you to make some high level choices of transform (eg rigid, rigid + deformation, etc) with a sensible parameter set.

**Comment by Sailadd** [comment]
Ok, thank you very much for your suggestions.

I found the best solution for recording, running the affine and then the registrationSyN.

Now there is another problem, changing subject. It is upstream, and is with antsCorticalThickness. In fact, unlike before, the extraction does not take place correctly, because the extracted brain also contains external parts, which are not brain.
In the antsCorticalThickness.sh script, corrective parameters like convergence, etc. are already included, so running I have not added any other inputs beyond those specified in the example.
Do you think that, even there, I need to perform a pre-processing with my MT image (similar to T1) to avoid these problems?

Maybe N4BiasFieldCorrection could be a solution?

Thanks for your precious help.

**Comment by Sailadd** [comment]
![5scp-all_l](https://user-images.githubusercontent.com/45062720/48662357-5c003b80-ea81-11e8-9245-d57c467f9bc7.png)

This is my problem: the brain extraction takes parts out of the brain. Could you suggest me which are the parameters tha is better to change running the command, please?

**Comment by cookpa** [comment]
I'm not sure what's going on here, but if you can share the affected brain mask and template, I can take a look.
