### ISSUE TITLE
converting affine transformations between RAS and LPS coordinates

### ISSUE THREAD

**Issue by ruyuanzhang** [ANTsX/ANTs#672]
Hi, ANTs team
       It seems to me that convertTransformFile can convert an affine transformation from LPS (ANTs/AFNI) to RAS space (FSL/SPM). So that an affine transformation obtained from ANTS can be used in FSL. Do I understand it correctly?
       Also, can any utility tool can do the reverse conversion (RAS to LPS)?? 
       Thanks.

**Comment by ntustison** [comment]
It's not quite that simple because you also have to deal with the different file formats.  You're probably looking for @pyushkevich 's [c3d tool](https://github.com/pyushkevich/c3d/blob/master/utilities/AffineTransformTool.cxx) which can also handle the reverse conversion.
