### ISSUE TITLE
antsRegistration  ICBM-DTI-81 white-matter atlas to individual space

### ISSUE THREAD

**Issue by SHJDwu** [ANTsX/ANTs#676]
Hello everyone!

I'm trying to warp labels of white-matter regions in ICBM-DTI-81 WM atlas to individual space. To do it, I used antsRegistrationSyNQuick.sh. The command I used is as follows:

antsRegistrationSyNQuick.sh -d 3 -f 00216_FA.nii -m rICBM_DTI_81_WMPM_FMRIB58.nii -o WMPM_FMRIB58_to_FA

Then, the image was completely deformed.  Please, see attachments.
How can I register ICBM-DTI-81 white-matter atlas to individual space (FA)?
Thanks in advance for any help!

![individual fa](https://user-images.githubusercontent.com/45736532/49699884-e3b91000-fc11-11e8-9be3-f4216e84016d.jpg)
![ricbm_wm_atlas](https://user-images.githubusercontent.com/45736532/49699887-e7e52d80-fc11-11e8-9baa-c729050532de.jpg)
![icbm_atlas to individual fa](https://user-images.githubusercontent.com/45736532/49699952-c6387600-fc12-11e8-9997-4f5418183db9.jpg)

**Comment by ntustison** [comment]
These registration scenarios are quite common---propagating a set of labels to an unlabeled image.  Typically, though, you have a corresponding template or atlas in which your label image is defined.  One would then register the template to the unlabeled subject and then use the resulting transform to propagate the labels.  You would most likely never try to register your label image directly to the unlabeled image.  In your case, you should use the FMRIB58 FA template.

**Comment by cookpa** [comment]
Register the moving image to the template and then call `antsApplyTransforms` to apply the warp to the label image, examples here 

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians
