### ISSUE TITLE
How to choose antsApplyTransforms interpolation?

### ISSUE THREAD

**Issue by SHJDwu** [ANTsX/ANTs#677]
Hi Nick,
Thanks for your reply on my last issue. I am trying to warp multilabeled white-matter atlas to individual space using two steps.

1. antsRegistrationSyNQuick.sh -d 3 -f 00216_FA.nii -m FMRIB58_FA_1mm.nii -o FMRIB58_FA_to_FA

2. antsApplyTransforms -d 3 -i rICBM_DTI_81_WMPM_FMRIB58.nii -o atlas_to_individual_FA.nii -n MultiLabel -r 00216_FA.nii -t FMRIB58_FA_to_FA1Warp.nii -t FMRIB58_FA_to_FA0GenericAffine.mat

Finally, in the output image of the second step, the labels for corpus callosum  seem to be bigger than the corpus callosum of individual FA. Similarly, the labels for middle cerebellar peduncle slightly exceed middle cerebellar peduncle of individual FA.  I am not sure if the interpolation I selected is right. 

antsApplyTransforms interpolation include Linear, NearestNeighbor, MultiLabel[<sigma=imageSpacing>,<alpha=4.0>], Gaussian[<sigma=imageSpacing>,<alpha=1.0>], BSpline[<order=3>] , CosineWindowedSinc, WelchWindowedSinc, HammingWindowedSinc,  LanczosWindowedSinc,  GenericLabel[<interpolator=Linear>].  How to choose the right interpolation option? what does [<sigma=imageSpacing>,<alpha=4.0>] means and how to define it?

Thanks in advance for any help!
![individual fa](https://user-images.githubusercontent.com/45736532/49716547-ff163080-fc8e-11e8-924d-e0d5c6c98ad8.jpg)
![2018-12-10_152010](https://user-images.githubusercontent.com/45736532/49716592-27059400-fc8f-11e8-8fa4-f12af49400f9.jpg)
![ricbm_wm_atlas](https://user-images.githubusercontent.com/45736532/49716599-2b31b180-fc8f-11e8-86f6-5396765253b4.jpg)
![2018-12-10_145912](https://user-images.githubusercontent.com/45736532/49716610-308efc00-fc8f-11e8-9f7a-2d7e6b1c19e8.jpg)
![2018-12-10_145955](https://user-images.githubusercontent.com/45736532/49716615-34bb1980-fc8f-11e8-9aad-d055ef93428d.jpg)
The underlay image is individual FA and overlay image is the output image of the second step.

**Comment by ntustison** [comment]
Try "GenericLabel[Linear]" which generally works well and you won't have to worry about parameter choices.

**Comment by cookpa** [comment]
The Gaussian options are a sigma for smoothing, and a neighborhood parameter alpha. The smoothing kernel is cut off at a distance from the center defined by alpha. If you make this larger, then a wider neighborhood is used, in other words you include more voxels at the tail edges of the smoothing function. This makes the program take longer to run as small contributions from a wider radius need to be computed.

GenericLabel[Linear] works pretty well for most cases.

**Comment by tashrifbillah** [comment]
What maximum order of `BSpline[<order=3>]` does it support? Or is `3` the fixed order?

**Comment by cookpa** [comment]
Three is the default, but it should work for 0 to 5

https://itk.org/Doxygen/html/classitk_1_1BSplineInterpolateImageFunction.html

**Comment by tashrifbillah** [comment]
I made a serendipitous error and found out the acceptable orders:

> itk::ERROR: BSplineDecompositionImageFilter(0x30350c0): SplineOrder must be between 0 and 5. Requested spline order has not been implemented yet.
