### ISSUE TITLE
aMTC2.sh outputs files incorrectly if they contain '.' in filenames.

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTs#679]
when input images are named like:
msbl_104.AB_sham_01.nrrd
msbl_104.AB_sham_02.nrrd
msbl_104.AB_sham_03.nrrd...

command antsMultivariateTemplateConstruction2.sh -d 3 -o Template_ *.nrrd
outputs as 
Template_msbl_10400GenericAffine.mat 
Template_msbl_10410GenericAffine.mat
Template_msbl_10420GenericAffine.mat
(and so forth with other .nii.gz files as well), which causes issues with file identity.

**Comment by gdevenyi** [comment]
Fixed here https://github.com/ANTsX/ANTs/pull/658

Are you using the latest version of the script?

**Comment by SlicerMorph** [comment]
Probably not. I see changes are from November, my ants install is older than that. How can I check the script version?

**Comment by gdevenyi** [comment]
There's no intrinsic versioning in the script sadly.

You can just download the script directly and use it instead of your current copy.
