### ISSUE TITLE
Forward or inverse warps for warping images, points sets, or Jacobian calculation 

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#680]
Since this has come up a few times lately, I tried to write a simple combined reference for these issues with links to some relevant examples.

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

**Comment by ntustison** [comment]
Thanks @cookpa .  This is a great reference.

**Comment by wangken1994** [comment]
Dear Experts,

I did tensor image registration with `antsRegistrationSyNQuick.sh` and `antsApplyTransforms`. My codes are shown below:
**Step 1**
```
antsRegistrationSyNQuick.sh \
-d 3 \
-f 1.nii.gz \
-m 2.nii.gz \
-o 2to1 \
-t s
```
where both `1.nii.gz` and `2.nii.gz` are tensor images. And deforming the moving image to the fixed image with:
**Step 2**
```
antsApplyTransforms \
-d 3 \
-e 2 \
-i 2.nii.gz \
-r 1.nii.gz \
-o 2to1.nii.gz \
-t 2to11Warp.nii.gz \
-t 2to10GenericAffine.mat
``` 
However, my supervisor said to me that ANTs can't register tensor image directly, and I should register the FA image of the corresponding tensor image in **Step1**  and using the produced files to deform the tensor image in **Step2**. i.e.
**Step 3**
```
antsRegistrationSyNQuick.sh \
-d 3 \
-f 1-fa.nii.gz \
-m 2-fa.nii.gz \
-o 2to1fa \
-t s
```
**Step 4**
```
antsApplyTransforms \
-d 3 \
-e 2 \
-i 2.nii.gz \
-r 1.nii.gz \
-o 2to1.nii.gz \
-t 2to1fa1Warp.nii.gz \
-t 2to1fa0GenericAffine.mat
```
After the experiments, I found the registered results of these two methods were different. See the figures.
**Result of Step1-2**
![image](https://user-images.githubusercontent.com/34388336/59039646-c8b91700-88a7-11e9-900d-083a5ef6e7e4.png)
**Result of Step3-4**
![image](https://user-images.githubusercontent.com/34388336/59039850-2cdbdb00-88a8-11e9-82fd-1e43db8f488f.png)
So which registration method is more suitable for tensor image registration? Thanks in advance!

**Comment by cookpa** [comment]
Unfortunately there is not a tensor metric for registration, so you need to use a scalar derived from the DT (as in steps 3-4). If registering tensors directly (not using an intermediate structural MRI), FA is probably the best.

After resampling the tensor with `antsApplyTransforms`, you need to reorient them:

https://github.com/ANTsX/ANTs/wiki/Warp-and-reorient-a-diffusion-tensor-image

**Comment by wangken1994** [comment]
I got it! Thank you so much! @cookpa

**Comment by gdevenyi** [comment]
wiki page is good, can be closed here.
