### ISSUE TITLE
How to build a template image for my dataset?

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#681]
First of all, this is not an issue. I install Ants is very easy. Thanks for making a good tutorial. 
I have a customer dataset includes raw images (range from 0 to 1000) and label images (0-background, 1 is foreground). My dataset has 10 nii images (3D images) likes
Brain Data
```
001.nii (intensity)
001_label.nii
002.nii
002_label.nii
....
010.nii
010_label.nii
```

They are same resolution 1x1x1, same direction but did not align. It may different origin. I want to build a template for label images and template for intensity image. Which procedures should I do? If it is possible, please give me some script to run it in Ubuntu. I am a newbie of ANTs. Thanks all

**Comment by ntustison** [comment]
Before you do anything, you should make sure your image headers are consistent between your intensity images and the corresponding label images.  Use ``PrintHeader`` to investigate origin, direction, spacing, etc. information.  If there inconsistencies, you can fix them using ``CopyImageHeaderInformation``.

**Comment by John1231983** [comment]
@ntustison : Thanks. I have corrected it. I am using your script at https://github.com/ntustison/TemplateBuildingExample . I used the change the file `templateCommandMultivariateBSplineSyN.sh` likes below to work on the 3D image. `d` from 2 to 3 and `${inputPath}/OASIS*.nii.gz` to `${inputPath}/0*.nii.gz`. Anything else? Thanks

```
inputPath=${PWD}/
outputPath=${PWD}/TemplateMultivariateBSplineSyN/

${ANTSPATH}/antsMultivariateTemplateConstruction2.sh \
  -d 3 \
  -o ${outputPath}T_ \
  -i 4 \
  -g 0.2 \
  -j 2 \
  -c 0 \
  -k 2 \
  -w 1x1 \
  -f 8x4x2x1 \
  -s 3x2x1x0 \
  -q 100x70x50x10 \
  -n 1 \
  -r 1 \
  -l 1 \
  -m CC[2] \
  -t BSplineSyN[0.1,26,0] \
  ${inputPath}/0*.nii.gz

```

**Comment by ntustison** [comment]
You should try that and see if it works for your data.

**Comment by John1231983** [comment]
@ntustison : It is running now. I am using intensity image to make an intensity template. If I use binary images to make a binary template. Is it possible?

**Comment by cookpa** [comment]
After you have built a satisfactory template, you can use the warps from the structural images to transform the corresponding binary images to the template space. Then you can combine them with majority voting or `antsJointFusion`.

**Comment by John1231983** [comment]
@cookpa : How if I only have binary images and I want to construct the template of the binary images. It looks register them to common space and average together. Is it possible?

**Comment by cookpa** [comment]
When you register image A to image B, then you can call `antsApplyTransforms` to apply the warps to any images in the same **physical** space as images A and B. 

So as long as your labels are in the same physical space as the structural images, you can use the registration of the structural image to the template to warp the labels to the template.

**Comment by John1231983** [comment]
@cookpa : Could I ask you one question about the template? Do we need to keep the original coordinate (physical coordinate) when performing template construction? I have changed the coordinate of all images to 0,0,0 when performing template construction. If we need to keep the physical coordinate, I will do it again. Thanks

**Comment by cookpa** [comment]
You can adjust the template's origin with `SetOrigin`, and you can verify the resulting physical coordinates with ITK-SNAP. It would be best to place the origin somewhere that is close to the origin of the images you intend to register to the template.

**Comment by John1231983** [comment]
Thanks. But I meant that do you think keep original origin for template construction or change all origin to (0,0,0). Which one is better?
