### ISSUE TITLE
Problem using deformation fields in antsApplyTransforms

### ISSUE THREAD

**Issue by madeleinedacey** [ANTsX/ANTs#685]
What I am trying to accomplish:

1)Normalize my FA maps to FMRIB152_FA using antsRegistrationSyN.sh
2)Use the deformation fields from 1 to transform other scalar maps (MD and RD) to MNI space as well.

Since both scalar maps are generated from the same tensor image of the same subject, I figured that the same deformation would produce an image in the same space.

Step 1 code:

#!/bin/bash

for subj in ,<subject list> ; do # Loop through each subject. User must specify the subject file names.

antsRegistrationSyN.sh -d 3 -f FMRIB58_FA_1mm.nii.gz -m "$subj"_FA.nii -o "$subj"_MNI_

done # For subj

Step 1 went fine, it generated subj_0GenericAffine.mat files and subj_1Warp.nii.gz files. The FA maps were aligned beautifully to MNI space. I tried to apply the transforms to the MD and RD maps using the following:

for subj in <subject list> ; do # Loop through each subject. User must specify the subject file names.

#antsApplyTransforms -d dimension -i input image -r image space to transform to -n transform type -o output image name -t transforms

antsApplyTransforms -d 3 -i MD/"$subj"_MD.nii -r FA_ants/"$subj"_MNI_Warped.nii.gz -n BSpline -o MD/"$subj"_MNI_InverseWarped.nii -t [FA_ants/"$subj"_MNI_0GenericAffine.mat,1 ] -t [FA_ants/"$subj"_MNI_1InverseWarp.nii.gz,0]

antsApplyTransforms -d 3 -i RD/"$subj"_RD.nii -r FA_ants/"$subj"_MNI_Warped.nii.gz -n BSpline -o RD/"$subj"_MNI_InverseWarped.nii -t [FA_ants/"$subj"_MNI_0GenericAffine.mat,1 ] -t [FA_ants/"$subj"_MNI_1InverseWarp.nii.gz,0]

done 

This runs without errors but the result is not aligned to the warped FA maps or MNI space and seems to be strangely distorted too.

**Comment by cookpa** [comment]
> No description provided.

Can't do much with that but we recently added a Wiki page that might help with this general topic area

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

**Comment by madeleinedacey** [comment]
> > No description provided.
> 
> Can't do much with that but we recently added a Wiki page that might help with this general topic area
> 
> https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

I accidentally submitted before filling in the description. I am filling it in now. I'll take a look at that link also.

**Comment by cookpa** [comment]
OK, I think it ought to work with the forward warps:

```
antsApplyTransforms -d 3 -i MD/"$subj"_MD.nii -r FMRIB58_FA_1mm.nii.gz -n BSpline -o MD/"$subj"_MNI_Warped.nii  -t FA_ants/"$subj"_MNI_1Warp.nii.gz -t FA_ants/"$subj"_MNI_0GenericAffine.mat
```

It might be preferable to use the template rather than the warped FA image as the reference image. They should be identical for the purposes of this command but there can be precision errors in the NIFTI headers written by ITK. These are generally very small but can be annoying in later processing if they trigger errors about the images not being in the same space.
