### ISSUE TITLE
About affine transformation

### ISSUE THREAD

**Issue by taipingqu** [ANTsX/ANTs#691]
Dear expert, how do I use ANTs to do affine alignment based on my own template? Could you tell me the command?

**Comment by ntustison** [comment]
You can use ``antsRegistrationSyNQuick.sh``.   To get the help menu, use

```
$ antsRegistrationSyNQuick.sh -h 1
```

For an affine transform, you could do something like

```
$ antsRegistrationSyNQuick.sh -d 3 -t a -f ${fixedImage} -m ${movingImage} -o ${outputPrefix}
```

**Comment by taipingqu** [comment]
Hi,I use the command you gave above to do affine alignment, how to output affine.txt?

**Comment by cookpa** [comment]
We use the `.mat` format for affine transforms now. This will be produced by the `antsRegistrationSyNQuick.sh`. 

```
antsRegistrationSyNQuick.sh -d 3 -t a -f ${fixedImage} -m ${movingImage} -o ${outputPrefix}

antsApplyTransforms -d 3 -r ${fixedImage} -i ${movingImage} -t ${outputPrefix}0GenericAffine.mat
```

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians
