### ISSUE TITLE
ANTs binaries fail to access files in an SGE environment

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTs#692]
**Describe the bug**
This is a strange bug I can't find the where is it coming from. Any help is appreciated.
I use a workstation with the Sun Grid Engine to schedule jobs. For some reason ANTs binaries fail when are run within an SGE environment (qsub or qrsh/qlogin) but not when I run them directly on the system.  The binary works in itself, I can see the help text, but looks like they have a problem to access files. Yet, I can access files without a problem. old `ANTS` command or even with a simple `PrintHeader`. This is happening both with an old `ANTS` binary coming with the ASHS software, and with my newest from October 2018.

Here I am in a QRSH interactive session
```
[dorian@chdimri ~]$ PrintHeader template.nii.gz
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted (core dumped)
```
It looked initially the problem was accessing the file, but I could copy the file and even run c3d on it without a problem.
```
[dorian@chdimri ~]$ c3d template.nii.gz -info
Image #1: dim = [192, 256, 160];  bb = {[-101.208 76.0937 -57.1925], [86.2924 326.094 102.808]};  vox = [0.976562, 0.976562, 1];  range = [0.0014886, 6.8749];  orient = RPI
```
I also checked if moving the file in another volume would help, but it didn't.

And if I go out of the QRSH session everything works fine.
```
[dorian@chdimri ~]$ exit
logout
[dorian@chdimri ~]$ PrintHeader template.nii.gz
 Spacing [0.976562, 0.976562, 1]
 Origin [-101.208, 76.0937, -57.1925]
 Direction
1 0 0
0 -1 0
0 0 1

 Size : 192 256  160

  Image Dimensions   : [192, 256, 160]
  Bounding Box       : {[-101.208 76.0937 -57.1925], [86.2924 326.094 102.808]}
  Voxel Spacing      : [0.976562, 0.976562, 1]
  Intensity Range    : [0.0014886, 6.8749]
  Mean Intensity     : 1.03137
  Direction Cos Mtx. :
...
```

**To Reproduce**
Can't reproduce, happening in my system only.

**Expected behavior**
Commands should work.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: CENTOS 7 
 - Browser: NA
 - Version: centos-release-7-6.1810.2.el7.centos.x86_64 (Linux chdimri 3.10.0-957.1.3.el7.x86_64)
 - SGE version: 8.1.9

**Additional context**
This problem was discovered while trying to use ASHS rev103, which relies on `ANTS` calls via qsub to segment the hippocampi. ASHS uses it's own `ANTS` binary, but the result is the same, the command crashes just like with the new binaries.

**Anyone has an idea what is going on?**

**Comment by dorianps** [comment]
Ran `strace` to understand more about the error. Files are attached. Not sure what is going on, seem that the access to the file becomes unavailable in both failure and success cases, but for some reason it is re-established for the successful case outside SGE. Any idea?

![image](https://user-images.githubusercontent.com/9083517/50553272-ae806a80-0c71-11e9-9af7-c1631a01c33d.png)

[PrintHeaderSTRACEfail.txt](https://github.com/ANTsX/ANTs/files/2717657/PrintHeaderSTRACEfail.txt)
[PrintHeaderSTRACEsuccess.txt](https://github.com/ANTsX/ANTs/files/2717658/PrintHeaderSTRACEsuccess.txt)

**Comment by gdevenyi** [comment]
Accidental VTK linkage attempting an X/OpenGL init? Might explain why an interactive session works.

Check your build config?

**Comment by cookpa** [comment]
Memory?

> CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f1910f869d0, tls=0x7f1910f86700, child_tidptr=0x7f1910f869d0) = 14682
mmap(NULL, 268439552, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = -1 ENOMEM (Cannot allocate memory)

Try allocating more RAM to the job.

Also, you might try setting ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1 . I don't think this is the problem here but it can reduce memory usage as well as preventing any problems from threading across devices in a cluster environment.

**Comment by cookpa** [comment]
In the absence of any user guidance, ITK will default to the number of threads it detects on the system. On a cluster machine with a lot of cores, this can be a large number.

At CFN, this is handled automatically, `NSLOTS` is exported for every job (default 1) and there is also a default setting of `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$NSLOTS`.

**Comment by cookpa** [comment]
I guess `PrintHeader` calls filters that are threaded. 

I don't know how `c3d` is written. It does use ITK, but I don't know if it does anything special with threads.
