### ISSUE TITLE
ResampleImage

### ISSUE THREAD

**Issue by tashrifbillah** [ANTsX/ANTs#693]
1. What's the difference b/w `ResampleImage` and `ResampleImageBySpace` (except `addvox`)?

```
./ResampleImage -h
Usage: ResampleImage imageDimension inputImage outputImage MxNxO [size=1,spacing=0] [interpolate type] [pixeltype]
  Interpolation type:
    0. linear (default)
    1. nn
    2. gaussian [sigma=imageSpacing] [alpha=1.0]
    3. windowedSinc [type = 'c'osine, 'w'elch, 'b'lackman, 'l'anczos, 'h'amming]
    4. B-Spline [order=3]
 pixeltype  :  TYPE
  0  :  char
  1  :  unsigned char
  2  :  short
  3  :  unsigned short
  4  :  int
  5  :  unsigned int
  6  :  float (default)
  7  :  double
```

```
./ResampleImageBySpacing -h
Usage:
ResampleImageBySpacing  ImageDimension inputImageFile  outputImageFile outxspc outyspc {outzspacing}  {dosmooth?}  {addvox} {nn-interp?}
 addvox pads each dimension by addvox
```

Does the latter support only nearest neighbor interpolation while the former supports five methods?

2. In `ResampleImage`, what are `[size=1,spacing=0]` ?

**Comment by ntustison** [comment]
> What's the difference b/w ResampleImage and ResampleImageBySpace (except addvox)?

Just two different implementations of resampling with overlapping functionality.  Both use the same underlying ITK classes.  ``addvox``  is probably the only functionality in the former which is not in the latter.  

> Does the latter support only nearest neighbor interpolation while the former supports five methods?

The latter uses NN when that boolean is set to ``1``.  Otherwise, linear interpolation is used.

> In ResampleImage, what are [size=1,spacing=0] ?

If you want to resample the image by specifying the number of voxels in each dimension, set this command line value to ``1``.  Otherwise, if you want to resample the image by specifying the spacing in each dimension, set the value to ``0``.

**Comment by tashrifbillah** [comment]
Does the B spline support any order? I am interested in order 7.

**Comment by ntustison** [comment]
No, [only orders from 0 to 5](https://itk.org/Doxygen/html/classitk_1_1BSplineInterpolateImageFunction.html).

**Comment by tashrifbillah** [comment]
Thanks. However, what would be the command for B spline interpolation? Let's say I want to specify number of voxels.

>ResampleImage 3 input output MxNx0 [1] [B-Spline 5]

but it didn't work. So, my problem is two fold:
1. interpolation by specifying number of voxels
2. B spline interpolation specifying a particular order

Please give a complete command line.

**Comment by ntustison** [comment]
```
ResampleImage 3 ${inputImage} ${outputImage} 256x256x256 1 4 5
```

**Comment by tashrifbillah** [comment]
Hi @ntustison , if I want to do 4D resampling, does it split to 3D, resample each 3D, and merge? If it does, along which axis is the splitting done?

**Comment by ntustison** [comment]
No splitting---full 4-D resampling.

**Comment by tashrifbillah** [comment]
So do you look at a 4D window and then resample that by that?

**Comment by ntustison** [comment]
No, there's a generalization to n-D images.  If you want more details, I recommend you look at the underlying [ITK filter](https://itk.org/Doxygen/html/classitk_1_1ResampleImageFilter.html).
