### ISSUE TITLE
problem using interpolation GenericLabel[Linear] in antsApplyTransforms

### ISSUE THREAD

**Issue by SHJDwu** [ANTsX/ANTs#694]
I am trying to warp multilabeled white-matter atlas to individual space using two steps.

1. antsRegistrationSyNQuick.sh -d 3 -f FA.nii.gz -m JHU-ICBM-FA-1mm.nii -o ICBM_FA_to_FA

2. antsApplyTransforms -d 3 -i JHU-ICBM-labels-1mm.nii -o atlas_to_FA.nii -n GenericLabel[Linear] -r FA.nii.gz -t ICBM_FA_to_FA1Warp.nii.gz -t ICBM_FA_to_FA0GenericAffine.mat

An error occurred in the step 2：“Error: unrecognized interpolation option. genericlabel"
![2019-01-09_151528](https://user-images.githubusercontent.com/45736532/50882974-8affb180-1421-11e9-9de0-7edd64e33dd3.jpg)

Then, I used antsApplyTransforms directly in the terminal，” GenericLabel[Linear] “ was not found in the -n option.
![n](https://user-images.githubusercontent.com/45736532/50883389-dcf50700-1422-11e9-8422-700f0989c27f.jpg)

I don't understand why I can't use ” GenericLabel[Linear] “ option.

**Comment by gdevenyi** [comment]
The command should be "-n GenericLabel"

**Comment by cookpa** [comment]
` -n GenericLabel[Linear] ` ought to work, but it appears from your usage that you have an older version of ANTs. You need to update so the usage shows

```
-n, --interpolation Linear
                         NearestNeighbor
                         MultiLabel[<sigma=imageSpacing>,<alpha=4.0>]
                         Gaussian[<sigma=imageSpacing>,<alpha=1.0>]
                         BSpline[<order=3>]
                         CosineWindowedSinc
                         WelchWindowedSinc
                         HammingWindowedSinc
                         LanczosWindowedSinc
                         GenericLabel[<interpolator=Linear>]
```

**Comment by gdevenyi** [comment]
Ah ha, I missed that its not even in the help output. Indeed needs an update.
