### ISSUE TITLE
How to build template for incomplete data?

### ISSUE THREAD

**Issue by malywladek** [ANTsX/ANTs#695]
Hi,
I've got DTI FA maps of cat brains. The data is longitudinal and I tried building the template from 5 timepoints of each individual with mvtc2.sh. The data is acquired with full coverage in case of 3 timepoints and reduced number of slices in 2 of them (top row). I found that the images easily register too much with deformable transforms as well as affine only (bottom row). Please let me know how to deal with such images.
Exemplary template was build with `/opt/software/ants_scripts/antsMultivariateTemplateConstruction2.sh -d 3 -c 2 -i 6 -j 2 -m CC[4] -k 1 -q 100x70x30x3 -f 8x4x2x1 -s 3x2x1x0 -n 1 -r 1 -l 1 -t Affine -y 1 *_eddy_dti_FA.nii`
![github_mvtc_ra_001](https://user-images.githubusercontent.com/28865905/50892258-5af2e700-13fe-11e9-8b88-d98d318987c5.png)

**Comment by cookpa** [comment]
You might be able to improve registration with a mask:

https://github.com/ntustison/PartialSlabEpiT1ImageRegistration

As for your template, it's going to be tough to build an unbiased average with a large chunk of the brain missing for two of the time points. You might be able to build a template from the complete coverage images with the template script and then register the partials to that.

**Comment by cookpa** [comment]
Also, I don't know if you've cropped your screen shots, but if your image FOV is very close to the edge of the brain, adding empty space around the image with the `ImageMath` PadImage command may help.
