### ISSUE TITLE
Error during registration

### ISSUE THREAD

**Issue by ChanghongLi** [ANTsX/ANTs#698]
**Describe the bug**
WARNING: In /usr/include/ITK-4.10/itkTransformFactoryBase.h, line 81
TransformFactoryBase (0x555e9eb4e430): Refusing to register transform “MatrixOffsetTransformBase_double_3_3” again!
**To Reproduce**
Run the commnad: antsApplyTransforms -d 3 -i AD_subject$i.nii.gz -r mean_FA_template.nii.gz -o rAD_subject$i.nii.gz -n BSpline -t [rFA_subject$i.mat,0] -t rFA_subjectWarp$i.nii.gz

**Expected behavior**
Normalized AD image for each subject should be output...But, when I tried to merge all subjets, if failed...

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6149690/50907521-e339b200-1427-11e9-9576-4de7fe971016.png)

**Desktop (please complete the following information):**
 - OS: Linux 

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by gdevenyi** [comment]
Old ANTs version. Update and reproduce.
