### ISSUE TITLE
N4BiasFieldCorrection change the image type

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#699]
I am using N4BiasFieldCorrection. My input is 16-bit unsigned integer, but the output of n4 is 32-bit float and the image range (min, max) also changed. How could I keep the original image type and close to image range. Thanks
```
---------------Information------------
| file name: original_image.nii.gz
| PixelID:  16-bit unsigned integer
| Min range: 0.0 Max range: 336.0
 --------------------------------------
```
Step : N4 bias correction
>./N4BiasFieldCorrection -d 3 -i original_image.nii.gz -o n4_image.nii.gz -s 4

```
---------------Information------------
| file name: n4_image.nii.gz
| PixelID:  32-bit float
| Min range: 0.0 Max range: 253.0560760498047
 -------------------------------------- 
```

**Comment by gdevenyi** [comment]
Most if not all of the ANTs tools always produce a float/double output. There is no configuration to change that.

**Comment by cookpa** [comment]
You can use `ConvertImagePixelType` to change the result back to uint16.

The intensity histogram is going to change under bias correction. I'm not sure why  range of 0-336 is better than a range of 0-253, but you can multiply the image by a constant with `ImageMath` if you like.

**Comment by John1231983** [comment]
Thanks @gdevenyi and @cookpa . I think I have only that way. I have to change the range because the original intensity is too big likes 0 to 1000. If I use uint8 type, a lot of information will loss

**Comment by cookpa** [comment]
Yes I would not use uint8, but your original post says you have uint16, which has a much larger range.

**Comment by John1231983** [comment]
Thanks all, I found the issue. It due to image type. I have read the image as type of Uint 16 and feed to N4 bias correction. So, it performs bias correction not so good. I have to convert the input to float32 and feed to N4. Now, the output is good

**Comment by gdevenyi** [comment]
@John1231983 this sounds like either an ANTs or ITK bug as it should properly load different on-disk formats.

Can you provide a little more detail as to why you think its loading it wrong?

**Comment by cookpa** [comment]
I'd be very surprised if there was such a bug in the I/O. More likely that the input data was truncated or contrast squashed before input to N4. 

If there's truly a problem with input data type, I would need to see example data that could be used to reproduce and fix the problem.

**Comment by John1231983** [comment]
Sorry. It is not I/O problem. I was wrong. The step is that I feed uint16 or float32 type to N4, the output will be float32. But when I save from float32 to uint16, then some information will be lost. I have to keep original float32 type. It is just saving image problem in my code. The lost information likes
![screenshot from 2019-01-10 11-05-49](https://user-images.githubusercontent.com/24875971/50980880-b76e0900-14c7-11e9-9834-a6b9c6580285.png)

**Comment by cookpa** [comment]
Thanks for the update. I don't think `ConvertImagePixelType` will do anything fancy, you'd need to handle the contrast yourself. `ImageMath` has a `Normalize` option that might help, but if you can work with float, it might just be easier to do so.

**Comment by gdevenyi** [comment]
Ahh, that's very important to know @cookpa. I would've expected (coming from MINC-land) that the tools that convert voxel types would also properly handling rescaling and dynamic range of the values as to not have data loss.

**Comment by John1231983** [comment]
Sorry if I ask it again. I found that some image has a larger range after bias correction. I am using the command
```
./N4BiasFieldCorrection -d 3 -i input.nii.gz -o output.nii.gz -s 4 -b [200] -c [50x50x50x50,0.000001]
```
This is image information before applies N4
```
Voxel size: 0.8x0.8x0.8
PixelID: , 32-bit float
 Min range:', 0.0, 'Max range:', 199.5606231689453
```
And this is log after N4
```
Voxel size: 0.8x0.8x0.8
PixelID: , 32-bit float
Min range:', 0.0, 'Max range:', 313.4952087402344
```
It shows that max value change from 199 to 313. Is it normal? I am applying it for T2 image. For T1, the range is fine, it just change very small. Thanks

**Comment by ntustison** [comment]
There is no constraint on the intensity range (similar to the original N3 formulation).  So you’ll often get intensity drift during optimization.  We added a rescaling option (-r) to address this which you’d probably want to check out.

**Comment by John1231983** [comment]
Thanks. The last question is that how should we choose the iteration c. I saw the default is `50x50x50x50`. As your expert, Do you think the setting is fine for brain 1x1x1 mm? Thanks
>-s 4 -b [200] -c [100x100x100x100,0.000001]

**Comment by ntustison** [comment]
That's a tough question---kind of like asking how many iterations one needs to do image registration.  It really depends on the situation.  However, I can say that it really doesn't depend on voxel resolution.  Rather, it depends on the amount of inhomogeneity in your image and that is going to vary based on field strength and potentially other factors.  The default number of iterations is something that we converged to based on our experience and I would start from there but ultimately you might need to change that number based on your data.
