### ISSUE TITLE
Faster zlib ?

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTs#702]
I was reading [this post](https://www.mccauslandcenter.sc.edu/crnl/optimizing-spmfsl) (I think by Chris Rorden), which suggests that installing the [Cloudflare fork](https://github.com/cloudflare/zlib) of zlib can yield massive speed improvement when producing .nii.gz files. There is an example at the end of that page.

Has anyone tried this zlib version before? And more generally, what zlib version are you currently using? (I am at `v1.2.7` on Centos 7)

What is also confusin is that the Cloudflare fork has stopped at `v1.2.8` while the [official zlib](https://zlib.net/) is much more recent at `v1.2.11`. So it's unclear to me if the speed improvements from Cloudflare were incorporated in the official development of zlib. Does anyone know?

**Comment by gdevenyi** [comment]
This is a upstream ITK question, of which there's already some discussion:
https://github.com/InsightSoftwareConsortium/ITK/issues/348

Also, https://github.com/zlib-ng/zlib-ng is trying to drag the "official" zlib implementation forward in a non-breaking way.

**Comment by gdevenyi** [comment]
Also, technically, its not ITK upstream even, its NIFTI upstream, which also has an open issue: https://github.com/NIFTI-Imaging/nifti_clib/issues/32

**Comment by gdevenyi** [comment]
Can be closed as its an upstream ITK/NIFTIclib issue to implement.
