### ISSUE TITLE
DenoseImage progress is misleading

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#703]
DenoiseImage shows nice progress like this with --verbose
```
Running for 3-dimensional images.
*********10*********20*********30*********40*********50*********60*********70*********80*********90*********
```

However it then sits at the last "*" for a very long time.

Looking at the implementation, I'm guessing
https://github.com/ANTsX/ANTs/blob/master/Utilities/itkAdaptiveNonLocalMeansDenoisingImageFilter.hxx#L393 actually has a fair amount of work to do. Perhaps another progress reporter is needed for the other stages?

**Comment by ntustison** [comment]
Yes, two sets of coordinating progress reporters are needed.  However, I started working on it but it became more trouble than it was worth.  You're welcome to submit a pull request but I'm not going fix it and I don't think anybody else is going to prioritize a fix anytime soon.

**Comment by gdevenyi** [comment]
Reopen as wouldbenice?
