### ISSUE TITLE
How to generate template histogram from multiple images?

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#705]
I have 10 brain MR images (`1.nii`, to `10.nii`). They will be used as training data, so I must apply a preprocessing step to match the histogram of these images. Do ANTs have any option to build a template histogram from multiple images? I have check 
```
ImageMath | grep Histogram
  HistogramMatch    : 
      Usage        : HistogramMatch SourceImage ReferenceImage {NumberBins-Default=255} {NumberPoints-Default=64} {useThresholdAtMeanIntensity=false}

```

But it is only for two inputs source and reference. Thanks

**Comment by ntustison** [comment]
No, we don't have a group-wise histogram building/matching functionality in ANTs.  I don't know if this is what you want but you could build a template from your images and construct a histogram from the result.

**Comment by John1231983** [comment]
Thanks.
>you could build a template from your images and construct a histogram from the result.

Means I have to register all images together to get a template image and the histogram of all image comes from the histogram of the template image. Am I right?

**Comment by cookpa** [comment]
You could build a template (or register to an existing one), then average the resulting deformed images. That should give you an average intensity histogram, which you can use as a reference image to apply to each of the original input images.

Be careful to use the correct normalization option if you build a template. By default, each deformed image is divided by its mean before averaging. See the usage for `antsMultivatiateTemplateConstruction2.sh`.

**Comment by John1231983** [comment]
Thanks. Do we need rescale input and reference image to same range before applying histogram matching? My input range is 0 to 200, while the reference is 0 to 600. Thanks

**Comment by ntustison** [comment]
You shouldn't.  But it's easy to test.
