### ISSUE TITLE
Using masks from SPM-VBM analysis for ANTs

### ISSUE THREAD

**Issue by Nazuna23** [ANTsX/ANTs#708]
Dear community,

I performed a VBM in SPM12 and I would like to use the significant clusters of this VBM as masks in a second analysis in ANTs. 
My problem is that I do not get my SPM-masks correctly matched on the ANTs-template no matter what I do (Coregister in SPM, Export via marsbar, etc.). The mask I extracted from my SPM results is a hippocampal cluster, but on the ANTs-template it is always slightly shifted and not matched 1:1 to the same region which makes my further analyses in ANTs impossible. 

I know that there have been some threads discussing the compatibility of SPM with ANTs but maybe someone had a similar problem and could help me on this issue of matching masks of SPM on an ANTs template. 

Thank you very much in advance!

**Comment by cookpa** [comment]
If you've reviewed the prior threads you may have seen this, but just in case

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

ITK only supports a rigid transform from voxel to physical space, in other words it doesn't use the sform matrix if possible. This can lead to a disagreement with other tools.

If you can share images, I will take a look.

**Comment by Nazuna23** [comment]
Hi,

Sorry for my late answer. Thank you very much for your answer and your point on sform matrix versus qform. 

I added a picture of the mask result of the right hippocampus from my VBM analysis in SPM, overlaid on the ANTs Template on the one hand and on the single subject T1 template in SPM for comparison purposes. You can see that in the SPM template, the cluster lies in the right hippocampus and in the ANTs template, the cluster is shifted and not in the hippocampus. I would need to have the mask matched to the ANTs template so that I can continue with my ROI analyses in ANTs.

I also added the Nifti-Files of the ANTs template and the Hippocampus ROI ( right HCROI) if that helps. 

If you have any suggestions how I can use the masks from my VBM analysis in SPM on my ANTs analyses, I would be really grateful. 

<img width="527" alt="roionspmtemplate" src="https://user-images.githubusercontent.com/47224213/52537703-c0255980-2d69-11e9-85e6-899739017deb.png">
<img width="532" alt="roionantstemplate" src="https://user-images.githubusercontent.com/47224213/52537710-cf0c0c00-2d69-11e9-852c-b4c58a2beed7.png">
[Template_ANTs.nii.zip](https://github.com/ANTsX/ANTs/files/2849211/Template_ANTs.nii.zip)
[Right_HCROI.nii.zip](https://github.com/ANTsX/ANTs/files/2849215/Right_HCROI.nii.zip)

**Comment by cookpa** [comment]
I couldn't find that exact template in SPM but I used their usual T1 template "T1.nii", which looks to be aligned with your ROI. This is not co-registered to the ANTs template, so I did:

```
antsRegistrationSyNQuick.sh -f Template_ANTs.nii.gz -m T1.nii.gz -t s -o spmToANTs_
antsApplyTransforms -d 3 -i Right_HCROI.nii.gz -r Template_ANTs.nii.gz -t spmToANTs_1Warp.nii.gz -t spmToANTs_0GenericAffine.mat -n GenericLabel -o Right_HCROIANTs.nii.gz
```

And I think it works OK

<img width="793" alt="image" src="https://user-images.githubusercontent.com/611507/52582490-52297280-2dfb-11e9-9643-9e07a9a28bb7.png">

**Comment by cookpa** [comment]
Update: I found the SPM single_subject_t1.nii.gz and it works too using the same method

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/611507/52582837-265abc80-2dfc-11e9-983f-fc14b43e3498.png">

**Comment by Nazuna23** [comment]
Hi. Thank you very much for your help! It worked perfectly!
