### ISSUE TITLE
Brain extraction of contrasts other than T1W

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#711]
Dear ANTs expert,

I was trying to perform antsBrainExtraction to strip a skull in an image of a proton-density-like contrast (the second inversion image of MP2RAGE: INV2).
However, I could not find a good template for that purpose other than T1-based template for option '-a.'

Anyway, I tried brain extraction of the INV2  with the T1-based template for option '-a.' It started the process and, however, it took forever. I could not wait forever and had to interrupt the process.

I wonder if you had any suggestions for brain extraction from images other than T1W contrast.
Any advice would be appreciated.

Thank you,
SC

**Comment by ntustison** [comment]
Can you make the images available for me to test on my end?

**Comment by s-j-choi** [comment]
I cannot attach the test file here due to 10 MB of file size restriction.
If you don't mind send me an email to scipy.choi@gmail.com, then I might be able to attach a file for the test on your end.

Thank you,
SC

**Comment by ntustison** [comment]
Try using something like google drive, dropbox, or wetransfer.

**Comment by s-j-choi** [comment]
Thank you,

I transferred two files via WeTransfer.

Best,
SC

**Comment by ntustison** [comment]
I never received an email or link for the data.

**Comment by s-j-choi** [comment]
After sending the files I received this confirmation as shown below. 

![image](https://user-images.githubusercontent.com/8732330/52566861-d28aac00-2dd8-11e9-9feb-8c3c003486b2.png)

If you confirm that you did not receive this notification from WeTransfer, I will find other ways to share the files. 

Thank you.

**Comment by s-j-choi** [comment]
I hope you received this time.

**Comment by ntustison** [comment]
Okay, a couple things:

* Cropping your images makes brain extraction more difficult.  Avoid, if possible.

* You don't have to use any of our [templates](https://figshare.com/articles/ANTs_ANTsR_Brain_Templates/915436) but if you choose to use your own reference image, you also need to supply a brain mask for that reference.  Otherwise the brain extraction won't work.  

* We've developed a [deep learning module for brain extraction](https://github.com/ANTsRNet/BrainExtraction) which is part of our ANTsRNet package.  If you can get it set up, you can get results similar to the attached in 30 sec on a laptop.  The cropping and inhomogeneity probably explains the missing top portion.

<img width="1008" alt="screen shot 2019-02-11 at 8 37 39 am" src="https://user-images.githubusercontent.com/324811/52578064-4e382900-2dd8-11e9-9aff-68ffdcb9943b.png">

**Comment by s-j-choi** [comment]
Thank you very much.
I wonder if you also have developed Deer Learning Module for
antsResgiration?
Are there any restrictions to use ANTsRNet for brain extraction or other
apps or tools?

Thank you,
SC

**Comment by ntustison** [comment]
You can see all our deep learning modules ("apps") [here](https://github.com/ANTsRNet).  

> I wonder if you also have developed Deer Learning Module for antsResgiration?

While you can see that we've developed image-based transformation models, we don't have anything that replaces ``antsRegistration``.

> Are there any restrictions to use ANTsRNet for brain extraction or other apps or tools?

Not sure what you mean by "restrictions."  Can you elaborate?

**Comment by dorianps** [comment]
Pretty impressive the BrainExtraction app, and runs in a fraction of the time of `antsBrainExtraction`. 

```
dp@CFIWKLMP04Y690A:/mnt/c/Users/albne/Desktop/BrainExtraction$ Rscript Scripts/doBrainExtraction.R ../../Desktop\ 2/example_N_012814880_MR_T1W__br_raw_20180626133141468_111_D255549_I392808.nii ../../Desktop\ 2/example_N_012814880_MR_T1W__br_raw_20180626133141468_111_D255549_I392808_DEEPbrainmask.nii.gz Data/Template/S_template3_resampled.nii.gz
Loading required package: ANTsRCore

Attaching package: ‘ANTsRCore’

The following object is masked from ‘package:stats’:

    var

The following objects are masked from ‘package:base’:

    all, any, apply, max, min, prod, range, sum

Reading reorientation template Data/Template/S_template3_resampled.nii.gz  (elapsed time: 0.3833609 seconds)
Using TensorFlow backend.
Loading weights filetrying URL 'https://ndownloader.figshare.com/files/13729661'
Content type 'application/octet-stream' length 1469520 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

2019-02-11 21:09:17.856806: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
  (elapsed time: 3.223064 seconds)
Reading  ../../Desktop 2/example_N_012814880_MR_T1W__br_raw_20180626133141468_111_D255549_I392808.nii  (elapsed time: 0.2048693 seconds)
Normalizing to template  (elapsed time: 0.8934488 seconds)
Prediction and decoding
 (elapsed time: 1.182379 seconds)
Renormalize to native space  (elapsed time: 0.3074005 seconds)
Writing ../../Desktop 2/example_N_012814880_MR_T1W__br_raw_20120626133141468_111_D255549_I392808_DEEPbrainmask.nii.gz  (elapsed time: 1.504094 seconds)

Total elapsed time: 1.245356 seconds
```

I thresholded the output, which is a probability mask, at 0.5 to get the image below.

![image](https://user-images.githubusercontent.com/9083517/52607134-2500b280-2e43-11e9-9cb9-06fb3dbdf275.png)

#### Have you done any qualitative comparison with `antsBrainExtraction` ?
