### ISSUE TITLE
ANTs skull stripping includes dura mater

### ISSUE THREAD

**Issue by oliver-xie** [ANTsX/ANTs#716]
We recently encountered an issue with the T1 skull stripping using ANTs. Part of dura mater was included in the brain mask. I wonder if there is a way to fix it.
The command used is as follows
`antsBrainExtraction.sh -a /data/sub-22146/anat/sub-22146_T1w.nii.gz -m /work/fmriprep_wf/single_subject_22146_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/T_template0_BrainCerebellumProbabilityMask.nii.gz -e /niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz -d 3 -f /niworkflows_data/ants_oasis_template_ras/T_template0_BrainCerebellumRegistrationMask.nii.gz -s nii.gz -k 1 -o highres001_ -q 1 -u 1`
![image](https://user-images.githubusercontent.com/3640318/53216831-ba9dfe00-360a-11e9-91dc-afaecf5a1dcf.png)
Skull-stripped T1w image
Thanks!
Oliver

**Comment by ntustison** [comment]
You could try a different template.
