### ISSUE TITLE
How to import antsimage as a data frame for R?

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTs#718]
When an image is loaded using antsImageRead, it is very nice that I can use a few R functions immediately. 

Now, I would like to use {dplyr} and {ggplot2} for visualization. ggplot2 requires data frame input. I naively tried data.frame(image). It did not work. 

I have not been successful to find any instructions on how to import an image as a data frame for {dplyr} or {ggplot2}. I wonder any who can indicate where I can find instructions, or share your expertise on it?

Best,
SC

**Comment by cookpa** [comment]
It's not clear what you are trying to visualize. If you want to render the image itself, see `plot.antsImage` in ANTsR.

Closing this here because this is an ANTsR issue.

**Comment by dorianps** [comment]
Maybe as.array(IMG) is what you need.
