### ISSUE TITLE
antsBrainExtraction incorrectly copies QForm information

### ISSUE THREAD

**Issue by TKoscik** [ANTsX/ANTs#719]
antsBrainExtraction.sh does not always copy the correct qform values from the input image to the extracted brain mask. These values sometimes differ at the 6th decimal place. If you run antsBrainExtraction then follow this with N4 correction (more specifically i was running antsAtroposN4.sh) you get an error regarding dimension mismatch.

You can fix this issue by running CopyImageHeaderInformation, however, this seems to obliterate any sfrom that is present, which may cause other problems integrating with other tools down the road.

**Comment by ntustison** [comment]
Any IO is performed by the underlying ITK libraries.  This [discussion](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F) is probably relevant.

**Comment by cookpa** [comment]
The image is read by the NIFTI reader into an ITK image (which is format agnostic) and then written back out as whatever format is selected. There is a loss of information and precision involved in this, which we can't really prevent. 

It might be a good idea to include the CopyImageHeaderInformation step in the brain extraction script. I can make that change once I get done with the glob fixes.

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/commit/eb971ef8bc5a0b93d7d9cce71d1ce608feca706d
