### ISSUE TITLE
antsJointFusion not recognizing masks

### ISSUE THREAD

**Issue by TKoscik** [ANTsX/ANTs#720]
when running a typical antsJointFusion call using the -x flag to specify the mask, I specify the full path to a mask file that I know exists, but antsJointFusion reports that the file does not exist.

**Comment by cookpa** [comment]
You can try this example

https://github.com/ntustison/MalfLabelingExample 

You would need to edit the "malfCommand.sh" script to use the provided mask `T_template0_mask.nii.gz`.

**Comment by cookpa** [comment]
Possibly related: if you suspect a glob problem, you can try a clean directory or update your scripts to the current master

https://github.com/ANTsX/ANTs/pull/727
