### ISSUE TITLE
PreventInSourceBuilds error in ANTs installation

### ISSUE THREAD

**Issue by divinediu** [ANTsX/ANTs#724]
**Describe the bug**
I followed steps here to install  my ANTs

**To Reproduce**
cmake and ccmake version are  3.13.4

When I configure (press c) at
`ccmake ~/code/ANTs`
I get :
`Errors occurred during the last pass `
This it the stack
` CMake Error at CMake/PreventInSourceBuilds.cmake:52 (message):
   Quitting configuration
 Call Stack (most recent call first):
   CMake/PreventInSourceBuilds.cmake:56 (AssureOutOfSourceBuilds)
   Common.cmake:14 (include)
   SuperBuild.cmake:15 (include)
   CMakeLists.txt:78 (include)`

**Expected behavior**
Configuration to run successfully! 

**Screenshots**
on running `ccmake ~/code/ANTs` and pressing c,

![image](https://user-images.githubusercontent.com/4358356/53618367-0d7e4380-3c11-11e9-9d7e-43ec06b5ce9d.png)
 on pressing e
![image](https://user-images.githubusercontent.com/4358356/53618415-2edf2f80-3c11-11e9-885d-b6e44bd86d0f.png)

scrolling all the way down,
![image](https://user-images.githubusercontent.com/4358356/53618424-3bfc1e80-3c11-11e9-9d42-da0750397f6d.png)

**Desktop (please complete the following information):**
 - OS: windows 10, running this on ubuntu WSL

**Comment by gdevenyi** [comment]
The error tells you exactly what you're doing wrong. You can't build in a subdirectory of the source

**Comment by cookpa** [comment]
I updated the Wiki to note this but the error is pretty clear. Start over with a clean copy of the code, cd to a build directory that is not inside `~/code/ANTs`, and it should be good to go.

**Comment by divinediu** [comment]
Thanks, fixed this! :)

**Comment by gdevenyi** [comment]
The close button



Down here
↓↓↓↓↓↓↓↓
