### ISSUE TITLE
Windows conda not recognizing ANTs installed in WSL

### ISSUE THREAD

**Issue by divinediu** [ANTsX/ANTs#725]
I have installed ANTs on the Windows Subsystem For Linux as given in the wiki.
Installation is successful.

This is my WSL Ubuntu in my Windows 10 system, with Ants and N4BiasFieldCorrection working.
![image](https://user-images.githubusercontent.com/4358356/53677409-58fa2580-3cd5-11e9-88cb-459e9519b8e3.png)

This is my conda environment in Windows 10 unable to find the installed ANTs 
![image](https://user-images.githubusercontent.com/4358356/53677419-8050f280-3cd5-11e9-91ca-15d8c6ba653f.png)

How do I get my Windows to recognize this now? How do I export the WSL path to my Windows path variable?
 - OS: Windows10

**Comment by cookpa** [comment]
https://docs.microsoft.com/en-us/windows/wsl/interop

**Comment by divinediu** [comment]
@cookpa 

I have gone through that, could you please help me out a little more?

```
 C:\Users\MAHE>wsl N4BiasFieldCorrection -h
/bin/bash: N4BiasFieldCorrection: command not found
(base) C:\Users\MAHE>
```

This happens when I run the command in conda

How do I execute the python file that has uses ANTs deployed in my WSL?

**Comment by cookpa** [comment]
I don't use Windows but have you tried the example?

```
wsl ls -la /proc/cpuinfo
```

If that works, then you can run Linux binaries, and it's probably a matter of setting the PATH. You can try running with the full path, eg

```
wsl /home/user/bin/ants/bin/N4BiasFieldCorrection -h
```

If that works, then you likely need to set PATH (you probably also want ANTSPATH for the scripts) in the default user environment that is initialized when you invoke `wsl`.
