### ISSUE TITLE
Questions about SyN output files

### ISSUE THREAD

**Issue by wangken1994** [ANTsX/ANTs#726]
Dear experts,

I am doing SyN registration with command antsRegistration, and my codes are shown below:
`antsRegistration -d 3 -o [1totemplate,1totemplateWarp.nii.gz,1totemplateInversewarp.nii.gz] -t SyN[0.1,3,0] -m cc[template.nii.gz,1.nii.gz,1,4] -c [100x70x50,1e-6,10] -f 8x4x2 -s 3x2x1`

After conducting this command, I found there were four output files:
1. 1totemplateWarp.nii.gz
2. 1totemplateInversewarp.nii.gz
3. 1totemplate0Warp.nii.gz
3. 1totemplate0InverseWarp.nii.gz

I found the output file 1 was different from the output file 3. So what's the relationship between the two fles.

And if I use `antsApplyTransforms` to transform the 1.nii.gz to template.nii.gz, which warp file should I choose?

Thanks in advance!

**Comment by ntustison** [comment]
Please start with the basic ``antsRegistrationSyNQuick.sh`` script.  You can read the help menu by typing ``antsRegistrationSyNQuick.sh -h 1``.  Once you figure that out, your issues above should be clarified.

**Comment by wangken1994** [comment]
Thanks your reply! @ntustison 

The reason why I didn't choose `antsRegistrationSyNQuick.sh` was that I found for SyN registration in `antsRegistrationSyNQuick.sh`, it consisted of three registrations:
-t s: rigid+affine+deformable syn

But I only need to do SyN. So could you kindly give me more tips?

**Comment by ntustison** [comment]
Please see

```
$ antsRegistrationSyNQuick.sh ... -t so ...
```

**Comment by wangken1994** [comment]
I got the solution from [https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians](url)
