### ISSUE TITLE
Suggestion for Resampling image

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#728]
I am working on different image resolutions. My trained model is for resolution of 1x1x1 mm, while the testing image is 0.9x0.9x0.9 mm. To segment the test images, I have to

1. Down-sampling from 0.9 to 1 mm
```
./ResampleImage 3 test1.nii test1_out.nii 1x1x1
```
2. Feed the resampled image to the network to obtain the results: label, probability results. Up-sampling the result to original resolution 0.9x0.9x0.9
```
./ResampleImage 3 prob_1.nii prob_1_out.nii 0.9x0.9x0.9
```
I found that up-sampling of probability map is more accurate than using label. However, the accurate still low. Do you have any suggestion for the re-sampling process?

In additions, before sample to 1x1x1, my image size is 256x256x256. After resample to 1x1x1 and resample back to 0.9x0.9x0.9 then my image size is not 256x256x256. How to solve it? Thanks all

As my understand, it due to 256*0.9=230.4, so it will be 230x230x230 in resolution of 1x1x1. After that, we resample back then 230/0.9=255 # 256

**Comment by ntustison** [comment]
You might want to try using ``antsApplyTransforms`` where you have additional interpolators to try.

**Comment by John1231983** [comment]
@ntustion: can antApplyTransform use for resampling image i.e from 0.9 to 1mm?

**Comment by ntustison** [comment]
Yes, just resample the original image to the new resolution and then apply ``antsApplyTransforms`` using an identity transform to the space of the new resolution image, i.e. ``antsApplyTransforms ... -i $originalImage -r $resampledImage ... -t identity ...``.

**Comment by tashrifbillah** [comment]
Hi @ntustison , can output datatype be set to INT16 this way? I see the default is FLOAT64 with an option to cast as FLOAT32 only.

**Comment by tashrifbillah** [comment]
Found the new feature https://github.com/ANTsX/ANTs/pull/926
