### ISSUE TITLE
FEATURE IDEA: template construction gradient step size list

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#729]
From the help of antsMultivariateTemplateConstruction2.sh
```
     -g:  Gradient step size (default 0.25): smaller in magnitude results in more
          cautious steps.  Use smaller steps to refine template details.
          0.25 is an upper (aggressive) limit for this parameter.
```

Currently, the gradient step size is a fixed parameter for any given run of the template builder. While this is the case, the help gives a hint that smaller values improve refinement of the template [citation needed]. Currently the way to take advantage of this is either to do many iterations with a small step size, or perhaps two runs, once with a large size, and another with a smaller size.

I'd like to propose an enhancement, allow a list of gradient step sizes, which must be equal to the number of iterations, so that the template builder can start off with big steps, and then move to smaller steps with later iterations.

**Comment by gdevenyi** [comment]
Following up here, does this concept make sense as I have described it? If not, I'd like to know so I don't waste time here...

**Comment by ntustison** [comment]
This description

```
-g:     Gradient step size (default 0.25): smaller in magnitude results in more
          cautious steps.  Use smaller steps to refine template details.
          0.25 is an upper (aggressive) limit for this parameter.
```

is probably more applicable to the gradient parameter associated with pairwise registration than it is in the context for which it is used in the template building script.  I don't know that this gradient parameter has ever been studied in a rigorous way but I'm skeptical that your proposed changes would make much difference in the end result.  I personally wouldn't spend time trying to add this feature.
