### ISSUE TITLE
GCC8 Compile Error in Atropos

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#732]
GCC8 has tightened up warnings vs errors and throws this error on build:
```
  47724 In file included from /home/nistmni/src/minc-toolkit-v2/ANTs/Examples/Atropos.cxx:16:
  47725 /home/nistmni/src/minc-toolkit-v2/ANTs/ImageSegmentation/antsAtroposSegmentationImageFilter.h: In member function 'void itk::ants::AtroposSegmentationImageFilter<TInputImage, TMaskImage, TClassifiedImage>::GetPriorLabelParameterMap()':
  47726 /home/nistmni/src/minc-toolkit-v2/ANTs/ImageSegmentation/antsAtroposSegmentationImageFilter.h:523:18: error: return-statement with a value, in function returning 'void' [-fpermissive]
  47727      return this->m_PriorLabelParameterMap;
  47728                   ^~~~~~~~~~~~~~~~~~~~~~~~
  47729 make[5]: *** [Examples/CMakeFiles/l_Atropos.dir/build.make:63: Examples/CMakeFiles/l_Atropos.dir/Atropos.cxx.o] Error 1
```

https://github.com/ANTsX/ANTs/blob/master/ImageSegmentation/antsAtroposSegmentationImageFilter.h#L523

**Comment by ntustison** [comment]
Thanks but this isn't our issue.  Compare our current [repo](https://github.com/ANTsX/ANTs/blob/master/ImageSegmentation/antsAtroposSegmentationImageFilter.h#L521-L524) with what you're compiling [above](https://github.com/vfonov/ANTs/blob/5decc62c18694fe9fcb46c88b03346c0d5f28177/ImageSegmentation/antsAtroposSegmentationImageFilter.h#L521-L524).

**Comment by gdevenyi** [comment]
very odd.. I looked back in time in the repo here and didn't see any changes on that line.

I'll have to figure out where that code changed.

thanks
