### ISSUE TITLE
antsRegistration CBF image to FA image

### ISSUE THREAD

**Issue by SHJDwu** [ANTsX/ANTs#735]
Hello everyone!
I'm trying to make a registration from CBF map to individual FA space. Here, the CBF map of 3D pCASL was post processed using Function Tool (AW 4.5 Workstation, GE Healthcare).The command I used is as follows:

antsRegistrationSyNQuick.sh -d 3 -f FA.nii -m CBF.nii -o CBF_to_FA

Then, the image was  deformed and match badly with FA map. Please, see attachments. I uploaded the CBF and FA map of a subject in the attachments. How can I register CBF map to individual FA space?
Thanks in advance for any help!
![2019-03-13_223723](https://user-images.githubusercontent.com/45736532/54287762-463ef500-45e1-11e9-895e-3aeeada0d756.png)
[CBF.zip](https://github.com/ANTsX/ANTs/files/2961974/CBF.zip)
[FA.zip](https://github.com/ANTsX/ANTs/files/2961975/FA.zip)
[T1.zip](https://github.com/ANTsX/ANTs/files/2961976/T1.zip)

**Comment by caugolm** [comment]
I think antsIntermodalityIntrasubject.sh generally works well for this, but it assumes you're trying to register a CBF map (for example) to a T1. That said, if you want to look at correspondence between FA and CBF then I think you want to get both the CBF and FA images into the T1-space anyway, as you have that nice T1 image.
