### ISSUE TITLE
Calculate MI, CC and MSQ 

### ISSUE THREAD

**Issue by Yangguoyuan** [ANTsX/ANTs#736]
Dear ANTs experts:
      I'm sorry to bother you. I have constructed two population-specific brain templates. Now I want to compare the difference between those two brain templates. So I decide to calculate the MI, CC, MSQ index between this two templates to represent the difference. Which code can solve this problem?

Sincerely
Guoyuan

**Comment by ntustison** [comment]
``MeasureImageSimilarity``
