### ISSUE TITLE
antsApplyTransforms accidentally writes input image for time series (type 4) under certain circumstances

### ISSUE THREAD

**Issue by nweisenfeld** [ANTsX/ANTs#737]
**Describe the bug**
This amounts to a typo in the code and is clearly not what is intended.

The line of code [here](https://github.com/ANTsX/ANTs/blob/ab0087a2473af8c14b391da40779a94ce9ec6bbe/Examples/antsApplyTransforms.cxx#L714) accidentally writes the input `timeSeriesImage` instead of the just-created `outputTimeSeriesImage`.  So the output is created, but never used.

**To Reproduce**
Resample a color JPEG, for instance, as "type 4", e.g.:

$ants/antsApplyTransforms -v -d 2 -e 4 -i $moving -r $fixed -o test.nii.gz -t "[testC10GenericAffine.mat,0]"

and you'll notice that the output has the shape of the original moving image, rather than the fixed image. 

Either way, it's clear from the code.

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/commit/680942c1628c8ed142c6b25a4c8b9e47aadf3e01

Thanks
