### ISSUE TITLE
problems compiling cmake

### ISSUE THREAD

**Issue by andygreg** [ANTsX/ANTs#739]
When compiling cmake for Mac I run into the following issue 

After entering the code

`ccmake ~/code/ANTs`

I get the following error

`CMake Error at`
`/usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CMakeTestCCompiler.cmake:52`
`(message):`
` The C compiler`

` "/anaconda3/bin/x86_64-apple-darwin13.4.0-clang"`

` is not able to compile a simple test program.`

How can I fix this?

**Comment by gdevenyi** [comment]
This isn't a question about ANTs. As per the error, your build system is broken or incomplete.

**Comment by cookpa** [comment]
You need a working C and C++ compiler, for example through the XCode developer tools.

You might already have this, but it's possible that your environment is pointing CMake to the wrong place. You can set the C and C++ compiler before running CMake (in a clean install directory).

```
export CC=/usr/bin/cc
export CXX=/usr/bin/c++
ccmake ~/code/ANTs
```
