### ISSUE TITLE
Update field smoothing in SyN

### ISSUE THREAD

**Issue by m-albert** [ANTsX/ANTs#740]
Hi,

generally SyN is working great for me. I have a quick question related to its fine tuning:

How is the update field convolution kernel size determined? Should (and can) I optimise it depending on my desired regularisation behavior?

Thanks a lot in advance!
Cheers,
Marvin

**Comment by ntustison** [comment]
> How is the update field convolution kernel size determined?

The options for SyN are
```
SyN[gradientStep,<updateFieldVarianceInVoxelSpace=3>,<totalFieldVarianceInVoxelSpace=0>]
```
The convolution kernel for both the update and total field variance are specified in terms of the radius in voxel space.

> Should (and can) I optimise it depending on my desired regularisation behavior?

Yes.

**Comment by quakberto** [comment]
Thanks for the quick answer @ntustison !

Sorry, I knew about this setting and should have been more precise in my question. Here's the longer version: I'm wondering whether it makes sense to customise how the update field varies depending on the resolution level.

Namely, using a python implementation of SyN (nipy.org/dipy) I found that I get better results for low target variances when starting out with higher variances (higher than the scaling coming from units given in voxels). So far so good. However, in some cases I get seemingly inconsistent behaviour when changing the variance within the same registration call (the metric can increase its value dramatically).

Therefore I was wondering whether anything in the SyN formulation would disallow me to freely play with the update field variance?

Thanks a lot again!

**Comment by ntustison** [comment]
> I'm wondering whether it makes sense to customise how the update field varies depending on the resolution level.  Therefore I was wondering whether anything in the SyN formulation would disallow me to freely play with the update field variance?

Sure, you can do that.  

> Namely, using a python implementation of SyN (nipy.org/dipy)...

Just one word of caution---implementing SyN is not straightforward so I wouldn't necessarily attribute differences in performance strictly to visible parameter choices.  In fact, I would get guidance on usage directly from the authors of that implementation.

**Comment by stnava** [comment]
yea and you can also use:
https://github.com/ANTsX/ANTsPy

brian

**Comment by quakberto** [comment]
> Just one word of caution...
You're right, thanks! 

> yea and you can also use:
> https://github.com/ANTsX/ANTsPy
Wow, will check it out. Thanks!

**Comment by gdevenyi** [comment]
A followup regarding this discussion:

Does updateFieldVarianceInVoxelSpace and totalFieldVarianceInVoxelSpace refer to the voxels of the currently subsampled space? i.e. If I am at shrink 8, is that 3*8 voxels of the original resolution?

**Comment by ntustison** [comment]
> If I am at shrink 8, and updateFieldVarianceInVoxelSpace=3 is that 3*8 voxels of the original resolution?

No, that value maintains for every resolution level.

**Comment by gdevenyi** [comment]
Okay to be really super clear :)

If I have a 1mm iso fixed-space, and I set updateFieldVarianceInVoxelSpace=3 what is the updateFieldVarianceInVoxelSpace in mm if my shrink factor is 8?

**Comment by ntustison** [comment]
3.
