### ISSUE TITLE
antsLongitudinalJointLabelFusion for two time points

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#742]
Dear experts,

I have a brain MRI of a subject with two time points: 24 years old (without label) and 36 years old with the label. I want to use the 36 years old time point to generate the label for 24 years old. I can do it in a simple way. First, I register the 36 years old brain to 24 years old. After that, I apply the transformation to the label of 36 years old, results in 24 years old label. This is my script

```
antsRegistrationSyN.py -d 3 \
  -f ${fixedImage} \
  -m ${movingImage} \
  -o ${outputDirectory}/ants
  
antsApplyTransforms -d 3 -i ${movingLabel} \
                    -r ${fixedImage} -o ${outputDirectory}/antsWarpedLabel.nii.gz \
                    -n GenericLabel[Linear] \
                    -t ${outputDirectory}/ants1Warp.nii.gz \
                    -t ${outputDirectory}/ants0GenericAffine.mat
```
The result looks reasonable. However, I found the script `antsLongitudinalJointLabelFusion`. I used it and it gave worst performance than my above script, **So, Is it better to use above script with two time points?** I am using below script for antsLongitudinalJointLabelFusion

```
antsLongitudinalJointLabelFusion.sh -d 3 \
-t ${fixedImage} \
-o ${outputDirectory}/ants \
-g ${movingImage} \
-l ${movingLabel} \
-g ${movingImage} \
-l ${movingLabel}
```
The log is
```
--------------------------------------------------------------------------------------
 Dimensionality:           3
 Output prefix:            ants
 Posteriors format:        
 Target image:             brain_MRI_24.nii.gz
 Atlas images:             brain_MRI_36.nii.gz,  brain_MRI_36.nii.gz
 Atlas labels:              label_MRI_36.nii.gz, label_MRI_36.nii.gz
 Transformation:           s

 Keep all images:          0
 Processing type:          0
 Number of cpu cores:      1
--------------------------------------------------------------------------------------
```

**Comment by stnava** [comment]
there will be fairly small advantage in this case, though it may reduce
bias which can be very important depending on your application.


brian
