### ISSUE TITLE
How to register two image using tissue probability map?

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#743]
Dear experts,
I want to register T1 image of moving image to T1 image of a fixed image. Due to changing
contrast and structures of two images, the direct register may be difficult. So, I found one solution is that register the tissue probability maps of two image together as below figure

![Capture](https://user-images.githubusercontent.com/24875971/54946878-6fc81c80-4f0f-11e9-9579-effc3f4c64e2.JPG)

However, the problem is that each tissue probability (i.e WM) provides an affine transformation matrix, So, If I have three classes then I have three affine transformations in total. How can I use them to transform the raw image T1 of moving to fixed image such as the script
```
antsApplyTransforms -d 3 -i ${movingLabel} \
                    -r ${fixedImage} -o ${outputDirectory}/antsWarpedLabel.nii.gz \
                    -n GenericLabel[Linear] \
                    -t ${outputDirectory}/ants1Warp.nii.gz \
                    -t ${outputDirectory}/ants0GenericAffine.mat
```
Thanks in advance!

**Comment by cookpa** [comment]
You can call `antsRegistration` with a metric for each tissue class. The metric weighting option allows you to control the relative importance of each. This will run a single registration and produce a single output transformation.

**Comment by John1231983** [comment]
Thanks cookpa for your answer. However, it is not so clear for me. Let takes one example. Assume I have the dataset as follows

```
fixed_T1
|-T1.nii.gz
|-prob_WM.nii.gz
|-prob_GM.nii.gz
|-prob_CSF.nii.gz
```````
moving_T1
|-T1.nii.gz
|-prob_WM.nii.gz
|-prob_GM.nii.gz
|-prob_CSF.nii.gz
```

So, first I used the script

```
fixedImage=/fixed_T1/prob_WM.nii.gz
movingImage=/moving_T1/prob_WM.nii.gz
antsRegistrationSyN.py -d 3 \
  -f ${fixedImage} \
  -m ${movingImage} \
  -o ${outputDirectory}/ants

```
So, what is the option to use a metric to weight them?

**Comment by cookpa** [comment]
I don't know if the scripts or the Python function will allow multiple metrics. But you can add multiple metrics with `antsRegistration`, for example

```
-t Affine[0.1] -m MI[ fixedCSF.nii.gz, movingCSF.nii.gz, 0.5, 32, Regular, 0.2] -m MI[ fixedGM.nii.gz, movingGM.nii.gz, 1, 32, Regular, 0.2] -m MI[ fixedWM.nii.gz, movingWM.nii.gz, 1, 32, Regular, 0.2]
```

Here I've set the CSF term to half the weight of GM and WM. The weights are internally normalized to 1, so these are relative weightings.

**Comment by John1231983** [comment]
@cookpa  this is my script. it can produce the single affine matrix but whrn I apply the transformation. the result is not affine. could you look at my script and let me know if any wrong?
```antsRegistration --d 3 \
-t Affine[0.1] \
-m MI[fixed_prob_1.nii.gz, moving_prob_1.nii.gz, 0.5, 32, Regular, 0.2] \
-m MI[fixed_prob_2.nii.gz, moving_prob_2.nii.gz, 1, 32, Regular, 0.2] \
-m MI[fixed_prob_3.nii.gz, moving_prob_3.nii.gz, 1, 32, Regular, 0.2] \
--convergence [1000x500x250x100,1e-6,10] \
--shrink-factors 12x8x4x2 \
--smoothing-sigmas 4x3x2x1vox \
--interpolation Linear \
--use-histogram-matching 0 \
--winsorize-image-intensities [0.005,0.995] \
-o out \
-v 1
```
```

antsApplyTransforms -d 3 \
-i moving_T1.nii.gz \
-r fixed_T1.nii.gz \
-o affine.nii.gz \
-n Linear \
-t out0GenericAffine.mat \
-v 1
```
And what is reference image should I use in antsapplytransform because we used three reference prob images in the step antsregistration

**Comment by ntustison** [comment]
>  it can produce the single affine matrix but whrn I apply the transformation. the result is not affine

The command calls looks correct.  How are you verifying that the transformed output image is not affine?

>  And what is reference image should I use in antsapplytransform because we used three reference prob images in the step antsregistration

The reference image simply supplies to image geometric information in the header so, assuming that all your fixed images define a single space (same for your moving images), it doesn't matter which image of the three you use.

**Comment by John1231983** [comment]
@ntustison great. I just visualize it with itksnap and the warped image (affine image) and the moving image are still same. Anything wrong? 

(2) i see. So they are same physical coordinate. So I can use any image as reference one.

**Comment by cookpa** [comment]
You can use `antsTransformInfo` to see what the transform matrix looks like.

**Comment by John1231983** [comment]
@cookpa : Here is output of the transformation matrix
```
Transform file: out0GenericAffine.mat
AffineTransform (0xfc5710)
  RTTI typeinfo:   itk::AffineTransform<double, 3u>
  Reference Count: 3
  Modified Time: 500
  Debug: Off
  Object Name: 
  Observers: 
    none
  Matrix: 
    1.14172 0.0603969 -0.0107968 
    -0.0133735 1.03887 0.0221548 
    -0.0630119 0.106267 0.975687 
  Offset: [15.2216, -40.2208, 17.0845]
  Center: [0, 0, 0]
  Translation: [15.2216, -40.2208, 17.0845]
  Inverse: 
    0.87586 -0.0520323 0.0108736 
    0.0100922 0.964226 -0.0217829 
    0.0554657 -0.10838 1.02799 
  Singular: 0
```

**Comment by cookpa** [comment]
If the output from antsApplyTransforms is not what you expect, it's likely that there a problem with the definition of physical space somewhere in the pipeline.  

https://github.com/ANTsX/ANTs/wiki/Output-images-have-incorrect-headers-or-otherwise-do-not-match-the-applied-transform

I'll take a closer look if you would like to share a complete runnable example with code and data.

**Comment by John1231983** [comment]
@cookpa @ntustison : This is the data and script. Feel free to check it
https://drive.google.com/drive/folders/1OycYDxTebHfWcurfTgMAJz-SB3bKp9vg?usp=sharing

**Comment by cookpa** [comment]
Thanks - but this folder doesn't include the T1 images that you are having problems with.

**Comment by cookpa** [comment]
Never mind, I see you also get an unexpected result warping the prob_3 image. I think I know the issue.

**Comment by John1231983** [comment]
Perfect!. Hope it is not from ANts. :)

**Comment by cookpa** [comment]
I think it's because the physical spaces of the moving and fixed image are very oblique to each other, resulting in a poor initialization for the registration.

One way to compensate for this is to use `antsAI` to search for a better initialization:

```
ResampleImageBySpacing 3 moving_prob_3.nii.gz moving_prob_3_downsample.nii.gz 4 4 4 1
ResampleImageBySpacing 3 fixed_prob_3.nii.gz fixed_prob_3_downsample.nii.gz 4 4 4 1
antsAI \
  -d 3 \
  -m Mattes[ fixed_prob_3_downsample.nii.gz, moving_prob_3_downsample.nii.gz, 32, Regular, 0.25 ] \
  -t Affine[0.1] \
  -s [ 30, 0.5 ] \
  -c 5 \
  -o initTransform0GenericAffine.mat \
  -v 1
```

And then add to the `antsRegistration` call: `-r [ initTransform0GenericAffine.mat ]`.

**Comment by John1231983** [comment]
Great. You are using downsampled image to find an init transformation. Will it reduce the accuracy comparison with using the original image (not downsampled)?

Seconds, the moving images include three prob, but the initTransform0GenericAffine resulted from only single prob `prob_3`. Does it affect the performance?
