### ISSUE TITLE
Optimising image registration quality

### ISSUE THREAD

**Issue by jimmy-jammy** [ANTsX/ANTs#744]
Hi,
I'm using SyN from ANTs and I get decent results (judged by eye).

While finding the optimal settings I ran into this: After the registration finished (because it reached convergence), restarting a new registration process (for example with just one level) with the original fixed and a transformed moving image significantly increases registration quality.

I do not entirely understand why this happens, my guess would be that performing registration close to the fixed image space rather than at t=0.5 between the two images adds additional information. Of course, the symmetry of the final output is lost, but for my application and probably many others this is not a problem.

My question would be: Is there any guideline or documentation to when it makes sense to run an additional registration?

Thanks a lot!
Jim

**Comment by stnava** [comment]
by eye, you may be detecting over fitting .... more parameters = more
overfitting.  running registration twice doubles the parameters.  here is
an extreme example of overfitting and its dangers:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3274625/

brian

**Comment by ntustison** [comment]
You're also interpolating the moving image twice.  The resulting smoothing effect might, by coincidence, give you better results but is not a good idea, in general.

**Comment by jimmy-jammy** [comment]
@stnava Thanks for pointing out the paper which is nice to cite! Interestingly, I also get important improvements when simply rerunning the last level (so not really increasing the number of parameters).

@ntustison Interesting, I was thinking about the effect of interpolation. I also found that using many different (non integer) resolution levels improves registration quality, which I would attribute to the availability of more different samplings of the image space (in addition to the smoother pyramid progression).

Do you think interpolation can only help because of its smoothing effect or could combining registrations on different distances to the two input images (t=0.1, t=0.9 etc.) also improve registration quality?

Thanks!

**Comment by ntustison** [comment]
> Do you think interpolation in this case only helps because of its smoothing effect or could combining registrations on different distances to the two input images (t=0.1, t=0.9 etc.) also improve registration quality?

You're not actually performing different registrations at different distances by re-running the registration a second time.  In other words, running the registration for a few more iterations in your original scenario vs., instead, running the registration on the warped moving image with the same parameters as the final stage for those additional number of iterations doesn't change the image distances involved between the two situations.  The interpolation is the major difference and probably the only difference of consequence in the scenario you've set up above.

**Comment by jimmy-jammy** [comment]
Hmm I was assuming that transforming the moving image for the second registration is a bit like continuing the registration at t=0 (with respect to the first registration). If not I'm probably confusing things and have to read up on SyN again. Thanks so much for the detailed answer! I'll continue playing around a bit with the iterations to understand the increase in quality

**Comment by stnava** [comment]
1.  you should not rely on similarity to assess registration accuracy ( see the paper )
2. composing two transforms increases the degrees of freedom and therefore allows more overfitting to occur ie   numberOfParameters( Transform_1 ) <  numberOfParameters( Transform_1  composed with Transform_2 )

**Comment by jimmy-jammy** [comment]
You're right that there's no way around a proper validation of the registration results. I should complement similarity with measuring the distances between landmarks, as suggested in the paper.
