### ISSUE TITLE
Image too blur after rigid align

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#745]
Dear experts,

I am using the script antsRegistrationSyN to rigid align two T1 images. However, the output is too blur in comparsion with the original fixed image. Do we have any option to make the output less blur? 

```
antsRegistrationSyN.sh  -d 3 \
  -f ${fixedImage} \
  -m ${movingImage} \
  -o ${outputDirectory}/ants \
  -n 16 \
  -t a
```

`antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [ants.nii.gz] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [0.005,0.995] --initial-moving-transform [fixed.nii,moving.nii,1] --transform Rigid[0.1] --metric MI[fixed.nii,moving.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox --transform Affine[0.1] --metric MI[fixed.nii,moving.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 12x8x4x2 --smoothing-sigmas 4x3x2x1vox`

I guess it due to `--smoothing-sigmas 4x3x2x1vox`. But I do not how to reduce it.

**Comment by ntustison** [comment]
> I guess it due to --smoothing-sigmas 4x3x2x1vox. But I do not how to reduce it.

No, the smoothing of the warped image is due to interpolation.  You can try different interpolators but it's something you can't get around.

**Comment by John1231983** [comment]
Also I cannot apply affine transform when using rigid align. If I used Syn, it is fine likes 

```
antsRegistrationSyN.py -d 3 \
  -f ${fixedImage} \
  -m ${movingImage} \
  -o ${outputDirectory}/ants
  
antsApplyTransforms -d 3 -i ${movingLabel} \
                    -r ${fixedImage} -o ${outputDirectory}/antsWarpedLabel.nii.gz \
                    -n GenericLabel[Linear] \
                    -t ${outputDirectory}/ants1Warp.nii.gz \
                    -t ${outputDirectory}/ants0GenericAffine.mat
```
But if I used
```
antsRegistrationSyN.sh  -d 3 \
  ...
  -t a
```
Then I cannot find the `ants1Warp.nii.gz` file.

**Comment by cookpa** [comment]
If the registration transform is only affine, or a subset of affine (rigid or translation), you won't get a warp field. 

To reduce blurring, try the BSpline interpolation.

**Comment by John1231983** [comment]
@cookpa : Thanks. So if I have a paired T1, T2 in fixed images and T1,T2 for moving images. I need to call two times `antsRegistrationSyN` for T1 (moving)-->T1(fixed) and T2 (moving) -->T2 (fixed) although the T1 and T2 in fixed images are well aligned before. Am I right

```
antsRegistrationSyN.sh  -d 3 \
  -f ${fixedT1Image} \
  -m ${movingT1Image} \
  -o ${outputDirectory}/ants \
  -n 16 \
  -t a

antsRegistrationSyN.sh  -d 3 \
  -f ${fixedT1Image} \
  -m ${movingT2Image} \
  -o ${outputDirectory}/ants \
  -n 16 \
  -t a
```

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians#warping-multiple-modalities-to-a-common-template

To get rid of unwanted interpolation artifacts in the background, you can use a mask. If you warp your moving image with linear interpolation and then threshold at zero, it will give you a background mask.

**Comment by John1231983** [comment]
@cookpa : Thanks. It worked. But the results of BSpline have negative values in the boundary. Is it normal? Can I use the threshold on the BSpline's result to generate mask instead of your way? Thanks

**Comment by cookpa** [comment]
You can either mask them out or replace them somehow (eg with the results from linear interpolation)
