### ISSUE TITLE
Contrast adjustment for all atlas images?

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#749]
Dear Ants Experts,

I have two atlas images from the same ages but different scanners result in different contrast. Could you suggest any method (available in Ants) to adjust these images the same contrast? I tried histogram matching but they lost a lot of information

![Screenshot from 2019-04-05 18-49-53](https://user-images.githubusercontent.com/24875971/55660323-bbae7780-57d3-11e9-81e2-11ffd6068aeb.png)

**Comment by gdevenyi** [comment]
HistogramMatching in ImageMath

**Comment by John1231983** [comment]
@gdevenyi : Thanks but as I mentioned that the image lost a lot of information when I use histogram matching 

This is my command

```
ImageMath 3 output.nii.gz HistogramMatch input.nii.gz ref.nii.gz 1024 7 1
```

I am wondering that should I use mean option (1) or turn off mean option (0) in the above command
