### ISSUE TITLE
Unintended consequence of ThresholdImage

### ISSUE THREAD

**Issue by jeffduda** [ANTsX/ANTs#750]
Having some issue resulting from line 904 in ANTs/Scripts/antsLongitudinalCorticalThickness.sh

logCmd ${ANTSPATH}/ThresholdImage ${DIMENSION} ${SINGLE_SUBJECT_TEMPLATE_PRIORS[$j]} ${TMP_CSF_POSTERIOR} 0 1 1 0

This occurs after subtracting out the CSF prior from every other prior in the cooking process. The issue is that the upper bound of 1 can cause problems. In some cases (i.e. deep white matter) the value in the posterior is image is slightly above 1.0. In that case the above line sets those values to zero, so the voxels with the highest confidence of being white matter are then set to zero confidence. One option is to change the line to
 
logCmd ${ANTSPATH}/ThresholdImage ${DIMENSION} ${SINGLE_SUBJECT_TEMPLATE_PRIORS[$j]} ${TMP_CSF_POSTERIOR} 0 inf 1 0

in which case all positive values are retained, the other option is to set all values greater than one equal to one before this step. Not sure which is preferred but either are preferable to the current situation.

**Comment by cookpa** [comment]
If this fails then either the WM probability is greater than one or the CSF probability is negative. I would suspect the former, and it may be related to the change in implementation from a discrete to recursive Gaussian filter some time ago.

I think it would be a good idea to restrict all the priors to the range 0-1 before doing that CSF subtraction step.

**Comment by ntustison** [comment]
Sounds good to me.

**Comment by cookpa** [comment]
@jtduda do you have a fix? If not, I can add one

**Comment by jeffduda** [comment]
Can submit a fix next week, but if you have one ready to go that works too.

**Comment by cookpa** [comment]
@jeffduda I think this should fix it, can you please confirm?

https://github.com/ANTsX/ANTs/tree/cookPriorsThresh

**Comment by cookpa** [comment]
@jeffduda FYI that branch won't compile, I have to roll back more changes to make it compile with older ITK. But you can take the script from there to test.

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/commit/efaf05375756dae34651bb771c1a851f03fdd5bf
