### ISSUE TITLE
ANTs brain extraction output problem

### ISSUE THREAD

**Issue by lmortel** [ANTsX/ANTs#755]
Hi all,

I've tried using AntsBrainExtraction (version 2.1.0) on my dataset with T1-weighted anatomical scans, testing both the OASIS (OASIS30Ants obtained from fmriprep/Templateflow) and NKI templates, and the extraction produces output that is extremely distorted. I've attached a screenshot of the output I see in mricron.

![bugscreenshot](https://user-images.githubusercontent.com/49486012/55887894-aa3be580-5bae-11e9-8f97-4f3fc45e302c.png)

My command looks like this:
antsBrainExtraction.sh -d 3 -a $path/to/T1_scan -e $path/to/tpl-OASIS30ANTs_res-01_T1w.nii -m $path/to/tpl-OASIS30ANTs_res-01_label-brain_probseg.nii -f $path/to/tpl-OASIS30ANTs_res-01_desc-BrainCerebellumExtraction_mask.nii -o $output_folder -k 1

This is the information of the T1-weighted scan from the .rec file:

 Patient name                       :   *
.    Examination name                   :   *
.    Protocol name                      :   cor T1w_1mm_4m40_S1 SENSE
.    Examination date/time              :   *
.    Series Type                        :   Image   MRSERIES
.    Acquisition nr                     :   2
.    Reconstruction nr                  :   2
.    Scan Duration [sec]                :   282
.    Max. number of cardiac phases      :   1
.    Max. number of echoes              :   1
.    Max. number of slices/locations    :   120
.    Max. number of dynamics            :   1
.    Max. number of mixes               :   1
.    Patient position                   :   Head First Supine
.    Preparation direction              :   Right-Left
.    Technique                          :   T1TFE
.    Scan resolution  (x, y)            :   240  240
.    Scan mode                          :   3D
.    Repetition time [ms]               :   8.136  
.    FOV (ap,fh,rl) [mm]                :   240.000  240.000  240.000
.    Water Fat shift [pixels]           :   2.268
.    Angulation midslice(ap,fh,rl)[degr]:   1.680  -2.349  -0.090
.    Off Centre midslice(ap,fh,rl) [mm] :   -10.869  0.062  1.845
.    Flow compensation <0=no 1=yes> ?   :   0
.    Presaturation     <0=no 1=yes> ?   :   0
.    Phase encoding velocity [cm/sec]   :   0.000000  0.000000  0.000000
.    MTC               <0=no 1=yes> ?   :   0
.    SPIR              <0=no 1=yes> ?   :   0
.    EPI factor        <0,1=no EPI>     :   1
.    Dynamic scan      <0=no 1=yes> ?   :   0
.    Diffusion         <0=no 1=yes> ?   :   0
.    Diffusion echo time [ms]           :   0.0000
.    Max. number of diffusion values    :   1
.    Max. number of gradient orients    :   1
.    Number of label types   <0=no ASL> :   0

Weirdly enough, the exact same command gives normal output from AntsBrainExtraction when I use a different T1-weighted dataset from my colleague.

Desktop (please complete the following information):**
 - OS: Linux 6.10

Any idea how to fix this problem?

Kind regards,

Laurens

**Comment by ntustison** [comment]
Yeah, I'm guessing the orientation header for this problematic image is incorrect.  You might want to look at it in ITK-SNAP.

**Comment by cookpa** [comment]
If the images look correct, you might try updating. Newer versions of the script try more starting points for the registration, which can compensate somewhat for the images not being well aligned.

**Comment by lmortel** [comment]
Hi all,

Thank you for your replies! Turns out my PAR/REC to Nifti converter (r2n) made some errors in creating the orientation header for my Nifti file. Using a different converter fixed the problem.

**Comment by dorianps** [comment]
If you don't mind my asking, what converter did you use before and which
one fixed the problem?
