### ISSUE TITLE
Basic Brain Mapping github example failure

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTs#756]
**Describe the bug**

The basic brain mapping example [here](https://github.com/stnava/BasicBrainMapping) fails on OSX with "latest ANTs" according to the user.

**To Reproduce**

Compile the "latest ANTs" and then run the BBM example according to the README.   The failure will look like:

```
M = [ ...
            -inf                0 
             nan  0.0300710175315  ]
/My_Folder_Mac_Work/NIH/ANTS/antsbin/ITKv5/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_svd.hxx: suspicious return value (2) from SVDC
/My_Folder_Mac_Work/NIH/ANTS/antsbin/ITKv5/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_svd.hxx: M is 2x2
M = [ ...
            -inf                0 
             nan  0.0300710175315  ]
Exception caught: 
itk::ExceptionObject (0x7ff3bc1e53a0)
Location: "unknown" 
File: /My_Folder_Mac_Work/NIH/ANTS/antsbin/ITKv5-install/include/ITK-5.0/itkMattesMutualInformationImageToImageMetricv4.hxx
Line: 195
Description: itk::ERROR: MattesMutualInformationImageToImageMetricv4(0x7ff3bc08b7b0): Joint PDF summed to zero
```

**Expected behavior**

the example should finish without error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  OSX

**Smartphone (please complete the following information):**

**Additional context**

This issue is opened on behalf of a user.

**Comment by ntustison** [comment]
Yeah, this happened very recently because I just updated ANTs from not too long ago and that example doesn't work now.  I'm guessing it's this [change](https://github.com/ANTsX/ANTs/commit/c56a0d8ccf683731d0b93f7a9358d03939d1238b).  Do you see anything that stands out?

**Comment by cookpa** [comment]
Working for me on 

```
ANTs Version: 3.0.0.0.dev34-gab008
Compiled: Mar 18 2019 15:27:03
```

**Comment by cookpa** [comment]
The registration works without a mask.

I was confused for a bit because the lesion mask is in the fixed space, but it is multiplied with the moving image to make the lesioned T1. I guess `MultiplyImages` works on the voxel data, and since the images are of the same voxel dimensions, it's OK.

It definitely does not like a mask though. I can't even register the template to itself with a mask.

**Comment by stnava** [comment]
yes - i found the same as @cookpa ie old commit works, new recent commit fails.  as such, i think we might ask for some insight from @hjmjohnson

**Comment by cookpa** [comment]
I think this is the underlying issue

https://github.com/InsightSoftwareConsortium/ITK/issues/694

I've tried a variety of images with identity and non-identity transforms. All fail with a mask but work fine without.

**Comment by ntustison** [comment]
Thanks for the information @cookpa .

**Comment by cookpa** [comment]
Not sure if this is a good solution but an explicit Update() on the mask object seems to work.

https://github.com/ANTsX/ANTs/tree/maskRegError

**Comment by cookpa** [comment]
Update: ITK closed their issue, it was just a boundary problem. Stephen Aylward explained that the spatial objects have a concept of voxel space, and object physical space, and a world space. The registration methods and metrics look up points in world space, so we have to ensure that this is set correctly, and remains correct through the stages of registration.

I don't have much time to look at this right now, we might need to roll back the ITK version for a while.

**Comment by ntustison** [comment]
Perhaps just [updating the ITK version fixes it](https://github.com/ANTsX/ANTs/commit/223b1d3b854bd080464e158e6ce3335fdcd83e14).

**Comment by ntustison** [comment]
Hey @cookpa , just wanted to make sure you saw this.  One of the four travis builds fails but I believe it's unrelated.  Just when you get a chance, let me know if this resolves the issue (as it seems to do for me).  Thanks.

**Comment by cookpa** [comment]
Yes it looks like that works. I built off master so it looks like the Update() call is superfluous now

**Comment by ntustison** [comment]
Great.  Thanks.
