### ISSUE TITLE
N4BiasFieldCorrection from nipype

### ISSUE THREAD

**Issue by wangken1994** [ANTsX/ANTs#757]
Dear Experts:

I use the `nipype` to do `N4BiasFieldCorrection`, my codes are:

`from nipype.interfaces.ants import N4BiasFieldCorrection`
`n4 = N4BiasFieldCorrection()` 
`n4.inputs.dimension = 3`
`n4.inputs.bspline_fitting_distance = 300`
`n4.inputs.shrink_factor = 3`
`n4.inputs.n_iterations = [50, 50, 30, 20]`
`n4.inputs.input_image = '.../T1w.mha'`
`n4.inputs.output_image = '.../T1w_n4.mha'`
`res = n4.run()`

However, when I run these codes, the error occurs:

> IOError: No command "N4BiasFieldCorrection" found on host computer. Please check that the corresponding package is installed.

But if I use `N4BiasFieldCorrection.help()`, it works. So I think the installation of `nipype` is no porblem. 

Another example works:
`from nipype.interfaces.fsl import BET`
`skullstrip = BET()`
`skullstrip.inputs.in_file = ".../T1w.nii.gz"`
`skullstrip.inputs.out_file = ".../T1w_bet.nii.gz"`
`res = skullstrip.run()`

So can anyone give me some tips?

**Comment by gdevenyi** [comment]
You don't have ants installed?

**Comment by wangken1994** [comment]
I think ANTs is included in `nipype` , so I don't install ANTs.

**Comment by gdevenyi** [comment]
Ants is not in nipype.

Nipype provides wrappers for a number of compiled neuroimaging tools.

**Comment by wangken1994** [comment]
Thank you so much for your answer! I will try to install ANTs.
