### ISSUE TITLE
Can't add "antsRegistrationSyNQuick.sh" to system path variables

### ISSUE THREAD

**Issue by wangken1994** [ANTsX/ANTs#762]
Dear Experts,

I have added the `ANTs.2.1.0.Debian-Ubuntu_X64` path to system path variables in my Linux system. 
The codes are shown below:
```python
sudo gedit ~/.bashrc
export PATH=/home/.../ANTs.2.1.0.Debian-Ubuntu_X64:$PATH
source ~/.bashrc
```
When I input the command `ANTS` in the terminal window, it works.
`call ANTS -h or ANTS --help`

However, if I input the command `antsRegistrationSyNQuick.sh` in the terminal, it shows 
```python
--------------------------------------------------------------------------------------
Error locating ANTS
--------------------------------------------------------------------------------------
It seems that the ANTSPATH environment variable is not set. Please add the ANTSPATH
variable. This can be achieved by editing the .bash_profile in the home directory.
Add:
ANTSPATH=/home/yourname/bin/ants/
Or the correct location of the ANTS binaries.
Alternatively, edit this script ( antsRegistrationSyNQuick.sh ) to set up this parameter correctly.
```` 
I think this error is related to the file prefix of `.sh`. 
So can anyone give me some tips? Thanks in advance!

**Comment by gdevenyi** [comment]
The error is very clear. The ANTs scripts rely on the ANTSPATH variable to find the binaries.

Add an ANTSPATH export to your bashrc

**Comment by wangken1994** [comment]
I solved this problem by:
```python
sudo gedit /etc/profile
export ANTSPATH=/home/.../ANTs.2.1.0.Debian-Ubuntu_X64
export PATH=${PATH}:${ANTSPATH}
source /etc/profile
reboot
```
Thank you so much for your help! @gdevenyi
