### ISSUE TITLE
differences of  several calculation results with the same fixed image and moving image

### ISSUE THREAD

**Issue by zzstefan** [ANTsX/ANTs#763]
Hi, I may encounter a problem here. I have some subjects may have been scanned times, like AP and PA or some other conditions. For example, one subject has been scanned 4 times. I want to do parallel processing of all this data on the server. So I  performed antsRegistrationSyNQuick.sh on all of the four data simultaneously. And my question is if I want to use the prefix_Ant1Warp.nii.gz files from the four results to do postprocessing, are there any influences on the final results?  I may have other two options. First, just performing  antsRegistrationSyNQuick.sh on the first scan and use the result for the following three scans. Second, average the results from the four scans and use the averaged result to do postprocessing. So what's your suggestion? Thank you.

**Comment by ntustison** [comment]
It depends on what post-processing you want to do.  Either of those two options is reasonable.

**Comment by zzstefan** [comment]
Mainly I have two post-processing steps, the first is using the prefix_Ant1InverseWarp.nii.gz file to register  an existing template to the preprocessed image file and use the registered template to extract time courses. The second is to register the melodic results to the MNI space using prefix_Ant1Warp.nii.gz file. Which strategy do you think I should use? Thank you.
