### ISSUE TITLE
How to remove a small blur region region in template?

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#766]
I am using the below scrip to build a brain template of 100 subjects
inputPath=${PWD}/
outputPath=${PWD}/TemplateMultivariateBSplineSyN/

```
${ANTSPATH}/antsMultivariateTemplateConstruction2.sh \
  -d 3 \
  -o ${outputPath}T_ \
  -i 20 \
  -g 0.2 \
  -j 2 \
  -c 0 \
  -k 2 \
  -w 1x1 \
  -f 8x4x2x1 \
  -s 3x2x1x0 \
  -q 100x70x50x10 \
  -n 0 \
  -r 1 \
  -l 1 \
  -m CC[2] \
  -t BSplineSyN[0.1,26,0] \
  ${inputPath}/*.img

```
It worked but the template has some blur region (indicates by red region) with intensity in the range of 0.1 to 2 (maybe bigger than 2). 

![ddddd](https://user-images.githubusercontent.com/24875971/57663013-55134980-761c-11e9-9808-3cab09295ec8.JPG)

Do you think it is normal in the template image? Do I need to use some post-processing to remove the region (like threshold...)?

**Comment by ntustison** [comment]
It's probably an issue with one or more of the template images.  You should review all your images normalized to the template.

**Comment by John1231983** [comment]
@ntustison : I checked all the input images. They are normalized to [0,5000]. The output template range in [0, 30]. What is issue that you mentioned?

**Comment by ntustison** [comment]
_Spatially_ normalized.  Take  a look at each image registered to the template to make sure they're all aligned as expected.

**Comment by John1231983** [comment]
@ntustison : So we check it at every iteration. Am I right? For example, I used 14 iters so for each iter., we have a template and aligned images. We check the aligned image to confirm that they well aligned with the current template?
