### ISSUE TITLE
Atlas of the ANTS output, how to get its corresponding segmentation map.

### ISSUE THREAD

**Issue by taipingqu** [ANTsX/ANTs#770]
Dear ANTS expert, I have created a few brain atlas, I have tried the following command: "antsMultivariateTemplateConstruction2.sh -d 3 -i 2 -k 1 -f 6x4x2x1 -s 3x2x1x0 -q 100x100x70x20 -t SyN -m CC -c 0 -o 27_ ./*.nii", after outputting the template, but there is no segmentation data for the atlas. If I would like to get the segmentation data of the atlas, what command could I execute?

**Comment by ntustison** [comment]
Segmentation is performed using the ``Atropos`` tool.  Here's a 2-D (example)[https://github.com/ntustison/antsAtroposN4Example] of how it's used in conjunction with bias correction.  For your 3-D data, you'll have to download one of the templates we've made available [here](https://figshare.com/articles/ANTs_ANTsR_Brain_Templates/915436) or [here](https://figshare.com/articles/ANTs_files_for_mni_icbm152_nlin_sym_09a/8061914).
