### ISSUE TITLE
antsBrainExtraction.sh issue

### ISSUE THREAD

**Issue by ptsii** [ANTsX/ANTs#771]
I've been trying to use the antsBrainExtraction.sh script. Here is my call:

antsBrainExtraction.sh -d 3 -a Subj002_anatomical.nii.gz -e ~/Documents/Research/atlases/OASIS-30_Atropos_template/T_template0.nii.gz -m ~/Documents/Research/atlases/OASIS-30_Atropos_template/T_template0_BrainCerebellumProbabilityMask.nii.gz -f ~/Documents/Research/atlases/OASIS-30_Atropos_template/T_template0_BrainCerebellumRegistrationMask.nii.gz -s nii.gz -o Subj002_anatomical_

However, this produces a pretty bad result:
![Subj002_antsbrain_test](https://user-images.githubusercontent.com/5157597/58658331-4c926280-82ee-11e9-9ca1-b46bd55d8486.png)

I've seen other suggestions along the lines of "try a different atlas", but I'm just wondering if I'm doing something obviously wrong here before I go looking for a different atlas to use.

Speaking of which... any suggestions of other atlases and probability maps that might be available for this?

Thanks for any suggestions

**Comment by hjmjohnson** [comment]
My guess is that your data is not conformant to the dicom standards with respect to direction cosine.

**Comment by ptsii** [comment]
Hmmm... The data are from a Siemens 3 Tesla Prisma MRI scanner, and the dicoms were combined into a nifti file using dcm2niix.  Is there any way you know of to determine whether the files are not conformant with respect to direction cosine? I'm not quite sure how to approach this

**Comment by ntustison** [comment]
Can you post the data for us to inspect?

**Comment by ptsii** [comment]
The anatomical .nii.gz is 27 MB.  Is that too big to post here?

**Comment by ptsii** [comment]
Its rejecting files over 10 MB

**Comment by ptsii** [comment]
see if this works:
https://iu.box.com/s/hwrvjyss6hx31bo1mu7h0klavhylgx87

**Comment by ptsii** [comment]
Hold on... have to upload the file

**Comment by ptsii** [comment]
its up there now.  Subj002_anatomical.nii.gz

**Comment by cookpa** [comment]
Your image is 4D with two components, this will cause a lot of problems for the ANTs scripts. Extract the first component or average them and it should work more normally.

**Comment by ptsii** [comment]
Ah!  Thank you.  I believe the image is two echos from the same anatomical sequence.  Is there a way to average them into one (instead of making them a 4D image)?  I think I know how to get dcm2niix to spit out the two separately...

**Comment by cookpa** [comment]
`TimeSeriesDisassemble` in `ImageMath` should do it.

**Comment by ptsii** [comment]
AverageImages 3 averaged_image.nii.gz 0 anatomical_1st_echo.nii.gz anatomical_2nd_echo.nii.gz

**Comment by stnava** [comment]
try retransfer

brian

**Comment by stnava** [comment]
sorry wetransfer

brian
