### ISSUE TITLE
issue with antsApplyTransforms

### ISSUE THREAD

**Issue by carolin31** [ANTsX/ANTs#772]
Hi, 
I am confused about the order of the 0GenericAffine.mat and 1Warp.nii.gz because I am getting different results depending on whether I use a label file or a brain image that I want to transform.
When I list first the 1InverseWarp.nii.gz file, antsApplyTransforms seems to apply first the 0GenericAffine.mat (see screenshot)

<img width="1875" alt="Screen Shot 2019-05-30 at 2 24 20 PM" src="https://user-images.githubusercontent.com/41706947/58666171-7431fc80-82e7-11e9-87f0-ce3062e9c739.png">

Now, this order seems to work well when it is a Labelfile that I want to transform, but when it is a brainImage, this order seems to be not right. Because the transformed image is not identical with the image min_outlier_ANTS_alig_InverseWarped.nii.gz. When I flip the order and I list the 0GenericAffine first, ants applies first the 1inverseWarp.nii.gz, but the transformed  brain image seems to be right because the image is identical to min_outlier_ANTS_alig_InverseWarped.nii.gz.

However, when I want to transform a label file, the last order where I list 0GenericAffine.mat first does not give a good result.  Ants applies the 1Warp.nii.gz file first and then the 0Generic Affine.mat and as a result the labels are not well transformed (see screenshot). But when I flip the order, they are.
<img width="1880" alt="Screen Shot 2019-05-29 at 6 01 28 PM" src="https://user-images.githubusercontent.com/41706947/58666704-ee16b580-82e8-11e9-8bbb-310cdb3f63f0.png">

<img width="629" alt="Screen Shot 2019-05-30 at 2 43 57 PM" src="https://user-images.githubusercontent.com/41706947/58666881-63828600-82e9-11e9-8dba-e0fe039b030c.png">

Do I need to switch the order depending on whether I transform a label file or a brain image? Or depending on whet I use the inverse?

Thank you very much in advance
Carolin

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

The ordering doesn't depend on label vs brain, but it does depend on whether the input image is the fixed or the moving image in the call to `antsRegistration`. 

For warping labels vs warping a brain, you would want to change the interpolation. Something like `-n NearestNeighbor` or `-n GenericLabel` for label images is needed. The default is `-n Linear`, which works for warping brains but not labels.

**Comment by carolin31** [comment]
Thanks a lot for the quick reply! Now I am less confused ;-)

I do include -n Multilabel when I transform a label file. So your recommendation is to change it to GenericLabel or NearestNeighbor? Why is this better?

Could you explain what the differences are? I can not find any information on this on GitHub or the ants handout.

Thanks a lot in advance!
Carolin

**Comment by ntustison** [comment]
You can read it about the different label interpolators [here](https://www.insight-journal.org/browse/publication/950).  ``MultiLabel`` has been subsumed by ``GenericLabel.``
