### ISSUE TITLE
Clarification regarding antsMultivariateTemplateConstruction2 and the article cited in the code

### ISSUE THREAD

**Issue by d-vogel** [ANTsX/ANTs#773]
Dear ANTs team,
I've been using the methodology that you implement in the `antsMultivariateTemplateConstruction2` script, which seem to be your preferred method of creating anatomical templates. Based on the script, I do pairwise (affine+SyN) registration of each patient's image to a reference, then refresh the reference by doing voxel-wise averaging (euclidean).

After digging a bit deeper in your publications ([1]), is seems to me that this methodology does not match the method that you call "SyGN" and presented in [2]:
- the Frechet mean is presented to give better results than the Euclidean mean for updating the template, however I did not find any implementation of this method within the ANTs toolkit.
- The optimization of the template appearance (section 2.2.1) is apparently done after the pairwise registrations (if i understand correctly). This is what distinguishes your "SyGN" and "OA" method.

To what extend are [2] and [1] valid in the case of the `antsMultivariateTemplateConstruction2` script ?

Cheers,

[1] A Reproducible Evaluation of ANTs Similarity Metric Performance in Brain Image Registration, Avants et al. 2010

[2] The Optimal Template Effect in Hippocampus Studies of Diseased Populations, Avants et al. 2010

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L386

**Comment by cookpa** [comment]
> You omitted the [shape update step](https://github.com/ANTsX/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L386).

Also the sharpening filter.

https://github.com/ANTsX/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L275

**Comment by d-vogel** [comment]
Sorry for the late answer.
Thanks to the shape update step, the results are much better.

Thank you for the clarification.
