### ISSUE TITLE
How to bring one label file into another labelfile's Dimension,voxelspacing and origin?

### ISSUE THREAD

**Issue by carolin31** [ANTsX/ANTs#774]
Hi,

I need to merge two label files together, which are both in the same physical space, but have different Dimensions, Voxel spacing and Origin etc. 

So I am basically looking for an Ants function, which does, what the -r option in antsApplytransforms does.

What is the right function to do that?
Thank you very much in advance
Carolin

**Comment by cookpa** [comment]
You can use antsApplyTransforms with the reference image and no warps (no -t).

On Jun 10, 2019, at 5:05 PM, carolin31 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I need to merge two label files together, which are both in the same physical space, but have different Dimensions, Voxel spacing and Origin etc.

So I am basically looking for an Ants function, which does, what the -r option in antsApplytransforms does.

What is the right function to do that?
Thank you very much in advance
Carolin

**Comment by carolin31** [comment]
Thanks! That was quick! And it worked!
