### ISSUE TITLE
Reproduce template using --random-seed

### ISSUE THREAD

**Issue by tashrifbillah** [ANTsX/ANTs#775]
In [v2.3.0](https://github.com/ANTsX/ANTs/releases), reproducibility of `antsRegistration` is made possible by introduction of `--random-seed` flag. I was wondering what parameters should I modify to reproduce a template using [`antsMultivariateTemplateConstruction2.sh`](https://github.com/ANTsX/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh). I have included `--random-seed` in lines [1008](https://github.com/ANTsX/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L1008) and [1279](https://github.com/ANTsX/ANTs/blob/master/Scripts/antsMultivariateTemplateConstruction2.sh#L1279), still the created templates don't match. However, I am using `-c 2` and `-j 2`.

Please advise ...

**Comment by ntustison** [comment]
Have you tried running it in serial (``-c 0``)?  Also, with ``export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1``?

**Comment by tashrifbillah** [comment]
You are so right. Now I have been able to reproduce the template with a trade off for increased duration.

Anyways, do you think omitting `c 0` and keeping only `export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1` should suffice?

**Comment by ntustison** [comment]
You should try it.

**Comment by tashrifbillah** [comment]
My hunch worked. The only thing necessary to set was the variable `export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1`.  Now, I have been able to reproduce the template as fast as before. Thanks for helping out.

P.S. Closing this issue now but I may reach out again if I have to correct myself in future.
