### ISSUE TITLE
How to use scipy map_coordinates and generated warp deformation field to get the transformed image?

### ISSUE THREAD

**Issue by wentaozhu** [ANTsX/ANTs#777]
**Is your feature request related to a problem? Please describe.**
Yes. When I am using map_coordinates and generated warp deformation field to get the transformed image, I find the tranformed image and that by ANTs are different.

**Describe the solution you'd like**
Could you please provide the implementation and the main framework of antsApplyTransforms? Could you please provide an example using map_coordinates to warp the image?

**Describe alternatives you've considered**
I have converted the deformation field to displacement field. But still fail to convert the same transformed image.

**Additional context**
Thank you!

**Comment by ntustison** [comment]
We don't support portability with scipy so you're going to have to do some digging on your own to figure out the differences in the representation of displacement fields between to the two toolkits.  Ours is based on the [ITK displacement field transform](https://itk.org/Doxygen/html/classitk_1_1DisplacementFieldTransform.html).

**Comment by wentaozhu** [comment]
Thank you for your instructions. I think I can make it.
