### ISSUE TITLE
Ask the source codes of Rigid, Affine & SyN registration in ANTs

### ISSUE THREAD

**Issue by wangken1994** [ANTsX/ANTs#780]
Hi, everyone,

I want to know the exact procedures of rigid, affine and SyN in the source codes of ANTs.

I read the script of `antsRegistrationSyN.sh`, and I found it call the `antsRegistration`. However, I didn't find the procedures such as the rotation or shear in the source code of `antsRegistration` nor the header files included in `antsRegistration`. So can you tell me which file includes the registration procedure such as the rotation or shear in the source codes of ANTs.

Best,
Ken

**Comment by gdevenyi** [comment]
https://github.com/InsightSoftwareConsortium/ITK

**Comment by wangken1994** [comment]
Thank you! @gdevenyi
