### ISSUE TITLE
Keep one slice in a 3D image

### ISSUE THREAD

**Issue by aghayoor** [ANTsX/ANTs#781]
Dear ANTs developers,

Is the any ANTs tool for keeping only one 2D slice in a 3D image space?

I have used "ExtractSliceFromImage" before to extract 2D slice from a 3D image, but now I want to keep only one slice in a 3D image space.

Thanks,
Ali

**Comment by ntustison** [comment]
How is ``ExtractSliceFromImage`` not giving what you want?  Is the header information incorrect?

**Comment by aghayoor** [comment]
@ntustison : Nick, the `ExtractSliceFromImage ` gives a 2D image as the output. However, I want a 3D image at the output consisting of only the selected slice.

To give more context about my problem, I am trying to run an MR to Histology registration, so I want to have one histology slice placed in the original 3D lattice space, so I can run the registration to find the corresponding slice in the MR atlas.

**Comment by ntustison** [comment]
We don't have that functionality in ANTs.  It's an option, though, that we should work to put in ``ExtractSliceFromImage``.

**Comment by ntustison** [comment]
Except you might want to see if ``ExtractRegionFromImage`` can give you what you want.  I don't have time to check right now.

**Comment by aghayoor** [comment]
@ntustison :
Hi Nick,

I could not find the requested functionality in `ExtractRegionFromImage`.
However, I added this option to the `ExtractSliceFromImage` by adding an optional argument to the command line.

Please review this [pull request](https://github.com/ANTsX/ANTs/pull/784).

Thank you,
Ali

**Comment by dorianps** [comment]
I think there is a way to do this in ANTSR but don't remember the exact
command off the top of my head. Maybe @stnava can help.

**Comment by jeffduda** [comment]
In ANTsR, this can be done with cropIndices()

**Comment by aghayoor** [comment]
Thank you for all responses.
