### ISSUE TITLE
N4BiasCorrection produces near imperceptible changes in presence of Bias

### ISSUE THREAD

**Issue by nimzodisaster** [ANTsX/ANTs#788]
N4BiasCorrection produces near imperceptible changes, despite clear bias. N**3**BiasCorrection does make visible corrections.

I've tried a lot of parameters. Nothing appears to change the result.
e.g., changing -s 4 or 2; changing -b [150] or [100] or [50] or default; Increasing iterations..

Observing the convergence e.g., below, it doesn't appear to move towards the threshold. I never gets below x.xe-7

``` Iteration 55 (of 1000).   Current convergence value = 3.5567e-07 (threshold = 1e-11)
  Iteration 56 (of 1000).   Current convergence value = 2.40951e-07 (threshold = 1e-11)
  Iteration 57 (of 1000).   Current convergence value = 7.6745e-07 (threshold = 1e-11)
  Iteration 58 (of 1000).   Current convergence value = 9.01844e-07 (threshold = 1e-11)
  Iteration 59 (of 1000).   Current convergence value = 3.13761e-07 (threshold = 1e-11)
  Iteration 60 (of 1000).   Current convergence value = 4.91637e-07 (threshold = 1e-11)
  Iteration 61 (of 1000).   Current convergence value = 3.64762e-07 (threshold = 1e-11)
  Iteration 62 (of 1000).   Current convergence value = 3.58591e-07 (threshold = 1e-11)
  Iteration 63 (of 1000).   Current convergence value = 2.41756e-07 (threshold = 1e-11)
  Iteration 64 (of 1000).   Current convergence value = 7.2214e-07 (threshold = 1e-11)
  Iteration 65 (of 1000).   Current convergence value = 8.48349e-07 (threshold = 1e-11)
  Iteration 66 (of 1000).   Current convergence value = 3.15249e-07 (threshold = 1e-11)
  Iteration 67 (of 1000).   Current convergence value = 4.91305e-07 (threshold = 1e-11)
  Iteration 68 (of 1000).   Current convergence value = 3.68147e-07 (threshold = 1e-11)
  Iteration 69 (of 1000).   Current convergence value = 3.56678e-07 (threshold = 1e-11)
  Iteration 70 (of 1000).   Current convergence value = 2.46124e-07 (threshold = 1e-11)
  Iteration 71 (of 1000).   Current convergence value = 7.2288e-07 (threshold = 1e-11)
```

![image](https://user-images.githubusercontent.com/19696085/60147550-bafa0180-9782-11e9-8123-ad480eba89a1.png)

Left bias field by N4, Middle original image, right bias corrected image

![image](https://user-images.githubusercontent.com/19696085/60147638-162bf400-9783-11e9-90f4-e52101405b81.png)

This last image was N3 correction, with clear improvements.

Build: ANTs was built from source today, on 6-25-19, but same issue in older build
OS: Ubuntu 16.04 - 
Here is my example mprage image
[example.nii.gz](https://github.com/ANTsX/ANTs/files/3328033/example.nii.gz)

**Comment by ntustison** [comment]
Your input image has negative values.  Try rescaling to strictly nonnegative values and try again.

**Comment by nimzodisaster** [comment]
Brilliant. Fixed! 
...might consider adding an option to N4 code to threshold image at zero.
![image](https://user-images.githubusercontent.com/19696085/60148759-35c51b80-9787-11e9-80bd-c0d66b9a7def.png)

**Comment by gdevenyi** [comment]
There's a lot of places where ANTs tools produce negative values (BSpline interpolation and SmoothImage come to mind), where thresholding would home in handy.
