### ISSUE TITLE
Add Motion artifact in the image

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#793]
Dear Experts,

I found that we have motion correction in the Ants. Assume that I have an image with no motion artifact. I want to create an image with the mortion artifact in my image then apply your motion correction. For that, I can see the effect of your function. Do we have any function to add a motion artifact in the MRI image?

Thanks

**Comment by ntustison** [comment]
There is not a specific function for generating motion artifacts in ANTs.
