### ISSUE TITLE
antsBrainExtraction.sh provides wrong options to antsAI

### ISSUE THREAD

**Issue by nimzodisaster** [ANTsX/ANTs#794]
**Describe the bug**
/data/bin/ANTs/antsbin/bin/antsAI -d 3 -v 1 -m Mattes[ /data/proj/app/pipeline/eacsf/Outputs/Step1_bigbatch//tmp8465//tmpBrainExtractionInitialAffineFixed.nii.gz,/data/proj/app/pipeline/eacsf/Outputs/Step1_bigbatch//tmp8465//tmpBrainExtractionInitialAffineMoving.nii.gz,32,Regular,0.2 ] -t Affine[ 0.1 ] -s [ 20,0.12 ] -g [ 40,0x40x40 ] -p 0 -c 10 -o /data/proj/app/pipeline/eacsf/Outputs/Step1_bigbatch//tmp8465//tmpBrainExtractionInitialAffine.mat
ERROR:  Invalid flag provided g
ERROR:  Invalid command line flags found! Aborting execution.

I'm going to venture a guess that this is an option that was in the older antsAffineInitializer, which was commented out in favor of antsAI

**Comment by ntustison** [comment]
``antsAI`` has been used in ``antsBrainExtraction.sh`` for awhile so I doubt that's the issue.  Also, ``antsAI`` does have a ``-g`` flag.  You might want to try updating your repo and see if the error persists.

```
antsAI --help

COMMAND: 
     antsAI
          Program to calculate the optimallinear transform parameters for aligning two 
          images. 

OPTIONS: 

...

     -g, --translation-search-grid [stepSize=25, AxBxC=0x0x0]
          Translation search grid in mm, which will translate the moving image in each 
          dimension in increments of the step size. 

...
```

**Comment by gdevenyi** [comment]
Looks like you're trying to use a "new"  antsBrainExtraction.sh with an older release of ANTs

**Comment by nimzodisaster** [comment]
strange. I just built Ants...maybe there is another Ants install active.
Thanks.

**Comment by cookpa** [comment]
I think this is a result of version mixing, so closing for now
