### ISSUE TITLE
79 Illegal Instruction (core dumped) $COMMAND

### ISSUE THREAD

**Issue by ronangarrison** [ANTsX/ANTs#797]
When running the following code in WSL (Ubuntu 18.04), I get an error:

`antsRegistrationSyN.sh -d 2 -f temp1.nii -m temp2.nii -o output`

The command calls ants Registration and then in the antsRegistrationSyN.sh script on line 606 there is the illegal instruction and core dumping error. I checked memory and it doesn't appear to be a faulty memory issue. I also don't think it is an overheating issue.

Any suggestions would be greatly appreciated.
![ants_issue](https://user-images.githubusercontent.com/52576726/60732833-195c7800-9f19-11e9-8bdb-1316bcbc7526.png)

**Comment by cookpa** [comment]
Related? Different system I know.

https://github.com/ANTsX/ANTs/issues/764

**Comment by gdevenyi** [comment]
To be clear, the devs believe the issue is that your CPU is older than corei7, which is what our default "arch" setting is:
/CMake/ITKSetStandardCompilerFlags.cmake@master#L245 

You can adjust this by adding "-march=native" to your compile options.

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#compilation-fails-or-run-time-errors-occur-with-illegal-instruction-errors
