### ISSUE TITLE
What does "..0GenericAffine.mat" mean?

### ISSUE THREAD

**Issue by wangken1994** [ANTsX/ANTs#800]
Hi, 
I got the `mat` file after the affine transformation with `antsRegistrationSyNQuick.sh`. And I found there were two parts included in this single `mat` file:

![image](https://user-images.githubusercontent.com/34388336/60872243-ec84c980-a266-11e9-8e2a-0a792c07581d.png)

where the `AffineTransform_double_3_3` was a 12x1 array, the `fixed` was a 3x1 array.
So what do these two parts mean?

**Comment by wangken1994** [comment]
Another problem:
I want to average several images whose formats are `nii.gz`. My procedure is shown below:
![AVG](https://user-images.githubusercontent.com/34388336/60874905-65862000-a26b-11e9-8651-ca8db5fb5ba5.jpg)

where the reference image is `A`, `B_A` represents registering `B` to `A`, `C_A` represents registering `C` to `A`, `Tba` is transformation of registering `B` to `A`, and I use `Tba times B` to acqure `B_A`.

So, is the final expression in line 3 correct? How to fulfill it with ANTs scripts?

Thanks in advance!

**Comment by gdevenyi** [comment]
Hi,

You should take a look at general details of transformations,
This describes the MINC XFM format, but its contents are identical to the ITK mat files.
https://en.wikibooks.org/wiki/MINC/Tools/mni_autoreg#What_is_registration

**Comment by ntustison** [comment]
In addition, [here](https://itk.org/Doxygen/html/classitk_1_1MatrixOffsetTransformBase.html) is a description of the ITK parameters and [here](https://github.com/ANTsX/ANTs/blob/master/Examples/AverageAffineTransform.cxx) and [here](https://github.com/ANTsX/ANTs/blob/master/Examples/AverageAffineTransformNoRigid.cxx) are the programs to do the affine averaging.

**Comment by wangken1994** [comment]
Thank you so much! @gdevenyi @ntustison
