### ISSUE TITLE
CreateJacobianDeterminantImage output not expected?

### ISSUE THREAD

**Issue by ashwinkumargb** [ANTsX/ANTs#801]
Hi,

I'm trying to calculate the Jacobian Determinant from the deformation field for a volume. Upon calculation using either the CreateJacobianDeterminantImage or ANTSJacobian, the determinant output differs from the original deformation field in that it's a discontinuous calculation. The deformation field (input parameter) is continuous. I've attached the determinant, deformation field, and target image to this [link](https://drive.google.com/drive/folders/13tBinSyhtXVz4DYoHEOtGGUDLvXHDNjr?usp=sharing). If possible, I would also appreciate a link to code where the determinant calculation occurs. Please let me know what you find and possibilities for fixing this?

Regards,
Ashwin

**Comment by ntustison** [comment]
Take a careful look at your input.  I'm seeing unexpectedly large numbers for your warp field (see below) so it's not surprising you're getting those numbers for your determinant (i.e., garbage in garbage out).  Code starts [here](https://github.com/ANTsX/ANTs/blob/master/Examples/CreateJacobianDeterminantImage.cxx).

```
> t <- antsImageRead( "~/Desktop/Deformation/determinant.nii.gz" )
> tc <- splitChannels( t )
> min( tc[[1]] )
[1] -100002.9
> max( tc[[1]] )
[1] 3.402823e+38
> min( tc[[2]] )
[1] -100003
> max( tc[[2]] )
[1] 3.402823e+38
> min( tc[[3]] )
[1] -100000
> max( tc[[3]] )
[1] 3.402823e+38
```

**Comment by ashwinkumargb** [comment]
The deformation field does not represent a one-to-one transform from source to target, but instead only a portion of the target image. The really large or really small values are where the deformation field doesn't overlay with the target image. Does this impact the Jacobian determinant calculation? Also, the code appears to return the values from the methods in other classes that are conducting the determinant calculation. Could you provide the code where the numerical calculations are happening?

**Comment by ntustison** [comment]
How was the displacement field computed?

I provided the front-end program as it contains the header files whic

**Comment by ashwinkumargb** [comment]
The field was calculated using spinal cord toolbox, which uses ANTs (for the most part) to compute the registration.

**Comment by ntustison** [comment]
That's interesting.  The toolbox must be doing something to change those masked values to large or small numbers.  Can you prevent that from happening and retry calculating the Jacobian?

**Comment by ashwinkumargb** [comment]
Hi,

Following up on this issue again. I made the file such that the extremely large values that were outside the specified image were not used in the Jacobian calculation. However, the calculated Jacobian files still have several planar, light striations. The respective deformation field does not possess such characteristics. I have attached a sample of the Jacobian determination, deformation field, and target file [here](https://drive.google.com/drive/folders/1XdaOMnWPe990--M4LWWk_zfPouQ_CVgP?usp=sharing). Any help for why this is happening is appreciated.

Regards,
Ashwin

**Comment by ntustison** [comment]
You should post this question with the spinal cord toolbox developers.  There are some application-specific tweaks that were made to basic ANTs tools with which they would be more familiar and in a better position to diagnose your problem.
