### ISSUE TITLE
Packaging and releases

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#802]
With the streamlining of the travis configuration, it is possible to have travis push a rendered file onto the github releases page after a successful build.

That, in combination with fixing the cmake configuration so that -DCMAKE_PREFIX_PATH is honoured should allow us to use cpack to create TGZ statically linked tarballs for a variety of distribution, or even cpack rpms or debs to install to say, /opt/ANTs/major.minor.patch

This will require a bit more re-engineering of the cmake config, and a bit more travis work, the question is, is it considered a reasonable goal by the devs?

**Comment by ntustison** [comment]
@gdevenyi Although @stnava should weigh in, I think that would be great.

**Comment by gdevenyi** [comment]
Things to think about for regular releases:
https://semver.org/
https://cmake.org/cmake/help/latest/module/CPack.html
https://docs.travis-ci.com/user/deployment/releases/

**Comment by stnava** [comment]
regular, automated releases would certainly make many people happier,
including me.

brian

**Comment by justbennet** [comment]
This seems like it would be a desirable thing.  I am only the system administrator, so my only comment would be that it would be great if the resulting binary distributions either worked on variety of systems or there were versions for a variety of systems.  I have, right now, Ubuntu 16.04, 18.04, and CentOS 7.  CentOS 8 will be added to the fold by the end of September.

I did notice today that there aren't binary releases for any of 2.3.1, 2.3.0, or 2.2.0.  Last binary release seems to be 2.1.0.

I am getting compilation errors from ITK 5 when following the instructions at https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS, and I'd be quite happy to have a binary distribution available.

**Comment by cookpa** [comment]
Got some releases set to build in #1393. It's a default superbuild, but I'm asking for feedback on potential options in https://github.com/ANTsX/ANTs/discussions/1397

**Comment by cookpa** [comment]
Some sub-issues (like semantic versioning) would be good to revisit at some point but I hope that the progress to date has increased happiness https://github.com/ANTsX/ANTs/releases
