### ISSUE TITLE
Documentation: Clarification on Multiple Metric Input Files for antsRegistration

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#803]
I am planning to investigate registrations using multiple MRI scan types where some scans might have different resolution, and might not be perfectly affinely co-registered to start.

Therefore I'm wondering how antsRegistration handles multiple metric files for registration. Can I provide different initializations for the input files? Do files have to have the same resolution?

**Comment by stnava** [comment]
multiple metrics are similar to multiple channel registration but where the
weights on each channel can differ.

ie they assume the channels are pre-aligned within a given fixed or moving
space.

brian

**Comment by gdevenyi** [comment]
Thanks @stnava, does "pre-aligned" also mean the same resolution, or can they still differ?

**Comment by ntustison** [comment]
It definitely won't work with any displacement field transforms.  My guess is that it won't for any of the linear transforms but you could easily try that case to make sure.

**Comment by gdevenyi** [comment]
Okay, so everything needs to be same-space in the strict sense. Thanks for the clarification!
