### ISSUE TITLE
4D antsApplyTransforms returns empty volumes

### ISSUE THREAD

**Issue by VVanreusel** [ANTsX/ANTs#804]
Dear all,

We want to do the following:
1. Realign a time series to the average image (made by antsMotionCorr) using antsMotionCorr
2. Register this average to a template using antsRegistration
3. Concatenate the deformation fields resulting from step 2 and duplicate them to match the number of time points of the original data
4. Use antsApplyTransforms to apply the deformation fields from step 1 and 3 to the original data.

The issue we encounter is that only the first half of the time series is normalized to the template space, whereas the second half of the time series is empty (i.e. all pixel values of these volumes are zero).
We found a workaround by duplicating the raw time series, performing the aforementioned steps and discarding the second half of the result. 
However we were wondering if there is a cleaner solution to our problem?

Thank you in advance,
Verdi

**Comment by gdevenyi** [comment]
Please provide the commands you used.

**Comment by VVanreusel** [comment]
Thank you for the fast response, here are the original commands (without the dupplication part):

```
antsMotionCorr -d 3 -a subj12722.nii -o subj12722_avg.nii.gz 

antsMotionCorr -d 3 -o [SyNCC,SyNCC.nii.gz,SyNCC_avg.nii.gz] -m CC[subj12722_avg.nii.gz, subj12722.nii,1,1,Regular,1] -t SyN[0.1,3,0.0] -i 100x100x100 -u 1 -e 1 -s 2x1x0 -f 4x2x1 -n 10 -w 1 -v 1


antsRegistration --dimensionality 3 --float 1 \
--interpolation Linear \
--winsorize-image-intensities [0.005,0.995] \
--use-histogram-matching 1 \
--initial-moving-transform [template.nii.gz,SyNCC_avg.nii.gz,1] \
--transform Rigid[0.1] \
--metric MI[template.nii.gz,SyNCC_avg.nii.gz,1,32,Regular,0.25] \
--convergence [100x50x20x10,1e-6,10] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox \
--transform Affine[0.1] \
--metric MI[template.nii.gz,SyNCC_avg.nii.gz,1,32,Regular,0.25] \
--convergence [10x5x2x1,1e-6,10] \
--shrink-factors 8x4x2x1 \
--smoothing-sigmas 3x2x1x0vox \
--transform SyN[0.1,3,0] \
--metric CC[template.nii.gz,SyNCC_avg.nii.gz,1,3,Regular,1] \
--convergence [10x10x10,1e-6,10] \
--shrink-factors 3x2x1 \
--smoothing-sigmas 2x1x0vox \
-x [mask.nii] \
-v 1 \
--output [Average2Template,Average2Template_SynWarped.nii.gz,Average2Template_invSynWarped.nii.gz]

antsApplyTransforms -d 3 -o [Average2Template3D_CollapsedWarp.nii.gz,1] -t Average2Template1Warp.nii.gz -t Average2Template0GenericAffine.mat -r template.nii.gz

ImageMath 3 template4D.nii.gz ReplicateImage template.nii.gz 25 2 0

ImageMath 3 Average2Template4D_CollapsedWarp.nii.gz ReplicateDisplacement Average2Template3D_CollapsedWarp.nii.gz 25 2 0

antsApplyTransforms -d 4 -o bold2template.nii -t Average2Template4D_CollapsedWarp.nii.gz -t SyNCCWarp.nii  -r template4D.nii.gz -i subj12722.nii
```

**Comment by gdevenyi** [comment]
Can you also please provide the version of ANTs you're using. Thanks.

**Comment by VVanreusel** [comment]
Sure, no problem. 

ANTs Version: 2.2.0.dev245-geff5d

If you need anything more please let me know. 
Thanks again!

**Comment by gdevenyi** [comment]
It looks like you're running a fairly old version, there's a recent commit that may be related to your issue: https://github.com/ANTsX/ANTs/issues/737

Can you please update to the HEAD of master and try these steps again? Thanks.

**Comment by VVanreusel** [comment]
Ok, I will do, and I will also check that issue.
Thank you very much! 
I'll let you know if it works.

**Comment by VVanreusel** [comment]
Hey All, 

I am trying to update my version of ANTs according to the steps described [here](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS), but I keep getting this error:

![image](https://user-images.githubusercontent.com/42803559/61446849-2719f080-a950-11e9-9bb8-d5c7f240d503.png)

Does anyone of you know how to solve it? Should I try to first install itk itself so that ANTs doesn't need to do it itself anymore?

Thanks in advance

**Comment by gdevenyi** [comment]
Hi, I think this looks like your GCC version is too old, but I can't comment further without some output from the cmake configuration.

**Comment by VVanreusel** [comment]
I will update the GCC version and try again. 
For now I installed one release earlier (https://github.com/ANTsX/ANTs/releases/tag/v2.3.0), and that didn't do the trick. 
Although the version is still not 2.3.0, so I might have made a mistake somewhere.

ANTs Version: 2.2.0

I'll continue with your suggestions and keep you updated. 
Thank you very much.

**Comment by cookpa** [comment]
To build the latest code you will need GCC 5 or later. 

Probably the most efficient workaround is to disassemble the time series with ImageMath's TimeSeriesDisassemble, then deform the images, then use ImageMath TimeSeriesAssemble.

**Comment by VVanreusel** [comment]
As I installed GCC 8.3.0 and got the same error, I think that workaround is for now the best way to go.
If someone however is able to fix that error, I will be very thankful. 
If one needs any more output please let me know, I'll gladly provide you.

Thanks a lot

**Comment by gdevenyi** [comment]
Our automated builds with gcc-8 work for us:
https://travis-ci.org/ANTsX/ANTs/jobs/555039706

In order to help any further we will need more comprehensive logging from the build.

**Comment by VVanreusel** [comment]
Dear All,

After quite some time we managed to update our ants version to:
ANTs Version: 3.0.0.0.dev97-g946c7
Compiled: Aug 12 2019 09:40:10

However, this didn't solve the problem.
After running the code shown in my second post here, volumes 14-25 only contain zeros.
We are currently running something like the workaround proposed by Cookpa, but in our case this leads to a two time interpolation which should be avoided.

Does anyone have an idea how to solve this issue?

Thank you in advance,
warm regards,
Verdi

**Comment by gdevenyi** [comment]
This sounds more like maybe the registration is failing for generating the transform. What happens if you apply identity transform (no -t)

**Comment by VVanreusel** [comment]
Well, as doing antsApplytransforms with the identity transform also 'deletes' volumes 14-25, I think the problem is not a failure of the registration. 
I also replaced the volumes 14-25 of the original 4D by volumes 1-12 to check wether the issue was due to the input data itself, but this gave me the same result (with or without transformation).

**Comment by gdevenyi** [comment]
Is this perhaps a header issue with the original file? What does PrintHeader say?

**Comment by VVanreusel** [comment]
That might be the case, I am currently checking what I get if I crop the nii to the first 13 volumes. 
But here you have the PrintHeader result:

```
PrintHeader mmouse-BL_B0001_12722.nii
 Spacing [1.5625, 1.875, 1.875, 1]
 Origin [73.4375, 88.125, -58.125, 0]
 Direction
-1 0 0 0
0 -1 0 0
0 0 1 0
0 0 0 1

 Size : [96, 96, 64, 25]

  Image Dimensions   : [96, 96, 64, 25]
  Bounding Box       : {[73.4375 88.125 -58.125 0], [223.438 268.125 61.875 25]}
  Voxel Spacing      : [1.5625, 1.875, 1.875, 1]
  Intensity Range    : [0, 32766]
  Mean Intensity     : 1378.29
  Direction Cos Mtx. :
-1 0 0 0
0 -1 0 0
0 0 1 0
0 0 0 1

  Voxel->RAS x-form  :
  Image Metadata:
    ITK_FileNotes = Masked
    bitpix = 16
    cal_max = 0
    cal_min = 0
    datatype = 4
    descrip = Masked
    dim[0] = 4
    dim[1] = 96
    dim[2] = 96
    dim[3] = 64
    dim[4] = 25
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    dim_info = 0
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    nifti_type = 1
    pixdim[0] = 0
    pixdim[1] = 1.5625
    pixdim[2] = 1.875
    pixdim[3] = 1.875
    pixdim[4] = 1
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 2
    qform_code_name = NIFTI_XFORM_ALIGNED_ANAT
    qoffset_x = -73.4375
    qoffset_y = -88.125
    qoffset_z = -58.125
    quatern_b = 0
    quatern_c = 0
    quatern_d = 0
    scl_inter = 0
    scl_slope = 1
    sform_code = 2
    sform_code_name = NIFTI_XFORM_ALIGNED_ANAT
    slice_code = 0
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = 1.5625 0 0 -73.4375
    srow_y = 0 1.875 0 -88.125
    srow_z = 0 0 1.875 -58.125
    toffset = 0
    vox_offset = 352
    xyzt_units = 10

```

**Comment by VVanreusel** [comment]
I think I found the problem, namely that the time spacing of the 4D template was 2 whereas for the 4D timetrace it was 1. Putting them both the same fixed the problem when using only volumes 1-13 with the identity transform. I'll run the original code again with this solution and inform you about the outcome.

If this fixes it, it was a very stupid mistake. 
Thank you all for the fast responses and all the help.

**Comment by VVanreusel** [comment]
Thank you all, the difference in time spacing was the problem.
