### ISSUE TITLE
is:issue is:open Invert the Warp from a combined Warp file -> is it possible?

### ISSUE THREAD

**Issue by braincharter** [ANTsX/ANTs#805]
Hi, I've used antsApplyTransform to combine all my transformation (t2-B to t2-A to t1 to MNI), which gives me a single Warp file but no InverseWarp. 

Is there a way to compute this inverseWarp from the Warp file? Or should I redo the same process as I did (but inverse) to get the inverseWarp manually?

**Comment by ntustison** [comment]
What were your commands for the forward transformation?

**Comment by braincharter** [comment]
Basically, the more important one was:

antsApplyTransforms -v -d 3 -i T2_meanvol.nii.gz -n BSpline[5] \
         -o [T2pre_2_MNI_ComposedWarp.nii.gz, 1] \
         -t T1mid_2_MNI_ComposedWarp.nii.gz \
         -t T2mid_2_T1mid_ComposedWarp.nii.gz \
         -t T2pre_2_T2mid_ComposedWarp.nii.gz \
         -r MNI.nii.gz

With each "ComposedWarp" generated using something like:

antsApplyTransforms -v -d 3 -i T2_meanvol.nii.gz -n BSpline[5] \
         -o [T2pre_2_T2mid_ComposedWarp.nii.gz, 1] \
         -t T2pre_2_T2mid0GenericAffine.mat \
         -t T2pre_2_T2mid1Warp.nii.gz \
         -r T2mid.nii.gz

**Comment by ntustison** [comment]
What was the ``antsRegistration`` call that produced the second ``antsApplyTransforms``?  It's highly unconventional and I just want to make sure everything up to the current issue is correct.

**Comment by braincharter** [comment]
antsRegistration -v -d 3 \
 -o [T2pre_2_T2mid, T2pre_2_T2mid.nii.gz]  \
 -m mattes[  T2pre.nii.gz, T2mid.nii.gz , 1 , 32, random , 0.25 ] -t affine[ 0.25 ]  \
 -c [1009x200x100,1.e-8,20] -s 4x2x0 -f 4x2x1\
 -m mattes[  T2pre.nii.gz, T2mid.nii.gz , 1 , 32 ] -t syn[ 0.25, 3, 0.0 ] \
 -c [200x100x50,1.e-8,10] -s 2x1x0 -f 4x2x1 \
 
I think the only "problem" is that when using antsApplyTransform to combine the transformations (I never used that before, but it works well!), there is no InverseWarp outputted. So I could do exactly the same but in reverse, but I just wondered if there was a tool to invert that warp file.

**Comment by ntustison** [comment]
I don't know where you got the ordering above for making the forward composed warp but it seems like this is what you want:

```
##  Create forward warp going from fixed image to moving image

antsApplyTransforms -v -d 3 
-o [T2pre_2_T2mid_ComposedWarp.nii.gz, 1] 
-t T2pre_2_T2mid1Warp.nii.gz 
-t T2pre_2_T2mid0GenericAffine.mat 
-r T2pre.nii.gz
```
```
##  Create inverse warp going from moving image to fixed image

antsApplyTransforms -v -d 3 
-o [T2pre_2_T2mid_ComposedInverseWarp.nii.gz, 1] 
-t [T2pre_2_T2mid0GenericAffine.mat,1]
-t T2pre_2_T2mid1InverseWarp.nii.gz 
-r T2mid.nii.gz
```
