### ISSUE TITLE
ImageMath command failing on paths containing periods

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#807]
**Describe the bug**
ImageMath PropagateLabelsThroughMask breaks if the output file path contains periods.

**To Reproduce**

ImageMath 3 PropagateLabelsThroughMask /tmp/dir.with.periods/myPropagated.nii.gz mask.nii.gz labels.nii.gz

**Additional context**

This function attempts to write the output file (eg myPropagated.nii.gz) as well as supplementary files (eg myPropagated_speed.nii.gz ). But it looks for the first period in the output path, which causes problems. In the above example, it would try to write  /tmp/dir_speed.with.periods/myPropagated.nii.gz.

---

Has this been solved elsewhere in the code? I know there was a fix on the scripting side. Is there code anywhere in ANTs to correctly find and strip the image extension?

**Comment by ntustison** [comment]
For this particular case, I would opt for not writing out those additional images.  I don't know that they have any use other than possible debugging.

**Comment by cookpa** [comment]
OK, I will push that change once I've tested it.
