### ISSUE TITLE
antsRegistration smoothing-sigmas and anisotropic voxels

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#808]
If I have anisotropic resolution for the fixed image like 0.39x0.39x2. I'm guessing that if I specify a smoothing of 2vox I will get two voxels of smoothing in each dimension. Is that correct.

Similarly if instead I specify 2mm, will I actually get a real-space 2mm sigma such that I'll get isotropic smoothing?

**Comment by ntustison** [comment]
Yes and yes.

**Comment by gdevenyi** [comment]
Cheers thanks.
