### ISSUE TITLE
antsRegistration shrink-factors and anisotropic voxels

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#809]
Following up on #808, while there is a mechanism to achieve isotropic smoothing during antsRegistration, I cannot currently find a way to achieve isotropic shrinks as shrinks are defined as selecting every Nth voxel in each dimension.

Due to this, I can run into the following situation
- either construct an image pyramid based on the smallest resolution in an image, and run the risk of sampling the largest resolution out of existence if I step too large
- construct an image pyramid based on the largest resolution, and fail to sufficiently sample the smallest resolution, resulting in an undersampled pyramid

My solution to such a problem thus-far has been to isotropically resample anisotopic data before processing to the smallest resolution to avoid this.

I would like to suggest a suffix addition of "mm" similar to smoothing-sigmas that will ask ANTs to sample at that step size in real-space coordinates, rather than shrinking on dimensions.

**Comment by gdevenyi** [comment]
Following up...

It looks like this might already be implemented:
--shrink-factors 17 on an 0.39x0.39x2 anisotropic fixed space yields:
  Shrink factors (level 1 out of 8): [17, 3, 17]

17x0.39 = 6.63 and 3x2 = 6 so maybe the code already does this somewhere?

**Comment by cookpa** [comment]
I forget how this is currently implemented but in `ANTS`, there was a hard limit of 32 voxels along each dimension. So if you had a 512x512x128 image, your maximum shrink factor along z was 4.

**Comment by gdevenyi** [comment]
Poking it a bit more with some inputs, it seems indeed that the implementation doesn't match the docs precisely. The shrink applies the smallest dimension and the other dimensions are scaled to make it isotropic in space. This is good, but undocumented from what I can tell.

**Comment by ntustison** [comment]
ITK's ShrinkImageFilter class is responsible for the downsampling.  To add the requested functionality would require switching this out for something like the ResampleImageFilter.  This would be doable but not trivial.

**Comment by gdevenyi** [comment]
Taking a look at ShrinkImageFilter vs ResampleImageFilter it would also be nice to enable (selectable) interpolation during subsampling. This also opens up the possibility of fractional subsamples, and supersamping (going below 1)

**Comment by ntustison** [comment]
[Adding more features is not necessarily a good thing](https://en.m.wikipedia.org/wiki/Feature_creep).  The proposed changes would make the command line more complicated and it’s not clear that the number of relevant use cases for improved performance would be significant.  Besides the current tool can easily accommodate a resampling workflow if the user performs such resampling themselves.   All this to say that I am not convinced that such changes are warranted or worth the trouble.

**Comment by cookpa** [comment]
There’s also customizable smoothing before downsampling at each level, which should be effective as interpolation

Sent from my iPhone

On Jul 28, 2019, at 2:07 PM, Nick Tustison <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding more features is not necessarily a good thing<https://en.m.wikipedia.org/wiki/Feature_creep>. The proposed changes would make the command line more complicated and it’s not clear that the number of relevant use cases for improved performance would be significant. Besides the current tool can easily accommodate a resampling workflow if the user performs such resampling themselves. All this to say that I am not convinced that such changes are warranted or worth the trouble.
