### ISSUE TITLE
How to handle with rotated atlas images during construction template

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#810]
I am using the following images to construct template. 
![Serial-MRI-in-a-patient-with-relapsing-remitting-multiple-sclerosis-Proton-density_Q320](https://user-images.githubusercontent.com/24875971/61994174-8343e980-b0a1-11e9-837b-dc0c333b1750.jpg)

As shown in figure, these images rotates 10~15 degrees, so the template that is constructed from these images also rotated. In the paper reports, I saw the template does not roate. How can I handle with the issue when the input atlas images rotated? Thanks

**Comment by ntustison** [comment]
You can use the ``-z`` option to specify an initial (unrotated) template with the rigid option ``-r`` turned on.

**Comment by John1231983** [comment]
Thanks. The -z option needs to input an initialTemplate but I have no the initialTemplate file. I also have turned on -r 1.

**Comment by gdevenyi** [comment]
You need to choose an initial template, such as the MNI model to provide a rigid target

**Comment by John1231983** [comment]
@gdevenyi: great suggestion. For brain MRI, my images resolution is 0.4x0.4x0.4, while the mni template is 1x1x1. Should I resample the mni template to 0.4x0.4x0.4 before using it as initial template? Thanks

**Comment by gdevenyi** [comment]
Definitely. The initial template defines the orientation and resolution of the final template. You can use ResampleImage for this.

**Comment by John1231983** [comment]
@gdevenyi : I did it, however the final template still rotated. I used the above script. Does it has any issue?

**Comment by gdevenyi** [comment]
To help any further please share some screenshots of the inputs initial templates and final template.

**Comment by cookpa** [comment]
I think you need `-z initialTemplate.nii.gz -r 0 -y 0` to remove the rigid component of the template update step.

**Comment by cookpa** [comment]
Normally I handle this by first creating a template with the defaults, manually rotating it to the desired orientation in ITK-SNAP, then running 2 or 3 more iterations with `-z manuallyAlignedTemplate.nii.gz -r 0 -y 0`.

**Comment by John1231983** [comment]
@cookpa : Great suggestion. How do you manually rotate the image to the desired orientation? Could you provide some command line?

**Comment by cookpa** [comment]
It's done in the GUI. Load the image, then load another copy as an overlay, then go to Tools -> Registration. On the manual tab you can change rotation parameters, or you can turn the wheels in the main window.

Then you reslice the image and save it.

![image](https://user-images.githubusercontent.com/611507/62474898-ea346300-b771-11e9-93bf-bced684de264.png)

**Comment by sufkes** [comment]
Hi, 
I had the same problem with `antsMultivariateTemplateConstruction2.sh` in that I created a template with no target volume (i.e. I did not use the -z option), and the resulting template was rotated off-axis (1st image below).  The options I used in this first trial were:
`-d 3 -o ${out}T_ -i 4 -g 0.25 -c 4 -k 1 -w 1 -f 6x4x2x1 -s 3x2x1x0 -q 100x100x70x20 -n 1 -r 1 -l 1 -m CC -t SyN -v 16gb ${in}/*`

Trying to follow @cookpa's suggestion (Aug 5, 2019), I took that template, manually rotated it using ITK-SNAP (2nd image below), and then tried creating the template again. I started with the original (unwarped) images, and used the options `-z rotatedTemplateFromTrial1.nii.gz -r 0 -y 0`. The full options I used in this second trial were:
`-z rotatedTemplateFromTrial1.nii.gz -d 3 -o ${out}T_ -i 4 -g 0.25 -c 4 -k 1 -w 1 -f 6x4x2x1 -s 3x2x1x0 -q 100x100x70x20 -n 1 -r 0 -y 0 -l 1 -m CC -t SyN -v 10gb ${in}/*`
The template resulting from this second trial was much better-aligned than the result of trial 1, but it was still rotated significantly off-axis (3rd image below).

Do you have any thoughts on why the result of Trial 2 (3rd image) is slightly rotated relative to the target volume (2nd image)? Is there an issue with any of the options that I used in Trial 2? @cookpa's comment mentioned "...then running 2 or 3 more iterations with...". I'm not sure exactly what is meant by "2 or 3 *more* iterations" -- I created a new template directory and reran using the same input images as in Trial 1, but with the aforementioned changes to the options. Am I missing something?

Result of Trial 1:
![trial_1](https://user-images.githubusercontent.com/28952185/76632621-ddeb6200-6519-11ea-92b3-569077aa0ad2.png)

Result of Trial 1 after manual rotation:
![trial_1_manually_rotated](https://user-images.githubusercontent.com/28952185/76632623-de83f880-6519-11ea-9a8a-e11e0f239ce9.png)

Result of Trial 2, in which the manually rotated template from Trial 1 was used as the target volume.
![trial_2](https://user-images.githubusercontent.com/28952185/76632625-df1c8f00-6519-11ea-853a-a1b7e2841168.png)

**Comment by ntustison** [comment]
Instead of running ``-i 4`` for Trial 2, try ``-i 0`` and looking at the results of the registration of each individual subject after the rigid alignment.

**Comment by sufkes** [comment]
Thanks for the prompt suggestion. I'm not sure exactly what you mean. I just tried another run, again starting with the original unwarped images and the following options:
`-z rotatedTemplateFromTrial1.nii.gz -d 3 -o ${out}T_ -i 0 -g 0.25 -c 4 -k 1 -w 1 -f 1 -s 0 -q 20 -n 1 -r 1 -y 0 -l 1 -m CC -t SyN -v 10gb ${in}/*`
The only output image I see is `T_template0.nii.gz`, which is shown below. Is this what you meant, and what should I be looking for?

Result of Trial 3 - Register original unwarped images to manually rotated template from Trial 1, and use option `-i 0`
![trial_3](https://user-images.githubusercontent.com/28952185/76646952-3cbcd580-6532-11ea-9f20-b4604a75513e.png)

Thanks very much

**Comment by ntustison** [comment]
Yes, that's correct.  And this looks like it should.  You can try looking at adding iterations to see where it starts to deviate but my guess is that the affine averaging is causing the problems.  If you want a bilaterally symmetric template, one possible approach would be to flip each subject using ``ImageMath ... ReflectionMatrix ...`` and then creating a template with all your subjects and their reflected counterparts.

**Comment by sufkes** [comment]
Thanks,
If I were to try adding iterations and determine where it was starting to rotate, what could I then do to remedy it? I don't necessarily want a bilaterally symmetric template - I just want the template to be aligned with the image frame.
Could this type of rotation be a symptom of some problem with the options I used, or is this just something that happens in this algorithm?

**Comment by cookpa** [comment]
Hmm, it's like `-y 0` is not removing the rotation entirely. It's possible that either

a. there's a bug preventing the `-y 0` option from a correctly removing the rotation.

b. The rigid registration step is not fully capturing the rotation. Residual rotations encoded in the deformable step will not be removed with `-y 0`. 

The intent of `-y 0` was to prevent extreme problems like templates disappearing from the field of view. It might not be possible to prevent the template moving entirely. It might be better just to finish your template and then rotate it manually at the end of the procedure.

**Comment by sufkes** [comment]
Thanks for the information and suggestion. (b) seems possible as the rotation is quite slight.
