### ISSUE TITLE
Potential bug in antsMultivariateTemplateConstruction

### ISSUE THREAD

**Issue by mattcieslak** [ANTsX/ANTs#811]
**Describe the bug**
I'm not sure this is a bug, but wanted to make sure I'm understanding the algorithm correctly. In the `shapeupdatetotemplate()` function the affine transforms from the current iteration are averaged. The transforms from the `Warp.nii.gz` images are also averaged and multiplied by the gradient step. The averaged and gradient-step-multiplied warp is then transformed by the inverse of the average affine transform. Finally, the transformed and gradient-step-multiplied warp is applied along with the inverted average affine transform here: https://github.com/ANTsX/ANTs/blob/v2.3.1/Scripts/antsMultivariateTemplateConstruction2.sh#L384

Is it correct that this warp should be added to the transform stack four times? It is applied 4 times in both `antsMultivariateTemplateConstruction.sh` and `antsMultivariateTemplateConstruction2.sh`. Is this related to the gradient step size default being 0.25?

Thanks in advance!

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/issues/806

**Comment by mattcieslak** [comment]
I'm not sure how this issue didn't come up when I searched. Sorry for the duplication

**Comment by ntustison** [comment]
No worries.  The same issue with a different title might make it easier for the topic to be found in the future.
