### ISSUE TITLE
LabelClustersUniquely -> different behaviour for ITK 4.12 / ITK 5.0

### ISSUE THREAD

**Issue by crossmanith** [ANTsX/ANTs#813]
ITK changed the instantiation of ConnectedComponentImageFilter from

ConnectedComponentImageFilter()
  {
    m_FullyConnected = false;
    m_ObjectCount = 0;
    m_BackgroundValue = NumericTraits< OutputImagePixelType >::ZeroValue();
  }

to
ConnectedComponentImageFilter() :
    ScanlineFilterCommon< TInputImage, TOutputImage >(this),
    m_BackgroundValue( NumericTraits< OutputPixelType >::NonpositiveMin() )

what means the the background value isn't set to 0 necessarily. For an image with background 0 and some labelled objects != 0 and with a floating point pixel type this leads to a huge component labelled with 1 comprising the background pixels and components labelled 2, 3, ... for the objects. With ITK 4.12 the 0-valued background was discarded and objects were labelled starting from 1.

We can get the old behaviour back by adding a line
filter->SetBackgroundValue( 0 );
in LabelClustersUniquely.cxx

**Comment by ntustison** [comment]
Great.  Thanks for pointing this out.  Can you put together a pull request?  If not, I can take care of it early next week.

**Comment by ntustison** [comment]
It appears that [this already exists in the current program](https://github.com/ANTsX/ANTs/blob/master/Examples/LabelClustersUniquely.cxx#L93).  Please reopen if this doesn't resolve the issue.

**Comment by dorianps** [comment]
Maybe this topic is related to this other, which was fixed for ANTsR.
https://github.com/ANTsX/ANTsR/issues/263
