### ISSUE TITLE
Equvalent to rigid body registration in flirt (--dof 6)

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#814]
I have a template image as a fixed image and moving image. I want to do rigid body registration that can do in flirt with dof of 6 ( translation + rotation)

>Restrict the transformation type. For 3D to 3D mode the DOF can be set to 12 (affine), 9 (traditional), 7 (global rescale) or 6 (rigid body). In 2D to 2D mode only 3 DOF (rigid body) transformations are allowed.

In ANTS, I only can find the option `-a` that closed to rigid-body registration. 
 
https://github.com/ANTsX/ANTs/blob/f154285a72c357366a4ad99bd2eef946eb843878/Scripts/antsRegistrationSyN.sh#L71

But I think the affine transformation will scale my moving image to fit with the template image, that I did not want. I only want to rotate and translation my moving image to the same space with template image without changing the brain size. Which option should I use? Thanks

This is my current command
```
antsRegistrationSyN.sh  -d 3 -f template.nii -m moving_T1.nii -o T1toTemplate.nii.gz -n 16 -t a
```

**Comment by ntustison** [comment]
“-t r” specifies a rigid registration transform (rotation + scaling).

**Comment by John1231983** [comment]
I do not want to scale. Just rotation and translation.

**Comment by ntustison** [comment]
Typo.  Fixed it.
