### ISSUE TITLE
How to "roughly aligned together" for my custom dataset?

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#815]
I have my own dataset that includes 95 subjects. I want to build a template image from the dataset. So, the very beginning step, one paper mentioned that 
> the 95 subjects were simultaneously registered to the common space. Briefly, all images were first roughly aligned together by using affine transformation

Besides, @ntustison also mentioned that 
> Also, make sure that the pairs of images are mutually aligned before running antsMultivariateTemplateConstruction.sh
https://sourceforge.net/p/advants/discussion/840261/thread/1659f99a/

Currently, I am using `antsMultivariateTemplateConstruction2.sh` to build the template. I do not want to register to MNI space because my dataset has other age and resolution. I want to make my own space from the dataset. Hence, I am wondering how can we do roughly aligned all images together by using affine transformation to make an initial template? Thanks

**Comment by gdevenyi** [comment]
Take the MNI model, and resample it using ResampleImage to the desired resolution.

Use -z mnimodel.nii.gz and -r to pre-align your input images to the MNI space before modebuilding.

Unless your population are neonates or very small children the MNI model should be a good enough rigid starting point.

**Comment by John1231983** [comment]
Yes. my data is neonates. I cannot use MNI. I need to build my own space

**Comment by gdevenyi** [comment]
Choose a representative subject, use ITK-snap to change the alignment according to https://github.com/ANTsX/ANTs/issues/810#issuecomment-518275966

Use that rotated image as the -z corrected_orientation.nii.gz and use -r in the run to rigidly align all subjects to that alignment before starting the model build.

**Comment by John1231983** [comment]
@gdevenyi : It looks like not the meaning of roughly aligned together. I think it should be in the loop for example
```
for i in range (1, 94):
     for j in range (j, 95)
           align subject i with subject j
 
```

**Comment by gdevenyi** [comment]
You do not need such complexity if you align to a single canonical target

**Comment by John1231983** [comment]
Actually, I do not know which orientation will be correct by manual align with itksnap. I would like to do it by code that can correct if i have a set of larger subject

**Comment by John1231983** [comment]
@ntustison : How about opinion?

**Comment by ntustison** [comment]
You seem to be going down an unnecessarily complex path for your stated objective specified in the original post.  I believe you ran the 2-D examples so you have everything you need to build your own template in your own space.  If you want it *rigidly* aligned with the MNI template, do as @gdevenyi suggested.  If not, then don't use anything for the ``-z`` option and let the script bootstrap one for you.  If you're still having trouble understanding, just run the script using your data and you'll probably alleviate your disconnect as you see the results.

**Comment by gdevenyi** [comment]
@John1231983 I also provided a "dumb" quick rigid self-alignment to the group average at https://github.com/ANTsX/ANTs/issues/674#issuecomment-452067967

**Comment by John1231983** [comment]
Great thank @gdevenyi .  I used it and this is a result that can be used as the initial template. The problem is that the axial view looks rotated and shifting (not in the center). Do I need to do anything to center the result 

![snapshot0003](https://user-images.githubusercontent.com/24875971/62783711-f890c080-ba8a-11e9-96de-6b3d2b1b2fbb.png)
![snapshot0002](https://user-images.githubusercontent.com/24875971/62783712-f890c080-ba8a-11e9-9483-7e6d31273525.png)
![snapshot0001](https://user-images.githubusercontent.com/24875971/62783713-f890c080-ba8a-11e9-8dd9-53b79da8cf3f.png)

**Comment by gdevenyi** [comment]
You can use ITKSnap to edit the file to change the FOV and paddding. I believe ANTs folks recommend at least 10v padding on all sides.
