### ISSUE TITLE
Ways to Pad Output Images with Certain Value/Edge Voxel Value

### ISSUE THREAD

**Issue by Lingfeng158** [ANTsX/ANTs#816]
The ``` ANTsRegistrationSynQuick``` works well for lung image co-registration. However, when we co-register a limited field of view image with wide field of view image as fixed image (reference), the  output image will include areas of padded value of 0 around original image.  

Is there a way to specify the padding value to a value or to set padding value to edge voxel values?  

![img](https://user-images.githubusercontent.com/35275986/62719853-7e9b0180-b9ce-11e9-98fc-7cedb32eb6cd.png)

**Comment by ntustison** [comment]
Use the transform files produced with ``antsRegistrationSyNQuick.sh`` to warp the moving image and use the ``-f`` option in ``antsApplyTransforms`` to specify a different default value.

**Comment by Lingfeng158** [comment]
Thank you for promptly answering my question! I'm currently a little bit confused about the usage of ```antsApplyTransform``` .  

 Assume the moving image is called ```mov.nii.gz``` and fixed image is called ```fix.nii.gz``` and output prefix is ``` OPT```.  

Output of ```antsRegistrationSyNQuick.sh``` will then be ```OPTWarped.nii.gz, OPTInverseWarped.nii.gz, OPT1Warped.nii.gz, OPT1InverseWarped.nii.gz``` and ```OPT0GenericAffine.mat```, and we would like pad value to be 170.  

Should the command be ```antsApplyTransforms -d 3 -r fixed.nii.gz -i mov.nii.gz -o [outputName.nii.gz,0] -t OPT1Warped.nii.gz -t OPT0GenericAffine.mat -f 170``` if my understanding is correct? Should I include both ```OPT1Warped.nii.gz``` and ```OPT0GenericAffine.mat``` as transform?

**Comment by ntustison** [comment]
Almost.  It should be

```
antsApplyTransforms -d 3 -r fixed.nii.gz -i mov.nii.gz -o outputName.nii.gz -t OPT1Warp.nii.gz -t OPT0GenericAffine.mat -f 170
```

Although it's fine, you don't need to specify ``-o [outputName.nii.gz,0]`` and I think you conflated the warped output with the actual warp file.

**Comment by Lingfeng158** [comment]
I can get result fairly quickly with  
```antsApplyTransforms -d 3 -r fixed.nii.gz -i mov.nii.gz -o outputName.nii.gz -t OPT1Warp.nii.gz -t OPT0GenericAffine.mat```
However, when adding ```-f 170```, the program gives 
```
ERROR:  Invalid flag provided f
```
Also, what do you mean by "conflated the warped output with the actual warp file"?

**Comment by Lingfeng158** [comment]
After reading documentation in terminal, the actual implementation used ```-v``` flag instead of ```-f``` flag introduced [here](https://github.com/ANTsX/ANTs/wiki/Warp-and-reorient-a-diffusion-tensor-image) and [here](http://manpages.org/antsapplytransforms)

**Comment by ntustison** [comment]
You might have an old version.  The ``-f`` option works with the current repository.

**Comment by Lingfeng158** [comment]
Okay, thank you very much! I will check my version.
