### ISSUE TITLE
itkLabelImageGenericInterpolateImageFunction.h requirement

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#817]
**Describe the bug**
ANTs won't build as it requires `itkLabelImageGenericInterpolateImageFunction.h`: 
[build.log](https://github.com/ANTsX/ANTs/files/3487216/build.log).

**Desktop (please complete the following information):**
 - OS: Genoo Linux

**Additional context**
[This](https://github.com/ANTsX/ANTs/files/3487223/itk.txt) is the list of ITK files available on my machine (installed `=itk-5.0.1`). Note that there are a number of interpolation functions, just not this “Generic” one. From [previous discussions](https://github.com/ANTsX/ANTs/issues/612#issuecomment-493694879) I understand ANTs is tightly synced with ITK. That's not an issue, as long as you know what ANTs commit might work with ITK 5.0.1.

I have tried a few commits, from around and before the ITK 5.0.1 release date, and they all seem to be looking for this file which my ITK install does not ship. Could this be an ITK issue?

**Comment by ntustison** [comment]
Is this using the Superbuild mechanism or your own ITK build?

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/blob/master/SuperBuild/External_ITKv5.cmake#L131

**Comment by TheChymera** [comment]
@ntustison the build.log I posted suggests this is indeed using my own ITK (of which you can see the constituent files linked in the original post):

```
cmake
    -C /var/tmp/portage/sci-biology/ants-9999/work/ants-9999_build/gentoo_common_config.cmake
    -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr
    -DITK_DIR=/usr/include/ITK-5.0/
    -DUSE_SYSTEM_ITK=ON
    -DUSE_SYSTEM_VTK=ON
    -DBUILD_TESTING=OFF
    -DCMAKE_BUILD_TYPE=Gentoo
    -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-biology/ants-9999/work/ants-9999_build/gentoo_toolchain.cmake
    /var/tmp/portage/sci-biology/ants-9999/work/ants-9999
```

**Comment by ntustison** [comment]
Yeah, I'd rather not dig through your build log if you can provide a quick answer.  Related to @gdevenyi 's link, you probably didn't turn on the corresponding module.

**Comment by TheChymera** [comment]
@ntustison how can I turn on the corresponding module?

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/blob/master/SuperBuild/External_ITKv5.cmake#L131
