### ISSUE TITLE
Current master fails when buit with testing support

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#821]
I am building ANTs (44f1cb824be9efde54ff7bf4cc8699b6842e5fcd) with

```
cmake -C /var/tmp/portage/sci-biology/ants-9999/work/ants-9999_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DITK_DIR=/usr/include/ITK-5.0/ -DUSE_SYSTEM_ITK=ON -DUSE_SYSTEM_VTK=ON -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-biology/ants-9999/work/ants-9999_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-biology/ants-9999/work/ants-9999
```

If I remove the `-DBUILD_TESTING=ON` bit it builds fine, but as is I get the following [build.log](https://github.com/ANTsX/ANTs/files/3541563/build.log).

Can you help me out? Ideally I'd like to support testing as well on my distribution.

**Comment by TheChymera** [comment]
Thank you.

this URL seems to not work: http://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=84cf0e06646142e0aa4c3d3324a62701&algorithm=MD5

Regarding http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=84cf0e06646142e0aa4c3d3324a62701 --- should I just download that into `/var/tmp/portage/sci-biology/ants-9999/work/ants-9999/.ExternalData/MD5/`? I assume there is more data that needs to go in there as well, right? Is there a full data bundle somewhere via which I can get all the data?

**Comment by gdevenyi** [comment]
The second URL is "old" the first one does work to grab the file.

Following up here, I believe you sorted this with the ITK, downloading the files manually.

You can stick them all in an external data folder and do this: https://github.com/ANTsX/ANTs/blob/master/.travis.yml#L287 to make ANTs find them and not try and download.

**Comment by TheChymera** [comment]
@gdevenyi how would one “grab” the file with the first URL? in the browser the page appears broken, and with wget it just hangs:

```
chymera@darkhost ~ $ wget https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=84cf0e06646142e0aa4c3d3324a62701&algorithm=MD5
[1] 27984
[2] 27985
chymera@darkhost ~ $ 
Redirecting output to ‘wget-log.3’.
```

Also, where is the external data directory? I see no `.ExternalData`, analogously to ITK in the build directory.

**Comment by gdevenyi** [comment]
The second URL is "old" the first one does work to grab the file.
The slicer link works for the same file.

On a normal online build, you can ExternalData at ANTS-build/ExternalData

**Comment by gdevenyi** [comment]
Reporter should have all the feedback to solve this.

**Comment by TheChymera** [comment]
can confirm, this worked.
