### ISSUE TITLE
Registration failure 

### ISSUE THREAD

**Issue by EmilyLars** [ANTsX/ANTs#826]
I'm working on a multisite project and I'm trying to register S0 images to T1 images. The results look lovely for 2 sites, but horrible for one. All the input data look good, so far the only difference I can tell is that for the sites that look good the sform/qform are set to 1, but for the site that fails it's 0. Could that be the reason it's failing? Or what else should I check?

**Comment by ntustison** [comment]
What are you using to view the results?

**Comment by cookpa** [comment]
It's quite likely that qform = 0 is the problem, that is a legacy feature of NIFTI and will result in the image being interpreted differently.

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

Also, though this probably isn't the issue here, be sure you are not mixing 4D and 3D images:

https://github.com/ANTsX/ANTs/issues/250

**Comment by EmilyLars** [comment]
I'm using fslview. Yep I checked and both files are 3D. I know you shouldn't mess with orientation info if at all possible but how can I fix this?

**Comment by ntustison** [comment]
As mentioned in the link provided by @cookpa, different packages handle the qform/sform in different ways.  Please use something that is ANTs-compatible, like [ITK-snap](http://www.itksnap.org), to view the results.

**Comment by EmilyLars** [comment]
Still looks funky
<img width="380" alt="Screen Shot 2019-08-29 at 3 06 23 PM" src="https://user-images.githubusercontent.com/24473709/63979831-b5fd4b00-ca6e-11e9-8ae7-19c4aea81e1b.png">

**Comment by ntustison** [comment]
Did you look at the input images in SNAP to make sure they're oriented similarly?  

If you can post the data, that would probably be the quickest way for us to diagnose the problem.

**Comment by EmilyLars** [comment]
Aha! Yep the DTI data for that site were A/P flipped. Works now. Thanks!
