### ISSUE TITLE
How to smooth warped label in registration?

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#827]
I am using greedyreg to obtain the warped label image. It has one option to smooth label using gaussian. 

```
Label interpolation (LABEL): this special mode is used for warping/reslicing multi-label segmentations. This mode applies a little bit of smoothing to each label in your segmentation (including the background), warps this smoothed segmentation, and then performs voting among warped smoothed binary segmentations to assign each voxel in reference space a label. This works better than nearest neighbor interpolation (less aliasing). 
The <sigma_spec> parameter to the -ri LABEL command specifies the standard deviation of the Gaussian kernel used to smooth the labels. It can be provided in voxel units (e.g., 0.2vox) or millimeter units (e.g., 0.2mm). Value of 0.2vox works well in most situations.
> greedy -d 3 \
    -rf reference.nii \
    -ri LINEAR \
    -rm t1mri.nii.gz warped_t1mri.nii.gz \
    -ri LABEL 0.2vox \
    -rm segmentation.nii.gz warped_seg.nii.gz \
    -r ...
```
For Ants, do we have any way to smooth warped label, given the fixed, moving, and transformation metric. 
https://sites.google.com/view/greedyreg/documentation?authuser=0

Thanks

**Comment by ntustison** [comment]
Cf.

``antsApplyTransforms ... -n Gaussian ...``

or 

``antsApplyTransforms ... -n GenericLabel[...] ...``

**Comment by John1231983** [comment]
@ntustison : Thanks. For `GenericLabel`, does it perform smooth label? I did not find the option to insert the sigma

**Comment by ntustison** [comment]
No, please read [this](https://www.insight-journal.org/browse/publication/950).

**Comment by John1231983** [comment]
@ntustison : Thanks. If I used ` -n BSpline` in the raw image, should I use `-n GenericLabel[Linear]` or `-n GenericLabel[BSpline]` for label?

**Comment by ntustison** [comment]
No, they're two different operations.  If you read that paper, I think they give a recommendation.

**Comment by gdevenyi** [comment]
Indeed, the implementation of GenericLabel is to use the recommended implementation from the paper.

**Comment by John1231983** [comment]
@ntustison and @gdevenyi : Thanks for your comments. 
I meant that if I used -n BSpline to interpolate the moving image to moved image, then which option should I use for moved label `-n GenericLabel[Linear]` or `-n GenericLabel[BSpline]`? For consistency, I guess we must use `-n GenericLabel[BSpline]`

**Comment by gdevenyi** [comment]
the only option is -n GenericLabel[Linear] which is hard-coded.
