### ISSUE TITLE
How to remove the negative region in -BSpline interpolation

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#828]
I have a template image and a moving image. I want to register the moving image to the template image using `BSpline` interpolation. It worked fine but the problem is that how to remove the negative region in moved image (results by `BSpline`)

I did it by using a mask that results in the threshold of moved image. However, I do not know which is threshold value should we choose. Currently, I am using 0.5 (just by visualize the mask). Could you suggest any way to select the threshold value? or the better way to remove the negative value in `BSpline` interpolation.

This is the source file
[OASIS_template0.nii.gz](https://github.com/ANTsX/ANTs/files/3569753/OASIS_template0.nii.gz)
[OASIS-TRT-20-1_brain.nii.gz](https://github.com/ANTsX/ANTs/files/3569754/OASIS-TRT-20-1_brain.nii.gz)
```
#Step 1
$ANTSPATH/antsRegistrationSyN.sh  -d 3 -f OASIS_template0.nii.gz -m OASIS-TRT-20-1_brain.nii.gz -o OASIS-TRT-20-1_brain_reg.nii.gz -n 16 -t a
#Step 2
$ANTSPATH/antsApplyTransforms -d 3 -i OASIS-TRT-20-1_brain.nii.gz -r OASIS_template0.nii.gz -o OASIS-TRT-20-1_brain_reg.nii.gz -n BSpline -t OASIS-TRT-20-1_brain_reg.nii.gz0GenericAffine.mat
#Step 3
ThresholdImage 3 OASIS-TRT-20-1_brain_reg.nii.gz OASIS-TRT-20-1_brain_reg_mask.nii.gz 0.5 Inf 1 0
#Step 4
ImageMath 3 OASIS-TRT-20-1_brain_reg_remove_negative.nii.gz m OASIS-TRT-20-1_brain_reg_mask.nii.gz OASIS-TRT-20-1_brain_reg.nii.gz
```

**Comment by cookpa** [comment]
If you want to remove negative values:

```
ThresholdImage 3 input.nii.gz mask.nii.gz 0 Inf
ImageMath 3 nonNegative.nii.gz m input.nii.gz mask.nii.gz
```

Negative values are now set to 0.

**Comment by John1231983** [comment]
I have tried to set it 0 but the mask looks not good. Also, it may keep non-zero value in the background of moved image (results in multiply mask and bspline result)
![Untitled](https://user-images.githubusercontent.com/24875971/64180658-291e0d00-ce33-11e9-9572-a8b734bb5059.png)

**Comment by cookpa** [comment]
OK then, if you have a brain mask as as well:

```
ThresholdImage 3 input.nii.gz nonNegativeMask.nii.gz 0 Inf
ImageMath 3 nonNegativeBrainMask.nii.gz m brainMask.nii.gz nonNegativeMask.nii.gz
ImageMath 3 nonNegative.nii.gz m input.nii.gz nonNegativeBrainMask.nii.gz
```

**Comment by John1231983** [comment]
@cookpa : I do not understand in step 2. Why multiple nonnegative brain mask and brainmask. The brain mask is in other location (because it did not register with template).

**Comment by cookpa** [comment]
You can transform the input brain mask to the template space with `antsApplyTransforms` using the same transforms you computed for the moving image. Or you can use the template brain mask.

**Comment by John1231983** [comment]
@cookpa : I found an interesting issue in threshold image. The lower value of threshold should be bigger than zero, instead of setting zero if we want to remove negative value.
```
ThresholdImage 3 input output 0 Inf 1 0
```
The above command will not work for remove negative. Because it will use likes
```
output = input >= 0
```
Instead of, we should add a small value in lower value likes
```
ThresholdImage 3 input output 0.01 Inf 1 0
```

**Comment by gdevenyi** [comment]
The issue appears to be this attempt at cleverness:
https://github.com/ANTsX/ANTs/blob/master/Examples/ThresholdImage.cxx#L86

**Comment by cookpa** [comment]
Aw geez, I vote to remove that.

**Comment by gdevenyi** [comment]
I agree its a bit hacky, but I can see why its there.

The BinaryThresholdImageFilter is inclusive, on both bounds: https://itk.org/Doxygen/html/classitk_1_1BinaryThresholdImageFilter.html which is a bit counterintuitive.

I think I would rather see it use itk's float eps: https://itk.org/Doxygen/html/namespaceitk_1_1Math.html#ae2b830734ef77b9bd69d0d19b91b96c9

**Comment by gdevenyi** [comment]
Looking at this, I'm a bit confused about why this even works :(

SetLowerThreshold should be low + eps and SetUpperThreshold should be high - eps so that the bounds are set "inside"

**Comment by cookpa** [comment]
Or it should just be an inclusive threshold as stated in the usage for `ThresholdImage`.

**Comment by gdevenyi** [comment]
Right. I wonder if BinaryThresholdImageFilter changed at some point since this looks like a workaround to enable "inclusive" thresholds.

**Comment by ntustison** [comment]
I agree with @cookpa --- it should be consistent with the underlying ITK class.  Any workaround to handle problematic cases should be pushed to the ITK folk.

**Comment by ntustison** [comment]
Or simply modify the entries on the command line.

**Comment by John1231983** [comment]
Dear experts,

So, how to threshold the negative value, assume that the threshold value is 0. Should I used 0 +eps as threshold to work with itk

**Comment by ntustison** [comment]
Is there a reason you need to use B-spline interpolation?  This is a well-known issue with B-spline interpolation so if you don't have a good reason to use it, you might want to use something simpler, i.e., linear interpolation.

**Comment by cookpa** [comment]
I'll fix ThresholdImage later but I don't understand why it doesn't work for this use case.

```
  float eps = 1.e-6 * low;
  inputThresholder->SetLowerThreshold( (PixelType) low - eps );
```

Unless I'm missing something, if low is 0, then eps is 1e-6 * 0 and the lower threshold remains 0. So this should still remove negative values even with an inclusive threshold.

But as @ntustison says, maybe it would be better to just use linear interpolation.

**Comment by John1231983** [comment]
@ntustison : The reason is that b-spline keep the contrast between tissue in the brain (or even the distribution between tissue in warped image). I tried linear interpolation but it makes the boundary between tissue so blur.

**Comment by John1231983** [comment]
This is example that shows the blur boundary
# Original image
![Screenshot from 2019-09-03 14-18-07](https://user-images.githubusercontent.com/24875971/64198356-1537d280-ce56-11e9-9345-0fc4f1510a37.png)
# Warped using linear interpolation

![Screenshot from 2019-09-03 14-20-42](https://user-images.githubusercontent.com/24875971/64198354-1537d280-ce56-11e9-8ce9-832d0f81fdea.png)

#Warped using B-spline and remove negative region
![Screenshot from 2019-09-03 14-18-50](https://user-images.githubusercontent.com/24875971/64198355-1537d280-ce56-11e9-8c7a-9ebd5efb9481.png)

**Comment by ntustison** [comment]
Are you sure you're not being biased by the artificial boundaries that are in the original image?

**Comment by John1231983** [comment]
This is another example show clearly different between b-spline and linear (left)
![Screenshot from 2019-09-03 14-30-23](https://user-images.githubusercontent.com/24875971/64199036-714f2680-ce57-11e9-820f-efc2f9f58d75.png)

I feel that the b-spline can keep the original distribution between class than linear interpolation
