### ISSUE TITLE
Maybe I got a fold that is close to half

### ISSUE THREAD

**Issue by white-hy** [ANTsX/ANTs#829]
Hi! Dear Author, Great work.I am using ANTs to complete the registration of lung images.
I used the command to complete the registration of the lung image.
```
antsRegistrationSyNQuick.sh \
-d 3 \
-f case1_T50.nii.gz \
-m case1_T00.nii.gz \
-t s \
-o case1_SynQuick
```
Then I use the command to calculate the Jacobian matrix of the deformation field.
`CreateJacobianDeterminantImage 3 case1_SynQuick1InverseWarp.nii.gz inv_jac.nii.gz 1 0`
Now the Jacobian matrix of the deformation field I got is like this.
![image](https://user-images.githubusercontent.com/33248778/64264584-21aa5100-cf64-11e9-8ab0-f1e0b2869232.png)
I noticed that nearly half of the values are negative. Does this mean that nearly half of the images have been folded?How can I improve so that I get less folding?

**Comment by ntustison** [comment]
It’s because your command line choices indicate calculating the _log_ Jacobian.

**Comment by cookpa** [comment]
You are computing the log of the Jacobian determinant, which will be negative if the determinant is less than 1. 

If you want to verify there are no actual negative values, use

```
CreateJacobianDeterminantImage 3 case1_SynQuick1InverseWarp.nii.gz inv_jac.nii.gz 0 0
```

**Comment by white-hy** [comment]
@ntustison @cookpa Thank you very much, I tried this command.
`CreateJacobianDeterminantImage 3 case1_SynQuick1InverseWarp.nii.gz inv_jac.nii.gz 0 0`
Now I got the right result.
Thanks again.

**Comment by cookpa** [comment]
Also, your interpretation of volume change depends on which warps you use. The inverse warp is what you would use if you want to evaluate the Jacobian in the moving image space.

Normally I compute the Jacobian in the fixed space, using the forward warps. Then the interpretation of the signs follows the table here

https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians#computing-the-jacobian

**Comment by white-hy** [comment]
@cookpa Thank you, you are so sweet.I will read the wiki carefully.
