### ISSUE TITLE
Generate transform based on two sets of landmark files

### ISSUE THREAD

**Issue by aghayoor** [ANTsX/ANTs#830]
Hi,

Is there any tool in ANTs that can be used to generate a transformation based on two sets of landmark files (e.g in csv formats)?
There is `antsLandmarkBasedTransformInitializer`; however, it takes two input images not point sets.

Thank you,
Ali

**Comment by ntustison** [comment]
[Here's](https://github.com/ntustison/Utilities/blob/master/src/CreateBSplineDeformationFieldFromPoints.cxx) some code that I use from my own repository.  However, that functionality is not (yet) in ANTs.

**Comment by hjmjohnson** [comment]
Ali,

BRAINSTools also has code to do what you request.

Hans

**Comment by gdevenyi** [comment]
Minc toolkit can do this

**Comment by aghayoor** [comment]
Thanks everyone!
