### ISSUE TITLE
Any post 2.3.1 release coming?

### ISSUE THREAD

**Issue by yarikoptic** [ANTsX/ANTs#832]
Here I am again inquiring. 
I have tried to build 2.3.1 a bit back on debian sid to get some not so clear to me "why" error:
```
/usr/bin/c++    -g -O2 -fdebug-prefix-map=/build/ants-2.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel -DCXX_HAS_DISABLE_OPTIMIZATION_FLAG   -o CMakeFiles/cmTC_1f1dd.dir/src.cxx.o -c /build/ants-2.3.1/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.cxx
/build/ants-2.3.1/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.cxx:1:1: error: expected unqualified-id before '-' token
 -O0
```
so before digging in or testing current snapshot thought to check may be a new release coming since there was a good amount of development (currently you are at v2.3.1-256-g03d751a4) since then

**Comment by gdevenyi** [comment]
Hi, to provide any help with builds you'll have to provide a bunch more details.

As far as we're aware, there's no issues with gcc 5+ and clang-3.6+. Perhaps you need to check your compiler version.

**Comment by gdevenyi** [comment]
As for releases, I'm working on it when I have time, discussion here: https://github.com/ANTsX/ANTs/issues/802

**Comment by yarikoptic** [comment]
Thanks for the reply. The question is either we should try to troubleshoot build of 2.3.1 (all the versions as of Debian buster and sid are of interest for me, gcc 9 on sid,  and I can provide detailed logs later) or should I wait and aim for the next one and this try to build current master snapshot

**Comment by gdevenyi** [comment]
Full logs are always appreciated, if we don't build in some configurations, we should figure out why.

**Comment by yarikoptic** [comment]
FWIW -- http://neuro.debian.net/_files/_buildlogs/ants/2.3.1/ants_2.3.1-1_amd64.build is the full log from building 2.3.1 on debian sid amd64 those few days back.  For any particular package version just look for "Unpacking".

**Comment by gdevenyi** [comment]
#841 has fixed the build system.

Next up is I need to add to travis automatic deployment of tags. Then ANTs devs will have to decide when to release a tag.

**Comment by satra** [comment]
now if i only knew how @stnava comes up with names!! is really random ant species? or do you have enough data to start wagering.

**Comment by gdevenyi** [comment]
Oh, a release. I guess I didn't get a chance to add my automatic cpacking for release blobs on Traivs :)

**Comment by yarikoptic** [comment]
since the issue/question in the title was "addressed", I will close this issue.
For the original issue in the description: https://github.com/ANTsX/ANTs/issues/898
