### ISSUE TITLE
Understanding multimodality registration method

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#833]
Dear expers,

In the document you said
>mutual information measures how similar the two images look. It uses the histograms of the two images to check the similarity. The value of 1 is a weight used if you do multimodal registration (i.e. using, T1, T2, FLAIR). Here is an example of a multimodal registration call
```
# --metric MI[$t1brain,$template,0.7,32,Regular,0.25] # weight 0.7 on t1
# --metric MI[$t2brain,$T2template,0.3,32,Regular,0.25] # weight 0.3 on t2
# the call format is [fixed, moving, weight, bins, sampling, samplingPercentage]
Our example call has 32 bins, and values are sampled regularly in 25% of the voxels, i.e. one voxel every four is considered.
```

If I have single T1/T2 modality, it is clear that we a single deformation field. In the case of multimodality, how they obtain the single deformation field as shown above? What is the contribution of the weight for constructing the deformation field (0.7 for t1 and 0.3 for t2)?

**Comment by ntustison** [comment]
> (0.7 for t1 and 0.3 for t2)?

Yes.

**Comment by John1231983** [comment]
So, how they generate a single deformation field for both t1 and t2?

**Comment by ntustison** [comment]
https://itk.org/Doxygen/html/classitk_1_1ObjectToObjectMultiMetricv4.html
