### ISSUE TITLE
Build error with the current branch

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTs#834]
Hi,
I am trying to build ANTs on my new laptop through wsl and I am getting the error below. It doesn't appear to be a case of missing libraries or along those lines...

[root@Maga-XPS15 ANTs-build]# make
[ 47%] Built target ITKv5
[ 52%] Performing forcebuild step for 'ANTS'
[ 58%] Performing build step for 'ANTS'
[  0%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o
In file included from /root/ANTs/Examples/antsRegistrationTemplateHeader.h:21:0,
                 from /root/ANTs/Examples/antsRegistrationTemplateHeader.cxx:1:
/root/ANTs-build/ITKv5-install/include/ITK-5.1/itkLabelImageGenericInterpolateImageFunction.h:40:70: error: expected ‘class’ before ‘TInterpolator’
 template <typename TInputImage,template<typename, typename> typename TInterpolator, typename TCoordRep=double >
                                                                      ^
In file included from /root/ANTs-build/ITKv5-install/include/ITK-5.1/itkLabelImageGenericInterpolateImageFunction.h:127:0,
                 from /root/ANTs/Examples/antsRegistrationTemplateHeader.h:21,
                 from /root/ANTs/Examples/antsRegistrationTemplateHeader.cxx:1:
/root/ANTs-build/ITKv5-install/include/ITK-5.1/itkLabelImageGenericInterpolateImageFunction.hxx:27:70: error: expected ‘class’ before ‘TInterpolator’
 template<typename TInputImage, template<typename, typename> typename TInterpolator , typename TCoordRep>
                                                                      ^
/root/ANTs-build/ITKv5-install/include/ITK-5.1/itkLabelImageGenericInterpolateImageFunction.hxx:58:70: error: expected ‘class’ before ‘TInterpolator’

 template<typename TInputImage, template<typename, typename> typename TInterpolator , typename TCoordRep>
                                                                      ^
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o] Error 1
make[4]: *** [Examples/CMakeFiles/antsUtilities.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
make[1]: *** [CMakeFiles/ANTS.dir/all] Error 2
make: *** [all] Error 2
[

**Comment by gdevenyi** [comment]
Please provide full details of exactly how you obtained, configured and built. Including full logs.

**Comment by muratmaga** [comment]
It is on windows linux subsystem running centos 7.6. If it means anything, ANTsR built correctly on the same environment.  

git clone https://github.com/antsx/ants
mkdir ants-build
cd ants-build
ccmake ../ants
(all default options, nothing special)
make 
it fails at that step. I can send you output of a clean build, but will be quite long. Is that what you wanted, or some other log file.

**Comment by cookpa** [comment]
Can you please also tell us your compiler and your CPU? Some problems have been hardware related

Sent from my iPhone

On Sep 7, 2019, at 12:19 PM, muratmaga <notifications@github.com<mailto:notifications@github.com>> wrote:


It is on windows linux subsystem running centos 7.6. If it means anything, ANTsR built correctly on the same environment.

git clone https://github.com/antsx/ants
mkdir ants-build
cd ants-build
ccmake ../ants
(all default options, nothing special)
make
it fails at that step. I can send you output of a clean build, but will be quite long. Is that what you wanted, or some other log file.

**Comment by gdevenyi** [comment]
And complete logs, please

**Comment by muratmaga** [comment]
truncated output from /proc/cpuinfo. I made clean clone and configure and building right now with saving the output to log. Will post once it is done.

processor       : 15
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
stepping        : 13
microcode       : 0xffffffff
cpu MHz         : 2400.000
cache size      : 256 KB
physical id     : 0
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave osxsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt ibrs ibpb stibp ssbd
bogomips        : 4800.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

**Comment by muratmaga** [comment]
Failed at the same place. Log is attached
[build.log](https://github.com/ANTsX/ANTs/files/3587064/build.log)

**Comment by gdevenyi** [comment]
There's the issue, gcc<5 doesn't properly support the new c++ standards that itk and ants use. Please upgrade your compiler

**Comment by muratmaga** [comment]
Thanks moving to the gcc7 fixed it. It think it might be useful to generate warning at the project build time.
Best,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gdevenyi** [comment]
Opened #835 to track. We'll sort it somehow
