### ISSUE TITLE
Fix gcc<5 builds or error out early

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#835]
We're getting regular reports of compile failure due to old gcc, we should fix or error out in cmake early.

**Comment by cookpa** [comment]
On my to-do list for today

**Comment by gdevenyi** [comment]
Poke me and I'll be happy to re-add older compilers to the travis config.

**Comment by cookpa** [comment]
This gives an error if you try to use GCC < 5. 

https://github.com/ANTsX/ANTs/tree/minGCC

But I wonder if we can fix it, I don't think GCC > 5 is officially an ITK requirement yet.

I'm going to try to build ITK independently on an older GCC.

**Comment by cookpa** [comment]
Actually looking at the older failure logs with GCC 4, the ITK build completes normally, but then ANTs fails when linking against it.

**Comment by cookpa** [comment]
I get the same error if I build ITK offline and use it as system ITK for ANTs. I don't have the time or expertise to get more into this, so I suggest we will have to start requiring GCC 5
