### ISSUE TITLE
antsApplyTransformsToPoints doesn't work sometimes.

### ISSUE THREAD

**Issue by white-hy** [ANTsX/ANTs#836]
Hi,Dear Author.Great works! I am using ANTs to complete the transformation of the landmark image of the lung image.
When I execute the following command. ANTs can complete the transformation of landmarks.At this time, the size of `case1_SynQuick1Warp.nii.gz` is `256*256*94*3`.
```
antsApplyTransformsToPoints \
-d 3 \
-i /landmarks/00Case1_300_T50_xyz.csv \
-o/landmarks/00Case1_300_T50_xyz_moved.csv \
-t /transfrom/case1_SynQuick1Warp.nii.gz \
-t /transfrom/case1_SynQuick0GenericAffine.mat
```
By looking at `00Case1_300_T50_resample_moved.csv`, it seems that just using `case1_resample_SynQuick0GenericAffine.mat` to complete the affine transformation, without using `case1_resample_SynQuick1Warp.nii.gz` to complete the next transformation. At this time, the size of `/case1_resample_SynQuick1Warp.nii.gz` is `236*162*213*3`
```
antsApplyTransformsToPoints \
-d 3 \
-i /landmarks/00Case1_300_T50_resample.csv \
-o/landmarks/00Case1_300_T50_resample_moved.csv \
-t /transfrom/case1_resample_SynQuick1Warp.nii.gz \
-t /transfrom/case1_resample_SynQuick0GenericAffine.mat
```
I don't understand why this happens. Can you give me some advice?

**Comment by ntustison** [comment]
Why would your landmark files be different?

**Comment by white-hy** [comment]
@ntustison Yes, my landmark file is different. Because my image was not resampled for the first time, and my image was resampled the second time. Two landmark files correspond to my two images.

**Comment by ntustison** [comment]
The landmark files should be specified in physical coordinates, not voxel coordinates, so they should be similar, if not the same even with resampling.

**Comment by white-hy** [comment]
@ntustison Hi!

My two landmarks files are both in the voxel coordinate system.

I want to clarify some concepts carefully. `SynQuick1Warp.nii.gz` is a densely deformed field that corresponds to the displacement of each pixel in the `X, Y, and Z` directions. If the landmarks are in the physical coordinate system, how should the transformation field work to convert the landmarks?

I have some doubts about whether `antsApplyTransformsToPoints `will not work when `SynQuick1Warp.nii.gz` is large.

**Comment by ntustison** [comment]
The warp field is also specified in terms of physical coordinates.

> I have some doubts about whether antsApplyTransformsToPoints will not work when SynQuick1Warp.nii.gz is large.

Any limitations are not due to algorithmic issues but rather hardware capabilities.

**Comment by white-hy** [comment]
@ntustison Thank you very much for your help, I will do what you said, transform all lanmark into physical coordinates.

**Comment by ntustison** [comment]
Also, you can use this [example](https://github.com/stnava/chicken) for a reference of proper usage.

**Comment by ai-llf** [comment]
@white-hy  how to transform image voxel coordinates into physical coordinates?
