### ISSUE TITLE
antsRegistration throwing file NULL does not exist

### ISSUE THREAD

**Issue by tashrifbillah** [ANTsX/ANTs#847]
**Describe the bug**

`antsRegistrationSyNQuick.sh` throws `file NULL does not exist` although`Fixed mask` exists. Here is a snippet from the `STDOUT`:

```
The composite transform comprises the following transforms (in order):
  1. Center of mass alignment using fixed image: /data/template/Mean_TAR_FA_b2000.nii.gz and 
moving image: /data/Target/harmonized_dwi_b2000_FA.nii.gz (type = Euler3DTransform)
=============================================================================
  Reading mask(s).
    Registration stage 0
      Fixed mask = /data/template/TAR_Mask.nii.gz
 file NULL does not exist .
      No moving mask
  number of levels = 4
  number of levels = 4
  number of levels = 4
  fixed image: /data/template/Mean_TAR_FA_b2000.nii.gz


```

**To Reproduce**
This is the command I used:
```
antsRegistrationSyNQuick.sh -d 3 -f /data/template/Mean_TAR_FA_b2000.nii.gz -x /data/template/TAR_Mask.nii.gz -m /data/Target/harmonized_dwi_b2000_FA.nii.gz -o /data/Target/harmonized_dwi_b2000_FA
```

**Additional Information**
> antsRegistration --version
```
ANTs Version: 2.2.0.dev148-gca322
Compiled: Jun 26 2019 09:01:49
```

Any idea about the source of error?

**Comment by ntustison** [comment]
Can you post the data?

**Comment by cookpa** [comment]
I think this is normal behavior, saying that the moving mask doesn't exist. It should still use the fixed mask.

**Comment by gdevenyi** [comment]
This is as expected, antsRegistration handles "no mask" by providing a non-existent filename and failing to open it:
https://github.com/ANTsX/ANTs/blob/master/Scripts/antsRegistrationSyN.sh#L384

**Comment by tashrifbillah** [comment]
> This is as expected, antsRegistration handles "no mask" by providing a non-existent filename and failing to open it:

May be this is something you want to suppress. I have a way of separating STDOUT and STDERR. In STDERR, I see only:

> file NULL does not exist

I had to do a lot of debugging to find out the source of the message. 

Feel free to close the issue as you see fit.

**Comment by kgodf** [comment]
What was the solution to this problem? I am having the same issue but both the fixed and moving mask exist

**Comment by tashrifbillah** [comment]
@kgodf , my report was not an issue, rather just a message, as folks pointed out.
