### ISSUE TITLE
use of antsLandmarkBasedTransformInitializer

### ISSUE THREAD

**Issue by andreaurru** [ANTsX/ANTs#851]
Hi, how do I use the antsLandmarkBasedTransformInitializer? How do I pass the landmarks coordinates in particular? Maybe it's a dumb question but in the guide I see

Usage: antsLandmarkBasedTransformInitializer dimension fixedImage
movingImage transformType outputTransform
[meshSize[0]xmeshSize[1]x...=1x1x1] [numberOfLevels=4] [order=3]
[enforceStationaryBoundaries=1] [landmarkWeights]

where do I have to specify the actual landmraks I want to match?

**Comment by ntustison** [comment]
Much of the work we do with landmarks involves "painting" blobs on images using ITK-SNAP so usage of this particular program is tailored accordingly.  The input fixed and moving landmark sets are specified as label images where the segmentation label designates which blobs correspond across images. Note that the centroids for each segmentation label are calculated and those coordinates are used as the landmarks.

**Comment by aghayoor** [comment]
You can also use [BRAINSLandmarkInitializer](https://github.com/BRAINSia/BRAINSTools/blob/master/BRAINSLandmarkInitializer/BRAINSLandmarkInitializer.cxx) from the BRAINSTools if you have two sets of landmark points (compatible with 3DSlicer fcsv file format).
