### ISSUE TITLE
Segment fault with aMTC2.sh

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTs#852]
**Describe the bug**
antsMultivariateTemplateConstructions2.sh is giving a segmentation fault.

**To Reproduce**
antsMultivariateTemplateConstruction2.sh -d 3 -a 0 -c 0 -q 1000x1000x500x50 -n 0 *gz -o rat_

--------------------------------------------------------------------------------------
 Creating template antsBTPtemplate0.nii.gz from a population average image from the inputs.
   UWBM_13966__rec_Segment_1.nii.gz UWBM-13967__rec_Segment_1.nii.gz UWBM-39631__rec_Segment_1.nii.gz UWBM-51126__rec_Segment_1.nii.gz UWBM_61915__rec_Segment_1.nii.gz UWBM-61921__rec_Segment_1.nii.gz uwbm_61933__rec_Segment_1.nii.gz UWBM-7010__rec_Segment_1.nii.gz UWBM-72371__rec_Segment_1.nii.gz UWBM-72432__rec_Segment_1.nii.gz UWBM-72433__rec_Segment_1.nii.gz UWBM-72434__rec_Segment_1.nii.gz UWBM-77333__rec_Segment_1.nii.gz UWBM_9190__rec_Segment_1.nii.gz UWBM-9213__rec_Segment_1.nii.gz -o rat_
--------------------------------------------------------------------------------------
/home/maga/ants-build/bin/antsMultivariateTemplateConstruction2.sh: line 272: 79341 Segmentation fault      (core dumped) ${ANTSPATH}/AverageImages $dim $output 0 ${images[*]}
 file antsBTPtemplate0.nii.gz does not exist . 
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /home/maga/ants-build/ITKv5/Modules/Core/Common/src/itkProcessObject.cxx:1404:
itk::ERROR: LaplacianSharpeningImageFilter(0x35f3580): Input Primary is required but not set.
/home/maga/ants-build/bin/antsMultivariateTemplateConstruction2.sh: line 272: 79344 Aborted                 (core dumped) ${ANTSPATH}/ImageMath $dim $output Sharpen $output
Your initial template : antsBTPtemplate0.nii.gz[0 ] was not created.  This indicates trouble!  You may want to check correctness of your input parameters. exiting.

##AverageImages work fine from the command line. 
-bash-4.2$ AverageImages 3 test.nii.gz 1 *gz
 bigimage 4 maxSize [258, 241, 473]
 Setting physcal space of output average image based on largest image 
 Averaging 15 images with dim = 3 vector components 1
 reading UWBM_13966__rec_Segment_1.nii.gz
 reading UWBM-13967__rec_Segment_1.nii.gz
 reading UWBM-39631__rec_Segment_1.nii.gz
 reading UWBM-51126__rec_Segment_1.nii.gz
 reading UWBM_61915__rec_Segment_1.nii.gz
 reading UWBM-61921__rec_Segment_1.nii.gz
 reading uwbm_61933__rec_Segment_1.nii.gz
 reading UWBM-7010__rec_Segment_1.nii.gz
 reading UWBM-72371__rec_Segment_1.nii.gz
 reading UWBM-72432__rec_Segment_1.nii.gz
 reading UWBM-72433__rec_Segment_1.nii.gz
 reading UWBM-72434__rec_Segment_1.nii.gz
 reading UWBM-77333__rec_Segment_1.nii.gz
 reading UWBM_9190__rec_Segment_1.nii.gz
 reading UWBM-9213__rec_Segment_1.nii.gz

**Screenshots**

OS=Centos 7.6

**Comment by ntustison** [comment]
Your ordering is incorrect.  The wild card specification of your images goes at the end.  Also, I recommend using full path names.

**Comment by muratmaga** [comment]
Arggh. Silly mistake. Apologies.
