### ISSUE TITLE
clang-9 -Weverything output

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#853]
Not all these are relevant, but they might be

[buildlog.log.gz](https://github.com/ANTsX/ANTs/files/3639170/buildlog.log.gz)

**Comment by ntustison** [comment]
Thanks @gdevenyi .  I actually enjoy cleaning up stuff like this but I can't start working on it as I'm    heading on vacation next week.  If you remember, please bump this thread sometime the week of September 30 and I'll start going through the list.

**Comment by gdevenyi** [comment]
Cheers!

**Comment by gdevenyi** [comment]
Following up @ntustison, hope you enjoyed your vacation

**Comment by gdevenyi** [comment]
Updated post https://github.com/ANTsX/ANTs/pull/869
[stderr.log](https://github.com/ANTsX/ANTs/files/3734821/stderr.log)

**Comment by gdevenyi** [comment]
Updated post #886 
[stderr.log](https://github.com/ANTsX/ANTs/files/3745162/stderr.log)

**Comment by gdevenyi** [comment]
Updated post round 4:
[stderr.log](https://github.com/ANTsX/ANTs/files/3772619/stderr.log)

**Comment by gdevenyi** [comment]
Post round #904 

Let me know if you want any warnings disabled, this is a pretty massive logfile.
[stderr.log](https://github.com/ANTsX/ANTs/files/3800606/stderr.log)

**Comment by gdevenyi** [comment]
Post #907 
[stderr.log](https://github.com/ANTsX/ANTs/files/3805926/stderr.log)

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/pull/910

**Comment by gdevenyi** [comment]
Post #910 
[stderr.log](https://github.com/ANTsX/ANTs/files/3847693/stderr.log)

**Comment by gdevenyi** [comment]
Way out of date.
