### ISSUE TITLE
gcc-9 enhanced warnings

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#854]
One more for @ntustison when he's bored.

Done with:
```
-Wno-variadic-macros -W -Wpedantic -Wextra -Wall -Wcast-align -Wcast-qual -Wstrict-aliasing=2 -Wframe-larger-than=32768 -Wno-strict-overflow -Wsync-nand -Wtrampolines -Wsign-compare -Wfloat-equal -Wmissing-braces -Winit-self -Wlogical-op -Wwrite-strings -Waddress -Warray-bounds -Wchar-subscripts -Wenum-compare -Wempty-body -Wmain -Waggressive-loop-optimizations -Wnonnull -Wparentheses -Wreturn-type -Wsequence-point -Wuninitialized -Wvolatile-register-var -Wignored-qualifiers -Wno-maybe-uninitialized -Wno-unused-function -Wodr -Wformat-signedness -Wsuggest-final-types -Wsuggest-final-methods -Wno-ignored-attributes -Wno-missing-field-initializers -Wshift-overflow=2 -Wduplicated-cond -Wduplicated-branches -Wrestrict -Wdouble-promotion -Wformat=2

```

[buildlog.log.gz](https://github.com/ANTsX/ANTs/files/3639292/buildlog.log.gz)

**Comment by gdevenyi** [comment]
Following up @ntustison, hope you enjoyed your vacation

**Comment by ntustison** [comment]
(Round 1)[https://github.com/ANTsX/ANTs/pull/869]

**Comment by gdevenyi** [comment]
Updated, I think there might be a bunch of new ones because I enabled the VTK stuff this time round.

[stderr.log](https://github.com/ANTsX/ANTs/files/3734508/stderr.log)

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/pull/886

**Comment by gdevenyi** [comment]
Updated post #886 
[stderr.log](https://github.com/ANTsX/ANTs/files/3745312/stderr.log)

**Comment by gdevenyi** [comment]
Happy to say that this work has paid off, I'm pretty sure it fixed <gcc5 build failures :)

**Comment by cookpa** [comment]
This will re-enable compilation on CENTOS6 with the older devtoolset-3. Thanks guys.

**Comment by ntustison** [comment]
Hi all, [here's another round](https://github.com/ANTsX/ANTs/pull/892).  Not all issues are resolved but I was sidetracked by some other work so I thought I'd go ahead and push what I had done.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/pull/893

**Comment by gdevenyi** [comment]
Post round 4, almost there!
[stderr.log](https://github.com/ANTsX/ANTs/files/3772538/stderr.log)

**Comment by ntustison** [comment]
Thanks @gdevenyi .  Will get to it soon.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/pull/897

**Comment by gdevenyi** [comment]
Post round 5
[stderr.log](https://github.com/ANTsX/ANTs/files/3776185/stderr.log)

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/pull/900

**Comment by gdevenyi** [comment]
@ntustison you are a monster.

Post Round 6:
[stderr2.log](https://github.com/ANTsX/ANTs/files/3781260/stderr2.log)

**Comment by ntustison** [comment]
Thanks @gdevenyi — I think we’re getting pretty close.

**Comment by gdevenyi** [comment]
sure, can do

**Comment by gdevenyi** [comment]
Post #902 
[stderr.log](https://github.com/ANTsX/ANTs/files/3790878/stderr.log)

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/pull/904

**Comment by gdevenyi** [comment]
Post #904
[stderr2.log](https://github.com/ANTsX/ANTs/files/3800590/stderr2.log)

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/pull/907

Just a couple changes trying to get rid of the last of the warnings.  I'm pretty sure I zapped one but I'm still a bit unclear on the other warning but we'll see what these changes yield.  I'll probably move to the clang warnings after this merge.

**Comment by gdevenyi** [comment]
Post #907 
[stderr.log](https://github.com/ANTsX/ANTs/files/3805863/stderr.log)

**Comment by ntustison** [comment]
Thanks @gdevenyi .  So this is good because I was able to fix the one warning with this pull request.  However, the last one is difficult (all the current warnings stem from a single issue).  The problem is that the compiler warnings want me to designate ``WarpImageMultiTransformFilter`` as _final_ but since there exists a derived class ``DisplacementFieldFromMultiTransformFilter``, I can't do that without the compiler throwing an error.  

Any ideas @hjmjohnson , @cookpa, @stnava ?

**Comment by gdevenyi** [comment]
Way out of date. I'll do some with the latest versions at some point.
