### ISSUE TITLE
Pediatric Template Integration

### ISSUE THREAD

**Issue by cjc17** [ANTsX/ANTs#856]
Hello 
I wanted to explore the capabilities of ANTs toolbox for segmentation and seem to be having some difficulty setting up a template based approach.  I saw that the NKI 10 and under template w/priors is available and was curious if anyone had any insight as how to incorporate that template into the segmentation workflow.  I have reviewed the documentation, but some additional clarification/guidance would be helpful.  Any assistance is greatly appreciated.  Thank so much.

**Comment by ntustison** [comment]
Did you try running the relevant 2-D [example](https://github.com/ntustison/antsAtroposN4Example)?
