### ISSUE TITLE
I want to perform affine registration. Which command should I run?

### ISSUE THREAD

**Issue by white-hy** [ANTsX/ANTs#859]
Hi, Dear Author. Great work！My image pair is three-dimensional. I am using ANTs to complete affine registration. Which command should I run?

**Comment by cookpa** [comment]
Please see `antsRegistrationSyNQuick.sh` for an example. It will print a call to `antsRegistration`, which you can save and modify as needed.

**Comment by white-hy** [comment]
@cookpa Thank you for your help！
