### ISSUE TITLE
Generate local correlation image

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#860]
## Preface

I'm facing this issue [here](https://neurostars.org/t/two-sample-t-test-for-data-sets-with-different-ranges/). I would like to compare image sets from two different modalities, with rather different (amplitude, as well as sign) ranges. Now, I've been able to actually do this by normalizing the data in both samples, but I am thinking maybe another solution would be better (or at least a good supplement).

Since the data is both from different modalities and subjects, I can't test correlation per-voxel (no one voxel in any sample has a specific pair). But I am thinking of comparing the correlation in image segments of the group averages.

## Explanation
Basically I would like to break the image space up into smaller regions, which cover it in its entirety. Then I would like to calculate a similarity metric (I am thinking something like GC would be best) within each region for two input images. I think this should be doable on 3x3 voxel segments. 27 samples is enough for a Pearson's r, and a 3-fold reduction of resolution seems like an ok price to pay for getting a correlation map for two datasets which are otherwise unpaired.

## Implementation
I know I could do this in numpy (if I use a simple similarity metric such as Pearson's r), I'm just curious if ANTs already has such a feature, which would also let me look at more advanced meterics (such as MI).

**Comment by ntustison** [comment]
We don't really have something like that in ANTs proper but you can do something like that in ANTsPy or ANTsR.  Is that a possibility for your workflow?

**Comment by TheChymera** [comment]
I'm already pretty swamped in software management in general and ANTs management in particular. Is ANTsPy just a wrapper for ANTs? I'm asking since if it just depends on ANTs and is otherwise “just a Python package”, I might be able to give it a try.

**Comment by ntustison** [comment]
They’re wrappers in the sense that they wrap core ANTs functionality in the respective languages.  However, they allow for increased capabilities given the additional packages associated with R and python.  These facilitate such core analysis steps as visualization and statistics.  Concrete examples include our deep learning packages ANTsPyNet and ANTsRNet.
