### ISSUE TITLE
antsApplyTransforms command not found!

### ISSUE THREAD

**Issue by belatulipo** [ANTsX/ANTs#865]
Hi
I used antMultivariateTemplateConstruction2 to build a template of a number of T1 images. Now I would like to use the .mat transform files to transfer a few manual ROI masks to the template space. I realize I should use antsApplyTransforms. However when I tried that, I encountered "command not found" error. 
I can't find an antsApplyTransforms.sh file in the scripts; only an antsApplyTransforms.cxx in the examples and antsApplyTransforms.h. I am not familiar with these formats. Should I do something before running this command?
I apologize in advance if the question seems trivial. Anyway, I would really appreciate some help here.

**Comment by ntustison** [comment]
Hi @belatulipo ,

If you used ``antMultivariateTemplateConstruction2.sh``, then you should have that program available in the build folder (which is also where the scripts should be).  How did you perform your installation?

**Comment by cookpa** [comment]
I just checked a recent build and `antsApplyTransforms` is in the bin directory with `antsRegistration` and the other binaries. 

It's possible something went wrong with the install at some point but we need to know how the software was installed to help further. Also, the version information that you get with `antsRegistration --version`.

**Comment by cookpa** [comment]
Thinking this might be a path issue, because the template script will use `ANTSPATH`. So possibly fixable with

```
export PATH=${ANTSPATH}:$PATH
```
