### ISSUE TITLE
ANTs on Mac OS Catalina

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#870]
Just a heads up, the default shell on Mac OS Catalina has changed from bash to zsh.

This link has instructions on how to change back to bash:

  https://www.cyberciti.biz/faq/change-default-shell-to-bash-on-macos-catalina/

Bash is still installed so ANTs scripts should continue to work. If you are reading this because ANTs is behaving strangely, please verify what shell you are using (see link above). 

Feel free to report any problems here, but the immediate workaround is to run your commands in a bash shell.

CC: @stnava @ntustison @gdevenyi

**Comment by ntustison** [comment]
@cookpa Thanks for the heads up.
