### ISSUE TITLE
Question: Atropos partial volume segmentation

### ISSUE THREAD

**Issue by rockandsalt** [ANTsX/ANTs#874]
Is there a paper on how Atropos handles partial volumes?

**Comment by ntustison** [comment]
Not really.  I'm guessing partial volume issues would only surface if one needed to use tissue priors and that's not really discussed in the original paper but is left to the user to decide how best to handle that situation.

**Comment by rockandsalt** [comment]
I think it works. I need to explain how the algorithm works for a report.
