### ISSUE TITLE
No command "N4BiasFieldCorrection" found on host computer. 

### ISSUE THREAD

**Issue by ninjakx** [ANTsX/ANTs#876]
I installed nipype using pip install and went through [it](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#copy-scripts) to install ants. I followed the whole procedure but still, I am getting the same error.
And also `which antsRegistration` returns me nothing. I went through all the previous related issue but couldn't find a solution for it.

**Comment by ntustison** [comment]
Did you follow the steps [here](http://miykael.github.io/nipype-beginner-s-guide/installation.html#ants), specifically the part about exporting the system path variables (i.e., step 5)?

**Comment by ninjakx** [comment]
Yes I did export the path and added it to bashrc

**Comment by ntustison** [comment]
Okay, there was a recent change in how ANTs is compiled but I don't know if nipype is actually using these recent changes.  Note that what nipype does with ANTs is beyond our awareness since they have a separate development group so you might ultimately have to ask over.  Do a ``find`` and tell me what the full path is for ``antsRegistration``.  If the new changes are being used, which is what I suspect, then your path should be something like ``${ANTs-build}/Examples/antsRegistration``.

**Comment by TheChymera** [comment]
@ninjakx My understanding of the ANTs build system is only cursory, but I experienced a similar lack of installed binaries by not running:

`
make install
`

inside the appropriate `ANTS-build` directory (more details [here](https://github.com/ANTsX/ANTs/issues/857), and [here](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#install-step)). ANTs uses CMake to get built *and* installed, and I am not sure `pip` can manage all of that correctly. If you are by any chance using Gentoo Linux, I am just finishing up an ebuild (Gentoo package atom) which can manage the dependencies, build ANTs locally, and install all the required files in the appropriate system-wide directories.

**Comment by ninjakx** [comment]
My export Path look like this :
```
export ANTSPATH=/opt/ants/bin/
export PATH=${ANTSPATH}:$PATH
```
@ntustison :
**antsRegistrationSyN.sh** -> /home/kriti/Desktop/ANTs/Scripts/antsRegistrationSyN.sh
**antsRegistration.h** -> /home/kriti/Desktop/ANTs/Examples/include/antsRegistration.h
**antsRegistration.cxx** -> /home/kriti/Desktop/ANTs/Examples/antsRegistration.cxx

**Comment by ntustison** [comment]
Without knowing anything about nipype (and echoing what @TheChymera said), my guess is that you didn't actually install ANTs.  If @TheChymera 's suggestion doesn't work, I'd ask the nipype folk.

**Comment by ninjakx** [comment]
@ntustison  Can you tell me what would be the files in the opt/ants/bin
Strange I could not see any ants folder inside opt though I follow the steps.
![Screenshot from 2019-10-13 09-17-20](https://user-images.githubusercontent.com/29797787/66710650-872b0200-ed9a-11e9-8698-aea0e68c937e.png)

**Comment by ninjakx** [comment]
There was some issue with the root directory. By changing the directory it's working now.

**Comment by hafedh-hichri** [comment]
i just followed step 5 in here and it worked for me http://miykael.github.io/nipype-beginner-s-guide/installation.html#ants 

1. open .bashrc file 
2. add these lines 
`export PATH=/usr/local/antsbin/bin:$PATH
export ANTSPATH=/usr/local/antsbin/bin/`

where `/usr/local/antsbin/bin`  is `path where you installed ANTs that you specified during the builing process`
