### ISSUE TITLE
Library Linking for VTK and ITK

### ISSUE THREAD

**Issue by TheChymera** [ANTsX/ANTs#879]
Are ITK and VTK linked statically or dynamically? I am asking because I wasn't able to determine if ANTs executables would still run if VTK and/or ITK were deleted.

**Comment by gdevenyi** [comment]
BUILD_SHARED_LIBRARIES determines this. The default build without the Gentoo overrides is static.

**Comment by TheChymera** [comment]
@gdevenyi thank you
