### ISSUE TITLE
About 'SetOrigin' command

### ISSUE THREAD

**Issue by wangken1994** [ANTsX/ANTs#880]
Hi, Experts!

I used **dtifit** (FSL, Oxford, UK) and **fsl_to_dtitk** (DTI-TK) to calculate the diffusion tensor image. The output files are shown as follow:
```
*_dti_dtitk.nii.gz (Estimated DTI file)
*_dti_FA.nii.gz (Derived FA file)
etc.
```
I found that the origin coordinate of DTI (0, 0, 0) and the derived FA (68.823, -69.857, -39.004) were not same.

 Therefore, I used the `SetOrigin` to correct the FA origin to (0 0 0), see:

`SetOrigin 3 *_dti_FA.nii.gz *_dti_FA_cor.nii.gz 0 0 0`

When I used 3D Slicer to check the corrected FA file, I found it still did't cover the DTI file, even though the origin coordinate between them were same after correction.

I upload the files as attachments. Any help will be appreciated!
[Data_dti_dtitk.nii.gz](https://github.com/ANTsX/ANTs/files/3722740/Data_dti_dtitk.nii.gz)
[Data_dti_FA.nii.gz](https://github.com/ANTsX/ANTs/files/3722741/Data_dti_FA.nii.gz)
[Data_dti_FA_cor.nii.gz](https://github.com/ANTsX/ANTs/files/3722742/Data_dti_FA_cor.nii.gz)

**Comment by ntustison** [comment]
This is a potential problem anytime you mix packages.  Your particular issue might be related to the [sform/qform](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F) issue.

**Comment by cookpa** [comment]
You're mixing four different software packages here, I recommend keeping everything in one environment as far as possible.

When you import into DTI-TK the data is forced to be LPI with zero origin. You can use the `TVGlyphView` to check if the tensors are correct for DTI-TK. You can then compute FA in the DTI-TK space with `TVtool`, which will produce an FA map with the same header.

**Comment by wangken1994** [comment]
OK, I will try it. Thanks so much! @ntustison @cookpa
