### ISSUE TITLE
Issue template for build problems

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#883]
@gdevenyi I made a start on an issue template to help users give enough information to diagnose problems. Please let me know if I've missed anything that would be helpful.

https://github.com/ANTsX/ANTs/blob/master/.github/ISSUE_TEMPLATE/build_errors.md

**Comment by gdevenyi** [comment]
Looks great! :)

**Comment by cookpa** [comment]
Cool. I just re-built ANTs on OS X and I don't see build.log, is that a Linux thing?

**Comment by gdevenyi** [comment]
Nope.

```
make 2>&1 | tee build.log
```

**Comment by gdevenyi** [comment]
I guess update the build instructions :)

**Comment by cookpa** [comment]
OK will do
