### ISSUE TITLE
ANTs build does not honour USE_SYSTEM_VTK

### ISSUE THREAD

**Issue by Littlehhh** [ANTsX/ANTs#885]
**When did the error occur?**
- [ ] CMake configuration (cmake / ccmake)
- [x] Compilation (make)
- [ ] Installation (make install)

**Build environment**
 - OS: [e.g. iOS] Ubuntu 18.04
    - ANTs version  git clone && git pull origin master
    - cmake version 3.10.2
    - gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
    - g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
 
**ANTs version**
`git log`
commit hash
commit 39ce5833217c435d55a3cb4f0c7300d86bbf3b24 (HEAD -> master, origin/master, origin/HEAD)

**Build configuration and logs**

Please attach the following files (relative to your build directory)

  - build.log (the terminal output from make)
[build.log](https://github.com/ANTsX/ANTs/files/3737442/build.log)
  - CMakeCache.txt
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/3737446/CMakeCache.txt)
  - CMakeFiles/CMakeError.log
[CMakeError.log](https://github.com/ANTsX/ANTs/files/3737447/CMakeError.log)
  - CMakeFiles/CMakeOutput.log
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/3737450/CMakeOutput.log)

**Comment by gdevenyi** [comment]
Thanks for the report. It looks like you have a newer system VTK installed and the ANTs build system is trying to use it despite also having ``USE_SYSTEM_VTK=OFF``. Your version is "too new" and we fail building against it.

So, possible fixes
1) Remove your system VTK temporarily, build ANTs, then install it again
2) Fix ANTs to build with newer VTKs and submit a PR
3) Disable USE_VTK on your build
4) Fix the build system to properly use the inbuilt VTK when USE_SYSTEM_VTK=OFF <-- I can look into this one.

@ntustison @cookpa could you please rename this "ANTs build doesn't honour USE_SYSTEM_VTK properly"

**Comment by cookpa** [comment]
USE_SYSTEM_ITK is ON, is it possible that ITK links to the newer VTK?

**Comment by Littlehhh** [comment]
> Thanks for the report. It looks like you have a newer system VTK installed and the ANTs build system is trying to use it despite also having `USE_SYSTEM_VTK=OFF`. Your version is "too new" and we fail building against it.
> 
> So, possible fixes
> 
> 1. Remove your system VTK temporarily, build ANTs, then install it again
> 2. Fix ANTs to build with newer VTKs and submit a PR
> 3. Disable USE_VTK on your build
> 4. Fix the build system to properly use the inbuilt VTK when USE_SYSTEM_VTK=OFF <-- I can look into this one.
> 
> @ntustison @cookpa could you please rename this "ANTs build doesn't honour USE_SYSTEM_VTK properly"

Thanks for your reply.

I have built ANTs without VTK successfully.  So I try to build it with VTK.  
I will try your first solution. And hope the bug be fixed.
Thanks again.

**Comment by Littlehhh** [comment]
> USE_SYSTEM_ITK is ON, is it possible that ITK links to the newer VTK?
Thanks for your reply.
What's means ITK links to the newer VTK?
I have built ITK use system VTK and open the module `ITKVTKglue`

**Comment by cookpa** [comment]
If you build ITK with system VTK, and that VTK is incompatible with ANTs, you might get problems.

A full superbuild with system VTK and system ITK both OFF would get you the correct version of all the packages

**Comment by Littlehhh** [comment]
> If you build ITK with system VTK, and that VTK is incompatible with ANTs, you might get problems.
> 
> A full superbuild with system VTK and system ITK both OFF would get you the correct version of all the packages

Thanks. 
You are right.  But I  try to custom some new things. And I get the ANTs superbuild cmake  option for building system VTK and ITK.  So I can build ANTs with system ITK. But build with system VTK not work and then I try use system ITK and superbuild VTK, It doesn't work too.

**Comment by Littlehhh** [comment]
> Thanks for the report. It looks like you have a newer system VTK installed and the ANTs build system is trying to use it despite also having `USE_SYSTEM_VTK=OFF`. Your version is "too new" and we fail building against it.
> 
> So, possible fixes
> 
> 1. Remove your system VTK temporarily, build ANTs, then install it again
> 2. Fix ANTs to build with newer VTKs and submit a PR
> 3. Disable USE_VTK on your build
> 4. Fix the build system to properly use the inbuilt VTK when USE_SYSTEM_VTK=OFF <-- I can look into this one.
> 
> @ntustison @cookpa could you please rename this "ANTs build doesn't honour USE_SYSTEM_VTK properly"

And maybe the ANTs build system is trying to use system ITK despite having USE_SYSTEM_ITK=OFF.

**Comment by cookpa** [comment]
This is what I think happened. You first built ITK with Module_ITKVtkGlue=ON, and VTK_DIR pointing to your system VTK 8.9.0. You then configured ANTs with USE_SYSTEM_ITK=ON and USE_SYSTEM_VTK=OFF. 

This tells ANTs to build VTK but use the system ITK. Only ANTs is going to want to build VTK v8.2.0, but the system ITK is already built with VTK v8.9.0.

I think this is a problem because ANTs has pretty specific version requirements for both ITK and VTK. If you do the superbuild in a clean environment, it will use ITK (commit 39f1ba9b9540a5daa38ddb87d2c091d4db1fb45d) and VTK (release v8.2.0).

**Comment by gdevenyi** [comment]
Good catch @cookpa.

@Littlehhh Please completely delete your build directly and redo the cmake configuration from scratch. If you still have a build problem, share those files and logs.

**Comment by cookpa** [comment]
I'm going to close this as I don't think it's an actual bug in the ANTs compilation, but feel free to comment further or re-open as needed.
