### ISSUE TITLE
antsCorticalThickness image calculation

### ISSUE THREAD

**Issue by satra** [ANTsX/ANTs#887]
in these lines:

https://github.com/ANTsX/ANTs/blob/master/Scripts/antsCorticalThickness.sh#L1322

is ImageMath simply counting / adding the absolute values of all voxels? So the outputs of B/G/Vol are in voxel counts rather than mm^3.

just wanted to verify i was reading that correctly.

**Comment by ntustison** [comment]
Correct.

**Comment by satra** [comment]
thank you.

**Comment by satra** [comment]
@cookpa - thank you. 

does that mean what it output is going to be dependent on which version of antscorticalthickness produced the output file? because it looks like the output changed but the keys did not.

also are there similar plans for LabelGeometry then which computes volumeinvoxels?

**Comment by ntustison** [comment]
> also are there similar plans for LabelGeometry then which computes volumeinvoxels?

No, I added this and I probably wouldn't change it.  It's very clear that the volume is given in voxels and it's an easy translation to mm^3.

**Comment by cookpa** [comment]
Yes, before March 2017 it was returning voxels. The ImageMath command outputs "total" (the raw sum) and "total-volume" (in mm^3), which suggested to me that when reporting a "Vol", one should output mm^3.

https://github.com/ANTsX/ANTs/blob/master/Examples/ImageMath_Templates.hxx#L5494

`LabelGeometryMeasures` does a completely different calculation and states its units as voxels, so I don't think we will change that.
