### ISSUE TITLE
labelgeometry output

### ISSUE THREAD

**Issue by satra** [ANTsX/ANTs#888]
in the output of labelgeometry are the values of all the outputs in mm (except for volume)?

```
Label 4.0
VolumeInVoxels 11072.0
SurfaceAreaInMillimetersSquared 4652.15857293133
Eccentricity 0.9856637322940179
Elongation 5.92692089080811
Orientation 1.85512914835733
Centroid_x 102.27059248554899
Centroid_y 106.454299132948
Centroid_z 155.25397398843901
AxesLength_x 15.850243568420401
AxesLength_y 31.643480300903303
AxesLength_z 93.9431381225586
BoundingBoxLower_x 88.0
BoundingBoxUpper_x 120.0
BoundingBoxLower_y 50.0
BoundingBoxUpper_y 156.0
BoundingBoxLower_z 132.0
BoundingBoxUpper_z 170.0
IntegratedIntensity 125.04255600273599
WeightedCentroid_x 43.2012922055256
WeightedCentroid_y 33.564573007514
WeightedCentroid_z 53.2618671027028
```

**Comment by ntustison** [comment]
Hi @satra ,  No, they're all in terms of voxels.  Here's the original [documentation](https://www.insight-journal.org/browse/publication/301).

**Comment by satra** [comment]
@ntustison - thank you.

what would `Elongation` mean in terms of non-isotropic voxels?

and does that mean that any of the x, y, and z elements are in terms of whatever voxel spacing is along that dimension.

**Comment by ntustison** [comment]
Good question---probably not meaningful in that case.  I haven't used those additional measures much, if at all.

**Comment by satra** [comment]
thanks @ntustison
