### ISSUE TITLE
error 'std::invalid_argument' when performing ResampleImage 

### ISSUE THREAD

**Issue by Jimmy2027** [ANTsX/ANTs#894]
**Describe the bug**
I am attempting to perform ResampleImage on a brain image with:

````
ResampleImage 3 sub-5668_ses-ofM_acq-TurboRARE_T2w.nii.gz resample/sub-5668_ses-ofM_acq-TurboRARE_T2w.nii 0.2x0.2x0.2 size=1 spacing=0 6
````

However, I get the error: 
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)
```
How can I correctly use the command ResampleImage on this example?

**To Reproduce**
- Get the brain image with 
````wget chymera.eu/debug/ANTs/sub-5668_ses-ofM_acq-TurboRARE_T2w.nii.gz````
- Use command 
````ResampleImage 3 sub-5668_ses-ofM_acq-TurboRARE_T2w.nii.gz sub-5668_ses-ofM_acq-TurboRARE_T2w.nii 0.2x0.2x0.2 size=1 spacing=0 6```` 
to get the error.
   
**Expected behavior**
Resample the image without error

**ANTs version information**
```
antsRegistration --version
ANTs Version: 2.3.1.dev37-gf78b2
Compiled: Oct 15 2019 20:42:39
```

@TheChymera

**Comment by gdevenyi** [comment]
The correct command is:
```
ResampleImage 3 sub-5668_ses-ofM_acq-TurboRARE_T2w.nii.gz resample/sub-5668_ses-ofM_acq-TurboRARE_T2w.nii 0.2x0.2x0.2 1 0 6
```

**Comment by gdevenyi** [comment]
I presume based on the MxNxO entry that you're attempting to specify a spacing.

**Comment by Jimmy2027** [comment]
Thank you for the answer! 
I might not have understood what exactly "size" and "spacing" represent.
If "spacing" is the space between voxels, what is then the voxel size?


If I specify spacing it works fine:
```
ResampleImage 3 sub-5668_ses-ofM_acq-TurboRARE_T2w.nii.gz resample/sub-5668_ses-ofM_acq-TurboRARE_T2w.nii 0.2x0.2x0.2 0
```

However, when I specify size I get an error:
```
ResampleImage 3 sub-5668_ses-ofM_acq-TurboRARE_T2w.nii.gz resample/sub-5668_ses-ofM_acq-TurboRARE_T2w.nii 0.2x0.2x0.2 1
terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /usr/include/ITK-5.0/itkImageFileWriter.hxx:267:
itk::ERROR: ImageFileWriter(0x5652ae9743e0): Largest possible region does not fully contain requested paste IO regionPaste IO region: ImageIORegion (0x7ffdb51736c0)
  Dimension: 3
  Index: 0 0 0 
  Size: 0 0 0 
Largest possible region: ImageRegion (0x7ffdb51737c0)
  Dimension: 3
  Index: [0, 0, 0]
  Size: [0, 0, 0]
```
What is the problem there?

**Comment by ntustison** [comment]
"Size" is in terms of the number of voxels per dimension.  ``0.2x0.2x0.2`` won't work for the size option.
