### ISSUE TITLE
How to convert probability map to the label?

### ISSUE THREAD

**Issue by John1231983** [ANTsX/ANTs#901]
I have three probability of CSF, WM, GM that ranges from [0,1]. In ImageMath or Ants, do we have any function or script to combine these probability maps to the label so that the label of a class is maximum probability at the location? Thanks

**Comment by stnava** [comment]
you just need the argmax operation wrt the probability+label across each
voxel.

then convert this to an image.

this is done more easily with either ANTsR or ANTsPy.   I don't recall an
operation for this in ANTs though it may exist.

in ANTsR, it is something like:

```
probabilityList = imageFileNames2ImageList( "*probability*nii.gz" )
mat = imageListToMatrix( probabilityList, brainMask )
segvec = apply( mat, FUN=which.max, MARGIN = 2)
seeing = makeImage( brainMask, segvec )
```

very similar in python.

best,

BA

brian
