### ISSUE TITLE
Inner or outer surface

### ISSUE THREAD

**Issue by tli3** [ANTsX/ANTs#903]
Hello,
I am using LabelGeometryMeasures to get the total surface area from antsCorticalThickness.nii.gz.
LabelGeometryMeasures  3 antsCorticalThickness.nii.gz 
where the antsCorticalThickness.nii.gz comes from the antsCorticalThickness.sh pipeline.

Label,VolumeInVoxels,SurfaceAreaInMillimetersSquared,Eccentricity,Elongation,Orientation,Centroid_x,Centroid_y,Centroid_z,AxesLength_x,AxesLength_y,AxesLength_z,BoundingBoxLower_x,BoundingBoxLower_y,BoundingBoxLower_z,BoundingBoxUpper_x,BoundingBoxUpper_y,BoundingBoxUpper_z
1,437959,313531.575386796,0.772581216612252,1.57501173019409,1.51002389870212,82.549012578803,117.647252368372,99.9262990371245,102.435249328613,129.550842285156,161.336715698242,18,147,37,201,48,160

I wonder is the SurfaceAreaInMillimetersSquared here the inner surface or outer surface, or inner+outter surface? Thanks a lot.

**Comment by ntustison** [comment]
``LabelGeometryMeasures`` is meant for label images.  Applying them to cortical thickness maps is meaningless.

**Comment by tli3** [comment]
Sorry, I made a mistake here.
May I apply it to the mask of the cortical thickness?
I use fsl to generate the mask first by
fslmaths antsCorticalThickness.nii.gz -bin CorticalThicknessMask.nii.gz
Then, for example,
LabelGeometryMeasures 3 CorticalThicknessMask.nii.gz antsCorticalThickness.nii.gz 1.csv

**Comment by tli3** [comment]
Can I calculate the total cortical surface area in that way? Thanks.

**Comment by ntustison** [comment]
You should probably use the brain extraction mask for that.

**Comment by dorianps** [comment]
I don't think makes sense to get surface area on a binary mask of cortical
thickness. The two gyri inside a sulcus often have adjacent voxels, and
your measurement will not get into that sulcus. Having a look at the binary
mask of cortical thickness might help you understand the problem.

**Comment by cookpa** [comment]
> I wonder is the SurfaceAreaInMillimetersSquared here the inner surface or outer surface, or inner+outter surface? Thanks a lot.

For a label, it's the total surface area enclosing the label volume. This is less than ideal for cortex, because you generally only want either the pial surface or the WM / GM surface.

**Comment by BIG-S2** [comment]
Many thanks to all of you. Is there any method to compute pial (gray/CSF) or (WM/GM) surface area from ANTs currently?

**Comment by cookpa** [comment]
I don't think there's a dedicated tool for it in ANTs. `LabelGeometryMeasures` is a much more general tool that uses a mesh-free approach. The algorithm is designed to accurately capture total surface areas from discretely sampled objects. More background here https://github.com/ANTsX/ANTs/issues/418

**Comment by tli3** [comment]
Thank you very much. 
I still have one short question here: 
In LabelGeometryMeasures, 
are Elongation and Eccentricity shape descriptors calculated the same as the following slides?
http://www.cyto.purdue.edu/cdroms/micro2/content/education/wirth10.pdf
(pp. 23~26)
(We find that those two shape measures are highly genetically heritable in some regions. We'd like to confirm how they are calculated)

**Comment by ntustison** [comment]
You should consult the [technical report](https://hdl.handle.net/1926/1493) detailing the filter.

**Comment by tli3** [comment]
That's really helpful! Thanks a lot!
