### ISSUE TITLE
[Support] [MultivariateTemplateConstruction]

### ISSUE THREAD

**Issue by tashrifbillah** [ANTsX/ANTs#905]
After `antsMultiVariateTemplateConstruction2.sh` completes, `template0.nii.gz` is created along with subject specific `0GenericAffine.mat` and `1Warp.nii.gz` files.

Question is, if I use the following, does my subject image gets warped to template?

> antsApplyTransforms -i sub_.nii.gz -r template0.nii.gz -t sub_1Warp.nii.gz sub_0GenericAffine.mat -o sub_WarpedtoTemplate.nii.gz

For details, this is how I am creating template:

```
antsMultivariateTemplateConstruction2.sh
-d 3
-g 0.2
-t BSplineSyN[0.1,26,0]
-r 1
-c 2
-j 16
-f 8x4x2x1
-o outPrefix
caselist.txt
```

cc: @oferpasternak

**Comment by ntustison** [comment]
```
$ antsApplyTransforms -i sub_.nii.gz -r template0.nii.gz -t sub_1Warp.nii.gz -t sub_0GenericAffine.mat -o sub_WarpedtoTemplate.nii.gz
```

**Comment by tashrifbillah** [comment]
Did you suggest the same command I wrote?

**Comment by ntustison** [comment]
No.  You forgot the second ``-t``.

**Comment by tashrifbillah** [comment]
So, in general, when multiple transform files are applied, should they be specified with `-t` individually?

**Comment by ntustison** [comment]
Yes.  You should look at some of the working examples we have linked to on the front page of the repository.

**Comment by tashrifbillah** [comment]
Okay. Just for the record, when `-t sub_1Warp.nii.gz sub_0GenericAffine.mat` was used, the executable didn't throw an error. So, which transform did actually get used in the above?

**Comment by tashrifbillah** [comment]
@ntustison , irrespective of the second `-t`, same message is printed by `antsApplyTransforms`:

> antsApplyTransforms -d 3 -i ../FA/preproc/989B_FA.nii.gz -o ~/tmp/989B_FA_to_target.nii.gz -r template0.nii.gz -t 989B_FA731Warp.nii.gz -t 989B_FA730GenericAffine.mat -v

(each transform is specified with `-t` flag)

```
Using double precision for computations.
Input scalar image: ../FA/preproc/989B_FA.nii.gz
Reference image: template0.nii.gz
=============================================================================
The composite transform comprises the following transforms (in order):
  1. 989B_FA730GenericAffine.mat (type = AffineTransform)
  2. 989B_FA731Warp.nii.gz (type = DisplacementFieldTransform)
=============================================================================
Default pixel value: 0
Interpolation type: LinearInterpolateImageFunction
Output warped image: /PHShome/tb571/tmp/989B_FA_to_target.nii.gz
```
> antsApplyTransforms -d 3 -i ../FA/preproc/989B_FA.nii.gz -o ~/tmp/989B_FA_to_target.nii.gz -r template0.nii.gz -t 989B_FA731Warp.nii.gz 989B_FA730GenericAffine.mat -v

(two transforms are specified with one `-t` flag)
```
Using double precision for computations.
Input scalar image: ../FA/preproc/989B_FA.nii.gz
Reference image: template0.nii.gz
=============================================================================
The composite transform comprises the following transforms (in order):
  1. 989B_FA730GenericAffine.mat (type = AffineTransform)
  2. 989B_FA731Warp.nii.gz (type = DisplacementFieldTransform)
=============================================================================
Default pixel value: 0
Interpolation type: LinearInterpolateImageFunction
Output warped image: /PHShome/tb571/tmp/989B_FA_to_target.nii.gz
```


Then,

> No. You forgot the second -t.

why do you say I made a mistake?

**Comment by ntustison** [comment]
Because I wrote the program and omitting the second -t is not intended usage.

**Comment by tashrifbillah** [comment]
Great! Then it should be easy for you to answer:

1. (not answered yet) When `-t sub_1Warp.nii.gz sub_0GenericAffine.mat` was used, the executable didn't throw an error. So, which transform did actually get used in the above?

2. Is there a discrepancy between the message printed on console and transforms "actually" applied? Like, do you parse `argv` following `-t`, print them on the console, and use one (or some) of the provided transforms?

We have a pipeline that runs several steps after `antsApplyTransforms`. We already processed some data. Going back and re-running with `-t` before each transform is difficult. So, I am trying to assess if it has been a problem or to what extent it has been a problem.

**Comment by ntustison** [comment]
I’m guessing both transforms are used but I can’t say for sure.  The easiest and  surest way would be for you to go back and check a couple data sets using both commands and seeing what, if any, differences exist between the two.

**Comment by tashrifbillah** [comment]
Going back and redoing the calculation, I didn't find any difference between the two. I know the surest way for you would be to revisit the program you wrote.

The reason I opened this issue was to check with you if the two transforms `sub_1Warp.nii.gz` ,  `sub_0GenericAffine.mat` warp `sub_.nii.gz` to `template0.nii.gz` space. You answered that anyway.

Feel free to close the issue.
