### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by fiona3668** [ANTsX/ANTs#912]
Dear all:
hi~ I am trying to install ANTs in ubuntu, and I followed thses steps:
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS
After this:
[ 70%] No install step for 'ANTS'
[ 76%] Completed 'ANTS'
[100%] Built target ANTS

I tried make install,but there is a error:
Install the project...
-- Install configuration: "MinSizeRel"
CMake Error at Examples/cmake_install.cmake:41 (file):
  file cannot create directory: /opt/ANTs/lib.  Maybe need administrative
  privileges.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)

what I can do for this?

Best,
Fiona

**Comment by ntustison** [comment]
Try changing the install directory in the CMake options.

**Comment by gdevenyi** [comment]
You have ignored the issue template. Please provide all the information requested.

The instructions for building and installing are here: https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS please ensure you follow them.

This issue can be closed.

**Comment by cookpa** [comment]
Specifically, I think 

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#the-build-completed-but-i-forgot-to-set-the-install-prefix-and-cant-write-to-the-default

Will help

**Comment by fiona3668** [comment]
thank you guys.  
@cookpa I tried that, but seems doesn't work.

**Comment by fiona3668** [comment]
ok I figure it out.

**Comment by fiona3668** [comment]
thank you guys
