### ISSUE TITLE
Atropos segmentation fault when initialized with label image with differing number of labels from number of classes specified.

### ISSUE THREAD

**Issue by gdevenyi** [ANTsX/ANTs#919]
**Describe the bug**
If one initializes Atropos with ``-i PriorLabelImage[3,file.nii.gz,0.5]`` where ``file.nii.gz`` then atropos segfaults at the ``Progress:`` stage.

**To Reproduce**
Take an existing label GM/WM/CSF initialization and modify one voxel to have value 4. 

**Expected behavior**
Atropos should catch and throw an error to provide useful feedback to the user, rather than crashing.

**System information (please complete the following information)**
 - OS: Ubuntu 
 - OS version: 14.04.3
 - Type of system: Workstation

**ANTs version information**
 - ANTs code version:
ANTs Version: 2.3.1.dev89-g77cb5
Compiled: Nov 19 2019 11:10:23
 - ANTs installation type: From git repository clone

**Additional context**
I realize this is a user error, but much time was spent figuring out what caused the crash, catching this bad input could save user time.

**Comment by ntustison** [comment]
If you post a 2-D example with command line call, I can work on it.

**Comment by gdevenyi** [comment]
Cheers will get back to you
