### ISSUE TITLE
Segmented masked spine Atlas generation using antsMultivariateTemplateConstruction2.sh

### ISSUE THREAD

**Issue by konstantlem** [ANTsX/ANTs#920]
**Describe the bug**
Hello, I am trying to create an averaging atlas from several spine CTs I have, using the antsMultivariateTemplateConstruction2.sh. I started using the buildtemplateparallel.sh but I kept getting some segmentation errors so I saw that antsMultivariateTemplateConstruction2.sh is an update of the previous mentioned and tried at the beginning only with 2 CTS segmented spines as nifti files. It has been running on my laptop for 2 days now (I dont know if that is normal but I have an Intel i7-7700HQ CPU@ 2.8GHz, RAM 8 GB) and I have the following issues:

1. Try 'cut --help' for more information.
D:/Ants/buildscripts/ANTS-build/Examples/Debug/antsMultivariateTemplateConstruction2.sh: line 920: cd: selection/: No such file or directory

2. Warning:  Your input image contains nonpositive values
which could cause failure or problematic results.  A
possible workaround would be to:
   1. rescale your image to positive values e.g., [10,100].
   2. run N4 on your rescaled image.
   3. (optional) rescale the N4 output to the original
      intensity range.

3. I think it skips SyN registration

*** Running SyN registration (varianceForUpdateField = 3.0000e+00, varianceForTotalField = 0.0000e+00) ***

Using single precision for computations.
Input scalar image: ./MYtemplate001_fifty_1559_1958_seg_ABRepaired.nii.gz
Reference image: MYtemplate0.nii.gz
Transform file does not exist: ./MY01_fifty_1559_1958_seg_AB00GenericAffine.mat
Can't read initial transform ./MY01_fifty_1559_1958_seg_AB00GenericAffine.mat

Running N4 for 3-dimensional images.

Mask not read.  Using the entire image as the mask.

Original intensity range:  [0, 24]

**The exact command line as it was run**
$ D:/Ants/buildscripts/ANTS-build/Examples/Debug/antsMultivariateTemplateConstruction2.sh -d 3 -i 2 -k 1 -f 4x2x1 -s 2x1x0vox -q 30x20x4 -t SyN  -m CC -c 0 -o MY sub*avg.nii.gz
  

**System information**
 - OS: Windows 10 x64 
 - Type of system: Laptop

**ANTs version information**
 - ANTs code version: 2.3.2
 - ANTs installation type: Using zip file downloaded from Github

Thank you

**Comment by ntustison** [comment]
Try turning off bias correction and using full paths:

```
$ D:/Ants/buildscripts/ANTS-build/Examples/Debug/antsMultivariateTemplateConstruction2.sh -d 3 -i 2 -k 1 -f 4x2x1 -s 2x1x0vox -q 30x20x4 -t SyN -m CC -c 0 -n 0 -o ${fullPathToOutputDirectory}/MY ${fullPathToInputDirectory}/sub*avg.nii.gz
```

**Comment by konstantlem** [comment]
Thank you for your quick reply! 

Regarding the path, I am invoking the process from the same directory in which I have my input files, is that a problem? I can see that it has created 3 jobs along with a template named MYtemplate0.nii, another template named MYtempate0MYtemplate0Repaired.nii and two more templates from my input nii files repaired. Which one is my final template having both my input nii files registered? Attached you can find the autocreated jobs.
[job_0_0_metriclog.txt](https://github.com/ANTsX/ANTs/files/3908567/job_0_0_metriclog.txt)
[job_1_0_metriclog.txt](https://github.com/ANTsX/ANTs/files/3908568/job_1_0_metriclog.txt)
[job_2_0_metriclog.txt](https://github.com/ANTsX/ANTs/files/3908569/job_2_0_metriclog.txt)

Also, I found this command line in the file antsMultivariateTemplateConstruction2.sh but I don't quite understand what is the sub*avg.nii.gz and why is not just *.nii.gz. Could you explain?

Regards

**Comment by ntustison** [comment]
For this run you didn't include the option ``-n 0`` which turns off the bias correction.  Please do that.  Also, don't specify your output directory to be the same as the input directory---it is not a "clean" way of doing things and can complicate the running of the program.  In fact, that explains some of the additional files that you're seeing.  Once you've changed those two things, then we can look at any questions you might have.

**Comment by konstantlem** [comment]
Hello again,

I did what you said and run the process without N4 bias correction and seperated the input and output folder but it still skips SyN registration as well as antsApplyTransforms. Attached you can find the logfile I kept as well as the error appears with a pop up window before SyN registration. I choose "retry" and then it stops.
[logfile without N4.txt](https://github.com/ANTsX/ANTs/files/3910976/logfile.without.N4.txt)
![error](https://user-images.githubusercontent.com/39050061/69955013-00261a80-14fd-11ea-9a75-0124f6449b40.png)

Regards

**Comment by ntustison** [comment]
This looks like some weird compilation error.  Did you compile this yourself or did you download one of the pre-compiled binaries?

**Comment by konstantlem** [comment]
No I did not download the pre-compiled binaries rather than used the cmake app along with visual studio to build and compile it on windows via cygwin.

**Comment by dorianps** [comment]
With all the Windows headaches, I would install docker and just use the
container. See here
https://github.com/dorianps/docker/tree/master/ants

If you place all files in a folder (input, output, templates) it should be
as easy as sharing that folder with the container. I have placed a script
that should run easily in Windows, all you need to do is install docker (if
you're Win 10 Pro or Educational, not Home).

**Comment by ntustison** [comment]
Thanks @dorianps .  

@konstantlem --- Just an FYI but development on the Windows platform is difficult as the majority of developers use either Mac or Linux.

**Comment by dorianps** [comment]
There is also the old Windows binaries from v2.1. But I have not used them
thoroughly and not sure if the changes made since then affect template
construction.

The downside of docker is that Windows will not let you use all the CPU
cores. But at least you get going quickly.

Other alternative is Windows Linux Subsystem, which I don't know if it sees
all cpu cores. But that is slower than docker for single threaded processes
from my quick tests.

**Comment by konstantlem** [comment]
Hello, 

Thank you both for your help. I have Windows 10 Home so I decided to install Linux alongside with my Windows and install again Ants there. I followed the process for the super build here https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS. 

I re-run the script without N4 correction again and saw that it runs much faster on linux and started SyN registration although the procedure was killed again after some iterations and it also didnt proceed to the antsApplyTransforms. I am attaching the logfile again.

[logfile.txt](https://github.com/ANTsX/ANTs/files/3915113/logfile.txt)


Regards,

**Comment by ntustison** [comment]
This time it looks like your image size is the culprit.  Try downsampling all your input images such that each dimension < 256 voxels.

**Comment by konstantlem** [comment]
Hello,

at first thank you very much Nick for the tool and your help because with your guidance I managed to take results. I downsampled my 2 CTs and upgraded my ram from 8 to 16 GB and so it runs faster and the last part continues normally having several output files.

However, I have some questions:

1. Is it ok for these output files to be in the same output folder?

2. My final atlas for both CTs is the file MYtemplate0.nii.gz, right? Because as I can see in imfusion, it looks totally similar with the first CT. Does it create the template mostly from the bigger image? Or is it just that I have not run it with N4 bias correction and it has only one iteration i=1? Also, the templeates related to the one CT(MY01_forty_1547_1963_seg_ab11InverseWarp.nii, MY01_forty_1547_1963_seg_ab11Warp.nii, MYtemplate001_forty_1547_1963_seg_ab1WarpedToTemplate.nii) are totally black as opposed to the the other templates related to the first CT.

3. Isn't it a problem for the atlas that I have downsampled so much my CTs? I mean now that I have a better RAM can I downsample my CTs less like <512 rather than <256 voxels for having better resolution?

4. Finally, based on several papers I have segmented the spines and so the input files are masked spines to ease the registrations. Could my atlas be negatively affected because I am using masked images?

Here is my log file again in case you need to clarify something: 
[logfile5.txt](https://github.com/ANTsX/ANTs/files/3921445/logfile5.txt)


Thanks a lot

**Comment by ntustison** [comment]
That's great we're making progress.

>> Is it ok for these output files to be in the same output folder?

Probably.  However, I would recommend keeping different output runs in different folders simply because template construction produces so many output files.  You definitely want to separate the outputs from inputs.

>> My final atlas for both CTs is the file MYtemplate0.nii.gz, right? Because as I can see in imfusion, it looks totally similar with the first CT.

It would be best if you could post the downsampled versions so I could take a look.

>> Isn't it a problem for the atlas that I have downsampled so much my CTs? I mean now that I have a better RAM can I downsample my CTs less like <512 rather than <256 voxels for having better resolution?

Maybe.  Certainly greater resolution is better, generally.  I had you downsample simply because I suspected a memory limitation issue to be what was preventing you from getting the program to run.

4.  Finally, based on several papers I have segmented the spines and so the input files are masked spines to ease the registrations. Could my atlas be negatively affected because I am using masked images?

That's certainly possible.  Again, it would be easier to diagnose if I could see your images.

**Comment by konstantlem** [comment]
Yes, I have different output folders for different runs.
Finally, I tried to run it also for the high resolution CTs, but using -l 1 means only for SyN registration (since here was the problem) without the affine. It works but I got the results I told you. Maybe it is that I didnt do affine registration and the images wasnt aligned? I can send you a link with the output folder but I am not sure if I can upload them here. Could you provide me an email?

Thank you

**Comment by ntustison** [comment]
email:  ntustison@gmail.com

But please send the downsampled input with the command line call.  I don't need the output.

**Comment by ntustison** [comment]
Okay, I think I figured out what your problem is.  Try turning on the ``-r 1`` option.

**Comment by konstantlem** [comment]
Thank you very much! I think now it works but still the similarity tends to be closer to the "resample08healthy" image as I can observe? Is there any specific reason that this happens or it is that we need more than 10 images for the template to be stable? 


And a  couple of questions regarding the parameters :)

So by turning on -r to 1, we do first a rigid body registration to align somehow the images to ease the subsequent SyN deformable registration?

I am now using the following command line:
${command} -d 3 -i 1 -l 0 -r 1 -f 4x2x1 -s 2x1x0vox -q 30x20x4 -t SyN -m CC -n 0 -o ${OutputDir}/MY ${InputDir}/*.nii.gz

Do you think I should try to change the parameters for example to add N4 bias correction or increase the iterations -i to 3 or 4 or even change the similarity metric? 

Also I have turn off -l to 0 while trying to run it but I am not sure that I dont need it. By turning on -l to 1 (default), rigid and affine registration is done before the deformable one, right? So whats the difference between the 2 parameters l and r? l is for both rigid and affine and r is only for rigid?

Regards,
Lemonia

**Comment by ntustison** [comment]
> Is there any specific reason that this happens or it is that we need more than 10 images for the template to be stable?

If one of your subjects is an outlier, then that one will dominate the resulting template.  

> So by turning on -r to 1, we do first a rigid body registration to align somehow the images to ease the subsequent SyN deformable registration?

Yes.

> Do you think I should try to change the parameters for example to add N4 bias correction or increase the iterations -i to 3 or 4 or even change the similarity metric?  

You should definitely increase the number of iterations to at least 4.  You'll have to look at the other parameters and test for yourself if they help improve the results.

> So whats the difference between the 2 parameters l and r?

``r`` refers to how the initial template is created.  ``-r 1`` creates an initial template by rigidly registering all images to the voxelwise average.  ``-l`` governs the linear part of the pairwise registration between each subject and the template.

**Comment by konstantlem** [comment]
Hello Nick, I got your answer but it took 2.5 days for the run (10 CTs) to finish because I also added 3 iterations. Thank you very much! It really looks pretty nice to me, isn’t it? I played a little bit with the parameters like the type of registrations and metrics but I think the ones I finally used are the best. The only thing I don’t get is the part of smoothing parameters -f 4x2x1 -s 2x1x0vox -q 30x20x4 which I haven’t changed at all. Does it make sense to change something here?

 

The command used is: ${command} -d 3 -i 1 -r 1 -l 1 -y 0 -f 4x2x1 -s 2x1x0vox -q 30x20x4 -t SyN -m CC -n 1 -o ${OutputDir}/MY ${InputDir}/*.nii.gz

 

 

Many thanks again,

**Comment by ntustison** [comment]
Yes,  I would change the overall number of iterations to something like ``-i 4``.  Also, since you already did quite a bit of work achieving your current template, you might want to translate your current template to the middle of the image and start optimization from there.  If we call the translated template ``template_translated.nii.gz``, then your command call would be something like

```
antsMultivariateTemplateConstruction2.sh -d 3 -i 4 -r 0 -l 1 -y 0 -f 6x4x2x1 -s 3x2x1x0vox -q 100x50x20x4 -t SyN -m CC -n 1 -o ${OutputDir}/MY ${InputDir}/*.nii.gz -z ``template_translated.nii.gz`` 
```

**Comment by konstantlem** [comment]
I tried to execute the command mentioned, but I get the following error and it is the same even if I specify the full path of the template.

I might have not fully understood  what I should do. I took the template previously generated and I was supposed to feed it to the command via the -z parameter, right?

--------------------------------------------------------------------------------------
 Creating template /home/lemonia/Desktop/atlas/attempt10/output/MYtemplate0.nii.gz from a population average image from the inputs.
   /home/lemonia/Desktop/atlas/attempt10/input/01_fifty_1559_1958_seg_AB.nii.gz /home/lemonia/Desktop/atlas/attempt10/input/01_forty_1547_1963_seg_ab.nii.gz /home/lemonia/Desktop/atlas/attempt10/input/01_healthy_1491_1989_seg_AB.nii.gz /home/lemonia/Desktop/atlas/attempt10/input/03_fifty_1564_1958_seg_AB.nii.gz /home/lemonia/Desktop/atlas/attempt10/input/03_sixty_1583_1949_seg_AB.nii.gz /home/lemonia/Desktop/atlas/attempt10/input/08_fifty_1575_1960_seg_AB.nii.gz /home/lemonia/Desktop/atlas/attempt10/input/08_healthy_1513_1982_seg_AB.nii.gz /home/lemonia/Desktop/atlas/attempt10/input/09_seventy_1625_1934_seg_ab.nii.gz /home/lemonia/Desktop/atlas/attempt10/input/10_fifty_1580_1954_seg_AB.nii.gz -z template_translated.nii.gz
--------------------------------------------------------------------------------------
/home/lemonia/ANTs/Scripts/antsMultivariateTemplateConstruction2.sh: line 272: 15403 Segmentation fault      (core dumped) ${ANTSPATH}/AverageImages $dim $output 1 ${images[*]}
Your initial template : /home/lemonia/Desktop/atlas/attempt10/output/MYtemplate0.nii.gz[0 ] was not created.  This indicates trouble!  You may want to check correctness of your input parameters. exiting.

**Comment by ntustison** [comment]
Please post the command call.

**Comment by konstantlem** [comment]
antsMultivariateTemplateConstruction2.sh -d 3 -i 4 -r 0 -l 1 -y 0 -f 6x4x2x1 -s 3x2x1x0vox -q 100x50x20x4 -t SyN -m CC -n 1 -o ${OutputDir}/MY ${InputDir}/*.nii.gz -z ``template_translated.nii.gz``

**Comment by ntustison** [comment]
Try:

```
antsMultivariateTemplateConstruction2.sh -d 3 -i 4 -r 0 -l 1 -y 0 -f 6x4x2x1 -s 3x2x1x0vox -q 100x50x20x4 -t SyN -m CC -n 1 -o ${OutputDir}/MY -z template_translated.nii.gz ${InputDir}/*.nii.gz 
```

**Comment by konstantlem** [comment]
Hello Nick,

Your last command worked fine and the spine seems clear enough. However I would like to ask you something more. The intensities of each vertebra of the template are not uniform and I need every vertebra with the same intensity because I am using intensities in my code where I should use the atlas to do several other things. Is there any way to keep intensities as it was in the input images (range 1-25)?

Thank you

**Comment by cookpa** [comment]
There's no way to directly manipulate the image intensities, but you can change the method used to generate the average image that becomes the template with `-a`.
