### ISSUE TITLE
antsMultivariateTemplateConstruction Execution Time 

### ISSUE THREAD

**Issue by asoroosh** [ANTsX/ANTs#923]
I'm processing 1000's of longitudinal MRI subjects through the `antsMultivariateTemplateConstruction2.sh` pipeline to create single subject templates (SSTs).  We're working at 1mm^3 resolution and many subjects have well over 10 visits, and as a result, the run times are becoming painful.  I'm opening this issue to solicit input on how I can make this more computationally efficient.

First, I'm aware that I can parallelise `antsMultivariateTemplateConstruction2.sh`, but with 1000's of subjects and a fixed number of cores, this won't change our overall throughput. (i.e. parallelisation can shorten per-subject run time but at the cost of running fewer subjects simultaneously)."

Mainly I'd like input on the different options I've considered to shorten execution time and their possible effect on the output SST:

1. Reduce the iterations (`-i`), from 4 to 3 or 2.
1. Increasing the shrink factors (`-f 8x8x2x1`).
1. Reduce the registration iterations (`-q 50x30x15x2`).
1. Skip some visits.

On this last option (i.e. Skip some visits):  The visits are not uniformly spaced, e.g. some have monthly scans in the first year, and then yearly for the next 5-8 years; I could consider only yearly scans, and then asymmetrically register the omitted scans to the SST.

**Comment by gdevenyi** [comment]
You need a cluster.

**Comment by asoroosh** [comment]
The term "cores" in my question refers to the cluster cores. I do use a cluster to generate SSTs using `antsMultivariateTemplateConstruction2.sh` but yet this operation is extremely taxing due to the reason explained in the questions; many many visits per subject and tens of thousands of subjects.

**Comment by gdevenyi** [comment]
All of the options you have proposed will reduce the quality of the overall average. You've run into the classic engineering tradeoff, "good, fast, cheap" pick two.

You should be aware its possible you're slightly biasing your modelbuild to the subjects with more scans, you may want to consider something like my wrapper implementation: https://github.com/cobralab/twolevel_ants_dbm which does a within-subject, then a between-subject modelbuild, to minimize such a bias.

**Comment by cookpa** [comment]
The registration should print the computation time for each stage of the registration, so you can get some idea of where time savings can be made. I would recommend looking at both the affine and deformable stages.

**Comment by nicholst** [comment]
Hi @gdevenyi, 

I work with @asoroosh... I was wonder what you thought about this comment from the [ANTS documentation](https://github.com/stnava/ANTsDoc/raw/master/ants2.pdf) (my **bold**)

> 2.9 Optimal template construction with ANTs
> A useful script for setting up optimal template construction is available in ANTs/Scripts. [...] Two key points about optimal templates: 1. **The outcome stabilizes at around ten images**, for most populations. 

I read this as "When making an intersubject template, it is sufficient to build your template based on 10 random subjects".

For our setting, longitudinal intrasubject registration, I want to translate this as "When making an intrasubject template, it is sufficient to build your template based on 10 representative images", and, let's face it... atrophy changes are dramatically smaller than intersubject differences, and so we probably don't even need 10 images... e.g. maybe 5 is enough?  

Given that some of our studies have *monthly* scans initially, but then go on with annual scans 10+years, I'm suggesting that @asoroosh to use 5 linearly spaced scans (1st scan, last scan, and 3 scans closest to 1/4, 1/2 and 3/4 time points) and then register the rest to that SST.

Does this seem like a reasonable approach?

**Comment by gdevenyi** [comment]
Hi @nicholst, it depends on your goal here.

My tool linked above is setup to produce a complete set of longitudinal DBM outputs suitable for analysis within-subject with something such as a linear mixed effects modeling voxel-wise. It uses the ants template builder underneath to get the best possible within-subject sensitivity, and then again between subjects to get everything into a common space for analysis. Everything needs to be processed so I have measures for every scan at the end.

If your goal is instead to produce a population level average for other purposes, then I suspect the recommendations from the documentation are sound. I suspect the ANTs guys have crunched a lot of data.
