### ISSUE TITLE
Atropos does not generate output when the binary mask is not in the same lattice space as the input image

### ISSUE THREAD

**Issue by aghayoor** [ANTsX/ANTs#924]
**Describe the bug**
When the input binary mask is not in the same lattice space as the input image, the Atropos does not generate any output. However, it does not return any error or failure.

**To Reproduce**
Here is the command line:
`Atropos -a input_image.nii -x mask.nii -o [segmented_output.nii.gz,posterior_probability%02d.nii.gz] -i Kmeans[5] -k Gaussian -m [0.1,1x1x1]`

Data can be downloaded here:
https://www.dropbox.com/s/5crjovxvva6say5/Rabbit_data_to_share.zip?dl=0
   
ITKSnap shows that the input image and the mask are correctly overlapped in physical space. However, they have different resolution in the z direction.

**System information (please complete the following information)**
 - OS: Mac OS
 - OS version: 10.14.6
 - Type of system: laptop

**ANTs version information**
 - ANTs code version: built based on the latest HEAD of master branch as of Nov 21, 2019 (2629431801865edd82d59c7ebb31b993c6243772)
 - ANTs installation type: Compiled from source

**Comment by gdevenyi** [comment]
This is a common limitation in most ants tools. Files must be in the same voxel space, not just the same physical space. Use antsapplytransforms to resample to a common voxel space.

**Comment by aghayoor** [comment]
Yes, I resampled the images to the same voxel space to resolve the issue. However, I was thinking it might be a bug that is worth to report, not a limitation. Thanks for the clarification.

**Comment by ntustison** [comment]
Just for clarification, this limitation goes all the way to the ITK foundation.

**Comment by aghayoor** [comment]
Hi Nick, 

I have made a way around this limitation in [BRAINSABC](https://github.com/BRAINSia/BRAINSTools/tree/master/BRAINSABC) by using interpolators inside the iterator loops. Now, BRAINSABC processes the images in physical space by doing a little compromise on the run time.

There is no need to follow the same approach in ANTs, but I suggest to return a warning when the images are not in the same voxel space. It will be very helpful to the users to identify the limitation. Currently Atropos runs silently while no output is generated. It can be very confusing to the users. It took me a while to find out what was wrong with my input data.

**Comment by cookpa** [comment]
Thanks @aghayoor for the example with data. 

With `--verbose`, I see this error:

```
itk::ExceptionObject (0x7fafb799da40)
Location: "unknown" 
File: /Users/pcook/tmp/NOT_BACKED_UP/antsBuild/staging/include/ITK-5.1/itkImageToImageFilter.hxx
Line: 220
Description: itk::ERROR: AtroposSegmentationImageFilter(0x7fafb799f060): Inputs do not occupy the same physical space! 
InputImage Origin: [1.9914438e+01, 1.3925134e+01, 1.4625000e+01], InputImage_1 Origin: [1.9914438e+01, 1.3925134e+01, 1.4898396e+01]
	Tolerance: 1.4973262e-07
InputImage Spacing: [1.4973262e-01, 1.4973262e-01, 7.5000000e-01], InputImage_1 Spacing: [1.4973262e-01, 1.4973262e-01, 1.4973262e-01]
	Tolerance: 1.4973262e-07
```

I worked around this with 

```
CopyImageHeaderInformation input_image.nii input_image.nii input_image2.nii 1 1 1 
CopyImageHeaderInformation input_image.nii mask.nii mask2.nii 1 1 1 
Atropos -a input_image2.nii -x mask2.nii -o [segmented_output.nii.gz,posterior_probability%02d.nii.gz] -i Kmeans[5] -k Gaussian -m [0.1,1x1x1]
```

This runs, but could give misleading results if the index space of the input images is assumed to be the same - I will add a note to the usage to inform users about this.

**Comment by aghayoor** [comment]
Thanks @cookpa for looking into that. I could resolve the issue by resampling the mask image to the input image lattice space. It will be great if a note is added to the usage to notify the users about this limitation.
