### ISSUE TITLE
Build failed: cannot open include file: itkLabelImageGenericInterpolateImageFunction

### ISSUE THREAD

**Issue by qiang-zhang-neu** [ANTsX/ANTs#928]
The building the ANTs is failed.
My environment is:
Win10
VS 2015
CMake 3.16.2

I use the system ITK, and the version is: 5.0.1

The error is:
![error](https://user-images.githubusercontent.com/58067483/71966009-ca7efa80-323b-11ea-9c90-759d53270d53.PNG)

Any suggestion is appreciated.

**Comment by crossmanith** [comment]
Did you build ITK with "Module_ITKReview                 ON "? This should resolve the last three lines complaining about missing file itkLabelGeometryImageFilter.hxx

**Comment by gdevenyi** [comment]
The system ITK needs to built with the GenericLabel module enabled: https://github.com/ANTsX/ANTs/blob/master/SuperBuild/External_ITKv5.cmake#L131

**Comment by qiang-zhang-neu** [comment]
Thanks for @crossmanith and @gdevenyi , it solved my problems.
