### ISSUE TITLE
How to start ANTs?

### ISSUE THREAD

**Issue by qiang-zhang-neu** [ANTsX/ANTs#929]
I have built the ANTs project, but I don't know how to use it. Some bash/R/python examples have been provided, but how can I use it in my C++ project, just like: ants.registration in the python?

Could you provide a demo including the source code and CMakeList.txt? Any suggestion is appreciated.

**Comment by gdevenyi** [comment]
ANTs provides command-line programs, not C++ interfaces.

Please look into ITKv5 if you want to write your own software.

**Comment by qiang-zhang-neu** [comment]
> ANTs provides command-line programs, not C++ interfaces.
> 
> Please look into ITKv5 if you want to write your own software.

For the command-line programs, should I add the D:\ANTs-master\bin\ANTS-build\Examples\Release to the system environment?
