### ISSUE TITLE
Eddy Current Correction - 3DT1 and 3D FLAIR

### ISSUE THREAD

**Issue by Adam123-png** [ANTsX/ANTs#930]
Hello all, 
I want to perform the eddy current correcction on my input 3DT1 and 3D FLAIR images. Is there any algorithm for eddy current correction? Actually I don´t assume any significant changes after the correction but I have to check it.

Thanks a lot
Regards
Adam

**Comment by cookpa** [comment]
There isn't anything specific, but if you have a model of the distortion, you can try to constrain the deformation to be similar (eg, by varying spline spacing or regularization parameters).

**Comment by Adam123-png** [comment]
OK. Thanks for your advice I will try it.
