### ISSUE TITLE
antsMotionCorr -- add support for other interpolation strategies

### ISSUE THREAD

**Issue by dangom** [ANTsX/ANTs#931]
**Is your feature request related to a problem? 

I noticed the resampled images that come as output of antsMotionCorr are somewhat smooth. Checking the code it seems like the ResampleImageFilter interpolator being used is the default   LinearInterpolateImageFunction, and users cannot change this.

**Describe the solution you'd like**
antsMotionCorr expose other interpolation schemes via a `--interpolation` flag.

**Describe alternatives you've considered**
I've considered saving the transform as a warpfield, and then applying it to the BOLD series later using antsApplyTransforms choosing a different interp algorithm. That is cumbersome in that it requires first replicating the reference to make it 4D, and there is always room for error when calling two commands instead of a single one.

**Comment by dangom** [comment]
I guess somewhere here:
https://github.com/ANTsX/ANTs/blob/f19c6394c35108c373ca8643814f9a37ea45e752/Examples/antsMotionCorr.cxx#L1428

A line with:
```
resampler->SetInterpolator( interpolator );
```

where `interpolator` comes from a command line flag?

**Comment by ntustison** [comment]
@dangom --- this sounds like a good idea.  Do you feel comfortable putting together a pull request?

**Comment by dangom** [comment]
I would love to. So far I've figured out that I have to add the following:

0. Add relevant headers:

```
#include "itkBSplineInterpolateImageFunction.h"
#include "itkLinearInterpolateImageFunction.h"
#include "itkGaussianInterpolateImageFunction.h"
#include "itkInterpolateImageFunction.h"
#include "itkNearestNeighborInterpolateImageFunction.h"
#include "itkWindowedSincInterpolateImageFunction.h"
#include "itkLabelImageGaussianInterpolateImageFunction.h"
#include "itkLabelImageGenericInterpolateImageFunction.h"

```

1. Add the interpolation options to the cli parser:
```
  {
    std::string description =
      std::string( "Several interpolation options are available in ITK. " )
      + std::string( "These have all been made available." );

    OptionType::Pointer option = OptionType::New();
    option->SetLongName( "interpolation" );
    option->SetShortName( 'n' );
    option->SetUsageOption( 0, "Linear" );
    option->SetUsageOption( 1, "NearestNeighbor" );
    option->SetUsageOption( 2, "Gaussian[<sigma=imageSpacing>,<alpha=1.0>]" );
    option->SetUsageOption( 3, "BSpline[<order=3>]" );
    option->SetUsageOption( 4, "CosineWindowedSinc" );
    option->SetUsageOption( 5, "WelchWindowedSinc" );
    option->SetUsageOption( 6, "HammingWindowedSinc" );
    option->SetUsageOption( 7, "LanczosWindowedSinc" );
    option->SetDescription( description );
    parser->AddOption( option );
  }
```

Parse it and check that it's OK:

```
  // Get the interpolator and possible parameters
  std::string whichInterpolator( "linear" );
  typename OptionType::Pointer interpolationOption = parser->GetOption( "interpolation" );
  if( interpolationOption && interpolationOption->GetNumberOfFunctions() )
    {
    whichInterpolator = interpolationOption->GetFunction( 0 )->GetName();
    ConvertToLowerCase( whichInterpolator );
    }
  if( !std::strcmp( whichInterpolator.c_str(), "multilabel" ) || !std::strcmp( whichInterpolator.c_str(), "genericlabel" ) )
    {
    if( verbose )
      {
      std::cerr << "A label-based interpolator is not appropriate for this application." << std::endl;
      }
    return EXIT_FAILURE;
    }
```
And finally set the interpolation type. This is the part where I'm stuck. How do I actually get an `interpolatorType` from the cli arguments? I couldn't find a straightforward example where this is done, but perhaps I'm missing something simple.

```
     \\ What should go in something_from_the_parser
      typename InterpolatorType::Pointer interpolator = something_from_the_parser
      resampler->SetInterpolator(interpolator );

```
Would that be all?

**Comment by ntustison** [comment]
``antsApplyTransforms.cxx`` would be a good guide.  Specifically, check out this [code chunk](https://github.com/ANTsX/ANTs/blob/master/Examples/antsApplyTransforms.cxx#L408-L426).
