### ISSUE TITLE
ANTs v2.3.0 or higher get corrupted header

### ISSUE THREAD

**Issue by arnaudbore** [ANTsX/ANTs#933]
**Describe the bug**
When using ANTs v2.3.0 and higher the ouput header is corrupted (srow_ are not set). When I use ANTs 2.1.0 or 2.2.0 the header is okay. 

**To Reproduce**
I uploaded the [data and script](https://box.criugm.qc.ca/f/211810a106d34b618b32/?dl=1
)
  
**Expected behavior**
The output header should look like this:

 ```
PrintHeader patient2mni_2mmWarped.nii.gz

Spacing [2, 2, 2]
 Origin [-90, 126, -72]
 Direction 
1 0 0
0 -1 0
0 0 1
 Size : 91 109  91
  Image Dimensions   : [91, 109, 91]
  Bounding Box       : {[-90 126 -72], [92 344 110]}
  Voxel Spacing      : [2, 2, 2]
  Intensity Range    : [0, 1042.3]
  Mean Intensity     : 92.5522
  Direction Cos Mtx. : 
1 0 0
0 -1 0
0 0 1
  Voxel->RAS x-form  : 
  Image Metadata: 
    bitpix = 64
    cal_max = 0
    cal_min = 0
    datatype = 64
    dim[0] = 3
    dim[1] = 91
    dim[2] = 109
    dim[3] = 91
    dim[4] = 1
    dim[5] = 1
    dim[6] = 1
    dim[7] = 1
    intent_code = 0
    intent_p1 = 0
    intent_p2 = 0
    intent_p3 = 0
    pixdim[0] = -1
    pixdim[1] = 2
    pixdim[2] = 2
    pixdim[3] = 2
    pixdim[4] = 0
    pixdim[5] = 0
    pixdim[6] = 0
    pixdim[7] = 0
    qform_code = 2
    qoffset_x = 90
    qoffset_y = -126
    qoffset_z = -72
    quatern_b = -0
    quatern_c = 1
    quatern_d = 0
    scl_inter = 0
    scl_slope = 1
    sform_code = 1
    slice_duration = 0
    slice_end = 0
    slice_start = 0
    srow_x = -2 -0 0 90
    srow_y = -0 2 -0 -126
    srow_z = 0 0 2 -72
    toffset = 0
    vox_offset = 352
```

**System information (please complete the following information)**
 - OS: Linux
 - OS version: 18.04
 - Type of system: Desktop

**ANTs version information**
 - ANTs code version: 2.2.0.dev150-g6f403 (v2.3.1) (even 2.3.0 didn't work)
 - ANTs installation type: Compiled from source

**Comment by cookpa** [comment]
This is a result of an ITK change in how NIFTI images are handled. The sform is removed to reduce ambiguity. I understand it can be a serious problem for users, but I don't think we can change this readily in ANTs.

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

**Comment by jchoude** [comment]
Quick question, since I don't really know about the internals of Ants / ITK: in the wiki page that you linked, it is said:

```
When writing NIFTI files, ITK encodes the rotation, 
translation and scaling in the qform. The qform code is set to 
1 (NIFTI_XFORM_SCANNER_ANAT), and the sform code is 
set to 0. The loss of the sform is unavoidable because the 
ITK I/O code reads images into a common internal structure, 
independent of the individual image format on disk, and only 
supports a rigid transformation.
```

Most of the other tools that we use deal with this situation by setting the `sform_code` to `1` and encoding exactly the same transformation in the `sform` as is encoded in the `qform`. That way, interoperability with other tools would still work in most cases.

I know that this is not exactly the intended behavior and use of the transforms as specified by the Nifti standard, but in practice, most recent tools use this behavior to help interoperability. Furthermore, I don't think a majority of users really use the full capacity of having two different transforms in a single Nifti file.

**Comment by ntustison** [comment]
All image IO in ANTs is executed via ITK standard libraries and this NIFTI header issue is purely an ITK issue.  If you want something changed or need more information, you would have to take this up with the [ITK people](https://discourse.itk.org).
