### ISSUE TITLE
No bug and no result

### ISSUE THREAD

**Issue by qiang-zhang-neu** [ANTsX/ANTs#935]
the shell code is:

```
antsRegistration -d 3 \
                 -v 1 \
                 -t BSplineSyN[0.1,80,0,3] \
                 -m MSQ[${inspirationPreprocessed},${expirationPreprocessed},1,1] \
                 -c 200x200 \
                 -f 8x6 \
                 -s 2x1 \
                 -o [${outputPrefix}]
```

the information shown in the command window is:

```
All_Command_lines_OK
Using double precision for computations.
  number of levels = 2
  fixed image: .//tmp//Output//N25I_preprocessed.nii.gz
  moving image: .//tmp//Output//N25E_preprocessed.nii.gz

```

There is no error. But the shell code is finished in less than 1 min, and I can not find the registration result. What's wrong with my code/data?

**Comment by ntustison** [comment]
Have you tried running some of the [examples](https://github.com/ANTsX/ANTs#lung)?

**Comment by cookpa** [comment]
Add `--verbose` to get more information on any problems

**Comment by qiang-zhang-neu** [comment]
> Have you tried running some of the [examples](https://github.com/ANTsX/ANTs#lung)?

@ntustison Yes, I have run your code of lung [registration](https://github.com/ntustison/antsCtLungRegistrationExample), and it's OK. But it failed for my data.

**Comment by qiang-zhang-neu** [comment]
> Add `--verbose` to get more information on any problems

@cookpa I add the --verbose to the code:
```
antsRegistration -d 3 \
                 -v 1 \
                 -t BSplineSyN[0.1,80,0,3] \
                 -m MSQ[${inspirationPreprocessed},${expirationPreprocessed},1,1] \
                 -c 200x200 \
                 -f 8x6 \
                 -s 2x1 \
                 -o [${outputPrefix}] \
		 --verbose
```

However, there is no more information:
```
All_Command_lines_OK
Using double precision for computations.
  number of levels = 2
  fixed image: .//tmp//Output//N25I_preprocessed.nii.gz
  moving image: .//tmp//Output//N25E_preprocessed.nii.gz

```

**Comment by ntustison** [comment]
I'm assuming you got the data and the script from this [example](https://github.com/ntustison/antsCtLungRegistrationExample/).  In that case, I have no trouble running your code (see below).  If you're able to run the examples, then you shouldn't have trouble with the small modification that you made to the example script.

```
$ antsRegistration -d 3 \
>                  -v 1 \
>                  -t BSplineSyN[0.1,80,0,3] \
>                  -m MSQ[${inspirationPreprocessed},${expirationPreprocessed},1,1] \
>                  -c 200x200x100x100x50 \
>                  -f 8x6x4x2x1 \
>                  -s 2x1x0x0x0 \
>                  -o [${outputPrefix},${outputPrefix}Warped.nii.gz,${outputPrefix}InverseWarped.nii.gz]
All_Command_lines_OK
Using double precision for computations.
  number of levels = 5
  fixed image: .//Output//N25I_preprocessed.nii.gz
  moving image: .//Output//N25E_preprocessed.nii.gz
Dimension = 3
Number of stages = 1
Use Histogram Matching false
Winsorize image intensities false
Lower quantile = 0
Upper quantile = 1
Stage 1 State
   Image metric = MeanSquares
     Fixed image = Image (0x7ffcab613080)
  RTTI typeinfo:   itk::Image<double, 3u>
  Reference Count: 2
  Modified Time: 1143
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 926
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [192, 192, 207]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [192, 192, 207]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [192, 192, 207]
  Spacing: [2, 2, 2]
  Origin: [-196.625, 43.625, -393]
  Direction: 
1 0 0
0 -1 0
0 0 1

  IndexToPointMatrix: 
2 0 0
0 -2 0
0 0 2

  PointToIndexMatrix: 
0.5 0 0
0 -0.5 0
0 0 0.5

  Inverse Direction: 
1 0 0
0 -1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x7ffcab613360)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
      Reference Count: 1
      Modified Time: 923
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x113801000
      Container manages memory: true
      Size: 7630848
      Capacity: 7630848

     Moving image = Image (0x7ffcad1d7ee0)
  RTTI typeinfo:   itk::Image<double, 3u>
  Reference Count: 2
  Modified Time: 1144
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 1141
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [192, 192, 207]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [192, 192, 207]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [192, 192, 207]
  Spacing: [2, 2, 2]
  Origin: [-196.625, 43.625, -393]
  Direction: 
1 0 0
0 -1 0
0 0 1

  IndexToPointMatrix: 
2 0 0
0 -2 0
0 0 2

  PointToIndexMatrix: 
0.5 0 0
0 -0.5 0
0 0 0.5

  Inverse Direction: 
1 0 0
0 -1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x7ffcad1d4c10)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
      Reference Count: 1
      Modified Time: 1138
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x118f55000
      Container manages memory: true
      Size: 7630848
      Capacity: 7630848

     Weighting = 1
     Sampling strategy = none
     Number of bins = 32
     Radius = 4
     Sampling percentage  = 1
   Transform = BSplineSyN
     Gradient step = 0.1
     Update field sigma (voxel space) = 0
     Total field sigma (voxel space) = 0
     Update field time sigma = 0
     Total field time sigma  = 0
     Number of time indices = 0
     Number of time point samples = 0
Registration using 1 total stages.

Stage 0
  iterations = 200x200x100x100x50
  convergence threshold = 1e-06
  convergence window size = 10
  number of levels = 5
  using the MeanSquares metric (weight = 1)
  Shrink factors (level 1 out of 5): [8, 8, 8]
  Shrink factors (level 2 out of 5): [6, 6, 6]
  Shrink factors (level 3 out of 5): [4, 4, 4]
  Shrink factors (level 4 out of 5): [2, 2, 2]
  Shrink factors (level 5 out of 5): [1, 1, 1]
  smoothing sigmas per level: [2, 1, 0, 0, 0]
  Using default NONE metricSamplingStrategy 

*** Running B-spline SyN registration (updateMeshSizeAtBaseLevel = [5, 5, 6], totalMeshSizeAtBaseLevel = [0, 0, 0]) ***

XDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
WDIAGNOSTIC,     1, 1.341722034051e-02, 1.797693134862e+308, 1.2822e+00, 1.2822e+00, 
WDIAGNOSTIC,     2, 1.288565192472e-02, 1.797693134862e+308, 1.4572e+00, 1.7497e-01, 
WDIAGNOSTIC,     3, 1.237284947610e-02, 1.797693134862e+308, 1.6247e+00, 1.6753e-01, 
WDIAGNOSTIC,     4, 1.187941336844e-02, 1.797693134862e+308, 1.7822e+00, 1.5751e-01, 
WDIAGNOSTIC,     5, 1.139371598740e-02, 1.797693134862e+308, 1.9420e+00, 1.5974e-01, 
WDIAGNOSTIC,     6, 1.092451951905e-02, 1.797693134862e+308, 2.1004e+00, 1.5839e-01, 
WDIAGNOSTIC,     7, 1.047784812412e-02, 1.797693134862e+308, 2.2594e+00, 1.5903e-01, 
WDIAGNOSTIC,     8, 1.005962541898e-02, 1.797693134862e+308, 2.4197e+00, 1.6027e-01, 
WDIAGNOSTIC,     9, 9.674643790006e-03, 1.797693134862e+308, 2.5747e+00, 1.5504e-01, 
WDIAGNOSTIC,    10, 9.365140356541e-03, 2.328248632090e-02, 2.7338e+00, 1.5906e-01, 
WDIAGNOSTIC,    11, 9.019728212699e-03, 2.044209924707e-02, 2.8904e+00, 1.5666e-01, 
...
```

**Comment by qiang-zhang-neu** [comment]
> I'm assuming you got the data and the script from this [example](https://github.com/ntustison/antsCtLungRegistrationExample/). In that case, I have no trouble running your code (see below). If you're able to run the examples, then you shouldn't have trouble with the small modification that you made to the example script.
> 
> ```
> $ antsRegistration -d 3 \
> >                  -v 1 \
> >                  -t BSplineSyN[0.1,80,0,3] \
> >                  -m MSQ[${inspirationPreprocessed},${expirationPreprocessed},1,1] \
> >                  -c 200x200x100x100x50 \
> >                  -f 8x6x4x2x1 \
> >                  -s 2x1x0x0x0 \
> >                  -o [${outputPrefix},${outputPrefix}Warped.nii.gz,${outputPrefix}InverseWarped.nii.gz]
> All_Command_lines_OK
> Using double precision for computations.
>   number of levels = 5
>   fixed image: .//Output//N25I_preprocessed.nii.gz
>   moving image: .//Output//N25E_preprocessed.nii.gz
> Dimension = 3
> Number of stages = 1
> Use Histogram Matching false
> Winsorize image intensities false
> Lower quantile = 0
> Upper quantile = 1
> Stage 1 State
>    Image metric = MeanSquares
>      Fixed image = Image (0x7ffcab613080)
>   RTTI typeinfo:   itk::Image<double, 3u>
>   Reference Count: 2
>   Modified Time: 1143
>   Debug: Off
>   Object Name: 
>   Observers: 
>     none
>   Source: (none)
>   Source output name: (none)
>   Release Data: Off
>   Data Released: False
>   Global Release Data: Off
>   PipelineMTime: 0
>   UpdateMTime: 926
>   RealTimeStamp: 0 seconds 
>   LargestPossibleRegion: 
>     Dimension: 3
>     Index: [0, 0, 0]
>     Size: [192, 192, 207]
>   BufferedRegion: 
>     Dimension: 3
>     Index: [0, 0, 0]
>     Size: [192, 192, 207]
>   RequestedRegion: 
>     Dimension: 3
>     Index: [0, 0, 0]
>     Size: [192, 192, 207]
>   Spacing: [2, 2, 2]
>   Origin: [-196.625, 43.625, -393]
>   Direction: 
> 1 0 0
> 0 -1 0
> 0 0 1
> 
>   IndexToPointMatrix: 
> 2 0 0
> 0 -2 0
> 0 0 2
> 
>   PointToIndexMatrix: 
> 0.5 0 0
> 0 -0.5 0
> 0 0 0.5
> 
>   Inverse Direction: 
> 1 0 0
> 0 -1 0
> 0 0 1
> 
>   PixelContainer: 
>     ImportImageContainer (0x7ffcab613360)
>       RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
>       Reference Count: 1
>       Modified Time: 923
>       Debug: Off
>       Object Name: 
>       Observers: 
>         none
>       Pointer: 0x113801000
>       Container manages memory: true
>       Size: 7630848
>       Capacity: 7630848
> 
>      Moving image = Image (0x7ffcad1d7ee0)
>   RTTI typeinfo:   itk::Image<double, 3u>
>   Reference Count: 2
>   Modified Time: 1144
>   Debug: Off
>   Object Name: 
>   Observers: 
>     none
>   Source: (none)
>   Source output name: (none)
>   Release Data: Off
>   Data Released: False
>   Global Release Data: Off
>   PipelineMTime: 0
>   UpdateMTime: 1141
>   RealTimeStamp: 0 seconds 
>   LargestPossibleRegion: 
>     Dimension: 3
>     Index: [0, 0, 0]
>     Size: [192, 192, 207]
>   BufferedRegion: 
>     Dimension: 3
>     Index: [0, 0, 0]
>     Size: [192, 192, 207]
>   RequestedRegion: 
>     Dimension: 3
>     Index: [0, 0, 0]
>     Size: [192, 192, 207]
>   Spacing: [2, 2, 2]
>   Origin: [-196.625, 43.625, -393]
>   Direction: 
> 1 0 0
> 0 -1 0
> 0 0 1
> 
>   IndexToPointMatrix: 
> 2 0 0
> 0 -2 0
> 0 0 2
> 
>   PointToIndexMatrix: 
> 0.5 0 0
> 0 -0.5 0
> 0 0 0.5
> 
>   Inverse Direction: 
> 1 0 0
> 0 -1 0
> 0 0 1
> 
>   PixelContainer: 
>     ImportImageContainer (0x7ffcad1d4c10)
>       RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
>       Reference Count: 1
>       Modified Time: 1138
>       Debug: Off
>       Object Name: 
>       Observers: 
>         none
>       Pointer: 0x118f55000
>       Container manages memory: true
>       Size: 7630848
>       Capacity: 7630848
> 
>      Weighting = 1
>      Sampling strategy = none
>      Number of bins = 32
>      Radius = 4
>      Sampling percentage  = 1
>    Transform = BSplineSyN
>      Gradient step = 0.1
>      Update field sigma (voxel space) = 0
>      Total field sigma (voxel space) = 0
>      Update field time sigma = 0
>      Total field time sigma  = 0
>      Number of time indices = 0
>      Number of time point samples = 0
> Registration using 1 total stages.
> 
> Stage 0
>   iterations = 200x200x100x100x50
>   convergence threshold = 1e-06
>   convergence window size = 10
>   number of levels = 5
>   using the MeanSquares metric (weight = 1)
>   Shrink factors (level 1 out of 5): [8, 8, 8]
>   Shrink factors (level 2 out of 5): [6, 6, 6]
>   Shrink factors (level 3 out of 5): [4, 4, 4]
>   Shrink factors (level 4 out of 5): [2, 2, 2]
>   Shrink factors (level 5 out of 5): [1, 1, 1]
>   smoothing sigmas per level: [2, 1, 0, 0, 0]
>   Using default NONE metricSamplingStrategy 
> 
> *** Running B-spline SyN registration (updateMeshSizeAtBaseLevel = [5, 5, 6], totalMeshSizeAtBaseLevel = [0, 0, 0]) ***
> 
> XDIAGNOSTIC,Iteration,metricValue,convergenceValue,ITERATION_TIME_INDEX,SINCE_LAST
> WDIAGNOSTIC,     1, 1.341722034051e-02, 1.797693134862e+308, 1.2822e+00, 1.2822e+00, 
> WDIAGNOSTIC,     2, 1.288565192472e-02, 1.797693134862e+308, 1.4572e+00, 1.7497e-01, 
> WDIAGNOSTIC,     3, 1.237284947610e-02, 1.797693134862e+308, 1.6247e+00, 1.6753e-01, 
> WDIAGNOSTIC,     4, 1.187941336844e-02, 1.797693134862e+308, 1.7822e+00, 1.5751e-01, 
> WDIAGNOSTIC,     5, 1.139371598740e-02, 1.797693134862e+308, 1.9420e+00, 1.5974e-01, 
> WDIAGNOSTIC,     6, 1.092451951905e-02, 1.797693134862e+308, 2.1004e+00, 1.5839e-01, 
> WDIAGNOSTIC,     7, 1.047784812412e-02, 1.797693134862e+308, 2.2594e+00, 1.5903e-01, 
> WDIAGNOSTIC,     8, 1.005962541898e-02, 1.797693134862e+308, 2.4197e+00, 1.6027e-01, 
> WDIAGNOSTIC,     9, 9.674643790006e-03, 1.797693134862e+308, 2.5747e+00, 1.5504e-01, 
> WDIAGNOSTIC,    10, 9.365140356541e-03, 2.328248632090e-02, 2.7338e+00, 1.5906e-01, 
> WDIAGNOSTIC,    11, 9.019728212699e-03, 2.044209924707e-02, 2.8904e+00, 1.5666e-01, 
> ...
> ```

Yes, I am using the code from this [example](https://github.com/ntustison/antsCtLungRegistrationExample/). The size of my data is [512, 512, 348]. When I down-resample the image to  [256, 256, 174], the code is OK. But when I down-resample the image to [512, 256, 348], a bug is reported:
```

All_Command_lines_OK
Using double precision for computations.
  number of levels = 2
  fixed image: .//tmp//fixImg.nii.gz
  moving image: .//tmp//movingImg.nii.gz
Dimension = 3
Number of stages = 1
Use Histogram Matching false
Winsorize image intensities false
Lower quantile = 0
Upper quantile = 1
Stage 1 State
   Image metric = MeanSquares
     Fixed image = Image (0271EA48)
  RTTI typeinfo:   class itk::Image<double,3>
  Reference Count: 2
  Modified Time: 1086
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 884
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [348, 512, 256]
  BufferedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [348, 512, 256]
  RequestedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [348, 512, 256]
  Spacing: [1, 1, 1]
  Origin: [0, 0, 0]
  Direction:
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix:
1 0 0
0 1 0
0 0 1

  PointToIndexMatrix:
1 0 0
0 1 0
0 0 1

  Inverse Direction:
1 0 0
0 1 0
0 0 1

  PixelContainer:
    ImportImageContainer (0268F8C8)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned long,double>
      Reference Count: 1
      Modified Time: 881
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 033EF020
      Container manages memory: true
      Size: 45613056
      Capacity: 45613056

     Moving image = Image (0271EDC8)
  RTTI typeinfo:   class itk::Image<double,3>
  Reference Count: 2
  Modified Time: 1087
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 1084
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [348, 512, 256]
  BufferedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [348, 512, 256]
  RequestedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [348, 512, 256]
  Spacing: [1, 1, 1]
  Origin: [0, 0, 0]
  Direction:
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix:
1 0 0
0 1 0
0 0 1

  PointToIndexMatrix:
1 0 0
0 1 0
0 0 1

  Inverse Direction:
1 0 0
0 1 0
0 0 1

  PixelContainer:
    ImportImageContainer (0268F910)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned long,double>
      Reference Count: 1
      Modified Time: 1081
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 19007020
      Container manages memory: true
      Size: 45613056
      Capacity: 45613056

     Weighting = 1
     Sampling strategy = none
     Number of bins = 32
     Radius = 4
     Sampling percentage  = 1
   Transform = BSplineSyN
     Gradient step = 0.1
     Update field sigma (voxel space) = 0
     Total field sigma (voxel space) = 0
     Update field time sigma = 0
     Total field time sigma  = 0
     Number of time indices = 0
     Number of time point samples = 0
Registration using 1 total stages.

Stage 0
  iterations = 200x200
  convergence threshold = 1e-06
  convergence window size = 10
  number of levels = 2
  using the MeanSquares metric (weight = 1)
  Shrink factors (level 1 out of 2): [8, 8, 8]
  Shrink factors (level 2 out of 2): [6, 6, 6]
  smoothing sigmas per level: [2, 1]
  Using default NONE metricSamplingStrategy
Exception Object caught:

itk::MemoryAllocationError (01CFD74C)
Location: "unknown"
File: d:\program files\itk\insighttoolkit-5.0.1\modules\core\common\include\itkImportImageContainer.hxx
Line: 199
Description: Failed to allocate memory for image.


```

If I input the original data, no bug and no output:
```

All_Command_lines_OK
Using double precision for computations.
  number of levels = 2
  fixed image: .//tmp//fixImg.nii.gz
  moving image: .//tmp//movingImg.nii.gz

```

**Comment by ntustison** [comment]
I'd be more than willing to look at your data to see if there's anything unusual but I suspect this is a system-specific issue.

**Comment by qiang-zhang-neu** [comment]
> I'd be more than willing to look at your data to see if there's anything unusual but I suspect this is a system-specific issue.

I have uploaded my data to [github](https://github.com/qiang-zhang-neu/lungRegistration).

**Comment by ntustison** [comment]
Thanks for uploading it.  Unfortunately, I can't reproduce the error for either this issue or the other issue.  When I run both of your scripts, they finish as expected.

**Comment by qiang-zhang-neu** [comment]
> Thanks for uploading it. Unfortunately, I can't reproduce the error for either this issue or the other issue. When I run both of your scripts, they finish as expected.

That's so weird. 
My environment is:
win 10 64 bit
vs 2015 64 bit

What else I can do to locate the error? Or could you please provide a tutorial to debug the code from VS?
