### ISSUE TITLE
some questions on Minboggle 101 atlas

### ISSUE THREAD

**Issue by BIG-S2** [ANTsX/ANTs#936]
I'm not sure shall I ask here. Someone told me that Minboggle 101 atlas has sulcus ROIs. But it seems that I can only calculate 101 gyrus/subcortical ROI's volumes from ANTs OASIS-TRT-20 joint fusion. Did anyone know are there sulcus ROI volumes in the labels of the training dataset OASIS-TRT-20? 

Thanks very much.

**Comment by ntustison** [comment]
Perhaps you should ask Arno Klein (@binarybottle).

**Comment by binarybottle** [comment]
When Mindboggle feature extraction and labeling software (mindboggle.info) is run on the Mindboggle-101 individual cortical surfaces, then you can get labeled sulci:

https://osf.io/yf8zn/
https://mindboggle.readthedocs.io/en/latest/#appendix-output
https://mindboggle.readthedocs.io/en/latest/labels.html

**Comment by BIG-S2** [comment]
Hi, binarybottle,
Thank you  for your help.
I can see that to get labeled sulci using Mindboggle software, to use Freesurfer first to get preprocessed results may be necessary. Is it correct?

**Comment by binarybottle** [comment]
Yes -- you can either run mindboggle123, which will also run FreeSurfer (and optionally ANTs), or recon-all and mindboggle separately. See https://mindboggle.readthedocs.io/en/latest/#run-one-command
