### ISSUE TITLE
git clone ITK failed

### ISSUE THREAD

**Issue by qiang-zhang-neu** [ANTsX/ANTs#938]
I am not sure whether it's a bug. 
My environment is:
win 10 64 bit
vs 2015 64 bit

When I compile ANTs and do not use the system ITK, the project would git clone ITK, and an error would be reported:
```
2>  Creating directories for 'ITKv5'
2>  Building Custom Rule C:/ANTs-master/ANTs/CMakeLists.txt
2>  Performing download step (git clone) for 'ITKv5'
2>  Cloning into 'ITKv5'...
2>fatal : read error : Invalid argument
2>  Cloning into 'ITKv5'...
2>fatal : read error : Invalid argument
2>  Cloning into 'ITKv5'...
2>fatal : read error : Invalid argument
2>  -- Had to git clone more than once:
2>            3 times.
2>  CMake Error at ITKv5-prefix/tmp/ITKv5-gitclone.cmake:31 (message):
2>    Failed to clone repository:
2>    'git://github.com/InsightSoftwareConsortium/ITK.git'
```
Then, I have a look at ITKv5-prefix/tmp/ITKv5-gitclone.cmake, and I find  the code for git clone is:
```

  execute_process(
    COMMAND "D:/Program Files/Git/cmd/git.exe"  clone --no-checkout "git://github.com/InsightSoftwareConsortium/ITK.git" "ITKv5"
    WORKING_DIRECTORY "D:/ANTsProjectError/bin"
    RESULT_VARIABLE error_code
    )
```
Actually, I find the code do not work in commond line:
`git clone --no-checkout "git://github.com/InsightSoftwareConsortium/ITK.git" "ITKv5"`
But the following code work:
`git clone --no-checkout "https://github.com/InsightSoftwareConsortium/ITK.git" "ITKv5"`

In fact, I have successfully built [SimpleElastix ](https://github.com/SuperElastix/SimpleElastix)project, in which the ITK should be git cloned. And I also have a look at the ITK-prefix/tmp/ITK-gitclone.cmake, and I find the code for git clone is:

```
  execute_process(
    COMMAND "D:/Program Files/Git/cmd/git.exe"  clone --no-checkout "https://github.com/InsightSoftwareConsortium/ITK.git" "ITK"
    WORKING_DIRECTORY "D:/SimpleElastix/Bin"
    RESULT_VARIABLE error_code
    )
```

Thus, I think that `"https://github.com/InsightSoftwareConsortium/ITK.git"` is correct. Please consider this report.

**Comment by gdevenyi** [comment]
The option to use HTTPS is already in the superbuild:
https://github.com/ANTsX/ANTs/blob/master/SuperBuild.cmake#L21-L24

It is also documented in the wiki:
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#compilation-starts-but-hangs-with-no-error-message

**Comment by cookpa** [comment]
I've updated the Wiki to make this clear. I guess some firewalls might reject outbound connections, causing an error message, while others just drop the packets, causing the build to hang.
