### ISSUE TITLE
ANTs + system ITK 5.1

### ISSUE THREAD

**Issue by crossmanith** [ANTsX/ANTs#940]
In order to build with system ITK 5.1 I had to change FileModeType to FileModeEnum and TransformCategoryType to TransformCategoryEnum. I've attached two patches instead of build logs because finally I could build ANTs successfully.

**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)
[x] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: Linux (Ubuntu)
 - OS version: 4.4.0-170-generic
 - Type of system: [Desktop, laptop, HPC cluster, cloud instance,
   other] desktop
 
**ANTs version**
commit a025d04

[0001-TransformType-TransformCategoryType-TransformType-Tr.patch.txt](https://github.com/ANTsX/ANTs/files/4098117/0001-TransformType-TransformCategoryType-TransformType-Tr.patch.txt)
[0002-FileModeType-FileModeEnum.patch.txt](https://github.com/ANTsX/ANTs/files/4098118/0002-FileModeType-FileModeEnum.patch.txt)

**Comment by ntustison** [comment]
Can you convert this to a pull request?

**Comment by crossmanith** [comment]
Some instructions how I can achieve this quickly?

**Comment by crossmanith** [comment]
fork + push to my fork and then new pull request?

**Comment by ntustison** [comment]
Yes

**Comment by crossmanith** [comment]
Done

**Comment by ntustison** [comment]
Thanks.  We'll wait for the travis builds before we merge.

**Comment by crossmanith** [comment]
As far as I can see, the first config in travis builds successfully but in the end there is some "deadline error message" which causes a failure for the build process. Anything I can do?
