### ISSUE TITLE
Issues using TimeVaryingBSplineVelocityField

### ISSUE THREAD

**Issue by andreaurru** [ANTsX/ANTs#942]
When I try to build the template using this option as transform, I get an error

Description: itk::ERROR: CommandLineParser(0x562c7f0): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert '12x12x12x2' to type 'j' as unsigned int

12x12x12x2 is the default size of the mesh grid. What should I do here?

Thank you

**Comment by ntustison** [comment]
The provided information is insufficient to diagnose.  We currently have a template for people to use when they open new issues in order to provide sufficient information for us to help debug.  Please follow that template.
