### ISSUE TITLE
DWI EPI correction

### ISSUE THREAD

**Issue by Adam123-png** [ANTsX/ANTs#949]
Hello all, my DWI input data set consists of 10 volumes of different b values. I want to perform an overall EPI distortion correction.

First of all I´m running affine registration (b0 image is the reference image and non b0 image is the moving image) in order to reduce the motion and eddy current distortion. Is that a right approach?

Moreover, I would like to reduce the geometric distortion and magnetic susceptibility induced distortions - does ANTs enable to perform these correction techniques? If so, which command is the best to use?

Thanks a lot in advance
Regards
Adam

**Comment by cookpa** [comment]
You might want to check out qsiprep, which uses ANTs and other tools for this use case

https://github.com/PennBBL/qsiprep

**Comment by Adam123-png** [comment]
Thanks for this link I will try to implement it.
