### ISSUE TITLE
build ANTs problem

### ISSUE THREAD

**Issue by GalaChen** [ANTsX/ANTs#950]
When I build ANTS in Ubuntu 16, terminal told following infromation:

`In file included from /home/chenxin/Documents/ANT/ANTsX-ANTs-a025d04/Examples/antsRegistrationTemplateHeader.cxx:1:0:
/home/chenxin/Documents/ANT/ANTsX-ANTs-a025d04/Examples/antsRegistrationTemplateHeader.h:21:58: fatal error: itkLabelImageGenericInterpolateImageFunction.h: there weren't exist that file
compilation terminated.
Examples/CMakeFiles/antsUtilities.dir/build.make:75: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o] Error 1
CMakeFiles/Makefile2:4673: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/all' failed
make[4]: *** [Examples/CMakeFiles/antsUtilities.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/ANTS.dir/build.make:114: recipe for target 'ANTS-prefix/src/ANTS-stamp/ANTS-build' failed
make[2]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
CMakeFiles/Makefile2:76: recipe for target 'CMakeFiles/ANTS.dir/all' failed
make[1]: *** [CMakeFiles/ANTS.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
`
Neither I use system ITK-5.0.1 nor ITK-5.1, I met this problem. 
By the way, when I compile ITK, I set the "Module-ITK_Review" ON.

So, how can I solve this problem?

**Comment by gdevenyi** [comment]
Please do not ignore the issue template. Provide all the information required.

**Comment by cookpa** [comment]
Can you try the SuperBuild with the defaults? It should build ITK successfully. See:

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

The example code on the Wiki shows how to get all the logs we need to debug problems. If it doesn't work, please open a new issue using the issue template, and provide all the information it asks for.
