### ISSUE TITLE
Automated container build on Dockerhub

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#951]
Moving this discussion to an issue for convenience.

Circleci is working! Thanks @ntustison, adding the deploy key fixed it.

It sees ANTsR etc, but doesn't build them. We could potentially add that later. 

To do:

1. Check the builds show up successfully on Docker hub at:

https://hub.docker.com/repository/docker/antsx/ants

2. Build Singularity image. @mattcieslak maybe we can look at this later?

3. Document the Docker page with a README, etc. I'll work on that when I get time. 

Beyond that:

a. Consider moving some / all Travis builds to to circleci?

b. Containers for ANTsPy, etc?

**Comment by dorianps** [comment]
Works ok on my Windows machine. A couple of comments:

1. Can you print some info on the version/tag installed, example here:
https://github.com/dorianps/docker/blob/master/ants/Dockerfile.ants#L48-L54
2. Would it perhaps be better if you add a non-privileged user instead of root? This is advised by many developers.
3. Do you want to include my Windows/Bash wrapper scripts to facilitate the container run, folder selection, etc? 
https://github.com/dorianps/docker/tree/master/ants
This way I don't need to keep anything on my side, all the tools are in ANTsX.

**Comment by cookpa** [comment]
@dorianps thanks for testing.

I think it would be best if we keep this automated container as minimal as possible. That way it can serve as a base layer for multiple projects that want to use ANTs.  

Maybe you could use automated container as a base layer, and add your customizations on top of that?

**Comment by dorianps** [comment]
@cookpa  That might work too. How often will the docker tags be created, is it at every commit? Or will you trigger docker creation manually?

**Comment by cookpa** [comment]
This container will update every time a commit is made to master, and it builds successfully.

**Comment by dorianps** [comment]
Thanks. And, forgot to ask, how will you tag them. By git commit, or date, or anything else?

**Comment by satra** [comment]
for other projects we tag using the following options:

master (built on every push to master)
laters (points to the last release)
release (points to the release)

when you set this up on dockerhub there is a place to manipulate the build configuration.

it's preferable to set up a bot github account (e.g., antsbot or antman if you prefer) to interact with dockerhub instead of a personal account. and you can give your core devs access to the bot account. this bit is a bit of a pain, but in the long run keeps things sane for external services.

**Comment by gdevenyi** [comment]
Definitely would like tagged releases in addition to master.

**Comment by satra** [comment]
this is a slightly more complex version, but this is how automated builds are configured on dockerhub.

![image](https://user-images.githubusercontent.com/184063/74675106-d76b0400-5180-11ea-8e38-2c151093328c.png)

**Comment by cookpa** [comment]
That's great, thank you @satra. I'll see what I can do with this.

**Comment by cookpa** [comment]
Hi all, I'm writing up a proposal to get some developer funding to advance ANTs containerization amongst other things. I've been looking online and I see a few ANTs containers about. I wanted to get the feedback of people in this thread and anyone else who may be interested. What would help make ANTs easier to use and to better integrate with other open source resources? 

I know a regular release schedule is a longstanding need, and that's definitely something I'd want to make happen.

Other than that, I was thinking a more organized DockerHub presence with an archive of releases, built for different platforms (suggestions for coverage welcome). 

An overhaul of testing seems obvious since we've had a couple of buggy releases lately.

I'd appreciate any feedback. I'm mostly thinking about containers and parallel processing at the minute, but happy to consider other topics (eg, BIDS apps, which I'm also interested in).

Thanks

**Comment by ntustison** [comment]
This is great, @cookpa .  Thanks.

**Comment by gdevenyi** [comment]
minc-toolkit uses a dockerized build system to make debs and rpms for all supported Centos, Ubuntu, and Debian releases, you can see our infrastructure here:
https://github.com/BIC-MNI/build_packages

It's not cloud-based yet, so I build it locally, but some kind of release infrastructure like this would be nice.

I would also probably provide a completely static build as an extractable tarball, built on the oldest centos, which is likely to work on all modern systems.

**Comment by dorianps** [comment]
Hi Phil,

For me, the number one priority would be to have ANTs as a BIDS app for
easy application on any BIDS dataset. Looks like there is an attempt to
BIDS-ify the cortical thickness pipeline, but I have not tried it, and I
don't know if it includes the longitudinal thickness/MALF pipeline:
https://github.com/ReproNim/containers

The second point then is a streamlined delivery of containers. I.e., for
fMRIprep it is a matter of few hours between a fix and the availability of
a new docker tag. It would be great if that interaction between user bug
report and fixes in ANTs is conveyed through docker images as well. The end
product needed by a user who works with reproducible approaches is most
likely the container. I am personally shifting to use containers for all
data processing, and use local software only for test runs. The difficulty
of keeping up with software changes is still a nightmare. I have seen
segmentation discrepancies between various builds of Freesurfer (even
same version) and ASHS. So, I keep the container with the data now, and run
it a new datasets if I need to merge data from multiple studies.

Dorian

**Comment by satra** [comment]
@cookpa - you've hit some of the key issues testing, releases. but @ntustison and @stnava have always told me ants is a framework, but people want some applications and how to configure ants tools to serve their specific need. so providing a way for guided tuning and having a set of applications ready to run for 80% use cases may be useful. and as an application, these ants derived scripts/tools could of course play nice with bids.

**Comment by cookpa** [comment]
Some great suggestions here that haven't been covered yet, notably BIDS, but at least a basic Docker build process is going on Github Actions. It should build tagged releases too when we can make those happen.
