### ISSUE TITLE
Apply Transform

### ISSUE THREAD

**Issue by Adam123-png** [ANTsX/ANTs#952]
Hello all,

I want to apply the saved transformation (a transformation matrix 4x4 acquired by registration of an anatomical and a diffusion image) on my input anatomical mask and change a final FOV by specifying a diffusion reference image (its voxels size). It means to apply the same command as the command ApplyXFM in FSL FLIRT. Does this option exist also in ANTS?

Thanks a lot
Regards
Adam

**Comment by ntustison** [comment]
You can use the affine transformation with a different reference image (see ``-r`` option) as long as it samples the same space.

**Comment by Adam123-png** [comment]
thanks a lot, it´s working.
