### ISSUE TITLE
Image registration quality assessment

### ISSUE THREAD

**Issue by Adam123-png** [ANTsX/ANTs#953]
Hello all,

I would like to assess the image registration (a rigid registration) quality performed in ANTS and FSL on the T1 and FLAIR images. Is there a way how to objectively evaluate the quality of image registration? Does any program enable to perform it? If so, which metric is used?

**Comment by ntustison** [comment]
That's an entire subfield of study.  There isn't a single solution so you'll have to do your own thinking about your specific application and how to best assess registration quality.

**Comment by Adam123-png** [comment]
OK. thanks for your answer.
