### ISSUE TITLE
Fix sharpening artifacts in template construction

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#956]
**Is your feature request related to a problem? Please describe.**

The Laplacian sharpening during template construction introduces an artifact near edges with large contrast gradients. In T1w templates this is most obvious as a bright fringe along the edge of the corpus callosum, adjacent to the lateral ventricles.

**Describe the solution you'd like**

A sharpening option that avoids this artifact, but still de-blurs the template acceptably.

**Describe alternatives you've considered**

There is an itkOptimalSharpeningFilter in ANTs/Utilities, but it has not been used in many years. Maybe one of the deconvolution filters in ITK could help?

**Additional context**

A template before and after the sharpening operation.

<img width="896" alt="average" src="https://user-images.githubusercontent.com/611507/75262906-3224e100-57bb-11ea-9079-b510f8247e52.png">
<img width="892" alt="sharpened" src="https://user-images.githubusercontent.com/611507/75262909-34873b00-57bb-11ea-8992-67a532b7d085.png">

**Comment by cookpa** [comment]
Inspired to revisit this by @ins0mniac2, who when I mentioned sharpening, immediately recognized it as a known problem in photography: the "halo effect".

**Comment by ntustison** [comment]
@cookpa --- I don't have a solution but I'd like to look more closely.  Can you post both those files?

**Comment by cookpa** [comment]
https://upenn.box.com/s/a9c0cns71pi07vq6c3y2imma3klrfown

Apologies for the size, it's a high resolution template.

For the unsharpened version I did ImageMath Normalize, then AverageImages without normalization / sharpening. Then I called ImageMath Sharpen, which uses the same Laplacian filter as AverageImages.

**Comment by ntustison** [comment]
Hey @cookpa ,

@stnava and I discussed this yesterday, specifically in the context of deep learning approaches.  I wanted to apply his [super resolution](https://github.com/ANTsXNet/MRISuperResolution) network to these images just to see the effects.  I'm attaching a screenshot in case you were interested.

[Superresolution.pdf](https://github.com/ANTsX/ANTs/files/4257323/Superresolution.pdf)

**Comment by stnava** [comment]
yes - that's one option.  another is training a new network to infer the best "mean" anatomy from the set of images.   this would be like a deep learning version of JIF - which is yet another option.

**Comment by ins0mniac2** [comment]
Meanwhile, can we get a user option to tune the sharpening ?

**Comment by cookpa** [comment]
@ins0mniac2 the ITK Laplacian filter doesn't seem to have options, we'd need to find another filter to use.

**Comment by stnava** [comment]
the old "optimal sharpening" filter was designed to do this .... it's a
trivial change to the itk filter that implements what's  called "blending"
ie I_original * wt + I_sharp * ( 1 - wt )

brian

**Comment by cookpa** [comment]
Thanks @stnava and @ntustison , of course the learning approaches have great potential. As an interim fix, the unsharp masking filter in ITK seems to be a reasonable compromise. I'll make a PR

<img width="2543" alt="image" src="https://user-images.githubusercontent.com/611507/75388466-0f75f380-58b3-11ea-80ba-932c84206ebf.png">

**Comment by stnava** [comment]
nice - looks reasonable

**Comment by cookpa** [comment]
Still testing, got a bit behind because ANTS was broken, but @ntustison has fixed that.

https://github.com/ANTsX/ANTs/pull/963

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/pull/963

@ins0mniac2 if you would like to try this out.

**Comment by gdevenyi** [comment]
@cookpa did you manage to test some settings here?

**Comment by cookpa** [comment]
Not really, I did a few experiments but I was having serious problems at the time as I was testing on 0.7mm T1w images and having a lot of problems related to memory and disk space.

Ballpark, the defaults aren't terrible but the tradeoff for not having the halo artifact is that the image doesn't get sharpened as much. I think amount = 0.7 and radius = 2vox is about right. Boosting the amount sharpens more but brings back some of the WM / ventricular brightness. It's not as bad as Laplacian though.

One way to play around is to run the template script with `-i 1 -k 1`. After it runs, you still have all the warped images. You can then average them, and compare the different sharpening options as I did in the image up thread.

But after that, of course it needs testing to see if it builds better templates over several iterations. 

It would be great if there was something more sophisticated that could dampen the sharpening where the intensity gradient is very strong. There is a threshold parameter in the unsharp mask but I think it does the opposite, it throws away small differences rather than the larger ones.

**Comment by cookpa** [comment]
I think this commit has the template scripts you'd need if you want to try it out

https://github.com/ANTsX/ANTs/pull/963/commits/8a277a6612ea3fe56af87f74409181168c952d1b

**Comment by cookpa** [comment]
@gdevenyi I've added the sharpening method as an option. I went back to the defaults for unsharp mask, as the whole point was to avoid halo artifacts, so I figure less is better. Fairly easily changed in the summarizeimageset function.
