### ISSUE TITLE
Qusetion of MeasureImageSimilarity

### ISSUE THREAD

**Issue by bheAI** [ANTsX/ANTs#958]
I use ANTs to register  the image from a.nii.gz to b.nii.gz, and get the new image b_scan.nii.gz. Then I have used MeasureImageSimilarity to measure similarity between 2 images (b.nii.gz and b_scan.nii.gz).
How many parameters of  similarity measurement are available?
three, 0, 1, 2?  (https://searchcode.com/codesearch/view/3400969/)
Or
four, 0 - MeanSquareDifference, 1 - Cross-Correlation, 2-Mutual Information , 3-SMI  ???

and 
my other problem is that MI value is a negative number, how should I interpretate these values (MI, CC...)?

**Comment by bheAI** [comment]
I use ANTs to register the image from a.nii.gz to b.nii.gz, and get the new image b_scan.nii.gz. Then I have used MeasureImageSimilarity to measure similarity between 2 images (b.nii.gz and b_scan.nii.gz).
How many parameters of similarity measurement are available?
three, 0, 1, 2? (https://searchcode.com/codesearch/view/3400969/)
Or
four, 0 - MeanSquareDifference, 1 - Cross-Correlation, 2-Mutual Information , 3-SMI ???(https://manpages.debian.org/experimental/ants/MeasureImageSimilarity.1.en.html)

and
my other problem is that MI value is a negative number, how should I interpretate these values (MI, CC...)?

**Comment by bheAI** [comment]
In particular, the result of MI value is negative and  CC  value is integer, how can we consider the registration result to be better.
thanks very much.

**Comment by bheAI** [comment]
But how should I interpretate these values (MI, CC...)? 
In particular, the result of MI value is negative and CC value is integer. 

1. The values obtained from different registration results with CC are all approximate to 0.98
MeasureImageSimilarity 3 1 image1.nii.gz image2.nii.gz {outimage.txt}
how can we consider the registration result to be better.

2. MI value is negative, the results are approximate to -0.6
MeasureImageSimilarity 3 1 image1.nii.gz image2.nii.gz {outimage.txt}
how can we consider the registration result to be better.

3. MeasureImageSimilarity 3 3 image1.nii.gz image2.nii.gz {outimage.txt} 
 this is error :
41419 Segmentation fault      (core dumped) MeasureImageSimilarity 3 3  image1.nii.gz image2.nii.gz

**Comment by ntustison** [comment]
@bheAI Please stop inundating the forum with multiple related requests.  We will get to your question as soon as we can.  

First things first, though.  You're using an old version of ``MeasureImageSimilarity``.  Please recompile a fresh checkout, try your experiments again, and then let us know of any questions you might have.

**Comment by bheAI** [comment]
> @bheAI Please stop inundating the forum with multiple related requests. We will get to your question as soon as we can.
> 
> First things first, though. You're using an old version of `MeasureImageSimilarity`. Please recompile a fresh checkout, try your experiments again, and then let us know of any questions you might have.





Tem_b0=Tem_b0.nii.gz
DTI_b0=DTI_b0.nii.gz
ANTS 3 -m CC[${Tem_b0},${DTI_b0},1,5] -o AtlasToTarget -t SyN[0.5] -r Gauss[3,0] -i 300x300x300 
WarpImageMultiTransform 3 ${Tem_b0} DTI_b0_scan.nii.gz -R ${DTI_b0} -i AtlasToTargetAffine.txt AtlasToTargetInverseWarp.nii.gz		
WarpImageMultiTransform 3 ${DTI_b0} Tem_b0_scan.nii.gz -R ${Tem_b0} AtlasToTargetWarp.nii.gz AtlasToTargetAffine.txt

example 1. 
MeasureImageSimilarity 3 1 ${Tem_b0} Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.5

output:
Tem_b0.nii.gz : DTI_b0.nii.gz => CC 0.987293
Only Implemented for MSQ and CC 
 targetvalue 0 metricvalue 0.987293 diff 0.987293 toler 0.5
 Failure? 1
 
example 2. 
 MeasureImageSimilarity 3 1 Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99
 
output:
Tem_b0.nii.gz : DTI_b0.nii.gz => CC 0.987293
Only Implemented for MSQ and CC 
 targetvalue 0 metricvalue 0.987293 diff 0.987293 toler 0.99
 Failure? 0
 
example 3. 
MeasureImageSimilarity 3 2 Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99

output:
Tem_b0.nii.gz : DTI_b0.nii.gz => MI -0.883133
Only Implemented for MSQ and CC 
 targetvalue 0 metricvalue -0.883133 diff -0.883133 toler 0.99
 Failure? 0
 
example 4. 
MeasureImageSimilarity 3 0 Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99

output:
Tem_b0.nii.gz : DTI_b0.nii.gz => MSQ 10.3884
Only Implemented for MSQ and CC 
 targetvalue 0 metricvalue 10.3884 diff 10.3884 toler 0.9
 Failure? 1
 
example 5.
MeasureImageSimilarity 3 3 Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99

output:
16826 Segmentation fault      (core dumped) MeasureImageSimilarity 3 3 Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99

So, My questions are:
Q1: How should I interpretate these values? 


Q2: Compared example 1. and 2., {target-value} and {epsilon-tolerance} could be setted by the experimenter. So What is the output value could suggest a resonable registration result?
For example 1. the output is CC 0.987293, so 0.987293 is good? 

Q3:  MeasureImageSimilarity ImageDimension whichmetric image1.ext image2.ext {logfile} {outimage.ext} {target-value} {epsilon-tolerance}

whichmetric=0,1,2,3, I tested different parameters, and the results were positive and negative, and some were very large (example 4=> MSQ 10.3884).What do these results mean? What kind of results suggest a good registration result?

Q4: Why example 5. is wrong?

thanks very much.

**Comment by bheAI** [comment]
********************************************************************
Sorry, I rearranged the question, thank you very much.
********************************************************************
Tem_b0=Tem_b0.nii.gz
DTI_b0=DTI_b0.nii.gz
ANTS 3 -m CC[${Tem_b0},${DTI_b0},1,5] -o AtlasToTarget -t SyN[0.5] -r Gauss[3,0] -i 300x300x300 
WarpImageMultiTransform 3 ${Tem_b0} DTI_b0_scan.nii.gz -R ${DTI_b0} -i AtlasToTargetAffine.txt AtlasToTargetInverseWarp.nii.gz		
WarpImageMultiTransform 3 ${DTI_b0} Tem_b0_scan.nii.gz -R ${Tem_b0} AtlasToTargetWarp.nii.gz AtlasToTargetAffine.txt

example 1. 
MeasureImageSimilarity 3 1 ${Tem_b0} Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.5

output:
Tem_b0.nii.gz : DTI_b0.nii.gz => CC 0.987293
Only Implemented for MSQ and CC 
 targetvalue 0 metricvalue 0.987293 diff 0.987293 toler 0.5
 Failure? 1
 
example 2. 
 MeasureImageSimilarity 3 1 ${Tem_b0} Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99
 
output:
Tem_b0.nii.gz : DTI_b0.nii.gz => CC 0.987293
Only Implemented for MSQ and CC 
 targetvalue 0 metricvalue 0.987293 diff 0.987293 toler 0.99
 Failure? 0
 
example 3. 
MeasureImageSimilarity 3 2 ${Tem_b0} Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99

output:
Tem_b0.nii.gz : DTI_b0.nii.gz => MI -0.883133
Only Implemented for MSQ and CC 
 targetvalue 0 metricvalue -0.883133 diff -0.883133 toler 0.99
 Failure? 0
 
example 4. 
MeasureImageSimilarity 3 0 ${Tem_b0} Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99

output:
Tem_b0.nii.gz : DTI_b0.nii.gz => MSQ 10.3884
Only Implemented for MSQ and CC 
 targetvalue 0 metricvalue 10.3884 diff 10.3884 toler 0.9
 Failure? 1
 
example 5.
MeasureImageSimilarity 3 3 ${Tem_b0} Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99

output:
16826 Segmentation fault      (core dumped) MeasureImageSimilarity 3 3 Tem_b0_scan.nii.gz Similarity2.txt Similarity2.nii.gz 0 0.99

So, My questions are:
Q1: How should I interpretate these values? 


Q2: Compared example 1. and 2., {target-value} and {epsilon-tolerance} could be setted by the experimenter. So What is the output value could suggest a resonable registration result?
For example 1. the output is CC 0.987293, so 0.987293 is good? 

Q3:  MeasureImageSimilarity ImageDimension whichmetric image1.ext image2.ext {logfile} {outimage.ext} {target-value} {epsilon-tolerance}

whichmetric=0,1,2,3, I tested different parameters, and the results were positive and negative, and some were very large (example 4=> MSQ 10.3884).What do these results mean? What kind of results suggest a good registration result?

Q4: Why example 5. is wrong?

thanks very much.

**Comment by ntustison** [comment]
I didn't make myself clear enough---please recompile your ANTs build with a fresh checkout.  If you don't know how to do that, please see [here](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS).  The problem is that your copy of ``MeasureImageSimilarity`` is outdated and I want to make sure you're up to date before we address your questions.  The following is the help menu which is printed when I type:

```
$ MeasureImageSimilarity

COMMAND: 
     MeasureImageSimilarity
          Program to calculate the similarity between two images using various metrics. 

OPTIONS: 
     -d, --dimensionality 2/3/4
          Dimensionality of the fixed/moving image pair. 

     -m, --metric CC[fixedImage,movingImage,metricWeight,radius,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  MI[fixedImage,movingImage,metricWeight,numberOfBins,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  Mattes[fixedImage,movingImage,metricWeight,numberOfBins,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  MeanSquares[fixedImage,movingImage,metricWeight,radius=NA,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  Demons[fixedImage,movingImage,metricWeight,radius=NA,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  GC[fixedImage,movingImage,metricWeight,radius=NA,<samplingStrategy={None,Regular,Random}>,<samplingPercentage=[0,1]>]
                  ICP[fixedPointSet,movingPointSet,metricWeight]
                  PSE[fixedPointSet,movingPointSet,metricWeight,<pointSetSigma=1>,<kNeighborhood=50>]
                  JHCT[fixedPointSet,movingPointSet,metricWeight,<pointSetSigma=1>,<kNeighborhood=50>,<alpha=1.1>,<useAnisotropicCovariances=1>]
          These image metrics are available--- CC: ANTS neighborhood cross correlation, 
          MI: Mutual information, Demons: (Thirion), MeanSquares, and GC: Global 
          Correlation. The "metricWeight" variable is not used. The metrics can also 
          employ a sampling strategy defined by a sampling percentage. The sampling 
          strategy defaults to 'None' (aka a dense sampling of one sample per voxel), 
          otherwise it defines a point set over which to optimize the metric. In addition, 
          three point set metrics are available: Euclidean (ICP), Point-set expectation 
          (PSE), and Jensen-Havrda-Charvet-Tsallis (JHCT). 

     -x, --masks fixedImageMask
                 [fixedImageMask,movingImageMask]
                 [fixedImageMask,NULL]
          Image masks to limit voxels considered by the metric. 

     -v, --verbose (0)/1
          Verbose output. 

     -o, --output gradientImage
          Output the metric gradient image (optional). 

     -h 
          Print the help menu (short version). 

     --help 
          Print the help menu. 
```

**Comment by namiranian** [comment]
hi,
I encounter inconsistent results using MeasureImageSimilarity with MI metric, ANTS version 2.3.4 (ITKv5), and ANTs version 2.1.0 (ITKv4). The old version calculates MI =-0.669661  while the recent version calculates MI= -0.479957 for the same images. 
Another problem with MeasureImageSimilarity (using recent version) is different results when the fixed and moving image replaced each other, is it true? (the old version as what is expected from MI definition, reports the same value for both situations.)

**Comment by ntustison** [comment]
Please post your images and the exact command call so that we can reproduce your results.

**Comment by ntustison** [comment]
Better yet, please don't re-open an old issue.  Instead, make a new issue with the requested information.
