### ISSUE TITLE
CT to MR registration

### ISSUE THREAD

**Issue by kurmukovai** [ANTsX/ANTs#959]
Hello, I am looking for a way to register MR image (FLAIR, T1/T1c) to a CT scan.
MR and CT are from the same person but images have different Affine Matrix ( rotation and shift) , pixel spacing and slice spacing. 

Could anyone suggest a method to do so? 

PS If there are any tutorials, manuals out there for such task, or anything it would be great. I do not want waste anyone's time, just can't find any answers for this:(

**Comment by ntustison** [comment]
There are several [examples](https://github.com/ANTsX/ANTs#learning-about-ants-examples-etc) on the ANTs website.

**Comment by cookpa** [comment]
`antsRegistrationSyNQuick.sh` is a good place to start. It will print an `antsRegistration` call that you can modify. It will align the images initially by their center of mass. If this doesn't work, you can try `antsAI` to search for an initial solution, which you can pass to `antsRegistration`.

**Comment by kurmukovai** [comment]
Thanks @ntustison , @cookpa, antsRegistratuinSynQuick.sh is doing the job! I just kinda curious it is said to use MI for histrogram matching, but I register MR on CT. How is that suppose to work? I mean, MR and CT have pretty different voxel intensities distribution. Or in the case of rigid registration it doesn't do any histogram matching and just learn transformation to align angle/position?
