### ISSUE TITLE
 installing ANTs from source

### ISSUE THREAD

**Issue by 921974496** [ANTsX/ANTs#964]
**When did the error occur?**
[Compilation (make)

**Build environment**
 - Linux
 - 18.04
 - Desktop
 

Windows Subsystem for Linux
 
**ANTs version**
git clone git://github.com/stnava/ANTs.git 

**Build configuration and logs**
Please attach the following files (relative to your build directory)

  - build.log (the terminal output from make)
  - CMakeCache.txt
  - CMakeFiles/CMakeError.log
  - CMakeFiles/CMakeOutput.log

**Additional context**
make -j 4
Error message：

 Fetching "http://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=d628681badc2cac83560501cd58b83b4&algorithm=MD5"
-- [download 100% complete]
-- Fetching "http://www.itk.org/files/ExternalData/MD5/d628681badc2cac83560501cd58b83b4"
-- [download 100% complete]
CMake Error at /usr/share/cmake-3.10/Modules/ExternalData.cmake:1121 (message):
  

  Object MD5=d628681badc2cac83560501cd58b83b4 not found at:

    file:////home/geng/ANTs/.ExternalData/MD5/d628681badc2cac83560501cd58b83b4 ("URL using bad/illegal format or missing URL")
    http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=d628681badc2cac83560501cd58b83b4 ("Timeout was reached")
    http://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=d628681badc2cac83560501cd58b83b4&algorithm=MD5 ("HTTP response code said error")
    http://www.itk.org/files/ExternalData/MD5/d628681badc2cac83560501cd58b83b4 ("HTTP response code said error")

Examples/TestSuite/CMakeFiles/ANTSFetchData.dir/build.make:340: recipe for target 'ExternalData/TestData/antsRegistrationTest_RigidAnisotropicMasks.result.nii.gz-hash-stamp' failed
make[5]: *** [ExternalData/TestData/antsRegistrationTest_RigidAnisotropicMasks.result.nii.gz-hash-stamp] Error 1
CMakeFiles/Makefile2:8822: recipe for target 'Examples/TestSuite/CMakeFiles/ANTSFetchData.dir/all' failed
make[4]: *** [Examples/TestSuite/CMakeFiles/ANTSFetchData.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/ANTS.dir/build.make:113: recipe for target 'ANTS-prefix/src/ANTS-stamp/ANTS-build' failed
make[2]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ANTS.dir/all' failed
make[1]: *** [CMakeFiles/ANTS.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gdevenyi** [comment]
File does exist here. http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=d628681badc2cac83560501cd58b83b4

Your firewall, or your internet connection is interfering, or slicer.kitware.com was done. Working fine now.

**Comment by 921974496** [comment]
I turned off the firewall and checked the network connection. The above problem still occurs.

**Comment by 921974496** [comment]
> File does exist here. http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=d628681badc2cac83560501cd58b83b4
> 
> Your firewall, or your internet connection is interfering, or slicer.kitware.com was down. Working fine now.

I turned off the firewall and checked the network connection. The above problem still occurs.

**Comment by 921974496** [comment]
> File does exist here. http://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=d628681badc2cac83560501cd58b83b4
> 
> Your firewall, or your internet connection is interfering, or slicer.kitware.com was down. Working fine now.

make -j 4 
[ 47%] Built target ITKv5
[ 52%] Performing forcebuild step for 'ANTS'
[ 58%] Performing build step for 'ANTS'
[ 13%] Built target ANTSFetchData
[ 13%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o
[ 13%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DFloat.cxx.o
[ 14%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DDouble.cxx.o
[ 14%] Building CXX object Examples/CMakeFiles/antsUtilities.dir/antsRegistration3DDouble.cxx.o
In file included from /home/geng/ANTs/Examples/antsRegistration2DDouble.cxx:1:0:
/home/geng/ANTs/Examples/antsRegistrationTemplateHeader.h:21:10: fatal error: itkLabelImageGenericInterpolateImageFunction.h: 没有那个文件或目录
 #include "itkLabelImageGenericInterpolateImageFunction.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Examples/CMakeFiles/antsUtilities.dir/build.make:110: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DDouble.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DDouble.cxx.o] Error 1
make[5]: *** 正在等待未完成的任务....
In file included from /home/geng/ANTs/Examples/antsRegistrationTemplateHeader.cxx:1:0:
/home/geng/ANTs/Examples/antsRegistrationTemplateHeader.h:21:10: fatal error: itkLabelImageGenericInterpolateImageFunction.h: 没有那个文件或目录
 #include "itkLabelImageGenericInterpolateImageFunction.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/geng/ANTs/Examples/antsRegistration3DDouble.cxx:1:0:
/home/geng/ANTs/Examples/antsRegistrationTemplateHeader.h:21:10: fatal error: itkLabelImageGenericInterpolateImageFunction.h: 没有那个文件或目录
 #include "itkLabelImageGenericInterpolateImageFunction.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Examples/CMakeFiles/antsUtilities.dir/build.make:86: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o] Error 1
Examples/CMakeFiles/antsUtilities.dir/build.make:158: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/antsRegistration3DDouble.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistration3DDouble.cxx.o] Error 1
In file included from /home/geng/ANTs/Examples/antsRegistration2DFloat.cxx:1:0:
/home/geng/ANTs/Examples/antsRegistrationTemplateHeader.h:21:10: fatal error: itkLabelImageGenericInterpolateImageFunction.h: 没有那个文件或目录
 #include "itkLabelImageGenericInterpolateImageFunction.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Examples/CMakeFiles/antsUtilities.dir/build.make:134: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DFloat.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DFloat.cxx.o] Error 1
CMakeFiles/Makefile2:6208: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/all' failed
make[4]: *** [Examples/CMakeFiles/antsUtilities.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/ANTS.dir/build.make:113: recipe for target 'ANTS-prefix/src/ANTS-stamp/ANTS-build' failed
make[2]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ANTS.dir/all' failed
make[1]: *** [CMakeFiles/ANTS.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by 921974496** [comment]
In file included from /home/geng/ANTs/Examples/antsRegistration2DDouble.cxx:1:0:
/home/geng/ANTs/Examples/antsRegistrationTemplateHeader.h:21:10: fatal error: itkLabelImageGenericInterpolateImageFunction.h: 没有那个文件或目录
 #include "itkLabelImageGenericInterpolateImageFunction.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/geng/ANTs/Examples/antsRegistration2DFloat.cxx:1:0:
/home/geng/ANTs/Examples/antsRegistrationTemplateHeader.h:21:10: fatal error: itkLabelImageGenericInterpolateImageFunction.h: 没有那个文件或目录
 #include "itkLabelImageGenericInterpolateImageFunction.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/geng/ANTs/Examples/antsRegistration3DDouble.cxx:1:0:
/home/geng/ANTs/Examples/antsRegistrationTemplateHeader.h:21:10: fatal error: itkLabelImageGenericInterpolateImageFunction.h: 没有那个文件或目录
 #include "itkLabelImageGenericInterpolateImageFunction.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/geng/ANTs/Examples/antsRegistrationTemplateHeader.cxx:1:0:
/home/geng/ANTs/Examples/antsRegistrationTemplateHeader.h:21:10: fatal error: itkLabelImageGenericInterpolateImageFunction.h: 没有那个文件或目录
 #include "itkLabelImageGenericInterpolateImageFunction.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
Examples/CMakeFiles/antsUtilities.dir/build.make:110: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DDouble.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DDouble.cxx.o] Error 1
make[5]: *** 正在等待未完成的任务....
Examples/CMakeFiles/antsUtilities.dir/build.make:86: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistrationTemplateHeader.cxx.o] Error 1
Examples/CMakeFiles/antsUtilities.dir/build.make:134: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DFloat.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistration2DFloat.cxx.o] Error 1
Examples/CMakeFiles/antsUtilities.dir/build.make:158: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/antsRegistration3DDouble.cxx.o' failed
make[5]: *** [Examples/CMakeFiles/antsUtilities.dir/antsRegistration3DDouble.cxx.o] Error 1
CMakeFiles/Makefile2:6208: recipe for target 'Examples/CMakeFiles/antsUtilities.dir/all' failed
make[4]: *** [Examples/CMakeFiles/antsUtilities.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/ANTS.dir/build.make:113: recipe for target 'ANTS-prefix/src/ANTS-stamp/ANTS-build' failed
make[2]: *** [ANTS-prefix/src/ANTS-stamp/ANTS-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ANTS.dir/all' failed
make[1]: *** [CMakeFiles/ANTS.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gdevenyi** [comment]
You are building against an external ITK and have not build the GenericLabel module:
https://github.com/ANTsX/ANTs/blob/master/SuperBuild/External_ITKv5.cmake#L131

This is not a recommended configuration for ANTs.

May I suggest you investigate the docker container or binary releases since you're having difficulties.

**Comment by cookpa** [comment]
Or you can try the Superbuild:

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

This will get the correct ITK version and configure it
