### ISSUE TITLE
change 0GenericAffine.mat

### ISSUE THREAD

**Issue by luckyxiaoqi** [ANTsX/ANTs#967]
I got 0GenericAffine.mat,and then changed the value of ‘AffineTransform_double_3_3'and 'fixed' to generate more affine images. After changed the value,I save the dict as another 0GenericAffine1.mat file. But when I use antsApplyTransform to generate .wraped.nii.gz file ,it come to a error :failed to read file 0GenericAffine1.mat. 
I read the 0GenericAffine.mat and 0GenericAffine1.mat ,then I found the first file doesn't have these keys such as '__globals__','__header__' which are necessary keys for .mat.
I want to ask you why your 0GenericAffine.mat doesn't have these keys such as '__globals__','__header__'

**Comment by ntustison** [comment]
I believe you're operating under the assumption that these .mat files are [matlab files](https://www.reviversoft.com/file-extensions/mat).    This is not the case.  They're actually an ITK-specific file format that has nothing to do with this other file type.

**Comment by luckyxiaoqi** [comment]
Thanks,I got it.
could you tell me how to read and save the .mat file using python version of itk? 
Thanks

**Comment by luckyxiaoqi** [comment]
I know how to do it .Thanks
