### ISSUE TITLE
Morphological operations

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTs#968]
Hey, just wondering if anybody knows anything about this particular implementation quirk of certain morphological operators in ``ImageMath``.  If one takes a look at the [relevant code](https://github.com/ANTsX/ANTs/blob/master/Examples/antsUtilities.h#L156-L190) in ``antsUtilities.h``, one can see that the dilate and erode operations are as expected but the open and close operations are composites of dilate and erode which actually produce different results from the open and close ITK filters.  For example, the main image below is the ``ImageMath`` version of "closing" (white = 1, black = 0) of the binary segmentation mask shown in red.

<img width="1080" alt="Screen Shot 2020-03-16 at 8 21 03 PM" src="https://user-images.githubusercontent.com/324811/76819066-79076480-67c4-11ea-8778-731c0d219ac7.png">

**Comment by cookpa** [comment]
Can you upload your mask? I can't seem to reproduce this on 

```
antsRegistration --version
ANTs Version: 2.3.1.dev23-gc3466
Compiled: Sep 29 2019 13:40:29
```

**Comment by ntustison** [comment]
Sure.  I'm guessing a pipeline issue but, regardless, I'm compiling a pull request now.  

```
$ antsRegistration --version
ANTs Version: 3.0.0.0.dev109-g8d278
Compiled: Sep  8 2019 09:22:03
```

[r16mask.nii.gz](https://github.com/ANTsX/ANTs/files/4346545/r16mask.nii.gz)

**Comment by cookpa** [comment]
Oh  yes, now I see the problem. The crazy floating point values make it look normal when loaded as a segmentation in SNAP

**Comment by ntustison** [comment]
@cookpa Thanks for checking this.

**Comment by gdevenyi** [comment]
I have been using iMath for these sorts of operations. Which is considered the "supported" implementation?

**Comment by ntustison** [comment]
If I remember correctly @jeffduda started ``iMath`` as a long term project to eventually subsume all of ``ImageMath`` functionality in a more organized fashion.  Obviously, that is going to take quite some time so, for the time being, both implementations are "supported."
