### ISSUE TITLE
Apply the transformation matrix from antsRegistratoinSyN does not work

### ISSUE THREAD

**Issue by danwu-bme** [ANTsX/ANTs#969]
Dear Expert,

I am using the "antsRegistratoinSyNQuick" script and the transformation works pretty well. However, when I tried to use the transformation matrix to co-coregister an image from subject space to atlas space, it did not work. For instance,
./antsRegistrationSyNQuick.sh -d 3 -f refImg.nii -m movImg.nii -o sj -n 4 -r 128 -j 1
It generates sjWarped.nii.gz, sj1Warp.nii.gz, etc. But when I apply the transformation matrix to the original image
antsApplyTransforms -i movImg.nii-r refImg.nii-o warpedImg.nii-t transMatrix
warpedImg.nii is not the same as sjWarped.nii.gz. Instead, warpedImg.nii was very similar to movImg.img.
Is there something wrong with the way apply the transformation matrix? Could you instruct the correct way to do it?

Thanks a lot,
Dan Wu

**Comment by ntustison** [comment]
Please post the actual commands and output.  This command 

```
antsApplyTransforms -i movImg.nii-r refImg.nii-o warpedImg.nii-t transMatrix
```

as written wouldn't work.

**Comment by danwu-bme** [comment]
Thanks for the quick response. Here is my actual command.

**Comment by danwu-bme** [comment]
Thanks for the quick response! Here is my actual code. 
for file1 in ${document}
do
{
    filename=/home/danwu/Documents/ISH_registration/LDDMM_result/E11.5/${file1}/
    movImg=${filename}"LDDMM_colormap2grey_cropped.nii"
    refImg=${filename}"template_cropped.nii"
    movColormap1=${filename}"LDDMM_colormap_ch1.nii"
    movColormap2=${filename}"LDDMM_colormap_ch2.nii"
    movColormap3=${filename}"LDDMM_colormap_ch3.nii"
    outColormap1=${filename}"warped_colormap_ch1.nii"
    outColormap2=${filename}"warped_colormap_ch2.nii"
    outColormap3=${filename}"warped_colormap_ch3.nii"
    transMatrix=${filename}"sj1Warp.nii.gz"

    /home/danwu/Documents/ISH_registration/antsRegistrationSyNQuick.sh -d 3 -f ${refImg} -m ${movImg} -o sj -n 4 -r 128 -j 1
    antsApplyTransforms -i ${movColormap1} -r ${refImg} -o ${outColormap1} -t ${transMatrix}
    antsApplyTransforms -i ${movColormap2} -r ${refImg} -o ${outColormap2} -t ${transMatrix}
    antsApplyTransforms -i ${movColormap3} -r ${refImg} -o ${outColormap3} -t ${transMatrix}
}&
done
wait

**Comment by ntustison** [comment]
Thanks.  So the output of your ``antsRegistrationSyNQuick.sh`` call comprises an affine matrix, ``${filename}sj0GenericAffine.mat``, and a displacement field pair ``${filename}sj1Warp.nii.gz`` and ``${filename}sj1InverseWarp.nii.gz``.  You have to apply both the affine and deformable part to reproduce the total transformation:

```
antsApplyTransforms -i ${movColormap1} -r ${refImg} -o ${outColormap1} -t ${filename}sj1Warp.nii.gz -t ${filename}sj0GenericAffine.mat
```

**Comment by danwu-bme** [comment]
Thank you so much! It works now :)
