### ISSUE TITLE
USE_VTK=ON but not building certain functions

### ISSUE THREAD

**Issue by Xin-Ma-1** [ANTsX/ANTs#972]
Before opening an issue, please review the build documentation here

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

If you are building the latest code snapshot, please also check Travis
to see if the code is building successfully

https://travis-ci.org/ANTsX/ANTs

If you are using system ITK or VTK, please verify you have the correct
versions (see the Wiki link above). If you can, please also attempt a
Superbuild and let us know if that compiles successfully.

**When did the error occur?**
The process went through but certain functions were missing, such as antsSurf.

**Build environment**
 - OS: Linux
 - OS version: 3.10.0-693.21.1.e17.x86-64
 - Type of system: HPC cluster
 
**ANTs version**
I built it this morning Mar 18, 2020. The installed version is 2.3.1.dev128-g65a3f.

**Build configuration and logs**
Please attach the following files (relative to your build directory)

[build.log](https://github.com/ANTsX/ANTs/files/4350717/build.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/4350718/CMakeCache.txt)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/4350719/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/4350720/CMakeOutput.log)

**Additional context**
This is the shell file I used:
[install.txt](https://github.com/ANTsX/ANTs/files/4350759/install.txt)

**Comment by gdevenyi** [comment]
You have not provided any description of the actual problem you're encountering.

**Comment by Xin-Ma-1** [comment]
Basically the building and installation process went through but I did not see VTK installed and certain functions related to it were missing, such as antsSurf. If you can help me check the options I chose for cmake and let me know which part went wrong, or maybe some other parts in the shell command went wrong, it would be very helpful!

**Comment by cookpa** [comment]
From CMakeCache.txt:

```
//Build tools that depend on VTK
USE_VTK:BOOL=OFF
```

I think you need to add -D to your options, eg:

```
   -DUSE_SYSTEM_ITK=OFF \
   -DUSE_SYSTEM_VTK=OFF \
   -DUSE_VTK=ON \
```

The first thing you should see when you make is

```
Scanning dependencies of target VTK
[  4%] Creating directories for 'VTK'
[  8%] Performing download step (git clone) for 'VTK'
Cloning into 'VTK'...
```

**Comment by Xin-Ma-1** [comment]
Simple solution but worked perfect for me. Thanks to you both for the help!

**Comment by Xin-Ma-1** [comment]
Now I encountered a new problem. I tried to run antsSurf command but got into error. There were three types of error messages I received:

1. ERROR: In /home/xma72/ants/build/VTK/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 754
vtkXOpenGLRenderWindow (0x4142630): Unable to find a valid OpenGL 3.2 or later implementation. Please update your video card driver to the latest version. If you are using Mesa please make sure you have version 11.2 or later and make sure your driver in Mesa supports OpenGL 3.2 such as llvmpipe or openswr. If you are on windows and using Microsoft remote desktop note that it only supports OpenGL 3.2 with nvidia quadro cards. You can use other remoting software such as nomachine to avoid this issue.

2. ERROR: In /home/xma72/ants/build/VTK/Rendering/OpenGL2/vtkShaderProgram.cxx, line 446
vtkShaderProgram (0x452d640): 1: #version 150

3. ERROR: In /home/xma72/ants/build/VTK/Rendering/OpenGL2/vtkShaderProgram.cxx, line 447
vtkShaderProgram (0x452d640): 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Does this mean my installed VTK is not fully functioning and my system is not compatible? Any help would be appreciated!

**Comment by gdevenyi** [comment]
Are you running a non standard Unix system such a WSL?

**Comment by cookpa** [comment]
I'm pretty sure this is a VTK issue and not an ANTs issue. 

You might get some information by running:

VTK-build/bin/vtkProbeOpenGLVersion 

You can also ask the VTK folks for help. Be sure to include all information about your system, not just kernel version but what distribution (Ubuntu, CentOS etc) and whether it is a native or virtual environment. 

The VTK version you would have built with a SuperBuild today is v8.2.0.

**Comment by Xin-Ma-1** [comment]
@gdevenyi I was building on my school's HPC cluster under my folder. That may limit my authorization to some functions. Do you think it can cause problem?

**Comment by gdevenyi** [comment]
I believe antsSurf tries to generate an OpenGL visualization. You're using a remote ssh session which probably won't work.

You should contact your cluster support for help in how to handle visualization.

**Comment by Xin-Ma-1** [comment]
@gdevenyi I am using Putty and connected to Xming. Would this setting work? Or I may need other ways to view OpenGL visualization?

**Comment by gdevenyi** [comment]
This question is beyond the scope of supporting ANTs, you will need to contact your cluster support staff

**Comment by cookpa** [comment]
Yes, it's probably not even a VTK issue, it's about rendering OpenGL remotely. If you can get glxgears running correctly, then other programs should work too.

**Comment by Xin-Ma-1** [comment]
@cookpa glxgears can run successfully. I will contact the cluster support team tomorrow. Thank you!

**Comment by cookpa** [comment]
Going to close as I don't think there's anything to do on the ANTs side. Feel free to comment again if you want to share a solution later.
