### ISSUE TITLE
antsSliceRegularizedRegistration: Larger OSX-Linux difference in recent build

### ISSUE THREAD

**Issue by jcohenadad** [ANTsX/ANTs#976]
Hi, while investigating an [issue related to slow processing time on some systems](https://github.com/neuropoly/spinalcordtoolbox/issues/947), I recently re-built ANTs binaries on Ubuntu 16.04 and OSX. Good news is: processing time is **much** faster with the recent built on Ubuntu 16.04:

### ANTs Version: 2.3.1.dev145-g7ed2b
~~~
time antsSliceRegularizedRegistration -t 'Translation[0.5]' -m 'MeanSquares[dest_RPI_crop.nii,src_reg_crop.nii,1,4,Regular,0.2]' -p 5 -i 50 -f 1 -s 0 -v 1 -o '[step1,src_reg_crop_regStep1-new.nii]'
Loop0 polyerr: 0.0995983 image-metric 0.225547
Loop1 polyerr: 0.00827533 image-metric 0.225138

real	0m4.414s
user	0m24.775s
sys	0m12.730s
~~~

### ANTs Version: 2.1.0.post359-g3df42
~~~
time antsSliceRegularizedRegistration -t 'Translation[0.5]' -m 'MeanSquares[dest_RPI_crop.nii,src_reg_crop.nii,1,4,Regular,0.2]' -p 5 -i 50 -f 1 -s 0 -v 1 -o '[step1,src_reg_crop_regStep1.nii]'
Loop0 polyerr: 0.139908 image-metric 0.226171
 polyx -0.496811 1.50435 -0.990867 -0.177755 0.221031 iceptx 0.0654782
 polyy -1.83812 12.1132 -25.9729 23.1219 -7.39511 icepty -0.0206768
Loop1 polyerr: 0 image-metric 0.226171
 polyx -0.496811 1.50435 -0.990867 -0.177755 0.221031 iceptx 0.0654782
 polyy -1.83812 12.1132 -25.9729 23.1219 -7.39511 icepty -0.0206768

real	1m5.092s
user	0m43.118s
sys	2m8.049s
~~~

However, there is a **much** larger difference in results between OSX and Linux for the more recent version. Version `2.1.0.post359-g3df42` shows a difference at the 10^-14 decimal while version `2.3.1.dev145-g7ed2b` shows a difference at the 10^-2 decimal. See example for the first three lines of the Tx params:

### ANTs Version: 2.3.1.dev145-g7ed2b
OSX | Linux
------------ | -------------
0.0510465709765176 | 0.064159965052827
-0.00246455359150863 | 0.000141873553017993
-0.0411416921788 | -0.0435655048206819

### ANTs Version: 2.1.0.post359-g3df42
OSX | Linux
------------ | -------------
0.0498505333483797 | 0.0498505333483799
-0.00060664358328652 | -0.000606643583286381
-0.0348264242930449 | -0.034826424293045

Data + Full Results here: 
[antsSliceRegularizedRegistration.zip](https://github.com/neuropoly/spinalcordtoolbox/files/4366324/antsSliceRegularizedRegistration.zip)

I was wondering if this is a known behaviour and if you have some clues about what could have introduced such larger discrepancies in the more recent build.

Thanks for your insights!

**Comment by cookpa** [comment]
What's the test-retest difference on each platform? It's possible that successive runs on the same platform are also more variable than they used to be.

**Comment by jcohenadad** [comment]
ah! Good catch. Indeed, successive testing yields different results. See below first row for Tx:
~~~
0.0699915216915313
0.0660665386223871
0.0425164161621468
0.0442404901924251
0.0641184696378914
~~~

Which is not expected given that the samplingStrategy was set `Regular` instead of `Random`. Full syntax:
~~~
time antsSliceRegularizedRegistration -t 'Translation[0.5]' -m 'MeanSquares[dest_RPI_crop.nii,src_reg_crop.nii,1,4,Regular,0.2]' -p 5 -i 50 -f 1 -s 0 -v 1 -o '[step1,src_reg_crop_regStep1.nii]'
~~~

**Comment by gdevenyi** [comment]
Regular includes a random perturbation on the grid sampling

**Comment by cookpa** [comment]
> Regular includes a random perturbation on the grid sampling

Correct, but this has been the case for some time.

More discussion here

https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues

**Comment by jcohenadad** [comment]
additional info: when setting `samplingPercentage` to 1 (instead of 0.2 previously), I also get a non-null variance on the results.

**Comment by gdevenyi** [comment]
I think the proper way to specify dense sampling is "None", rather than Regular,1.0

**Comment by stnava** [comment]
also, for reproducibility, one should set the ants seed and nthreads to 1.

**Comment by cookpa** [comment]
> also, for reproducibility, one should set the ants seed and nthreads to 1.

Thanks @stnava - I'm not sure if this program supports a fixed random seed, but if not it probably should.

Single threading will also remove another source of precision loss, though in my experiments linked above, it was a much smaller delta than the random sampling variation.

**Comment by jcohenadad** [comment]
> also, for reproducibility, one should set the ants seed and nthreads to 1.

Yes, these env variables were already set properly.

> I think the proper way to specify dense sampling is "None", rather than Regular,1.0

That worked! Thanks a lot. I would suggest to add this option in the usage:
`samplingStrategy={Regular,Random}` --> `samplingStrategy={Regular,Random,None}`

**Comment by cookpa** [comment]
I updated the usage (https://github.com/ANTsX/ANTs/commit/ea5a7f16ebd9e8dd2d5ca9d878698f55a6f715a2). 

Wiki page for metric sampling strategies

https://github.com/ANTsX/ANTs/wiki/antsRegistration-metric-sampling-strategies

**Comment by cookpa** [comment]
Closing for now, feel free to re-open if there's additional questions
