### ISSUE TITLE
Number of Threads?

### ISSUE THREAD

**Issue by djk-milab** [ANTsX/ANTs#979]
When using antsRegistrationSynQuick.sh, I found out there is an option for the number of threads by -n #. I tried from default to 8, 16, 32, 64, and found out while default was the slowest (Total elapsed time: 361.1), and -n 8 and 16 were the fastest (Total elapsed time: 176.3 and Total elapsed time: 176.5 ), not 64 (Total elapsed time: 217.7) nor 32 (Total elapsed time: 197.2). Am I using correctly?

**Comment by cookpa** [comment]
https://en.wikipedia.org/wiki/Multithreading_(computer_architecture)

Multi-threading takes advantage of parallelism, but there are limits to how much a problem can be parallelized until either the CPUs run out of capacity or the cost of handling the threads offsets the speed advantage of parallel processing.

Also, if you have many jobs to run, you have to decide if it's better to run a few jobs with many threads or process more jobs with fewer threads. This may also be limited by available memory.
