### ISSUE TITLE
Issue with my registration using AntsRegistrationSyN.sh

### ISSUE THREAD

**Issue by natsunami** [ANTsX/ANTs#982]
Hello everyone,

 I am new to ANTs, I have performed a registration T2 to T1 on my subjects using AntsRegistrationSyN.sh with an affine transform:

antsRegistrationSyNQuick.sh -d 3 -t sr -o tse_to_t1_ants2.nii.gz  -f t1_skull_stripped.nii.gz -m tse.nii.gz  

It performed well on many subjects but some of them failed...You will find attached the data  of one subject whose registration didn't work :

https://drive.google.com/file/d/1wISSx5wGjVYyiOndkE33JkccsTYDE0Q9/view?usp=sharing

 I would be very grateful for any insights concerning what could lead to this failed registration.

Thank you for our help!

**Comment by ntustison** [comment]
The slice thickness looks incorrect for the tse image.  Are you sure the specified voxel dimensions are correct?  Also, you might want to look at this [example](https://github.com/ntustison/PartialSlabEpiT1ImageRegistration) which shares some characteristics with your problem.

**Comment by tina-ebi** [comment]
Hi There,
I want to use ANTs for non-linear registration. But I do not know how I should run  antsRegistrationSyN.sh. Is it through using the terminal in Linux?
Thank you for any help.

**Comment by ntustison** [comment]
You should follow some of the examples in the README.md.  But, yes, after installing ANTs, you should be able to use it through the terminal in Linux or other comparable platforms.
