### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTs#984]
For purely selfish reasons, as we are transitioning to a more centralized cluster system where the admins like to install things, and it's easier to have numbered releases.

v2.3.3 sample release notes:

- Unsharp mask filter added to ImageMath

- Bug fixes for ImageMath morphological operators

- Command line arg bug fixes and improvements for N3BiasFieldCorrection, antsRegistration, antsApplyTransforms, antsMotionCorr

- Option to install libraries only for more compact ANTsR builds

- Multiple code updates for C++11

**Comment by gdevenyi** [comment]
Yes please.

**Comment by cookpa** [comment]
@stnava I'm seeing the 2.3.3 release as a tag, but not a release. Maybe it's still in draft mode?

<img width="911" alt="image" src="https://user-images.githubusercontent.com/611507/83360886-b48ce600-a352-11ea-960f-2c862517aa69.png">

Also, minor point, but could we choose a different name? Mostly because I'm tired of seeing the c-word, but also not wanting to bring up false positives in Google. We can keep iterating through the ant genera with Leptomyrmex. Apologies to anyone attempting to search the study of ants with ANTs.

**Comment by cookpa** [comment]
I see the release now, thanks @stnava

**Comment by gdevenyi** [comment]
Release tag has a pretty critical bug, compare master vs release...
https://github.com/ANTsX/ANTs/compare/v2.3.3...master

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/commit/8c61a430099e9d5ba580b7255132cfa58a7ee880

**Comment by cookpa** [comment]
Oh yes. I thought the tag was not affected but I must have been looking in the wrong place.

**Comment by cookpa** [comment]
OK, what to do now? I can try to move the tag to the current HEAD commit, but I'm not sure what that will do to the release

**Comment by gdevenyi** [comment]
Releases can be deleted as far as I know? Not sure. Either that or do 2.3.4.

**Comment by cookpa** [comment]
Ok yes that seems easiest

Sent from my iPhone

On Jun 1, 2020, at 1:10 PM, Gabriel A. Devenyi <notifications@github.com> wrote:

﻿

Releases can be deleted as far as I know? Not sure. Either that or do 2.3.4.

**Comment by cookpa** [comment]
OK I updated to the latest master, without the bug. Thanks @gdevenyi 

I thought I saw a delete release button somewhere at some point, but I could not find it. But I have marked the previous two buggy releases as "pre-releases".
