### ISSUE TITLE
color map change, add color bar

### ISSUE THREAD

**Issue by Adam123-png** [ANTsX/ANTs#985]
Hello all,

I did the post-processing on brain images in ANTs. I changed the color coding to display where MR signals values are higher or lower. I need to add the color bar onto the image in order to easily identify what "blue" or "red" color means. Please, in which program is it possible to change the color map and to add the color bar as well? I tried to implement it in ITK-SNAP but the option of adding the color bar is not implemented there. Do some affiliate programs to ANTs enable to do that?

Thanks a lot
Regards
Adam

**Comment by ntustison** [comment]
One can perform color mapping using the program ``ConvertScalarImageToRgb`` but you'll have to add your own color bar.

**Comment by Adam123-png** [comment]
And is it possible to create and display the color scale?

**Comment by ntustison** [comment]
Sure.  If you can create a grayscale version of your colorbar, you can pass it through the same program.

**Comment by Adam123-png** [comment]
I was trying to create the colorbar in ITK-SNAP but this option might bot be implemented. In which program is it possible to create the colorbar?

**Comment by ntustison** [comment]
I'm not sure.  Perhaps gimp or some other photo editing program.
