### ISSUE TITLE
How start to run antsregistrationSyN.sh code?

### ISSUE THREAD

**Issue by tina-ebi** [ANTsX/ANTs#986]
I have installed ANTs from source code on Linux according to this website: https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS. 
Now, I do not know how I can run antsregistrationSyN.sh. I cannot find any video or text about guiding the running of antsregistrationSyN.sh code. How I can run this code?
your help will be grateful.

**Comment by cookpa** [comment]
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#post-installation-set-environment-variables-path-and-antspath

**Comment by tina-ebi** [comment]
Dear Philip,
Thank you very much. I have tried to run my script (antscommandreg) according to that link you sent me. But it is giving an error:
tinaeb@tinaeb-VirtualBox:~$ export ANTSPATH=/home/tinaeb/install/bin/
tinaeb@tinaeb-VirtualBox:~$ export PATH=${ANTSPATH}:$PATH
tinaeb@tinaeb-VirtualBox:~$ which antscommandreg
tinaeb@tinaeb-VirtualBox:~$ antscommandreg.sh
bash: /home/tinaeb/install/bin/antscommandreg.sh: Permission denied
![my script](https://user-images.githubusercontent.com/62328344/78346726-ae79c380-75b4-11ea-961d-9923e378a337.png)
Could you please guide me to fix this error too?
Best,
Tina

**Comment by cookpa** [comment]
You can read about how to make a file executable here

http://linuxcommand.org/lc3_lts0090.php

This is part of a whole tutorial on the command line that I recommend reading if you are new to Linux.

http://linuxcommand.org/lc3_learning_the_shell.php

The ANTs scripts are designed to be executable upon install. For your own scripts, you would make them executable with `chmod` as described in the link.

I don't recommend putting your own scripts in the ${ANTSPATH} directory. You can put them somewhere else and add that directory to PATH, or just execute them directly. That way you won't mix up your ANTs installation and your own code.

**Comment by tina-ebi** [comment]
Dear ANTs experts,
As you told, I have made my file executable by:  chmod +x antsreg.sh   
![basic](https://user-images.githubusercontent.com/62328344/78538106-c2683400-7805-11ea-8157-da6a3573a43f.JPG)
![permssion](https://user-images.githubusercontent.com/62328344/78538113-c5632480-7805-11ea-9b68-b0f6b81bfb2d.JPG)
![run_error1](https://user-images.githubusercontent.com/62328344/78538115-c72ce800-7805-11ea-82c9-929f30afe6c3.JPG)
![run_error2](https://user-images.githubusercontent.com/62328344/78538124-ca27d880-7805-11ea-9f62-ae5a1fa93c68.JPG)
![permssion](https://user-images.githubusercontent.com/62328344/78538128-cb590580-7805-11ea-9d52-afc96fcfa59e.JPG)
![run_error1](https://user-images.githubusercontent.com/62328344/78538132-cc8a3280-7805-11ea-9f62-6b7bd4f338fe.JPG)
![run_error1](https://user-images.githubusercontent.com/62328344/78538152-d3b14080-7805-11ea-825c-40a3f0c5deff.JPG)
![run_error2](https://user-images.githubusercontent.com/62328344/78538155-d4e26d80-7805-11ea-9006-60dc92784273.JPG)
![run_error2](https://user-images.githubusercontent.com/62328344/78538189-e0359900-7805-11ea-9eaf-0398e8d31364.JPG)
![basic](https://user-images.githubusercontent.com/62328344/78538261-f6435980-7805-11ea-8a0b-51090a9f8545.JPG)
![run_error2](https://user-images.githubusercontent.com/62328344/78538258-f5aac300-7805-11ea-8cdc-9c43ccfbb630.JPG)
![run_error2](https://user-images.githubusercontent.com/62328344/78538260-f6435980-7805-11ea-8ed0-7c3d3a0b5185.JPG)
![basic](https://user-images.githubusercontent.com/62328344/78538265-f80d1d00-7805-11ea-9764-25284e456d3f.JPG)
![basic](https://user-images.githubusercontent.com/62328344/78538285-00fdee80-7806-11ea-818a-562903e29946.JPG)
![permssion](https://user-images.githubusercontent.com/62328344/78538287-01968500-7806-11ea-8551-b69fe49c87ab.JPG)
![permssion](https://user-images.githubusercontent.com/62328344/78538291-022f1b80-7806-11ea-96fc-761c5700a1af.JPG)
![basic](https://user-images.githubusercontent.com/62328344/78538295-03604880-7806-11ea-8f07-24f0d7c147b6.JPG)
![run_error1](https://user-images.githubusercontent.com/62328344/78538298-03f8df00-7806-11ea-9d81-faebf878b12e.JPG)
![permssion](https://user-images.githubusercontent.com/62328344/78538299-03f8df00-7806-11ea-8184-99658d5fd420.JPG)
![run_error1](https://user-images.githubusercontent.com/62328344/78538310-078c6600-7806-11ea-996f-bcf839dec738.JPG)

command line.
Then I used two ways to run my script file (attached pictures), but I got error and registration was not done. Is there anyone to tell me what was going on?
Thank you.

**Comment by cookpa** [comment]
It looks like the command is not being parsed correctly. You can't have any whitespace after a line separator "\".

**Comment by tina-ebi** [comment]
Dear Philip,
Thank you so much for your suitable comments. As you had guessed, There were some whitespaces after line separator "\". I have deleted all of them and almost all the errors were fixed. But still, there is only one error about the first line. I have attached my scripts and that error. Could you please help me to solve this error? I should mention that one of my .nii image (OEF_slg.nii in the script) is not structural but totally a quantitative map. 
your help will be greatly appreciated.

![register_code](https://user-images.githubusercontent.com/62328344/78816329-d323d000-79e6-11ea-88c1-492c233f602e.JPG)
![register_error](https://user-images.githubusercontent.com/62328344/78816341-d919b100-79e6-11ea-8d27-4946aaf3971f.JPG)

**Comment by cookpa** [comment]
You need to set ANTSPATH and PATH to include your ANTs install bin dir. 

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#post-installation-set-environment-variables-path-and-antspath

**Comment by tina-ebi** [comment]
Dear Philip,
I set ANTSPATH and PATH like what you mentioned in the previous post.  Although I manually registered Two images, I got an error in antsregistration commands. Any suggestions would be appreciated.
![initial_matrix](https://user-images.githubusercontent.com/62328344/79105722-73327e00-7d86-11ea-8639-cf14e6dd3e5f.JPG)
![script](https://user-images.githubusercontent.com/62328344/79105730-788fc880-7d86-11ea-93a0-75a79f022ebd.JPG)


![register_error2](https://user-images.githubusercontent.com/62328344/79105066-28643680-7d85-11ea-9ee7-3cea5298104e.JPG)
.

**Comment by cookpa** [comment]
Closing this as it has been answered elsewhere. Please don't post the same problem in multiple places.

**Comment by tina-ebi** [comment]
Dear Dr. Philip,Please accept my apologies. I did not know that I do not have such a right to post the same problem in two different places. Thanks for all of your help.Sincerely yours.Tina

    On Monday, April 13, 2020, 07:46:39 PM GMT+4:30, Philip Cook <notifications@github.com> wrote:  
 
 


Closing this as it has been answered elsewhere. Please don't post the same problem in multiple places.
