### ISSUE TITLE
Converting from ITK image to ANTS image and vice versa

### ISSUE THREAD

**Issue by dagap** [ANTsX/ANTs#987]
Is there a way to convert back and forth between an ANTS and the ITK image as defined by SimpleITK. At the moment, I write the image to disk and read it again with ITK or ANTS every time I need to use something ITK or ANTS specific.

ANTS has method to convert from and fro from Nibabel. Is there something similar for ITK or would it be something simple to implement?

**Comment by stnava** [comment]
this is an antspy issue - please raise there.
