### ISSUE TITLE
Registering moving image to a weighted combination of fixed image

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTs#988]
Is it possible to register a moving image to a weighted combination of fixed images 
<img width="890" alt="Screenshot 2020-04-10 at 14 51 31" src="https://user-images.githubusercontent.com/45297533/78992232-18f1ad00-7b3b-11ea-958b-4bbe6304d553.png">

I want to do something like this is it possible to do this using ANTs

**Comment by ntustison** [comment]
Look at ``antsRegistration --help``, specifically the ``--metric`` option.  You can specify multiple metrics and multiple image pairs per registration stage as well as relative weighting.

**Comment by anorak94** [comment]
is it possible to do this through antspy

**Comment by anorak94** [comment]
--metric MI[$t1brain,$template,0.7,32,Regular,0.25] # weight 0.7 on t1
 --metric MI[$t2brain,$T2template,0.3,32,Regular,0.25] # weight 0.3 on t2 ah i guess i use this and then 

in antspy i do 
ccMetric1 = ['MattesMutualInformation', fx_wm, mv_wm, 2, 1 ] , 2 is the weighting to moving image dont know what 1 is 
and then 

`metrics = list()
  metrics.append(ccMetric1)
`
    reg=ants.registration(fx_wm,mv_wm,'SyNOnly', syn_metric='mattes', reg_iterations=( 300,150, 50, 20 ), syn_sampling=2, verbose=1, total_sigma=0.0, multivariate_extras=metrics )

**Comment by anorak94** [comment]
```
--metric CC[$t1brain,$template,1,4] \
--metric MI[$t1brain,$template,1,32,Regular,0.25] \
```

i checked the documentation these are the two i found i want to do something like
`--metric MI[$t1brain,$template,1,32,Regular,0.25] \
`
but im not sure how to do this in antspy for my use case id like to have multiple lines of the above command maybe i can do it in this 
```
metrics = list() 
metrics.append(ccMetric1)
reg=ants.registration(fx_wm,mv_wm,'SyNOnly', syn_metric='mattes', reg_iterations=( 300,150, 50, 20 ), syn_sampling=2, verbose=1, total_sigma=0.0, multivariate_extras=metrics )
```
but im not sure how to go about writing this in antspy  because the multimetric registration example follows this template

`--metric CC[$t1brain,$template,1,4] \
`
while i want to do the other one

**Comment by ntustison** [comment]
ANTsPy is a recent development and it could be that the functionality you require is not (yet) available there.  If not, we would certainly welcome a pull request to make it available to ANTsPy users.  Regardless, this is an ANTsPy issue so please don't cross-post between the two forums.

**Comment by stnava** [comment]
it is available in antspy and I've answered this question ( with examples )
there so not sure why this is continuing on.

brian

**Comment by anorak94** [comment]
Ah okay sorry i get it now. Its available for certain metrics and it follows the same template as the antsregistration call in ants sorry
