### ISSUE TITLE
ITK failed to checkout tag during make build.

### ISSUE THREAD

**Issue by trey325** [ANTsX/ANTs#991]
**When did the error occur?**
[ ] CMake configuration (cmake / ccmake)
[X ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: RedHat
 - OS version: Red Hat Enterprise Linux Server release 7.6 (Maipo)
 - Type of system: HPC Cluster
 
   If you are building inside a virtual machine, container, Cygwin, 
   Windows Subsystem for Linux, or other non-native environment, please 
   let us know and include details of both the virtual Linux and the 
   host OS. 
 
**ANTs version**

Current from repo.

**Build configuration and logs**
Please attach the following files (relative to your build directory)

  - build.log (the terminal output from make)
  - CMakeCache.txt
  - CMakeFiles/CMakeError.log
  - CMakeFiles/CMakeOutput.log

**Additional context**

I have a different version of ITK 4 set up elsewhere on the cluster, but I have removed the ITK_DIR variable, so I doubt it is due to that.
[build.log](https://github.com/ANTsX/ANTs/files/4467121/build.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/4467124/CMakeCache.txt)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/4467125/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/4467126/CMakeOutput.log)

**Comment by cookpa** [comment]
It looks like the SuperBuild could not clone the version of ITK it wants because a local copy already exists with modifications. Try cloning building in a clean directory.

**Comment by gdevenyi** [comment]
Please update the title to reflect the actual issue

**Comment by trey325** [comment]
Thanks for getting back to me so quickly.  @cookpa I thought something similar, but I am already cloning into a new build directory (and deleting it between failed attempts), and I have removed the $ITK_DIR environment variable pointing to the old version I previously installed.

Is there a way to figure out from this output where it is finding some other version of ITK?  Maybe someone else installed it elsewhere on the cluster.

**Comment by trey325** [comment]
If I set USE_SYSTEM_ITK to Off, it complains that it can't find any version of ITK, so I think it must be an issue with the cloned version in the build directory.

**Comment by trey325** [comment]
I believe the issue has to do with cluster settings which are changing the git permissions:

diff --git a/Wrapping/images/templated_pipeline.png.sha512 b/Wrapping/images/templated_pipeline.png.sha512
old mode 100644
new mode 100755

**Comment by cookpa** [comment]
That might be it! As a workaround, maybe this could help:

  git config --global core.fileMode false

This will tell git not to care about file mode changes. Obviously this can cause problems so you might want to turn it back on after you build.

**Comment by trey325** [comment]
@cookpa In a perfect, simple world, that would be the answer.  But in this case, it looks like the script checks out the repo from scratch each time.  If I change the file mode to false between errors, it still has the error.  I have verified that the file mode is changed back to true after the build attempt.  I am working with the cluster staff at my company to get it resolved, but if you know of a workaround in the installation scripts I'd love to hear it.  I have tried a few hacks that have not worked.

**Comment by cookpa** [comment]
In a perfect world, no permissions would be needed.

The script does clone repo each time, but with the `--global` switch to git config, it ought to apply to all git ops. But if that's not working, you could try finding the git checkout command for ITK and changing it to `git checkout --force`, to ignore local mods.

**Comment by trey325** [comment]
I believe it is working now (still building but passed the point of error).  I was incorrectly focusing on hacking the git clone command.  Your suggestion to modify the checkout command was correct.  I added "--force" to the git checkout command in this file:  .../ants/build/ITKv5-prefix/tmp/ITKv5-gitclone.cmake.

execute_process(
  COMMAND "apps/git/install/2.1.2/bin/git" ${git_options} checkout --force 1e708db2f586997e408cfdc2cea5114ae5575892 --
  WORKING_DIRECTORY "../ants/build/ITKv5"
  RESULT_VARIABLE error_code
  )

**Comment by trey325** [comment]
Thanks for your help.  It works on my cluster now.
