### ISSUE TITLE
Registering a floating quantitative map to a T1 image by ANTs?

### ISSUE THREAD

**Issue by tina-ebi** [ANTsX/ANTs#994]
Hi there,
I would like to register a quantitative floating 3D map to a structural T1W template. But at every iteration, it gives so many warnings. finally, the result of registration is not good. Could you please help me to do the correct registration of a quantitative map to T1 image? (I should mention that I could register two structural T1 images very well. But once, I closed terminal page while it was running. After that time, I receive these many WARNINGs during the running of antsregistration.sh command.)
Thanks for any comment.

![error_running2](https://user-images.githubusercontent.com/62328344/79683001-247c5c80-823c-11ea-8272-49e433c20f56.JPG)
![register_result](https://user-images.githubusercontent.com/62328344/79683003-26deb680-823c-11ea-9abf-78eac9e03120.JPG)

**Comment by ntustison** [comment]
Please post the data and the commands that you used to perform your registration.

**Comment by tina-ebi** [comment]
Hi Nick,
I have attached my data and command. But I cannot attached t1template.nii because of its high volume. 
Thanks again.
[command.txt](https://github.com/ANTsX/ANTs/files/4503240/command.txt)
[OEF.zip](https://github.com/ANTsX/ANTs/files/4503364/OEF.zip)
[mask.zip](https://github.com/ANTsX/ANTs/files/4503369/mask.zip)

**Comment by ntustison** [comment]
Because you are a novice user, you should use ``antsRegistrationSyN.sh`` or ``antsRegistrationSyNQuick.sh``.   Try doing

```
$ antsRegistrationSyNQuick.sh -d 3 -f t1template.nii -m OEF.nii -o registered1
```

The ``antsApplyTransforms`` call will be the same.

**Comment by cookpa** [comment]
What is this quantitative image? From which image is it derived?

**Comment by tina-ebi** [comment]
Thank you, Nick. I will try those commands. 
Mr. Philip, my data is Oxygen Extraction Fraction (OEF) map. I've derived it from Quantitative Susceptibility Mapping (QSM) images. By using the magnitude and phase images of SWI sequence, It is possible to obtain QSM.

**Comment by cookpa** [comment]
OK. You want to use an image with similar anatomical features to do the registration. You can then apply the warps to any other image that is in the *same physical space* as the image used for registration. For example,

`antsRegistrationSyNQuick.sh -d 3 -f t1template.nii -m SWI.nii -o swiToTemplate`

IF this registration works, you can do

`antsApplyTransforms -d 3 -r t1template.nii -i OEM.nii -o oemDeformed.nii -t swiToTemplate1Warp.nii.gz -t swiToTemplate0GenericAffine.mat -v 1`

I'm assuming here that SWI is in the same space as OEM.

**Comment by tina-ebi** [comment]
Thank you very much, Nick and Philip. I could register my quantitative images very well. Your recommendation worked very well. I need to do BET for my T1 and SWI-magnitude images for better registration by ANTs.  Is it possible to do brain extraction by ANTs?

**Comment by ntustison** [comment]
Yes, [here](https://github.com/ntustison/antsBrainExtractionExample) is a link to an example that you should try to run before running it on your data.

**Comment by tina-ebi** [comment]
Dear Nick,
According to your recommendation, I tried to run antsBrainExtraction.sh in that link you sent (for 2D data) and fortunately, I could run it. But when I run that command for my 3D data by using 3D IXI templates (T_template0.nii and also T_template2.nii), the command gets to run but several minutes after the onset of running, I receive an error. Also, some files in output appear as well, but none of them is BETbrain. Could you please tell me what something wrong I have done?
Thank you.

![BETcommand](https://user-images.githubusercontent.com/62328344/80135614-a9a59f80-85b5-11ea-98ee-05ef0085f9f8.png)
![output file](https://user-images.githubusercontent.com/62328344/80135641-b32f0780-85b5-11ea-91ee-ad1c755d5797.png)

![ANTS_BET](https://user-images.githubusercontent.com/62328344/80135502-91ce1b80-85b5-11ea-9e0f-21432d1d8bbc.png)

**Comment by ntustison** [comment]
@cookpa would probably know better than I but given the "VirtualBox" environment, my guess is that you ran past memory limits and so your job was killed.

**Comment by dorianps** [comment]
I would guess the same. Try increasing the memory. I am not sure how much
memory a typical image registration needs, but if you can give it 7gb l,
which I used for the full cortical thickness pipeline, it will work for
standard images.

**Comment by gdevenyi** [comment]
I have some benchmarking here https://github.com/gdevenyi/antsRegistration-benchmarking

**Comment by tina-ebi** [comment]
Dear ANTs experts,
I have increased memory of VirtualBox machine up to 7GB and then run antsBrainExtraction.sh again. But I still receive an error without the creating any BETbrain image. That error contains this tens:

 **file /home/tinaeb/Desktop/BETANTs//Template/T_template2ProbabilityMask.nii.gz does not exist .** 
How can I get -m  parameter in antsBrainExtraction.sh command? Also, how can I chose best 3D template for -e parameter?

![output2](https://user-images.githubusercontent.com/62328344/80212531-e5d80f00-864c-11ea-8a68-8f9e63e09749.png)

![BETerror2](https://user-images.githubusercontent.com/62328344/80212488-d062e500-864c-11ea-814c-7f3b2eb0dab0.png)

**Comment by ntustison** [comment]
Where did you get the IXI templates?

**Comment by tina-ebi** [comment]
you have introduced link below in issue #1: 
https://figshare.com/articles/ANTs_ANTsR_Brain_Templates/915436
I got IXI.zip there.

**Comment by ntustison** [comment]
Okay, the missing file should be in there.

**Comment by tina-ebi** [comment]
Dear Nick,
You were right. For fixing the error, I just should have added that missing file to the path of Template. I thank you very much. But brain extraction of my data is not as good as ANTs data. Do you have any suggestion to doing better brain extraction (I mean to remove intervals of brain tissue and skull)?
Thank you very much for your helpful guide.

![command](https://user-images.githubusercontent.com/62328344/80287974-e30f1400-8749-11ea-80e0-0c23b4770c0f.png)

![BrainExtraction](https://user-images.githubusercontent.com/62328344/80287921-93304d00-8749-11ea-9295-b8ad859a0048.png)

**Comment by ntustison** [comment]
Perhaps you should look at FreeSurfer which tends to produce brain masks with tighter boundaries.

**Comment by tina-ebi** [comment]
Dear Philip,
I could solve most of my problems with ANTs experts's help. I could register my OEF map by antsRegistratuinSyNQuick.sh command but not very well. Because when I analyze my map, the standard deviation of ROI is very high. This is because of not being good registration of OEF map and T1-structural brain. I decided to run your suggest in previous posts (first register SWI and T1, then apply transformation matrix on quantitative map). But result got worse. Could you please help me with finding the causes this problem?
Thank you.

![OnlyantsQuick](https://user-images.githubusercontent.com/62328344/80648382-55069680-8a85-11ea-959b-a7f7d8345950.png)

![Quick_plus_antstransform](https://user-images.githubusercontent.com/62328344/80648394-59cb4a80-8a85-11ea-94f7-6d9be287a1ea.png)
