### ISSUE TITLE
Selecting the "right" MALF for antsCorticalThickness

### ISSUE THREAD

**Issue by mwagshul** [ANTsX/ANTs#995]
Hi.

I have a general question, relating to the best way to run antsCorticalThickness (cross-sectional).  We are studying a group of healthy older adults (mean ~ 75 yo), so we have created a MALF using the antsJointLabelFusion on a group of older individuals from the OASIS database.  We have also created a study-specific anatomical template using buildtemplateparallel; the MALF is in this space.  So, I have three questions:
1) Do we need to "Cook" this MALF prior to running antsCorticalThickness, or should we run it straight with these MALF images?
2) Is there an advantage to re-running antsCorticalThickness using the output posterior MALF's as inputs (it wasn't clear whether or not this was the recommended method)?
3) Do you have any experience (or is there any literature) on using the antsCorticalThickness outputs in a voxel-wise analysis, as opposed to using a template (e.g. DKT) warped to the antsCorticalThickness maps to extract regional values? At least from the first pass of running antsCorticalThickness, the cortical thickness maps normalized to the template seemed to have a lot of distortion; I'm not sure how reliable voxel-wise analyses would be with the level of distortion we were seeing.  We could also smooth the cortical thickness maps prior to warping, which we would do in any event for voxel-wise analysis.
 
Any thoughts/suggestions would be most appreciated.

Thanks.  Best wishes for a safe and healthy weekend!

Mark

**Comment by ntustison** [comment]
> Do we need to "Cook" this MALF prior to running antsCorticalThickness, or should we run it straight with these MALF images?

As the developers of the software and based upon our evaluations (both formal and informal), we recommend "cooking" the priors which, as you might be aware, entails some slight additional processing post antsJointLabelFusion.

> Is there an advantage to re-running antsCorticalThickness using the output posterior MALF's as inputs (it wasn't clear whether or not this was the recommended method)?

We don't recommend using the posteriors although we haven't done any testing in that respect.  

Let me just add that there are multiple ways of incorporating tissue priors with one's template and basically that is what is being done here.  But each of these methods yields a different "flavor" of priors and it's not as though any one is universally better than any other.  For example, the SPM priors look very different from typical ANTs-based priors and it's not that SPM or ANTs is better, but more likely that the developers have established certain protocols for what works with their respective softwares.

> Do you have any experience (or is there any literature) on using the antsCorticalThickness outputs in a voxel-wise analysis, as opposed to using a template (e.g. DKT) warped to the antsCorticalThickness maps to extract regional values? At least from the first pass of running antsCorticalThickness, the cortical thickness maps normalized to the template seemed to have a lot of distortion; I'm not sure how reliable voxel-wise analyses would be with the level of distortion we were seeing. We could also smooth the cortical thickness maps prior to warping, which we would do in any event for voxel-wise analysis.

There shouldn't be levels of distortion that prevent voxelwise analyses.  You might want to post visuals illustrating this issue.

**Comment by mwagshul** [comment]
Nick,

Thanks for the quick response.   I still have to re-run the cortical thickness with the cooked priors, but here is a screenshot of the prior (just cortical GM prior) as well as the template cortical thickness, which doesn't look right.  Any thoughts?
![antsCorticalThicknessCookResults-2020Apr30](https://user-images.githubusercontent.com/18051669/80809424-a7cc7500-8b8f-11ea-80ad-a8dff95c6d55.png)

**Comment by ntustison** [comment]
So what doesn't look right to you?  The colors look off on the cortical thickness map  but I don't know if that's the windowing or if there's something actually wrong with the data.  The min/max numbers look reasonable.

Also, I hope you're aware of the issues between FSL and ITK/ANTs in [reading nifti headers](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F).    It's obviously fine if you want to mix packages.  I mention it because it has caused issues for users in the past and for us as well in trying to debug why "ANTs doesn't work."

**Comment by mwagshul** [comment]
The cortical thickness numbers seems to high, I don't think it's a windowing issue.  All of the bright yellow are in the range of 6-9 mm which seems way to high (unless this is expected for the template because of the smoothing inherent in the template creation, although this doesn't appear to be the case from a simple qualitative assessment of the cortical ribbon).
Yes, I am aware and was very careful with this, everything  was converted to FSL space prior to ants processing.

**Comment by ntustison** [comment]
Okay, yeah 6-9 mm is high.  We've run antsCT on our templates and I've never seen anything that looks like that.

**Comment by mwagshul** [comment]
Perhaps this illustrates the issue better.  The Cooked prior is completely "effacing" the sulcus; is this simply from the smoothing of the cooked prior?  Note the estimated thickness in this area is 2-3 mm larger than expected.
![antsCorticalThicknessCookResults2-2020Apr30](https://user-images.githubusercontent.com/18051669/80836653-39a1a580-8bc3-11ea-81b3-f6208e0da096.png)

**Comment by ntustison** [comment]
That's not unexpected and, yes, a result of smoothing.  The diffeomorphic constraint discussed in the original thickness paper is used to address this but it's not perfect.

**Comment by stnava** [comment]
suggests the gradient step is too high.

brian

**Comment by mwagshul** [comment]
Which input parameter would this be (I assume into antsRegistration)?

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/blob/master/Scripts/antsCorticalThickness.sh#L237

**Comment by mwagshul** [comment]
Thanks.
So, I ran it with a gradient step of 0.01 (default = 0.025), but I also dropped the thickness prior to 5 and 8 (I assume mm), and the numbers are now more in line with what I'd expect.  Since I don't have the source code, I can't tell how this prior is used.  But I'm a bit concerned, as the results seem to be too highly dependent on this prior (getting as much as a 10-20% higher numbers is some places with 8 compared to 5).  Any thoughts?

**Comment by ntustison** [comment]
Parameter sensitivity is an issue in any algorithmic pipeline.  There are several parameters upstream which all can have as dramatic an effect on the end results as this one.  Is there a reason why you're particularly concerned about this one?

**Comment by mwagshul** [comment]
No.  The only reason I focused on this in particular was because I noticed it when changing the gradient, and a thickness prior of 10 mm seemed much too big considering what I was expecting.  I did notice that the maximum thickness seems to be only slightly bigger than this prior, which makes me worry about using a prior which is too small.  
One more question - when using a smaller gradient step, should I be increasing the number of iterations?  How do I know that  the algorithm converged?
Thanks again for the advice.

**Comment by ntustison** [comment]
> One more question - when using a smaller gradient step, should I be increasing the number of iterations?  How do I know that the algorithm converged?

Probably.  But you'd have to test it out and see how it works for your data.  We measure convergence by tracking the energy profile and exiting when its gradient goes below a certain threshold or has exhausted the max number of iterations (see the ``--convergence`` option in ``KellyKapowski``).
