### ISSUE TITLE
 No bin directory is generated

### ISSUE THREAD

**Issue by CR-Pan** [ANTsX/ANTs#997]
HI,

I followed the steps to install some problems. Centos7. I cannot use the command sudo.
When I first installed it, I was prompted that there is no ZLIB, and then I installed ZLIB in / home / pwb / zilb /.
ccmake ../ANTs -DZLIB_INCLUDE_DIR = / home / pwb / zilb / include -DZLIB_LIBRARY = / home / pwb / zilb / lib
When I installed it for the second time, after pressing the ‘C’ option, there was no ‘g’ option. I press ‘c’ again. Then the 'g' option appeared. I pressed the ‘g’ option. But there is no bin directory in the antsbin folder.
Then continue to install make -j 4.
I created the bin directory. mkdir bin. Then cp ../ANTs/Scripts/* ./bin/
Then added PAHT. Source .bashrc in .bashrc
But when I use antsBrainExtraction.sh, I get an error.

**Comment by gdevenyi** [comment]
1) use the issue template
2) follow the build instructions at https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS
