### ISSUE TITLE
ANTs versions

### ISSUE THREAD

**Issue by BIG-S2** [ANTsX/ANTs#998]
Dear sir,

I wonder is there any improvement between ANTs version 2.3.1 and the old version 2.2.0? I've tried antscorticalthickness pipeline and antsJointLabelFusion.sh using two different versions and the results seems slightly different. Generally it seems the N4 bias correction file 'antsBrainSegmentation0N4.nii.gz' are different; the final total brain volume for some subjects (2%) are different; some ROIs using joint label fusion can be different (90%~94% correlation between the old and new)
So I wonder is there some significant improvement between those two versions? Thank you very much!

**Comment by ntustison** [comment]
ANTs is a dynamic library that is constantly undergoing changes, bug fixes, etc.  There are also certain algorithms that have a random component (including the segmentation, eg., brain extraction).   So, yes, those changes should explain the differences that you're seeing.
